### ISSUE TITLE
[bitnami/rabbitmq] helm install ignores setting clusterIP when using service type LoadBalancer

### ISSUE THREAD

**Issue by mjattie** [bitnami/charts#10175]
### Name and Version

bitnami/rabbitmq 9.0.6

### What steps will reproduce the bug?

Deploy a new rabbitmq installation
Set service type to LoadBalancer
clusterIP variable is being ignored, even though this is still relevant

### Are you using any custom parameters or values?

relevant values content:
```
service:
  type: LoadBalancer
  clusterIP: 123.123.123
```

### What is the expected behavior?

It is expected, the cluster ip variable is set.

### What do you see instead?

The variable is being ignored

### Additional information

It seems the chart template checks for the type of the service, and if it's not ClusterIP, the clusterIP variable is being ignored.

in the [service template](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/svc.yaml), we check if the type of the service is ClusterIP, and if it's not, we do not set the clusterIP variable:
```  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}```

**Comment by excalq** [comment]
This may (or may not) be related to the blocker that I encountered yesterday when trying to install the `bitnami/rabbitmq` chart into a cluster using Traefik as a frontend proxy, and the service type of `ClusterIP`. If this is a separate issue, or I'm misunderstanding the problem, my apologies.

The chart, with a very minimal setting of values, produces an install with a pod having two services (`rabbitmq`, and `rabbitmq-headless`, both exposing the same ports. `rabbitmq-headless` has no Cluster-IP. I observe that Traefik is attempting to route to the pod's internal IP, rather than the Cluster IP, and is rejecting it since there is more than one service matching the requested management port (15672). I'll continue messing with the ingress config as I may just have something misconfigured, but this looked relevant.

**Comment by excalq** [comment]
Follow-up question: what is the distinction between both services (`rabbitmq`, and `rabbitmq-headless`), as they expose the same ports? Perhaps this could be better documented.

**Comment by excalq** [comment]
Turns out my issue was due to misconfigured DNS. My apologies.

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know! Could you confirm that the issue can be closed then?

**Comment by mjattie** [comment]
@excalq, good thing you found out what the problem was!

@javsalgar, this issue is not related to the issue excalq mentioned. It is about setting the ClusterIP value for the service. This should be possible when using the LoadBalancer service type, but right now it is being ignored. I've already created a pull request since the changes are easy to implement.
