### ISSUE TITLE
[bitnami/mongodb] CPU for mongodb replicas are very high for helm chart 12.0.0

### ISSUE THREAD

**Issue by chary1112004** [bitnami/charts#10316]
### Name and Version

bitnami/mongodb 12.0.0

### What steps will reproduce the bug?

1. Mongodb 4.2.15 with helm chart 7.14.8 and model statefulset is deployed to EKS
- CPU is ~ 25m for 1 replica

2. Mongodb 5.0.8 with helm chart 12.0.0 and model statefulset is deployed to EKS
- CPU is ~ 500 - 900m for 1 replica even checking on mongodb in specific namespace where no one run application (So it more than 20 - 30 times if compare with mongodb 4.2.15)
- Primary is always located in availability zone A
- Secondary is always located in availability zone B
- Both primary & secondary are NOT located in availability zone C

### What do you see instead?

We deploy mongodb to many namespaces and situation is always same as above.

Any clue in determining the cause of this issue would be very much appreciated.

Thank you!

**Comment by aarontavio** [comment]
Hi, I also wanted to add a few bits of information to this ticket. I work in the same project as @chary1112004 so it is the same case. The part related to the availability zones does not concern me that much, it has to do with the pod anti affinity and the fact that our cluster only have 1 node per zone, so if a specific pod cannot be placed in one node because of the pod anti affinity then it will end up de facto in another availability zone.

What we are really concerned about is the CPU usage that went trough the roof (above 600m) even if no users are working with the DB.

After EXECuting into the pods and having a look at the running processes we saw these two `mongosh` commands coming on a regular basis and making a high CPU usage.

```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
17918 1001      20   0  963076 180836  65708 R  47.0   0.6   0:01.41 mongosh --port 27017 --eval db.adminCommand('ping')
17937 1001      20   0  925180 174612  65792 R  40.0   0.5   0:01.20 mongosh --port 27017 --eval db.isMaster().ismaster || db.isMaster().secondary
    1 1001      20   0 2162648 154396  59916 S   1.0   0.5   5:34.37 /opt/bitnami/mongodb/bin/mongod --config=/opt/bitnami/mongodb/conf/mongodb.conf
17911 1001      20   0    3736   2944   2688 S   0.3   0.0   0:00.01 /bin/bash /bitnami/scripts/ping-mongodb.sh
17925 1001      20   0    3868   3140   2788 S   0.3   0.0   0:00.01 /bin/bash /bitnami/scripts/readiness-probe.sh
16971 1001      20   0    4000   3224   2720 S   0.0   0.0   0:00.01 bash
17637 1001      20   0    8124   3400   2812 R   0.0   0.0   0:00.01 top -c
17938 1001      20   0    3084    836    732 S   0.0   0.0   0:00.00 grep -q true
```

After verifying the deployment manifests we saw that the liveness and readyness probes of the mongodb container were custom scripts that issue the mongosh commands. So after disabling them or just decreasing the frequency (from 10 seconds to 4 minutes) we saw the CPU usage go down to normal (10m).

I'm wondering if there is a better way of doing the readiness & liveness probes without consuming that much CPU.

Another thing that might be related is: if I execute the liveness probe inside the pod I get an error, it seems to me that the liveness probe does not work well:
```
I have no name!@mongodb-0:/opt/bitnami/mongodb/bin$ mongosh $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.adminCommand('ping')'
Current Mongosh Log ID: 628644991ef79663976c1540
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.3.1
Using MongoDB:          5.0.8
Using Mongosh:          1.3.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

ReferenceError: ping is not defined
```
After researching a bit in mongodb 5 the correct way of doing ping is: `db.adminCommand({ ping: 1 })` as demonstrated here:
```
I have no name!@mongodb-0:/opt/bitnami/mongodb/bin$ time mongosh --port 27017 --eval 'db.adminCommand({ ping: 1 })'
Current Mongosh Log ID: 628649cc899ae426519e0820
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.3.1
Using MongoDB:          5.0.8
Using Mongosh:          1.3.1

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

{
  ok: 1,
  '$clusterTime': {
    clusterTime: Timestamp({ t: 1652967883, i: 1 }),
    signature: {
      hash: Binary(Buffer.from("2cbd49de3edd3949f867c62dda4697dd674f6f81", "hex"), 0),
      keyId: Long("7097111591790837766")
    }
  },
  operationTime: Timestamp({ t: 1652967883, i: 1 })
}
```

Also the readiness probe seems to be using `db.isMaster()` which for mongodb 5.0.8 should be replaced by `db.hello()` as explained in the [documentation](https://www.mongodb.com/docs/manual/reference/method/db.hello/).

Now, I'm pretty new to mongodb so I'm interested to now if anybody else has the same problem and could solve it without having to disable/reduce the frequency of the health checks.

**Comment by fmulero** [comment]
Thanks a lot for such detailed explanation. 

In MongoDB 5.0, the `mongo` client was deprecated, being new `mongosh` CLI the replacement ([Here](https://www.mongodb.com/docs/manual/reference/program/mongo/) you can find more information).

We are trying to adapt our containers and charts to reduce the impact of this new client but any issue about the performance of `mongosh` should be [reported to MongoDB](https://github.com/mongodb/mongo/wiki/Submit-Bug-Reports)

**Comment by aarontavio** [comment]
Thanks @fmulero yes, after posting my comment I saw also that `mongo` db now is deprecated. I will report the issue in the MongoDB project. Thanks for the link.

**Comment by rmuehlbauer** [comment]
> bug

I've upvoted your issue....hope they are going to fix this soon

**Comment by JD-Robertson** [comment]
I also upvoted the issue. For me this results  in containers that fail to go ready unless the probe timeouts are set very high.

**Comment by ellis2323** [comment]
Hello

With a version 10.31.5, an empty mongodb (architecture: standalone) use 0.020 cpu. After this version (version 11 & 12), the cpu is at minimum 0.240. After reading this thread, I disable readyness et liveness probe: the cpu is now around 0.080. It's better but not expected for an empty service. Not sure, if there's another cpu eater process.

**Comment by ignatiusreza** [comment]
To save someone else time, the first release which replaced `mongo` with `mongosh` is actually `v11.2.0` instead of `v12.0.0`..

The latest release which does not come with high CPU profile are `v11.1.10`..

**Comment by fmulero** [comment]
NOTE: The mongo shell was definitely [removed in MongoDB 6.0](https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed). We are tracking the progress of the ticket in the MongoDB's bug tracker, [MONGOSH-1240](https://jira.mongodb.org/browse/MONGOSH-1240), but it is still under investigation

**Comment by ludat** [comment]
should this be closed?

**Comment by chary1112004** [comment]
@ludat it should not be closed however I could not re-open it. May be @fmulero could re-open it?

**Comment by frabe1579** [comment]
Just for information, using chart version 13.1 with old mongodb v5.0.11, disabling liveness and readiness probes, cpu usage drops from 400m to less than 10m on a idle mongodb instance.

**Comment by Anubiso** [comment]
@fmulero 

Since there is no real progress on [MONGOSH-1240](https://jira.mongodb.org/browse/MONGOSH-1240) and they even wrote that they can't achieve performance like before, maybe we as community should think about not using mongosh for the probes, but for example an alternative executable that executes similar commands. For example a mini-mongodb-probe tool in golang or similar

**Comment by javsalgar** [comment]
Hi,

That sounds interesting. Do you know a project like this currently in the works?

**Comment by SNDK7** [comment]
Since we didn't find an existing project, we started a POC that shows how this could look like, for example:

https://github.com/syndikat7/mongodb-rust-ping

TLS-Options are currently not supported.

**Comment by javsalgar** [comment]
Great!
