### ISSUE TITLE
Can we get a helm chart for setting up saltstack?

### ISSUE THREAD

**Issue by lknite** [bitnami/charts#10318]
### Name and Version

bitnami/saltstack:1.0

### What is the problem this feature will solve?

Kubernetes is the future.  All the benefits of kubernetes, certificates ready from the start, etc ...

### What is the feature you are proposing to solve the problem?

Being that vmware has acquired saltstack, and being the bitnami is associated with vmware, and being that you have all these great patterns within the values.yaml files across all your helm charts, seems natural that you would maintain a helm chart for server-side saltstack.

### What alternatives have you considered?

https://github.com/adammike/saltstack-enterprise

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute to the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container images are not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR (**once analyzed the request and agreed to be included**). If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
