### ISSUE TITLE
[bitnami/etcd] version 8.2.0 present in git repo but not chart repo

### ISSUE THREAD

**Issue by gclawes** [bitnami/charts#10322]
### Name and Version

bitnami/charts 8.2.0

### What steps will reproduce the bug?

1. `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. `helm repo update`
3. `helm search repo --versions bitnami/etcd | head -2`

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

Version 8.2.0 should be the latest available, based on the git repo state here: https://github.com/bitnami/charts/blob/05b1e73601b4e007188929d0efe6456ba2c69c02/bitnami/etcd/Chart.yaml#L27

### What do you see instead?

```
$ helm search repo --versions bitnami/etcd | head -2
NAME            CHART VERSION   APP VERSION     DESCRIPTION
bitnami/etcd    8.1.3           3.5.4           etcd is a distributed key-value store designed ...
```

**Comment by carrodher** [comment]
Please note that, in terms of time, may be a slight difference between the appearance of the code in GitHub and the chart in the registry. This is caused due to the different verifications and tests we internally perform before pushing the Helm charts to the registry.
You can find more info at https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md

Regarding this specific case, note the new version was published some minutes ago:
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo bitnami/etcd
NAME        	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/etcd	8.2.0        	3.5.4      	etcd is a distributed key-value store designed ...
```
