### ISSUE TITLE
RabbitMQ port ends up with stream or task as 0

### ISSUE THREAD

**Issue by corneil** [bitnami/charts#10446]
### Name and Version

bitnami/spring-cloud-dataflow

### What steps will reproduce the bug?

Deploy scdf in minikube
Register a stream app
launch the app.
describe the pod and then `SPRING_RABBITMQ_PORT=0`

### Are you using any custom parameters or values?

No

### What is the expected behavior?

RabbitMQ port should match the value in rabbitmq deployment.
`SPRING_RABBITMQ_PORT=5672`

### What do you see instead?

`SPRING_RABBITMQ_PORT=0`

**Comment by joancafom** [comment]
Hi @corneil 

Thanks so much for reporting, I have been able to reproduce the issue on my side. This might be related to some wrong reference to one of the parameters in the `values.yaml` file, most likely caused by recent changes in the RabbitMQ chart.

I see that you already created a PR addressing the issue, so let's move the conversation there.
