### ISSUE TITLE
restore a db snapshot

### ISSUE THREAD

**Issue by herbalizer404** [bitnami/charts#1047]
Is there any process to restore a backup previously made with etcdctl snpashot save file.db ?

**Comment by javsalgar** [comment]
I am afraid we do not have a documented process currently, though I think it would be interesting to allow the use of init scripts for that matter. My advice would be to use the etcd command line tools inside the container.

https://stackoverflow.com/questions/50825489/how-can-i-restore-etcd-cluster-from-snapshot-in-docker-image-on-coreos

**Comment by krwrang** [comment]
I'd really like some insight on how the manual restoring could work.

As far as I can tell, even if I re-create the data directories from snapshots inside the containers and then let the containers restart to actually use that data, the command ran by chart would notice there is data present and then attempt to join nodes to the cluster (to node 0). This would then fail when doing `etcdctl member add` since in a HA environment a single etcd node does not answer to etcdctl (`exceeded header timeout`).

**Comment by juan131** [comment]
Hi @krwrang 

Could you provide the steps (step-by-step if possible) to reproduce the issue on my side? I'd like to understand the issue and be able to debug it.

**Comment by krwrang** [comment]
Hi @juan131 

I would prefer steps on how to actually get it to work, but here is what I have tried:

- 5 node etcd cluster with ceph persistence
- If I attempt to rely on the persisted data and just start the nodes, node 0 starts with pre-existing data, then latter nodes will fail in https://github.com/bitnami/charts/blob/411566bd7ead16a6f2f98705eb29a3847b47350a/bitnami/etcd/templates/statefulset.yaml#L124 due to not being able to connect to node 0 (exceeded header timeout)
- If I try and use a sidecar to mount the ceph volume, remove the data directory and restore from a snapshot, I then run into the same problem as I again have pre-existing data directory and cannot connect to the initial node

**Comment by juan131** [comment]
In this [guide](https://coreos.com/etcd/docs/latest/v2/admin_guide.html#restoring-a-backup) they recommend you to initialise the **etcd** cluster with the option `-force-new-cluster` so it initializes a new, single-member cluster with the default advertised peer URLs, but preserve the entire contents of the etcd data store.

We could add an env. variable to indicate the "extra flags" to append to the **etcd** command. Then, you could start a etcd cluster with a single node and the flag mentioned above. 

Once, you have a running node, you can modify the advertise client URLs and scale the cluster so other members can join it.
