### ISSUE TITLE
Update Strategy for Redis chart

### ISSUE THREAD

**Issue by florianschendel** [bitnami/charts#10481]
### Name and Version

bitnami/redis

### What steps will reproduce the bug?

We use Netbox with the HelmChart from https://github.com/bootc

This Chart uses the bitnami Redis Chart. In the netbox helm chart we set a different Update Strategy for Redis.
Unfortunaley the Redis Chart always set the UpdateStrategy to "RollingUpdate" because you defined in your yaml
```rollingupdate: {}```

### What is the expected behavior?

The update strategy should be configurable.

### What do you see instead?

I see on OpenShift in the UpdateStrategy: RollingUpdate and my custom value is only attached.

**Comment by rafariossaa** [comment]
Hi,
  The parameter to set the up the update strategy are `master.updateStrategy.type` and `replica.updateStrategy.type`. 
  In any case, when setting the redis pameters in netbox you will be using `redis._PARAMETER_NAME`, so it should be something like: `redis.master.updateStrategy.type`.
  I am sorry, I am not very sure about this issue. Could you elaborate a bit more ?

**Comment by burkhat** [comment]
Hello,
I'm a colleague from Florian and I think it is following problem.
We have set the entry in our to: 
master:
  updateStrategy:
    type: OnDelete

In the Statefulset, we can see the that the updateStrategy has changed to "OnDelete", but we got an error because the helmchart also wants to add the entry "rollingUpdate {}" to the updateStrategy and this isn't allowed for "OnDelete".

I think the problem is that in the default value.yaml the entry "rollingUpdate {}" is set for the updateStrategy.
https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml line 286

**Comment by rafariossaa** [comment]
Hi,
  You could try to set `master.updateStrategy.rollingUpdate=null` . That should remove the entry in the subchart. 
https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

**Comment by burkhat** [comment]
Thanks for your answer, it is working. 
You can close the case.
Thanks for your help

**Comment by florianschendel** [comment]
Thanks for you support! its working
