### ISSUE TITLE
Chart repository unreachable

### ISSUE THREAD

**Issue by hugowangler** [bitnami/charts#10535]
### Name and Version

bitnami

### What steps will reproduce the bug?

1. run `helm repo add bitnami https://charts.bitnami.com/bitnami`

### What do you see instead?

Running the above command gives the following error 

```Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR; received from peer```

### Additional information

If you visit the [URL](https://charts.bitnami.com/bitnami) you get an access denied error.

**Comment by potiuk** [comment]
We experience very similar problems in Apache Airflow CI. They started to occur more and more frequently and we are discussing vendoring in the chart we need or copying it to a github repository as described here:

https://github.com/apache/airflow/issues/24037#issuecomment-1143980447

Those itnernal errors are causing our CI failuire and our users At Apache Airflow get a lot of false negatives as results of their Pull Requests. It's highly, highly annoying. 

Example stack trace: https://github.com/apache/airflow/runs/6666449965?check_suite_focus=true#step:9:314

```
  Save error occurred:  could not find : chart postgresql not found in https://charts.bitnami.com/bitnami: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR
  Deleting newly downloaded charts, restoring pre-update state
  Error: could not find : chart postgresql not found in https://charts.bitnami.com/bitnami: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR
  Dumping logs from KinD
  kind --name airflow-python-3.7-v1.24.0 export logs /tmp/kind_logs_2022-05-31_2413420940_tests-kubernetes
  Exporting logs for cluster "airflow-python-3.7-v1.24.0" to:
  /tmp/kind_logs_2022-05-31_2413420940_tests-kubernetes
```

What we do is we use the latest version of our chart from the sources:

https://github.com/apache/airflow/tree/main/chart

and run `helm dependency update` . Since we have bitnami's postgresql chart as dependency https://github.com/apache/airflow/blob/d86ae090350de97e385ca4aaf128235f4c21f158/chart/Chart.yaml#L35  our CI will fail if such internal error is received.

Dear Bitnami support -  Is there a stability workaround that we could use if bitnami's flakiness is not solved? Or the only solution is to copy the chart elsewhere if we want some stability  ?

**Comment by carrodher** [comment]
Thanks for letting us know, there is already an existing issue for this topic, see https://github.com/bitnami/charts/issues/8433.

We are looking into this issue. In order to avoid duplication and keep the efforts in a single place, I will close this issue in favor of the existing one.
