### ISSUE TITLE
Old charts not available

### ISSUE THREAD

**Issue by amateope** [bitnami/charts#10545]
### Name and Version

postgresql-ha, nginx-ingress-controller and keycloak

### What steps will reproduce the bug?

Old charts disappeared from the helm repository for:
- postgresql-ha
- nginx-ingress-controller
- keycloak

### What do you see instead?

Newer versions

**Comment by edgarkz** [comment]
Same here with rabbitmq (8.20.1) and redis charts 14.x

**Comment by thisislawatts** [comment]
Please see https://github.com/bitnami/charts/issues/10539

**Comment by kumarpmd** [comment]
we are facing issues pulling chart versions - 
- external-dns v6.0.2 
- metrics-server v5.10.12

**Comment by adawalli** [comment]
Similar issue with

- Rabbit MQ: 9.1.4
- Redis: 14.0.2

**Comment by danieleh11** [comment]
Similar issue with
kafka: 12.2.0
postgresql :10.3.15

**Comment by carrodher** [comment]
**All the previous Chart versions still exist and they are available as usual, please check [this post](https://github.com/bitnami/charts/issues/10539)**. This change only affects the `index.yaml` listing.

This change can potentially affect users or CI/CDs trying to package charts (`helm package` or `helm dep update`). **In any case regular installations or deployments**.

Apart from that, in the above-mentioned issue, you can see a workaround to continue using older versions as part of your Helm charts:

```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
or
```diff
-  repository: https://charts.bitnami.com/bitnami
+  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
```

Being said that, the recommendation is to use recent versions of the Helm charts in order to keep the deployments secure and up-to-date.

**Comment by adawalli** [comment]
> **All the previous Chart versions still exist and they are available as usual, please check [this post](https://github.com/bitnami/charts/issues/10539)**. This change only affects the `index.yaml` listing.
> 
> This change can potentially affect users or CI/CDs trying to package charts (`helm package` or `helm dep update`). **In any case regular installations or deployments**.
> 
> Apart from that, in the above-mentioned issue, you can see a workaround to continue using older versions as part of your Helm charts:
> 
> ```
> $ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
> "bitnami-pre-2022" has been added to your repositories
> ```
> 
> or
> 
> ```diff
> -  repository: https://charts.bitnami.com/bitnami
> +  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
> ```
> 
> Being said that, the recommendation is to use recent versions of the Helm charts in order to keep the deployments secure and up-to-date.

To be honest, this seems less painful
```
helm repo remove bitnami
helm repo add bitnami  https://raw.githubusercontent.com/bitnami/charts/index/bitnami
```

**Comment by Pokom** [comment]
We're using `helmfile` to manage deployments for a number of our charts. I've followed the steps to use the repo with "older" versions and now it appears that helm is not recognizing the existing deployments. For instance, we already have `external-dns` deployed, and now the diff wants to reinstall every component. 

Has anyone else seen this and can advise?

**Comment by adilreza** [comment]
Is there any way to use the older chart version?? if any backup, it will be helpful I need postgresql 8.6*

**Comment by adawalli** [comment]
> Is there any way to use the older chart version?? if any backup, it will be helpful I need postgresql 8.6*

```
helm repo remove bitnami
helm repo add bitnami  https://raw.githubusercontent.com/bitnami/charts/index/bitnami
```

**Comment by adilreza** [comment]
I am searching for postgresql, but no luck!!

**Comment by nodesocket** [comment]
What's going on? Just today started getting:

```
Error: can't get a valid version for repositories postgresql. Try changing the version constraint in Chart.yaml
```

Chart.yaml is:

```
  - name: postgresql
    version: 10.3.18
    repository: "@bitnami"
```

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client.

The `index.yaml` is stored in this repository under the [_index_ branch](https://github.com/bitnami/charts/tree/index/bitnami), users should be able to use any commit in that branch to add a previous version of the `index.yaml`.

- Manually using `helm repo add`
```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
- When used as a dependency in _Chart.yaml_:
```diff
  - name: postgresql
    version: 8.1.0
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: postgresql.enabled
```

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the above mentioned GH issue, closing the other ones.

**Comment by Anticom** [comment]
What has happened to the pre-2022 work-arround? I'm no longer able to fetch any updates from that repo and opening the [index.yaml](https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami/index.yaml) only yields a 404.

Are the old versions of bitnami charts available via the regular helm repo again?

**Comment by carrodher** [comment]
The branch containing the old charts is [archive-full-index](https://github.com/bitnami/charts/tree/archive-full-index) which is updated by [this GH action](https://github.com/bitnami/charts/actions/workflows/archive-full-index.yaml). It contains the whole history (no truncation) and it is served directly on GitHub.

[Here](https://github.com/bitnami/charts/issues/10833) you can find more info.
