### ISSUE TITLE
Old chart version deleted?

### ISSUE THREAD

**Issue by KraMorK** [bitnami/charts#10542]
### Name and Version

bitnami/redis:10.7.11

### What steps will reproduce the bug?

```console
$ helm search repo bitnami/redis --version 10
No results found
```
same problem with rabbitmq, no versions below 8.24.13
is this a temporary glitch, or a planned deletion? where can I download the old charts?

### What is the expected behavior?

helm chart avalible

### What do you see instead?

No results found

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client

**Comment by hatharom** [comment]
This archive repo doesn't exist

**Comment by isaaguilar** [comment]
Did eb5f9a9513d987b519f0ecd732e7031241c50328 disappear? Does anyone know of some archive with the old charts?
