### ISSUE TITLE
Error: chart "etcd" version "6.1.3" not found in https://charts.bitnami.com/bitnami repository

### ISSUE THREAD

**Issue by chsukhija** [bitnami/charts#10564]
### Name and Version

bitnami/etcd 6.1.3

### What steps will reproduce the bug?

helm upgrade etcd etcd --install --repo https://charts.bitnami.com/bitnami --version "6.1.3" --namespace etcd --set persistence.storageClass=astra -f ./values.yaml

### Are you using any custom parameters or values?

Yes 

### What is the expected behavior?

Chart should install

### What do you see instead?

Error: chart "etcd" version "6.1.3" not found in https://charts.bitnami.com/bitnami repository

**Comment by GianniGiglio** [comment]
Having the same issue with postgresql chart.
Since yesterday we had issue's feching version 10.3.11. It was gone from the bitnami repository
Upgraded this morning to version 10.16.2 but now that one is gone.

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client
