### ISSUE TITLE
mongodb v10.20.5 removed without warning

### ISSUE THREAD

**Issue by dave-yotta** [bitnami/charts#10586]
### Name and Version

bitnami/mongodb 10.20.5

### What steps will reproduce the bug?

in chart.yaml:
```
dependencies:
  - name: mongodb
    version: 10.20.5
    repository: https://charts.bitnami.com/bitnami
```

run `helm dependency update`

### What do you see instead?
```
Save error occurred:  could not find : chart mongodb not found in https://charts.bitnami.com/bitnami: looks like "[https://charts.bitnami.com/bitnami"](https://charts.bitnami.com/bitnami%22) is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR; received from peer
```

Edit: Most recently
```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Error: can't get a valid version for repositories mongodb. Try changing the version constraint in Chart.yaml
```

### Additional information

Our pipleline started failing with no changes to our charts over the weekend.  Is there a breaking change in the chart repo over here? Checking for any helm client breaking changes now...

**Comment by dave-yotta** [comment]
Looks like you've removed a version?  Was this a mistake, or is there documentation on how long a version is kept for? we are pinned....

**Comment by rafariossaa** [comment]
Hi,
  Could you take a look to this issue ? https://github.com/bitnami/charts/issues/10539

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client.

The `index.yaml` is stored in this repository under the [_index_ branch](https://github.com/bitnami/charts/tree/index/bitnami), users should be able to use any commit in that branch to add a previous version of the `index.yaml`.

- Manually using `helm repo add`
```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
- When used as a dependency in _Chart.yaml_:
```diff
  - name: postgresql
    version: 8.1.0
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: postgresql.enabled
```

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the above mentioned GH issue, closing the other ones.

**Comment by dave-yotta** [comment]
looks like https://github.com/bitnami/charts/commit/d5f82623e6c437d90d0368336314dfe257f9d9e1 🤔

**Comment by dave-yotta** [comment]
ok just need the latest chart listing like you've posted.  got it.
