### ISSUE TITLE
How to access bitnami/external-dns old version 4.11.0

### ISSUE THREAD

**Issue by vsana1** [bitnami/charts#10581]
### Name and Version

bitnami/external-dns old version 4.11.0

### What steps will reproduce the bug?

Looks like Bitnami has removed all Helm chart versions older than six months from their repository

we are using bitnami/external-dns 4.11.0 and this is not available now to download and our playbooks are failing. Is there any work around to keep using this in our playbooks until we upgrade ? if so what is the best way to use it. 

Would you please help me to understand when you get a chance.

Thanks

### What do you see instead?

Just want to use this until we upgrade to stable version

**Comment by rafariossaa** [comment]
Hi,
  We posted information regarding this in [this pinned issue](https://github.com/bitnami/charts/issues/10539) ?

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client.

The `index.yaml` is stored in this repository under the [_index_ branch](https://github.com/bitnami/charts/tree/index/bitnami), users should be able to use any commit in that branch to add a previous version of the `index.yaml`.

- Manually using `helm repo add`
```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
- When used as a dependency in _Chart.yaml_:
```diff
  - name: postgresql
    version: 8.1.0
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: postgresql.enabled
```

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the above mentioned GH issue, closing the other ones.

**Comment by vsana1** [comment]
My pod is failing with "Back-off restarting failed container"
I am checking all the options, would you please confirm 

I am using this "helm repo add bitnami-legacy-6012022 https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami" 
Is this repo still valid ?
