### ISSUE TITLE
Older zookeeper charts removed from the repository (versions prior to 7.6.0)

### ISSUE THREAD

**Issue by igable** [bitnami/charts#10599]
### Name and Version

bitnami/zookeep 5.5.1

### What steps will reproduce the bug?

Older versions of the zookeeper chart were removed in the last few days  from the bitnami helm repo https://charts.bitnami.com/bitnami (We guess Friday June 3). We [depend](https://github.com/stardog-union/helm-charts/tree/develop/charts/stardog) on zookeeper chart version 5.5.1. Would it be possible to restore these older versions to the repository?

I'm sure the advise is going to be to upgrade, however we would would very appreciate the restoration of those older version we we can undertake that in an orderly fashion.

Thanks very much for maintaining these very useful charts.

### Are you using any custom parameters or values?

no

### What do you see instead?

Older chart versions removed.

**Comment by joshlopes** [comment]
Not sure if related but also got a "INSTALLATION FAILED: failed to download "bitnami/mysql" at version "7.1.0"" today... this is really annoying

**Comment by joshlopes** [comment]
Looking at https://charts.bitnami.com/ I don't see this version really, seems for mysql only a few 8.0.x

**Comment by beltran-rubo** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10539 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client.

The `index.yaml` is stored in this repository under the [_index_ branch](https://github.com/bitnami/charts/tree/index/bitnami), users should be able to use any commit in that branch to add a previous version of the `index.yaml`.

- Manually using `helm repo add`
```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
- When used as a dependency in _Chart.yaml_:
```diff
  - name: postgresql
    version: 8.1.0
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: postgresql.enabled
```

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the above mentioned GH issue, closing the other ones.
