### ISSUE TITLE
Where did older mariadb-galera charts go?

### ISSUE THREAD

**Issue by ljohnston** [bitnami/charts#10842]
### Name and Version

bitnami/mariadb-galera

### What steps will reproduce the bug?

Looks like the oldest release of the mariadb-galera chart in the bitnami helm repo is 6.2.0.

I'm trying to upgrade a mariadb-galera deployment that was done with chart version 5.13.4. It would sure be nice to have access to that chart. Does it exist anywhere?

I'm running the following:
`helm fetch --version 5.13.4 bitnami/mariadb-galera`

And getting the following:
`Error: chart "mariadb-galera" matching 5.13.4 not found in bitnami index. (try 'helm repo update'): no chart version found for mariadb-galera-5.13.4`

### What is the expected behavior?

The chart should be available.

### What do you see instead?

`Error: chart "mariadb-galera" matching 5.13.4 not found in bitnami index. (try 'helm repo update'): no chart version found for mariadb-galera-5.13.4`

**Comment by ljohnston** [comment]
Never mind, thanks. Found this:  https://github.com/bitnami/charts/issues/10833

**Comment by carrodher** [comment]
It is due to a recent change in the retention policy, the Helm charts were not deleted but the `index.yaml` was updated to keep Helm charts from the latest 6 months.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10833 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client and dependent Helm charts.

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the [already existing GH issue](https://github.com/bitnami/charts/issues/10539), closing the other ones.
