### ISSUE TITLE
Rabbitmq metrics enabled but not all labels available

### ISSUE THREAD

**Issue by FranAguiar** [bitnami/charts#10877]
### Name and Version

bitnami/rabbitmq (version 10.1.9)

### What steps will reproduce the bug?

I installed the chart and tried to activate the metrics to monitor the queues, with the below yaml. 
Then I get metrics in prometheus, but I don't have the label "queue", neither "vhost". Probably I have to enable something else, but I'm not sure what or where.

I cannot filter by queue or vost:
`rabbitmq_queue_messages_ready{vhost="/",queue="myqueue"}
`

Any idea?? Thanks

### Are you using any custom parameters or values?

```
metrics:
  enabled:
    value: true
  serviceMonitor:
    enabled: true
```

### What is the expected behavior?

I expect to have the queue label, but is no there. Same for vhost
```
rabbitmq_queue_messages_ready{queue="myqueue", container="rabbitmq", endpoint="metrics", instance="10.168.2.6:9419", job="rabbitmq", namespace="default", pod="rabbitmq-0", service="rabbitmq"}

```

### What do you see instead?

No queue label in my output
```
rabbitmq_queue_messages_ready{container="rabbitmq", endpoint="metrics", instance="10.168.2.6:9419", job="rabbitmq", namespace="default", pod="rabbitmq-0", service="rabbitmq"}
```

**Comment by rafariossaa** [comment]
Hi,
  When enabling metrics the chart enables the `rabbitmq_prometheus` plugin. 
  You can check the metrics exported by getting into the pod and running: `curl http://127.0.0.1:9419/metrics`. If the metrics you need aren`t there, I would suggest you to report it in rabbitmq forums because there is nothing that can be done in the chart side.
