### ISSUE TITLE
[thanos] Store Gateway HPA does not work with sharding enabled

### ISSUE THREAD

**Issue by aslafy-z** [bitnami/charts#11305]
### Name and Version

bitnami/thanos 11.1.0

### What steps will reproduce the bug?

Install the chart with the given values.

### Are you using any custom parameters or values?
```yaml
storegateway:
  autoscaling:
    enabled: true
  sharded
    enabled: true
```

### What is the expected behavior?

There should be one HPA per shard. 

### What do you see instead?

```shell
$ kubectl get events
115s        Warning   FailedGetScale                 horizontalpodautoscaler/thanos-storegateway                     statefulsets.apps "thanos-storegateway" not found

$ kubectl get hpa
thanos-storegateway     StatefulSet/thanos-storegateway    <unknown>/80%   3         6         0          3h22m

$ kubectl get sts
thanos-storegateway-0                             1/1     3h22m
```

**Comment by FraPazGal** [comment]
Hi @aslafy-z,

You are right, our HorizontalPodAutoscaler's target is the statefulset created when sharding is disabled, so it won't apply otherwise. For it to work, we'll need logic similar to the one used in `statefulset-sharded.yaml`:

https://github.com/bitnami/charts/blob/b5fccfb8d326f53b3836da6a7e6df908efcf4b0e/bitnami/thanos/templates/storegateway/statefulset-sharded.yaml#L14

Would you be interested in adding this feature to the chart? We'll be glad to review your contribution and add it to `bitnami/thanos`.

**Comment by aslafy-z** [comment]
Not stale
