### ISSUE TITLE
Mongodb replicaset secondary not joining primary

### ISSUE THREAD

**Issue by ppathard** [bitnami/charts#11306]
### Name and Version

bitnami/mongodb:10.26.4

### What steps will reproduce the bug?

K8S: 1.24.3
CoreDNS: 1.8.6
Calico: 3.23.1

helm install the chart with below provided values.yaml file.

### Are you using any custom parameters or values?

[values.txt](https://github.com/bitnami/charts/files/9164661/values.txt)

### What is the expected behavior?

All 3 mongodb coming up and replicaset is healthy

### What do you see instead?

[pod2.txt](https://github.com/bitnami/charts/files/9164668/pod2.txt)

```
ntv-mongodb-0                               2/2     Running            0                 34m
ntv-mongodb-1                               2/2     Running            0                 34m
ntv-mongodb-2                               1/2     Running            0                 34m
```

Attaching logs of pod2 with debug enabled.

after checking the code pod2 is waiting at below code
```
  result=$(
        mongodb_execute "$user" "$password" "admin" "$host" "$MONGODB_INITIAL_PRIMARY_PORT_NUMBER" <<EOF
db.getUsers()
EOF
```

This setup is tls enabled.

**Comment by rafariossaa** [comment]
Hi,
  Could you try with the default values.yaml and just enabling the metrics ? I would like to discard if it is because of your enviroment or if it is related to the parameters.

**Comment by nainapatidar** [comment]
Thanks for checking this thread. I would like to provide more details here:

We have one more environment where all the MongoDB pods are working perfectly fine. But only on this environment we are seeing issues with MongoDB replica's. We tried to compare the configuration of both the environments but it was all same(CNI, CoreDNS etc.).

On this environment, MongoDB is consistently failing to make the 3rd pod up, though the other 2 pods are coming up quickly.
I need your help to drill down the cause why it is getting stuck at a particular step.

Can you please provide any suggestions/troubleshooting steps that can be tried out to identify the root cause will help a lot.

**Comment by rafariossaa** [comment]
That's weird.
My guess is that could be network related. 
Maybe you can enter that container and try to check if it could reach other pod's ports. For this, you can increase the time of liveness and readiness probes. If that doesn't work, maybe you can try using `diagnosticMode.enabled`, in this case you need to check the logic in the container and run it manually.
