### ISSUE TITLE
[bitnami/redis-cluster] Rerouting is not happening in redis-cluster in gcp

### ISSUE THREAD

**Issue by abhishekgupta2205** [bitnami/charts#11325]
### Name and Version

bitnami/redis-cluster , 7.1.0

### What steps will reproduce the bug?

helm install redis redis-cluster

### Are you using any custom parameters or values?

--cluster.externalaccess.enabled=true
service.type=nodeport

### What is the expected behavior?

I am able to connect to redis through redis-cli 

### What do you see instead?

I am able to connect to redis through redis-cli but when settting a key and rerouting is happneing then key is not set. it is gone in processing state.

### Additional information

i am using gcp cluster .
![Screenshot from 2022-07-25 00-38-17](https://user-images.githubusercontent.com/68244292/180662213-4abd6390-6229-470e-87a2-4d5a4caba2d4.png)

**Comment by fmulero** [comment]
Thanks @abhishekgupta2205

I think this issue is also related to your issues #11336 and #11322. If you have related issues, please mention them when you are creating the issue.

I am not sure but I think redis is not able to advertise the external IP when it is exposed through LoadBalancer or NodePort service (#10808). Please correct me if that's not the cause of your problem

**Comment by fmulero** [comment]
Please see this [comment](https://github.com/bitnami/charts/issues/11336#issuecomment-1195751689)
