### ISSUE TITLE
My bitnami localhost/wordpress account is not responding

### ISSUE THREAD

**Issue by nestechs** [bitnami/charts#11687]
### Name and Version

Bitnami/WordPress/6.0.1

### What steps will reproduce the bug?

Please how can i resolve this issue, I started using bitnami for my windows 3days ago to create my website but since my windows upgrade yesterday evening.. I cannot access my WordPress acct till now.. Telling me unable to reach website. Please how can i resolve this?

### Are you using any custom parameters or values?

No

### What is the expected behavior?

This site cannot be reached.

### What do you see instead?

This site cannot be reached.

### Additional information

Please how can i resolve this issue, I started using bitnami for my windows 3days ago to create my website but since my windows upgrade yesterday evening.. I cannot access my WordPress acct till now.. Telling me unable to reach website. Please how can i resolve this?

**Comment by nestechs** [comment]
Hello

**Comment by fmulero** [comment]
Hi @nestechs 

Thanks for using our packages. In order to do a proper triage of your issue we are going to need more information:
* What kind of package are you using?: Virtual Machines, Container image or Helm chart
* How did you installed the package? Did you set any custom parameter?
* Could you provide the logs from the asset?

These are examples of issues with enough information to diagnose them and find a solution:
* https://github.com/bitnami/charts/issues/11448
* https://github.com/bitnami/charts/issues/11210
* https://github.com/bitnami/charts/issues/11134
