### ISSUE TITLE
[bitnami/mongodb] Mongodb custom cert not working

### ISSUE THREAD

**Issue by ginofrid** [bitnami/charts#11966]
### Name and Version

bitnami/mongodb 13.0.2

### What steps will reproduce the bug?

In K8S (version 1.23) using most default chart parameters and supplying my own caKey and caCert. 

### Are you using any custom parameters or values?

```
--set architecture=replicaset,auth.replicaSetKey=***,replicaCount=1
--set auth.enabled=true,auth.rootPassword=***,auth.usernames[0]=mongo,auth.passwords[0]=***,auth.databases[0]=www 
--set tls.enabled=true,tls.autoGenerated=false
--set tls.caKey='***'    base64 encoded key
--set tls.caCert='***'   base64 encoded cert
```

### What do you see instead?

```console
$ kubectl describe pod -n mongo3 mongodb-0
 ...
  Warning       Unhealthy  51s (x63 over 42m)    kubelet  (combined from similar events): Liveness probe failed: Current Mongosh Log ID:  6302781048ebfa82bc2bc65b
Connecting to:             mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2Fcerts%2Fmongodb.pem&tlsCAFile=%2Fcerts%2Fmongodb-ca-cert&appName=mongosh+1.5.4
MongoServerSelectionError: key usage does not include certificate signing
```

**Comment by migruiz4** [comment]
Hi @ginofrid,

Could you please share more details about how you generated your CA certificate and key?

I couldn't reproduce the issue using the following commands:
```
$ openssl genrsa -out ca.key 4096
$ openssl req -new -x509 -days 1826 -key ca.key -out ca.crt
$ base64 ca.key
$ base64 ca.crt
```

**Comment by noelashford** [comment]
I too hit this - My goal was to use lets encrypt certs - I did it as follows. 

https://github.com/bitnami/bitnami-docker-mongodb/issues/289

I understand this poster had no luck but my goal is not self signed certs, its lets encrypt which I suspect this was too, so why is this not working ? 

could it be that you need to append the CA of lets encrypt ? 

https://gist.github.com/novemberborn/4eb91b0d166c27c2fcd4

**Comment by ginofrid** [comment]
My goal is to use letsencrypt certs for front end communication.  what options should I be passing to cert bot to generate the cert I can use with bitnami/mongodb helm chart and what options I should use to pass it in the helm chart?

**Comment by migruiz4** [comment]
Hi @ginofrid,

I was asking about the method used to generate the certificates because that would be the cause of the error `MongoServerSelectionError: key usage does not include certificate signing`.

I think the current method included in the `bitnami/mongodb` chart to implement TLS is not compatible with Letsencript and a refactor of the TLS configuration and a new major would be needed to support it.

That is because the current method consists in providing a CA key and certificate, which then is used by the chart to generate a certificate for each MongoDB node.

To be able to use Letsencrypt, a different method would be required, where the users provide the certificate for each individual MongoDB node and the CA public cert used to sign them. This is the method used in other charts which are compatible with Letsencrypt, e.g bitnami/kafka, bitnami/keycloak, bitnami/geode. Or other cases, like bitnami/elasticsearch, where nodes deployed with the same statefulset share a certificate with a common wildcard certificate.

I have created an internal task to evaluate the TLS refactor and implement it, but I can not provide an ETA for it.

If you'd like to contribute, feel free to send a PR and we will be glad to review it and help with anything needed.
