### ISSUE TITLE
Enable Redis Components via Helm Chart: Redis JSON and Redis Search

### ISSUE THREAD

**Issue by darthmolen** [bitnami/charts#12287]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

Currently, the helm chart has no capabilities to deploy Redis with components installed, with 2 of the most popular being Redis Search and Redis Json.

### What is the feature you are proposing to solve the problem?

 Please enable these optional components in the deployment via helm chart parameters.

**Comment by carrodher** [comment]
Thanks for the suggestion, I just created an internal task to evaluate this feature. Due to the team capacity and other priorities we are working on, I can't provide an ETA for this evaluation. Because of that, I'm moving this issue to `On hold` and we'll update it once we have more news.

As usual, the Bitnami team will be happy to review any contribution via PRs and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. After analyzing internally our priorities and due to other issues/initiatives we are working on, we didn't find the bandwidth to implement this feature.

Being said that, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by palmtown** [comment]
Hello Community,

There's is an example script at https://medium.com/@gerkElznik/deploy-redis-stack-using-bitnamis-helm-chart-d8339453352c that shows how to use Bitnami and redis-stack to enable modules.  I haven't given it a try, however, thought it would be worth adding in this thread.

**Comment by thexiang** [comment]
> Hello Community,
> 
> There's is an example script at https://medium.com/@gerkElznik/deploy-redis-stack-using-bitnamis-helm-chart-d8339453352c that shows how to use Bitnami and redis-stack to enable modules. I haven't given it a try, however, thought it would be worth adding in this thread.

Thanks for sharing! It worked for me with a slight twist.
I had to replace all `\$` to `$` 
hardware: Mac Intel Chip
k8s cluster: k3d running in local
