### ISSUE TITLE
bitnami/mongodb 4.4.16 - Image Availability in Dockerhub for MongoDB Upgrade

### ISSUE THREAD

**Issue by zohebs341** [bitnami/charts#12281]
### Name and Version

bitnami/mongodb 4.4.16

### What is the problem this feature will solve?

Hi Team,

Currently, we are using bitnami/mongodb 4.4.9-debian-10-r18(Image). We wanted to upgrade MongoDB from 4.4.9 to 4.4.16, as MongoDB has a newer version available. But the image is not yet available in the dockerhub.

https://www.mongodb.com/docs/upcoming/release-notes/4.4/

### What is the feature you are proposing to solve the problem?

Using bitnami/mongodb charts, we should be able to upgrade mongoDB.

I.e from 4.4.9-debian-10-r18 to 4.4.16

### What alternatives have you considered?

As the 4.4.16 image is not available in dockerhub, we cannot upgrade it.

**Comment by carrodher** [comment]
[Please note MongoDB 4.4 is only supported for Debian 9 and Debian 10](https://www.mongodb.com/docs/v4.4/tutorial/install-mongodb-on-debian/#platform-support). Since the Bitnami Application Catalog is based on Debian 11, this MongoDB branch can't be provided.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

**Comment by zohebs341** [comment]
@carrodher Thanks for your response.

In Dockerhub, we can see this image - https://hub.docker.com/layers/bitnami/mongodb/4.4.15-debian-10-r8/images/sha256-916202d7af766dd88c2fff63bf711162c9d708ac7a3ffccd2aa812e3f03ae209?context=explore

Dockerhub:

bitnami/mongodb:4.4.15-debian-10-r8 (Log4Shell CVE not detected)
DIGEST:sha256:916202d7af766dd88c2fff63bf711162c9d708ac7a3ffccd2aa812e3f03ae209
OS/ARCH
linux/amd64
COMPRESSED SIZE 
206.95 MB
LAST PUSHED
2 months ago by [bitnamibot](https://hub.docker.com/u/bitnamibot)

The above image is related to version 4.4.15 and we were looking for version 4.4.16.

In a similar way, we are looking for 4.416 image in Dockerhub.

**Comment by zohebs341** [comment]
@carrodher Is there any way forward for us to upgrade? The only option for us now is 4.4.9 to 4.4.15 and then we can use 5.0.x versions accordingly. Or are there any alternative/best possible options for MongoDB upgrade from 4.4.9 to next?

**Comment by carrodher** [comment]
You can upgrade to 4.4.15 as usual and/or then upgrade to a more recent major version such as 5.0 or 6.0. For that I recommend you to check the official MongoDB instructions about how to upgrade between versions

**Comment by zohebs341** [comment]
@carrodher Thanks for your sharing valueable information.
