### ISSUE TITLE
[bitnami/keycloak] keycloak-config-cli failed to execute

### ISSUE THREAD

**Issue by strainovic** [bitnami/charts#12699]
### Name and Version

bitnami/keycloak 10.1.2

### What steps will reproduce the bug?

1. Enable keycloakConfigCli
2. Provide import file
3. Run install

### Are you using any custom parameters or values?

No

### What is the expected behavior?

To run the job successfully.

### What do you see instead?

Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.2.jar

### Additional information

```console
I have no name!@99b9cc5b0fff:/opt/bitnami/keycloak-config-cli$ ls -al
total 77036
drwxr-xr-x 3 root root     4096 Aug 26 11:20 .
drwxrwxr-x 5 root root     4096 Sep 12 10:04 ..
-rw-r--r-- 1 root root 19707689 Aug  4 14:09 keycloak-config-cli-16.1.1.jar
-rw-r--r-- 1 root root 19714798 Aug  4 14:09 keycloak-config-cli-17.0.1.jar
-rw-r--r-- 1 root root 19716611 Aug  4 14:09 keycloak-config-cli-18.0.2.jar
-rw-r--r-- 1 root root 19718795 Aug  4 14:10 keycloak-config-cli-19.0.1.jar
lrwxrwxrwx 1 root root       63 Aug  4 14:10 keycloak-config-cli.jar -> /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.1.jar
drwxr-xr-x 2 root root     4096 Aug 26 11:20 licenses
```

**Comment by fastlorenzo** [comment]
Same issue here, since I've upgrade to the latest version of Helm chart ().

It looks like the command is based on the chart `.AppVersion`, but that the container is missing the correct jar file.

https://github.com/bitnami/charts/blob/dade1cc7cf93454885f4d02af8a005f8283d64b6/bitnami/keycloak/templates/keycloak-config-cli-job.yaml#L57

Workaround for now, override the job command. In Helm values:

```yaml
keycloakConfigCli:
  command:
    - java
    - -jar
    - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.1.jar
```

**Comment by marcosbc** [comment]
Hi @strainovic, this happens because there hasn't been a release of keycloak-config-cli for 19.0.2 yet: https://github.com/adorsys/keycloak-config-cli/releases

If you have any ideas on how to improve the current chart, feel free to contribute with a PR, we'd be glad to help with the review and release if needed.

**Comment by jensklose** [comment]
the bot is wrong
