### ISSUE TITLE
[bitnami/cassandra] add support to exec custom scripts before cassandra starts

### ISSUE THREAD

**Issue by zehweh** [bitnami/charts#1277]
**Which chart**:

bitnami/cassandra

**Description**

It would be great to have a way to run custom scripts before cassandra starts.
My use case: I want to make the cassandra pods rack aware. ATM, k8s doesn't support passing node labels (which in my case contain the rack name) to pods using environment variables. The only way to get that information is to fetch it inside the pod via k8s API.

To do that, I add the neccessary code to the statefulset.yaml template:

```
        command:
          - bash
          - -ec
          # Node 0 is the password seeder
          - |
              if [[ $HOSTNAME =~ (.*)-0$ ]]; then
                echo "Setting node as password seeder"
                export CASSANDRA_PASSWORD_SEEDER=yes
              else
                # Only node 0 will execute the startup initdb scripts
                export CASSANDRA_IGNORE_INITDB_SCRIPTS=1
              fi
              ***[CODE FOR FETCHING NODE LABEL]***
              /app-entrypoint.sh /run.sh
``` 

A different approach would be to create a directory similar to `files/docker-entrypoint-initdb.d` where we could add scripts that will be executed every time before cassandra starts.

What do you think?

**Comment by andresbono** [comment]
Hi @zehweh, have you tried to execute the container as specified in this section of the README?

[bitnami/cassandra README.md: Initializing with custom scripts](https://github.com/bitnami/bitnami-docker-cassandra#initializing-with-custom-scripts)

I think that is exactly what you are looking for. Let us know about it!

**Comment by zehweh** [comment]
Thanks @andresbono for your answer.
I tried that at first but unfortunately this only works for the first time the pod starts.

I need to fetch the node label on every start of the pod.

**Comment by andresbono** [comment]
Oh, got it!

I have just created an internal task to evaluate the inclusion of this feature in our charts. We will leave this issue open for now; that way, we can see if other users are also interested on the feature that you are requesting.

In any case, changing the command in the statefulset is working for you, right? Let us know if we can help with a workaround in the meantime.

**Comment by zehweh** [comment]
Thanks for that.

Changing the command works, yes. But using a ConfigMap or a file to execute scripts would be more elegant.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
