### ISSUE TITLE
MariaDB Galera Helm Chart unstable after deleting pods

### ISSUE THREAD

**Issue by lbornov2** [bitnami/charts#13039]
### Name and Version

bitnami/mariadb-galera 7.4.5

### What steps will reproduce the bug?

1. Bring up a 3-node MariaDB Galera cluster:
```
helm upgrade --install "foobar-database" openiam/mariadb-galera --version "7.4.5" --set rootUser.password="passwd00"
```
2. You should have 3 nodes up:
```console
$ kubectl get pods
NAME                               READY   STATUS    RESTARTS   AGE
foobar-database-mariadb-galera-0   1/1     Running   0          6m42s
foobar-database-mariadb-galera-1   1/1     Running   0          5m50s
foobar-database-mariadb-galera-2   1/1     Running   0          5m6s
```

3. Now, let's kill node 0 and node 2 repeatedly:
```
watch -n 5 kubectl delete pods/foobar-database-mariadb-galera-0 pods/foobar-database-mariadb-galera-2 --force --grace-period=0
```

4. Wait ~20 seconds

5. Now, let's create some data on the remaining node:
```console
$ kubectl exec -it foobar-database-mariadb-galera-1 bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I have no name!@foobar-database-mariadb-galera-1:/$ mysql -u root -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 77
Server version: 10.6.10-MariaDB-log Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> create database foobar;
Query OK, 1 row affected (7.463 sec)
MariaDB [(none)]> use foobar;
Database changed
MariaDB [openiam]> create table FOO (ID VARCHAR(32) NOT NULL);
ERROR 1047 (08S01): WSREP has not yet prepared node for application use
```

4. As you can see, you get a WSREP problem
5. Kill the watch statement in step 3
6. Wait 20 seconds
7. You end up with this:
```console
$ kubectl get pods | grep galera
foobar-database-mariadb-galera-0   0/1     CrashLoopBackOff   5 (70s ago)   7m33s
foobar-database-mariadb-galera-1   0/1     CrashLoopBackOff   7 (10s ago)   17m
```
8. Basically, the galera cluster is now unstable and unusable.  Killing the crashed pods does nothing to fix it.

### Are you using any custom parameters or values?

no

### What is the expected behavior?

MariaDB Cluster should come back up to 3 nodes

### What do you see instead?

All nodes stay down, even after killing all pods

**Comment by corico44** [comment]
Hello @lbornov2, I haven't been able to reproduce the error you mention. I see you're using the **openiam/mariadb-galera** image instead of using the **bitnami/mariadb-galera** image. Could you try using that other image and let me know if it fixes the error?
Also, you can check these other issues that other users have previously had that are related to your problem:
- https://github.com/bitnami/charts/issues/8560
- https://github.com/bitnami/charts/issues/2260
- https://github.com/bitnami/charts/issues/4929

And other links that may be helpful:
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb-galera#bootstraping-a-node-other-than-0
- https://stackoverflow.com/questions/40653238/mariadb-galera-error-when-a-node-shutdown-error-1047-wsrep-has-not-yet-prepare
