### ISSUE TITLE
Redis-Cluster helm chart incorrectly uses REDIS_TLS_PORT_NUMBER env variable instead of REDIS_TLS_PORT

### ISSUE THREAD

**Issue by codervinod** [bitnami/charts#13346]
### Name and Version

bitnami/redis-cluster 7.0.5

### What steps will reproduce the bug?

Enable TLS for Redis-cluster helm chart
Cluster wont come up.

### Are you using any custom parameters or values?

TLS enabled

### What is the expected behavior?

Cluster should come up

### What do you see instead?

/opt/bitnami/scripts/libredis.sh: line 405: REDIS_TLS_PORT: unbound variable

### Additional information

https://github.com/bitnami/containers/blob/main/bitnami/redis-cluster/7.0/debian-11/rootfs/opt/bitnami/scripts/libredis.sh#L405 refers to port as REDIS_TLS_PORT

vs helm chart is setting up REDIS_TLS_PORTNUMBER

**Comment by navneet066** [comment]
I am also facing the same issue

**Comment by codervinod** [comment]
Any updates?

**Comment by aoterolorenzo** [comment]
Hey @navneet066, @codervinod 

The container logic has been updated and a fix is out since a few days ago though [[bitnami/redis-cluster] Release 7.0.5-debian-11-r19](https://github.com/bitnami/containers/pull/14145) (apologies for missing the call to update the thread). Don't hesitate in reopen the issue if any issue.

**Comment by navneet066** [comment]
Thank you for the update @aoterolorenzo . I will test it and let you know the result :)
