### ISSUE TITLE
Website inconsistent with KeyCloak chart?

### ISSUE THREAD

**Issue by markusheiden** [bitnami/charts#13475]
### Name and Version

keycloak/12.1.1

### What steps will reproduce the bug?

1. Go to https://bitnami.com/stack/keycloak/helm
2. See that 3 days ago a KeyCloak 2.0.1 had been released.
3. See the keycloak Helm chart in this GitHub repo just containing 19.0.3

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Both sites contain consistent information.

### What do you see instead?

Different versions.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was detected by our automated test & release pipeline but we found some issues when testing this new version **in the Helm chart** and need to fix it manually.

At this moment the team is working on it. We will update this thread once released the new version.

The version indicated on that page is not specific for the Helm chart but is the latest version available for any deployment kind, since the container is already released (see https://github.com/bitnami/containers/tree/main/bitnami/keycloak/20/debian-11), it is showing this version as the latest one.

**Comment by carrodher** [comment]
There is an already existing open ticket that we will update once released the new major version. I'm closing this one in favor of the existing one. See https://github.com/bitnami/charts/issues/13407
