### ISSUE TITLE
keycloak helm chart image security vulnerabilities

### ISSUE THREAD

**Issue by jpgtama** [bitnami/charts#13516]
### Name and Version

docker.io/bitnami/keycloak:19.0.3-debian-11-r4
docker.io/bitnami/postgresql:15.0.0-debian-11-r1

### What is the problem this feature will solve?

The images in the chart `12.1.0` was scanned out a few CVE vulnerabilities using [trivy](https://github.com/aquasecurity/trivy) which can be found in the attached files. 

[docker.io_bitnami_keycloak_19.0.3-debian-11-r4 (debian 11.5) - Trivy Report - 2022-11-14 08_40_50.394395704 +0000 UTC m=+1.391258221.pdf](https://github.com/bitnami/charts/files/10008503/docker.io_bitnami_keycloak_19.0.3-debian-11-r4.debian.11.5.-.Trivy.Report.-.2022-11-14.08_40_50.394395704.%2B0000.UTC.m.%2B1.391258221.pdf)

[docker.io_bitnami_postgresql_15.0.0-debian-11-r1 (debian 11.5) - Trivy Report - 2022-11-14 08_40_22.8962313 +0000 UTC m=+1.093114650.pdf](https://github.com/bitnami/charts/files/10008535/docker.io_bitnami_postgresql_15.0.0-debian-11-r1.debian.11.5.-.Trivy.Report.-.2022-11-14.08_40_22.8962313.%2B0000.UTC.m.%2B1.093114650.pdf)

### What is the feature you are proposing to solve the problem?

CVE analysis report or image/libs upgrades.

### What alternatives have you considered?

A document page about security vulnerabilities in homepage or wiki like the one offered by [Istio](https://istio.io/latest/docs/releases/security-vulnerabilities/#base-images) would be very greate.

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS or the application itself, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS or the application. [Here](https://docs.bitnami.com/kubernetes/open-cve-policy/) you can find more info about this topic.

The Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

In this specific case, the Helm chart is still using Keycloak 19 since we are in the middle of releasing the new major version (Keycloak 20). The container image was already released, see [DockerHub](https://hub.docker.com/layers/bitnami/keycloak/20.0.1/images/sha256-034e863ebfb8c0ad28fd9167e003b5ec8242fdeee6b09d04138335ae6ca74a51?context=repo), and we are working on the Helm chart right now.

**Comment by evan-xy-hu** [comment]
Hi carrodher, very thanks to your clarification. CVEs in base image is indeed a common and popular issue for cloud native nowdays. Though there are some efforts to solve this, e.g [distroless images](https://github.com/GoogleContainerTools/distroless), more time are still needed for us to find out the best way to handle this.
