### ISSUE TITLE
[bitnami/spark] Require `--master yarn` support

### ISSUE THREAD

**Issue by rahuls-fens** [bitnami/charts#13760]
### Name and Version

bitnami/spark:3.3.0-debian-11-r44

### What is the problem this feature will solve?

This feature will allow to submit spark job using master as yarn

### What is the feature you are proposing to solve the problem?

Resource management is easily done by yarn

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feature request. Could you add more details on how this feature works? Does it require adding a new package to the container or yarn would be already there and we just need to edit the logic

**Comment by rahuls-fens** [comment]
> Hi,
> 
> Thank you so much for the feature request. Could you add more details on how this feature works? Does it require adding a new package to the container or yarn would be already there and we just need to edit the logic

You can get more details here:
https://sparkbyexamples.com/spark/spark-setup-on-hadoop-yarn/

**Comment by CeliaGMqrz** [comment]
Hi @rahuls-fens 

Thanks for your feature request. I have created an internal task for our team to work on this new feature. We'll leave this issue on-hold until our dev team works on the related task.

**Comment by carrodher** [comment]
Hi, thanks for creating this issue. After analyzing internally our priorities and due to other issues/initiatives we are working on, we didn't find the bandwidth to implement this feature.

Being said that, would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
