### ISSUE TITLE
[bitnami/elasticsearch]There is no healthcheck.sh

### ISSUE THREAD

**Issue by 92ppl** [bitnami/charts#13870]
### Name and Version

bitnami/elasticsearch17.5.7

### What steps will reproduce the bug?

```
helm install elasticsearch bitnami/elasticsearch -n middleware --set global.kibanaEnabled=true --set global.storageClass=default --set image.tag=7.9.3-debian-10-r0 --version 17.5.7
```

### Are you using any custom parameters or values?

```
--set global.kibanaEnabled=true --set global.storageClass=default --set image.tag=7.9.3-debian-10-r0 
```

### What is the expected behavior?

run success

### What do you see instead?

```
Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/opt/bitnami/scripts/elasticsearch/healthcheck.sh\": stat /opt/bitnami/scripts/elasticsearch/healthcheck.sh: no such file or directory": unknown
```

**Comment by javsalgar** [comment]
Hi,

I'm afraid you are using an image that does not have the script, note that it was added in version 7.17

https://github.com/bitnami/containers/commit/cf02358a81b0f54c225d200252b19d9ec5b6ce53

You would need to add your own custom probe or disable the probes in order to use that image. Note that this old version would be out of the support scope we provide here.
