### ISSUE TITLE
[bitnami/postgresql-ha] Enable updating pgpool usernames/passwords after installation

### ISSUE THREAD

**Issue by carolili** [bitnami/charts#13931]
### Name and Version

bitnami/postgresql-ha 10.0.5

### What is the problem this feature will solve?

- When using the [global.pgpool.existingSecret value](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/values.yaml#L44) for an existing secret with usernames and passwords it seems like there isn't a way to update the credentials after an initial installation
- I tried updating the secret and running a Helm upgrade for the chart. It did not seem to update the users
```
helm upgrade postgresql-ha bitnami/postgresql-ha -f values.yaml --version 10.0.5
```
- If it should work, please let me know, and I will check my configuration. If there is any alternative way to update the Postgresql DB users without having to reinstall the chart or manually update users in the DB, please let me know 🙂 

### What is the feature you are proposing to solve the problem?

- Enable a way to update the pgpool credentials for DB users if the pgpool existingSecret is changed

**Comment by javsalgar** [comment]
Hi,

I'm afraid that, by design, the passwords are set on first boot and are not modified afterwards. The reason of not doing it is because the amount of complexity and corner cases that we would need to cover, making the container code difficult to maintain. As an alternative, you could try adding custom init scripts that are executed on each run or maybe deploy with `extraDeploy` a Job object that performs the change.

**Comment by carolili** [comment]
Hi, thank you for the update and explanation. I will try with a custom init script or a job.
