### ISSUE TITLE
[Chart] Prometheus-CRD only

### ISSUE THREAD

**Issue by jcpunk** [bitnami/charts#14001]
### Name and Version

bitnami/kube-prometheus

### What is the problem this feature will solve?

It would make it much easier to install cilium/calico via helm.

The current workflow:

1. install cilium
2. install kube-prometheus
3. enable cilium service monitor

Since you cannot enable the serviceMonitor without the CRDs and you cannot install kube-prometheus via helm without a working CNI, this gets a bit ugly.

This is a bit frustrating with config management tools. In step 1, a set of chart values are set. These get changed in step 3. So enforcement of the settings gets a bit ugly.

The Operator chart could then depend on the CRD chart.

### What is the feature you are proposing to solve the problem?

Helm Best Practices recommends [separating the CRD resources](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts) into their own chart.

I propose to create a new kube-prometheus-crds chart + any related update scripts which only contain the CRDs. 

### What alternatives have you considered?

Using one of the various unofficial charts (see also https://github.com/prometheus-community/helm-charts/issues/2612)

https://artifacthub.io/packages/helm/wiremind/kube-prometheus-stack-crds
https://artifacthub.io/packages/helm/morremeyer/kube-prometheus-stack-crds
https://artifacthub.io/packages/helm/appscode/prometheus-operator-crds

**Comment by fmulero** [comment]
Hi Pat, Sorry for my very late response.

I completely understand your point and I did a little research and I have some concerns about your approach. If we use a different chart for CRDs, it shouldn't be declared as subchart of current `bitnami/kube-prometheus` because the CRDs get deleted if we uninstall the release, as a consequence, we will lose all the definitions in the cluster base on this CRDs (this behaviour is not desired). So we have two options:
* Create `bitnami/kube-prometheus-crd` chart and **delete** the `crd` folder from the `bitnami/kube-prometheus` chart. It will have a big impact in  our CI/CD workflows and tools, they are not prepared for this kind of dependencies.
* Create `bitnami/kube-prometheus-crd` chart and **keep** the `crd` folder in the `bitnami/kube-prometheus` chart. We will need to keep the same code twice, and users should skip crd installation in `bitnami/kube-prometheus` if they need to install both.

I will open an internal discussion. In the mean time this could be a feasible option:
```bash
$ helm pull bitnami/kube-prometheus
$ tar -xf kube-prometheus-*.tgz 
$ find kube-prometheus/crds/ -type f -name "*.yaml" -exec kubectl apply -f {} \;
$ # Install cellium
$ helm install --skip-crds kube-prometheus kube-promethues -f <your values file>
```

**Comment by fmulero** [comment]
Hi Pat, we have been discussing it internally and finally we decided to not implement your proposal, due to the following reasons:
* This chart follows the [Method 1](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) described in the helm guide you provided. So we are already following the Best Practices.
* Helm doesn't take care about CRD upgrade or delete, so "manual" intervention is always required when you are upgrading or undeploying your chart. 
* This change would require more maintenance from our side and it could have a big impact in our CI/CD workflows.
