### ISSUE TITLE
Error: chart "postgresql" version "10.16.2" not found in https://charts.bitnami.com/bitnami repository

### ISSUE THREAD

**Issue by Quasarman** [bitnami/charts#14029]
### Name and Version

bitnami/postgresql 10.16.2

### What steps will reproduce the bug?

This was working yesterday just fine. Now the version is gone? How can that ever happen? I dont have the time to always upgrade to the newest version why are old ones just removed out of nowhere?

I also cannot fin it here https://artifacthub.io/packages/helm/bitnami/postgresql

Why do you keep removing versions this causes a lot of issue?

### What is the expected behavior?

Versions not to be deleted randomly or after any amount of time...thats the principle of versioning IMHO

### What do you see instead?

 Error: chart "postgresql" version "10.16.2" not found in https://charts.bitnami.com/bitnami repository

**Comment by carrodher** [comment]
As announced in the below-mentioned GH issues, we are applying a retention policy of 6 months.
Recently, the script to guarantee the retention policy was executed, see https://github.com/bitnami/charts/pull/14024. Please note as a result of this execution, the `index.yaml` was updated to keep Helm charts from the latest 6 months but the Helm charts were not deleted.

Please, take a look a this pinned issue https://github.com/bitnami/charts/issues/10833 to have more info about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client and dependent Helm charts.

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the [already existing GH issue](https://github.com/bitnami/charts/issues/10539), closing the other ones.

**Comment by Quasarman** [comment]
Thanks for the quick response! I will check that out and use the github link to have access to older versions of the respective charts.
