### ISSUE TITLE
Access Denied trying to access https://charts.bitnami.com/bitnami

### ISSUE THREAD

**Issue by leandroblanc** [bitnami/charts#14043]
### Name and Version

bitnami/<all>

### What steps will reproduce the bug?

1. Open a web browser
2. Visit https://charts.bitnami.com/bitnami

We found this issue because our ArgoCD servers are no longer able to synchronize the Bitnami helm charts we use (RabbitMQ, Redis, etc)

### Are you using any custom parameters or values?

N/A

### What is the expected behavior?

I expect to be able to access https://charts.bitnami.com/bitnami

### What do you see instead?

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>JW7Z032Q8613BCP0</RequestId>
<HostId>3UmAiJa3DShIlOwWoYGMohTHTgyeF1d9x+C0leDlu0ahVBD9BZ4sxxJrBPJyg6ezTsy9cgz2Qdk=</HostId>
</Error>
```

### Additional information

This issue is similar to this one (old one): https://github.com/bitnami/charts/issues/5527

**Comment by andreykozudaev** [comment]
Having the same issue

**Comment by carrodher** [comment]
Please note this URL is not appropriate to be used by a web browser but by the Helm Client, the only browsable URL is https://charts.bitnami.com/ (although this is a static site with info about how to use the Helm registry).

Regarding the issue you're facing with some chart versions it is because, as announced in the below-mentioned GH issues, we are applying a retention policy of 6 months for Helm charts.
Recently, the script to guarantee the retention policy was executed, see https://github.com/bitnami/charts/pull/14024. Please note as a result of this execution, the `index.yaml` was updated to keep Helm charts from the latest 6 months but the Helm charts were not deleted.

Please, **take a look a this pinned issue https://github.com/bitnami/charts/issues/10833 to have more info** about this change and some ways to use previous versions as usual by adding a previous `index.yaml` version to the `helm` client and dependent Helm charts.

In order to consolidate the conversations and unify the effort, we will answer questions as well as any other communication in the [already existing GH issue](https://github.com/bitnami/charts/issues/10539), closing the other ones.

**Comment by leandroblanc** [comment]
Thanks for your info! I'll start using the bitnami-full-index then. 

Suggestion: maybe the charts docs should include a warning/note indicating that they will be kept for 6 months only. For example, it could be nice if that info is included here (examples):

- https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq
- https://bitnami.com/stack/rabbitmq/helm

Thanks again!

**Comment by janpastrnak** [comment]
Currently is occurring again.

**Comment by ChrisSteinbach** [comment]
And again?
