### ISSUE TITLE
How to access bitnami/external-dns old version 4.11.0 repo bitnami-legacy-6012022

### ISSUE THREAD

**Issue by vsana1** [bitnami/charts#14154]
### Name and Version

bitnami/external-dns old version 4.11.0

### What steps will reproduce the bug?

We are having issues with old version 4.111.0 and created a ticket https://github.com/bitnami/charts/issues/10581 in the past.

We are using this `helm repo add bitnami-legacy-6012022 https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami`

My external-dns pod is failing now with the following error 
```
----     ------     ----                  ----               -------
  Normal   Scheduled  14m                   default-scheduler  Successfully assigned confluent/external-dns-b94485f9c-6q2tl to ip-10-240-30-35.ec2.internal
  Normal   Created    10m (x4 over 14m)     kubelet            Created container external-dns
  Normal   Started    10m (x4 over 14m)     kubelet            Started container external-dns
  Normal   Pulled     8m29s (x5 over 14m)   kubelet            Container image "docker.io/bitnami/external-dns:0.7.6-debian-10-r63" already present on machine
  **Warning  BackOff    4m10s (x27 over 12m)  kubelet            Back-off restarting failed container**
```
Is there anything changed in above mentioned repo ? would you please help us.

**Comment by carrodher** [comment]
That is not related to the Helm registry, the Helm chart is fetched and deployed from the registry, and the issue is when executing one of the containers. You should debug the pod and the container by checking the logs (`kubectl logs`) or describing the resources (`kubectl describe`).

For information regarding the application itself, customization of the content within the application, or questions about the use of the technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.
