### ISSUE TITLE
MariaDB chart stuck in "Running mysql_upgrade..."

### ISSUE THREAD

**Issue by iWangJiaxiang** [bitnami/charts#1427]
**Which chart**:

Mariadb

**Description**

I have 2 bitnami mariadb charts in my k8s cluster. Today I found all of them got "unavailable" status. And the log is as below:

![image](https://user-images.githubusercontent.com/19409802/65399779-3a828580-ddf1-11e9-8ecf-ebfed4e0847b.png)

It was stuck here foerever.

Do you have any idea?

**Comment by iWangJiaxiang** [comment]
Problem Solved! It's not you~ It's my storage issue.

**Comment by ReachInfinity** [comment]
Hello ! I have the same problem. How did you solve your problem with storage?

**Comment by iWangJiaxiang** [comment]
Plz check your persistent volume. Mine was a NFS storage issue.

________________________________
发件人: ReachInfinity <notifications@github.com>
发送时间: Friday, October 11, 2019 5:20:36 AM
收件人: bitnami/charts <charts@noreply.github.com>
抄送: Wang Jiaxiang <iwangjiaxiang@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [bitnami/charts] MariaDB chart stuck in "Running mysql_upgrade..." (#1427)


Hello ! I have the same problem. How did you solve your problem with storage?

―

**Comment by juan131** [comment]
Hi @ReachInfinity 

You're probably upgrading your chart without indicating the same credentials that were originally used the 1st time you installed the chart.

Please note that passwords are randomly created when they're not specified. If there's data in the PV referring to the credentials that were generated the 1s time, then the readiness/liveness probes will fail since they will try to use different passwords.

More information can be found in the link below:

https://github.com/helm/charts/tree/master/stable/mariadb#upgrading
