### ISSUE TITLE
How to specify vapid on mastodon chart

### ISSUE THREAD

**Issue by digitalbuddha** [bitnami/charts#14401]
### Name and Version

bitnami/mastodon

### What steps will reproduce the bug?

build the helm chart

### What is the expected behavior?

ability to set vapid

### What do you see instead?

do not have the ability

### Additional information

When looking at mastodon official chart there is ability to set the vapid secrets https://github.com/mastodon/chart/blob/ae892d539ed35433ceadeadaf87113cca75c2ea7/values.yaml#L72

Those secrets are needed for push/streaming api to work properly
https://docs.joinmastodon.org/admin/config/

Normal install from source/docker tells you run rake tasks after first install, generate the keys and then reinstall

As an example here is how linode instructs installation using docker-compose and the official image.

My question is how to do this in the bitnami chart? Is this a step that should be automated or is it left up to the user?

Ideally I would like to not have to ssh into my pods and having to set the keys manually. Thank you for your help

**Comment by marcosbc** [comment]
Hi @digitalbuddha, it seems like this is a missing feature from when Mastodon was implemented. It should be simple to add an environment variable to be used in the chart.

For now, it should be enough to define in each `extraEnv`:

* `VAPID_PRIVATE_KEY`
* `VAPID_PUBLIC_KEY`

In addition, since these values require a specific format (public/private keys), it could be good to set the values if the envvars were not set before in the [container image](https://github.com/bitnami/containers/tree/main/bitnami/mastodon). To do so, you would add some logic to `mastodon_initialize` in `libmastodon.sh` if those envvars are not set already, to execute the rake command.

Feel free to contribute an improvement so it is easier to set these values!

**Comment by digitalbuddha** [comment]
Got it, I will give it a try, this is fairly new to me.

As an fyi this is how we can generate the keys
```

 ## openssl ecparam -name prime256v1 -genkey -noout -out vapid_private_key.pem
    ## openssl ec -in vapid_private_key.pem -pubout -out vapid_public_key.pem
    ## echo -n VAPID_PRIVATE_KEY=;cat vapid_private_key.pem | sed -e "1 d" -e "$ d" | tr -d "\n"; echo
    ## echo -n VAPID_PUBLIC_KEY=;cat vapid_public_key.pem | sed -e "1 d" -e "$ d" | tr -d "\n"; echo

similar
secretKeyBase The secret key base, required to set up. You can generate it with `openssl rand -hex 64`
 otpSecret The OTP secret, required to set up. You can generate it with `openssl rand -hex 64`. Ignored if set in an existing secret.
```
