### ISSUE TITLE
[bitnami/mariadb-galera] Add or change user rights on Bitnami Galera

### ISSUE THREAD

**Issue by adrian-sa** [bitnami/charts#14517]
### Name and Version

bitnami/mariadb-galera

### What is the problem this feature will solve?

Hi there Bitnami !

This might be a support ticket more than a feature request maybe.

Is there a way to add/modify/delete a user to be able to do actions ?
For instance, the non-root user can't create TRIGGERS, some frameworks do this type of action.

For instance, if I take a the Redis Helmcharts, there is the following entry: `master.disableCommands` that disables some commands.

Is there such a configuration for Galera ?

If not, it might be interesting to be able via `values.yaml` to GRANT actions on the created user.

Thanks !

### What is the feature you are proposing to solve the problem?

Be able to add parameters on the GRANT command when creating the non-root user

The GRANT actions could be added via the values.yaml

### What alternatives have you considered?

I thought maybe interfacing with the init scripts, but i couldn't see a way to retrieve the created non-root user

**Comment by carrodher** [comment]
Thanks for reporting this issue. Would you like to contribute by creating a PR to solve the issue? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by migruiz4** [comment]
Hi @adrian-sa!

First of all, I would like to clarify one thing as I feel there could be some misunderstanding around the 'non-root' user in the original post.

By non-root user we usually refer to the system UID used to run the process inside the container, in this case, mariadb-galera.

I'm mentioning this because you appear to be referring to MariaDB user permissions.

If that is the case, when using default values the MariaDB Galera helm chart will only create the database `root` user. Additionally, a 'non-root' user can be created using the values `db.user` and `db.password`.

The feature you are asking for can be achieved by using the value `initdbScripts` (or `initdbScriptsConfigMap`), which you can use to provide either Shell scripts or .sql/.sql.gz scripts.

Here is an example `values.yaml`:
```
image:
  debug: true
db:
  user: "sample_user"
  password: "sample_pass"
initdbScripts:
  my_init_script.sh: |-
    #!/bin/sh
    echo "Hello world."
  config_permissions.sql: |-
    GRANT ALL PRIVILEGES ON *.* TO 'sample_user'@'%';
```

Output:
```
...
mariadb 10:25:37.61 DEBUG ==> Executing /docker-entrypoint-initdb.d/config_permissinos.sql
mariadb 10:25:37.62 DEBUG ==> Executing SQL command:
GRANT ALL PRIVILEGES ON *.* TO 'sample_user'@'%';
mariadb 10:25:37.63 DEBUG ==> Sourcing /docker-entrypoint-initdb.d/my_init_script.sh
Hello world.
...
```

Note: scripts are executed in alphanumeric order based on the filename, in case you need to run scripts in a determined order.

**Comment by adrian-sa** [comment]
Hello @migruiz4 !

Sorry for the misunderstanding :(

But what you are linking is precisely what I was talking about.
I wasn't sure that we could use `initdbScripts` for the GRANT permissions, but as you are showing is all good !

Thanks for the precisions !

I'll resolve the ticket.
Have a nice day !
