### ISSUE TITLE
[kafka] accessing kafka cluster from the outside

### ISSUE THREAD

**Issue by joselmh** [bitnami/charts#1467]
**Which chart**: kafka

**Description**
Not able to connect externally using load balancer 

```
chart installation command: helm install --namespace bitnami --name my-release bitnami/kafka -f ./values-production.yaml --set service.type=LoadBalancer
```

Cluster is up and running and I'm able to create topics, publish and suscribe following the instructions. For example:
 
```
export POD_NAME=$(kubectl get pods --namespace bitnami -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=my-release,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
    kubectl --namespace bitnami exec -it $POD_NAME -- kafka-console-producer.sh --broker-list localhost:9092 --topic test
``` 
But following instructions to connect from outside:

```
kubectl --namespace bitnami exec -it $POD_NAME -- kafka-topics.sh --create --zookeeper my-release-zookeeper:2181 --replication-factor 3 --partitions 2 --topic testreplicated
Created topic testreplicated.
```
```
export SERVICE_IP=$(kubectl get svc --namespace bitnami my-release-kafka --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
PRODUCER:
        kafka-console-producer.sh --broker-list $SERVICE_IP:9092 --topic test
    CONSUMER:
        kafka-console-consumer.sh --bootstrap-server $SERVICE_IP:9092 --topic test --from-beginning
```

the commands fail:

```
kafka-console-producer.sh --broker-list $SERVICE_IP:9092 --topic testreplicated
>first message
>[2019-10-09 11:43:19,104] WARN [Producer clientId=console-producer] Got error produce response with correlation id 3 on topic-partition testreplicated-0, retrying (2 attempts left). Error: NOT_LEADER_FOR_PARTITION (org.apache.kafka.clients.producer.internals.Sender)
[2019-10-09 11:43:19,104] WARN [Producer clientId=console-producer] Received invalid metadata error in produce request on partition testreplicated-0 due to org.apache.kafka.common.errors.NotLeaderForPartitionException: This server is not the leader for that topic-partition.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
``` 

If I try to consume messages that have been published from within the cluster:

```
kubectl --namespace bitnami exec -it $POD_NAME -- kafka-console-producer.sh --broker-list localhost:9092 --topic testreplicated
>1111111
>222222222
>3333333
>444444
>555555
>
```

And try to consume them from outside the cluster:

```
kafka-console-consumer.sh --bootstrap-server $SERVICE_IP:9092 --topic testreplicated --from-beginning
1111111
3333333
555555
```
only a few are received (apparently half of them)

**Steps to reproduce the issue:**

1. Install chart:
 ``` helm install --namespace bitnami --name my-release bitnami/kafka -f ./values-production_noauth.yaml --set service.type=LoadBalancer
 ```

2. Create a topic from within the cluster 
``` 
export POD_NAME=$(kubectl get pods --namespace bitnami -l "app.kubernetes.io/name=kafka,app.kubernetes.io/instance=my-release,app.kubernetes.io/component=kafka" -o jsonpath="{.items[0].metadata.name}")
    kubectl --namespace bitnami exec -it $POD_NAME -- kafka-topics.sh --create --zookeeper my-release-zookeeper:2181 --replication-factor 3 --partitions 2 --topic testreplicated
```

3. Publish from outside the cluster (this fails): 

``` 
export SERVICE_IP=$(kubectl get svc --namespace bitnami my-release-kafka --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
kafka-console-producer.sh --broker-list $SERVICE_IP:9092 --topic testreplicated
>first message
```

4. Publish from within the cluster (this works as expected)

5. Consuming from outside the cluster (this fails. Only a few messages are received. Seems to be messages from only one partition):

```
kafka-console-consumer.sh --bootstrap-server $SERVICE_IP:9092 --topic testreplicated --from-beginning
``` 

**Describe the results you received:**

Publishing messages from outside the cluster fails (error trace above)
Consuming messages from outside the cluster fails. Only a few messages are received.

I should be able to publish messages from outside the cluster without any error, and consuming all the messages from outside the cluster.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**: 
Helm v2.14.3
Azure Kubernetes Service: Kubernetes version 1.13.10

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
``` 

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

In values-production.yaml auth is disabled

**Comment by marcosbc** [comment]
Hi @joselmh, we could get this to work in a local Minikube installation without any issues. However in an external cluster we found some issues (possibly unrelated) and are looking into it.

We'll get back to you soon with an update.

**Comment by marcosbc** [comment]
Hi @joselmh, apparently I got it working in my local Minikube due to using an old container version, which included a bug allowing for this.

With current releases, unfortunately connecting to the cluster from outside is not possible. If you wanted to make it happen, Kafka would need to be [customized further](https://medium.com/@tsuyoshiushio/configuring-kafka-on-kubernetes-makes-available-from-an-external-client-with-helm-96e9308ee9f4).

The current Helm chart configures Kafka's `advertised.listeners` to point to headless services, which are not supposed to be accessible from the outside. Also, since Kafka consumers/producers need to have access to all nodes (advertised listeners), any connection would fail because of this unless manually adding to `/etc/hosts`.

I understand this is a feature that may be desired in some use cases, so I've created an internal task for adding support for this feature.

Keep in mind our backlog is quite big, so unfortunately we cannot provide an ETA for when this would be implemented, it will most likely take a while to happen. However, if you have ideas, feel free to contribute with a PR implementing this feature!

**Comment by marcosbc** [comment]
I noticed you were able to produce consumers from the outside. Just to confirm, are you using the Bitnami Kafka chart version 6.0.1?

If it works for you, did you perform any additional steps in order to connect Kafka consumers/producers from outside of cluster pods? I.e. adding entries to `/etc/hosts`.

**Comment by joselmh** [comment]
Hi @marcosbc 
I installed the chart from the github repo. Looking at Chart.yaml file I can see that the version tag points to **6.0.2**. So I assume that is the version of the chart.
Regarding any additional steps, I **added entries to /etc/hosts** , mapping the three advertised listeners to the load balancer external ip. Which I think is not completely correct, since I always assumed that each broker needs to have its own advertised listener. But not sure how this should work on kubernetes.

**Comment by marcosbc** [comment]
Thanks for letting us know @joselmh, I've added the info to the internal task. In that case it makes sense it works for you, although your issue is quite strange.
However, I believe that Kafka will need to be configured further to work in this scenario. We'll get back if we have any updated, but please beware it could take some time.
