### ISSUE TITLE
[bitnami/odoo] Odoo seems to have secret issues with external database

### ISSUE THREAD

**Issue by ghost** [bitnami/charts#14741]
### Name and Version

bitnami/odoo v23.0.7

### What steps will reproduce the bug?

when using an external database I get an error:
```
Error: secret "test1-externaldb" not found
```

This is the command I run:

```
helm upgrade --install --wait --create-namespace -n test1 test1 bitnami/odoo --version 23.0.7 \
  --set controller.publishService.enabled=true \
  --set service.type=ClusterIP \
  --set postgresql.enabled=false \
  --set externalDatabase.host=DB_SERVER_ADDRESS \
  --set externalDatabase.user=DB_USERNAME \
  --set externalDatabase.password=DB_PASSWORD \
  --set externalDatabase.port=5432
```

Previous charts version have the same behaviour.

### Are you using any custom parameters or values?

```
--set controller.publishService.enabled=true \
  --set service.type=ClusterIP \
  --set postgresql.enabled=false \
  --set externalDatabase.host=DB_SERVER_ADDRESS \
  --set externalDatabase.user=DB_USERNAME \
  --set externalDatabase.password=DB_PASSWORD \
  --set externalDatabase.port=5432
  ```

### What is the expected behavior?

a secrets get created.

### What do you see instead?

CreateContainerConfigError

```
Error: secret "test1-externaldb" not found
```

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this Helm chart](https://github.com/bitnami/charts/tree/main/bitnami/odoo#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this Helm chart by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by mashaal95** [comment]
I am also facing the same issue

**Comment by AlMaVizca** [comment]
I'm facing the same error. I think the issue is with the naming conventions.
The secret is requested on the following file:
https://github.com/bitnami/charts/blob/09b80f82df6a51202b219805ae4b0d743ae406cc/bitnami/odoo/templates/deployment.yaml#L141-L145

Looking at it, by default is using the `.Release.name`
https://github.com/bitnami/charts/blob/09b80f82df6a51202b219805ae4b0d743ae406cc/bitnami/odoo/templates/_helpers.tpl#L100-L102

While the secret is created using `common.names.fullname`
https://github.com/bitnami/charts/blob/09b80f82df6a51202b219805ae4b0d743ae406cc/bitnami/odoo/templates/externaldb-secrets.yaml#L8-L11

I don't know if they are supposed to be the same, but it looks like they aren't.
On my case, the secret is like: `app-odoo-externaldb`, while the definition is looking for `app-externaldb`

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
