### ISSUE TITLE
Deployment Template For Keycloak

### ISSUE THREAD

**Issue by amartincolby** [bitnami/charts#15056]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

I am manipulating deployments by grabbing yaml data via kubectl (specifically to inject a Linkerd mesh), but since Keycloak does not have a deployment template, it does not generate a deployment entity, and `kubectl get deployments` returns nothing.

### What is the feature you are proposing to solve the problem?

Just creating a deployment template.

### What alternatives have you considered?

None. Linkerd is set up to only work with deployments.

**Comment by fmulero** [comment]
Hi Aaron,

In this case we needed to use a [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) to manage the workload. This approach is completely valid and I don't fully understand why a deployment is required in your case because linkerd should work with statefulsets without issues.
