### ISSUE TITLE
[bitnami/wordpress] fails to pull r49 from public ECR

### ISSUE THREAD

**Issue by pfragoso** [bitnami/charts#15119]
### Name and Version

bitnami/wordpress:15.2.45

### What steps will reproduce the bug?

Changing to:
```yaml
global:
  imageRegistry: public.ecr.aws
```
fails as the r49 image is not in public.ecr -> https://gallery.ecr.aws/bitnami/wordpress

### What is the expected behavior?

We should be able to pull the pinned version from the helm from ECR.

**Comment by carrodher** [comment]
Please note the release cadence can be different between registries. Helm charts are ready to work out of the box with DockerHub images since `docker.io` is the default registry.

It's not 100% guaranteed that the Helm charts work out of the box when changing the registry since, as you rightly point out, some specific tags may not yet be present in registries other than DockerHub.

**Comment by pfragoso** [comment]
Hello,

Thanks for the information, i couldn't find anything related.
Is this a process that is syncing the registries? ie is there any way to see that status?

**Comment by carrodher** [comment]
Helm charts are tested as an "isolated package" with the container images bundled inside this package. Replacing the container images work in most cases but it is not something tested so some exceptions can appear.

Regarding the registries, the default one is Docker Hub, in other registries you can find the same container images but the tags may vary, mainly the revision (`-rXX`), if you would like to use a different registry my recommendation is using a rolling tag pinning the specific version without revision, for instance, `image.tag=6.1.1` because, as I mention, it is not guaranteed that the specific revisions are distributed in the different registries in the same time.

> Is this a process that is syncing the registries? ie is there any way to see that status?
When a container image is tested and built by our internal test & release pipeline it is distributed to our default registry (Docker Hub) right after, but other registries are populated based on different rules.
