### ISSUE TITLE
[bitnami/jupyterhub] Jupyterhub Custom SingleUser Instances

### ISSUE THREAD

**Issue by djMax** [bitnami/charts#15380]
### Name and Version

bitnami/jupyterhub 3.0.11

### What is the problem this feature will solve?

The singleuser template uses docker.io/bitnami/bitnami-shell and docker.io/bitnami/jupyter-base-notebook. It's not entirely clear how to use other images like https://hub.docker.com/r/jupyter/datascience-notebook or similar that have more useful features for certain applications. The home directory, user environment, volume mounts, etc aren't well documented (that I could find) so that one could use an alternate image.

### What is the feature you are proposing to solve the problem?

More documentation or examples of using other images.

### What alternatives have you considered?

I could extend the bitnami base jupyter image instead, which perhaps doesn't require anything other than the ordinary docker stuff.

**Comment by CeliaGMqrz** [comment]
Hi @djMax,

Thanks for your feature request! Do you have specific questions? It would be more effective to answer specific questions in order to adapt our documentation as best as possible. 

Would you like to contribute by creating a PR to add the information? The Bitnami team will be happy to review it and provide feedback. [Here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) you can find the contributing guidelines.
