### ISSUE TITLE
[node] node chart disappeared from the oci repo

### ISSUE THREAD

**Issue by jouve** [bitnami/charts#15653]
### Name and Version

bitnami/node

### What architecture are you using?

amd64

### What steps will reproduce the bug?

https://hub.docker.com/r/bitnamicharts/node => 404

**Comment by carrodher** [comment]
In the index.yaml is present, see 
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo node
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/node         	19.1.7       	16.18.0    	DEPRECATED Node.js is a runtime environment bui...
```

As OCI artifact is not present (and it is not going to be present) since we started to publish the Bitnami Helm charts as OCI packages once the _bitnami/node_ Helm chart was deprecated (as well as others) and we are not retroactively publishing already deprecated Helm charts.
