### ISSUE TITLE
[bitnami/schema-registry] Configuring Schema Registry with SSL and external Kafka cluster

### ISSUE THREAD

**Issue by NDoBln** [bitnami/charts#15771]
### Name and Version

bitnami/schema-registry 9.0.1

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Environment: Cloud-managed Openshift Cluster 4.10
2. Configuration: With all parameters that are given below and as external Kafka we have used a Strimzi based Kafka (Red Hat AMQ Streams Kafka)

### Are you using any custom parameters or values?

- kafka.enabled=false
- externalKafka.brokers=["ssl://address"]
- externalKafka.auth.protocol=ssl
- podSecurityContext.enabled=false
- containerSecurityContext.enabled=false
- auth.kafka.jksSecret=secret-name
- auth.kafka.keystorePassword=keystore-password
-  auth.kafka.truststorePassword=truststore-password
- auth.tls.enabled=true
- auth.tls.jksSecret=secret-name
- auth.tls.keystorePassword=keystore-password
- auth.tls.truststorePassword=truststore-password

### What do you see instead?

The schema registry pod shows the following error log:

```
schema-registry 14:44:49.90
schema-registry 14:44:49.90 Welcome to the Bitnami schema-registry container
schema-registry 14:44:49.90 Subscribe to project updates by watching https://github.com/bitnami/containers
schema-registry 14:44:49.90 Submit issues and feature requests at https://github.com/bitnami/containers/issues
schema-registry 14:44:49.91
schema-registry 14:44:49.92 INFO  ==> ** Starting Schema Registry setup **
schema-registry 14:44:49.93 INFO  ==> Validating settings in SCHEMA_REGISTRY_* env vars
schema-registry 14:44:49.94 ERROR ==> In order to configure the TLS encryption for communication with Kafka brokers, you must mount your schema-registry.keystore.jks and schema-registry.truststore.jks certificates to the /opt/bitnami/schema-registry/certs directory.
```

**Comment by javsalgar** [comment]
Hi,

Which are the contents of the JKS secret? Maybe the filenames are different and therefore they are not detected in the installation

**Comment by alinavretinaris** [comment]
Hi @javsalgar, 
I am working with @NDoBln on this. 
The names of the JKS secret are schema-registry-0.keystore.jks and schema-registry.truststore.jks

We did notice that there should be a copy process from /certs (where the secret is mounted) to /opt/bitnami/schema-registry/certs. But the mounting is done as readOnly: true. could that have an impact somehow? we tried it once to overwrite it to false manually, but this had no effect. nevertheless I thought I mention it.

**Comment by javsalgar** [comment]
Hi,

I don't think that the readOnly should have an impact on this. The copy of the certs is because we wanted to avoid issues with how secrets and configmaps are mounted.

**Comment by NDoBln** [comment]
Ok. Do you have any other ideas what the problem could be?

**Comment by NDoBln** [comment]
@jotamartos Could you help us on this issue?

**Comment by jotamartos** [comment]
Sorry for the big delay here. I'm going to start working on checking this and will update the ticket once I have more information.

**Comment by jotamartos** [comment]
Hi @NDoBln,

I just found that the .Values.auth.tls.jksSecret parameter was not used at all in the chart. I created this PR to mount the certs in the certs folder if required 

https://github.com/bitnami/charts/pull/16130

However, I also saw that if you are using the same secret name for the auth.tls' and auth.kafka's secrets, it's not being mount due to this line in the template.

https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/templates/statefulset.yaml#L4

I suggest you take a look at your configuration parameters and test the solution with the changes I proposed. If everything works as expected, I'll merge the changes so they are available in the public chart. 

Thanks

**Comment by NDoBln** [comment]
@jotamartos let me know if I should test something else what might help you with debugging.

**Comment by jotamartos** [comment]
>I have added a bash echo into the statefulset.yaml before line 100: echo “kafkaProtocol is: $kafkaProtocol” and I can see in my deployed Pod that the environment variable $kafkaProtocol seems to be empty.

The ssl protocol is not taken into account in the `schema-registry.listenerType` function. 

https://github.com/bitnami/charts/blob/172286a5937a4300d2c418d0fceea51b841ad3d1/bitnami/schema-registry/templates/_helpers.tpl#L95

Can you edit the line and confirm everything works properly when including the ssl protocol there? You can create a PR to solve this issue

```
{{- else if or (eq .protocol "ssl") (eq .protocol "tls") (eq .protocol "mtls") -}}
SSL
```

>Note: The values.yaml file needs to be updated as well

>When I debug the corresponding container I can see that: in /certs the secrets have been mounted but I have also noticed that the directory /opt/bitnami/schema-registry/certs is empty. Thus, it seems that the copy commands from line 105 & 106 in statefulset.yaml did not work.

As the protocol is not properly configured, this block is not rendered

https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/templates/statefulset.yaml#L100

**Comment by alinavretinaris** [comment]
Hey @jotamartos 

we did try changing the parameter as suggested. 
The docu states for the protocol the following: 
<img width="1032" alt="Bildschirmfoto 2023-04-26 um 13 29 58" src="https://user-images.githubusercontent.com/41105397/234563075-2093fcf6-119d-42f7-9a22-e7504e585997.png">

therefore we tried the following command: 
`helm install confluent-sr $CHART_PATH \
--set kafka.enabled=false \
--set externalKafka.brokers=\["tls://adress"\] \
--set externalKafka.auth.protocol=tls \
...`

that gives the following Error as expected, since tls is not a protocol. 
<img width="1021" alt="Bildschirmfoto 2023-04-26 um 13 30 42" src="https://user-images.githubusercontent.com/41105397/234563483-01a90152-93fd-4fad-adf3-12adf16e9074.png">

to avoid this we additionally tried setting the parameters as follows: 
`helm install confluent-sr $CHART_PATH \
--set kafka.enabled=false \
--set externalKafka.brokers=\["SSL://adress"\] \
--set externalKafka.auth.protocol=tls \
...`

it still gives us an error: 
<img width="1375" alt="Bildschirmfoto 2023-04-26 um 13 33 06" src="https://user-images.githubusercontent.com/41105397/234563756-0f7de629-a12a-40e6-87a3-7adb7c0738ae.png">

Using SSL in both parameters did help us to get past these java errors, therefore we used them that way. but that led to the issue of the files in /certs not being copied. 

Thank you for helping!:)

**Comment by NDoBln** [comment]
@jotamartos do you gain more insights or could find the bug? If we should test something else let us know.

**Comment by jotamartos** [comment]
I tried to reproduce the issue but it's taking longer than expected. However, checking the information you posted, it seems that the kafkastore.security.protocol parameter is not properly configured in the solution. This function takes care of evaluating the protocols used when accessing Kafka 

https://github.com/bitnami/containers/blob/main/bitnami/schema-registry/7.3/debian-11/rootfs/opt/bitnami/scripts/libschemaregistry.sh#L26

In my case, it returned a valid value 

```
## The security protocol to use when connecting with Kafka
##
kafkastore.security.protocol = SSL
```

the problem I have is that the dummy keystore/truststore I generated is not valid for the IP/domain I'm using but you shouldn't have problems with that. 

These are the changes I made to the values.yaml file 

```
diff --git a/bitnami/schema-registry/values.yaml b/bitnami/schema-registry/values.yaml
index fe4ba31c6..8b3b3c973 100644
--- a/bitnami/schema-registry/values.yaml
+++ b/bitnami/schema-registry/values.yaml
@@ -168,7 +168,7 @@ auth:
     ## 4) Run the command below where SECRET_NAME is the name of the secret you want to create:
     ##       kubectl create secret generic SECRET_NAME --from-file=./kafka.truststore.jks --from-file=./kafka-0.keystore.jks --from-file=./kafka-1.keystore.jks ...
     ##
-    jksSecret: ""
+    jksSecret: "jota-truststore-keystore-sr"
     ## @param auth.kafka.tlsEndpointIdentificationAlgorithm The endpoint identification algorithm used validate brokers hostnames
     ## Disable server hostname verification by setting it to an empty string
     ## See: https://docs.confluent.io/current/kafka/authentication_ssl.html#optional-settings
@@ -176,10 +176,10 @@ auth:
     tlsEndpointIdentificationAlgorithm: https
     ## @param auth.kafka.keystorePassword Password to access the keystore when it's password-protected
     ##
-    keystorePassword: ""
+    keystorePassword: "bitnami"
     ## @param auth.kafka.truststorePassword Password to access the truststore when it's password-protected
     ##
-    truststorePassword: ""
+    truststorePassword: "bitnami"
     ## @param auth.kafka.saslMechanism Mechanism that schema registry will use to connect to kafka. Allowed: PLAIN, SCRAM-SHA-256, SCRAM-SHA-512
     ##
     saslMechanism: PLAIN
@@ -635,10 +635,17 @@ serviceAccount:
 kafka:
   ## @param kafka.enabled Enable/disable Kafka chart installation
   ##
-  enabled: true
+  enabled: false
   ## @param kafka.replicaCount Number of Kafka brokers
   ##
   replicaCount: 1
+  auth:
+    clientProtocol: tls
+    tls:
+      existingSecrets: ["jota-truststore-keystore-sr"]
+  service:
+    ports:
+      client: 9092

 ##
 ## External Kafka Configuration
@@ -648,7 +655,7 @@ externalKafka:
   ## @param externalKafka.brokers Array of Kafka brokers to connect to. Format: protocol://broker_hostname:port
   ##
   brokers:
-    - PLAINTEXT://localhost:9092
+    - SSL://kafka.jotamartos.svc.cluster.local:9092
   ## Authentication parameters
   ## @param externalKafka.auth.protocol                   Authentication protocol. Allowed protocols: plaintext, tls, sasl and sasl_tls
   ## @param externalKafka.auth.jaas.user                  User for SASL authentication
@@ -664,7 +671,7 @@ externalKafka:
     ## | sasl      | Yes (via SASL)                | No                 |
     ## | sasl_tls  | Yes (via SASL)                | Yes                |
     ##
-    protocol: plaintext
+    protocol: tls
     ## JAAS configuration for SASL authentication
     ## MANDATORY when protocol is 'sasl' or 'sasl_tls'
     ##
```

>Note: I'll investigate the reason why I needed to set the kafka.auth and kafka.service blocks when kafka is disabled.

**Comment by NDoBln** [comment]
@jotamartos 

I have checked my values.yaml and configured it the same way as you did in the above post.
Unfortunately I am still receiving an error:

```
> `io.confluent.kafka.schemaregistry.rest.SchemaRegistryConfig:376)
> [2023-05-10 13:08:20,930] INFO Logging initialized @847ms to org.eclipse.jetty.util.log.Slf4jLog (org.eclipse.jetty.util.log:170)
> [2023-05-10 13:08:20,973] INFO Initial capacity 128, increased by 64, maximum capacity 2147483647. (io.confluent.rest.ApplicationServer:619)
> [2023-05-10 13:08:21,094] INFO Adding listener with HTTP/2: http://0.0.0.0:8081 (io.confluent.rest.ApplicationServer:488)
> [2023-05-10 13:08:21,708] ERROR Server died unexpectedly: (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain:53)
> org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
> ... 
> Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /opt/bitnami/schema-registry/certs/schema-registry.keystore.jks of type JKS
> ... 
> Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
> ... 
> Caused by: java.security.UnrecoverableKeyException: Password verification failed`
```

Thus I have debugged my container. 
There I can still see that: in /certs the secrets have been mounted but I have also noticed that the directory /opt/bitnami/schema-registry/certs is empty. Thus, it seems that the copy commands from line 105 & 106 in statefulset.yaml did not work.
![Screenshot 2023-05-10 at 15 15 20](https://github.com/bitnami/charts/assets/93553703/77d28aee-60dd-4acb-bfcb-8f32884d6e65)

**Comment by jotamartos** [comment]
It seems that the password is not configured properly. Can you review the configuration file and confirm that the password is set there? 

https://docs.confluent.io/platform/current/schema-registry/security/index.html#additional-configurations-for-https

**Comment by NDoBln** [comment]
@jotamartos I can confirm that I have set every parameter that you have also set in your values.yaml. So in regard of the passwords I have configured the following parameters:

1. auth.kafka.keystorePassword
2. auth.kafka.truststorePassword
3. auth.tls.keystorePassword
4. auth.tls.truststorePassword

I have also double-check that the keystore / truststore passwords are correct.

**Comment by jotamartos** [comment]
Could you please confirm you are not using existing PVs/PVCs that were created in a  previous deployment? As I mentioned above, the cert files were created when I deployed the solution.

**Comment by NDoBln** [comment]
Hi @jotamartos sorry for the big delay here. 
Regarding your questions:
1) PVs/PVCs are created by the helm chart (so we are not using existing ones)
2) We have created the secrets that contains the corresponding JKS stores as stated in the README. (Note: We use an external Kafka Cluster).

If you have further questions. Please let me know.

**Comment by jeffthompson1971** [comment]
Not sure if this is the same issue.  I'm unable to just launch the SchemaRegistry using docker.   I'm using upstash for my cluster.   I'm able to launch it, but it fails when using SSL.   Is there anything I can do?  Where am I supposed to get these certs to mount?

2023-06-03 14:50:26 schema-registry 19:50:26.61 
2023-06-03 14:50:26 schema-registry 19:50:26.61 Welcome to the Bitnami schema-registry container
2023-06-03 14:50:26 schema-registry 19:50:26.61 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-06-03 14:50:26 schema-registry 19:50:26.61 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-06-03 14:50:26 schema-registry 19:50:26.61 
2023-06-03 14:50:26 schema-registry 19:50:26.61 INFO  ==> ** Starting Schema Registry setup **
2023-06-03 14:50:26 schema-registry 19:50:26.62 INFO  ==> Validating settings in SCHEMA_REGISTRY_* env vars
2023-06-03 14:50:26 schema-registry 19:50:26.63 ERROR ==> In order to configure the TLS encryption for communication with Kafka brokers, you must mount your schema-registry.keystore.jks and schema-registry.truststore.jks certificates to the /opt/bitnami/schema-registry/certs directory.

This is how I run it:

docker run -d --name schema-registry -p 8081:8081 \
  --env SCHEMA_REGISTRY_DEBUG=true \
  --env SCHEMA_REGISTRY_KAFKA_BROKERS=SASL_SSL://assured-gnat-8841-us1-kafka.upstash.io:9092 \
  --env SCHEMA_REGISTRY_KAFKA_SASL_USERS=YXNzdXJlZC1nbmF0LTg4NDEkGKe9h_o5UQJPOERo1zivF8RCm1d_9r9svHpOQHM \
  --env SCHEMA_REGISTRY_KAFKA_SASL_PASSWORDS=2afc4007d2bf4974993ff0ff707dbfbf \
  --volume /var/folders/bitnami:/bitnami \
  bitnami/schema-registry:latest

**Comment by jotamartos** [comment]
Hi @jeffthompson1971,

You need to mount the certs (both truststore and keystore files) in the /opt/bitnami/schema-registry/certs folder for the app to work properly. 

https://github.com/bitnami/containers/blob/main/bitnami/schema-registry/7.4/debian-11/rootfs/opt/bitnami/scripts/libschemaregistry.sh#L303

If you continue running into issues, please create a new support ticket in the [Bitnami's containers repository](https://github.com/bitnami/containers/issues)

**Comment by NDoBln** [comment]
> 

Hi @jotamartos 

thanks for also posting your jks-store secret. 
That was the missing puzzle when it comes to configuring the SSL connection between Confluent Schema Registry and our external Kafka. 
The secret that you have used for the parameter `auth.kafka.jksSecret` consists of trust- and keystore with the name `schema-registry.truststore.jks` and `schema-registry-0.keystore.jks` which is different than the naming convention which is documented in your `values.yaml`. There it says that both stores should have names `kafka.truststore.jks` and `kafka-0.keystore.jks ` 

Now we just have one SSL issue left. How do you configure Confluent Schema Registry to communicate with a client via SSL, thus when you set the following parameters:

- `listeners: https://0.0.0.0:8085` 
- `auth.tls.enabled: true`

How must the jksSecret for the parameter `auth.tls.jksSecret` look like?

Thanks again.

**Comment by jotamartos** [comment]
Hi @NDoBln,

The documentation mentions that you need to use schema-registry.truststore.jks and schema-registry-0.keystore.jks in [this section](https://github.com/bitnami/charts/tree/main/bitnami/schema-registry#enable-authentication-for-kafka). It also mentions the certificates you need to create to deploy Kafka. 

 Regarding the `auth.tls.jksSecret` parameter, it seems it's not used by the chart right now. Would you like to [contribute](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) and make the necessary changes to support it? In the meantime, you will need to use the `.Values.auth.tls.keystorePassword` and `.Values.auth.tls.truststorePassword` parameters. 

https://github.com/bitnami/charts/blob/main/bitnami/schema-registry/templates/statefulset.yaml#L129

**Comment by jotamartos** [comment]
Sorry for the delay here @NDoBln. We recently added many changes to the Kafka chart and will need to review that the changes in that PR are still valid. I'll update this ticket once I have more information.

**Comment by jotamartos** [comment]
Adding the on-hold tag to avoid closing this ticket

**Comment by jotamartos** [comment]
PR is now merged. Version 13.0.2 should be available soon.
