### ISSUE TITLE
use local pvc, node goes down, pod-0 can not restart success

### ISSUE THREAD

**Issue by jisongxi** [bitnami/charts#15783]
### Name and Version

bitnami/etcd 8.7.3

### What architecture are you using?

None

### What steps will reproduce the bug?

If a node goes down, delete PVC (using openebs-hostpath) and pod, allowing PVC and pod to be recreated on another node, but if the server cannot be started, how to solve this scenario? For example, if the 0th pod node goes down.
when pod-0 member not remove from the cluster, the error is :
```
{"level":"fatal","ts":"2023-03-29T02:25:37.699Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"member 3657dab4a6d76e1f has already been bootstrapped","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\tgo.etcd.io/etcd/server/v3/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\tgo.etcd.io/etcd/server/v3/etcdmain/main.go:40\nmain.main\n\tgo.etcd.io/etcd/server/v3/main.go:32\nruntime.main\n\truntime/proc.go:255"}
```

when i remove the pod-0 member_id from the cluster , the error is
```
{"level":"warn","ts":"2023-03-29T02:30:17.808Z","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00024c000/etcd-xx-test-0.etcd-xx-test-headless.songxi-test.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
Error: context deadline exceeded
```

How to solve the issuer, when pod-0 node  goes down

### What is the expected behavior?

If node-0 fails and the PVC is deleted, pod-0 will attempt to pull the pod on another node and rejoin the original cluster, so the service will start normally.

**Comment by jotamartos** [comment]
Hi @jisongxi,

After evaluating your information a bit more, I think we need more information in order to troubleshoot this. Can you answer these questions?

- Are you deploying the solution with custom parameters? Does the same error happen when using the default values?
- Can you reproduce the issue when not using `openebs-hostpath`? 
- There is a preStop hook that removes the node from the cluster when the container is stopped

https://github.com/bitnami/containers/blob/main/bitnami/etcd/3.5/debian-11/rootfs/opt/bitnami/scripts/etcd/prestop.sh

Is the node removed correctly when you drop the pod? 

Thanks
