### ISSUE TITLE
[bitnami/nginx] Add optional config map 

### ISSUE THREAD

**Issue by obeyler** [bitnami/charts#1591]
NEW FEATURE
A good idea for ngnix is to add to the helm chart the opportunity to mount volume by specify configmap to allow static web site

**Comment by rafariossaa** [comment]
Hi @obeyler ,
  Thanks for your request. I have created an internal task to implement it.

**Comment by obeyler** [comment]
thanks @rafariossaa

**Comment by mrfelton** [comment]
This would help me configure http basic auth, for which I need to be able to mount a htpasswd file and tell nginx where it is.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
