### ISSUE TITLE
How often charts get pushed to docker?

### ISSUE THREAD

**Issue by fvogl** [bitnami/charts#16155]
### Name and Version

fluentd, rabbitmq, redis

### What architecture are you using?

amd64

### What steps will reproduce the bug?

At least these 3 charts were updated +20 hours ago, but they are not uploaded to the registry.

### What is the expected behavior?

Charts get pushed to the registry after they get changed in Github.

### What do you see instead?

No updated charts in the registry

**Comment by carrodher** [comment]
Hi, the latest versions were not pushed because it was a special PR modifying all the charts at once (https://github.com/bitnami/charts/pull/15998) and this is not something supported for making a release since it is not possible to test all the charts in a single PR. That was an edge case we were aware of it.

For regular releases, charts are pushed to DockerHub once the different jobs/GH actions in charge of testing and releasing them finish successfully.
