### ISSUE TITLE
bitnami/cassandra Helm chart 10.2.0 not in index or OCI registry

### ISSUE THREAD

**Issue by mprimeaux** [bitnami/charts#16246]
### Name and Version

bitnami/cassandra 10.2.0

### What architecture are you using?

arm64

### What steps will reproduce the bug?

I neither see version `10.2.0` of the [bitnami/cassandra](https://github.com/bitnami/charts/tree/main/bitnami/cassandra/) Helm chart in the index nor is it found in the OCI registry (e.g. `oci://registry-1.docker.io/bitnamicharts/cassandra`)

```shell
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm search repo bitnami/cassandra
❯ helm search repo bitnami/cassandra
NAME             	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/cassandra	10.1.3       	4.1.1      	Apache Cassandra is an open source distributed ...
```

The latest chart seems to be [10.2.1](https://github.com/bitnami/charts/blob/5980213df89719b260c1370bb21febd16e6221aa/bitnami/cassandra/Chart.yaml#L26).

Also, following the OCI registry deployment for the same version indicates that version is also not in the OCI registry.

```shell
helm install my-release oci://registry-1.docker.io/bitnamicharts/cassandra --version 10.2.0
Error: INSTALLATION FAILED: registry-1.docker.io/bitnamicharts/cassandra:10.2.0: not found
```

### Are you using any custom parameters or values?

No.

### What is the expected behavior?

The expected behavior is the chart is deployed.

### What do you see instead?

Please see the repro steps above.

**Comment by carrodher** [comment]
Hi, the latest versions were not pushed because it was a special PR modifying all the charts at once (https://github.com/bitnami/charts/pull/15998) and this is not something supported for making a release since it is not possible to test all the charts in a single PR. That was an edge case we were aware of it.

For regular releases, charts are pushed to DockerHub once the different jobs/GH actions in charge of testing and releasing them finish successfully.

**Comment by mprimeaux** [comment]
Thanks.
