### ISSUE TITLE
Error running python script with Apache Spark

### ISSUE THREAD

**Issue by jordanandres1** [bitnami/charts#1626]
### Chart: 
spark-1.0.11

### Helm version: 
v2.13.0

### Kubernetes version: 
v1.13.12

### Description: 
Error running python script with Apache Spark

### Steps to reproduce:
- Install bitnami chart
- Connect to cluster using telepresence
- Run a script like this one
```
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("spark://spark-master-svc.spark:7077").appName('my_first_app').getOrCreate()
file = spark.read.csv('file.csv')
```

### Result:
The script is running in a loop with this warning (TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources). The workers and the running application appears in the UI but this problem appears.

**Comment by gmatev** [comment]
+1 Same issue here

Tried using older image tags as far back as `2.4.4-debian-9-r34 release` but with no luck

**Comment by jordanandres1** [comment]
This issue is still happening after merge.

**Comment by juan131** [comment]
Hi everyone,

Yes, I can confirm the issue is still there. I also noticed we already have an internal task to fix this issue. I would try to bump its priority so we can work on having a solution asap.

We'll update this issue once we have news.

**Comment by dani8art** [comment]
Hi, I've fixed some error/missing in the NOTES.txt for this chart that could cause this issue, also we should take into account some `spark-submit` restriction.

Spark uses a concept which is called the driver and it is responsible for allocating resources and the communication in the spark cluster during the task executions. The way `spark-submit` executes this driver depends on the value of the `--deploy-mode` flags if you want to run the driver inside the cluster you should use --deploy-mode cluster and all should work correctly. If this flag is not set the driver is running locally, because of that, the connectivity is failing with the workers since the workers have not external IPs. Also, `--deploy-mode cluster` is not supported for Python in a spark standalone cluster so you can not run Python apps from outside the cluster using `spark-submit` and this chart because we are using standalone spark cluster configuration.

Regards.

**Comment by JWDobken** [comment]
What is the status of this issue?

I have the same problem:

- kubernetes: v1.15.7
- Helm: v3.1.0
- Chart: 1.2.7

**Comment by dani8art** [comment]
Hi @JWDobken ,

As I said, that is a matter of how spark works, you can read also some of my comments in this other issue https://github.com/bitnami/charts/issues/1775#issuecomment-572513554 that can help you to deal with it. 

Regards.

**Comment by jpellman** [comment]
Hi @dani8art/@beltran-rubo,

Being able to use client deploy mode / interactive Spark shells is desirable for a number of reasons (e.g., connecting a Jupyter notebook pod that was deployed using JupyterHub with a standalone cluster).  I think that it's worth re-opening this issue and exploring it in further depth.

Unless I'm missing something, it should be possible to enable client deploy mode by exposing the workers as services internally using the `ClusterIP` class.  This would allow bidirectional connectivity between the client-side driver program and the worker pods, which is necessary according to the following diagram (from [here](https://spark.apache.org/docs/latest/cluster-overview.html#components)):

![image](https://spark.apache.org/docs/latest/img/cluster-overview.png)

Furthermore, according to [here](http://spark.apache.org/docs/latest/security.html#all-cluster-managers), the bidirectional edges between the client-side driver and the worker pods in the above diagram represent communication needed for the Spark Block Manager port.  The Spark Block Manager port is normally a random port, but if it is configured to be a specific port in the Spark configuration, it can then be exposed on that specific port via `ClusterIP`.  Does this sound right to you?

**Comment by jpellman** [comment]
My apologies, my earlier comment is the result of a misconception about how Kubernetes does networking.  I ultimately figured out how to get PySpark working within a pod managed by JupyterHub in my comment [here](https://github.com/bitnami/charts/issues/2946#issuecomment-949015598).
