### ISSUE TITLE
[bitnami/rabbitmq] Upgrade needs passwords

### ISSUE THREAD

**Issue by elwood218** [bitnami/charts#16273]
### Name and Version

bitnami/rabbitmq 11.14.2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

We use helmfile for upgrading and the passwords are set via secrets:
```yaml
auth:
  ...
  existingPasswordSecret: rabbitmq-pass
  existingErlangSecret: rabbitmq-pass
```

When trying to upgrade it wants the `auth.password` to be set. Why?? Why it just doesn't read the current values from the secret? Don't understand that part. Also, the link to your documentation does not really explain it to me.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Helm should just upgrade and use the defined values.

### What do you see instead?

```
STDERR:
  Error: Failed to render chart: exit status 1: Error: execution error at (rabbitmq/templates/secrets.yaml:4:17):
  PASSWORDS ERROR: You must provide your current passwords when upgrading the release.
                   Note that even after reinstallation, old credentials may be needed as they may be kept in persistent volume claims.
                   Further information can be obtained at https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases
      'auth.password' must not be empty, please add '--set auth.password=$RABBITMQ_PASSWORD' to the command. To get the current value:
```

**Comment by CeliaGMqrz** [comment]
Hi @elwood218,

Sorry for the delay. 

Passwords are required during the upgrade process because they may be stored in persistent volume claims, and Helm needs the current values to ensure a successful upgrade. In the guide, you can see an example to resolve credential errors during the upgrade of chart versions.

You can get your current password:
```
    echo "Password : $(kubectl get secret --namespace default rabbitmq-pass -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
    echo "ErLang Pass : $(kubectl get secret --namespace default rabbitmq-pass -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"
```

You can use the `--set auth.password=<your-current-password>` flag to upgrade the chart. Make sure that the secret contains the key that exists in your namespace `kubectl get secrets -n <your-namespace>` `kubectl describe secrets/rabbitmq-pass -n <your-namespace>`

**Comment by joywaves** [comment]
I have the same issue in 11.5.5 or 11.5.7. Does anyone has a fix for it?
