### ISSUE TITLE
[bitnami/kafka] setup stuck at formatting

### ISSUE THREAD

**Issue by n5nk** [bitnami/charts#16384]
### Name and Version

bitnami/kafka3.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

As part of the kafka cluster upgrade from 2.8 to 3.4

1.  I see the setup just stucks at formatting the storage prompt.
Saw few websites which say we need to format the log location inorder to proceed, the same happened when i tried the bare kafka setup in local.

    ```
    kafka-storage format --config server.properties --cluster-id 5MB5lq-XT-6JzQqJeIuhWQ
    Formatting /tmp/kafka-logs/ with metadata.version 3.3-IV3.
    ```

Can bitnami confirm if storage formatting is required as part of the upgrade, if yes, why the chart doesnt include it.

2. Since we need to perform this above formatting, what would bitnami suggest the best place to run the command. Since it requires server.properties, which are built dynamically as part of bitnami/kafka chart.

### Are you using any custom parameters or values?

No, just enabled raft. But I have a previous version of kafka 2.8

### What is the expected behavior?

Setup should complete.

### What do you see instead?

The setup stucks after starting kafka server
<img width="1022" alt="Screenshot 2023-05-04 at 9 50 12 PM" src="https://user-images.githubusercontent.com/119731738/236264190-19bc46d0-0712-48ab-aa59-2204d8e0a77e.png">

**Comment by jotamartos** [comment]
>Can bitnami confirm if storage formatting is required as part of the upgrade, if yes, why the chart doesnt include it.

The _kafka-storage format_ command is executed every time the container/chart is deployed

https://github.com/bitnami/containers/blob/main/bitnami/kafka/3.4/debian-11/rootfs/opt/bitnami/scripts/libkafka.sh#L801

If the process is stuck there, it may be due to some incompatibility between those 2 versions or just because you have a big amount of data and it takes time to format it. You can try to obtain more information by enabling the image.debug parameter and see if more information is logged

https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml#L97

As a final note, I suggest you upgrade to version 21.x of the chart first to not to make 2 changes at the same time. Upgrading to version 21.x will upgrade the Kafka version without enabling Kraft. Version 22.x enables Kraft by default and you can upgrade the deployment to that version later.
