### ISSUE TITLE
unable to connect redis pod from different k8s clusters

### ISSUE THREAD

**Issue by abhishekGupta2205** [bitnami/charts#16436]
### Name and Version

bitnami/redis , latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

helm install redis redis

### Are you using any custom parameters or values?

1) sentinel enabled
2) nodeport enabled
3) use hostname =false

### What is the expected behavior?

i want that when i enable nodeport , my pod should be connectible from different k8s clusters . i have disabled use hostname parametr to avoid tilting issue . 

### What do you see instead?

after applying all these above changes , my java service is able to connect to sentinel which in turns return the address of master pod . when disabling use hostname option , sentinel returns address in form of internal pod ip which is connectible from java services which are present inside same k8s cluster . but that pod ip is not accesssible from a differnt cluster .so in short i mean i want hostname in sentinel masters fields ip  but cannot use it due to tilting issue

### Additional information

![image](https://user-images.githubusercontent.com/68244292/237001784-0279aff5-71bc-4914-be60-d50dc2910fc6.png)
this is the output of sentinel masters command .

**Comment by rajivmishra-123** [comment]
so how can i make my redis pod connectible from outside . when using hostaname , ip would be returned in format redis-node-0-namespace . for this case i can make dns entry in my hostfile and this dns can be easily accessible from anywhere. but now ip is in form of pod ip which is changing . so the above approach cannot be used .

**Comment by migruiz4** [comment]
When deploying the Helm chart some installation notes appear in the console showing information about how to connect/access the application based on the parameters you used to deploy the Helm chart. You can see those notes at any time after the installation by running helm get notes RELEASE_NAME.

In the case of bitnami/redis, there is a section explaining how to connect from outside the Kubernetes cluster:
```
To connect to your database from outside the cluster execute the following commands:

    export NODE_IP=$(kubectl get nodes --namespace default -o jsonpath="{.items[0].status.addresses[0].address}")
    export NODE_PORT=$(kubectl get --namespace default -o jsonpath="{.spec.ports[0].nodePort}" services myrelease-redis)
    REDISCLI_AUTH="$REDIS_PASSWORD" redis-cli -h $NODE_IP -p $NODE_PORT
```

**Comment by migruiz4** [comment]
Hi @rajivmishra-123,

Thank you for the extended details about the issue. I do now see what the problem is.

I do see now that the issue is not about connecting a Redis client from outside the client, but a Java application that needs to connect with Sentinel first collects the Redis master IP from it, and then uses that IP to connect with Redis.

In that case, the only supported solution at the moment would be using the `useExternalDNS.enabled` feature, which relies on an 'external-dns' deployment to configure DNS addresses for the Redis nodes.

The root cause of the problem here is that Redis requires a `replica-announce-ip` that is reachable both internally and externally in Kubernetes, and the only method that met that requirement would be `useExternalDNS`.

The value of `replica-announce-ip` is set using the following logic:
```
get_full_hostname() {
        hostname="$1"

        {{- if .Values.useExternalDNS.enabled }}
        full_hostname="${hostname}.{{- include "redis.externalDNS.suffix" . }}"
        {{- else if eq .Values.sentinel.service.type "NodePort" }}
        full_hostname="${hostname}.{{- .Release.Namespace }}"
        {{- else }}
        full_hostname="${hostname}.${HEADLESS_SERVICE}"
        {{- end }}

        {{- if .Values.useHostnames }}
        echo "${full_hostname}"
        {{- else }}
        retry_count=0
        until getent hosts "${full_hostname}" | awk '{ print $1; exit }' | grep .; do 
            if [[ $retry_count -lt {{ .Values.nameResolutionThreshold }} ]]; then
                sleep {{ .Values.nameResolutionTimeout }}
            else
                error "IP address for ${full_hostname} not found"
                exit 1
            fi
            ((retry_count++))
        done
        {{- end }}
    }
```

In other words, that leaves us with the following scenarios
- If `useExternalDNS.enabled=true` and `useHostnames=true` -> 'replica-announce-ip pod-N.external-dns-suffix'
- If `useExternalDNS.enabled=true` and `useHostnames=false` -> 'replica-announce-ip <external_IP>' (IP obtained by resolving the DNS 'pod-N.external-dns-suffix'.
---
- Else If using`service.type=NodePort` and `useHostnames=true` -> 'replica-announce-ip pod-N.Namespace'
- Else If using`service.type=NodePort` and `useHostnames=false` -> 'replica-announce-ip <Internal_IP>' (Nodeport service 'Cluster-IP').
---
- Else If using`service.type=NodePort` and `useHostnames=false` -> 'replica-announce-ip pod-N.headless-svc' 
- Else If using default service type (ClusterIP) and `useHostnames=false` -> 'replica-announce-ip <Internal_IP>' (Pod IP).

**Comment by rajivmishra-123** [comment]
@migruiz4 , thanks for detailed solution . can you tell how can i use the external dns concept here and also is there any other solution that might be comig in next helm chart releases

**Comment by migruiz4** [comment]
You can find that information in the following section of the `bitnami/redis` README.md: https://github.com/bitnami/charts/blob/main/bitnami/redis/README.md#external-dns

For more information about how to deploy `external-dns` I would recommend checking the following links:
- README.md of bitnami/external-dns chart: https://github.com/bitnami/charts/tree/main/bitnami/external-dns
- Upstream external-dns projectL https://github.com/kubernetes-sigs/external-dns
- This page on how to configure ExternalDNS from our documentation: https://docs.bitnami.com/kubernetes/infrastructure/external-dns/configuration/dns-provider-requirements/

---

> is there any other solution that might be comig in next helm chart releases .

I don't think a different solution would be feasible with Redis current features. 
As I mentioned, the requirement in this case is having a single IP or hostname per node that is reachable both internally and externally. That requirement is not met by any Kubernetes methods (Load balancers, NodePorts, etc.), at least that I can think of at the moment.

The only workaround I can think of would be, if `useHostnames=true`, use `/etc/hosts` on your Java application host to translate the service name into the Kubernetes IP:
```
test-redis:26379> sentinel masters
1)  1) "name"
    2) "mymaster"
    3) "ip"
    4) "test-redis-node-0.default"
    5) "port"
    6) "30003"
...
```
On the client side `/etc/hosts`:
```
X.X.X.X       test-redis-node-0.default
```

**Comment by migruiz4** [comment]
Could you please provide more details on that tilting issue? I haven't experienced that behavior while deploying the chart in the different methods I mentioned before.

**Comment by rajivmishra-123** [comment]
@migruiz4  pls refer this https://github.com/bitnami/charts/issues/9689

**Comment by migruiz4** [comment]
Thanks for pointing that issue out. 
After reading the thread and based on the results obtained by users, I would say the issue might be caused by a bug in the Redis Sentinel source and not our image/chart.

Quoting the comment that helped us come up with a solution:
> Somehow https://github.com/bitnami/charts/compare/master...maxfilov:charts:master?diff=split made our redis/sentinel stable. From tilting every ~5m to days of uptime.
  This patch makes the redis and sentinels announce themselves using their pod ip instead of their domain name. There might be some strange interactions between sentinel and the way rke2 handle DNS names resolution

**Comment by abhishekGupta2205** [comment]
@migruiz4 , In #9689 , we see that due to tilting issue , i can not use hostname feature, which is necessary if i want to connect to redis from outside kubernetes cluster . i need an ip and port which is accessible from anywhere . is there any alternate solution you can suggest for it

**Comment by abhishekGupta2205** [comment]
this is a problem many users will be facing as we cannot bring everything in same k8s 
cluster

**Comment by migruiz4** [comment]
Hi @abhishekGupta2205!

I have shared my finding regarding the `tilt-mode` issue at https://github.com/bitnami/charts/issues/7431#issuecomment-1588823024.

As mentioned there, while the `tilt-mode` appears to be aggravated by the `useHostname=true`, its root cause is 'Redis Sentinel spent more than 2 seconds frozen', which I think could be caused by either slow storage, CPU starvation (which would explain why using IPs partially solves the issue) or heavy workloads.

As an alternative to `useHostname=false`, could you please try increasing the resources of the sentinel container using `sentinel.resources` to see if the tilting issue persists?

**Comment by migruiz4** [comment]
Hi @abhishekGupta2205,

In order to help us further investigate the 'tilt-mode' issue, could you please share what kind of storage are you using in your deployment? 

As mentioned, the cause for the 'tilt-mode' appears to be slow performance, but we have yet to discover what could be causing it, we suspect it could either be caused by low resources, slow I/O, or caused by the Redis or Sentinel Settings.

**Comment by abhishekGupta2205** [comment]
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

this is my storage class yaml file .  i am enabling persistence volume =true . is it what you want or you want to know something else

**Comment by abhishekGupta2205** [comment]
@migruiz4  any update

**Comment by migruiz4** [comment]
I'm sorry for the late response.

I see you are using 'Local' type volumes (https://kubernetes.io/docs/concepts/storage/storage-classes/#local) meaning that the storage is located locally in your Kubernetes host.

Could you please provide more details about what type of backend filesystem are you storing those volumes? 
- Is it the host hard drive or maybe are you using some kind of shared filesystem like NFS?
- Are you running any other I/O intensive application in the same Kubernetes cluster?

As mentioned before, 'tilt-mode' would not be related to the image or the chart logic, but to system resource limitations that cause stored timestamp to differ from computational timestamp to more than 2 seconds.
