### ISSUE TITLE
[bitnami/cassandra] database migrate to new cluster

### ISSUE THREAD

**Issue by devopsdymyr** [bitnami/charts#1658]
BUG REPORT INFORMATION
-------------------------------

**Which chart**:

Bitnami/cassandra 
**Description**

How to export database from cassandra and migrate to my new cassandra database

**Describe the results you received:**

Required some detailed documentation on migration from cassandra to cassandra

**Describe the results you expected:**

How to take backup and restore to cassandra .

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v2.14.3
```

**Comment by javsalgar** [comment]
Hi,

This question is more related to how cassandra works rather than the helm chart itself. My recommendation would be to export the data and then import it to the new cluster. I found these links that may help with that.

https://stackoverflow.com/questions/16440606/import-and-export-schema-in-cassandra
https://www.datastax.com/blog/2012/07/simple-data-importing-and-exporting-cassandra

Hope it helps.

**Comment by devopsdymyr** [comment]
Thanks ,let me check above links
