### ISSUE TITLE
[bitnami/redis-cluster] When k8s service + statefullset forwards a write request to the slave pod, will the slave pod execute the request successfully?

### ISSUE THREAD

**Issue by QQandWX** [bitnami/charts#16726]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

None

### What steps will reproduce the bug?

i didn't test

### What do you see instead?

Hello, I have a question, but now I don't have an environment to test. 
As I know, the Slave pod of the redis-cluster can not write the database, and can not execute the write request, only the Master pod can.
According to Bitnami/redis-cluster, uses service+statefulset to build 6 Redis PODs, including three masters and three slaves. When there is a request that is prepared to write a database, the k8s service forwards it to the slave pod, will the slave node execute successfully? I think k8s services don't know which pod is master. Or the slave pod would forward the write request to the Master Pod?
thank you so much for your advice.

**Comment by QQandWX** [comment]
Hi @aoterolorenzo
   So, even without using K8S to deploy cluster ,  when a write request is sent to slave, the slave will also route it to master? Does this phenomenon also occur in Sentinel mode [bitnami/redis]？

   I don't have a Redis Cluster in my environment, but i have a Redis Sentinel. I access  redis sentinel slave using command : redis-cli  , and try to set a data , but failed： Can not set data in slave node.  
   So when i using  [bitnami/redis] to deploy a Redis Sentinel ,  a write request is sent to k8s service+statefulset,  and it be forwarded to slave pod by k8s service, whether the slave pod can execute write requests successfully like my environment's Redis Sentinel?

**Comment by aoterolorenzo** [comment]
In that case, the slave pod will not reject the request but, instead, it will forward the request to the master node responsible for handling write operations within the cluster.

**Comment by QQandWX** [comment]
So when i set data in slave by using redis-cli command, it will fail. but in k8s redis cluster, a write request to slave pod will be executed successfully.   
So  redis-cli fail,   k8s success.
What is the difference between using redis-cli to write data and using k8s to wirte data? 
thank you

**Comment by aoterolorenzo** [comment]
@QQandWX `redis-cli` is just the tool to interact with a instance or a cluster of Redis instances. So this means that the networking and the configuration that you implement in them, is always independent of the tool and on your own customization. The helm chart provides you a functional cluster with a pre-set networking.

So if you configure a local set up of Redis instances implementing High Availability, you will be able to configure the nodes in order to interact through themselves and forward your example request.

**Comment by QQandWX** [comment]
hi 
its so hard for me to understand you point.  is that  if i configure a local set up of Redis instances, i should recognize requests and then forward the write requests to Redis-Master by myself. And if i use helm chart in k8s,  this job will be done by k8s , but how k8s do this.

i am still so confused.

**Comment by aoterolorenzo** [comment]
> hi its so hard for me to understand you point. is that if i configure a local set up of Redis instances, i should recognize requests and then forward the write requests to Redis-Master by myself. And if i use helm chart in k8s, this job will be done by k8s , but how k8s do this.
> 
> i am still so confused.

Yes, is exactly that. I think at this point you may need to refer the [Redis documentation](https://redis.io/docs/) and the [High Availability for Redis Sentinel](https://redis.io/docs/management/sentinel/) (high availability when not using Redis Cluster). Also you may want to take a look at a Redis Cluster set up documentation.

**Comment by rafariossaa** [comment]
Hi, 
  Could you indicate the command and parameters you used to start the redis cluster ?

**Comment by QQandWX** [comment]
I made very few changes，in values.yaml , i only changed storageClass，service NodePort， and image registry
1、storageClass: "local-storage"
2、service:
  type: NodePort
  nodePorts:
    redis: "31379"

and i use local pv.

commands:
kubectl create -f local-pv.yaml
kubectl create -f redis-cluster-pv.yaml
helm install redis-cluster redis-cluster/

zips:
local-pv.yaml
redis-cluster-pv.yaml
values.yaml
[my-yaml.zip](https://github.com/bitnami/charts/files/11623244/my-yaml.zip)

**Comment by rafariossaa** [comment]
Hi,
  According to [redis documentation](https://redis.io/docs/reference/cluster-spec/#moved-redirection), that error (`(error) MOVED 1180 10.233.97.59:6379`) means that the server is redirecting the client to that (`97.59`) node. 
  In order to follow the redirection, you need to use the `-c` parameter in the client:
```
$ redis-cli --help

  -c                 Enable cluster mode (follow -ASK and -MOVED redirections).
```

  When you use the service, underneath it forwards the request to one of the pods, usually in round robin, so there are chances that you hit a node that is able to fulfill your request and it is not redirected to other node.

**Comment by QQandWX** [comment]
Hi
But according to what I said above.

I had used -c parameter in client outside the k8s , but get fail: 

root@gsta:/data# redis-cli -c -h 10.225.2.21 -p 31379 -a 123
Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
10.225.2.21:31379> get aa
-> Redirected to slot [1180] located at 10.233.97.59:6379
Could not connect to Redis at 10.233.97.59:6379: Connection timed out
Could not connect to Redis at 10.233.97.59:6379: Connection timed out
(260.37s)

10.225.2.21 is my k8s node ip

**Comment by rafariossaa** [comment]
That is because the client is not able to reach `10.233.97.59` because it is outside the cluster.
What I meant is that there is a chance when using the service's IP, that you hit the right node and you don't get the error because you are not being redirected.
If those IPs are not reachable by the client you are going to get the `Connection timed out` errors.
