### ISSUE TITLE
[bitnami/minio] Deploy Minio chart as a NAS gateway

### ISSUE THREAD

**Issue by robertgates55** [bitnami/charts#1698]
I’d like to run minio as a NAS gateway. I’ve previously used the official minio helm chart to do this, but would like the security benefits of the bitnami charts.

Could the present charts be configured to run in that mode?

**Comment by alemorcuq** [comment]
Hi, @robertgates55.

At the moment we don't support this mode. Looking [at their documentation](https://docs.min.io/docs/minio-gateway-for-nas.html), it should be possible to do that since it seems to be a matter of changing the command.

I will create an internal task to discuss and implement it. I can't give you an ETA on this. though. PRs are welcome too, in case you want to contribute.

Thank you very much for your feedback.

Regards,
Alejandro

**Comment by harshavardhana** [comment]
> I’d like to run minio as a NAS gateway. I’ve previously used the official minio helm chart to do this, but would like the security benefits of the bitnami charts.

What are the security benefits which exist in bitnami which do not exist on official minio helm chart? can you outline them?

**Comment by beltran-rubo** [comment]
Hi @harshavardhana, Bitnami developer here. In the case of Minio I do not think there are major differences. The official Minio Helm Chart is maintained up-to-date and that is what we focus on Bitnami to provide for the whole catalog. 

There are some differences but those are more related to the Bitnami standardization rather than security specifically. E.g. The official Minio Docker image is based on Alpine and Bitnami one is based on Debian. The Minio official image uses the 'root' user by default but the securityContext of the Chart deploys it with non-root privileges, so no difference.

Any suggestions or PR for improving the Helm Chart will be welcome, thanks.

**Comment by WebSpider** [comment]
@harshavardhana @beltran-rubo This may have become more urgent, given the deprecation notice of the Minio official chart here:

https://github.com/minio/charts/blob/8.0.6/README.md

They are moving to an operator model, which also doesn't have gateway functionality btw.

**Comment by javsalgar** [comment]
Thanks for letting us know! I will forward this to the team for evaluation. In case you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by juan131** [comment]
Hi everyone,

I just want to let you know that we just released a new version of the chart (6.4.0) that adds support to deploy MinIO(R) as a Gateway for other storage systems.

Please give it a try when you have a chance and provide us feedback.
