### ISSUE TITLE
Prompted for username and password when connecting to EKS

### ISSUE THREAD

**Issue by guytz72** [bitnami/charts#17097]
### Name and Version

None

### What architecture are you using?

None

### What steps will reproduce the bug?

Follow this guide https://docs.bitnami.com/aws/get-started-eks/, and at the end of Step 5 run the below: 

kubectl get svc

I get prompted for a username then a password.

### Are you using any custom parameters or values?

No

### What is the expected behavior?

The command outputs the below without a username/pwd prompt

https://capture.dropbox.com/VWHTFEflAFubIggF

### What do you see instead?

https://capture.dropbox.com/B2tbONV4qeuVjvW0

**Comment by joancafom** [comment]
Hi @guytz72 

What is the version of `kubectl` you are using? Could you please execute the following commands and report their output?

```bash
$ which kubectl
$ kubectl version
$ kubectl config current-context
```

**Comment by joancafom** [comment]
Hi!

It seems to me that this may be related to the `kubectl` tool in use. You are using the `kubectl` that's included with your Docker installation instead of a standalone binary.

Please, follow the same guide (which references some steps) to install the standalone binary instead. Once done, please validate the installation by performing the following:

```bash
$ which kubectl
/usr/local/bin/kubectl
```

The output should be `/usr/local/bin/kubectl` instead of `/Applications/Docker.app/Contents/Resources/bin//kubectl`
