### ISSUE TITLE
JCasC config via ConfigMap with jenkins.yaml?

### ISSUE THREAD

**Issue by schnitzlein** [bitnami/charts#1715]
JCasC config via ConfigMap with jenkins.yaml?

It would be nice to use this kind of setup.
Maybe you have it already done ?

**Comment by dani8art** [comment]
Hi @schnitzlein 

Sorry, we do not support this kind of configuration yet, currently, you can configure just `jenkinsUser`,  `jenkinsPassword`, `jenkinsHome`, `disableInitialization` or `javaOpts` as you can see on https://github.com/bitnami/charts/tree/master/bitnami/jenkins#parameters

I will proceed to create an internal task to evaluate supporting custom configuration via JCasC and ConfigMap. Thanks so much for your feedback. We'll keep you updated about our advances.

Regards.

**Comment by jeffellin** [comment]
Is this being worked on in any form?  I ended up not using the bitnami chart since this wasn't supported.

**Comment by alemorcuq** [comment]
Hi, @jeffellin. We don't install the `configuration-as-code` plugin by default, but if you install it you can use the `extraEnvVars`, `extraDeploys`, `extraVolumes` and `extraVolumeMounts` to deploy a ConfigMap with your configuration, mount it to the pod and define the environment variable the plugin expects.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
