### ISSUE TITLE
Upgrade all redis images from Debian Bullseye to Bookworm to resolve CVE-2019-8457

### ISSUE THREAD

**Issue by MartijnPDirekt** [bitnami/charts#17282]
### Name and Version

bitnami/redis*

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Use bookworm instead of bullseye.

### What do you see instead?

https://github.com/bitnami/containers/blob/main/bitnami/redis/7.0/debian-11/Dockerfile

### Additional information

Please also have a look at the below websites, describing the issue/solution in a bit more detail. 
https://security-tracker.debian.org/tracker/CVE-2019-8457
https://github.com/advisories/GHSA-p4jx-5p2x-4pq7

**Comment by MartijnPDirekt** [comment]
https://github.com/bitnami/minideb/pull/149
It should be supported based on the above PR

**Comment by carrodher** [comment]
Hi, as you rightly said, those security vulnerabilities are not fixed by the OS in Debian 11, so although we built the images on a regular basis to provide the latest version of system packages, this kind of CVE will be reported while there is no new version patching the issue in the OS. [Here](https://docs.bitnami.com/kubernetes/open-cve-policy/) you can find more info about this topic.

At this moment, the Bitnami Application Catalog (OpenSource) is based on Debian 11 but Bitnami, as part of VMware, provides a custom container and Helm Charts catalog based on the desired base image (generic distro such as Debian 10 & 11, CentOS 7, PhotonOS 3 & 4, Ubuntu 18.04, 20.04 & 22.04, RedHat UBI 8 & 9, or custom golden image) through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

Debian 12 will be added as a selectable distro in VMware Application Catalog, in the case of the Bitnami Application Catalog, it's likely at some point we move the base image from Debian 11 to 12, but I can't provide an estimation about when this will happen.

**Comment by MartijnPDirekt** [comment]
@carrodher, thanks for your reply, it somewhat satifies. Anywhere I can track progress on upgrading to Debian 12, apart from this ticket. If so, this one can be closed.

**Comment by carrodher** [comment]
Unfortunately, since there is not something we are working on at this moment, there is no place to track the process. We can keep this ticket on-hold and update it when we have some news to share

**Comment by carrodher** [comment]
At this moment, the Bitnami Application Catalog (OpenSource) is built on Debian 11.
As part of VMware, Bitnami offers a custom container and Helm Charts catalog through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog). Debian 12 is available as one of the base images in this catalog.

There are plans to incorporate Debian 12 into the Bitnami OpenSource catalog as well. Unfortunately, a specific ETA for the Debian 12 integration cannot be provided due to other priorities within the team.
