### ISSUE TITLE
[bitnami/kafka] Understanding the Different Tags for Bitnami Kafka Docker Images

### ISSUE THREAD

**Issue by bharathreddy901** [bitnami/charts#17358]
### Name and Version

bitnami/kafka

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hi Team - I wanted to discuss the various tags available for the Bitnami Kafka Docker images and clarify their differences. Understanding these tags will help us make informed decisions when selecting the appropriate image for our use case.

Please let us know what is the difference between the images below.
```
docker pull bitnami/kafka:latest
docker pull bitnami/kafka:3.5.0-debian-11-r0
docker pull bitnami/kafka:3.5.0
docker pull bitnami/kafka:3.5-debian-11
```
Thanks

### What do you see instead?

Understanding the Different Tags for Bitnami Kafka Docker Images

**Comment by javsalgar** [comment]
Hi,

The following tags are floating, and will point to the latest version inside the branch.

```
docker pull bitnami/kafka:latest
docker pull bitnami/kafka:3.5.0
docker pull bitnami/kafka:3.5-debian-11
```

If you pull the image again, you may get a different image.

This one is immutable, and will never be updated.

```
docker pull bitnami/kafka:3.5.0-debian-11-r0
```

In production, our recommendation is to stick with immutable images and manually update the tag to ensure that there are no unexpected issues because of an unwanted image update.

**Comment by bharathreddy901** [comment]
Thanks for the update @javsalgar.
