### ISSUE TITLE
[bitnami/elasticsearch] failed to obtain lock on /bitnami/elasticsearch/data

### ISSUE THREAD

**Issue by meisamhasani** [bitnami/charts#17449]
### Name and Version

bitnamicharts/elasticsearch

### What architecture are you using?

None

### What steps will reproduce the bug?

1.kuber
2.helm install

### Are you using any custom parameters or values?
```
helm install elasticsearch . --set master.persistence.storageClass=nfs-elastic --set data.persistence.storageClass=nfs-elastic --set global.elasticsearch.service.name=master --set service.type=NodePort --set service.nodePorts.restAPI=30020 --set global.storageClass=nfs-elastic --set master.replicaCount=1 --set data.replicaCount=0 --set coordinating.replicaCount=0 --set ingest.replicaCount=0
```

### What do you see instead?

![image](https://github.com/bitnami/charts/assets/2770416/40853a56-0630-45d4-b5f5-e8f3f4ff35cc)

**Comment by javsalgar** [comment]
Hi,

It seems to be a permissions issue due to non-root containers. Could you try using `volumePermissions.enabled=true`?

**Comment by meisamhasani** [comment]
i set volumePermissions.enabled=true , result is:

![image](https://github.com/bitnami/charts/assets/2770416/2a75f9fc-6814-4b01-8c82-32deffd43f0b)

**Comment by joancafom** [comment]
Hi @meisamhasani 

I have found multiple threads in the official ES forum discouraging the usage of NFS drives for the product, for instance:

https://discuss.elastic.co/t/why-nfs-is-to-be-avoided-for-data-directories/215240  
https://discuss.elastic.co/t/does-elasticsearch-not-support-nfs-as-data-directory/311692

The last one has a similar error to what you are experiencing, so I guess this is something at application level rather than to the chart itself.

**Comment by zibuyule** [comment]
@joancafom 
Hi!

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-path

"Elasticsearch requires the filesystem to act as if it were backed by a local disk, but this means that it will work correctly on properly-configured remote block devices (e.g. a SAN) and remote filesystems (e.g. NFS) as long as the remote storage behaves no differently from local storage. You can run multiple Elasticsearch nodes on the same filesystem, but each Elasticsearch node must have its own data path."

**Comment by joancafom** [comment]
> But how can i differentiate the path according to this chart.

I'm not sure I fully understand. Could you please further explain what you refer to by that?

**Comment by sarathskumar** [comment]
@joancafom 
Last week we have an issue with EKS nodes so that our elasticsearch cluster got restarts. After EKS nodes up, then the elasticsearch master nodes and data nodes are throwing this error **(fatal exception while booting Elasticsearch java.lang.IllegalStateException: failed to obtain node locks, tried [/bitnami/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?**)

As per the above threads i understood we need to change the datapath but it will lost our current data right. How can i take the existing data to the newly changed datapath.

**Comment by joancafom** [comment]
Hi again,

>As per the above threads i understood we need to change the datapath

I'm not sure what threads you are referring to. The support threads from the official Elasticsearch team are related to using a NFS drive to store the data. If you are doing this, please be aware that the asset discourages this practice, and it might be the root issue under your problem.

If you are not using a NFS drive, please make sure the volume is properly mounted and that is writable. Also, ensure that there is no other pod/process that has acquired the lock on that same path.

> As per the above threads i understood we need to change the datapath but it will lost our current data right

I'm not really sure where this is coming from though. Nevertheless, the path where the data is stored does not seem to be directly configurable in the chart.
