### ISSUE TITLE
Need more documentation on installing themes and additional plugins

### ISSUE THREAD

**Issue by mwoodpatrick** [bitnami/charts#17536]
### Name and Version

bitnami/wordpress-16.1.25

### What is the problem this feature will solve?

Be able to set up a WordPress site with a specific theme (possibly coming from a source like GitHub) and a custom set of plugins. 

### What is the feature you are proposing to solve the problem?

It would be very helpful if the docs for the chart provided more information on how to configure the values.yaml file to set up a WordPress site with a specific theme (possibly coming from a source like GitHub) and a custom set of plugins. The docs just defines wordpressPlugins as being an array of plugin names or the value "all". Its not clear what the exact naming should be or what plugins are implied by "all". It would be useful to show the equivalent specification of the array as the expanded list of what all maps to and how to add additional plugins like Gutenberg or "simple history" and how to specify the theme for the site. In general a more detailed tutorial showing the usage of more of the advanced values for automating site setup would be very helpful. I did a web search but all the examples I saw of using the chart are all pretty simple. 

Similarly I did not see an example of specifying the storageClass for the chart, an example using e.g. Open EBS or more details on what is expected here and how to validate values file would be useful.

**Comment by mwoodpatrick** [comment]
A pointer to the wordpress wp cli docs e.g.:

https://developer.wordpress.org/cli/commands/plugin/list/

and use of a few kubectl commands gives me the names I was looking for:

````
WORDPRESS_POD_NAME=`kubectl get pods --selector=app.kubernetes.io/name=wordpress -o jsonpath='{.items[*].metadata.name}'``

k exec $WORDPRESS_POD_NAME -- wp plugin list --status=active --format=table
name    status  update  version
akismet active  none    5.2
all-in-one-wp-migration active  none    7.76
all-in-one-seo-pack     active  none    4.4.1
amp     active  none    2.4.1
bbpress active  none    2.6.9
google-analytics-for-wordpress  active  none    8.17
hello   active  none    1.7.2
jetpack active  none    12.3
simple-tags     active  none    3.8.0
w3-total-cache  active  none    2.3.3
wp-mail-smtp    active  none    3.8.0
```

It would be good to include the list of plugins that get installed

**Comment by andresbono** [comment]
Thank you for your proposals, they look interesting additions. Why don't we start with the one about "wordpressPlugins: all" not being clear? It seems the most simple improvement.

In the end, what `wordpressPlugins` does it to populate the `WORDPRESS_PLUGINS` env-var in the [bitnami/wordpress](https://github.com/bitnami/containers/tree/main/bitnami/wordpress) container.

Would it make sense for you to add a note (probably in both the container and chart READMEs) explaining how to obtain the full list of plugins to activate when the value `all` is set? I'm proposing this because adding the list of plugins directly might become difficult to maintain and if we add/remove some of the plugins, we might forget to update the README.

**Comment by mwoodpatrick** [comment]
I will review how best to get this list and create some instructions that I will post here first for review and we can go from there.

**Comment by andresbono** [comment]
Great, that makes sense. Thank you!

**Comment by mwoodpatrick** [comment]
This is still on my todo list and hope to have an update soon
