### ISSUE TITLE
[bitnami/thanos] Missing metrics for Thanos Compactor when running as CronJob

### ISSUE THREAD

**Issue by sidineyc** [bitnami/charts#17779]
### Name and Version

bitnami/thanos 12.8.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Related to this change https://github.com/bitnami/charts/issues/16742

With this change, no `serviceMonitor` is created, therefore no Compactor metrics are available.

I'm not sure  the best way to handle this, considering if we have the `serviceMonitor`, we'll get Target Down as explained on the issue, but then we miss Compactor metrics.

### What is the expected behavior?

Compactor Metrics available and no `TargetDown` alerts

### What do you see instead?

No Compactor Metrics available

**Comment by dgomezleon** [comment]
Hi @sidineyc ,

Are you configuring the compactor to run as a cronjob? Could you please share the values you are using?

**Comment by dgomezleon** [comment]
Hi @sidineyc ,

In order to push metrics from jobs is common to use Pushgateway. I think the documentation below could be useful:
https://prometheus.io/docs/practices/pushing/

I hope it helps

**Comment by sidineyc** [comment]
hey @dgomezleon  in my understanding this would require some logic built in with Thanos Compactor itself, no ?

**Comment by juan131** [comment]
Hi @sidineyc 

Yew, when using PushGateway it's expected that services push their metrics instead of exposing them for Prometheus to expose them.

That said, it isn't mandatory Thanos Compactor push them (that would require building that logic on that component), you can use a sidecar container instead. This sidecar container would be the responsible of obtaining the compactor metrics and push them to the PushGateway.
