### ISSUE TITLE
[bitnami/kafka] Receive older zookeeper version

### ISSUE THREAD

**Issue by Hmr-ramzi** [bitnami/charts#1793]
**Which chart**:
bitnami/kafka

**Description**
Whenever i fork the repo, try to apply "helm dep update ." inside the kafka folder, I receive zookeeper latest version as a dependency as expected (version 5.3.0). However, if i use kafka latest version "7.1.0" as a dependency in another chart and try to apply  "helm dep update ."  (after adding the bitnami helm repo https://charts.bitnami.com/bitnami) i received kafka version 7.1.0 but with older version of zookeeper 5.2.0 instead of latest 5.3.0

**Describe the results you received:**
Older version of zookeeper

**Describe the results you expected:**
latest version of zookeeper

**Comment by sameersbn** [comment]
@Hmr-ramzi The kafka chart specifies version `5.x.x` for the [zookeeper dependency](https://github.com/bitnami/charts/blob/master/bitnami/kafka/requirements.yaml#L3). So when you execute `helm dep up`, it will download the latest `5.x.x` version of zookeeper chart as you rightly pointed out. 

When you add the kafka 7.1.0 chart as a dependency to your chart, it downloads the packaged chart from https://charts.bitnami.com/bitnami. The packaged chart also contains packaged version of the zookeeper chart (zookeeper `5.2.0` is probably the version available when the kafka chart was packaged).

Instead of `helm dep up` if you execute `helm dep build`, you will get the same dependency versions 
 as the packaged chart as it uses the `requirements.lock` file.

**Comment by Hmr-ramzi** [comment]
Is it possible to switch the format of the chart to Helm 3 as the requirements.yaml / lock are no longer existing in helm 3? I submitted a pull request for it but it is currently on hold for some reason @juan131 can you please advise ?

**Comment by sameersbn** [comment]
@Hmr-ramzi  We want to maintain the compatibility of the chart with Helm v2 until end-of-life. Could you instead rebuild the dependencies using the helm v2 client. That way we will be compatible with both Helm version.

**Comment by Hmr-ramzi** [comment]
Ahaa Ok got it. Thanks for the prompt reply. Sure. will do

**Comment by sameersbn** [comment]
@Hmr-ramzi A new zookeeper version was tagged a few minutes back #1797. It's an important fix and hence it would be perfect if you're PR uses the new version (5.3.1).

Note: You may need to wait for a couple minutes for the new version to get published to the bitnami helm repo. At the moment its still  on `5.3.0`

```bash
$ helm.v2.16.1 repo up && helm.v2.16.1 search zookeeper
NAME                	CHART VERSION	APP VERSION	DESCRIPTION                                                 
bitnami/zookeeper   	5.3.0        	3.5.6      	A centralized service for maintaining configuration infor...
```

**Comment by Hmr-ramzi** [comment]
Sure. Thanks for letting me know

**Comment by sameersbn** [comment]
It's released. Please update the PR with the new release and helm v2 format.

**Comment by Hmr-ramzi** [comment]
Done. Can you please check it?
