### ISSUE TITLE
[bitnami/postgresql-ha] failover change replicatation state from quorum/sync to async

### ISSUE THREAD

**Issue by naude-r** [bitnami/charts#18009]
### Name and Version

bitnami/postgresql-ha 11.7.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy 2 node postgres-ha
2. important config: 
```
    replicaCount: 2
    syncReplication: true
    syncReplicationMode: ANY
```
3. delete master
4. select * from pg_stat_replication
5. sync_state has now changed from quorum to async.

### Are you using any custom parameters or values?
```
replicaCount: 2
  syncReplication: true
  syncReplicationMode: ANY
```
### What is the expected behavior?

after fail-over sync_state to retain previous value, ie quorum

### What do you see instead?
```
sync_state = async
```

**Comment by migruiz4** [comment]
Hi @naude-r,

Does this issue happen if you deploy 3 replicas?
For a quorum to work 2 replicas are usually not enough as you need `number_of_nodes / 2 + 1` to reelect a new master in order to prevent split-brain scenarios.

When having 2 replicas, the condition for reelection would never be met as you need both nodes up to vote for a new master.

**Comment by naude-r** [comment]
@migruiz4 apologies. this was with 2 replicas. that was a misunderstanding on my end. you may close the issue in that case.

**Comment by migruiz4** [comment]
No worries @naude-r , please let us know if you find any further issues
