### ISSUE TITLE
[bitnami/mastodon] arm64 architecture support

### ISSUE THREAD

**Issue by bcross** [bitnami/charts#18192]
### Name and Version

bitnami/mastodon

### What is the problem this feature will solve?

The Mastodon image is the only image required by this chart that does not have an arm64 build.

### What is the feature you are proposing to solve the problem?

The main Mastodon image already supports this.

https://github.com/mastodon/mastodon/pkgs/container/mastodon

**Comment by carrodher** [comment]
We faced some issues when adding ARM support for this container image, but we have an internal task to review all the applications where ARM support was not added in the past so we can check if the blocker issue we faced is solved now.

We'll update this issue once we advance in that tasks, although due to other priorities in the team we can't provide an ETA
