### ISSUE TITLE
When setting clientEncryption to yes the starting instance is unable to connect to the db

### ISSUE THREAD

**Issue by pomberer** [bitnami/charts#1826]
When setting clientEncryption to yes accessing the cql from the startup (to execute init db scripts or change default user) fails:

```
cassandra 14:20:39.26 INFO  ==> Trying to access CQL server @ test-cassandra-0.test-cassandra-headless.name.svc.cluster.local
cassandra 14:20:39.29 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
Connection error: ('Unable to connect to any servers', {'10.244.1.136': ConnectionShutdown('Connection to 10.244.1.136 was closed',)})
cassandra 14:20:49.83 DEBUG ==> Executing CQL "DESCRIBE KEYSPACES"
```

[values-prod.yaml.txt](https://github.com/bitnami/azure-marketplace-charts/files/4059593/values-prod.yaml.txt)

dbUser and initDBConfigMap are ignored and cannot be executed on the server

**Comment by andresbono** [comment]
Hi @pomberer, thanks for filling the issue. We will try to reproduce the issue and we will get back to you.

**Comment by andresbono** [comment]
Sorry for the delay, @pomberer. We could reproduce the issue. After the first fail of the pod, it is restarted and then it initializes correctly. Does it happen the same for you?

In any case, we have created an internal task to investigate it in more depth.

**Comment by pomberer** [comment]
@andresbono 
Thank you for the response. Yes after the restart of the first pod it initializes correctly, but the user specified in dbUser.user is still not created after the restart...

**Comment by andresbono** [comment]
Thanks for the information @pomberer. We will investigate that issue too

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
