### ISSUE TITLE
[bitnami/harbor] Required certificate authority

### ISSUE THREAD

**Issue by migmartri** [bitnami/charts#1863]
Hi,

I deployed an instance of Harbor reading from a prepopulated k8s tls certificate generated through a trusted certificate authority.

To do so, after getting the certificate I 1) created the k8s secret by running 

```
kubectl create secret tls harbor-ingress-certs \
  --key certs//privkey1.pem \
  --cert certs/fullchain1.pem 
```

And 2) deployed harbor setting the external tls name `--set service.tls.secretName=harbor-ingress-certs`

The issue is that the `core` pod will not start because can not mount the CA file since it is not part of the secret https://github.com/bitnami/charts/blob/449f80cf4dda6fa105b3801292ad6148ae0d69b1/bitnami/harbor/templates/core/core-dpl.yaml#L134

To workaround it I downloaded the public, trusted CA from the internet and manually added it to the secret but, is a CA required even if it is from upstream? Would it make sense to make the CA optional?

Thanks!

**Comment by dani8art** [comment]
Hi @migmartri 

I agree, when we are passing a cert/key trusted by a CA form internet we could avoid using CA as a volume, however, we don't know if harbor requires this path to work (it shouldn't) or we can avoid it. 

I will try some changes in the chart and find an approach that fits all the cases in my local environment. Then we have to open a PR to the official chart in order to validate the changes and then integrate upstream changes in this one. 

Thank you for your feedback. 
Regards.

**Comment by migmartri** [comment]
Thanks @dani8art! Let me know if you want me to test something out or need more info.

**Comment by dani8art** [comment]
Hi, @migmartri 

Sorry for my late response. I've tested an approach that works fine but I would like to be sure that It breaks nothing in Harbor, I would like to test more cases and try to understand better how, why and when Harbor needs CA.

Regards.
