### ISSUE TITLE
[bitnami/mongodb] enable SSL/TLS for inter node communication and client connections

### ISSUE THREAD

**Issue by pomberer** [bitnami/charts#1867]
From the documentation of the bitnami mongodb docker image it says TLS/SSL for both client connections and inter node communication can be enabled setting the env vars MONGODB_EXTRA_FLAGS, MONGODB_CLIENT_EXTRA_FLAGS and MONGODB_ADVERTISED_HOSTNAME.

It seems like the helm chart only supports mongodbExtraFlags as configurable env var. 
Can this be achieved another way or is this feature just not implemented ?

**Comment by dani8art** [comment]
Hi @pomberer ,

Thank you for submitting this issue,  I would like to identify which chart you are pointing out, when you say `bitnami/mongodb` do you mean: `bitnami/mongodb-sharded` or `stable/mongodb` which also is owned by bitnami. I would need to clarify it because they are a bit different.

Regards.

**Comment by pomberer** [comment]
Hello @dani8art ,

I was referring to stable/mongodb
Regard Gerhard

**Comment by dani8art** [comment]
Hi @pomberer ,

Then, If I understand you well, I would say that you can use `.Values.extraEnvVars` to pass the other environment variables to the containers and configure them as in the documentation.

Regards.

**Comment by pomberer** [comment]
Hi @dani8art ,
Ok thank you that confirms that my initial idea
Regards
