### ISSUE TITLE
[bitnami/solr] your zk connection string (1 hosts) is different from the dynamic ensemble config (3 hosts). solr does not currently support dynamic reconfiguration and will only be able to connect to the zk hosts in your connection string.

### ISSUE THREAD

**Issue by Sagarbud** [bitnami/charts#18774]
### Name and Version

bitnamicharts/solr

### What architecture are you using?

None

### What steps will reproduce the bug?

![Screenshot from 2023-08-22 12-47-43](https://github.com/bitnami/charts/assets/115458338/8aa3ee94-50b6-46ce-8b51-9c9efa4a5024)
Hello,

 have installed bitnamicharts/solr in GKE cluster. But when I login in Solr admin panel and check the Zookeeper status. It is showing the following error.
your zk connection string (1 hosts) is different from the dynamic ensemble config (3 hosts). solr does not currently support dynamic reconfiguration and will only be able to connect to the zk hosts in your connection string.

Also, I have tried to install different version but getting the same error. I have attached the screen capture for your reference.

Please look into it.

### What do you see instead?

Status: green

**Comment by fmulero** [comment]
Thanks @Sagarbud, I've just reproduced the issue with the default values.

I'll work on it in a few days. I hope to be back with news soon

**Comment by janhoy** [comment]
Hi, I added that warning to the solr UI.

Zookeeper is designed so that the client (Solr) will have a separate connection to each zookeeper node, i.e. if you have 3 zookeepers, you should configure `ZK_HOST` with a comma separated list of these three. This lets Solr's ZK client instantly switch to a different zookeeper node if/when one becomes unavailable, i.e. no interruption or waiting for reconnect.

Now, the bitnami ZK chart exposes a single only, load balancing traffic to the PODs in the stateful set. Thus Solr believes that you only have one zookeeper node, but then it finds through introspection that there are in fact three. Thus the warning.

While this seems to work well, and is mostly not critical for stability, it is not optimal.

The proper solution would be for Bitnami zookeeper to add services for each pod, like the solr-operator does (https://github.com/apache/solr-operator)

**Comment by fmulero** [comment]
Hi

I've just create a PR with the fix. Please feel free to review it.

Thanks a lot @janhoy
