### ISSUE TITLE
[postgresql-ha] extended ConfigMap mounted to wrong directory

### ISSUE THREAD

**Issue by jakubowy** [bitnami/charts#1884]
**Which chart**:

postgresql-ha-1.4.0

**Description**

ConfigMap postgresql-ha-postgresql-extended-configuration generated when using extended configuration is mounted to wrong path
https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/postgresql/statefulset.yaml#L181

```
            {{- if or (.Files.Glob "files/conf.d/*.conf") .Values.postgresql.extendedConf .Values.postgresql.extendedConfCM }} 
            - name: postgresql-extended-config
              mountPath: /bitnami/repmgr/conf/conf.d/
            {{- end }}
```
according to postgresql documentation for include_dir

> Non-absolute directory names are taken as relative to the directory containing the referencing configuration file.

This postgress is run with the configration file "/opt/bitnami/postgresql/conf/postgresql.conf" which is copied from "/bitnami/postgresql/conf" on startup, so "conf.d" should also be under "/bitnami/postgresql/conf"

**Comment by juan131** [comment]
Hi @jakubowy 

You're right, the `postgresql.conf` must me mounted at `/bitnami/repmgr/conf/` since the "repmgr" logic will detect the file and put in the right place instead of auto-generating a new config file for PostgreSQL (check the line below):

- https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/12/debian-10/rootfs/librepmgr.sh#L416

However, that logic doesn't take into account the "extended configuration", which should be directly mounted at `/bitnami/postgresql/conf/conf.d/`.

I'm creating a PR to fix it.
