### ISSUE TITLE
[bitnami/kafka] YAML parse error on kafka/templates/broker/svc-headless.yaml

### ISSUE THREAD

**Issue by ewertonhm** [bitnami/charts#18866]
### Name and Version

bitnami/kafka

### What architecture are you using?

None

### What steps will reproduce the bug?

I'm trying a new deploy of kafka with zooekeeper, on helm install passing some parameters in the values it retourn the error

### Are you using any custom parameters or values?
```
--set zookeeper.enabled=false 
--set replicaCount=3 
--set broker.replicaCount=2 
--set broker.zookeeperMigrationMode=true
```

### What do you see instead?
```
helm install kafka oci://registry-1.docker.io/bitnamicharts/kafka --set zookeeper.enabled=false --set replicaCount=3 --set broker.replicaCount=2 --set broker.zookeeperMigrationMode=true --set externalZookeeper.servers=zookeeper.kafka.svc.cluster.local
Pulled: registry-1.docker.io/bitnamicharts/kafka:25.1.1
Digest: sha256:2828aa833c0a6e91b9e0e353b974b91a76c34d2c9da3f4d7bc7eb0e615042866
Error: UPGRADE FAILED: YAML parse error on kafka/templates/broker/svc-headless.yaml: error converting YAML to JSON: yaml: line 29: mapping values are not allowed in this context
```
### Additional information

It sees to be related with the broker.zookeeperMigrationMode parameter, without it, its working fine.

**Comment by snowsky** [comment]
It seems this was caused by this line's indentation: [https://github.com/bitnami/charts/blob/0a432781a472f590c5192ec24a4b2e2364942a57/bitnami/kafka/templates/broker/svc-headless.yaml#L36](https://www.codementor.io/redirect-notice?url=https%3A%2F%2Fgithub.com%2Fbitnami%2Fcharts%2Fblob%2F0a432781a472f590c5192ec24a4b2e2364942a57%2Fbitnami%2Fkafka%2Ftemplates%2Fbroker%2Fsvc-headless.yaml%23L36)
