### ISSUE TITLE
[bitnami/redis-cluster] new redis-cluster chart rolled back redis image from 7.2 to 7.0

### ISSUE THREAD

**Issue by sereinity** [bitnami/charts#18861]
### Name and Version

bitnami/redis-cluster 8.8.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Install bitnami/redis-cluster v8.8.0

Upgrade to v8.8.1, "upgraded" pods will crashloop.

### What do you see instead?

```
NAME              READY   STATUS             RESTARTS      AGE
redis-cluster-0   2/2     Running            0             29m
redis-cluster-1   2/2     Running            0             29m
redis-cluster-2   2/2     Running            0             29m
redis-cluster-3   2/2     Running            0             28m
redis-cluster-4   2/2     Running            0             18m
redis-cluster-5   1/2     CrashLoopBackOff   2 (17s ago)   72s
```

```
redis-cluster 13:53:00.15
redis-cluster 13:53:00.15 Welcome to the Bitnami redis-cluster container
redis-cluster 13:53:00.15 Subscribe to project updates by watching https://github.com/bitnami/containers
redis-cluster 13:53:00.16 Submit issues and feature requests at https://github.com/bitnami/containers/issues
redis-cluster 13:53:00.16
redis-cluster 13:53:00.16 INFO  ==> ** Starting Redis setup **
redis-cluster 13:53:00.20 INFO  ==> Initializing Redis
redis-cluster 13:53:00.23 INFO  ==> Setting Redis config file
Changing old IP 10.0.8.150 by the new one 10.0.8.150
Changing old IP 10.0.6.153 by the new one 10.0.6.153
Changing old IP 10.0.9.94 by the new one 10.0.9.94
Changing old IP 10.0.7.238 by the new one 10.0.7.238
Changing old IP 10.0.2.228 by the new one 10.0.2.228
Changing old IP 10.0.4.210 by the new one 10.0.10.197

redis-cluster 13:53:10.51 INFO  ==> ** Redis setup finished! **
1:C 25 Aug 2023 13:53:10.556 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Aug 2023 13:53:10.556 # Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Aug 2023 13:53:10.556 # Configuration loaded
1:M 25 Aug 2023 13:53:10.556 * monotonic clock: POSIX clock_gettime
1:M 25 Aug 2023 13:53:10.557 * Node configuration loaded, I'm 6d7e424e4a2f8f25bb5fb40d426da3f07e46f7be
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 7.0.12 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in cluster mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 25 Aug 2023 13:53:10.558 # Server initialized
1:M 25 Aug 2023 13:53:10.560 * Reading RDB base file on AOF loading...
1:M 25 Aug 2023 13:53:10.561 # Can't handle RDB format version 11
1:M 25 Aug 2023 13:53:10.561 # Error reading the RDB base file appendonly.aof.3.base.rdb, AOF loading aborted
1:M 25 Aug 2023 13:53:10.561 # Unrecoverable error reading the append only file appendonly.aof.3.base.rdb: Invalid argument
```

### Additional information

This is due to https://github.com/bitnami/charts/pull/18858 which automatically rolled back from `docker.io/bitnami/redis-cluster:7.2.0-debian-11-r3` to `docker.io/bitnami/redis-cluster:7.0.12-debian-11-r0`

**Comment by FraPazGal** [comment]
Hi @sereinity, thanks for reporting this! Apologies for any inconveniences this has caused, the root issue came from an internal labelling error, by which we considered the latest `redis@7.2` container as it being a `7.0` version release. Chronologically, we saw that:

1. Both of our charts, `bitnami/redis` & `bitnami/redis-cluster` started using the `7.2` version (tagged internally as `7.0`) with only a patch version bump. See https://github.com/bitnami/charts/pull/18430
2. After roughly a week, a new version of `redis@7.0` was released and thus our charts were updated. This resulted in the redis image going back to using `redis@7.0`. See https://github.com/bitnami/charts/pull/18858
3. A few days later, we updated our charts internally to start using the `redis@7.2` branch. The update caused a new release PR updating the chart to the new branch, now correctly bumping the chart version to a new major. See https://github.com/bitnami/charts/pull/18907

As it is now, the newest chart major version uses `redis@7.2`, with the last version of the previous major using `redis@7.0`. Seeing the issue is solved on that front, we are working on fixing the labelling issue internally and adding an explanation in both charts' Upgrading notes to avoid further confusion (https://github.com/bitnami/charts/pull/18891).
