### ISSUE TITLE
[bitnami/minio] Improve provisioner documentation

### ISSUE THREAD

**Issue by E1v1s** [bitnami/charts#18910]
### Name and Version

bitnami/minio 12.4.1

### What is the problem this feature will solve?

Sorry to probably bother community, i'm try to backup data within standalone mode to existing s3 bucket with service user,
and it's almost blind way through. I mean there is no documentation or example what i need to fill in provisioner.bucket, provisioner.usersExistingSecrets and so on to reach simple scheduled backup.
I guess i can parse in the hard way from template job, but maybe i'm blind to see easier way?
Looking for advices.

### What is the feature you are proposing to solve the problem?

Add template example to documentation, improve documentatiton with provision examples

### What alternatives have you considered?

Parsing values from job templates not friendly way of using this chart.

**Comment by E1v1s** [comment]
provisioning.users working great, but why i can't add alias with 
`provisioning.extraCommands: mc alias set myS3 https://sport-infra-backups-stage.s3.eu-central-1.amazonaws.com accesskey secretkey`
?
in logs it's show me that
```
Enabled user `test-username` successfully.
Added `myS3` successfully.
End Minio provisioning
```
but in main pod there is no myS3

**Comment by juan131** [comment]
Hi @E1v1s 

As it's explained in the M[inIO documentation](https://min.io/docs/minio/linux/reference/minio-mc/mc-alias-set.html) aliases are stored locally:

> The **mc alias set** command adds or updates an alias to the local mc configuration.

Therefore, you can't expect the alias to exist in the main pod since it was created in the provisioning job one.

Regarding the missing documentation, I agree with you that it's hard to understand how to properly use this provisioning job. Maybe we should add a new guide at the docs site below explaining this:

- https://docs.bitnami.com/kubernetes/infrastructure/minio/administration

> Note: the docs site source code is also open-source and available at https://github.com/bitnami/charts-docs (see https://github.com/bitnami/charts-docs/tree/main/charts/minio). Contributions to improve this documentation are very welcome.
