### ISSUE TITLE
Support for cert-manager certificates went away?

### ISSUE THREAD

**Issue by danielluke** [bitnami/charts#18971]
### Name and Version

bitnami/kafka 25.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. install bitnami/kafka 19.1.0 using values.yaml that has `auth.tls.existingSecrets` set to 3 certificates managed by cert-manager.
2. Time passes
3. realize that my install is out of date, go to install bitnami/kafka 25.1.4, there doesn't appear to be a way to get the configure_kafka_tls() shell script to use the values from a cert-manager secret because it requires the certificate name to be something other than cert-manager's secret keys (for either PEM or JKS formatted certificates)

### Are you using any custom parameters or values?

values.yaml with: 

```yaml
externalClientProtocol: mtls
  tls:
    type: pem
    existingSecrets:
      - kafka-0-tls
      - kafka-1-tls
      - kafka-2-tls
```

### What is the expected behavior?

Ideally, I'd like to use the same k8s secrets with the new version, but I'd settle for some way to use a cert-manager-managed certificate.

### What do you see instead?

the kafka-scripts ConfigMap's `kafka-init.sh` is looking for a mounted PEM certificate secret with a key of `kafka-${POD_ROLE}-${POD_ID}.(crt|key)` or `kafka.(crt|key)` - but cert-manager's secrets have a key of `tls.(crt|key)`

Alternatively, it looks for a JKS certificate mounted with key of `kafka-${POD_ROLE}-${POD_ID}.keystore.jks` or `mounted-certs/kafka.keystore.jks` while cert-manager's secret has a key of `keystore.jks`

### Additional information

I don't see any documented way of having cert-manager use different keys in the secret it generates for certificates it manages.

**Comment by fmulero** [comment]
Hi @danielluke thanks for reporting this issue.

Whole SSL configuration was refactored [here](https://github.com/bitnami/charts/pull/17507) in order to make it clearer and more aligned with the Kraft features introduced by Kafka.

Checking those changes I realised what you mentioned above, now in the existing secret should exist a pair of entries for each node with the certificate and key, following this naming convention: `kafka-${POD_ROLE}-${POD_ID}.(crt|key)`. I understand it makes harder the integration with `cert-manager` and probably it wasn't taken into account.

I'll open an internal discussion. I hope to be back soon.

**Comment by fmulero** [comment]
@danielluke please have a look to this [PR](https://github.com/bitnami/charts/pull/18887), it has a contribution to sort out a similar issue.

**Comment by danielluke** [comment]
> @danielluke please have a look to this [PR](https://github.com/bitnami/charts/pull/18887), it has a contribution to sort out a similar issue.

That looks like it will work, thanks!
