### ISSUE TITLE
mongodb-labeler - problem label collection Goland out of date

### ISSUE THREAD

**Issue by BK-STAR77** [bitnami/charts#19013]
### Name and Version

bitnami/mongodb 12.1.31

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hello

We have recently a problem with the pod labeler to put label to the pod.

The image image: "korenlev/k8s-mongo-labeler-sidecar" Goland collection is out of date and we resolved the issue in puting a new image of k8s-mongo-labeler-sidecar with the latest Goland collection.

Can you update your collection too in the Helm chart?

Thank you

### What do you see instead?

```
time="2023-08-30T12:52:15Z" level=error msg="Pod \"mongodb-0\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds`, `spec.tolerations` (only additions to existing tolerations) or `spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
  core.PodSpec{
    ... // 10 identical fields
    AutomountServiceAccountToken: nil,
    NodeName:                     \"\",
    SecurityContext: &core.PodSecurityContext{
      ... // 11 identical fields
      FSGroupChangePolicy: nil,
      Sysctls:             nil,
-     SeccompProfile:      &core.SeccompProfile{Type: \"RuntimeDefault\"},
+     SeccompProfile:      nil,
    },
    ImagePullSecrets: {{Name: \"mongodb-dockercfg-j9pjg\"}},
    Hostname:         \"mongodb-0\",
    ... // 16 identical fields
  }
"
```

**Comment by carrodher** [comment]
The image you mentioned (korenlev/k8s-mongo-labeler-sidecar) is not part of the bitnami/mongodb Helm chart. Could you please check that?

**Comment by BK-STAR77** [comment]
> The image you mentioned (korenlev/k8s-mongo-labeler-sidecar) is not part of the bitnami/mongodb Helm chart. Could you please check that?

[Line 672](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/values.yaml#L672)

**Comment by carrodher** [comment]
I see, that's an example of how to use sidecar containers for a specific use case.
I'm not familiar with how to update that image, since it is setting `imagePullPolicy: Always` it should pull the latest version of the image automatically.
If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
