### ISSUE TITLE
[Airflow:1.0.0] Separate Resource blocks for worker , web and scheduler

### ISSUE THREAD

**Issue by appunni-m** [bitnami/charts#1906]
We are running into issue as we try to run larger number of workers and dags, scheduler needs more CPU, while Web and Worker requires less. While Worker Needs more memory but Web and Scheduler doesn't.

If we could separate out resource blocks in yaml it would be great.

**Comment by carrodher** [comment]
Hi @appunni-dishq, I agree that it could be a good feature. Would you consider contributing to the project by creating a PR to add this feature? I'd be glad to review it.

**Comment by appunni-dishq** [comment]
I will try to, I am very new to helm. Currently I moved to stable/airflow.

**Comment by carrodher** [comment]
Hi, I just created an internal task to implement the required changes and send the PR. We will work on it but as it depends on other priorities I can't give you an exact ETA.

We'll update this issue with more news. Thanks for reporting it

**Comment by Mauraza** [comment]
Hi @appunni-dishq 

I just do a PR #1951 separated the resources for web, scheduler and worker. You can use the new version of the chart `4.4.0`

I hope that change helps you.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
