### ISSUE TITLE
[bitnami/etcd] Production config - Cluster is not recovered after helm upgrade or deleting a pod 

### ISSUE THREAD

**Issue by turkenh** [bitnami/charts#1908]
**Which chart**:

etcd - 4.4.12

**Description**

With production config (3 replicas), I am trying to test the following scenarios to make sure it is safe to deploy into production:

a. To simulate any kind of pod restart (e.g. OOM, rescheduled by k8s or even manual pod delete), `kubectl delete` any pod and expect to it recover.
b. In case of a need to updating configuration, run helm upgrade by increasing memory limit and expect cluster is still functional.

However for both cases, restarted / upgraded (not etcd version upgrade) pod keeps crashing with the following logs:

```
2020-02-11 08:57:36.138446 I | embed: ClientTLS: cert = /opt/bitnami/etcd/certs/client/cert.pem, key = /opt/bitnami/etcd/certs/client/key.pem, trusted-ca = /opt/bitnami/etcd/certs/client/ca.crt, client-cert-auth = true, crl-file =
2020-02-11 08:57:36.146355 I | embed: listening for peers on [::]:2380
2020-02-11 08:57:36.146646 E | rafthttp: streaming request ignored (ID mismatch got 3399487d12010a3d want b64def235981cdc4)
raft2020/02/11 08:57:36 INFO: raft.node: b64def235981cdc4 elected leader 491212fc9af6c8e2 at term 5
2020-02-11 08:57:36.147159 E | rafthttp: streaming request ignored (ID mismatch got 3399487d12010a3d want b64def235981cdc4)
2020-02-11 08:57:36.147343 E | rafthttp: streaming request ignored (ID mismatch got 3399487d12010a3d want b64def235981cdc4)
2020-02-11 08:57:36.849042 E | etcdserver: the member has been permanently removed from the cluster
2020-02-11 08:57:36.849071 I | etcdserver: the data-dir used by this member must be removed.
2020-02-11 08:57:36.849194 E | etcdserver: publish error: etcdserver: request cancelled
2020-02-11 08:57:36.849212 E | etcdserver: publish error: etcdserver: request cancelled
2020-02-11 08:57:36.935624 E | etcdserver: publish error: etcdserver: request cancelled
2020-02-11 08:57:37.035588 I | etcdserver: aborting publish because server is stopped
2020-02-11 08:57:37.043626 E | rafthttp: streaming request ignored (ID mismatch got 3399487d12010a3d want b64def235981cdc4)
2020-02-11 08:57:37.044445 E | rafthttp: streaming request ignored (ID mismatch got 3399487d12010a3d want b64def235981cdc4)
2020-02-11 08:57:37.047203 E | rafthttp: streaming request ignored (ID mismatch got 3399487d12010a3d want b64def235981cdc4)
2020-02-11 08:57:37.047464 W | rafthttp: failed to process raft message (raft: stopped)
```

**Steps to reproduce the issue:**

1. helm install with the following value overrides:
```
statefulset:
  replicaCount: 3
auth: 
  rbac:
    rootPassword: qwerty123
  client:
    secureTransport: true
    useAutoTLS: false
    enableAuthentication: true
    existingSecret: etcd-client-tls
  peer:
    secureTransport: true
    useAutoTLS: true
    enableAuthentication: false
resources:
  limits: 
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 256Mi
image:
  debug: true
```
2. Wait until cluster is stabilized, make sure it is functional by running some etcdctl queries

3. a. kubectl delete any pod

or

3. b. increase memory limit in helm overrides and run helm upgrade

4. Wait until cluster is stabilized

**Describe the results you received:**

restarted / upgraded (not etcd version upgrade) pod never comes and keeps crashing.

**Describe the results you expected:**

For both cases, cluster comes to a functional state again.

**Additional information you deem important (e.g. issue happens only occasionally):**

Tested on both a kind cluster and also on a GKE cluster. Result is same.

I see a [member remove](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/scripts-configmap.yaml#L207) in pre-stop hook. Could this be related? 

Btw, I am not willing to enable disaster recovery since it requires ReadWriteMany PVs, which I had quite a lot of issues in the past. 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.23", GitCommit:"93457f9dac45d5f95c2c609232e1ff2343c72684", GitTreeState:"clean", BuildDate:"2020-01-14T06:01:01Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Full logs of crashing container (etcd-cluster-2): https://gist.github.com/turkenh/119ae5a40421d115dc829f5a5414f6db

**Comment by turkenh** [comment]
As an experiment, I removed the `etcdctl member remove` [line from pre-stop](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/scripts-configmap.yaml#L207) **pods came up successfully**.
AFAIU, removing member in pre-stop makes sense for scale down cases but I believe these two scenario is more common. Of course best is to find a solution handling for all cases.

**Comment by nvtkaszpir** [comment]
I've seen similiar issue when creating 3 node cluster and deleting pod 0 - it is stuck in crashloop.
So when I kept that cluster running I deleted pod 1, but then the pod recovered (probably because etcd remove member cannot be excuted if cluster in not healthy).

**Comment by nvtkaszpir** [comment]
I believe it would be better to move the etctdctl member remove into the cronjob which would prune dead nodes after some time - this would allow to have pod recovery in case of crashes, but still would be able to clean up in case of scale downs.

**Comment by dani8art** [comment]
Hi @turkenh ,

Thank you for opening this issue, I going to try to reproduce it and I have a question, when you said "production config" do you mean you are using `values-production.yaml`? or you are just using `values.yaml` overriding some values as you've mentioned above. I would need to know if you are using `values.yaml` or `values-production.yaml` and then overriding it.

Regards.

**Comment by turkenh** [comment]
Hi @dani8art,

Thanks! 
I am using `values.yaml` and overriding with values above. 

The reason that I am saying production config is, I built that set of overrides by looking the difference between `values.yaml` and `values-production.yaml`. So, I expect to reach the same config as using `values-production.yaml`.

**Comment by dani8art** [comment]
Ok thanks, I will investigate the issue trying to reproduce it. I will come back to you as soon as I found something.

**Comment by turkenh** [comment]
> Ok thanks, I will investigate the issue trying to reproduce it. I will come back to you as soon as I find something.

@dani8art any update on this?

**Comment by dani8art** [comment]
Hi @turkenh, I was investigating and I can confirm that as you mention the issue in fact is around [member removal on this line](https://github.com/bitnami/charts/blob/master/bitnami/etcd/templates/scripts-configmap.yaml#L207), however, we can not follow what you suggested in your experiment because we need to find a general solution for that. 

Regarding that, we are going to open an internal task to evaluate a solution for this issue, we can not give you an ETA but we keep you updated. 

Thank you so much for your feedback.
Regards

**Comment by salanki** [comment]
I am having this issue as well. Super easy to reproduce. Happens every time.

**Comment by salanki** [comment]
I can also confirm that @turkenh's workaround works. I don't see how this chart is useful for production without it tbh.

**Comment by dani8art** [comment]
Hi @salanki, thank you for the feedback, we are trying to handle this issue since it is so important, as you say, to have this chart in production. Unfortunately, we can not give you an ETA, however we are open to contribution and if you have a chance we will be so happy to discuss the best solution in a PR.

**Comment by sjgiri** [comment]
I also encountered continuous crashloop after deleting a pod manually. After going through different issues similar to this, I applied the following change to `statefulset.yaml` and not seeing the crash loop anymore. I think when a pod is killed, the node name and node ip address changes. I guess ip address change is handled by raft not the node name. 

```
- name: CONSUL_NODE_NAME
   valueFrom:
     fieldRef:
       fieldPath: metadata.name
```

Also, I override `localConfig` with `disable_host_node_id: false` to ensure that the node id is same across restarts.

**Comment by dbaumgarten** [comment]
I am having a similar Issue and would really like to have this solved.
When I delete pod 1 and 2 from a 3-replica deployment, pod 0 is left and functions as a health one node cluster, because pod 1 and 2 have removed themselves from the cluster in their pre-stop hooks.

However, the restarted pods 1 and 2 fail to re-join the cluster, because the function is_disastrous_failure wrongly assumes a disaster happened. It checks if the mayority of endpoints is healthy (based on the replica count set by the helm chart) and as only pod 0 is healthy, it assumes the cluster is unhealthy. 
BUT as pod 1 and 2 had been removed from the cluster, the cluster IS healthy. If is_disastrous_failure would just notice that, the startup-script would re-add the nodes to the cluster and everything should (in theory) work again.

Maybe fixing is_disastrous_failure would be a better solution then disabling the member-remove?

**Comment by rgarcia89** [comment]
@dani8art any update on this? The issue is open since February 🤔

Maybe the community can help if you let us know where exactly you are struggling with right now?

**Comment by rgarcia89** [comment]
Changing `ETCD_INITIAL_CLUSTER_STATE` from `new` to `existing` fixes the issue.
Could you guys please make this variable configurable?

**Comment by dbaumgarten** [comment]
I think the true issue for all this problems is far deeper.
The whole setup.sh script is really unreliable. 

It decides what actions to take (re-join the cluster, update cluster member, add member to cluster, delete datadir) based on files stored on the volume of the pod. Unfortunately it also does directly delete this files after checking them. If now a (temporary) error occurs during the action it chose, it has no chance to choose the correct action on the next restart (because it deleted the files it would need for this).

Also the is_disastrous_failure is just wrong. As pods do remove themselves from the cluster on termination, having less then 50% of the original replica-count available does not mean, that the cluster is broken. If all other pods have removed themselves before terminating, then even a cluster with a single node is stilll working. The only reliable way to find out if the cluster is broken or not, is to ask the cluster if it is healthy.

Also the whole "should I add myself back as a member"-thing could be solved far more reliable, if the pod just checked if it is still registered as a cluster-member or not.

**Comment by nvtkaszpir** [comment]
That's why we switched to coreos/etcd-operator (now defunct, but cwbs fork works), because rewriting the shell scripts would actually mean that we write another etcd-operator.

**Comment by rgarcia89** [comment]
@nvtkaszpir I tried the helm chart for the coreos/etc-operator. This was way less working. We have a DEV Cluster in the cloud that gets suspend during the night. Guess what? The coreos/etc-operator is not able to handle such a situation. So all etcd pods fail

**Comment by dani8art** [comment]
Hi guys!

> The whole setup.sh script is really unreliable.

I think this is the best way to tackle it we would need to improve the way we decide what action to take and change the way we check `is_disastrous_failure`

what I would suggest changing is:

- moving the removal of the file later and outside`should_add_new_member` function 
- also do `store_member_id` synchronous

```diff
- rm -f "$(dirname "$ETCD_DATA_DIR")/member_removal.log" 1>&3 2>&4

        elif should_add_new_member; then
            echo "==> Adding new member to existing cluster..." 1>&3 2>&4
            etcdctl $AUTH_OPTIONS member add "$HOSTNAME" --peer-urls="{{ $etcdPeerProtocol }}://${HOSTNAME}.{{ $etcdHeadlessServiceName }}.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:{{ $peerPort }}" | grep "^ETCD_" > "$ETCD_DATA_DIR/new_member_envs" 1>&3 2>&4
            sed -ie 's/^/export /' "$ETCD_DATA_DIR/new_member_envs"
            echo "==> Loading env vars of existing cluster..." 1>&3 2>&4
            source "$ETCD_DATA_DIR/new_member_envs" 1>&3 2>&4
-           store_member_id & 1>&3 2>&4
+           store_member_id 1>&3 2>&4
+           rm -f "$(dirname "$ETCD_DATA_DIR")/member_removal.log" 1>&3 2>&4
        else
```

then 

-  `is_disastrous_failure` I would say there is no direct command to ask the cluster status, but we could improve it doing it relative to the current state of the cluster instead of to the values in the yaml.

```bash
current_cluster_size=get_current_members
current_min_endpoint=$((({{ $replicaCount }} + 1)/2))
...
```

Finally,

- change the way the node decides if "should I add myself back as a member". Do you have any suggestions here @dbaumgarten?

Do you guys think this could help to solve the issue? do you have any other suggestions or think something could help? @nvtkaszpir @rgarcia89 ?

**Comment by nvtkaszpir** [comment]
@rgarcia89 well, too bad, maybe it's because in general etcd is clustered so that is is always available, and not shut down/up when needed. In such case I suggest delete etcd cluster defined by CRD for the night and then spawn it back. Or use backup/restore operator - we got that working with backups to google cloud storage via backup operator and mix it with restore operator.

AFAIR the chart needs more complex script which will handle proper node shut down and replacement of the pods IP addresses when it comes back up.
I'm really very sorry but I'm not going to participate more in the upcoming discussion, due to the lack of time.

**Comment by dbaumgarten** [comment]
I did already create a modified version of the script. In my tests it did perform fine.
I also added a few "maintenance-features" that allow you to recover a broken cluster from a single node and that allow you to execute commands manually before etcd starts.

I do not expect this script to be used as it, but maybe it provides some ideas.
```
    #!/bin/bash

    set -o errexit
    set -o pipefail
    set -o nounset

    # Debug section
    exec 3>&1
    exec 4>&2

    if [ "${BITNAMI_DEBUG}" = true ]; then
        echo "==> Bash debug is on"
    else
        echo "==> Bash debug is off"
        exec 1>/dev/null
        exec 2>/dev/null
    fi

    # Constants
    HOSTNAME="$(hostname -s)"
    AUTH_OPTIONS="{{ $etcdAuthOptions }}"
    ETCDCTL_ENDPOINTS="{{range $i, $e := until $replicaCount }}{{ $etcdClientProtocol }}://{{ $etcdFullname }}-{{ $e }}.{{ $etcdHeadlessServiceName }}.{{ $releaseNamespace }}.svc.{{ $clusterDomain }}:{{ $clientPort }},{{ end }}"
    # Remove the last comma "," introduced in the string
    export ETCDCTL_ENDPOINTS="$(sed 's/,/ /g' <<< $ETCDCTL_ENDPOINTS | awk '{$1=$1};1' | sed 's/ /,/g')"
    export ROOT_PASSWORD="${ETCD_ROOT_PASSWORD:-}"
    if [[ -n "${ETCD_ROOT_PASSWORD:-}" ]]; then
        unset ETCD_ROOT_PASSWORD
    fi
    # Functions

    ## Configure RBAC
    configure_rbac() {
        # When there's more than one replica, we can assume the 1st member
        # to be created is "{{ $etcdFullname }}-0" since a statefulset is used
        if [[ -n "${ROOT_PASSWORD:-}" ]] && [[ "$HOSTNAME" == "{{ $etcdFullname }}-0" ]]; then
            echo "==> Configuring RBAC authentication!" 1>&3 2>&4
            etcd &
            ETCD_PID=$!
            while ! etcdctl $AUTH_OPTIONS member list; do sleep 1; done
            echo "$ROOT_PASSWORD" | etcdctl $AUTH_OPTIONS user add root --interactive=false
            etcdctl $AUTH_OPTIONS auth enable
            kill "$ETCD_PID"
            sleep 5
        fi
    }
    ## Try to find a working endpoint and set ETCDCTL_ENDPOINTS accordingly
    find_active_endpoint() {
        local endpoints_array=(${ETCDCTL_ENDPOINTS//,/ })

        ETCDCTL_ENDPOINTS=""
        for e in "${endpoints_array[@]}"; do
            if [[ "$e" != "$ETCD_ADVERTISE_CLIENT_URLS" ]] && (unset -v ETCDCTL_ENDPOINTS; etcdctl $AUTH_OPTIONS  endpoint health --endpoints="$e"); then
                ETCDCTL_ENDPOINTS=${e}
                break
            fi
        done
        echo "==> Chose endpoint: $ETCDCTL_ENDPOINTS"  1>&3 2>&4
    }

    ## Check if we have a filled data-dir that we can use to join the cluster
    check_local_data() {
        if [[ -d "$ETCD_DATA_DIR/member/snap" ]]; then
            DATAOK="yes"
            return 0
        fi
        DATAOK="no"
    }

    ## Ask the current cluster what state this member is in
    find_member_state() {
        local ENDPOINT_LIST=$(etcdctl $AUTH_OPTIONS member list)
        if ! echo "$ENDPOINT_LIST" | grep -q "$HOSTNAME"; then
            MEMBER_STATE="none"
            return 0
        fi
        if echo "$ENDPOINT_LIST" | grep "$HOSTNAME" | grep -q " started"; then
            MEMBER_STATE="started"
            return 0
        fi
        MEMBER_STATE="starting"
    }

    TESTFILE="$(dirname $ETCD_DATA_DIR)/testfile"
    echo "$HOSTNAME" > $TESTFILE
    if [[ $(cat "$TESTFILE") != "$HOSTNAME" ]]; then
        echo "==> Volume not writable" 1>&3 2>&4
        exit 1
    fi

    if [[ -v MANUAL_REPAIR ]]; then
    until [[ -f /tmp/start ]]; do
        echo "==> Waiting for start-signal"
        sleep 10
    done
    fi

    if [[ ! -d "$ETCD_DATA_DIR" ]]; then
        echo "==> Creating data dir..." 1>&3 2>&4
        mkdir -p "$ETCD_DATA_DIR"
        echo "==> There is no data at all. Initializing a new member of the cluster..." 1>&3 2>&4
        configure_rbac
    elif [[ {{ $replicaCount }} -eq 1 ]]; then
        echo "==> Single node cluster detected!!" 1>&3 2>&4
    elif [[ -v RECOVER_FROM ]] && [[ "${RECOVER_FROM}" == "$HOSTNAME" ]]; then
        echo "==> Strating recovery from this node" 1>&3 2>&4
        export ETCD_FORCE_NEW_CLUSTER="true"
    else
        find_active_endpoint
        if [[ "${ETCDCTL_ENDPOINTS}" != "" ]]; then
            echo "==> Found a working cluster" 1>&3 2>&4
            find_member_state
            echo "==> Member state is: $MEMBER_STATE" 1>&3 2>&4
            check_local_data
            echo "==> Having local data: $DATAOK" 1>&3 2>&4
            if [[ ${MEMBER_STATE} == "started" ]] && [[ ${DATAOK} == "yes" ]]; then
                echo "==> Returning to existing cluster" 1>&3 2>&4
            else
                if [[ ${MEMBER_STATE} != "none" ]]; then
                    echo "==> Removing myself from cluster." 1>&3 2>&4
                    MEMBER_ID=$(etcdctl $AUTH_OPTIONS member list | grep "$HOSTNAME" | awk '{ print $1}' | awk -F "," '{ print $1}')
                    etcdctl $AUTH_OPTIONS member remove --debug=true $MEMBER_ID
                fi
                echo "==> Cleaning datadir" 1>&3 2>&4
                rm -rf ${ETCD_DATA_DIR}/* || true
                echo "==> Joining cluster" 1>&3 2>&4
                etcdctl $AUTH_OPTIONS member add "$HOSTNAME" --peer-urls="{{ $etcdPeerProtocol }}://${HOSTNAME}.{{ $etcdHeadlessServiceName }}.{{ .Release.Namespace }}.svc.{{ $clusterDomain }}:{{ $peerPort }}" | grep ETCD_ > joinenv.txt
                sed -i -e 's/^/export /' joinenv.txt
                cat joinenv.txt
                source joinenv.txt  
            fi
        else
          echo "==> No active endpoints found. Starting etcd and hoping for the best" 1>&3 2>&4
        fi
    fi


    {{- if .Values.configFileConfigMap }}
    exec etcd --config-file /opt/bitnami/etcd/conf/etcd.conf.yml 1>&3 2>&4
    {{- else }}
    exec etcd 1>&3 2>&4
    {{- end }}
```

**Comment by rgarcia89** [comment]
I see there are a lot of good ideas. However, with the current chart version, it is not even possible to modify the deployment by for example adding `envVarsConfigMap` in case you mist it, in the first place without breaking it. Therefore, I would really appreciate it, if we could get a hotfix in place to make this work. Further improvements could be addressed as next step. My option at least

**Comment by dbaumgarten** [comment]
Updating the setup.sh script does not require changing anything in the deployment.
The updated script I am using is (nearly) completely compatible to the current chart.
The only thing that is missing is the original disaster recovery feature. As I am not using it, I just left it out when doing my changes.

While I generally agree, that a short fix should be the first step, I do think it is difficult to find a hotfix for these deeply rooted issues.

**Comment by sfesfizh** [comment]
I did some tests with provided solution and confirm it works when the on the node (pod) fails it can rejoin after.
But I tried to kill two pods of three in the cluster and none of them can up again. They are in a continuous fail loop.

**Comment by rgarcia89** [comment]
This has todo something with this update...
https://github.com/bitnami/charts/commit/f234cc7ff1c59950de819151b2da221d72ec24b6#diff-13f2888821f2166e69fef5282a0b4d81

I already mentioned it in the merge but nobody seems to care :-1:

**Comment by juan131** [comment]
Hi @rgarcia89 @sfesfizh 

Please let's move the conversation to this issue to avoid having duplicated threads https://github.com/bitnami/charts/issues/3190

**Comment by Excpt0r** [comment]
Hi @juan131 
the referenced issue #3190 is closed and seems to work, but the described issue here not.
I think the solution with setting initialClusterState works only when some cluster members are killed/restarted, but a running majority remains.

With latest chart version 5.6.0 I reproduced this issue with doing helm install, uninstall and install again. The pods will fail.
As @turkenh has pointed out, the member removal in prestop-hook.sh is the problem, and his hotfix is working.
Personally, I would prefer to include this hotfix until a final solution, to be able to re-install the chart, but losing the scaling ability.

The values.yaml I used is the default one, with the following changes:
debug: true
replicaCount: 3
podAntiAffinityPreset: hard

Maybe this issue could be re-opened.

**Comment by marcosbc** [comment]
Hi @Excpt0r, could you open a new issue instead? There have been a lot of things going on here. Adding a small note linking to this issue would be more than enough to locate anyone wanting to investigate more. If you could also link to the specific hotfix you mentioned it would be great.

> I also had a look into https://github.com/bitnami/charts/tree/master/bitnami/etcd#disaster-recovery
>if that might help here. Using a snapshot as starting point, does that mean data between the last snapshot and the failure of etcd is lost?

Exactly, that's why the schedule of the cronjob is set to create a snapshot each 30 minutes (see parameters section), and not each day or more.
