### ISSUE TITLE
bitnami/logstash-exporter info needed

### ISSUE THREAD

**Issue by kokesz1202** [bitnami/charts#19230]
### Name and Version

bitnami/logstash-exporter-archived

### What is the problem this feature will solve?

My lack of info about the docker image.

### What is the feature you are proposing to solve the problem?

Hello all,

Is there any information publicly available why this docker image archived and what are the alternatives to it?

Thanks in advance!

**Comment by carrodher** [comment]
It was deprecated since the upstream project where it was based was archived, see https://github.com/sequra/logstash_exporter.

It was removed from the bitnami/logstash Helm chart at https://github.com/bitnami/charts/pull/10233 and documented its removal at https://github.com/bitnami/charts/tree/main/bitnami/logstash#to-500
