### ISSUE TITLE
bitnami/minio values.yaml How to set the access policy of a bucket to access: "PUBLIC"

### ISSUE THREAD

**Issue by liuxin638507** [bitnami/charts#19523]
### Name and Version

bitnami/minio	12.8.9

### What is the problem this feature will solve?

How can I set the access policy of a bucket to access: "PUBLIC" but the setting does not take effect
![image](https://github.com/bitnami/charts/assets/32058132/bc75d101-a6f0-410d-916c-eaff75028683)

### What is the feature you are proposing to solve the problem?

How can I set the access policy of a bucket to access: "PUBLIC" and   Access Keys or  service Accounts,Please give an example

**Comment by juan131** [comment]
Hi @liuxin638507 

There's no support for any `provisioning.buckets[].access` property, please check the supported properties in the values below:

- [values.yaml#L342-L376](https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L342-L376)

In the piece of code below you can find how the chart iterates over the `provisioning.buckets` using a series of [mc commands](https://min.io/docs/minio/linux/reference/minio-mc.html) to create the bucket, set the quota, etc.

- [provisioning-job.yaml#L178-L194](https://github.com/bitnami/charts/blob/main/bitnami/minio/templates/provisioning-job.yaml#L178-L194)

In order to be able to set/remove anonymous policies, it's required to use the [mc anonymous](https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous.html) command but currently the chart doesn't support mechanisms to use it while provisioning.

Feel free to contribute improving the logic that iterates over `buckets` including support for setting anonymous access when a new parameter (e.g. ``provisioning.buckets[].anonymous`) is set to `true`.

**Comment by liuxin638507** [comment]
> 你好
> 
> 不支持任何属性，请检查以下值中支持的属性：`provisioning.buckets[].access`
> 
> * [值.yaml#L342-L376](https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L342-L376)
> 
> 在下面的一段代码中，您可以找到图表如何使用一系列 [mc 命令](https://min.io/docs/minio/linux/reference/minio-mc.html)来创建存储桶、设置配额等进行迭代。`provisioning.buckets`
> 
> * [provisioning-job.yaml#L178-L194](https://github.com/bitnami/charts/blob/main/bitnami/minio/templates/provisioning-job.yaml#L178-L194)
> 
> 为了能够设置/删除匿名策略，需要使用 [mc anonymous](https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous.html) 命令，但目前图表不支持在预配时使用它的机制。
> 
> 随意贡献改进迭代的逻辑，包括支持在新参数（例如）设置为时设置匿名访问。`buckets``provisioning.buckets[].anonymous``true`

sorry，You are right
hank you ，I added a new line in provisioning-job.yaml to set permissions, which can also be set as variables
vim templates/provisioning-job.yaml
183 mc mb {{ $target }} --ignore-existing {{ $region }} {{ $withLock }};
184 mc anonymous set download {{ $target }};

> Hi @liuxin638507
> 
> There's no support for any `provisioning.buckets[].access` property, please check the supported properties in the values below:
> 
> * [values.yaml#L342-L376](https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L342-L376)
> 
> In the piece of code below you can find how the chart iterates over the `provisioning.buckets` using a series of [mc commands](https://min.io/docs/minio/linux/reference/minio-mc.html) to create the bucket, set the quota, etc.
> 
> * [provisioning-job.yaml#L178-L194](https://github.com/bitnami/charts/blob/main/bitnami/minio/templates/provisioning-job.yaml#L178-L194)
> 
> In order to be able to set/remove anonymous policies, it's required to use the [mc anonymous](https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous.html) command but currently the chart doesn't support mechanisms to use it while provisioning.
> 
> Feel free to contribute improving the logic that iterates over `buckets` including support for setting anonymous access when a new parameter (e.g. `provisioning.buckets[].anonymous`) is set to `true`.



> Hi @liuxin638507
> 
> There's no support for any `provisioning.buckets[].access` property, please check the supported properties in the values below:
> 
> * [values.yaml#L342-L376](https://github.com/bitnami/charts/blob/main/bitnami/minio/values.yaml#L342-L376)
> 
> In the piece of code below you can find how the chart iterates over the `provisioning.buckets` using a series of [mc commands](https://min.io/docs/minio/linux/reference/minio-mc.html) to create the bucket, set the quota, etc.
> 
> * [provisioning-job.yaml#L178-L194](https://github.com/bitnami/charts/blob/main/bitnami/minio/templates/provisioning-job.yaml#L178-L194)
> 
> In order to be able to set/remove anonymous policies, it's required to use the [mc anonymous](https://min.io/docs/minio/linux/reference/minio-mc/mc-anonymous.html) command but currently the chart doesn't support mechanisms to use it while provisioning.
> 
> Feel free to contribute improving the logic that iterates over `buckets` including support for setting anonymous access when a new parameter (e.g. `provisioning.buckets[].anonymous`) is set to `true`.

You are right
hank you ，I added a new line in provisioning-job.yaml to set permissions, which can also be set as variables
vim templates/provisioning-job.yaml
183 mc mb {{ $target }} --ignore-existing {{ $region }} {{ $withLock }};
184 mc anonymous set download {{ $target }};
