### ISSUE TITLE
[bitnami/airflow]: Jobs don't run

### ISSUE THREAD

**Issue by bappr** [bitnami/charts#1978]
Hey guys,

I am using your airflow helm chart that I deployed on my K8S cluster.

Every component is deployed and running. I deployed Redis (your helm chart) and Postgres (my helm chart) as external dependencies.

```
cs-airflow-scheduler-5bdd477cd9-n48jx   1/1     Running   0          8h
cs-airflow-web-5b474647bd-v59lv         1/1     Running   0          2d13h
cs-airflow-worker-0                     1/1     Running   1          2d13h
cs-postgres-postgresql-0                1/1     Running   0          2d13h
cs-redis-master-0                       1/1     Running   0          2d13h
```

Accessing and login to the UI is fine. I enabled the "autoloadExamples" so that airflow is not empty and I can play with it.

However, when I trigger the jobs, nothing happen. I can see the job having a RUNNING state. But nothing else. No logs in the worker or scheduler.

It seems that the worker/scheduler are just standing idle here, doing nothing.

Did I miss something?

**Comment by javsalgar** [comment]
Hi,

Did you check the logs or the task instance details? Does it show anything meaningful?

**Comment by bappr** [comment]
Hey @javsalgar 
Nop it's empty.

**Comment by javsalgar** [comment]
Hi,

I think I was able to reproduce the issue. We'll need to take a more in-depth look to understand what the issue is. I will update this thread as soon as we have more news.

Thanks for reporting

**Comment by Mauraza** [comment]
Hello @bappr, 
 
I was testing airflow, this application needs a lot of resources. I was able to reproduce the issue, so I change the cluster because of the pods restarted when I try to run a dag. The first time airflow finished a job it takes too many time so I thought maybe it was for the resources, then I  increased the replicates, and the jobs finished sooner.
![image](https://user-images.githubusercontent.com/17168510/76983021-05d52e00-693d-11ea-9bce-970f88bad86f.png)

I suggest you add more workers, to do the jobs and please check they aren't restarted.
I've realized some times when airflow doesn't have enough resources the pods often restarted. That's could be the reason you don't have any log.

With three workers It's working fine.

```
NAME                                            READY   STATUS    RESTARTS   AGE
NAME                                            READY   STATUS    RESTARTS   AGE
my-release-airflow-scheduler-766c79bd79-kplqs   1/1     Running   0          5h1m
my-release-airflow-web-dfff97bd5-s78v8          1/1     Running   0          84m
my-release-airflow-worker-0                     1/1     Running   0          5h1m
my-release-airflow-worker-1                     1/1     Running   0          85m
my-release-airflow-worker-2                     1/1     Running   0          83m
my-release-postgresql-0                         1/1     Running   0          5h1m
my-release-redis-master-0                       1/1     Running   0          5h1m
my-release-redis-slave-0                        1/1     Running   0          5h1m
my-release-redis-slave-1                        1/1     Running   0          5h

```

I hope this helps you and please asking again if you have any questions.
