### ISSUE TITLE
[bitnami/zookeeper] Support for pod/statefulset annotations

### ISSUE THREAD

**Issue by jshrack-ssi** [bitnami/charts#1991]
**Which chart**:
Zookeeper

**Description**
I'd like to see support for pod/statefulset annotations. We require such to support external monitoring via DataDog.

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**
No ability to add pod/statefulset annotations via Helm Chart overlay.

**Describe the results you expected:**
Ability to add pod/statefulset annotations.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Comment by miguelaeh** [comment]
Hi @jshrack-ssi ,
Thank you very much for your suggestion. We will add it when we have the chance.
If you prefer you can also create a PR adding it.
Regards.

**Comment by javsalgar** [comment]
Not stale

**Comment by miguelaeh** [comment]
Hi @jshrack-ssi ,
We have added the `podAnnotations` section, could you give it a try?

**Comment by miguelaeh** [comment]
not stale

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
