### ISSUE TITLE
[bitnami/kubeapps] oauthProxy.clientSecret may be empty/unset, should not be required

### ISSUE THREAD

**Issue by sspreitzer** [bitnami/charts#20236]
### Name and Version

bitnami/kubeapps 14.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Enable oauthProxy
2. Not setting a oauthProxy clientSecret

### Are you using any custom parameters or values?

```yaml
oauthProxy:
  enabled: true
  clientSecret: null
```

### What is the expected behavior?

It should use OpenID Connect without a client secret

### What do you see instead?

Value is required Helm error message

**Comment by andresbono** [comment]
Hi, thanks for opening this issue. I can reproduce it with the following command:

```console
$ helm install kubeapps oci://docker.io/bitnamicharts/kubeapps --version 14.0.1 --set authProxy.enabled=true --set authProxy.clientID=foo --set authProxy.clientSecret=null

Error: INSTALLATION FAILED: execution error at (kubeapps/templates/frontend/oauth2-secret.yaml:19:19): You must fill ".Values.authProxy.clientSecret" with the Client Secret of the provider
```

Is that the error that you find? I see that error message just as a validation to give the user an early warning. Isn't the `client-secret` mandatory for OAuth2 Proxy? See this issue: https://github.com/oauth2-proxy/oauth2-proxy/issues/1714

If I run the oauth2-proxy container (standalone), the binary also complains of a missing client-secret:

```console
$ docker run --rm --entrypoint=oauth2-proxy docker.io/bitnami/oauth2-proxy:7.5.1-debian-11-r10
[2023/10/17 10:17:26] [main.go:54] invalid configuration:
  missing setting: cookie-secret
  provider missing setting: client-id
  missing setting: client-secret or client-secret-file
  missing setting for email validation: email-domain or authenticated-emails-file required.
      use email-domain=* to authorize all email addresses
```

If you still think that the issue is related to the Helm chart itself, can you give us more details on your use case? In particular, what [OAuth Provider](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/) are you using?
