### ISSUE TITLE
{feature request} Onboard [bitnami/metallb] and [bitnami/contour] helm charts.

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#2030]
## Why?

Bitnami provides easy to extend and use Helm Charts.
I want to provide the same for MetalLB and Contour.
We use Bitnami Helm charts heavily in our own projects.

## Clarification of onboarding process

* What should be provided from me?
* What should be looked out for when onboarding?
* What are the requirements?
* Are their templates for the bitnami-docker-\<software\> repositories?

## metallb
A LoadBalancer for Kubernetes.

* My current chart implementation
[release/charts/metallb/README.md](https://github.com/Cellebyte/helm/blob/release/charts/metallb/README.md)
* The project.
[MetalLB](https://github.com/metallb/metallb/)

## contour
A IngressController for Kubernetes with CRDs.

* My current chart implementation
[release/charts/contour/README.md](https://github.com/Cellebyte/helm/blob/release/charts/contour/README.md)
* The project.
[Contour](https://github.com/projectcontour/contour)

**Comment by carrodher** [comment]
Hi @Cellebyte,

Thanks for your proposal, we are happy to add new charts to this repository.

Answering your questions:
> What should be provided from me?
> What should be looked out for when onboarding?
> What are the requirements?

There are only three major requirements:
- Use Bitnami based container images
- Follow the same structure/patterns that the rest of the Bitnami charts
- Use an [OSI approved](https://opensource.org/licenses) license for all the software

We have a guide about [Best Practices for Creating Production-Ready Helm charts](https://docs.bitnami.com/tutorials/production-ready-charts/) but apart from that, I recommend you to use one of the existing charts as an example.

In the same way, we recently migrated our charts from `stable` to this repository, as part of the 2nd-day operations, we are going to create some contributions guideline for this repository, but they are still in progress due to the early stage of the migration.

> Are their templates for the bitnami-docker-<software> repositories?

Those repositories are the ones hosting the code for the docker images, each image that the chart includes should have the corresponding `bitnami-docker-image` repository. For example, the fluentd image is based in a bash approach and all the required files can be found in [this folder](https://github.com/bitnami/bitnami-docker-fluentd/tree/master/1/debian-10). But that is something we can do on our side or help you with it.

Once created the chart and the images in GitHub we will take care of integrating everything into our pipeline to get the benefit of the automatic updates, push to the main registries, etc

**Comment by carrodher** [comment]
Hi @Cellebyte,

we just started working on the `bitnami-docker-metallb` and `bitnami-docker-contour` images that is the requirement more bitnami-dependant.

If you have any question or doubt creating the charts, please, don't hesitate to ping us!

**Comment by Cellebyte** [comment]
@carrodher the charts are currently in my own repository. If you are missing something don't hesitate to reach out to me or create an issue.
I like to migrate them into your repository as a PullRequest.

https://github.com/Cellebyte/helm/tree/release/charts

**Comment by carrodher** [comment]
It would be nice if you can create the PRs (separately) so we can start reviewing them and then add the proper images once finished this part on our side, what do you think?

**Comment by Cellebyte** [comment]
Mark it as non stale. Because the PRs are still open.

**Comment by carrodher** [comment]
It will not happen again!

**Comment by carrodher** [comment]
Pending the contour one
