### ISSUE TITLE
[wordpress] missing module imagick

### ISSUE THREAD

**Issue by polRk** [bitnami/charts#2048]
<img width="823" alt="Снимок экрана 2020-03-13 в 3 37 26 PM" src="https://user-images.githubusercontent.com/39828645/76621495-8c0a0280-6540-11ea-83a6-db2106ce0a88.png">
The optional module, imagick, is not installed, or has been disabled.

**Comment by rafariossaa** [comment]
Hi @polRk ,
  You will need to use a custom WP image. [Here](https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image) you can find information on how to do this.

**Comment by polRk** [comment]
Thank you

**Comment by frankoonk** [comment]
Is it possible to add this specific php.ini extension in further releases? Because it's a standard WordPress improvement and i don't want to use a custom WP Image, because of future updates.

**Comment by rafariossaa** [comment]
Hi,
  The current image contains php with imagick but the extension is disabled.
  Instead of creating new image, you can extend ours to enable imagick. This way, when you want to update only you need to extend the same way the new image.
  To enable imagick you need to uncomment the following line from `/opt/bitnami/php/lib/php.ini`:
```
;extension = imagick
```
  You have an example on how to extend a WP image in this [link](https://github.com/bitnami/bitnami-docker-wordpress#user-content-customize-this-image).
