### ISSUE TITLE
[bitnami/kafka] kafka broker crash

### ISSUE THREAD

**Issue by derekcha** [bitnami/charts#20496]
### Name and Version

bitnami/kafka:3.5.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I was previously using bitnami/kafka:3.4.0, and was also using zookeeper.
I am testing kraft application while using version 3.5.1.
I tried using the migration method provided in the document (https://github.com/bitnami/charts/tree/main/bitnami/kafka#migrating-from-zookeeper-early-access), but a crash occurred in the broker after step 4.
The crash error is as follows.

```
kafka 08:30:57.87 INFO  ==> Formatting storage directories to add metadata...
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: If process.roles contains just the 'broker' role, the node id 0 must not be included in the set of voters controller.quorum.voters=Set(0, 1)
        at scala.Predef$.require(Predef.scala:281)
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:2246)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:2160)
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1568)
        at kafka.tools.StorageTool$.$anonfun$main$1(StorageTool.scala:50)
        at scala.Option.flatMap(Option.scala:271)
        at kafka.tools.StorageTool$.main(StorageTool.scala:50)
        at kafka.tools.StorageTool.main(StorageTool.scala)
```

### Are you using any custom parameters or values?

```yaml
kraft:
  enabled: true
  clusterId: "~~~~~"

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT


controller:
  zookeeperMigrationMode: false
  controllerOnly: true
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 2Gi
  replicaCount: 2

broker:
  zookeeperMigrationMode: false

  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 2Gi
  replicaCount: 2

  priorityClassName: scheduling-first

  pdb:
    create: true


  persistence:
    enabled: true
    #size: 25Gi
    #existingClaim: data-log-stack-kafka

metrics:
  kafka:
    enabled: false
  jmx:
    enabled: false


zookeeper:
  enabled: false
  replicaCount: 2
```

### What is the expected behavior?

the container should start

### What do you see instead?

exited code 1

**Comment by mshivanna** [comment]
Is there any update on this? We are trying to migrate from zookeeper to Kraft following the steps described in the README.md file

**Comment by migruiz4** [comment]
Hi @mshivanna,

I'm sorry this case wasn't replied in time. 
I think the issue has to do with the Kafka node ID during the migration.

Kafka will reuse the existing ID during the migration, but newly deployed Controller nodes are not aware of the `node.id` of the existing brokers.

Considering this is the error log:
```
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: If process.roles contains just the 'broker' role, the node id 0 must not be included in the set of voters controller.quorum.voters=Set(0, 1)
```

If I'm not mistaken, depending on when your Kafka was deployed, it may be possible your Broker nodes are using IDs 0, 1, 2...

By default, the new Controller nodes are also configured to use IDs starting on 0. Therefore, Broker nodes are being configured with controller quorum `0@controller-node-0`, and failing with the error above (because they are already using the ID 0).

If I'm not mistaken, changing the `node.id/broker.id` is not possible without flushing the partition data, so the proper way to solve this issue would be to set `controller.minID` to use a controller range ID different than the IDs already used by the brokers.

If the controller node was already started, it may be possible that it was already configured with ID 0 and will attempt to reuse it, so you may need to remove the PVC for the controller node.

**Comment by mshivanna** [comment]
ah makes sense, will give it a try. our brokers have ids (0,1,2) and we set the controller ID(100). We might have been using stale zookeeper data. Will test it and let you know. thanks.
