### ISSUE TITLE
[bitnami/redis-cluster] How to disable persistence and use `persistence.enabled` and `redis.useAOFPersistence` combination

### ISSUE THREAD

**Issue by northtyphoon** [bitnami/charts#20497]
### Name and Version

bitnami/redis-cluster 9.0.13

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have a question about disabling persistence. My goal is to have the data in memory only and avoid writing data on volume. I see two related options `persistence.enabled` and `redis.useAOFPersistence`. If I just set `persistence.enabled` to false, the AOF file is still created. I want to check if I need to disable both.

### What do you see instead?

If I just set `persistence.enabled` to false, the AOF file is still created.

**Comment by aoterolorenzo** [comment]
Hi @northtyphoon,

Using `persistence.enabled=false` will prevent the application from using a PVC (and therefore, to persist any fail after the cluster stops). On the other hand, `redis.useAOFPersistence` is used to enable AOF persistence in redis, this means: write to a file in append mode. So, even setting this to true, since there's no PVC, there will be no persistense. Said that, you probably don't want to have the cluster writting to a file that will never be persisted, so probably you will want to set both to false.
