### ISSUE TITLE
[bitnami/minio] Bad PVC Template in minio distrubuted

### ISSUE THREAD

**Issue by mhkarimi1383** [bitnami/charts#21024]
### Name and Version

bitnami/minio 12.1.10

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. in any setup
2. create a minio release (with more than one drive per node)
3. change drive per node to 1 and upgrade chart
4. you will see that new pvcs are created with new names :/

### Are you using any custom parameters or values?

Just changing drives per node

### What is the expected behavior?

no new volumes for upgraded realese

### What do you see instead?

new volumes with new names

**Comment by migruiz4** [comment]
Hi @mhkarimi1383,

I would say this is expected behavior and changing from a single drive to multiple drives per node is not supposed to be performed on the fly when upgrading the `bitnami/minio` chart.

If you would like to switch an existing deployment from single drive mode to multiple drives per node, you will need to perform manual actions.

I know it is not the same case, but in case it helps you can find a similar example about how to reclaim existing persistentVolumes in our Kafka chart README.md: https://github.com/bitnami/charts/tree/main/bitnami/kafka#retaining-persistentvolumes.

**Comment by mhkarimi1383** [comment]
Oh,
I see

But I wanna know the reason for that condition

**Comment by migruiz4** [comment]
Here is the bitnami/minio chart logic that controls the persistent volumes:
https://github.com/bitnami/charts/blob/cd3c48b1d7046d653e5d666527f7ccf8b6fe2b2d/bitnami/minio/templates/distributed/statefulset.yaml#L301-L337

I think that at the time the multiple drives per node feature was added, it was not designed to be performed during upgrades, at least from 1->n, probably to not introduce a breaking change by naming that forced all users to reassign their PersistentVolumes.

**Comment by mhkarimi1383** [comment]
@migruiz4,
I saw the logic that was why I created this issue and that was interesting to me to know the reason
