### ISSUE TITLE
[bitnami/common] Bug in common.images.version

### ISSUE THREAD

**Issue by manuelstein** [bitnami/charts#21089]
### Name and Version

bitnami/common 2.13.3

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Use an .imageRoot.tag that doesn't match the regex in https://github.com/bitnami/charts/blob/9dde49c88c7a45d7fa36df5b81c285a627bad896/bitnami/common/templates/_images.tpl#L110
2. Helm tries to render `.chart.AppVersion` which should be `.Chart.AppVersion` in https://github.com/bitnami/charts/blob/9dde49c88c7a45d7fa36df5b81c285a627bad896/bitnami/common/templates/_images.tpl#L110-L115
3. Throws error

### What do you see instead?

Error

**Comment by Mauraza** [comment]
Hi @manuelstein,

I just created a PR to fix it.

**Comment by migruiz4** [comment]
Hi @manuelstein,

Could you please share more information about your issue?

It would be helpful if you could provide an example to reproduce your issue and which chart were you using when you encountered this issue.

In this case `.chart != .Chart` because it references the input value "chart" described in the usage example:
https://github.com/bitnami/charts/blob/9dde49c88c7a45d7fa36df5b81c285a627bad896/bitnami/common/templates/_images.tpl#L103-L106

**Comment by manuelstein** [comment]
Oh, okay, then I guess I was using it wrong
