### ISSUE TITLE
[Odoo 17] Error when viewing shopping cart: POP_JUMP_FORWARD_IF_NOT_NONE

### ISSUE THREAD

**Issue by nuelgoz** [bitnami/charts#21293]
### Name and Version

bitnami/odoo 17.0.20231105-debian-11-r2

### What architecture are you using?

Rancher RKE2

### What steps will reproduce the bug?

After installing the template and accessing the data path, installing the ecommerce module, and clicking on the cart page, an error occurs in the web template views.

### What is the expected behavior?

The expectation is that the template displays correctly and does not generate any errors.

### What do you see instead?

Instead, an error appears in the ecommerce cart view.

[Odoo 17] Error when viewing shopping cart: POP_JUMP_FORWARD_IF_NOT_NONE

### Additional information

It is possible that this error may be resolved by updating the Odoo version, as the current version predates the release of Odoo 17.

**Comment by joancafom** [comment]
Hi @nuelgoz 

Thanks for reaching out to us, I confirm the issue is reproducible on my side. I have checked and there seems to be an [identical upstream issue](https://www.odoo.com/forum/help-1/odoo-17-error-when-viewing-shopping-cart-pop-jump-forward-if-not-none-236611), so I fear this could be something related to the application/module itself and not to the bitnami packaging. 

In this case, I recommend you reach out to the original developer, as there is little we can do on our side. Thanks again 😁 .

**Comment by Spider4eyes** [comment]
I still face the issue in odoo 16 when install stock module
