### ISSUE TITLE
[bitnami/minio] Is it normal that no ingress be defined when web ui is disabled?

### ISSUE THREAD

**Issue by zadigus** [bitnami/charts#2167]
**Which chart**:
bitnami/minio

**Describe the bug**
If I set `ingress.enabled=true` and `disableWebUI=true`, then I get no ingress. I am wondering why there should be no ingress when the web ui is disabled. It might indeed be that I need access to my minio instance even without web ui, might it not? For example, assuming I am setting policy public to some of my buckets, how do I access their contents without an ingress from a frontend application? Is there something fundamental I am missing here? Am I trying to use minio in the wrong way?

To be more precise: assuming I have called
```
mc policy set public my-minio-alias/my-bucket
```
To access an element contained in `my-bucket`, I browse e.g. http://my-minio-instance/my-bucket/my-element.jpg. That works only with an ingress, or is there another way for my frontend app in my cluster to get that jpg from my minio instance?

**Comment by miguelaeh** [comment]
Hi @zadigus ,
An ingress is a resource that applies only to `http` and `https` ports, so if there is not a web UI active, it has no sense to access it using an ingress. In the case you need to access Minio without the Ingress you can always use the service as LoadBalancer and set a LoadBalancerIP
I hope this information is helpful, feel free to continue the thread if there is something not clear.
Regards.

**Comment by zadigus** [comment]
@miguelaeh making my assets publicly available let me access them via
```
http(s)://my-minio-instance/my-bucket/my-element.jpg
```
It can therefore well be that I need `http` / `https` access without the web ui, can't it be? I haven't actually tested that, but I guess it is possible to 
```
mc policy set public my-minio-alias/my-bucket
```
and then 
```
mc cp my-element.jpg my-minio-alias/my-bucket/my-element.jpg
```
without web ui, because here I'm only using `mc`. And finally, if I want to access `my-element.jpg`, I need `http` / `https` access, because it is available over
```
http(s)://my-minio-instance/my-bucket/my-element.jpg
```
That's why I don't understand https://github.com/bitnami/charts/blob/master/bitnami/minio/templates/ingress.yaml#L1. There you disable the ingress resource if the web ui is disabled and the ingress is disabled. In my opinion, that makes no sense, but I might be missing a point.

**Comment by miguelaeh** [comment]
Hi @zadigus ,
If you deploy the chart using a LoadBalancerIP you should be able to use that IP and the port (by default `9000`) to send `http` request, it will not block the `http` traffic. An Kubernetes Ingress is normally used to expose a GUI, so that is why it is disabled if there is no GUI.
Could you give a try to the LoadBalancerIP? You should be able to make the request without problems.
The only thing the Ingress does is to take the request that receives in the ports `80` and `443` and sent them to the Kubernetes service used to access the minio Pods.  If you don't use the Ingress but you expose the Service that to the LoadBalancerIP you will be connected directly to the service that is used to access the Pods.
