### ISSUE TITLE
Nginx: Cannot bind to port 80, if `serverBlock` is used

### ISSUE THREAD

**Issue by max-wittig** [bitnami/charts#2186]
**Which chart**:
nginx: 5.1.12

**Describe the bug**
If serverBlock is defined like this:

```
  serverBlock: |-
    server {
      listen 0.0.0.0:80;

      location / {
         proxy_pass http://web:8000/;
      }
    }
```

then nginx crashes with this message

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
```

If nothing is defined, nginx will happily display it's default start page on port 80

**Comment by Mauraza** [comment]
Hi @max-wittig,

That's happened because it doesn't have privileges to bind the port 80. I recommend using another port.

**Comment by max-wittig** [comment]
@Mauraza Thanks for the response. It does have the privileges, otherwise the default nginx start page wouldn't work, right?

**Comment by Mauraza** [comment]
The container executes like non-root so you can't use the port 80.

**Comment by max-wittig** [comment]
But why does it work in default config, without the custom `serverBlock`?

**Comment by machine424** [comment]
@max-wittig , here there !

If you're using the docker image by default, the container runs an nginx that listens on `0.0.0.0:8080`, you can see the config with `kubectl exec` to the pod and `cat /opt/bitnami/nginx/conf/nginx.conf`.

You can modify the port number by passing the env var `NGINX_HTTP_PORT_NUMBER` to the container, see: https://github.com/bitnami/bitnami-docker-nginx/blob/master/1.16/debian-10/rootfs/opt/bitnami/scripts/libnginx.sh#L179
and set your port here also: https://github.com/bitnami/charts/blob/master/bitnami/nginx/templates/deployment.yaml#L39
so that liveness probe doesn't kill the container.

if you set `NGINX_HTTP_PORT_NUMBER` to 80 for example, you will see the same behaviour as with your serverBlock: nginx will not start, because as @Mauraza has mentioned, the user trying to do so (1001) doesn't have the right to bind privileged ports inside the sontainer.

the port 80 you've mentioned is the service's, it wraps 8080, the port that nginx listens on by default. So maybe you were port-forwarding to the service:80.

**Comment by Mauraza** [comment]
@machine424, thanks for you contributing! I hope that's help @max-wittig.

**Comment by max-wittig** [comment]
@machine424 Thanks for the detailed response!

**Comment by buffaloDeveloper** [comment]
@max-wittig how did you send resolving this issue?  I'm running into the same problem with port 80 permissions.

**Comment by max-wittig** [comment]
Just ended up using my own `deployment_nginx.yaml` which was way less complicated and switched to Kustomize.
