### ISSUE TITLE
Hello, would you please consider providing Sentry support because the current official Charts are too complicated?

### ISSUE THREAD

**Issue by oomgomgxx** [bitnami/charts#21899]
### Name and Version

bitnami/sentry

### What is the problem this feature will solve?

Hello, would you please consider providing Sentry support because the current official Charts are too complicated?

### What is the feature you are proposing to solve the problem?

Hello, would you please consider providing Sentry support because the current official Charts are too complicated?

**Comment by carrodher** [comment]
Unfortunately, Sentry is not licensed under an open source license.

Hi, unfortunately after an internal review, and because Sentry is not licensed under an open source license, this solution was not considered to be added to the catalog.

We apologize for the inconvenience. We will be sure to reconsider it in the future if something changes.

Thanks for your suggestion!
