### ISSUE TITLE
[bitnami/schema-registry] Schema Registry Persistency

### ISSUE THREAD

**Issue by morkalfon** [bitnami/charts#21949]
### Name and Version

Latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

It's just a general question: since Confluent Schema Registry doesn't add any persistent volumes and store all in-memory. 
How can I achieve persistency of the schema if pods get deleted?

### What do you see instead?

No schema after pods get deleted.

**Comment by javsalgar** [comment]
Hi

This seems to be a question more related to the Schema Registry itself rather than the Bitnami packaging of Schema Registry. My advice would be to check with the upstream schema-registry devs. 

I found this link which may help with the question: https://stackoverflow.com/questions/45275334/confluent-schema-registry-persistence
