### ISSUE TITLE
[bitnami/joomla] website maintenance mode breaks readiness probe

### ISSUE THREAD

**Issue by funtimeerror** [bitnami/charts#22531]
### Name and Version

bitnami/joomla 18.0.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. after installation login to administrator panel   (www.website.com/administrator)
2. navigate to "System -> Global Configuration"
3. change "Site Offline" toggle to "yes"
4. press "Save" in top left (index.php will now return http status 503, all css files, images and admin url still return http 200)
5. removing the readiness probe or setting the url to the administrator page brings the site back up

### What is the expected behavior?

The joomla index.php when in maintenance mode is browsable and allows you to provide custom text
![maintenance_mode_index_php](https://github.com/bitnami/charts/assets/885198/f9e36331-410e-4ef6-a000-e2db0df4972f)

### What do you see instead?

pod readiness probe fails due to index.php http status showing 503 which in turn brings down the website

### Additional information

should the readiness probe look at the administrator index.php since that will have a status 200 when the site is in maintenance mode?

**Comment by migruiz4** [comment]
Hi @funtimeerror,

I think this issue could be fixed by replacing the Joomla probes to use the admin panel path instead of the `index.php`.

https://github.com/bitnami/charts/blob/bc4b1dcd3ba113f5a1e75b6a65ba522acc241dc5/bitnami/joomla/templates/deployment.yaml#L152-L190

Would you like to contribute by sending a PR?
