### ISSUE TITLE
[bitnami/kafka] v10.1.0 Unable to set ssl.client.auth=none using Environment Variables

### ISSUE THREAD

**Issue by adityajalkhare** [bitnami/charts#2256]
**Which chart**:
[bitnami/kafka] 10.1.0

**Describe the bug**
Unable to set `ssl.client.auth`=`none` using Environment Variables

**To Reproduce**
Enable SSL, provide secret containing keystore and truststore to be used by Kafka, configure proper Listeners.

Keystore and Truststore names are according to README.md

`listeners`, `advertisedListeners`, `listenerSecurityProtocolMap`, `interBrokerListenerName` config:
```
listeners: "SSL://:9093,PLAINTEXT://:9092"

advertisedListeners: "SSL://$(MY_POD_IP):9093,PLAINTEXT://$(MY_POD_IP):9092"

listenerSecurityProtocolMap: "SSL:SSL,PLAINTEXT:PLAINTEXT"

interBrokerListenerName: PLAINTEXT
```
**Expected behavior**
Kafka Cluster comes into running state, with `ssl.client.auth`=`required`, whereas, I tried setting it using `extraEnvVars` feature with parameters:
```
- name: KAFKA_SSL_CLIENT_AUTH
  value: none
```
and
```
- name: KAFKA_CFG_SSL_CLIENT_AUTH
  value: none
```
but still `ssl.client.auth`=`required` is seen in logs and server.properties (checked inside pod).

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"c52f59bbba5fbf21fbb18e9a06f96e563fe4c20a", GitTreeState:"clean", BuildDate:"2020-01-31T20:00:26Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
None

**Comment by juan131** [comment]
Hi @adityajalkhare 

I guess you enabled SSL by setting the `auth.ssl` chart parameter to `true` without enabling authentication (setting the `auth.enabled` chart parameter to `false`). When that's done, you can leave `listeners` and `advertisedListeners` parameters unset, and Kafka should be properly configured, see:

- https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L158
- https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L171

When the Kafka container detects the SSL protocol in the listeners, it'll configure `ssl.client.auth=required`, see:

- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L407
- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L332
- https://github.com/bitnami/bitnami-docker-kafka/blob/master/2/debian-10/rootfs/opt/bitnami/scripts/libkafka.sh#L290

That configuration will be written in the configuration file and it takes precedence over the environment variable  `KAFKA_CFG_SSL_CLIENT_AUTH`. Therefore, there's no current way to enable SSL without enabling `ssl.client.auth=required`.

That said, it's something to be fixed in the Kafka container, so we have a way to disable this option. Could you please open an issue at https://github.com/bitnami/bitnami-docker-kafka/issues describing the same behaviour? Thanks in advance.

**Comment by adityajalkhare** [comment]
Hi @juan131 ,

Thanks for the advice. Yes, I enabled ssl without authentication (by setting `auth.enabled` as `false`)

After facing issue I went through the statefulset.yaml and saw that `listeners` and `advertised.listeners` are automatically configured. 

I also went through [bitnami/bitnami-docker-kafka](https://github.com/bitnami/bitnami-docker-kafka) as suggested and I agree with your point.

I'll be opening an issue at [bitnami/bitnami-docker-kafka](https://github.com/bitnami/bitnami-docker-kafka)
