### ISSUE TITLE
[postgresql-ha] pgpool not updated when new write instance is elected

### ISSUE THREAD

**Issue by wuestkamp** [bitnami/charts#2298]
**Which chart**:
bitnami/postgresql-ha
2.3.1

**Describe the bug**
We start like this:
* `postgres-ha-postgresql-ha-postgresql-0`: write master
* `postgres-ha-postgresql-ha-postgresql-1`: read replica

When the `-0` gets terminated, the `-1` takes correctly over. When `-0` comes back we have this:

* `postgres-ha-postgresql-ha-postgresql-0`: read replica
* `postgres-ha-postgresql-ha-postgresql-1`: write master

But the pool instance `postgres-ha-postgresql-ha-pgpool-569ff99fc8-4rt5n` still points for write actions to the `-0` instance. Hence I cannot perform any writes any longer by pointing to the pool service.

**Expected behavior**
The pool should be updated with the new master?

**Workaround**
Kill the pool pod.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.0", GitCommit:"b29d20baf09943e134c2fa5e1e1cab3bf93315fa", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
@wuestkamp Actually the chart does update itself with the new master, however it takes a few second for the Pool to detect the new changes. In some cases you may even see the pool be automatically recreated due to failing a liveness probe test.

For connecting to the node I executed the command below (shown in the chart README):

```
$ kubectl run wizened-narwhal-postgresql-ha-client1 --rm --tty -i --restart='Never' --namespace default --image bitnami/postgresql:11 --env="PGPASSWORD=$POSTGRES_PASSWORD"  \
        --command -- psql -h wizened-narwhal-postgresql-ha-pgpool -p 5432 -U postgres -d postgres
```

And then followed the steps below:

* Create deployment and wait until it completes. Node -0 is primary and the other -1 is standby.
* Remove node -0. The Pool detects it is removed and sets the primary to node -1.
* Connect via the CLI to the pool. Create a sample database. Works without issues.
* Once node -1 is fully running, remove it. The Pool detects it is removed and sets the primary to node -0.
* Connect via the CLI to the pool. Create a sample database. Works without issues.

Let us know if there's anything we're missing from your configuration.

**Comment by wuestkamp** [comment]
When I tried it I wasn't able to write any longer through the pool and the pool pod was also not restarted, at least not in like 2minutes. But this seems to be isolated on my setup. Feel free to close. Thanks for checking this @marcosbc !

**Comment by marcosbc** [comment]
That's fine, thank you @wuestkamp! If you continue finding this issue with a set of reproducible steps let us know, and we can re-open this ticket for further investigation.
