### ISSUE TITLE
[bitnami/consul] disable_host_node_id should be set to true as default value

### ISSUE THREAD

**Issue by stvnwrgs** [bitnami/charts#2315]
**Which chart**: bitnami/consul:latest

**Describe the bug**
After Consul was restarted, I can see mismatching node id's in the logs and consul won't start.  This is caused due to the missing config parameter  `disable-host-node-id` which is set to false as default with the currently used consul version. (7.x) 

https://www.consul.io/docs/agent/options.html#_disable_host_node_id
```
-disable-host-node-id - Setting this to true will prevent Consul from using information from the host to
generate a deterministic node ID, and will instead generate a random node ID which will be persisted in
the data directory. This is useful when running multiple Consul agents on the same host for testing. This
defaults to false in Consul prior to version 0.8.5 and in 0.8.5 and later defaults to true, so you must opt-in 
for host-based IDs. Host-based IDs are generated using
```

**To Reproduce**
1. Install chart with 3 or more replicas and multiple nodes
2. Delete all pods
3. Wait till pods get rescheduled
4. Check the logs

**Expected behavior**
Pods should restart after deleting all pods 

**Additional context**
Quickfix would be to add the respective ENV variable, but it should be considered to fix it in the docker container as well or upgrade to the latest consul version.

I tried to overwrite it via `localConfig` which resulted in a bug finding and a PR: https://github.com/bitnami/charts/pull/2314

**Comment by miguelaeh** [comment]
Hi @stvnwrgs ,
Thank you very much for reporting this issue.
Would you like to create a PR for the docker image? It can be done at https://github.com/bitnami/bitnami-docker-consul

**Comment by stvnwrgs** [comment]
@miguelaeh PR can be found here: https://github.com/bitnami/bitnami-docker-consul/pull/5 I was not sure how the image versions are built, so I just added the fix, no version increase.

**Comment by miguelaeh** [comment]
Thank you very much @stvnwrgs , we are already taking care of it

**Comment by sjgiri** [comment]
Hi @stvnwrgs,
Thanks for working on this issue. I was wondering if you have any update on the fix. I'm also facing this issue on K8s.

**Comment by miguelaeh** [comment]
Hi @sjgiri ,
I am sorry for the late response, we missed the notification.
The information regarding this issue in on the PR: https://github.com/bitnami/bitnami-docker-consul/pull/5

**Comment by miguelaeh** [comment]
not stale

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
