### ISSUE TITLE
The kibanaEnabled value affect service name value

### ISSUE THREAD

**Issue by dostalradim** [bitnami/charts#23218]
### Name and Version

bitnami/elasticsearch

### What architecture are you using?

None

### What steps will reproduce the bug?

Set the fullnameOverride to elasticsearch chart and then enable kibana with `global.kibanaEnabled`.

### Are you using any custom parameters or values?

```yaml
fullnameOverride: "test-app-elasticsearch"
global:
  kibanaEnabled: true
```

### What is the expected behavior?

The service name will be the same with and without kibana chart.

### What do you see instead?

Changed service name. Which makes the problems with another application.

### Additional information

This happened because of this part in _helpers.tpl

```
{{/*
Name for the Elasticsearch service
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
Required for the Kibana subchart to find Elasticsearch service.
*/}}
{{- define "elasticsearch.service.name" -}}
{{- if .Values.global.kibanaEnabled -}}
    {{- $name := .Values.global.elasticsearch.service.name -}}
    {{- if contains $name .Release.Name -}}
    {{- .Release.Name | trunc 63 | trimSuffix "-" -}}
    {{- else -}}
    {{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
    {{- end -}}
{{- else -}}
    {{- printf "%s" ( include "common.names.fullname" . )  | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

I am not sure why is there a condition based on `global.kibanaEnabled`?

**Comment by migruiz4** [comment]
Hi @dostalradim,

This is not a bug but expected behavior. 

The condition can be reduced to:
```
{{- if Kibana enabled -}}
    {{- .Values.global.elasticsearch.service.name -}} // Global value shared by Elasticsearch and Kibana
{{- else -}}
    {{- ( include "common.names.fullname" . ) -}} // Output of the helper
{{- end -}}
```

Why does the Elasticsearch service use a different name when Kibana is enabled?

Kibana needs an Elasticsearch endpoint to connect to, in this case, it is the chart's 'elasticsearch service'.
Because Kibana is a subchart of Elasticsearch (and not the opposite), there is no way to provide Kibana with a dynamic Elasticsearch service name.

For example, by providing `fullnameOverride` your service will be configured with the output of 'common.names.fullname' using the Elasticsearch chart values. Attempting to provide a function/helper in .Values.kibana will cause it to be rendered using Kibana chart values, meaning the output of `'common.names.fullname'` will be different (Kibana's fullname).

Because of that, we need to use [global values](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/) to provide a common service name, for Elasticsearch to expose and Kibana to connect to.
