### ISSUE TITLE
rabbitmq manager port not be static node port

### ISSUE THREAD

**Issue by susimsek** [bitnami/charts#2337]
chart name: rabbitmq
chart version: 6.25.3

when I set service.type=NodePort,rabbitmq managment nodeport is constantly changing.I want to set a fixed node port to managment port with nodeManagerPort parameter.I think this might be a nice feature

**Comment by marcosbc** [comment]
@susimsek It looks like this is already implemented by the `service.nodePort` parameter. See the [Parameters](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#parameters) section for the list of all available options.

**Comment by pmorelli92** [comment]
Sorry for re opening this, but I am having the same problem.

@marcosbc  the `service.nodePort` is mapping against the 5672 port as you can see here:

https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/svc.yaml#L33

Meanwhile por the management port 15672 the node port will always be null:

https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/svc.yaml#L61

Moreover, we cannot override this with `extraPorts` since it will throw a duplicate port error.

**Comment by marcosbc** [comment]
>Meanwhile por the management port 15672 the node port will always be null:
>
>https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/templates/svc.yaml#L61

Note that it is only null with `service.type=ClusterIP`, which as per this issue should not be the case (since `service.type=NodePort`):

      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}

But since it is not set to null, it will try to allocate a random port (even though it is not configurable), which I understand is the main issue. I probably got confused with the nodePort/managerPort distinction when I posted the original reply.

If we change the above logic to this it should work:

      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.managerPort)) }}
      nodePort: {{ .Values.service.managerPort }}
      {{- end }}

Feel free to contribute via PR if that change works for you!

**Comment by pmorelli92** [comment]
Hi @marcosbc thanks for the quick reply :)

I cannot just change:

    - name: http-stats
      port: {{ .Values.service.managerPort }}
      targetPort: stats
      {{- if eq .Values.service.type "ClusterIP" }}
      nodePort: null

To this:

    - name: http-stats
      port: {{ .Values.service.managerPort }}
      targetPort: stats
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- else if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.managerPort)) }}
      nodePort: {{ .Values.service.managerPort }}
      {{- end }}

Because I will end up saying that the port (for example) 30001 should map to the node port 30001.
I would need to introduce another variable named `service.managerNodePort`.
I can do of course do the PR, if we sync on this :)

**Comment by marcosbc** [comment]
You're right. For now I'm opening an internal task for fixing this, but if you identify a fix feel free to contribute it! If you have any questions let us know.
