### ISSUE TITLE
[bitnami/spark] Deploying Spark Application/jar to Cluster?

### ISSUE THREAD

**Issue by kuro337** [bitnami/charts#23386]
### Name and Version

bitnami/spark

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Hey!

I was following this thread and seemed relevant - https://github.com/bitnami/charts/issues/13771

Following helpful comments and messages from people there I managed to get to this point - where I have a Cluster running and I am able to deploy the examples - and even compile a .jar and stage it on the Pod and run it

So I was doing something like this

```bash
# Create Folder on pod
kubectl exec my-spark-worker-0 -- mkdir -p /opt/spark-apps/

# Stage .jar
kubectl cp MySparkApp-assembly-0.1.jar default/my-spark-worker-0:/opt/spark-apps/MySparkApp-assembly-0.1.jar

# Run Job

 kubectl exec -ti --namespace default my-spark-worker-0 -- spark-submit --master spark://my-spark-master-svc:7077 \
    --class MySparkApp  \
    /opt/spark-apps/MySparkApp-assembly-0.1.jar

```

But I was wondering were there instructions or recommendations - or if this is possible in general with the current Helm chart for Spark:

If I want to deploy a .jar directly to the Cluster - without staging it on the Pod manually - can it be done? Would highly appreciate any pointers!

Ideally I can submit a jar to the cluster and it runs it across n pods or runs it on a pod dynamically - is this possible? I can't seem to find much info

https://spark.apache.org/docs/latest/running-on-kubernetes.html#submitting-applications-to-kubernetes

I was following this documentation but was confused as to how it directly relates to deploying applications as well? 

### What do you see instead?

From all the info I have seen so far it involves manually staging the logic within Pods - but how to launch applications such that the pods are launched appropriately with it?

#### Kick off Custom Jobs

```bash
# 1. Write App and create .jar file

# Create Folder on Worker
kubectl exec my-spark-worker-0 -- mkdir -p /opt/spark-apps/

# Stage .jar
kubectl cp MySparkApp-assembly-0.1.jar default/my-spark-worker-0:/opt/spark-apps/MySparkApp-assembly-0.1.jar

# Run Job - should work

 kubectl exec -ti --namespace default my-spark-worker-0 -- spark-submit --master spark://my-spark-master-svc:7077 \
    --class MySparkApp  \
    /opt/spark-apps/MySparkApp-assembly-0.1.jar

```

From official Docs-

```
Submitting Applications to Kubernetes
Docker Images
Kubernetes requires users to supply images that can be deployed into containers within pods. The images are built to be run in a container runtime environment that Kubernetes supports. Docker is a container runtime environment that is frequently used with Kubernetes. Spark (starting with version 2.3) ships with a Dockerfile that can be used for this purpose, or customized to match an individual application’s needs. It can be found in the kubernetes/dockerfiles/ directory.

Spark also ships with a bin/docker-image-tool.sh script that can be used to build and publish the Docker images to use with the Kubernetes backend.

Example usage is:

$ ./bin/docker-image-tool.sh -r <repo> -t my-tag build
$ ./bin/docker-image-tool.sh -r <repo> -t my-tag push
```

Does this mean - doing this - enables us to actually deploy the pods and we stage the .jar files here?

Thank you for any help!

**Comment by migruiz4** [comment]
Hi @kuro337,

The process you mentioned is described in both the [README.md](https://github.com/bitnami/charts/tree/main/bitnami/spark#submit-an-application) and the [chart notes](https://github.com/bitnami/charts/blob/main/bitnami/spark/templates/NOTES.txt#L56), for example:

```
2. Submit an application to the cluster:

  To submit an application to the cluster the spark-submit script must be used. That script can be
  obtained at https://github.com/apache/spark/tree/master/bin. Also you can use kubectl run.

  export EXAMPLE_JAR=$(kubectl exec -ti --namespace default spark-worker-0 -- find examples/jars/ -name 'spark-example*\.jar' | tr -d '\r')

  kubectl exec -ti --namespace default spark-worker-0 -- spark-submit --master spark://spark-master-svc:7077 \
    --class org.apache.spark.examples.SparkPi \
    $EXAMPLE_JAR 5
```

Now, if I understood correctly, your request would be a feature to automatically allocate that JAR file into all nodes and then run `spark-submit`, right?

I think this is not an issue with the chart, but a question on what you can do with Kubernetes, since the goal would be to 'sync' a file into every pod.

I can think of at least two solutions for this use case:
1. First option would be to implement something similar to the `git.clone` and `git.sync` feature already existing in the Airflow chart. In this case, a combination of init-container + sidecar-container take care of cloning and synchronizing a Git repository into a Volume, which will also be available in the Spark container.
2. Similar to option 1, but a Sidecar using aws-cli, azure-cli, curl, etc. could be used to download and synchronize the content of a remote storage where your JARs are available
3. I would need to test this one, but I think it would be possible to create a Configmap containing you JAR files, then add a `kind: CronJob` manifest to monitor any of the previous sources where your JARs are stored. When a change is detected, (and with the proper ServiceAccount/role configured). That should cause the mounted ConfigMap to be updated in the Spark pod, so the CronJob could also trigger the spark-submit automatically when changes are detected.
 
Not sure if I misunderstood your use case, but I hope this helps answer your question.
