### ISSUE TITLE
[bitnami/redis-cluster] Redis pods going into "Succeeded" state after some time

### ISSUE THREAD

**Issue by mmosierteamvelocity** [bitnami/charts#23405]
### Name and Version

bitnami/redis-cluster

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1.) Deploy Redis cluster helm chart 
2.) Pods will run for some time then go into succeeded state
3.) Delete pods in succeeded state and cluster returns to normal

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Cluster should run without terminating pods

### What do you see instead?

Cluster pods going into succeeded state

### Additional information

So we have been using the Redis cluster helm chart for several years without issue at this point. We are using them in GKE and they seem to run great for the most part. Recently (over the last 6 months or so) we have  been seeing some of the pods in the Redis clusters we run go into a "Succeeded" state. This causes an outage on the affected cluster and their apps. When we delete all of the "Succeeded" pods the cluster goes back to a healthy state. It looks like this lifecycle was added in [Kubernetes 1.27](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase
![succeededpods](https://github.com/bitnami/charts/assets/93136454/2904f7dc-b8a0-4380-becd-30c3ca663bdf)
). It seems like a bug. Any ideas?

**Comment by Mauraza** [comment]
Hi @mmosierteamvelocity,

Did you check if some event shows in the pod that the status was "succeeded"?

**Comment by paulclark222** [comment]
I've been seeing this for some time too. For me it's happening when the pod is evicted due to memory pressure:
`43m         Warning   Evicted                  pod/redis-node-2                                           The node was low on resource: memory. Threshold quantity: 750Mi, available: 764316Ki.`

The logs from the pod:
`
1:M 21 Feb 2024 23:23:23.596 * Connection with replica redis-node-0.redis-headless.live-tdm.svc.cluster.local:6379 lost.
1:X 21 Feb 2024 23:23:23.922 * Sentinel new configuration saved on disk
1:X 21 Feb 2024 23:23:23.922 # +new-epoch 2
1:M 21 Feb 2024 23:23:24.586 * Connection with replica redis-node-1.redis-headless.live-tdm.svc.cluster.local:6379 lost.
1:X 21 Feb 2024 23:23:24.587 # +config-update-from sentinel 2a09ba7abbb41ee71e79087310d75f9809c3c815 redis-node-0.redis-headless.live-tdm.svc.cluster.local 26379 @ mymaster redis-node-2.redis-headless.live-tdm.svc.cluster.local 6379
1:X 21 Feb 2024 23:23:24.587 # +switch-master mymaster redis-node-2.redis-headless.live-tdm.svc.cluster.local 6379 redis-node-0.redis-headless.live-tdm.svc.cluster.local 6379
1:X 21 Feb 2024 23:23:24.589 * +slave slave redis-node-1.redis-headless.live-tdm.svc.cluster.local:6379 redis-node-1.redis-headless.live-tdm.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.live-tdm.svc.cluster.local 6379
1:X 21 Feb 2024 23:23:24.589 * +slave slave redis-node-2.redis-headless.live-tdm.svc.cluster.local:6379 redis-node-2.redis-headless.live-tdm.svc.cluster.local 6379 @ mymaster redis-node-0.redis-headless.live-tdm.svc.cluster.local 6379
1:X 21 Feb 2024 23:23:24.602 * Sentinel new configuration saved on disk
1:signal-handler (1708557805) Received SIGTERM scheduling shutdown...
1:signal-handler (1708557805) Received SIGTERM scheduling shutdown...
1:X 21 Feb 2024 23:23:25.483 * User requested shutdown...
1:X 21 Feb 2024 23:23:25.484 # Sentinel is now ready to exit, bye bye...
1:M 21 Feb 2024 23:23:25.516 * User requested shutdown...
1:M 21 Feb 2024 23:23:25.516 # Redis is now ready to exit, bye bye...
`

The terminated pod remains in Completed state until i delete it. I would expect the pod to be removed and a new one started in it's place.

**Comment by Mauraza** [comment]
Hi @mmosierteamvelocity,

Did you check the space of the cluster? It seems the pod had a problem with the memory... the PVCs show something?

**Comment by mmosierteamvelocity** [comment]
It looks like it's related to a bug in Kubernetes version 1.27.

`Setting a mirror pod's phase to Succeeded or Failed can prevent the corresponding static pod from restarting due mutation of a Kubelet cache. (https://github.com/kubernetes/kubernetes/pull/116482, [@smarterclayton](https://github.com/smarterclayton)) [SIG Node]`

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md

After upgrading to 1.28 we have not seen this issue resurface.

**Comment by Mauraza** [comment]
Hi @mmosierteamvelocity,

I'm glad you solved the issue.

**Comment by michael-blackbit** [comment]
I wanted to add that we just faced this issue with Kubernetes 1.28, too. The pod was in succeeded state until i deleted it manually. Then it came up running normally again. Any hints on how to debug this appreciated.

**Comment by Mauraza** [comment]
Hi @michael-blackbit,

you can add image.debug=true to see if the logs show something more...
