### ISSUE TITLE
[bitnami/redis] Slave persistence

### ISSUE THREAD

**Issue by gopal229** [bitnami/charts#2343]
I have deployed Redis 10.0.0 chart on AKS with slave count 2 and also enabled Sentinel for HA.

I have created a PVC by following steps in https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv and provided the PVC name in the helm values.

After deploying the chart, I see could see 2 Azure managed disks ( for slave-0, and slave -1 ) got created as the persistence is enabled by default for slave. I understand AKS has a default storage class that provisions volumes in Azure disks.

Do we need persistence in slave as well, is there a way to mount the same volume across master and slave's?

**Comment by austince** [comment]
There is a `persistence.existingClaim` option in the [values file here](https://github.com/bitnami/charts/blob/5e14618f1c7eaf0dd7fcc1d75b2c980ec50b6c14/bitnami/redis/values.yaml#L213-L218) to use existing volumes, but it looks like that only applies to the master. You can turn slave persistence off (with the `.slave.persistence.enabled: false`, but it doesn't look like there is a way to use the same volume accross all.

**Comment by gopal229** [comment]
Thanks, @austince, yes I can turnoff slave persistence but wanted to understand the behavior when the failover happens. When a slave is promoted to master, will it have persistence?

**Comment by marcosbc** [comment]
@gopal229 I'm not sure about what you mean. Like mentioned by austinice, the slaves include an option for enabling persistence.

Slaves will include the data of the master node (because of replication), so if failover happens, the slaves should include the same data when turning into a master.

However, note that you should use a **separate** persisted volume for both, even though they may include the same data.

Note that the [bitnami/redis-cluster chart is different](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#choose-between-redis-helm-chart-and-redis-cluster-helm-chart), could it be possible you are referring to that one instead of bitnami/redis?

**Comment by gopal229** [comment]
@marcosbc  Thanks for the reply. I was checking if we can use the same volume across master and slave since only the master is responsible for writes and slaves read data from disk.

We are using https://github.com/bitnami/charts not the redis-cluster.

**Comment by marcosbc** [comment]
Unfortunately that's not an option. The main issue is that slaves may run in a different Kubernetes node. Also, note that their data may differ at certain points in time until replicated.
