### ISSUE TITLE
Version postgresql-ha:13.3.3 on registry-1.docker.io includes charts-data for bitnami/postgresql-ha:13.3.1

### ISSUE THREAD

**Issue by falk-w** [bitnami/charts#23599]
### Name and Version

bitnami/postgresql-ha:13.3.1

### What architecture are you using?

None

### What steps will reproduce the bug?

It seems there is a missmatch in what is currently released to registry-1.docker.io

If I pull the latest chart: 
```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/postgresql-ha --untar
Pulled: registry-1.docker.io/bitnamicharts/postgresql-ha:13.3.3
Digest: sha256:5d3f13b0874d1778dcdbb4d06e9b7ce693843a4c7c955b322305cbdf7428c89d
```

The images defined in this 13.3.3 chart:
```console
$ helm template postgresql-ha | grep image                                
          image: registry-1.docker.io/bitnami/pgpool:4.5.0-debian-11-r20
          imagePullPolicy: "IfNotPresent"
          image: registry-1.docker.io/bitnami/postgresql-repmgr:16.2.0-debian-11-r18
          imagePullPolicy: "IfNotPresent"
```

Match the images defined in the current image versions of 13.3.1 defined here: https://github.com/bitnami/charts/commit/7969261a789b280d6e556d66d09c44fdf8e6d8d4

If I pull 13.3.1 from registry-1.docker.io I get older images:
```console
$ helm pull oci://registry-1.docker.io/bitnamicharts/postgresql-ha --version 13.3.1 --untar
$ helm template postgresql-ha | grep image
          image: registry-1.docker.io/bitnami/pgpool:4.5.0-debian-11-r19
          imagePullPolicy: "IfNotPresent"
          image: registry-1.docker.io/bitnami/postgresql-repmgr:16.2.0-debian-11-r16
          imagePullPolicy: "IfNotPresent"
```

### What is the expected behavior?

I expect to receive the chart as defined here: https://github.com/bitnami/charts/tree/main/bitnami/postgresql-ha
when pulling bitnami/postgresql-ha:13.3.1 from registry-1.docker.io

### What do you see instead?

When I pull `helm pull oci://registry-1.docker.io/bitnamicharts/postgresql-ha --version 13.3.1`I am receiving older code.

**Comment by viceice** [comment]
seems related to
- #23582

**Comment by carrodher** [comment]
Thanks for reporting. Yes, it is an issue in our release process. Helm charts are being built, tested and released as usual but with the wrong version number and a different hostname for the registry (`registry-1.docker.io` instead of `docker.io`).
Charts are totally functional, tested and secure as usual, but there has been some confusion with versions (the number itself) not the Helm chart as a package.

There are some related issues:
* https://github.com/bitnami/charts/issues/23582
* https://github.com/bitnami/charts/issues/23576
* https://github.com/bitnami/charts/issues/23599

We are working on a fix (already in progress) to unify the versions between DockerHub and GitHub.
