### ISSUE TITLE
[bitnami/nginx-ingress-controller] Diverging versions in registry and git

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#23619]
### Name and Version

bitnami/nginx-ingress-controller 10.5.0

### What architecture are you using?

None

### What steps will reproduce the bug?

As for the git history for this chart v10.4.0 and v10.5.0 should be the last two versions published.
however, the latest versions in the registry are 10.4.1 and 10.4.2, both of which SHOULD NOT exist looking at the git history.
10.4.0 and 10.5.0 are also missing entirely, so the CI for those tags is likely broken as well

see https://hub.docker.com/r/bitnamicharts/nginx-ingress-controller/tags and https://github.com/bitnami/charts/commits/main/bitnami/nginx-ingress-controller/Chart.yaml

### What do you see instead?

unpublished versions

**Comment by carrodher** [comment]
Thanks for reporting. Yes, it is an issue in our release process. Helm charts are being built, tested and released as usual but with the wrong version number and a different hostname for the registry (`registry-1.docker.io` instead of `docker.io`).
Charts are totally functional, tested and secure as usual, but there has been some confusion with versions (the number itself) not the Helm chart as a package.

There are some related issues:
* https://github.com/bitnami/charts/issues/23582
* https://github.com/bitnami/charts/issues/23576
* https://github.com/bitnami/charts/issues/23599
* https://github.com/bitnami/charts/issues/23619

We are working on a fix (already in progress) to unify the versions between DockerHub and GitHub.
