### ISSUE TITLE
Documentation to create a new chart based on common template

### ISSUE THREAD

**Issue by thibaut-atempo** [bitnami/charts#23784]
### Name and Version

bintnami/common latest

### What is the problem this feature will solve?

I can't find a documentation on how to use the common template to create my own charts. 

### What is the feature you are proposing to solve the problem?

Explain how to replace correctly all values to use the common template for a custom chart.

Would you recommend not to do that or is it a good idea to use this template as a starting point for a new chart ?

### What alternatives have you considered?

Start from scratch instead of re-using the template.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! Please note this is mainly used internally to facilitate the creation of new Helm charts following the Bitnami guidelines. There is no documentation about its usage because it was designed for internal purposes and the team is familiar with the different placeholders that need to be replaced. 

If you're interested in contributing and adding some instructions, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
