### ISSUE TITLE
"i have no name" user for kafka helm chart 

### ISSUE THREAD

**Issue by hatharom** [bitnami/charts#2428]
**Which chart**:
Kafka

**Describe the bug**
 When logged in to the container the user is :"i have no name"
I just wanted to change to image to pull and got a permission kind of error on entrypoint.sh. 

**To Reproduce**
simple` helm install . `

How to solve this on chart's Values.yaml level? (I can solve this when I create my own image but I dont want to do that)

**Comment by hatharom** [comment]
Was not a chart issue

**Comment by carrodher** [comment]
Hi, you can see that prompt because the Kafka container is a non-root container, you can find more information about non-root containers in the following articles:
- https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html
- https://docs.bitnami.com/tutorials/work-with-non-root-containers/

If you are facing a specific issue related to that in the Kafka chart, please, don't hesitate to let us know
