### ISSUE TITLE
[bitnami/redis] Sentinels get into bad state, require manual recovery if all restart simultaneously

### ISSUE THREAD

**Issue by darintay** [bitnami/charts#24380]
### Name and Version

bitnami/redis 17.15.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

- Install bitnami redis helm chart, with `sentinel: enabled: true`.
- Wait for it to come up, verify Redis is working fine with 3 pods, each with a Redis and a sentinel container
- Exec into all 3 sentinel containers and run `kill 1` at the same time to force sentinel to restart

### Are you using any custom parameters or values?

```yaml
sentinel:
  enabled: true
```

### What is the expected behavior?

The sentinels should reach a consensus on a master, possibly via a failover.

### What do you see instead?

- On startup, each sentinel runs: `redis-cli -h redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster`
- This fails, because none of them are running yet
- The fallback seems to be to declare itself master; now each redis sentinel thinks itself is master
- For 2/3 of them, the underlying Redis container thinks it is a replica, so those eventually enter a `sdown` state

They then just sit there, broken, each pointing at a different master (2/3 of which don't think they are masters) until there is manual intervention (e.g. rolling restart).

### Additional information

The way I saw this occur in production is that my cluster had a temporary network outage, where none of the sentinels could see the other for a brief period. This caused their healthchecks to fail, which caused them to all restart together.

All the sentinels are up and are aware of each other, and aware of all 3 Redis instances, they just never even seem to try to reconcile their masters.

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by gmbnomis** [comment]
I think this problem would not occur if Sentinel persistence is enabled (see `sentinel.persistence.*` values). When starting, the `start-sentinel.sh` script will look for a persisted master configuration first (see https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/scripts-configmap.yaml#L341) and, if found, will use that master when writing a new configuration file.

However, I wonder why  `start-sentinel.sh` even tries to always re-write the configuration at startup. If there is a sentinel config in `/opt/bitnami/redis-sentinel/etc/sentinel.conf`, we can be sure (at least I think so) that we are restarting after a crash/kill (or restarting with a persisted config). Can't we just use that config if it is present?

**Comment by juan131** [comment]
Hi @darintay 

Thanks for bringing up this topic. As you stated, there's a minimum qorum of running replicas that must be guaranteed every moment. Otherwise, there's a chance of reproducing a split brain issue as the one you described.

@gmbnomis regarding your insights about `start-sentinel.sh`, I think you're right. I mean, the `/opt/bitnami/redis-sentinel/etc/sentinel.conf` would exist on two possible scenarios while initializing the container:

1. A container restart.
2. A pod is rescheduled reusing the persistent volume with sentinel data (only if `sentinel.persistence.enabled=true`).

The current logic doesn't take into account the 1st scenario. Would you mind doing some testing & contributing with a PR removing the condition you pointed? Thanks in advance.

**Comment by gmbnomis** [comment]
Hi @juan131 

> @gmbnomis regarding your insights about `start-sentinel.sh`, I think you're right. I mean, the `/opt/bitnami/redis-sentinel/etc/sentinel.conf` would exist on two possible scenarios while initializing the container:
> 
>     1. A container restart.
> 
>     2. A pod is rescheduled reusing the persistent volume with sentinel data (only if `sentinel.persistence.enabled=true`).


Thinking about the second scenario a little more, reusing a persisted config would make the Sentinel "unconfigurable" once there is a config file. (Changes to the Helm values that would go into that file would simply be ignored as we would always reuse the existing file).

Hence, I tend to keep the current logic and just reuse the master config in both scenarios (master info obtained from a running Sentinel instance still takes precedence)

You are completely right in saying that the current logic does not take the first scenario into account. Looking one level deeper (which, I must admit, is scary; I think the Helm chart supports too many deployment options by now), there is this lock for the persisted config option (introduced here https://github.com/bitnami/charts/pull/9282#discussion_r819495268), which does not work in this scenario because we can't assume that `start-node.sh` in the `redis` container runs at the same time.

I am not sure what to make about this one. We could:

1. Just remove the lock (after all the race condition is small and even if a "should be replica node" starts as a master, it should be reconfigured by the Sentinels soon)
2. Remove the lock and prepare the new sentinel config in a different file e.g. `/opt/bitnami/redis-sentinel/etc/prepared-sentinel.conf` and when final, do an atomic move (same filesystem) `mv /opt/bitnami/redis-sentinel/etc/prepared-sentinel.conf /opt/bitnami/redis-sentinel/etc/sentinel.conf`. Thus, the `start-node.sh` script should never see a partial config file.

Hmm, I kind of answered this myself now. I will look into the second option I guess unless a better idea comes up here.

**Comment by juan131** [comment]
Hi @gmbnomis 

Thanks again for your insights!

> Changes to the Helm values that would go into that file would simply be ignored as we would always reuse the existing file

That's a very good point. The configuration must dynamically be adapted if, for example, the number of replicas is scaled.

> Remove the lock and prepare the new sentinel config in a different file e.g. `/opt/bitnami/redis-sentinel/etc/prepared-sentinel.conf` and when final, do an atomic move (same filesystem) mv `/opt/bitnami/redis-sentinel/etc/prepared-sentinel.conf` `/opt/bitnami/redis-sentinel/etc/sentinel.conf`. Thus, the `start-node.sh` script should never see a partial config file.

We'll also need a lock on this use case, right? The difference is that the lock is added by `start-node.sh` once the node has been fully initialized (just before `exec redis-server ...`) and removed by `start-sentinel.sh` once the new `prepared-sentinel.conf` is completed and the atomic move is done, right?

**Comment by gmbnomis** [comment]
I think we can't make any safe assumption about when `start-node.sh` and `start-sentinel.sh`  will run. Of course, they will be started at the same time in almost all cases (pod startup). But if a container crashes/is killed, only the respective script will run.

To me it looks like the lock mechanism was introduced because - in the persisted sentinel config case - `start-node.sh`  reads the master information from `/opt/bitnami/redis-sentinel/etc/sentinel.conf` while `start-sentinel.sh` might be modifying that same file. Therefore, the lock file tells `start-sentinel.sh` to wait until `start-node.sh` has obtained the master info from it (@javsalgar, is this correct?). 

Now, if we modify the update mechanism of `/opt/bitnami/redis-sentinel/etc/sentinel.conf` in such a way that `start-node.sh` will always find a master info, there should be no need for a lock.

**Comment by juan131** [comment]
@javsalgar @migruiz4 as authors of this lock: what's your opinion about this?

**Comment by javsalgar** [comment]
> Therefore, the lock file tells start-sentinel.sh to wait until start-node.sh has obtained the master info from it (@javsalgar, is this correct?).

Yes, that was the reasoning of adding the lock.

**Comment by juan131** [comment]
Hi @gmbnomis 

Thanks for creating the PR! We really appreciate it, let's continue our conversation there.
