### ISSUE TITLE
[bitnami/spark] with reverse proxy and ssl

### ISSUE THREAD

**Issue by yankees5963** [bitnami/charts#24472]
### Name and Version

[bitnami/spark 8.9.1

### What architecture are you using?

amd64

### What steps will reproduce the bug?

Deploy to k8s with private ca enabled jks keys and tls 

Master/Worker config:
```
-Dspark.ui.reverseProxy=true -Dspark.ui.reverseProxyUrl=https://{URL}
service.type=LoadBalancer
security.ssl.enabled=true
```
Ingress is NOT enabled. LoadBalancer handles AWS to 443

### What is the expected behavior?

Main UI works, but when clicking into worker /proxy/ I get a 500 Missing SslContextFactory

### What do you see instead?

```html
<html>
<body>
<!--StartFragment--><h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 java.lang.NullPointerException: Missing SslContextFactory</h2>
URI: | /proxy/worker-20240315111534-10.114.3.11-33205
-- | --
500
java.lang.NullPointerException: Missing SslContextFactory
org.apache.spark.ui.JettyUtils$$anon$3-7de597ba
java.lang.NullPointerException: Missing SslContextFactory

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">java.lang.NullPointerException: Missing SslContextFactory</pre><!--EndFragment-->
</body>
</html>
```

### Additional information

Related ticket was closed without a solution: https://github.com/bitnami/charts/issues/21062

**Comment by migruiz4** [comment]
Hi @yankees5963,

I'm sorry but I'm not sure if there is much we can do to help you with this issue as it is possible the issue is not related to the chart itself but the upstream application. I found this issue in Spark that could be related: https://issues.apache.org/jira/projects/SPARK/issues/SPARK-47133

I would like to help you, but the information provided is not enough to help troubleshoot your issue.
- What intermediate elements are you using in your Client -> Server connection?
- Is the URL directly assigned to the EKS service by adding some notation?
- Have you tried using an ingress controller? Does the same issue happen when using the ingress controller?
