### ISSUE TITLE
[bitnami/postgresql] Password not being set properly in Postgres

### ISSUE THREAD

**Issue by arches-richard** [bitnami/charts#24720]
### Name and Version

bitnami/postgresql 15.1.4

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Set `auth.database`, `auth.username`, `auth.password` and set `auth.usePasswordFiles` first to true, then to false
2. Install the chart 
3. Attach to the pod
4. Run `cat $PGPASSFILE` if `auth.usePasswordFiles` is true, or `echo $PGPASSWORD` otherwise

### Are you using any custom parameters or values?

```yaml
auth:
  database: 'postgres'
  username: 'postgres'
  usePasswordFiles: # Tried both true and false
  password: 'abc'
```

### What is the expected behavior?

When `auth.usePasswordFiles` is true, it should create a [`.pgpass`](https://www.postgresql.org/docs/current/libpq-pgpass.html) file somewhere with 0600 permissions and set the `PGPASSFILE` environment variable to point to it. 

When `auth.usePasswordFiles` is false, it should set the [`PGPASSWORD`](https://www.postgresql.org/docs/current/libpq-envars.html#:~:text=PGPASSWORD) environment variable to the `auth.password`.

### What do you see instead?

When `auth.usePasswordFiles` is true, it creates an environment variable `POSTGRES_PASSWORD_FILE` that points to a file containing only the password (not in `.pgpass` format) that has 0777 permissions.

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/primary/statefulset.yaml#L216-L218

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/primary/statefulset.yaml#L233-L235

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/read/statefulset.yaml#L214-L216

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/read/statefulset.yaml#L231-L233

When `auth.usePasswordFiles` is false, it creates an environment variable `POSTGRES_PASSWORD` containing the password. 

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/primary/statefulset.yaml#L220-L224

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/primary/statefulset.yaml#L237-L241

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/read/statefulset.yaml#L218-L222

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/read/statefulset.yaml#L235-L239

### Additional information

It seems like the backup is setting the correct environment variables even though primary/read are not. It is still not creating the password file with the right format or giving it the right permissions. 

https://github.com/bitnami/charts/blob/ddbc3e61f38176d15f7e093fd7ef17fd60b9877d/bitnami/postgresql/templates/backup/cronjob.yaml#L59-L68

**Comment by javsalgar** [comment]
Hi,

The use of `_FILE` files is a standard in our Bitnami containers, which have [a logic that translates](https://github.com/bitnami/containers/blob/main/bitnami/postgresql/15/debian-12/rootfs/opt/bitnami/scripts/postgresql-env.sh#L165) all possible variables to a `_FILE` equivalent (this can be seen in other [non-bitnami containers](https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L9) as well), so it was not expected to use the `.pgpass` format. In the end it's a way to use the env vars in files in order to improve security. About the 777 format that's something we could check by changing the permissions of the mounted file.

About `PGPASSWORD`, this variable is meant to be used by the container bash logic. In order to separate the pure postgresql variables from the Bitnami container variables, we used the `POSTGRES_PASSWORD` variable. This also happens in other PostgreSQL container variants.
