### ISSUE TITLE
Redis slave pod restarts when redis master pod fails

### ISSUE THREAD

**Issue by abhishekGupta2205** [bitnami/charts#24758]
### Name and Version

bitnami/redis , latest

### What architecture are you using?

amd64

### What steps will reproduce the bug?

`helm install redis-master redis`

### What is the expected behavior?

Let's suppose in some case, I have promoted my slave pod (`redis-master-replicas-0`) to master and made master pod (`redis-master-master-0`) as the slave of `redis-master-replicas-0` using slave of command. Now I expect that if my master pod (`redis-master-master-0`)  goes down, nothing should be impacted as my slave pod which is currently master running.

### What do you see instead?

As soon as the pod with the name (`redis-master-master-0`) restarts, the replica pod which is currently master goes down.

### Additional information

Steps to reproduce-
1) `kubectl exec -it redis-master-replicas-0 -- /bin/bash`   -> `redis-cli -p 6379`   -> slave of no one
2) `kubectl exec -it redis-master-master-0 -- /bin/bash`   -> `redis-cli -p 6379`   -> slave of redis-master-replicas 6379
3) `kubectl delete pod redis-master-master-0`

**Comment by abhishekGupta2205** [comment]
@fevisera , can you provide any solution to this

**Comment by jotamartos** [comment]
Sorry for the delay in getting back to you. 

That's the expected behavior, if you want the cluster to continue running when the master is down, you will need to enable Redis Sentinel. You can read more about this here

https://github.com/bitnami/charts/tree/main/bitnami/redis#master-replicas-with-sentinel

**Comment by abhishekGupta2205** [comment]
@jotamartos , i am discusing the case where i have switched master . I have made redis-replicas-0 pod as my new master and redis-master-0 as slave . Now when i restart my redis-master-0 pod ,  redis-replicas-0  pod also restarts , which should not happen

**Comment by abhishekGupta2205** [comment]
In my case master pod is down ,not actual redis master

**Comment by abhishekGupta2205** [comment]
@jotamartos , you are not understanding my point .    i am discusing the case **where i have switched master** . I have made **redis-replicas-0 pod** as **my new master** and **redis-master-0** pod  as new  slave . Now when i restart my redis-master-0 pod , redis-replicas-0 pod also restarts , which should not happen.

you are giving me solution when i run default helm chart having master and slave , and if master restarts then slave also restarts , which i agree with you should happen. but my case is differnt .

**Comment by jotamartos** [comment]
Hi @abhishekGupta2205,

Yes, I understood your message and reproduced the issue locally. I switched master and restarted the pod later and confirmed that the slaves (one of them now master) is restarted. That's caused by the probe I mentioned above. 

If you do not want this to happen, you can enable the sentinel pod or disable the probe as I mentioned too. 

Thanks
