### ISSUE TITLE
[bitnami/kafka] Initial checksum/passwords-secret is incorrect

### ISSUE THREAD

**Issue by Cybermaxke** [bitnami/charts#24870]
### Name and Version

bitnami/kafka 28.0.0

### What architecture are you using?

None

### What steps will reproduce the bug?

1. Install kafka with auto generated passwords
2. Helm upgrade with the same values (helm upgrade kafka kafka.tgz --reuse-values)
3. The controller gets restarted, even though nothing changed

### What is the expected behavior?

The controller should not restart when no values have changed between an initial install and an upgrade

### What do you see instead?

The problem is that during the templating the passwords/kraft-cluster-id are generated and for the initial install this is done twice, causing different values in the actual secrets.yaml and the checksum/passwords-secret of the stateful set. For upgrades, the passwords are looked up from the secret on the cluster, which will update the checksum correctly for the first upgrade which causes the restart that is happening. Any more upgrades don't cause any restarts.

Ref: https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/controller-eligible/statefulset.yaml#L42

**Comment by migruiz4** [comment]
Hi @Cybermaxke,

Thank you for reporting this issue.

I was able to reproduce it, and as mentioned, the checksum generated during the first installation is changed during the second:
```diff
        annotations:
          checksum/configuration: dc20b600bb2ed1afcff48b69c4383e8d628313ec1b9ab110290dc0fcb56911de
-         checksum/passwords-secret: f38edac533845a82f68318ea7916aca3117d0c893028932a4f15fb349c9519e1
+         checksum/passwords-secret: d96a1b8b60bcd931d1d72dc3fcb4dc7a35266b940f008d0a9356fdf52529bf9d
```

As mentioned, when leaving passwords and cluster-id to autoconfigure, the chart will generate them when rendering the secret.
This will happen twice: In the statefulset.yaml, in [the lines you mentioned](https://github.com/bitnami/charts/blob/main/bitnami/kafka/templates/controller-eligible/statefulset.yaml#L42) and when generating the actual secrets.yaml manifest.

This causes the checksum during the first install to not match the actual value until the first upgrade is executed.

During upgrades the issue will not happen again, because now the render will use the helm `lookup` function instead of generating a new password, therefore both renders will generate the same output.

I'm sorry but I do not think it is possible to fix this issue, unless we remove the checksum from the statefulset therefore not restarting in other cases where it would be decided.

Because of that, and considering that recreating the statefulset on the first chart upgrade may not be considered a severe issue, we might have to close this as "won't fix".

**Comment by Cybermaxke** [comment]
It is possible to store values during the templating like this (will not work across parent/subcharts):
```
{{- define "getOrCreatePassword" -}}
{{- if not .Values.myPassword -}}
{{- $_ := set .Values "myPassword" (randAscii 10) -}}
{{- end -}}
{{ .Values.myPassword }}
{{- end }}
```
You can use this in multiple files and it will output the same password.

**Comment by jcox10** [comment]
I also ran into this issue. Seems like there is an easy solution that was provided by @Cybermaxke. The original "will not fix" decision was based on it being not possible. Can this be reconsidered?

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.
