### ISSUE TITLE
bitnami/postgresql pushed with wrong version

### ISSUE THREAD

**Issue by nevivurn** [bitnami/charts#24928]
### Name and Version

bitnami/postgresql 15.2.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. `helm pull oci://registry-1.docker.io/bitnamicharts/postgresql --version 15.2.3`
2. See `Error: registry-1.docker.io/bitnamicharts/postgresql:15.2.3: not found`
3. `helm pull oci://registry-1.docker.io/bitnamicharts/postgresql --version 16.2.0` does succeed, inspecting the pulled chart shows it as version `15.2.3`.

### What is the expected behavior?

#24924 should have been released as `15.2.3`.

### What do you see instead?

#24924 was released as `16.2.0`, which is the appVersion.

**Comment by carrodher** [comment]
Thanks for letting us know, we made a change in our internal tooling to publish Helm charts in the DockerHub OCI registry and there was a misconfiguration that has caused some Helm charts published using the app version (16.2.0 in this case) instead of the chart version (15.2.3 in this case).

A fix for this issue is already in the oven. Sorry for the inconvenience.

**Comment by carrodher** [comment]
We just created [this issue](https://github.com/bitnami/charts/issues/24943) to condense any other conversation regarding this topic. Feel free to post there if needed.

New versions are already in the oven and they should be released during the following hours (if they have not already been released).
