### ISSUE TITLE
[bitnami/postgresql] automatic restart when got error.

### ISSUE THREAD

**Issue by OrwillT** [bitnami/charts#2500]
My postgresql pod got this error sometime:

`
2020-05-04 09:18:43.075 GMT [211] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Input/output error
`

This happend because the storageclass I used sometimes failed. After failure happend my storageclass will automatic remount PVC but still need postgresql pod to restart.

So is there a way to automatic restart psql pod after this error happend?

**Comment by dani8art** [comment]
Hi @OrwillT, it depends on the status of the pods if I've understood well the pod doesn't get into an error, right? since this is a `WARNING` for psql and the container doesn't fail, isn't it? 

> This happend because the storageclass I used sometimes failed. After failure happend my storageclass will automatic remount PVC but still need postgresql pod to restart.

Could you elaborate this a bit more, please? I don't see how a pod could start with a PVC mount failing.

**Comment by OrwillT** [comment]
Is not a pod start with a PVC mount dailing, is a pod suddenly got a PVC mount failing when it's running.

The storageclass I'm using is [Longhorn](https://longhorn.io/docs), I'm not sure but I think with this storageclass, the PVC resource status displayed in K8S may not match its actual status. Longhorn could expand PVC without change PVC resource in cluster and might radom fail. Before version 0.8.0 of longhorn, everytime this happend comes with a volume detached in longhorn backend but PVC resource still show ready.

**Comment by dani8art** [comment]
Sorry, but I didn't understand well, is this an error caused by an error in your PVC storageclass, right? I don't know how we can handle this. What would you need when this error happen? maybe a pods restart? I mean, If this error came you would need to restart the pod? or how it would be solved?

**Comment by OrwillT** [comment]
I need to restart my pod. This is the only way to fix this problem.-------- 原始邮件 --------发件人： Daniel Arteaga <notifications@github.com>日期： 2020年5月11日周一 半夜11:21收件人： bitnami/charts <charts@noreply.github.com>抄送： "Orwill Q. Song" <orwill@anislet.dev>, Mention <mention@noreply.github.com>主    题： Re: [bitnami/charts] [bitnami/postgresql] automatic restart when got error. (#2500)
Sorry, but I didn't understand well, is this an error caused by an error in your PVC storageclass, right? I don't know how we can handle this. What would you need when this error happen? maybe a pods restart? I mean, If this error came you would need to restart the pod? or how it would be solved?

**Comment by dani8art** [comment]
I'm thinking about a solution that could be to improve the liveness probe, with that, the deployment will check the liveness of a pod taking in to account this specific warning. However, we should understand a bit more the error at postgresql level so that we could implement a better liveness probe. Do you know if there is any way to detect this error? Maybe through a `psql` query?

**Comment by OrwillT** [comment]
I will give it a try but I don't know how to reproduction this issue so I need time. I currently believe you just can't connect to that psql server when this happend.

**Comment by dani8art** [comment]
I think that it couldn't be detected only with a `psql` connection since the current liveness probe is a `psql` connection. If this was the case, it would restart the pods, and you are saying that it is not happening, so we need to find another way of detecting it.

**Comment by sjoodin** [comment]
Hi we are experiencing similar issues, getting this error at the postgresql pod: "FATAL: could not open relation mapping file "global/pg_filenode.map"

As you see from the error log from our django server, there is a response sent about this error over the psql connection:
![bild](https://user-images.githubusercontent.com/47199287/117812198-cb75d100-b261-11eb-9b8f-3268c2ff0420.png)

We do not know exactly what caused the error, but the severity increased because the pod kept running even when getting this fatal error. A restart of the pod got everything running again.

Thus, it would be really nice if the postgresql pod would automatically restart when it gets fatal errors like these.

**Comment by rafariossaa** [comment]
Hi @sjoodin ,
  Do you mind opening a new issue for this ? This way we can ask for more information and track it properly.
  At first sight I think you are right, it seems to be PVC related.
