### ISSUE TITLE
Drupal: Redeploying chart change password but not all components are aware about this fact.

### ISSUE THREAD

**Issue by hetii** [bitnami/charts#2526]
**Which chart**:
The ndrupal-6.2.20	8.8.5 

**Describe the bug**
Redeploying chart change database password but only on secrets and not in DB engine,
so at the end of the day you lost access to drupal site.

**To Reproduce**
1. Redeploy again the chart

**Expected behavior**
Redeploying chart if change password then all components should be aware about this changes.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```
-   mariadb-password: '-------- # (10 bytes)'
-   mariadb-root-password: '-------- # (10 bytes)'
+   mariadb-password: '++++++++ # (10 bytes)'
+   mariadb-root-password: '++++++++ # (10 bytes)'

**Comment by juan131** [comment]
Hi @hetii 

When you don't provide any value for `mariadb.rootUser.password` and `mariadb.db.password` installing or upgrading the chart, those values are randomly generated in the secret.

It's very important to indicate these values both when installing and upgrading the charts, so they're not auto-generated. The problem comes when a value is generated the 1st time the chart is installed, an a different one is generated when upgrading it. When this happen, the persisted data uses a different password and, therefore, you face connectivity issues.

You can find more information in the links below:

- https://github.com/bitnami/charts/blob/master/bitnami/drupal/values.yaml#L99
- https://github.com/bitnami/charts/tree/master/bitnami/mariadb#upgrading
