### ISSUE TITLE
Helm repo add bitnami https://charts.bitnami.com/bitnami is failing with 

### ISSUE THREAD

**Issue by vikram-yerneni** [bitnami/charts#25364]
### Name and Version

charts.bitnami.com/bitnami

### What architecture are you using?

None

### What steps will reproduce the bug?

https://github.com/bitnami/charts/issues/8433

### Are you using any custom parameters or values?
```
find . -name 'Chart.yaml' && find . -name 'values.yaml
```
### What is the expected behavior?

It should download the charts and package them via Helm

### What do you see instead?

```
time="2024-04-24T13:37:55Z" level=error msg="`sh -c \"helm repo add argo [https://argoproj.github.io/argo-helm\\nhelm](https://argoproj.github.io/argo-helm//nhelm) repo add bitnami [https://charts.bitnami.com/bitnami\\nhelm](https://charts.bitnami.com/bitnami//nhelm) dependency build\\n\"` failed exit status 1: Error: looks like \"[https://charts.bitnami.com/bitnami\"](https://charts.bitnami.com/bitnami/%22) is not a valid chart repository or cannot be reached: Get \"[https://charts.bitnami.com/bitnami/index.yaml\":](https://charts.bitnami.com/bitnami/index.yaml/%22:) x509: certificate signed by unknown authority\nError: cannot load values.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}" execID=4b3fd

time="2024-04-24T13:37:55Z" level=error msg="finished streaming call with code Unknown" error="error generating manifests: `sh -c \"helm repo add argo [https://argoproj.github.io/argo-helm\\nhelm](https://argoproj.github.io/argo-helm//nhelm) repo add bitnami [https://charts.bitnami.com/bitnami\\nhelm](https://charts.bitnami.com/bitnami//nhelm) dependency build\\n\"` failed exit status 1: Error: looks like \"[https://charts.bitnami.com/bitnami\"](https://charts.bitnami.com/bitnami/%22) is not a valid chart repository or cannot be reached: Get \"[https://charts.bitnami.com/bitnami/index.yaml\":](https://charts.bitnami.com/bitnami/index.yaml/%22:) x509: certificate signed by unknown authority\nError: cannot load values.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type map[string]interface {}" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=plugin.ConfigManagementPluginService grpc.start_time="2024-04-24T13:37:55Z" grpc.time_ms=159.792 span.kind=server system=grpc
```
### Additional information

It seems the issue with https://github.com/bitnami/charts/issues/8433 is keep on repeating. How can we bypass it?

**Comment by carrodher** [comment]
It seems the same issue reported at https://github.com/bitnami/charts/issues/18133 instead of https://github.com/bitnami/charts/issues/8433.

It seems related to an issue in Helm itself, see https://github.com/helm/helm/pull/9318

Currently, the default method to fetch Bitnami charts is using the [Bitnami DockerHub OCI repository](https://hub.docker.com/u/bitnamicharts), and given that OCI is supported out of the box in [Helm 3.8.0](https://github.com/helm/helm/releases/tag/v3.8.0), could you try using OCI?

[Here](https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html) you can find more information about this topic
