### ISSUE TITLE
Release notes, changelog on a chart by chart basis

### ISSUE THREAD

**Issue by ktzsolt** [bitnami/charts#25668]
### Name and Version

bitnami/*

### What is the problem this feature will solve?

Because of the monorepo style we can not review changes in specific helm charts easily, also there is no changelog and no release notes.

### What is the feature you are proposing to solve the problem?

basically use githubs "releases" https://github.com/bitnami/charts/releases feature and separate helm charts into repositories if needed.

### What alternatives have you considered?

using git log locally

**Comment by carrodher** [comment]
Thank you for the suggestion! This is something that was already requested by other users at https://github.com/bitnami/charts/issues/18903 and we are working on it in this PR (https://github.com/bitnami/charts/pull/25359), hopefully, this new functionality will be implemented sooner rather than later.

I'm closing this issue as duplicated to funnel all the conversation into the existing issue.
