### ISSUE TITLE
RabbitMQ  helm upgrade forces pod recycle

### ISSUE THREAD

**Issue by michelefa1988** [bitnami/charts#2612]
**Which chart**:
rabbitmq-6.25.5

**Describe the bug**
When running helm upgrade on the RabbitMQ chart, the pod is being deleting and being created again.

**To Reproduce**
Install Chart ```helm upgrade --install --set persistentVolume.enabled=false test-rabbitmq ./rabbitmq/```

**Expected behavior**
No changes were made to the chart, therefore I do not expect the pod to die and re-create but remains running

**Version of Helm and Kubernetes**: 1.15.7

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"169db3bff4b5fb7722e967c5b6356713f05f15ed", GitTreeState:"clean", BuildDate:"2020-04-03T16:14:09Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by marcosbc** [comment]
Hi @michelefa1988, unfortunately I could not reproduce this on our environment. In any case, it would be very helpful if you checked the logs for the failing pods, in case there's something we could detect there.

Also, could you describe if you're also upgrading the chart version, and if you're using an environment other than a vanilla Kubernetes/minikube?

**Comment by marcosbc** [comment]
Oh, I see, you're specifying this parameter:

```
persistentVolume.enabled
```

But the chart supports this:

```
persistence.enabled
```

Since the persistence is getting created, it will have already been initialized with the secrets. But when you re-deploy, those secrets are re-created and they are wrong. To avoid that happening, you should either disable persistence, or specify existingPasswordSecret, existingErlangSecret (or their raw value) via --set.

**Comment by michelefa1988** [comment]
@marcosbc 

I have pulled the latest Bitnami repository and updated to the latest chart. I have also updated the helm install command as per your previous message to ```helm upgrade --install  test-rabbitmq ./rabbitmq/```

However the pod still keep restarting every time I run the above command

I am assuming that it is because of the cookie, however this since is a dev environment I would prefer to have ```persistence.enabled: false```

When I redeploy I would also prefer if the pod doesn't get restarted.

I am triggering this helm chart with Azure pipelines (azure devops) and it is running on AKS.

**Comment by marcosbc** [comment]
@michelefa1988 Note that since your deployment was already installed with a PVC, and you want to configure it without persistence, you must delete the previous one:

```
helm del test-rabbitmq
kubectl get pvc | grep rabbitmq
kubectl delete pvc RABBITMQ_PVC_NAME # change this to the appropriate value
```

> However the pod still keep restarting every time I run the above command

That is because when you run "helm upgrade", it replaces the secrets, meaning it changes the credentials of the deployment. And since you have enabled persistence it will use the passwords from a previous deployment, which doesn't match the ones in the current one, so after some time the health check fails because of wrong credentials.

The correct way to do it is to disable persistence, if that's something you can live with, or instead specify the secret names when upgrading (--set existingPasswordSecret=... --set existingErlangSecret=...).

>When I redeploy I would also prefer if the pod doesn't get restarted.

Note that it is how Kubernetes works, when it needs to update a resource from a StatefulSet, it only knows how to delete+create it. Unfortunately there's not much that can be done about that.

**Comment by michelefa1988** [comment]
@marcosbc  I have been testing various combinations of this. The command I have been running is

`` helm upgrade --install  test -f values.yaml  ./rabbitmq/ --set existingPasswordSecret=test-rabbitmq --set existingErlangSecret=test-rabbitmq
and
``` helm upgrade --install  test -f values.yaml  ./rabbitmq/ --set rabbitmq.existingPasswordSecret=test-rabbitmq --set rabbitmq.existingErlangSecret=test-rabbitmq

However the pod still keeps restarting. Please note persistance is disabled in my values file as per your message above. 

The only part I have not tried yet is creating a secret manually but I would prefer if the secret is generated as part of the helm chart (and never recycled)

**Comment by marcosbc** [comment]
>The only part I have not tried yet is creating a secret manually but I would prefer if the secret is generated as part of the helm chart (and never recycled)

In that case you must not specify `rabbitmq.existingErlangSecret`. For instance, the below command worked without issues for me:

```
helm upgrade --install myrabbitmq --set persistence.enabled=false bitnami/rabbitmq
```

Afterwards, my RabbitMQ deployment runs without any issues:

```
mbrabbitmq-0                      1/1     Running     0          5m14s
```

Could you try the command above and let us know if it works? It could be possible there is a misconfiguration in your `values.yaml` file.
