### ISSUE TITLE
Getting started instructions don't work

### ISSUE THREAD

**Issue by glensc** [bitnami/charts#2618]
The [readme] says:

[readme]: https://github.com/bitnami/charts/blob/c7751eb5764e468e1854b58a1b8491d2b13e0a4a/README.md#tldr

> `helm repo add bitnami https://charts.bitnami.com/bitnami`
> `helm search repo bitnami`

but that gives no results. first I thought the instructions lack "update" command, but that still did not change anything.

```
➔ helm version --client --short
Client: v2.16.0+ge13bc94

➔ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories

➔ helm search repo bitnami
No results found
➔ helm search repo apache
No results found

➔ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete.

➔ helm search repo apache
No results found
➔ helm search repo bitnami
No results found
➔
```

**Comment by glensc** [comment]
perhaps the word repo is superfluous? did it work earlier? what helm version?

```

➔ helm search apache
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/apache      	7.3.15       	2.4.43     	Chart for Apache HTTP Server
bitnami/airflow     	6.2.2        	1.10.10    	Apache Airflow is a platform to programmatically author, ...
bitnami/cassandra   	5.4.1        	3.11.6     	Apache Cassandra is a free and open-source distributed da...
bitnami/kafka       	10.3.3       	2.5.0      	Apache Kafka is a distributed streaming platform.
bitnami/tomcat      	6.3.6        	9.0.34     	Chart for Apache Tomcat
stable/hadoop       	1.1.2        	2.9.0      	The Apache Hadoop software library is a framework that al...
stable/ignite       	1.0.1        	2.7.6      	Apache Ignite is an open-source distributed database, cac...
stable/jenkins      	1.13.0       	lts        	Open source continuous integration server. It supports mu...
stable/kafka-manager	2.3.1        	1.3.3.22   	A tool for managing Apache Kafka.
stable/spark        	0.1.2        	           	A Apache Spark Helm chart for Kubernetes. Apache Spark is...
stable/superset     	1.1.10       	0.35.2     	Apache Superset (incubating) is a modern, enterprise-read...
bitnami/spark       	1.2.21       	2.4.5      	Spark is a fast and general-purpose cluster computing sys...

➔ helm search bitnami
NAME                            	CHART VERSION	APP VERSION            	DESCRIPTION
bitnami/bitnami-common          	0.0.8        	0.0.8                  	Chart with custom templates used in Bitnami charts.
bitnami/airflow                 	6.2.2        	1.10.10                	Apache Airflow is a platform to programmatically author, ...
bitnami/apache                  	7.3.15       	2.4.43
...
```

**Comment by joancafom** [comment]
Hi @glensc !

It seems that you are using Helm legacy v2. The [command](https://helm.sh/docs/helm/helm_search_repo/) `helm search repo` was introduced in v3, but as you pointed out the way of doing it back in v2 was `helm search` + _keyword_. 

Reference: https://v2.helm.sh/docs/helm/#helm-search

Hope it helps, thanks!

**Comment by glensc** [comment]
So the documentation should be updated that the commands are for helm 3! 

or indicate for which helm version the command is for, like in stable/redis:
- https://github.com/helm/charts/tree/master/stable/redis#redis

but current readme says 2.12+ is needed:
- https://github.com/bitnami/charts/tree/6dbafa0007b48ce2fb85dee24560ec3fa895a5a4/bitnami/redis#prerequisites

**Comment by utkinpol** [comment]
Please explain how and why default project behaves like this:
[rancher@rancher ~]$ helm install postgres1234 bitnami/postgresql
[rancher@rancher ~]$ kubectl get pods -w
NAME                        READY   STATUS        RESTARTS   AGE
postgres1234-postgresql-0   0/1     Terminating   6          6m37s
postgres1234-postgresql-0   0/1     Terminating   6          6m39s
postgres1234-postgresql-0   0/1     Terminating   6          6m39s
postgres1234-postgresql-0   0/1     Pending       0          0s
postgres1234-postgresql-0   0/1     Pending       0          0s
postgres1234-postgresql-0   0/1     ContainerCreating   0          0s
postgres1234-postgresql-0   0/1     ContainerCreating   0          1s
postgres1234-postgresql-0   0/1     Running             0          2s
postgres1234-postgresql-0   0/1     Error               0          3s
postgres1234-postgresql-0   0/1     Error               1          4s
postgres1234-postgresql-0   0/1     CrashLoopBackOff    1          5s
postgres1234-postgresql-0   0/1     Running             2          18s
postgres1234-postgresql-0   0/1     Error               2          19s
postgres1234-postgresql-0   0/1     CrashLoopBackOff    2          24s
...

I tired initially to run it from rancher and it was crashing due to error setting user access for /bitnami/postgresql/data - and it seems the default chart in the default vanilla way crashes exactly same? What am I missing there? I tried to do exactly what the default instructions say, with no alterations.

**Comment by joancafom** [comment]
Hi @glensc ,

Thanks for your feedback on the README instructions, we will consider implementing it in our repo. It is true that requirements state a version greater than Helm 2.12 to work. However, working with a certain version does not imply that it is the mainstream one. Helm v2 is a _legacy_ version now and there are [plans](https://helm.sh/blog/2019-10-22-helm-2150-released/#helm-2-support-plan) to drop support for it by the end of this year.  Hence, the current recommended version to use is 3 and the README reflects that mindset.

Thanks for your feedback!

**Comment by joancafom** [comment]
Hi @utkinpol ,

Could you provide me with the output of some useful commands that will help me bound the issue? I have tried to replicate your issue, but the default projects works as expected for me:

```console
$ helm install postgres1234 bitnami/postgresql
$ kubectl get pods -w                                                                                                                                                                              
NAME                        READY   STATUS              RESTARTS   AGE
postgres1234-postgresql-0   0/1     ContainerCreating   0          8s
postgres1234-postgresql-0   0/1     Running             0          63s
postgres1234-postgresql-0   1/1     Running             0          72s
```

Commands that may help further describing the issue:

```console
$ kubectl describe pod postgres1234-postgresql-0                                                                                                                                                                           
...
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/postgres1234-postgresql-0 to minikube
  Normal  Pulling    3m35s      kubelet, minikube  Pulling image "docker.io/bitnami/postgresql:11.8.0-debian-10-r5"
  Normal  Pulled     2m34s      kubelet, minikube  Successfully pulled image "docker.io/bitnami/postgresql:11.8.0-debian-10-r5"
  Normal  Created    2m34s      kubelet, minikube  Created container postgres1234-postgresql
  Normal  Started    2m34s      kubelet, minikube  Started container postgres1234-postgresql
```

```console
$ kubectl logs postgres1234-postgresql-0  -f                                                                                                                                                         
postgresql 07:47:40.45
postgresql 07:47:40.46 Welcome to the Bitnami postgresql container
postgresql 07:47:40.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 07:47:40.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 07:47:40.46
postgresql 07:47:40.47 INFO  ==> ** Starting PostgreSQL setup **
postgresql 07:47:40.50 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 07:47:40.51 INFO  ==> Loading custom pre-init scripts...
postgresql 07:47:40.52 INFO  ==> Initializing PostgreSQL database...
postgresql 07:47:40.53 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 07:47:40.54 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 07:47:40.54 INFO  ==> Generating local authentication configuration
postgresql 07:47:40.54 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 07:47:40.55 INFO  ==> Configuring replication parameters
postgresql 07:47:40.56 INFO  ==> Configuring fsync
postgresql 07:47:40.56 INFO  ==> Loading custom scripts...
postgresql 07:47:40.57 INFO  ==> Enabling remote connections
postgresql 07:47:40.57 INFO  ==> Stopping PostgreSQL...

postgresql 07:47:40.58 INFO  ==> ** PostgreSQL setup finished! **
postgresql 07:47:40.61 INFO  ==> ** Starting PostgreSQL **
2020-05-21 07:47:40.648 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-05-21 07:47:40.648 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2020-05-21 07:47:40.649 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-05-21 07:47:40.654 GMT [170] LOG:  database system was shut down at 2020-05-21 07:45:49 GMT
2020-05-21 07:47:40.657 GMT [1] LOG:  database system is ready to accept connections
```

Thanks!

**Comment by glensc** [comment]
@joancafom the current readme doesn't state what version the commands are for, and hence this issue.

**Comment by joancafom** [comment]
I understand your point @glensc . Our Charts require a minimum v2 of Helm, but documentation is written targeting Helm v3, with is the official mainstream release. Nevertheless, we value your feedback and we will consider it!

Thanks!

**Comment by utkinpol** [comment]
> Hi @utkinpol ,
> 
> Could you provide me with the output of some useful commands that will help me bound the issue? I have tried to replicate your issue, but the default projects works as expected for me:
> 
> ```
> $ helm install postgres1234 bitnami/postgresql
> $ kubectl get pods -w                                                                                                                                                                              
> NAME                        READY   STATUS              RESTARTS   AGE
> postgres1234-postgresql-0   0/1     ContainerCreating   0          8s
> postgres1234-postgresql-0   0/1     Running             0          63s
> postgres1234-postgresql-0   1/1     Running             0          72s
> ```
> 
> Commands that may help further describing the issue:
> 
> ```
> $ kubectl describe pod postgres1234-postgresql-0                                                                                                                                                                           
> ...
> Events:
>   Type    Reason     Age        From               Message
>   ----    ------     ----       ----               -------
>   Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/postgres1234-postgresql-0 to minikube
>   Normal  Pulling    3m35s      kubelet, minikube  Pulling image "docker.io/bitnami/postgresql:11.8.0-debian-10-r5"
>   Normal  Pulled     2m34s      kubelet, minikube  Successfully pulled image "docker.io/bitnami/postgresql:11.8.0-debian-10-r5"
>   Normal  Created    2m34s      kubelet, minikube  Created container postgres1234-postgresql
>   Normal  Started    2m34s      kubelet, minikube  Started container postgres1234-postgresql
> ```
> 
> ```
> $ kubectl logs postgres1234-postgresql-0  -f                                                                                                                                                         
> postgresql 07:47:40.45
> postgresql 07:47:40.46 Welcome to the Bitnami postgresql container
> postgresql 07:47:40.46 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
> postgresql 07:47:40.46 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
> postgresql 07:47:40.46
> postgresql 07:47:40.47 INFO  ==> ** Starting PostgreSQL setup **
> postgresql 07:47:40.50 INFO  ==> Validating settings in POSTGRESQL_* env vars..
> postgresql 07:47:40.51 INFO  ==> Loading custom pre-init scripts...
> postgresql 07:47:40.52 INFO  ==> Initializing PostgreSQL database...
> postgresql 07:47:40.53 INFO  ==> postgresql.conf file not detected. Generating it...
> postgresql 07:47:40.54 INFO  ==> pg_hba.conf file not detected. Generating it...
> postgresql 07:47:40.54 INFO  ==> Generating local authentication configuration
> postgresql 07:47:40.54 INFO  ==> Deploying PostgreSQL with persisted data...
> postgresql 07:47:40.55 INFO  ==> Configuring replication parameters
> postgresql 07:47:40.56 INFO  ==> Configuring fsync
> postgresql 07:47:40.56 INFO  ==> Loading custom scripts...
> postgresql 07:47:40.57 INFO  ==> Enabling remote connections
> postgresql 07:47:40.57 INFO  ==> Stopping PostgreSQL...
> 
> postgresql 07:47:40.58 INFO  ==> ** PostgreSQL setup finished! **
> postgresql 07:47:40.61 INFO  ==> ** Starting PostgreSQL **
> 2020-05-21 07:47:40.648 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 2020-05-21 07:47:40.648 GMT [1] LOG:  listening on IPv6 address "::", port 5432
> 2020-05-21 07:47:40.649 GMT [1] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
> 2020-05-21 07:47:40.654 GMT [170] LOG:  database system was shut down at 2020-05-21 07:45:49 GMT
> 2020-05-21 07:47:40.657 GMT [1] LOG:  database system is ready to accept connections
> ```
> 
> Thanks!

i suspect the issue was indeed crazy frustrating and underlying cause was the way how persistent volumes were mounted on the Linux host. t eh postgres container was totally refusing to work UNTIL it was given a persistent volume mounted as a simple directory on the linux host itself. 
i did not have much time to deal with it further yet. not sure what it means from the practical implications side of things as nobody EVER would use local internal unix directories as persistent volumes, i need to test it further next week to discover what gives. 

that log below gives similar picture of what was happening - it was not visible at the pod level, it is the container log. i has to go all the way into there to find this. then googled the '“pg_wal/000000010000000000000001”: Operation not permitted" and that brought up an another complaint about posgres failing on Azure persistent volume drivers. i had a different mount - a mounted in external drive under /mnt slice - but it was enough to brake it all. very frustrating stuff, 3 days wasted as it was totally unclear what component to blame. 


2020-05-22T02:55:54.581Z WARN cmd/keeper.go:182 password file permissions are too open. This file should only be readable to the user executing stolon! Continuing… {“file”: “/etc/secrets/stolon/pg_repl_password”, “mode”: “01000000777”}
2020-05-22T02:55:54.581Z WARN cmd/keeper.go:182 password file permissions are too open. This file should only be readable to the user executing stolon! Continuing… {“file”: “/etc/secrets/stolon/pg_su_password”, “mode”: “01000000777”}
2020-05-22T02:55:54.582Z INFO cmd/keeper.go:2039 exclusive lock on data dir taken
2020-05-22T02:55:54.590Z INFO cmd/keeper.go:525 keeper uid {“uid”: “keeper1”}
2020-05-22T02:55:54.609Z INFO cmd/keeper.go:1033 our keeper data is not available, waiting for it to appear
2020-05-22T02:55:59.612Z INFO cmd/keeper.go:1033 our keeper data is not available, waiting for it to appear
2020-05-22T02:56:04.615Z INFO cmd/keeper.go:1033 our keeper data is not available, waiting for it to appear
2020-05-22T02:56:09.620Z INFO cmd/keeper.go:1033 our keeper data is not available, waiting for it to appear
2020-05-22T02:56:14.624Z INFO cmd/keeper.go:1033 our keeper data is not available, waiting for it to appear
2020-05-22T02:56:19.629Z INFO cmd/keeper.go:1094 current db UID different than cluster data db UID {“db”: “”, “cdDB”: “9ba49f5e”}
2020-05-22T02:56:19.629Z INFO cmd/keeper.go:1101 initializing the database cluster
The files belonging to this database system will be owned by user “stolon”.
This user must also own the server process.
The database cluster will be initialized with locale “en_US.utf8”.
The default database encoding has accordingly been set to “UTF8”.
The default text search configuration will be set to “english”.
Data page checksums are disabled.
creating directory /stolon-data/postgres … ok
creating subdirectories … ok
selecting default max_connections … 100
selecting default shared_buffers … 128MB
selecting default timezone … Etc/UTC
selecting dynamic shared memory implementation … posix
creating configuration files … ok
2020-05-22 02:56:20.078 UTC [48] LOG: could not link file “pg_wal/xlogtemp.48” to “pg_wal/000000010000000000000001”: Operation not permitted
2020-05-22 02:56:20.079 UTC [48] FATAL: could not open file “pg_wal/000000010000000000000001”: No such file or directory
child process exited with exit code 1
initdb: removing data directory “/stolon-data/postgres”
2020-05-22T02:56:20.105Z ERROR cmd/keeper.go:1135 failed to initialize postgres database cluster {“error”: “error: exit status 1”}
2020-05-22T02:56:25.109Z ERROR cmd/keeper.go:1063 db failed to initialize or resync
2020-05-22T02:56:25.117Z INFO cmd/keeper.go:1094 current db UID different than cluster data db UID {“db”: “”, “cdDB”: “9ba49f5e”}
2020-05-22T02:56:25.117Z INFO cmd/keeper.go:1101 initializing the database cluster
running bootstrap script … The files belonging to this database system will be owned by user “stolon”.
This user must also own the server process.
The database cluster will be initialized with locale “en_US.utf8”.
The default database encoding has accordingly been set to “UTF8”.
The default text search configuration will be set to “english”.
Data page checksums are disabled.
creating directory /stolon-data/postgres … ok
creating subdirectories … ok
selecting default max_connections … 100
selecting default shared_buffers … 128MB
selecting default timezone … Etc/UTC
selecting dynamic shared memory implementation … posix
creating configuration files … ok
2020-05-22 02:56:25.645 UTC [61] LOG: could not link file “pg_wal/xlogtemp.61” to “pg_wal/000000010000000000000001”: Operation not permitted
2020-05-22 02:56:25.647 UTC [61] FATAL: could not open file “pg_wal/000000010000000000000001”: No such file or directory
child process exited with exit code 1
initdb: removing data directory “/stolon-data/postgres”
2020-05-22T02:56:25.676Z ERROR cmd/keeper.go:1135 failed to initialize postgres database cluster {“error”: “error: exit status 1”}
2020-05-22T02:56:30.681Z ERROR cmd/keeper.go:1063 db failed to initialize or resync
2020-05-22T02:56:30.686Z INFO cmd/keeper.go:1094 current db UID different than cluster data db UID {“db”: “”, “cdDB”: “9ba49f5e”}
2020-05-22T02:56:30.686Z INFO cmd/keeper.go:1101 initializing the database cluster
running bootstrap script … The files belonging to this database system will be owned by user “stolon”.
This user must also own the server process.
The database cluster will be initialized with locale “en_US.utf8”.
The default database encoding has accordingly been set to “UTF8”.
The default text search configuration will be set to “english”.
Data page checksums are disabled.
creating directory /stolon-data/postgres … ok
creating subdirectories … ok
selecting default max_connections … 100
selecting default shared_buffers … 128MB
selecting default timezone … Etc/UTC
selecting dynamic shared memory implementation … posix
creating configuration files … ok

**Comment by joancafom** [comment]
It seems to me like the persistent volume that you were trying to mount lacks some permissions. Hence, containers were not able to initialise properly and some files are missing:

```
...
LOG: could not link file “pg_wal/xlogtemp.61” to “pg_wal/000000010000000000000001”: 
Operation not permitted
...
```
In fact, it working with the simple directory (as you pointed out) increases the probability of this hypothesis (it is likely that you have the right permissions on a regular home directory for your user). 

Could you provide me with some more context? I suppose you are running your application on a physical host machine rather than a cloud cluster.

Thanks!
