### ISSUE TITLE
[bitnami/mysql] mysql Server upgrade from 'X' to 'X' takes 5 minutes

### ISSUE THREAD

**Issue by vholer** [bitnami/charts#26559]
### Name and Version

docker.io/bitnami/mysql:8.0.37-debian-12-r2

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. Installing the mysql helm chart.
2. Stop debug in helm chart
3. Importing about 3 GB of data into the database
4. Kill mysql pod in kubernetes
5. look into the log of the restarted mysql pod
6. The following entry appears in the log "Server upgrade from '80037' to '80037' started"
7. after 5 minutes the following entry appears in the log "Server upgrade from '80037' to '80037' completed"
8. after 5 minutes the database is available again

This behavior occurs every time the Pod is restarted.

### What is the expected behavior?

The expectation would be that a restart of the mysql pod does not trigger a mysql_upgrade if it is not necessary. Since in this case nothing has changed and it is obvious from the log that nothing has changed, I would expect that the application that needs the data is not down for 5 minutes.

### What do you see instead?

Applications that do not work for 5 minutes and wait for the database. Since Kubernetes often restarts a pod, this behavior is dangerous for the stability of the application.

**Comment by vholer** [comment]
Copy of #15550 which was closed due to inactivity.

**Comment by fmulero** [comment]
Hi @vholer, thanks a lot for using Bitnami containers.

I've been checking previous issues and I am not sure right now if this is a leftover or it was intentional (I've just opened an internal discussion):
https://github.com/bitnami/containers/blob/303b68309891bc0326e1973b428aea7db6493b3e/bitnami/mysql/8.0/debian-12/rootfs/opt/bitnami/scripts/libmysql.sh#L821-L833

Please feel free to open PR with the fix, The Bitnami team will be happy to review it and and continue the discussion there. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.

**Comment by fmulero** [comment]
PR https://github.com/bitnami/containers/pull/68565 should fix this issue
