### ISSUE TITLE
[bitnami/external-dns] Why bitnami chart allows to modify number of replicas for external dns when external dns does not support multiple replicas

### ISSUE THREAD

**Issue by mzeeshan1** [bitnami/charts#26682]
### Name and Version

bitnami/external-dns

### What architecture are you using?

None

### What steps will reproduce the bug?

Bitnami external chart allows to configure number of replicas for external dns when external dns does not support multiple replicas
ref: https://github.com/kubernetes-sigs/external-dns/issues/2430
This impacts multiple things in chart
- Daemonset should not be there
- Pod Disruption Budget should not be enabled by default.
- Deployment strategy. It should be Recreate by default if I am not missing anything.

### What do you see instead?

The chart allows to modify number of replicas for external DNS it also allows to deploy external DNS as a daemonset

**Comment by migruiz4** [comment]
Thank you for reporting this issue @mzeeshan1.

After some further investigation, looks like indeed external-dns does not officially support having multiple replicas, and doing so could lead to problems.

Because of that, I have submitted #26759, a new major release dropping support for Daemonset and multi-replica deployments. If in a future release external-dns adds support for multiple replicas, we will restore these features.
