### ISSUE TITLE
[bitnami/clickhouse] Clickhouse PVC expansion

### ISSUE THREAD

**Issue by IgorBatyukov** [bitnami/charts#27059]
### Name and Version

bitnami/clickhouse4.0.10

### What is the problem this feature will solve?

We use the standard configurations of Clickhouse with 2 shards and the Zookeeper. Tried to change persistence.size value with fluxcd with no effect. The StatefullSet yaml displaying desired storage size, however all PVCs remained unchanged. The StorageClass allows volume expansion. 

### What is the feature you are proposing to solve the problem?

Is there any workaround to resize the PVC of Clickhouse statefulsets without loosing the data?

**Comment by javsalgar** [comment]
Hi,

It seems to me that this issue is not related with the Bitnami packaging of Clickhouse but with the cluster configuration and the storage class management settings. Did you check with the storage class provider for help on this? I will leave the ticket open in case someone from the community wants to share their experiencie.

**Comment by IgorBatyukov** [comment]
Hi, @javsalgar 

Thanks for your response. That's right, the issue isn't related to the Bitnami packaging. My bad, sorry for opening the wrong issue thread. Turned out that the PVCs need to be edited manually as well as HelmRelease values in order changes to be applied. No data loss occurred, btw.
