### ISSUE TITLE
[bitnami/wordpress] problem with persistent volume

### ISSUE THREAD

**Issue by chrouzz** [bitnami/charts#2720]
**Which chart**:
bitnami/wordpress       9.3.6           5.4.1

**Describe the bug**
I just install wordpress using helm and the error arrived direcly.
I describe the pvc and below you can see the error. They say there is no persistent volume available.
```
Name:          mywp-wordpress
Namespace:     default
StorageClass:
Status:        Pending
Volume:
Labels:        app.kubernetes.io/instance=mywp
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=wordpress
               helm.sh/chart=wordpress-9.3.6
Annotations:   meta.helm.sh/release-name: mywp
               meta.helm.sh/release-namespace: default
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    mywp-wordpress-6c86d75674-lmgvd
Events:
  Type    Reason         Age                From                         Message
  ----    ------         ----               ----                         -------
  Normal  FailedBinding  9s (x8 over 104s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```

**Expected behavior**
Expected to have wordpress up and running.
**Version of Helm and Kubernetes**:
client Version: v1.18.3
Server Version: v1.18.3

- Output of `helm version`:

```
v3.2.1+gfe51cd1
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by juan131** [comment]
Hi @chrouzz 

Do you have any Persistent Volume Provisioner in your K8s cluster? Please note that you need one in order to dynamically create Persistent Volumes that you can attach to your pods. You can find more information in the link below:

- https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

The error could also be related with your Persistent Volume Provisioner expecting a specific Storage Class to be used on the PVCs. If that's the case, then you'll have to set the `persistence.storageClass` parameter with the name of that Storage Class. More info in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/wordpress#wordpress-parameters
