### ISSUE TITLE
RabbitMQ missing metadata.name and metadata.namespace

### ISSUE THREAD

**Issue by oxr463** [bitnami/charts#2769]
**Which chart**:

Catalog: rabbitmq
Template Version: 6.8.3

**Describe the bug**

I am receiving the following error:

```sh
/opt/bitnami/rabbitmq/sbin/rabbitmq-server: 1: eval: MY_POD_NAME: not found
/opt/bitnami/rabbitmq/sbin/rabbitmq-server: 1: eval: MY_POD_NAMESPACE: not found
```

Despite these being defined as seen below:

field | status.podIP | All | MY_POD_IP
-- | -- | -- | --
field | metadata.name | All | MY_POD_NAME
field | metadata.namespace | All | MY_POD_NAMESPACE
secret | rabbitmq | {{cookie}} | RABBITMQ_ERL_COOKIE
secret | rabbitmq | {{password}} | RABBITMQ_PASSWORD

**To Reproduce**

This occurs sporadically–I have not been able to figure out the exact cause.

**Expected behavior**

The pod should be able to find those values.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
v2.14.3-rancher1
```

- Output of `kubectl version`:

```Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

This is an Azure Kubernetes Cluster with Rancher running as the front-end:

Rancher | v2.3.6
-- | --
User Interface | v2.3.40
Helm | v2.14.3-rancher1
Machine | v0.15.0-rancher34

**Comment by carrodher** [comment]
Hi, in order to try to reproduce the issue, are you using the default parameters, or did you modify the `values.yaml` or use other parameters via `--set`? I would like to be able to deploy the chart with the same conditions, although it seems a specific issue in Rancher (see https://github.com/rancher/rancher/issues/18312).

Are you able to execute `env` in the container to check if those environments variables appear? If you have access to a CLI you can execute `kubectl exec -it POD_NAME env`, where `POD_NAME` can be found by running `kubectl get pods`.

**Comment by oxr463** [comment]
When it is up, yes. But this issue causes the container to crash so I am not able to exec since it is dead at that point. Thanks for that Rancher issue link. That might be the problem.

**Comment by carrodher** [comment]
Yes, you're right if the container is not running you can't check the environment variables. I am not sure if the issue is solved in more recent versions of Rancher or it's related to the Helm version used by Rancher. I tried in Rancher `v2.14.3-rancher1` and the issue didn't appear, but as you rightly said (and the descriptions in the Rancher issue), the error appears sporadically so my deployments were some lucky deployments.

**Comment by Edenee** [comment]
Hi, I have the same problem @oxr463. Did you find a solution?

**Comment by oxr463** [comment]
> 
> 
> Hi, I have the same problem @oxr463. Did you find a solution?

No, but as a workaround we have instructed the developers to not try to scale the workload down to 0 using the slider anymore. Otherwise, I have to delete the app and redeploy.

**Comment by mccj** [comment]
I use rancher v2.5.8 and I have the same problem

**Comment by carrodher** [comment]
It seems an issue with Rancher itself and not related to the Bitnami container image, I hope you can find a solution in the Rancher ticket.

**Comment by cctvccav** [comment]
I have the same problem
