### ISSUE TITLE
[chart/wordpress]Guidelines for required storage

### ISSUE THREAD

**Issue by ppintogbm** [bitnami/charts#2780]
**Which chart**:
wordpress-9.2.4

**Is your feature request related to a problem? Please describe.**
I'm trying to install the chart on IBM Cloud Kubernetes Service (IKS), and get it running, but get a poor performance (super slow site). IBM provides some ways to provision different kinds of storage (file, block, cloud object), and some of them have constraints like the IOPS. Tried to deploy it using a combination of:
- File for wordpress (500 IOPS) and Block for MariaDB (200 IOPS)
- Cloud Object for Wordpress and Block for MariaDB (200 IOPS)

On both deploys i get a slow site. Without persistent storage, the site works as expected.

**Describe the solution you'd like**
Maybe some kind of guidelines for kind of storage required for the chart deployment. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by marcosbc** [comment]
Hi @ppintogbm, we do offer support for Storage Classes, and there is a section in the README for production-compatible configuration: https://github.com/bitnami/charts/tree/master/bitnami/wordpress#production-configuration

If you want to read more on Storage Classes, check the [official Kubernetes documentation page](https://kubernetes.io/docs/concepts/storage/storage-classes/).

**Comment by marcosbc** [comment]
We have a related GitHub Issue for the WordPress container image, with the intention of improving the performance of initialization for slow volumes: https://github.com/bitnami/bitnami-docker-wordpress/issues/164

However, that was already fixed in version 9.3.1 of the chart. Could you look into updating to that version or newer ones and see if it works better now?
