### ISSUE TITLE
{feature request} [bitnami/gatekeeper-operator] Onboard Open Policy Agent gatekeeper-operator.

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#2795]
**Which chart**:
[bitnami/gatekeeper-operator]
[bitnami/gatekeeper]

**Describe the solution you'd like**
I want to onboard the gatekeeper operator.

**Additional context**
As the gatekeeper project stated, that complex helm charts are currently not in the scope of the project [https://github.com/open-policy-agent/gatekeeper/pull/505](https://github.com/open-policy-agent/gatekeeper/pull/505).
I created some prework in my own repository. [https://github.com/Cellebyte/helm/tree/release/charts/gatekeeper-operator](https://github.com/Cellebyte/helm/tree/release/charts/gatekeeper-operator)
But integrating it here would be much nicer.
Is their capacity/will to onboard this chart?
If so I can create a PullRequest to track the development of that chart.

**Comment by Cellebyte** [comment]
I currently lack time but will create a PR. It would be great if someone can help me to make the helm chart bitnami compliant.

**Comment by dani8art** [comment]
Great, we will be happy to handle it, hopefully working on this soon! thank you so much!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
