### ISSUE TITLE
Keycloak 25

### ISSUE THREAD

**Issue by Evodam** [bitnami/charts#27965]
### Name and Version

bitnami/keycloak

### What is the problem this feature will solve?

Keycloak 25 contains some bugfixes and enhancements.

### What is the feature you are proposing to solve the problem?

Keycloak 25 was released June 10 2024. https://www.keycloak.org/2024/06/keycloak-2500-released

When is a helm chart for this version planned?

**Comment by carrodher** [comment]
Thank you for bringing this to our attention. Our automated test and release pipeline detected the new version; however, we have identified some issues during the packaging process that require manual intervention.

Our team is actively addressing these issues at the moment. We are committed to resolving them as quickly as possible.

We will close this issue since there is an already existing ticket for this topic, see https://github.com/bitnami/containers/issues/67751
