### ISSUE TITLE
Solving security issues

### ISSUE THREAD

**Issue by Chardonneaur** [bitnami/charts#28172]
### Name and Version

bitnami/matomo

### What is the problem this feature will solve?

Hi there,
could you please update the image of Matomo you have in order to fix all vulnerabilities issues. https://artifacthub.io/packages/helm/bitnami/matomo?modal=security-report

### What is the feature you are proposing to solve the problem?

fixing the issues

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. We regularly update our images with the latest system packages; however, certain CVEs may persist until they are patched in the OS or application. Additionally, some CVEs remain unfixed due to the absence of available patches. In vulnerability scanners like Trivy, you can use the `--ignore-unfixed` flag to ignore such CVEs. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.

**Comment by Chardonneaur** [comment]
@carrodher thank you, what would be the best way here to get those vulnerabilities fixed? I am working for the Matomo team, so I could help, but I have no idea who developped the Matomo image here or neither how to contact her/him https://artifacthub.io/packages/helm/bitnami/matomo?modal=security-report
Can you please help?

**Comment by carrodher** [comment]
We track upstream projects and release new versions of our images when there is a new upstream version. In the same way, if our system detect a fixable CVE in the underlying base image (Debian 12), the container and Helm chart are rebuilt so there is a new version updating the system packages, for instance https://github.com/bitnami/charts/pull/28215
