### ISSUE TITLE
[bitnami/scylladb] Autoscaling problem and questions

### ISSUE THREAD

**Issue by mariusz-gomse-centra** [bitnami/charts#28200]
### Name and Version

bitnami/scylladb 1.0.6

### What architecture are you using?

amd64

### What steps will reproduce the bug?

When using https://artifacthub.io/packages/helm/bitnami/scylladb and do:

```
helm --set dbUser.user=admin,dbUser.password=password,persistence.enabled=false install my-release oci://registry-1.docker.io/bitnamicharts/scylladb
```
and then
```
 k scale statefulset my-release-scylladb --replicas 2
```

It is not working - error in `/opt/bitnami/scylladb/log` is saying about not existing internal service for 2nd replica (it is about `service.internal.enabled` configuration (I'll need to scale through helm upgrade - then new service will be created).

The above error made me think of a few things:
1. In the documentation `service.internal.enabled` there is written _"Create a service per pod (this improves the cluster stability when scaling or performing upgrades)"_ - could you elaborate what does it mean? I'm curious how much non-stable it will be if I'll do `service.internal.enabled=false`
2. With the default configuration - how HPA is working (it is in documentation as an option)? It won't add new services so it seems for me that there is also a bug (I mean `service.internal.enabled=true` and `autoscaling.hpa.enabled=true` will proceed to defined by me problem

Thank you in advance for answers and infos

### Are you using any custom parameters or values?

dbUser.user=admin,dbUser.password=password,persistence.enabled=false

### What is the expected behavior?

sts should scale up

### What do you see instead?

2nd pod IS NOT in ready state (problem with non existing service)

### Additional information

I'm fully aware that by default scaling should be done with helm upgrade however please check my questions :)

**Comment by javsalgar** [comment]
Hi,

When not enabling the internal service it will use the headless service. In this scenario, the hostname will be associated to a ephemeral IP. When performing upgrades (that is, tearing down the pod and creating a new one), it will still have registered the IP of the previous node. The initialization will take a while before discarding the ephemeral IP and accepting the new one. That's the reason of having a service per pod, because the IP will be the same always. 

It's true that, when using the HPA, the new service will not be created. In that scenario, maybe we can allow creating more internal services to a maximum of N expected instances. Not the most optimal solution, but it could work. Another option would be disabling the internal service and have this slow initialization because of the ephemeral IPs.

**Comment by mariusz-gomse-centra** [comment]
ℹ️ I checked and about 2) now I'm supre that with the newest version JMX can (and should IMHO) be disabled (`jmxProxy.enabled=false`). The reason for this is that in 6.0 nodetool is a native Scylladb tool and JMX server is by default removed in 6.0 (see https://forum.scylladb.com/t/release-scylladb-6-0/2143).

So I'm quite sure that I can go with `jmxProxy.enabled=false` right? :)

**Comment by javsalgar** [comment]
Hi!

If that's the case, you could give it a go to see if that works without issues. If so, maybe we can consider disabling it in future releases.
