### ISSUE TITLE
[harbor] Error upgrading to chart version 6.0.0

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#2821]
**Which chart**:
harbor, version 6.0.0

**Describe the bug**
When attempting to upgrade my harbor install to this version, I get the following error:

> execution error at (harbor/templates/registry/registry-dpl.yaml:35:33): A secret key is required!

**To Reproduce**
1. Attempt to upgrade from chart version 5.4.0 to 6.0.0

**Expected behavior**
The upgrade to be successful.

**Version of Helm and Kubernetes**:
helm 3.2.0, kubernetes 1.17.5

**Additional context**
I'm pretty sure that there is something that needs to be added to my values.yaml for this version, but I'm not sure what it is.

**Comment by carrodher** [comment]
Hi, in this major version we introduced some changes that can break backwards compatibility, can you take a look at the upgrade section in the README? https://github.com/bitnami/charts/tree/master/bitnami/harbor#600

It's possible the issue with the key is due to `secretKey` has been moved to `core.secretKey`.

**Comment by ajchiarello** [comment]
That was it, thanks!
