### ISSUE TITLE
[bitnami/mongodb] MongoDB primary pod restart fails to connect to mongodb-secondary

### ISSUE THREAD

**Issue by ganchandrasekaran** [bitnami/charts#2848]
**Which chart**:
The name (and version) of the affected chart
chart: bitnami/mongodb 
version: 7.14.6

**Describe the bug**
Once MongoDB cluster is deployed with replicaSet enabled and persistence disabled. 
persistence. enabled: false
replicaSet. enabled: true

**To Reproduce**
1. Deploy MongoDB chart
```
# kubectl get po
mongodb-arbiter-0                                                 1/1     Running   0          40s
mongodb-primary-0                                                 1/1     Running   0          40s
mongodb-secondary-0                                               1/1     Running   0          30s
```
2. Restart Primary node:
```
# kubectl rollout restart statefulset mongodb-primary
```
3. Check logs of primary to see error, note there is no error show on the status of the pod. 
```
# kubectl logs mongodb-primary-0
2020-06-16T13:24:31.670+0000 I  CONNPOOL [Replication] Connecting to mongodb-arbiter-0.mongodb-headless.default.svc.cluster.local:27017
2020-06-16T13:24:31.732+0000 I  REPL_HB  [replexec-1] Heartbeat to mongodb-arbiter-0.mongodb-headless.default.svc.cluster.local:27017 failed after 2 retries, response status: InvalidReplicaSetConfig: replica set IDs do not match, ours: 5ee8c801d5cdd538b8153c1c; remote node's: 5ee8c7b17f3ff3a4aec1d0d7
```

**Expected behavior**
Primary should bind with the existing the replication cluster

**Additional context**
Based on similar bug reports before such as: https://github.com/bitnami/bitnami-docker-mongodb/issues/110
1, This was fixed for Pod using PV.  Is it possible to make changes to make it work with emptyDir{} as well. Perhaps some way to sync the replica set IDs with existing secondary. 
2, What would be the exact role of Secondary and arbiter?can Secondary take the role of Primary as I understand primary is always rescheduled by K8S. Does this mean, Write operation has some downtime when primary pod is down?

**Comment by carrodher** [comment]
Hi, thanks for the detailed explanation.

I was able to see the same behavior, it seems that disabling persistence via `--set persistence.enabled=false` the rollout restart of any node (not only the primary) produce an error adding the node to the cluster because it is not able to find a matching ID. Maybe this issue can be solved by setting a fixed ID in the node without relying on the volume, but it's something we need to investigate (PRs are welcome).

Regarding the role of secondaries and arbiters, according to the official docs https://docs.mongodb.com/manual/core/replica-set-architecture-three-members/ it seems the secondary can be elected as the primary while the arbiter is only used to vote in the elections.

**Comment by ganchandrasekaran** [comment]
Hello, Thank you for response. 

=>
Regarding the role of secondaries and arbiters, according to the official docs https://docs.mongodb.com/manual/core/replica-set-architecture-three-members/ it seems the secondary can be elected as the primary while the arbiter is only used to vote in the elections.

In general, yes that is the behavior. However, from this chart it looks like the Primary is constructed as seperate StatefulSet and has its own Service. So when the Primary pod is deleted, the R/W query will have a downtime until a new pod is recreated by StatefulSet. So in this case the secondaries are not elected as Primary.

**Comment by carrodher** [comment]
Hi, I was reviewing our internal backlog and there is a task to improve the behavior in this kind of use case. At this moment there is a teammate working on that, so probably in the next days/week, there is a new release of MongoDB chart fixing this issue by using a new approach.

I just added a link to this issue in the task just to be taken into account. Thanks again for letting us know. I am setting the `on-hold` label to prevent our stale bot from closing this issue while we're working on it.

**Comment by ganchandrasekaran** [comment]
@carrodher Can you share more information on such new approach? Perhaps add link to the PR page! 
I found similar limitation with MariaDB, so reported in its spaces: https://github.com/bitnami/charts/issues/2896
Thanks

**Comment by carrodher** [comment]
Hi, the work is still in progress, when the PR was created we can link the PR with this issue

**Comment by juan131** [comment]
Hi everyone,

A new major version of MongoDB (**8.0.0**) was released including refactoring the way to expose MongoDB nodes outside the K8s cluster, so there's one service per node. It also groups every secondary and primary node under the same statefulset. Please feel free to give it a try since it should address this issue.

More info at https://github.com/bitnami/charts/tree/master/bitnami/mongodb#to-800
