### ISSUE TITLE
[bitnami/apisix] Request Help: Is there a way to use cert-manager certificates in apisix standalone mode deployment?

### ISSUE THREAD

**Issue by vivekhegadems** [bitnami/charts#28652]
### Name and Version

bitnami/apisix 3.3.9

### What architecture are you using?

amd64

### What steps will reproduce the bug?

I have deployed apisix in standalone mode by configuring values.yaml as mentioned in https://github.com/bitnami/charts/tree/main/bitnami/apisix .
All things look fine. There is no issue with the deployment

As I understand in standalone mode deployment of apisix, all routes/ssl certificates will be configured via configmap that will be mounted as local file to apisix container and also the "config_provider: yaml" is set to yaml.
Reference Links:
https://github.com/bitnami/charts/tree/main/bitnami/apisix
https://apisix.apache.org/docs/apisix/deployment-modes/#standalone

I am checking if there is any way to use certificates created from cert-manager in apisix standalone mode deployment.
Need inputs on the same.

### Are you using any custom parameters or values?

Not using any custom parameters/values

### What is the expected behavior?

Need inputs on anyway to use the certificates created from cert-manager in apisix standalone mode deployment.

### What do you see instead?

I tried the way as mentioned in https://apisix.apache.org/docs/ingress-controller/tutorials/manage-certificates-with-cert-manager/, and reference the secret that includes certificates in dataPlane -> tls section of values.yaml. But this doesn't work. Maybe because of the standalone mode deployment of apisix which uses only reference from yaml.

### Additional information

Problem with apisix standalone mode is the certificates will need to be statically configured in the yaml as mentioned in https://apisix.apache.org/docs/apisix/deployment-modes/#how-to-enable-ssl.

**Comment by javsalgar** [comment]
Hi!

In other charts we are adding support for cert-manager certificates, like for example in scylladb. Would something like that cover your use case?

**Comment by vivekhegadems** [comment]
@javsalgar, thank you for your response!

yes, I checked: https://github.com/bitnami/charts/tree/main/bitnami/scylladb and that should be fine.

I just want to make sure that in standalone mode deployment of apisix the cert-manager issued certificates needs to be used and not statically updated in the apisix yaml as mentioned in https://apisix.apache.org/docs/apisix/deployment-modes/#how-to-enable-ssl.

Also, can you please confirm if cert-manager certificates usage is currently supported in apisix standalone mode deployment?

**Comment by vivekhegadems** [comment]
@javsalgar, can you please confirm the above details for standalone mode apisix deployment?
Also, it would be great if you can provide the timeline on the cert-manager certificate usage support.

**Comment by javsalgar** [comment]
Hi,

The question about the use of tls certs with yaml provider is not about the Bitnami packaging of APISIX, but of the usage of APISIX itself. Maybe the YAML provider allows setting certificate file paths instead of adding the full certificate in the YAML. However, that's something to check with the upstream APISIX devs. Ideally, we would like to have file paths so the future integration with cert-manager is easier. If not, some init container magic would be necessary to include the certs.

About the specific cert-manager integration just like the scylladb chart, I will forward it to the team, but as it is not a critical feature we cannot guarantee an ETA. If you want to speed up the process, you can submit a PR (mimicking the logic of the scylladb chart) and the team will take a look.

**Comment by vivekhegadems** [comment]
@javsalgar, thank you for the details!
Yeah, for confirmation on using certificates I will check with Apisix devs.
