### ISSUE TITLE
[bitnami/postgresql-ha] Clarification of pgpool scaling

### ISSUE THREAD

**Issue by jonathan-m-foley** [bitnami/charts#2866]
**Which chart**:
[bitnami/postgresql-ha]

**Is your feature request related to a problem? Please describe.**
The postgresql-ha chart inclues a value "pgpool.replicaCount" that allows the deployment of pgpool to be scaled. However, it is unclear from the documentation whether setting this value to 2 or more is ever advisable. I don't see any places in the templates where pgpool watchdog is configured so an HA cluster of pgpool nodes cannot be deployed in the manner that the pgpool documentation recommends (i.e. watchdog coordinating the pgpool instances) using this chart.

With values left at defaults, the pgpool kubernetes service will have type "ClusterIP" and thus will be load-balanced within kubernetes (e.g. via userspace proxy, iptables, or IPVS).  I am considering deploying multiple replicas of pgpool behind this service which should result in client requests being load balanced between pgpool instances. I do not know pgpool very well, so I'm not clear on whether it is safe to allow kubernetes to load balance the requests to pgpool instances that do not coordinate via watchdog. If this is safe, then I would also worry that the current pgpool service template does not permit configuring a Session Affinity for the service which may be desirable for performance reasons (maybe...again I am not well versed in pgpool).

The concerns above could perhaps be addressed by dropping in a pgpool.conf (e.g. via values.yaml) that sets up watchdog appropriately and using a post-render tool like kustomize to add Session Affinity to the service definition. But it would be helpful to have some documentation for the chart making a general recommendation for whether or not to use multiple pgpool instances and a suggested/example configuration if they are.

**Describe the solution you'd like**
Documentation added for the chart making a general recommendation for whether or not to use multiple pgpool instances and a suggested/example configuration if they are.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by miguelaeh** [comment]
Hi @jonathan-m-foley ,
Thank you very much for sharing your thoughts. Actually, I think we should investigate about having more than one PgPool replicas. I will open a task on our side to check the official docuemntation and adapt the Helm Chart if needed or document the current approach.

**Comment by jonathan-m-foley** [comment]
Great, thank you!

**Comment by anatoliy-balakirev** [comment]
Hi guys. Any news on this so far? I would also like to use this helm chart now to get HA Postgres and this pgpool seems to be the single point of failure there.

**Comment by miguelaeh** [comment]
Hi guys,
We got some information about this and the conclusion seems to be that it is possible to use multiple pgpools.
I paste the emails we shared:

- Our initial question:

```
Hi,
  First of all I am not very sure if this is the right list to post this question, if it is not, please point me to the appropriate place.

  I would like to deploy pgpool in HA in kubernetes, but as kubernetes handle all the liveness test of the nodes, load balancing and "virtual" IPs handling, I would like to know what I should configure in pgpool.
  Let's say I would like to run 2 instances of pgpool, if I have a Load balancer that send requests to the nodes, Would it be safe to do just that, or does a pgpool instance need to know the others to sync some information ?.
  I have seen this and this pages, but it is not clear to me if the `other_xxxx` parameters are used just for watchdogging or there is more involved that I am missing.

Example configuration from the AWS link.

use_watchdog = on
delegate_IP = ''
wd_hostname = 'instance-1-private-ip'
other_pgpool_hostname0 = 'instance-2-private-ip'
other_pgpool_port0 = 9999
other_wd_port0 = 9000
wd_escalation_command = '$path_to_script/aws-escalation.sh'
wd_de_escalation_command = '$path_to_script/aws-de-escalation.sh


Thanks forehand.
```

- The response:

```
Hi,

> Hi,
>   First of all I am not very sure if this is the right list to post this
> question, if it is not, please point me to the appropriate place.

Yes. Here is the right place to ask questions related to pgpool.

>   I would like to deploy pgpool in HA in kubernetes, but as kubernetes
> handle all the liveness test of the nodes, load balancing and "virtual" IPs
> handling, I would like to know what I should configure in pgpool.
>   Let's say I would like to run 2 instances of pgpool,

As you said K8s will handle all the liveness test of the nodes,
why do you need 2 instances of pgpool?

> if I have a Load
> balancer that send requests to the nodes, Would it be safe to do just that,
> or does a pgpool instance need to know the others to sync some information
> ?.

Do you mean you will send queries via another load balancer, not via pgpool?
It is possible to send queries without going through pgpool.

Below is an example of configuring pgpool on k8s.

https://github.com/pgpool/pgpool2_on_k8s
https://github.com/pgpool/pgpool2_on_k8s/blob/master/docs/index.md

>   I have seen this
> <https://www.pgpool.net/docs/latest/en/html/example-aws.html> and this
> <https://www.pgpool.net/docs/latest/en/html/example-aws.html> pages, but it
> is not clear to me if the `other_xxxx` parameters are used just for
> watchdogging or there is more involved that I am missing.

Yes. "other_xxxx" is used only for watchdog.
```

And a later response:

```
> > >   I would like to deploy pgpool in HA in kubernetes, but as kubernetes
> > > handle all the liveness test of the nodes, load balancing and "virtual"
> > IPs
> > > handling, I would like to know what I should configure in pgpool.
> > >   Let's say I would like to run 2 instances of pgpool,
> >
> > As you said K8s will handle all the liveness test of the nodes,
> > why do you need 2 instances of pgpool?
> >
> 
> For HA, or balancing load.

I think you don't need HA on K8s, so you can disable
pgpool's watchdog capability using "use_watchdog = off".

You don't need Pgpool-II's health_check, automated failover and watchdog on K8S.
You may only need to use query load-balacing and connection pooling.

> > > if I have a Load
> > > balancer that send requests to the nodes, Would it be safe to do just
> > that,
> > > or does a pgpool instance need to know the others to sync some
> > information
> > > ?.
> >
> > Do you mean you will send queries via another load balancer, not via
> > pgpool?
> > It is possible to send queries without going through pgpool.
> >
> 
> I wanted to mean, a service of type LoadBalancer, like this:
> https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer

Yes. You can use other LoadBalancer.
```

**Comment by anatoliy-balakirev** [comment]
hi @miguelaeh TBH from those emails I'm still not 100% convinced we are all on the same page here.
> I think you don't need HA on K8s, so you can disable
> pgpool's watchdog capability using "use_watchdog = off".

I'm not sure how that person came to this conclusion, TBH :) If now I have only one instace of the pgpool available in my k8s setup and for whatever reason it crashes - my app won't be able to function properly as long as pgpool is not restarted. Having a couple of instances of the pgpool deployed is exactly to solve that problem. Otherwise it's all highly available, we have multiple instances of Postgres, but then in front of them we have one instance of pgpool, which is then the single point of failure and undermines the whole point.

From this article: https://hackernoon.com/postgresql-connection-pooling-and-load-balancing-with-pgpool-ii-cluster-edbbb7959ef1
> In PgPool-II cluster mode, only 1 node will be accepting connections at a time (it is, of course, the master node). The watchdog of each node will perform heartbeat checking to the master node. In case of failure to detect master node, the slave/standby node assumes the master is down and takes over the master role.

I'm making a conclusion that when scaling pgpool - there must be one leader and whatever number of followers. So first of all, is it the correct assumption or there might also be just multiple leaders? Because based on the review of the current helm chart, leader / follower setup doesn't seem to be supported (there is no watchdog configured anywhere).

Then if we just missed sometihng and increasing number of replicas in the current helm chart will properly set up cluster of leader / followers - it is not clear on how to connect to the leader in the k8s env, when there is a `Service` in front of all instances of the pgpool, which will randomly send requests to different pods, so they will end up randomly on leader and on follower. Do we even need to connect to leader or connecting to the follower is ok as well?


So to wrap it up:
* In which mode cluster of pgpool instances will be set up if I set `pgpool.replicaCount=2`? Two leaders or leader/follower?
* In case it will be multiple leaders - is it really a valid set up or rather a bug?
* In case it will be leader/follower - is it ok to connect to both of them using k8s `Service` (wich will send requests to either of them randomly) or we need to somehow figure out on the application side, which one is now the leader and only connect there? (which I'm not even sure how to do)

**Comment by miguelaeh** [comment]
Hi @anatoliy-balakirev ,
Thank you for bringing this. I also have some doubts about what you are exposing.  I will add this information to our internal task so we can make a further investigation about it and also add to the `README.md` a section about using multiple pgpool.
We will get back to you when we have news.
Thank you for your patience.
Regards.

**Comment by haizafrog** [comment]
Hi @miguelaeh,
I'm following this thread and really curious if there in any progress in this effort of enabling pgpool-II, HA capabilities in [bitnami/postgresql-ha] chart ?

Thanks!

**Comment by miguelaeh** [comment]
Hi @haizafrog ,
@rafariossaa will investigate this deeper during the next week, so he should bring new information soon.
Thank you for the patience guys! We are a small team and sometimes we cannot work on everything we would like.

**Comment by rafariossaa** [comment]
Hi @anatoliy-balakirev @haizafrog ,
  Sorry for the delay.

  I would like to make some clarifications first. 
  When it is said that `you don't need HA on K8s` it doesn't mean you don't need several pgpool nodes to ensure availability. What it means is you don't need to handle the HA because K8s is taking care of that.
  In typical HA scenarios, not in kubernetes but when using baremetal or virtual servers, you will have a monitoring service that monitor a process (pgpool) in each node and handle which node is the "owner" of the service IP (aka floating IP).
  In kubernetes this is not needed because that is what kubernetes does with services and deployments. Basically, the service provides an IP and load balancing, and deployments take care that the node(s) are alive.

  You can have the number of pgpool nodes you want, they hold no data that need to be sync across all the pgpool nodes. There is not leader/follower roles, so it is safe to scale it to the desired number.

  I hope this make sense.

**Comment by haizafrog** [comment]
Hi @rafariossaa

Thank you very much for the explanation. It make sense :)
I will test it and update if there will be any issue.
Thanks,
Hai

**Comment by rafariossaa** [comment]
Hi,
  You are welcome.
  I am procceding to close this issue now.
  Please, don't hesitate to reopen it or open a new one if you find more issues.

**Comment by msenmurugan** [comment]
@rafariossaa If you scale the replicas of PgPool to 2, then there will be load balance between 2 replicas of PgPool and the max pool and num_init_children need to be tuned in order to support this feature. From this, we can't straight away increase the number of replicas. In order to avoid this, we need to use watchdog feature where 1 instance will be active and other replicas will be standby.

**Comment by rafariossaa** [comment]
Hi,
  @msenmurugan are you telling this because the number of connections in the posgresql nodes ?
  If yes, you have to take this into account when deploying the cluster to adjust the settings accordingly.

**Comment by ladislav-ollos-materna** [comment]
Hi
I noticed pgpool.replicaCount has been added to the chart, but when I try to set it to 2 the second instance ends up in a crash loop (with no information in the logs). Is there some setting I am missing that needs to be set for the pgpool to be redundant too?

**Comment by carrodher** [comment]
Thank you for reaching out and for your interest in our project. We'd be happy to assist you, but to do so effectively, we'll need some more details. Could you please create a separate issue filling the Issue template?

Providing this information will help us better understand your situation and assist you in a more targeted manner.
