### ISSUE TITLE
Update dependencies to eliminate vulnerabilities

### ISSUE THREAD

**Issue by MaciejZakk** [bitnami/charts#28706]
### Name and Version

bitnami/spark 9.2.8

### What is the problem this feature will solve?

Eliminate vulnerabilities.

### What is the feature you are proposing to solve the problem?

Update dependencies to eliminate as many vulnerabilities as possible. Key ones are obviously critical and here, apache derby and zookeper have already released new versions with those problems fixed.

Also if possible, some dependencies with high or even medium vulnerabilities should be updated.

Sorry for posting this as a feature but I couldn't post it differently for some reason. Those vulnerabilities are all publicly visible e.g. on Artifact Hub (https://artifacthub.io/packages/helm/bitnami/spark).

**Comment by carrodher** [comment]
I understand your concern regarding security vulnerabilities. We regularly update our images with the latest system packages; however, certain CVEs may persist until they are patched in the OS or application. Additionally, some CVEs remain unfixed due to the absence of available patches. In vulnerability scanners like Trivy, you can use the `--ignore-unfixed` flag to ignore such CVEs. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
