### ISSUE TITLE
Mediawiki - Is it gone ?

### ISSUE THREAD

**Issue by stanbog** [bitnami/charts#28767]
### Name and Version

bitnami/mediawiki

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello,

We noticed that the Mediawiki helm chart had been deprecated and removed from the repository.
We were wondering what was the reason for this.
We were using this helm chart for one of our customers and worked perfectly.

Can we still use it? Will the images be removed as well?

Thank you.

### What do you see instead?

Mediawiki helm chart

**Comment by hongbo-miao** [comment]
Might be related to https://github.com/bitnami/charts/issues/28765

**Comment by carrodher** [comment]
Thank you for raising your concern regarding the deprecation of MediaWiki. MediaWiki has been deprecated from the Bitnami catalog because we are now focusing on infrastructure solutions. Consequently, we are phasing out certain web application assets to better align with our strategic direction. This is an ongoing effort to ensure our catalog includes the most demanded applications.

As a result, new MediaWiki images will no longer be released in our catalog. However, existing container images will remain available in the registries. After a few months, the [bitnami/mediawiki](https://hub.docker.com/r/bitnami/mediawiki) repository will be replaced by [bitnami/mediawiki-archived](https://hub.docker.com/r/bitnami/mediawiki-archived), where all existing images can be found.

Similarly, the Helm chart will continue to be available as an [OCI artifact on DockerHub](https://hub.docker.com/r/bitnamicharts/mediawiki) but will be flagged as deprecated, meaning it will no longer receive updates.

As part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 4 & 5, Ubuntu 20.04 & 22.04, RedHat UBI 8 & 9, and custom golden images, where other criteria can be followed when choosing which applications are part of the catalog.
You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).
