### ISSUE TITLE
No documentation for upgrading to helm chart of version 22.x

### ISSUE THREAD

**Issue by nix-power** [bitnami/charts#28935]
### Name and Version

bitnami/keycloak-22.1.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

README.md lacks instructions for upgrading to Chart version of 22.0, the last one that appears is the upgrade to 21.0

### What do you see instead?

Still investigating differences between chart values

**Comment by carrodher** [comment]
This is expected since no changes in the Helm chart itself were made, just the Keycloak version was updated from 24.x.x to 25.x.x. In those case where the underlying application is bumped in a major we automatically bump the chart version in a major as well, but since no changes were implemented on our side you need to check the upgrade notes in Keycloak itself
