### ISSUE TITLE
[bitnami/mariadb] MariaDB Switchover, promote a slave to take its Master's place

### ISSUE THREAD

**Issue by ganchandrasekaran** [bitnami/charts#2896]
**Which chart**:
The name (and version) of the affected chart.
charts/bitnami/mariadb

**Is your feature request related to a problem? Please describe.**
Currently the exact role of Slave is unclear. Slave is unable to take the role of Master. As I understand Master is always rescheduled by K8S.  This would mean, Write operation has some downtime when Master pod is down. 

**Describe the solution you'd like**
Perform a dynamic SwitchOver from Slave to Master on master pod failure. 

**Additional context**
Resources:
1, https://mariadb.com/resources/blog/mariadb-maxscale-2-2-introducing-failover-switchover-and-automatic-rejoin/
2, https://mariadb.com/kb/en/replication-overview/

**Comment by dani8art** [comment]
Hi @ganchandrasekaran we are currently using [standard replication as topology](https://mariadb.com/kb/en/replication-overview/#standard-replication) in this chart. However, if you need to have more than one master or use other topology you can also use our [bitnami/mariadb-galera](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera) chart which permits multiple master replication and other advances features. Please, take a look at this chart it maybe fit your requirements. 

Thank you so much for your proposal, if there were something you need help with galera don't hesitate to contact us.

**Comment by ganchandrasekaran** [comment]
@dani8art Thank you for your comment. This Issue is regarding not having all the features of[ Standard replication you pointed out.](https://mariadb.com/kb/en/replication-overview/#standard-replication)

1, Provides infinite read scale out. (Does support with k8s service name: mariadb-slave )
2, Provides high-availability by upgrading slave to master. (However, this is not the case. When a master is down a Slave doesn't switchover to Master. Instead a New Master pod is scheduled by K8S leading to Write Downtime)

**Comment by dani8art** [comment]
Hi @ganchandrasekaran , thank you for the suggestion. 

It could be interesting to support this feature, it is cool. We could open an internal task in order to evaluate it, unfortunately, due to there are existing solutions that can cover both requirements like [1] and [2] ( bitnami/mariadb-galera ) and regarding priorities and internal milestones we can't guarantee it is going to be tackle even if we would tackle it we couldn't give you an ETA. However, if it is important for you and you feel you can handle it and you have a chance to create a PR we would be so happy to handle it.
