### ISSUE TITLE
[bitnami/mediawiki] ERROR: You did not provide an external host in your 'helm install' call

### ISSUE THREAD

**Issue by rafaelbielawski** [bitnami/charts#2912]
bitnami/mediawiki

**Comment by dani8art** [comment]
Hi @rafaelbielawski could you give us a bit more info (commands, values, etc...) so that we can try to reproduce the issue?

BTW, Mediawiki needs an external host when exposing externally because the app itself does some redirection and builds some path base on this, so we prevent future errors by adding this kind of validations. 

```bash
$ helm install m --set mediawikiHost=<your_external_host> --set mediawikiHost=localhost bitnami/mediawiki
```

or you can also try to deploy using ClusterIP. 

```bash
$ helm install m --set service.type=ClusterIP --set mediawikiHost=localhost:8084 bitnami/mediawiki
$ kubectl port-forward --namespace default svc/m-mediawiki 8084:80
```

**Comment by rafaelbielawski** [comment]
hi @dani8art,

command
`helm upgrade --install mediawiki --namespace mediawiki -f values.yaml --set persistence.existingClaim=mediawiki-pvc bitnami/mediawiki`

this chart is compatible with postgres?

**Comment by dani8art** [comment]
Hi @rafaelbielawski did you tested commands with `--set mediawikiHost=<your_external_host>` or locally with `--set mediawikiHost=localhost:8084`?

> this chart is compatible with postgres?

Right now this chart is only compatible with `mariadb`.
