### ISSUE TITLE
[bitnami/kong] Support Kong Manager 

### ISSUE THREAD

**Issue by anjia0532** [bitnami/charts#29164]
### Name and Version

bitnami/kong 12.2.11

### What is the problem this feature will solve?

bitnami/kong charts support kong manager oss feature.
Kong document: https://docs.konghq.com/gateway/latest/kong-manager/
Kong charts: https://github.com/Kong/charts/blob/15a302ba0bec4c170ba993ac444f5bba0106406a/charts/kong/values.yaml#L1069-L1114

**Comment by carrodher** [comment]
Thank you for bringing this issue to our attention. We appreciate your involvement! If you're interested in contributing a solution, we welcome you to create a pull request. The Bitnami team is excited to review your submission and offer feedback. You can find the contributing guidelines [here](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md).

Your contribution will greatly benefit the community. Feel free to reach out if you have any questions or need assistance.

**Comment by anjia0532** [comment]
[bitnami/kong](https://github.com/bitnami/containers/blob/main/bitnami/kong/3/debian-12/Dockerfile) need build and copy [kong/kong-manager](https://github.com/Kong/kong-manager) to `/opt/bitnami/kong/server.default/gui`

e.g.

```Dockerfile
FROM kong:3.7.1 as builder
FROM bitnami/kong:3.7.1-debian-12-r7

COPY --from=builder /usr/local/kong/gui /opt/bitnami/kong/server.default/gui

USER 1001
```

**Comment by andresbono** [comment]
Hi @anjia0532, thank you for proposing this improvement and sharing references. It looks like the addition of kong-manager will require:

1) Tracking the https://github.com/Kong/kong-manager component (internal changes on our side).
2) Changes in https://github.com/bitnami/containers. Downloading the component as part of the Dockerfile, some new initialization logic related to kong-manager.
3) Changes in the bitnami/kong chart (this repo).

In order to evaluate and prioritize the actions on our side, we would like to ask first if you would like to contribute opening PRs for 2) and 3). Is that something you are up to do?
