### ISSUE TITLE
[bitnami/cassndra] Uninstalling and reinstalling cassandra results in bad username and password

### ISSUE THREAD

**Issue by scottillogical** [bitnami/charts#2929]
**Which chart**:
bitnami/cassandra 

**Describe the bug**
If you install, uninstall, and then re-install the cassandra helm chart, the instructions to connect to it no longer work.  

I understand this is likely because the password is stored in the persistent volume which does not get removed when you helm uninstall.    

**To Reproduce**
1.  Install the helm chart
2. Verify password works with provided instructions
3. Uninstall helm chart
4. Install helm chart
5.  Attempt to connect with password by pulling it out of k8s secret store with provided instructions
6.  Observe this does not work

**Expected behavior**
The password stored in k8s secrets upon re-install should work.    

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @scottillogical 

As you mentioned this is related to the PVCs. There is a known issue in Helm (reported quite long time ago) with PVCs since these ones are not deleted when you delete your helm release, see:

- https://github.com/helm/helm/issues/5156

Therefore, you need to ensure that you manually removed them. Otherwise, if you install again a chart using the same name you previously used, it'll try to reuse the existing PVCs giving a conflict.
