### ISSUE TITLE
Postgres-ha

### ISSUE THREAD

**Issue by rg2609** [bitnami/charts#2931]
**Which chart**:
Postgres-ha

**Describe**
Postgres-ha is a good feature, one more feature makes it better that is Horizontal Pod Auto-scaling (HPA). Now, we can scale the pod but it is manually scaling. 

**Expected behavior**
It should scale up and down the pod automatically.

**Comment by carrodher** [comment]
Hi, thanks for the suggestion, at this moment we are working on different fixes/improvements for the postgresql(-ha) charts, but the one you are suggesting was not in our short term improvements list. I think it's a good feature to be added to the chart if you want to contribute with the required changes we are happy to help and review the PR.

**Comment by rg2609** [comment]
Hi @carrodher, thanks for the quick response. If you could give us a guidence on how to implement HPA (what components needs to be tweaked on top of a example like [https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#create-horizontal-pod-autoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#create-horizontal-pod-autoscaler))
We could implement it and raise a PR for your review

**Comment by carrodher** [comment]
Hi, at this moment there are different charts implementing HPA: `spring-cloud-dataflow`, `spark`, `nginx`, `thanos` or `kong`.

For example, in the case of kong, [this is the template](https://github.com/bitnami/charts/blob/master/bitnami/kong/templates/hpa.yaml) and [here you can find the values](https://github.com/bitnami/charts/blob/master/bitnami/kong/values.yaml#L475).

**Comment by srinathganesh1** [comment]
Hey, I am working with @rg2609 on this topic of HPA for postgres. So I am NOT hijacking this thread/post 
------

Summary of Research:
- There is a environment variable called `REPMGR_PARTNER_NODES` 
  - This maintains a list of known replicas in format `APP_NAME-postgresql-ha-postgresql-REPLICA_NUM.APP_NAME-postgresql-ha-postgresql-headless.default.svc.cluster.local`
  - This is populated by `templates/postgresql/statefulset.yaml` in its `env` section 
- The replication is to be set on the StatefulSet
  - The statefulset auto create PVC
  - We can check replicate via `kubectl describe statefulset test-postgresql-ha-postgresql | grep Replicas:`

Questions:
- Since `REPMGR_PARTNER_NODES` is set via `statefulset.yaml` with the list of replicas, is there a way to update it?
- Or do we have to manually go into the Pods and set `REPMGR_PARTNER_NODES`?

**Comment by carrodher** [comment]
Hi, thanks for being keeping an eye on this. Are you able to share this env. variable across nodes and maintain it up-to-date?

**Comment by srinathganesh1** [comment]
> Hi, thanks for being keeping an eye on this. Are you able to share this env. variable across nodes and maintain it up-to-date?

Not able to find a way to use HPA to update `REPMGR_PARTNER_NODES`

**Comment by andresbono** [comment]
Hi @srinathganesh1, this seems to be a blocker. We couldn't find an easy way to keep the variable up-to-date. We will continue checking possibilities and if we find a solution we will post a comment.

**Comment by srinathganesh1** [comment]
> Hi @srinathganesh1, this seems to be a blocker. We couldn't find an easy way to keep the variable up-to-date. We will continue checking possibilities and if we find a solution we will post a comment.

Ok thank you. If you have any ideas I can try implement and raise a PR.

**Comment by andresbono** [comment]
In the same way, please, let us know if you come up with new approaches.

**Comment by srinathganesh1** [comment]
> In the same way, please, let us know if you come up with new approaches.

ok sure
