### ISSUE TITLE
[bitnami/redis-cluster] scale will cause original pod restart

### ISSUE THREAD

**Issue by halleystar** [bitnami/charts#29389]
### Name and Version

bitnami/redis-cluster 11.0.3

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. helm install abc  bitnami/redis-cluster --set "usePassword=false"
2. helm upgrade --timeout 600s abc --set "usePassword=false,cluster.update.addNodes=true,cluster.update.currentNumberOfNodes=6" bitnami/redis-cluster

### What is the expected behavior?

old pod would be not affected

### What do you see instead?

the  original pod will Rolling restart

**Comment by jotamartos** [comment]
Hi @halleystar,

The currentNumberOfNodes parameter is used to perform some validations before the upgrade, but it doesn't block/prevent the upgrade process to be executed

https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/update-cluster.yaml
https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/_helpers.tpl

The upgrade command will update the cluster with the latest changes in the chart (or configuration parameters you set). It uses a RollingUpdate strategy and that's why pods are restarted.

**Comment by halleystar** [comment]
In order to minimize the impact, I only want to expand redis and do not want to restart it. And in a bare metal environment, the expansion operation does not require restarting the container. I think helm cannot do the restart expansion. I investigated the reason myself and found that the script in the bitnami container needs to use the environment variable `REDIS_NODES`. Changing this environment variable will cause all containers to restart.

**Comment by jotamartos** [comment]
Hi @halleystar,

As I mentioned above, the logic is defined in those files I shared. We are open to suggestions and improvements, would you like to contribute? You can follow [our contributing](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md) guidelines and improve the solution with your ideas. Those changes will be reviewed by the team and will benefit the whole community. 

Thanks
