### ISSUE TITLE
Mediawiki - question

### ISSUE THREAD

**Issue by stanbog** [bitnami/charts#29590]
### Name and Version

bitnami/mediawiki 20.2.7

### What steps will reproduce the bug?

Hello,

On 7th of August, Mediawiki has been removed from your helm charts. We are actually using this and we'd like to know the following:

1. Is it ok if we fork the removed code into our own repository and keep maintaining it? Any license issues?
2. If the above is yes, can we also get the Dockerfile used to build the Mediawiki images? Couldn't find it in the removed code.

Thank you.

**Comment by carrodher** [comment]
You can do it, the Bitnami Helm charts and containers are licensed under Apache 2 license.

MediaWiki was deprecated around August 6th, you can navigate through the git history to find commits before that date where the MediaWiki container and Helm chart were still here.
Example:
- https://github.com/bitnami/containers/commits/main/bitnami?since=2024-08-06&until=2024-08-06
- https://github.com/bitnami/charts/commits/main/bitnami?since=2024-08-06&until=2024-08-06

**Comment by stanbog** [comment]
Thank you

**Comment by stanbog** [comment]
Can we also get the Dockerfile please?

**Comment by carrodher** [comment]
The latest version was removed in [this PR](https://github.com/bitnami/containers/pull/70602), you can get it from there
