### ISSUE TITLE
[bitnami/elasticsearch] Request more node role support in chart

### ISSUE THREAD

**Issue by gzOne2Free** [bitnami/charts#29614]
### Name and Version

bitnami/elasticsearch 19.5.5

### What is the problem this feature will solve?

We need to setup a transformer node to activate and use transform function in Elasticsearch.

### What is the feature you are proposing to solve the problem?

Can bitnami elasticsearch chart support more ES node type? Currently it support master, data and ingest. We need transformer node.

**Comment by migruiz4** [comment]
Hi @gzOne2Free,

It is possible to extend the current node roles the values: `master.extraRoles`/`data.extraRoles`/`ingest.extraRoles`/`coordinating.extraRoles`.

If you would like to deploy transform-only nodes, it would be necessary to modify the chart manifests to include the new type of dedicated node.

I have created an internal task to work on this feature request but since we are a small team and have to deal with other priorities, I can not give an ETA for it. 
Otherwise, if you would like to contribute by sending a PR adding support for dedicated transform nodes we will be happy to review it and help with anything needed.
