### ISSUE TITLE
[bitnami/grafana] Any way to add notification channels / alerts into the grafana chart?

### ISSUE THREAD

**Issue by alextes** [bitnami/charts#2963]
**Which chart**:
Grafana 2.1.2

**Is your feature request related to a problem? Please describe.**
When recreating grafana my opsgenie webhook notification channel is gone. It also appears a dashboard is failing to automatically create because it can't find the notification channel it needs for its alert.
```
t=2020-06-29T22:23:05+0000 lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=default-provider error="Alert validation error: Data source used by alert rule not found,
```

**Describe the solution you'd like**
Declare notification channel like we do dashboards

**Comment by carrodher** [comment]
Hi,

In order to try to reproduce the issue on our side, please, can you provide more information about the specific parameters you used to deploy the chart? Mainly what are the custom values you used such as parameters, config files, etc

Apart from that, once deployed the chart, what method are you using to recreate Grafana?

**Comment by dani8art** [comment]
Hi @alextes any updates, could you please take a look at the @carrodher's questions?

**Comment by alextes** [comment]
@dani8art it's resolved for me actually! I figured out how to do this, totally forgot about this issue and [created a feature request](https://github.com/bitnami/charts/issues/3031) explaining what the chart would need to do.
