### ISSUE TITLE
[Bitnami Wordpress] local PV for PVC: data-wordpress-mariadb-0 ?

### ISSUE THREAD

**Issue by huangyingw** [bitnami/charts#2975]
**Which chart**:
wordpress:latest

**Is your feature request related to a problem? Please describe.**
I tried to install wordpress on my local bare-metal server:
helm dependency update ./
helm install wordpress ./

it creates a PVC:
kubectl get persistentvolumeclaims
NAME                       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-wordpress-mariadb-0   Pending                                                     11h

But how/where to define a LOCAL PV for this PVC?
I don't find where this PVC "data-wordpress-mariadb-0 " is defined.

**Describe the solution you'd like**
I just want to run it in my local bare-metal server.

**Comment by andresbono** [comment]
Hi @huangyingw, 

Do you have any Persistent Volume Provisioner in your K8s cluster? Please note that you need one in order to dynamically create Persistent Volumes that you can attach to your pods. You can find more information in the link below:

- https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

The error could also be related with your Persistent Volume Provisioner expecting a specific Storage Class to be used on the PVCs. If that's the case, then you'll have to set the `global.storageClass` parameter with the name of that Storage Class. More info in the link below:

- https://github.com/bitnami/charts/tree/master/bitnami/wordpress#global-parameters
