### ISSUE TITLE
[bitnami/redis] 7.2.6 support

### ISSUE THREAD

**Issue by Nuranto** [bitnami/charts#29798]
### Name and Version

bitnami/redis

### What is the problem this feature will solve?

We're planning to switch to valkey next month, but in the meantime, we want to upgrade redis to 7.2.6 quickly for fixing security vulnerabilities.

https://github.com/redis/redis/releases/tag/7.2.6

### What is the feature you are proposing to solve the problem?

add support for 7.2.6

**Comment by carrodher** [comment]
According to our branch strategy, we only provide support for version 7.4.x since this is the minor version with active support from the upstream project, see https://endoflife.date/redis.
The last version of 7.2.x was 7.2.5 released a couple of months ago, but we won't cut a new release for new versions within this branch.

**Comment by Nuranto** [comment]
Even if 7.2.x are the last versions using historical licensing ? (Also, 7.2 seems supported since 7.2.6 is 5 days old)

But yes, I understand your policy. I guess we'll have to switch to valkey earlier.

Thanks for your time.
