### ISSUE TITLE
[bitnami/thanos] 15.7.29 helm chart is not available on dockerhub

### ISSUE THREAD

**Issue by aadyyb** [bitnami/charts#29908]
### Name and Version

bitnami/thanos 15.7.29

### What architecture are you using?

amd64

### What steps will reproduce the bug?

https://artifacthub.io/packages/helm/bitnami/thanos/15.7.29 is published but the helm chart is not available on dockerhub

```
docker manifest inspect registry-1.docker.io/bitnamicharts/thanos:15.7.29
no such manifest: registry-1.docker.io/bitnamicharts/thanos:15.7.29
```

### What do you see instead?

registry-1.docker.io/bitnamicharts/thanos:15.7.29 is available

**Comment by carrodher** [comment]
Thanks for letting us know. I just checked DockerHub and it was automatically published some minutes ago, see https://hub.docker.com/layers/bitnamicharts/thanos/15.7.29/images/sha256-65e38377f2428b069f9b49891863e16475f027ccdac12f632619223c3b5040de?context=explore.

Please note since the process of publishing Helm charts in the _index.yaml_ (to be discontinued at some point) and DockerHub is different, so there could be delays.
