### ISSUE TITLE
Cannot produce/consume when using load balancer for per pod service NLB in kafka

### ISSUE THREAD

**Issue by dsindatry** [bitnami/charts#2997]
I have spun up Kafka in eks cluster and using per node load balancer service. But i cannot produce or consumer. 
Telnet NLB port works 

This is my command 
```
[ec2-user@ip-192-168-64-237 bin]$ ./kafka-producer-perf-test.sh  --topic test-rep-five  --num-records 10000000 --record-size 100 --throughput -1 --producer-props bootstrap.servers=ac72c20a342a64195a7f1619003daec0-edf9a508d906b4a4.elb.us-east-2.amazonaws.com:9094,a5c783acb7bf0483f9d9e4ed538c0171-412dc51745b60c1d.elb.us-east-2.amazonaws.com:9094,aedc0f0eac1c34705a590bb0c692b26e-fce2b20040adc101.elb.us-east-2.amazonaws.com:9094
```

**Comment by carrodher** [comment]
Hi, thanks for using the bitnami kafka chart. In order to try to reproduce the issue on our side, please can you provide more info about how did you deploy the chart? Did you change any parameter by using a custom _values.yaml_ or options via `--set` when installing the chart?

In the same way, there is a section in the README about [how to access Kafka brokers from outside the cluster](https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster), can you take a look just in case you find something useful for your use case?

**Comment by dsindatry** [comment]
Yes i followed those steps and ran my charts like this _helm install kafka -f values.yaml bitnami/kafka_ 
I am running bitnami kafka chart on amazon eks. 
I am testing Producers/consumers from an ec2 instance in the same vpc. I can create topics but cannot produce/consume using load balancer URL's

**Comment by carrodher** [comment]
Hi, running `helm install kafka -f values.yaml bitnami/kafka` it is going to use the default parameters, without taking into account the specific configuration for the load balancers. There are two ways, on the first one you can take advantage of an initContainer in order to discover the IPs, in that case you need to install the chart using
```
helm install kafka --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer
externalAccess.service.port=9094 --set externalAccess.autoDiscovery.enabled=true --set serviceAccount.create=true --set rbac.create=true bitnami/kafka
```
On the second way, you can manually specify the IPs:
```
helm install kafka --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer
externalAccess.service.port=9094 --set externalAccess.service.loadBalancerIPs[0]='external-ip-1' --set 
externalAccess.service.loadBalancerIPs[1]='external-ip-2' bitnami/kafka
```

**Comment by dsindatry** [comment]
@carrodher I run <helm install kafka -f values.yaml bitnami/kafka> after modifying <values.yaml> to include the parameters mentioned 

externalAccess.enabled=true
externalAccess.service.type=LoadBalancer
externalAccess.service.port=9094
externalAccess.autoDiscovery.enabled=true
serviceAccount.create=true
rbac.create=true

I can also try your suggestion.

**Comment by dsindatry** [comment]
How to specify annotations using `set`
Tried this and its not working. 
@carrodher your thoughts ?

helm install kafka --set externalAccess.enabled=true --set externalAccess.service.type=LoadBalancer --set externalAccess.service.port=9094 --set externalAccess.autoDiscovery.enabled=true --set serviceAccount.create=true --set rbac.create=true --set service.annotations='service.beta.kubernetes.io/aws-load-balancer-internal: "true"' --set service.annotations="service.beta.kubernetes.io/aws-load-balancer-type: nlb" bitnami/kafka

**Comment by rafariossaa** [comment]
Hi @dsindatry ,
  To set the annotations, could you take a look to [this thread ](https://github.com/bitnami/charts/issues/1894) ? Maybe it helps.
