### ISSUE TITLE
[bitnami/elasticsearch] How to enable FIPS for elasticsearch

### ISSUE THREAD

**Issue by mpostument** [bitnami/charts#30033]
### Name and Version

bitnami/elasticsearch

### What is the problem this feature will solve?

I see that the Helm chart has an option called [fipsEnabled](https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml#L235). When this value is set to true, it will configure [ELASTICSEARCH_ENABLE_FIPS_MODE](https://github.com/bitnami/charts/blob/d1b9a1f3e9eb822b16643667316db02d1eeb5308/bitnami/elasticsearch/templates/_helpers.tpl#L475) to true as well.

However, I couldn't find specific information about what changes occur when this variable is set to true. There are no mentions of this variable in the documentation here: https://www.elastic.co/guide/en/elasticsearch/reference/current/fips-140-compliance.html#java-security-manager.

Could you please clarify the steps of what happens when this value is set to true? Is this enough to enable FIPS, or do we also need to build our image with a FIPS-enabled version of Java? Additionally, could you provide the steps to enable FIPS using this Helm chart?

### What is the feature you are proposing to solve the problem?

Documentation about how to enable FIPS using bitnami/elasticsearch elasticsearch

**Comment by carrodher** [comment]
With that flag, FIPS is enabled at the ElasticSearch level requiring a Gold/Platinum license. It was added by the upstream as part of the X-Pack configuration and mimicked in the Bitnami Helm chart at https://github.com/bitnami/charts/pull/6486.

Having said that, just enabling that flag is not enough since other components such as Java should be FIPS-compliant as well. The Bitnami Application Catalog (OpenSource) doesn't implement this kind of security framework.
Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog, the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog). In this catalog different security frameworks and standards are applied, see [Security frameworks and industry best practices in Tanzu Application Catalog](https://docs.vmware.com/en/VMware-Tanzu-Application-Catalog/services/main/GUID-security-frameworks-security-frameworks-industry-best-practices-in-tac.html) and more specifically this page for [FIPS](https://docs.vmware.com/en/VMware-Tanzu-Application-Catalog/services/main/GUID-security-frameworks-FIPS-compliance.html).
