### ISSUE TITLE
[bitnami/keycloak] Critical Vulnerability 2024-8698

### ISSUE THREAD

**Issue by Alezzzander** [bitnami/charts#30237]
### Name and Version

bitnami/keycloak:16.1.8

### What architecture are you using?

None

### What steps will reproduce the bug?

Hello,
According to https://github.com/advisories/GHSA-4xx7-2cx3-x473
There is critical  vulnerability in this version and RH fixed it for keycloak in 22.0.13 and 24.0.8. Is it possible somehow to build new images with this fix ? If not,what is the closest chart version that already includes this fix?

### What do you see instead?

-

### Additional information

https://github.com/advisories/GHSA-4xx7-2cx3-x473

**Comment by carrodher** [comment]
I understand your concern about security vulnerabilities. We regularly update our images with the latest system packages; however, certain CVEs may persist until they are patched in the OS or application. Additionally, some CVEs remain unfixed due to the absence of available patches. In vulnerability scanners like Trivy, you can use the `--ignore-unfixed` flag to ignore such CVEs. You can learn more about our CVE policy [here](https://docs.bitnami.com/kubernetes/open-cve-policy/).

In this case, the Helm chart bundles Keycloak 26.0.5 which is not affected by this issue. In the case of containers, we support both Keycloak branches, 25 and 26, with being 25.0.6 the latest one in branch 25, which according to the link you mentioned, it's the patched version.

The Bitnami Application Catalog (OpenSource) is built on Debian 12. Additionally, as part of VMware, Bitnami offers a custom container and Helm Charts catalog based on various base images, such as Debian 11 & 12, PhotonOS 5, Ubuntu 22.04 & 24.04, RedHat UBI 8 & 9, and custom golden images. You can explore these options through the [VMware Tanzu Application Catalog](https://tanzu.vmware.com/content/blog/use-bitnami-apps-with-vmware-application-catalog).

If you have any further questions, feel free to ask.
