### ISSUE TITLE
Feature request: Streaming NATS chart

### ISSUE THREAD

**Issue by alextes** [bitnami/charts#3029]
**Which chart**:
Doesn't exist.

**Is your feature request related to a problem? Please describe.**
The NATS chart is great, but it doesn't support streaming NATS.

**Describe the solution you'd like**
A great streaming NATS chart like the many others Bitnami made 👌 .

**Describe alternatives you've considered**
https://nats-io.github.io/k8s/ has a pretty decent Helm chart already, but is missing some convenient bits like resources, server config, a servicemonitor, production defaults, and maybe more.

**Comment by marcosbc** [comment]
Thanks for the suggestion. The Streaming NATS chart is not currently in our backlog but I make sure to open an internal discussion for this.

Note that you could always contribute the Streaming NATS chart to the Bitnami `charts` repository if you want. Other users have already contributed charts such as [Discourse](https://github.com/bitnami/charts/pull/2072), [MetalLB](https://github.com/bitnami/charts/pull/2068) and [Contour](https://github.com/bitnami/charts/pull/2069).

**Comment by alextes** [comment]
I recently learned the NATS team is working on https://github.com/nats-io/jetstream , might want to wait.

Noted on the welcome contribution!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
