### ISSUE TITLE
Custom Charts substitution script

### ISSUE THREAD

**Issue by teceP** [bitnami/charts#30361]
### Name and Version

bitnami/custom:1.0.0

### What is the problem this feature will solve?

Custom generation of helmcharts.

### What is the feature you are proposing to solve the problem?

I'm looking to generate custom Helm charts for my application based on the charts available in the Bitnami chart templates (e.g., [this template](https://github.com/bitnami/charts/tree/main/template)). I would like to use these templates as a base and replace the placeholders (e.g., `%%CHART_NAME%%`, `%%DESCRIPTION%%`, etc.) with my own values.

Is there an existing script or tool that can help automate this process? Ideally, I'd like to be able to write my custom values into a file or configuration and then generate the final chart with the placeholders replaced accordingly.

If such a tool or script does not currently exist, I would be happy to contribute and create one. Please let me know if this is something I can work on and contribute back to the community.

**Comment by carrodher** [comment]
Hi, thank you for the offer! This template was created for internal development purposes and shared here so the community could benefit from it. Bitnami Helm charts follow various internal processes and phases, so there's no single script that can substitute all placeholders.

If you'd like to create a script for your own use, that could certainly streamline your development. However, we wouldn’t be able to host it in this repository since it would add an extra maintenance task for a tool that we don’t use internally.
