### ISSUE TITLE
[bitnami/postgresql-ha] How to use repmgr to check postgresql replication cluster status

### ISSUE THREAD

**Issue by Roarain** [bitnami/charts#3049]
**Which chart**:
The name (and version) of the affected 
chart postgresql-ha 
docker.io/bitnami/postgresql-repmgr:12.2.0-debian-10-r108

no matter using what option repmgr output 

```
I have no name!@postgresql-postgresql-ha-postgresql-0:/$ PGPASSWORD=MDt5TdRZx1 repmgr -U repmgr -f "/opt/bitnami/repmgr/conf/repmgr.conf" cluster show
could not get current user name: Success
I have no name!@postgresql-postgresql-ha-postgresql-0:/$ repmgr
could not get current user name: Success
```

How to use repmgr to check postgresql replication cluster status

**Comment by marcosbc** [comment]
@Roarain The reason is because the nss_wrapper environment is not configured when you run "kubectl exec".

Note that the PostgreSQL container is non-root, and repmgr does not play well with non-root users, so we are adding nss_wrapper for making it think it has a proper configuration.

To fix it on your side, you would need to run the following commands to setup the environment, so you can run `repmgr`:

```console
$ . /opt/bitnami/scripts/postgresql-env.sh
$ export LD_PRELOAD="/opt/bitnami/common/lib/libnss_wrapper.so"
$ export NSS_WRAPPER_PASSWD="$(mktemp)"
$ export NSS_WRAPPER_GROUP="$(mktemp)"
$ echo "postgres:x:$(id -u):$(id -g):PostgreSQL:$POSTGRESQL_DATA_DIR:/bin/false" > "$NSS_WRAPPER_PASSWD"
$ echo "postgres:x:$(id -g):" > "$NSS_WRAPPER_GROUP"
```

Alternatively, you could always use the `entrypoint.sh` wrapper which configures this for you:

```console
$ BITNAMI_QUIET=1 /opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh repmgr
```
