### ISSUE TITLE
bitnami/chartmuseum  Unable to get Upgrade's to my installed custom helm charts from Kubeapps

### ISSUE THREAD

**Issue by satya0429** [bitnami/charts#3053]
**Which chart**:
The **Chartmuseum v2.13.0** of the affected chart

**Describe the bug**
* I have created a custom helm chart and Upload a custom chart to ChartMuseum.
* I am able to install the custom chart from kubeapps.
* Later on, made some changes to my custom chart and again upload it to ChartMuseum.
* But the thing is I am not getting any updates to my custom chart which I have installed already, even though if I click on the upgrade button it is asking me to "Select the source repository of mychart" but if I'll select also I am not getting anything to update it.
![Capture-4](https://user-images.githubusercontent.com/55990456/86795512-43e09400-c08b-11ea-9c82-e1bad7ae6e14.JPG)
* But all the updates are getting fetched via App Repo (I am able to install the same chart with latest updates)

![Capture-5](https://user-images.githubusercontent.com/55990456/86798558-848ddc80-c08e-11ea-8647-e6661bbf419c.JPG)

**To Reproduce**
1.  Create a custom chart and upload it to the chartmuseum and install it.
2. Made some changes to the custom chart and again push it to chartmuseum.
3. Go to 'Installed custom app'
2. Click on 'Upgrade'
3. Select Chart Repository Name from the drop-down button.
4. See whether you are able to upgrade it or not.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
helm version
Client: &version.Version{SemVer:"v2.16.8", GitCommit:"145206680c1d5c28e3fcf30d6f596f0ba84fcb47", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.8", GitCommit:"145206680c1d5c28e3fcf30d6f596f0ba84fcb47", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dani8art** [comment]
Hi @satya0429, thank you for opening the issue, I was able to reproduce the issue and It seems something relates with kubeapps at least regarding the logs that I found.

The thing is that when it is trying to list the repositories kubeapps is able to list them

```
127.0.0.1 - - [08/Jul/2020:08:30:28 +0000] "GET /api/clusters/default/apis/kubeapps.com/v1alpha1/namespaces/default/apprepositories HTTP/1.1" 200 1324 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
```

Also, when kubeapps tries to get the charts inside a repository it returns a 200 HTTP code

```
127.0.0.1 - - [08/Jul/2020:08:29:55 +0000] "GET /api/assetsvc/v1/ns/default/charts/example HTTP/1.1" 200 943 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
127.0.0.1 - - [08/Jul/2020:08:30:12 +0000] "GET /api/assetsvc/v1/ns/default/charts/my-app-repository HTTP/1.1" 200 1012 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
```

The problem comes when it tries to get info from a repository then it returns a 404 HTTP code

```
127.0.0.1 - - [08/Jul/2020:08:37:06 +0000] "GET /api/clusters/default/apis/kubeapps.com/v1alpha1/namespaces/kubeapps/apprepositories/my-app-repository HTTP/1.1" 404 321 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
```

Maybe, @andresmgot could add sth more here?

**Comment by andresmgot** [comment]
Hi @satya0429,

Indeed, this is a bug present in the latest version of Kubeapps: https://github.com/kubeapps/kubeapps/issues/1815

It will be fixed in the next release but in the meantime, you can create the App Repository in the same namespace than Kubeapps. This will make the App Repository global (so it can be used in any namespace) and you should be able to upgrade the application.

Let us know if that works for you.

**Comment by satya0429** [comment]
Awesome, Thanks much @dani8art  @andresmgot changed namespace it's working now.
