### ISSUE TITLE
Postgresql-HA | Documentation for backup-restore and importing database (from regular postgres)

### ISSUE THREAD

**Issue by srinathganesh1** [bitnami/charts#3071]
**Which chart**:
Postgresql-HA

**Is your feature request related to a problem? Please describe.**
I cannot find documentation to perform these critical tasks:
1. Perform Backup and Restore
2. Import database from a existing regular Postgres database

**Describe the solution you'd like**
Documentation or Guidence to achieve above

**Comment by juan131** [comment]
Hi @srinathganesh1 

We have this generic docs about how to create/restore backups on Bitnami solutions (such as installers or VMs) including PosgreSQL:

- https://docs.bitnami.com/general/infrastructure/postgresql/administration/backup-restore-postgresql/

Then one we have these guides that are specific for the PostgreSQL chart:

- https://docs.bitnami.com/kubernetes/infrastructure/postgresql/

I guess you're looking for specific instructions to manage backups using the chart, right?

**Comment by srinathganesh1** [comment]
> Hi @srinathganesh1
> 
> We have this generic docs about how to create/restore backups on Bitnami solutions (such as installers or VMs) including PosgreSQL:
> 
> * https://docs.bitnami.com/general/infrastructure/postgresql/administration/backup-restore-postgresql/
> 
> Then one we have these guides that are specific for the PostgreSQL chart:
> 
> * https://docs.bitnami.com/kubernetes/infrastructure/postgresql/
> 
> I guess you're looking for specific instructions to manage backups using the chart, right?

Ok thanks, since Postgresql-HA has replicas I felt there would be a diffent instruction set for it. I will try out the links, thanks

**Comment by juan131** [comment]
Hi @srinathganesh1 

I agree, we should have specific guides for this solution. I'll share your feedback with the docs team, so they can evaluate and create specific guides if needed.

**Comment by srinathganesh1** [comment]
> Hi @srinathganesh1
> 
> I agree, we should have specific guides for this solution. I'll share your feedback with the docs team, so they can evaluate and create specific guides if needed.

Hey, did the documentation team review it?

**Comment by juan131** [comment]
Not yet. Let's reopen the issue and mark it as "on-hold" to avoid it to be auto-closed by the stale bot.

**Comment by TJM** [comment]
For backups, we generally have been creating a [CronJob](https://gist.github.com/TJM/b969b6af82c6625e5bc53e597283f010) based on an [unmaintained docker image](https://github.com/Annixa/docker-pg_dump). However it would be nice if that was just a "boolean" to enable a cronjob based backup with a "pvc" volume.

We were also thinking of writing a script that we could drop into the "initdb.d" dir (ConfigMap maybe) that would find the most recent backup in the "pvc" volume (mentioned above) and restore it automatically if there was no database. This would also make major version upgrades almost easy. :)

We would also **_really_** like to see the Point-in-Time-Recovery (archived WAL) enabled as a helm chart option.... which of course could have the requisite built-in restore to a "point in time" as an option.

**Comment by juan131** [comment]
> For backups, we generally have been creating a CronJob based on an unmaintained docker image. However it would be nice if that was just a "boolean" to enable a cronjob based backup with a "pvc" volume

We already support similar features on other chart (e.g [etcd](https://github.com/bitnami/charts/tree/master/bitnami/etcd)). I think it would be interesting including it on this chat (and other db charts too). What do you think @javsalgar ?

> We were also thinking of writing a script that we could drop into the "initdb.d" dir (ConfigMap maybe) that would find the most recent backup in the "pvc" volume (mentioned above) and restore it automatically if there was no database. This would also make major version upgrades almost easy. :)

We should be very cautious about "automated" upgrades. I mean, this kind of operations are very error-prone, and sysadmins usually prefer to perform them manually while monitoring that everything goes well (specially when talking about production environments).

> We would also really like to see the Point-in-Time-Recovery (archived WAL) enabled as a helm chart option.... which of course could have the requisite built-in restore to a "point in time" as an option.

Using the `extendedConfConfigMap` you should be able to add any custom PostgreSQL configuration, including the wal settings (see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf). Could you give that a try?

**Comment by TJM** [comment]
> Using the `extendedConfConfigMap` you should be able to add any custom PostgreSQL configuration, including the wal settings (see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#allow-settings-to-be-loaded-from-files-other-than-the-default-postgresqlconf). Could you give that a try?


Setting up PiTR is on my (excessively long) list of things I would like to do, hence why I'd like it to be a "boolean" in the chart, rather than something I have to actually fully understand what I am doing :) Thanks for the pointer.

**Comment by juan131** [comment]
Hi @TJM 

I understand that it's easier to setup if we have a boolean parameter, but we also need to ensure we have some balance between flexibility for users, and complexity for maintainers.

A parameter like that will imply modifying both the chart and the container, adding the corresponding logic in the container to detect a specific environment variable and configure PostgreSQL accordingly. That's why we offer this "generic" solutions such as `extendedConfConfigMap` that allow us to provide users enough flexibility to set custom advanced configuration while keeping the containers/charts simple and easy to maintain.

**Comment by franklin432** [comment]
Interesting conversation. I am attempting to create a backup and restore solution as well in which I could incorporate into the /bitnami/mongdb chart

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by RomainWilbert** [comment]
Hi !
I deployed a postgresql instance with the chart, and would like to migrate to the postresql-ha. I am looking into options to migrate data from one to the other. Obviously using the old volume with the new chart would not work ?

**Comment by juan131** [comment]
Hi @RomainWilbert 

The old volume won't work for that purpose given they're different solutions with different configuration and internal database, hence you'll have to backup your database and restore it in a new PostgreSQL HA solution.

Please note this issue was solved very long time ago, so please open a new issue if you require further assistance.
