### ISSUE TITLE
New container images security assessments

### ISSUE THREAD

**Issue by carrodher** [bitnami/charts#30850]
On December 10th, 2024, we released a minor version for every Helm chart in the Bitnami catalog. This major version introduced a new security mechanism to detect the usage of non-standard containers while installing or upgrading Helm chart releases.

Replacing the original containers that are shipped with the charts will result in installation errors like the one below:
```
⚠ ERROR: Original containers have been substituted for unrecognized ones. Deploying this chart with non-standard containers is likely to cause degraded security and performance, broken chart features, and missing environment variables.

Unrecognized images:

- [REGISTRY]/[REPOSITORY]:[TAG]
(...)
```

### Why did Bitnami introduce this mechanism?

There are several reasons to introduce this change:

1. Bitnami charts are designed, tested, and validated on multiple platforms using a specific set of Bitnami and Tanzu Application Catalog containers. Therefore, Bitnami cannot guarantee the same quality standards levels when the original container images are replaced.
2. Non-standard container images are likely to cause degraded security and performance, broken chart features, and missing environment variables.
3. Incapacity to provide efficient support for non-standard container images given the Bitnami support team's limited bandwidth.

### Can I use different image tags?

Yes, replacing default image tags is considered a valid use case. For instance, a user might be interested in using the Bitnami PostgreSQL chart using Bitnami PostgreSQL _15.x_ container images (note the chart uses _16.x_ images by default).

That said, it is expected that you see some warnings on the chart notes given that the specific chart & image combination wasn't tested and validated by Bitnami on any platform.

### Can I skip the security verification?

Yes, we introduced a new global parameter on every chart that can be used for that purpose, see:

|Name|Description|Value|
| -------- | ------- | ------- |
|_global.security.allowInsecureImages_|By default, this chart verifies that the original container images that were designed, tested, and validated are used. This option makes the chart skip the verification step and proceed.|_false_|

At your own risk, you bypass the verification specifying the parameter adding the `--set global.security.allowInsecureImages=true` argument to `helm install` or `helm upgrade` commands or, alternatively, adding the block below to your values YAML file:
```yaml
global: 
  security: 
    allowInsecureImages: true
```

### Should I expect any issues upgrading my existing chart releases?

No issue is expected if you upgrade your existing releases using original container images. If you replace them, you'll have to skip the security verification.

### Should I expect errors consuming Bitnami charts from mirror registries?

Yes. It is expected that you face installation errors while consuming Bitnami chart from mirror registries given the security mechanism will detect original images are not used. To continue using mirror registries, you'll have to skip the security verification.

### I built my custom image extending a Bitnami container image, should I expect errors?

Yes. Custom images, even if they're extensions of original Bitnami container images, would be detected by the security mechanism and it is expected to face installation errors. To use your custom image, you'll have to skip the security verification at your own risk.

**Comment by robcresswell** [comment]
I'll take the bait and ask the obvious question; why was this a _minor_ version release? You've probably broken thousands of dev workflows and pipelines

**Comment by perfectra1n** [comment]
*marks as minor version update*
*introduces breaking changes*

**Comment by cglacet** [comment]
I must be stupid, but eventhough this post is long, I don't understand what I'm supposed to do. So I just ignored the error and set `global.security.allowInsecureImages` to `true`. I guess its not so much of an issue because I only use bitnami images in development, but that's a bit confusing.

**Comment by robcresswell** [comment]
They basically just don't want you to use non-bitnami images in their helm charts because its too annoying to support. This is totally fine and reasonable, but they're masquerading it as both a security issue (debatable) and a minor version (absolutely not), which is disappointing.

That said, the vast majority of us are probably just using all this for free so... 🤷🏻‍♂️

**Comment by ggogel** [comment]
What if I'm using an air-gapped environment and pull the image through a remote cache registry? Will this trigger the error? What exactly does this "security assessment" check: repository name, image name and / or image hash?

**Comment by ggogel** [comment]
> It is expected that you face installation errors while consuming Bitnami chart from mirror registries given the security mechanism will detect original images are not used. 

Bitnami team, are you aware that pulling through a mirror or remote cache is basically standard in enterprise environment? What is the security mechanism actually checking? Just the repository and image name?

**Comment by RangerRick** [comment]
> Bitnami team, are you aware that pulling through a mirror or remote cache is a standard practice in enterprise environments? Could you clarify what the security mechanism is actually verifying? The repository and image name?

Yeah, we're overriding the images (which `values.yaml` explicitly supports...) to point to a pull-through proxy, but it is actually the bitnami images still. Seems like extra validation is good idea in general, but the implementation breaks a pretty major usecase which should be supported without having to just turn off validation entirely.

**Comment by pofl** [comment]
Can confirm that we pull our images through a proxy and our Continuous Deilvery fails now.

**Comment by hrobertson** [comment]
:hand: using a pull-through cache.

Even for those genuinely using different images, that doesn't mean those images are 'insecure'!
1. The only thing being validated here is image names/tags, not checksums or anything more rigorous (which I appreciate is beyond the capability of a Helm chart).
2. `global.acceptUnsupportedImagesDisclaimer` would have been a far more reasonable key to use than `global.security.allowInsecureImages`! i.e. this is nothing about security.
3. The message should be a warning, not an error. 
4. "Deploying this chart with non-standard containers is likely to cause degraded security and performance, broken chart features, and missing environment variables." `sed 's/is likely to/may/'`

**Comment by portswigger-tim** [comment]
SHould this not work with public ECR bitnami images too?

**Comment by carrodher** [comment]
Thanks for your feedback. We hear your comments and suggestions, and as always, will take them into account for future changes. We work to make this change as simple and smooth as possible, with an easy-to-follow approach to bypass the error.
 
#### Why did we make this a minor version release?
 
Bitnami's policy for versioning Helm charts is to release a major version for anything that could break the service upgrade or persistent data:
* The major version of the application
* A configuration change in the application (e.g., configuration parameter) that breaks compatibility with the previously deployed configuration.

The supply chain integrity check only affects an optional property of the chart for users who are overwriting the path of the images. It does not affect the previously deployed application during the upgrade; the error is thrown when evaluating the template.

#### Why we introduced a supply chain integrity check
 
The Helm charts have included a warning since May ‘24. We have seen multiple instances where users substituting non-Bitnami or modified images experienced serious security problems, which is why we introduced this check and a simple workaround that ensures awareness when non-standard images are substituted.
 
#### Commercial Bitnami images are available for business use cases.
 
We made this change concurrently with the release of our commercial product, [Bitnami Premium](https://www.arrow.com/globalecs/na/vendors/bitnami/). Bitnami Premium raises the security level for Bitnami Premium and Tanzu Application Catalog with SLSA level 3 in-toto attestations and cryptographic signatures for images and charts. Those security improvements make it easier to mirror or cache commercial Bitnami containers and Helm charts without setting a flag during deployment.

**Comment by perfectra1n** [comment]
> Bitnami's policy for versioning Helm charts is to release a major version for anything that could break the service upgrade

> A configuration change in the application (e.g., configuration parameter) that breaks compatibility with the previously deployed configuration.

This change breaks the service upgrade, as the the Helm chart's templates no longer evaluate when using values that were previously supported.

**Comment by ggogel** [comment]
> We made this change concurrently with the release of our commercial product, Bitnami Premium.

It appears that this breaking change was introduced to align with, and potentially promote, your new commercial offering rather than serving a purely technical or user-driven purpose.

> We have seen multiple instances where users substituting non-Bitnami or modified images experienced serious security problems

Claiming that this change enhances security is not entirely accurate. Using the default image does not inherently guarantee the integrity of the deployed image, as true verification can only be achieved by validating its hash. Likewise, using a different image does not necessarily result in a less secure deployment. I therefore see the name of this parameter as counterintuitive and misleading.

**Comment by viceice** [comment]
what about the official `public.ecr.aws/bitnami/*` images? they should also be accepted. 🤔

**Comment by seagyn** [comment]
If I enable `allowInsecureImages` for a pull-through cache, does that imply Bitnami images are inherently insecure?

**Comment by abhilash-ghosh** [comment]
>  we released a minor version for every Helm chart in the Bitnami catalog. 
I'd suggest to follow the sem version policy strictly. If this is a minor version release, the default value of `global.security.allowInsecureImages` is set to `true`, isn't it?

**Comment by guyguy333** [comment]
Helper checks image URL, breaking all mirrors and pull-through caches, even if used image is the official one.
Instead, helper should checks SHA256 of deployed image. Issue is not origin of image but its content.

**Comment by Dreathorian** [comment]
maybe instead of checking for secure images which you obviously can't, (the floodgate mechanism of `global.security.allowInsecureImages` is just stupid and the opposite of secure, because it is mandatory to use now)  maybe use images from trustworthy sources, that we can define as such?

**Comment by SF97** [comment]
There seems to be no interest from Bitnami to change anything... This is obviously a push for Bitnami premium. It's obviously fine that you want to profit from your work, but stating that non-bitnami repositories are, by default, unsafe and a security flaw is not only wrong but ethically questionable. With no changes to this policy don't expect me to buy anything from Bitnami. I know I'm just a drop in the bucket, but since our words are not being listened to, maybe our money will.

**Comment by cradules** [comment]
This is the first step in monetizing. We already have examples of this strategy. Open source has started to be more like a temporary mask until they hook you, and after that, you are forced to pay, already hooked. 

I have nothing against making money, but don't use the principle of "open source" and then you force users to use their card.  

More and more I want to shift to the old school where open source was driven 100% by communities and not companies.  More and more I see big companies getting into the open source (and I was happy about it) but I was naive! I think they want to control the open source tro'  all kinds of "best practices and security"! 

Risks will always be. Every time you step out of your house you increase the risk of happening something to you. This means I don't need to step out of my house.

Shame on you!

**Comment by portswigger-tim** [comment]
It's all okay guys... just add `--set global.security.allowInsecureImages=true` to your Helm deployment pipelines 🤣  - no need for all the rage.

**Comment by cglacet** [comment]
I don't quite understand, why is bitnami marking its own images as unsafe to use?

I was using `oci://registry-1.docker.io/bitnamicharts/postgresql` but apparently its unsafe now because it uses `docker.io/bitnami/bitnami-shell:10-debian-10-r431` internally. I have no idea what that means.

I only use this for local dev so its not too much of a problem, but its weird.

**Comment by efbicief** [comment]
> The supply chain integrity check only affects an optional property of the chart for users who are overwriting the path of the images. It does not affect the previously deployed application during the upgrade; the error is thrown when evaluating the template.

I work in an environment where all images, including in this case official Bitnami images, get pulled through a proxy. This change has resulted in applications which break when they get moved or recreated (in my environment, these operations result in the templates getting re-evaluated). This is not acceptable for a "minor" change (clearly violates semver - `MINOR version when you add functionality in a backward compatible manner`, this breaks config which previously worked so is not backward compatible), and really reduces my trust in Bitnami.

If this supply chain integrity check were to be implemented properly (by evaluating the pulled image, eg. comparing a hash of the image to what is expected), rather than just checking where the image gets pulled from, this would have caused no problems.
As other commenters have said, I understand that Bitnami wants to monetise through Bitnami Premium, but _please_ don't needlessly break my deployments next time you want to push your product.

**Comment by davgia** [comment]
This is even more relevant now that [docker-hub has changed policies](https://www.docker.com/blog/revisiting-docker-hub-policies-prioritizing-developer-experience/). For unauthenticated users there will be a limit of 10 pull/h. Both Bitnami's images and charts are hosted on docker-hub now. So a pull-through cache is practically a must. This means that I will need to set `global.security.allowInsecureImages` everywhere probably defeating the whole purpose of it.

**Comment by stefanprodan** [comment]
Funny how Bitnami's own images are considered insecure

```
ERROR: Original containers have been substituted for unrecognized ones. Deploying this chart with non-standard containers is likely to cause degraded security and performance, broken chart features, and missing environment variables.

Unrecognized images:
- public.ecr.aws/bitnami/metrics-server:0.7.2-debian-12-r18
```

**Comment by jessesimpson36** [comment]
One side-effect of this that I don't think has been considered are usecases where the bitnami charts are installed as subcharts to a bigger chart.  If  `global.security.allowInsecureImages` is enabled, it doesn't just affect bitnami charts, it would affect all charts installed that listen on that option.  Though I admit, I do not know of a chart other than bitnami's that listens for the `global.security.allowInsecureImages` option.

I personally would prefer if this were a setting in the chart-level, or if this was in a subsection such as `global.bitnami.security.allowInsecureImages`.

**Comment by yardenshoham** [comment]
What's the point of this check if I can mirror the registry in the container runtime configuration?

**Comment by franklouwers** [comment]
> I just find out something that invalidates my previous statement. bitnami and bitnamicharts are a DockerHub [Verified Publishers](https://docs.docker.com/docker-hub/repos/manage/trusted-content/dvp-program/). This means that DockerHub pull rate limiting is not applied for their images and charts. So it's a problem no more (at least for now). That said, I will go ahead and setup a pull-through cache with Harbor anyway just to be safe if docker changes its policy in the future.

@davgia I don't find any mention of that on https://www.docker.com/blog/revisiting-docker-hub-policies-prioritizing-developer-experience/ but also seems to contradict the following quote from https://github.com/bitnami/charts/issues/30853

> Beginning on December 16th, 2024, all free Bitnami Helm charts and containers will be subject to standard pull-rate limits and pull caps in Docker Hub.

**Comment by aschleifer** [comment]
Also just because you can pull them without rate limting from docker hub doesn't mean you want to. There are security concerns out there which make you want to remove public "random" internet access from your cluster nodes. in that case you want to have PTC through a "trusted" registry (e.g. AWS ECR). in that case everything is pulled through a PTC but still the official image.

**Comment by RobKenis** [comment]
Can this be adapted to `global.security.allowRegistries`? We pull all images through our own registry for multiple reasons, so this change feels a little counter intuitive.

**Comment by claytonchew** [comment]
Might be worth adding an exception for "official" mirrors – such as [https://gallery.ecr.aws/bitnami/](https://gallery.ecr.aws/bitnami/).

Also, with many mirrors out there, there's even no mention of what source is considered the "official" images anywhere?

**Comment by franklouwers** [comment]
@claytonchew it seems that mirror isn't even "official" anymore. The blogpost announcing it's official is gone, no more mention of it on the website etc

**Comment by dminca** [comment]
who came up with this brilliant idea, let alone, set it as default to block the chart from installing whatsoever

**Comment by astrosteveo** [comment]
I definitely value the security aspect that Bitnami is taking seriously to assure users they are using a secure image. This implementation is just poorly executed. As previous commenters have mentioned, a hash from the image itself should be checked, not the repo/URL it's coming from. The same way we can download ISO's from mirrors and be assured it's an unaltered copy by verifying the MD5 checksum from what is provided by the original source.

All I did was pull the image from `docker.io` with `docker pull docker.io/bitnami/postgresql:17.5.0-debian-12-r12` and retag it with my local repo and push it up. Nothing else changed. Just because the image is tagged with `my-localrepo/bitnami/postgresql:17.5.0-debian-12-r12` instead of `docker.io/bitnami/postgresql:17.5.0-debian-12-r12` shouldn't make it an insecure, untrusted image. The hash of `postgresql:17.5.0-debian-12-r12` itself should be checked, not the repo it's coming from.

**Comment by psimms-cs** [comment]
This update has broke our deployment now due to us using a self hosted proxy for dockerhub, which is becoming the norm.  This feature needs to be removed or re worked

Getting around it is of course easy, enabling allowInsecureImages, but we shouldn't have to allow "Insecure Images" when we are using your exact image

**Comment by booleanbetrayal** [comment]
This is also breaking attempts at migrating to `bitnamilegacy` repos as per the migration guide here - https://github.com/bitnami/charts/issues/35164

**Comment by Faheetah** [comment]
Bitnami revokes their own images but also makes it a pain to use other images. What a rug pull. Having this issue installing paperless helm chart right now and it's complaining that I am not using images that no longer exist.
