### ISSUE TITLE
with azure-marketplace-charts/bitnami/elasticsearch chart, kibana pod is failing when installing image version 6 

### ISSUE THREAD

**Issue by ericfaure007** [bitnami/charts#3089]
**Which chart**:
azure-marketplace-charts/bitnami/elasticsearch/ 
version: elasticsearch-12.4.3

**Describe the bug**
when installing chart with command:
helm install elastic-test --set image.tag=6,name=elastic-test,global.kibanaEnabled=true bitnami-azure/elasticsearch
kibana pod is failing because elastic is running version 6.8.10 but kibana is running in version 7.8.0

**To Reproduce**
helm install elastic-test --set image.tag=6,name=elastic-test,global.kibanaEnabled=true bitnami-azure/elasticsearch
pod kibana is failling

**Expected behavior**
when setting image.tag=6 to helm install command, elastic AND kibana should use the version 6.8.10

**Version of Helm and Kubernetes**:
helm version: v3.1.3+2
openshift 4.3

- Output of `helm version`:

```
helm version
version.BuildInfo{Version:"v3.1.3+2.el8", GitCommit:"4edcae3c96edf7fa6a3bcf93de6d85763aed1284", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Output of `kubectl version`:

```
 oc version
Client Version: 4.4.6
Server Version: 4.3.27
Kubernetes Version: v1.16.2+d6d3cff
```

**Additional context**
N/A

**Comment by marcosbc** [comment]
Hi @ericfaure007, we understand your issue but we don't believe it's something the chart should be doing, since this would only be to support a very specific use case, which can be easily fixed by just setting the kibana version with `kibana.image.tag`.

Note that we only test the version of Elasticsearch currently published in the chart (currently 7.8.0), meaning that any other tag (i.e. 6.x) may fail. We're not able to maintain that except in the case the fix is simple and compatible with the current version, as some versions contain breaking changes making it impossible to run different versions of the software between major versions.
