### ISSUE TITLE
[bitnami/jenkins] Allow specifying the JNLP port

### ISSUE THREAD

**Issue by PhoneixS** [bitnami/charts#3140]
**Which chart**:
Bitnami/jenkins 5.0.18

**Is your feature request related to a problem? Please describe.**
The problem is trying to use docker agents. They are created correctly but they can't communicate with the Jenkins server as the port isn't opened in the pod neither in the service.

**Describe the solution you'd like**
I think it could be a nice feature to allow the user to set extra ports to be opened and added to the service or at least one for the JNLP.

**Describe alternatives you've considered**
For now, I have changed the ports manually in the deployment and service directly in kubernetes.

**Comment by joancafom** [comment]
Hi @PhoneixS !

Thanks for posting your issue. It would be a nice feature for sure, and we already have some other charts that support it (see [EJBCA](https://github.com/bitnami/charts/tree/master/bitnami/ejbca) or [Discourse](https://github.com/bitnami/charts/blob/3250b3dfd96d1f5a20bf8e5d2a383259d1e8fcdd/bitnami/discourse/values.yaml#L342), for example). We can implement that in our side, or if you like to (in order to speed up the process), you could create a PR with the changes. Our team will be more than happy to review it and merge it!

**Comment by PhoneixS** [comment]
I coul try to implement it when I have more free time.

**Comment by joancafom** [comment]
Nice to hear that! We are a small team that receive dozens of feature requests (and we love that 😄) and sometimes implementing them on our side can take more time that we wanted to. Thank you very much!
