### ISSUE TITLE
Access denied on https://charts.bitnami.com/index.yaml

### ISSUE THREAD

**Issue by nguse** [bitnami/charts#3153]
**Describe the bug**
Currently receiving 401 access denied on https://charts.bitnami.com/index.yaml, this was working before today

**Comment by rajan123456** [comment]
I have been using https://charts.bitnami.com/bitnami/index.yaml and it is still working correctly.

**Comment by avinashbo** [comment]
Was working well yesterday

$ helm repo add bitnami https://charts.bitnami.com
Error: Looks like "https://charts.bitnami.com" is not a valid chart repository or cannot be reached: Failed to fetch https://charts.bitnami.com/index.yaml : 403 Forbidden
$

**Comment by beltran-rubo** [comment]
Hi,

This was an old repository location, it was moved to https://charts.bitnami.com/bitnami in 2018 and we were keeping a redirection. Due to a HTTPS to HTTP redirection, we recently removed the redirection and added the instructions to the proper location in the HTML site, sorry for the inconvenience.

Please use https://charts.bitnami.com/bitnami as the Helm repository.

**Comment by carrodher** [comment]
I am adding more info just in case more people found the same issue. As @beltran-rubo rightly said, the repo URL was moved in 2018 from `https://charts.bitnami.com` to `https://charts.bitnami.com/bitnami` but we keeping a redirection to the previous one. Last month, we removed that redirection adding the instructions about how to add the repository from scratch in the HTML of the old URL (https://charts.bitnami.com).

If you want to add the bitnami charts repository following the instructions that appear in that site should be enough (those are the same instructions present in the [README](https://github.com/bitnami/charts#tldr) of this repo):
```console
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm search repo bitnami
$ helm install my-release bitnami/chart-name
```

On the other hand, if you are using a bitnami chart as subchart, you need to change the `repository` field pointing to the "new" URL in your _requirements.yaml_, something like:
```diff
dependencies:
  - name: mariadb
    version: 7.x.x
-   repository: https://charts.bitnami.com/
+   repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
```

**Comment by petr-motejlek** [comment]
I've been getting 401 Access Denied since last Thursday at `https://charts.bitnami.com/bitnami`. It has not gone away since. Is it me, my ISP, my country? :D

**Comment by rafariossaa** [comment]
Hi,
  Accessing to `https://charts.bitnami.com/bitnami/index.yaml` should work.
  Could you try that ?

**Comment by petr-motejlek** [comment]
Yup, that works.

**Comment by rafariossaa** [comment]
Hi,
  I am happy that worked for you.

**Comment by petr-motejlek** [comment]
It's a bit confusing, because `helm` gave me an error 10 days ago, and my instinct was to test the URL, but I never realized that I need to suffix it with `index.yaml` :) It was probably just some glitch that got sorted fairly quickly, but I waited for the URL (without `index.yaml`) to respond with 200 :)

**Comment by rafariossaa** [comment]
Yes, it could be a glitch at that time.
In any case, the repository url always needs the `index.yaml` part when queried without helm (eg. the browser, curl,..) . That is handled internally by the helm tool.

**Comment by renepardon** [comment]
> Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; INTERNAL_ERROR

Today our CI/CD pipeline fails because of that reason

**Comment by rafariossaa** [comment]
Hi,
  Could you check if it is fixed now ?

**Comment by renepardon** [comment]
@rafariossaa by just opening the link I posted I would say no

**Comment by carrodher** [comment]
Please note the above link is only designed to work using the Helm client. If you want to work with it using a regular browser the only possible action is access to https://charts.bitnami.com/bitnami/index.yaml to download the _index.yaml_

**Comment by carrodher** [comment]
Thanks for letting us know, we are facing some transient issues with the Helm registry, it should work if you retry it:
```console
$ helm repo add bitnami2 https://charts.bitnami.com/bitnami
"bitnami2" has been added to your repositories
```

About the browser, please note this URL is designed for the Helm CLI, the only path accessible via browser is https://charts.bitnami.com/bitnami/index.yaml where you can download the _index.yaml_

Please note this issue was already reported and we are tracking the progress at #8433

**Comment by pansachin** [comment]
Seems like some issue while adding bitnami charts.
Any idea how to fix this ? 

```
helm repo add bitnami https://charts.bitnami.com/bitnami                                                                                                    
Error: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: read tcp <MY-IP>:<PORT>->52.85.3.44:443: read: connection reset by peer
```

**Comment by carrodher** [comment]
There are some transient errors with the Helm registry, we are tracking the progress and unifying conversations at https://github.com/bitnami/charts/issues/8433
