### ISSUE TITLE
Correct way to connect to redis-cluster chart?

### ISSUE THREAD

**Issue by guiajlopes** [bitnami/charts#3183]
Hello,

What is the correct way to connect to the redis-cluster chart on k8s? Should I use the ClusterConfig in the Client and put all the pod hostnames on it? or should I use only 1 connection and connect to the LoadBalancer?

Thanks

**Comment by joancafom** [comment]
Hi @guiajlopes 

Thanks for your issue! Are you trying to connect from within the cluster or are you planning to access from outside it? Here you may find some more [information](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology) regarding both options.

Thanks!

**Comment by guiajlopes** [comment]
Hi @joancafom, thanks for your reply.

I am doing it from inside the cluster. As I understood in my application I can connect directly to the Load Balancer (only 1 address) and the masters and replicas will redirect to the correct shard, is that correct? or do I have to specify the shards in the application level?

**Comment by joancafom** [comment]
Hi @guiajlopes ,

If you are connecting from within the cluster, you can use the default service that is deployed (`ClusterIP`) instead of using a LoadBalancer.

```console
$ helm install beta bitnami/redis-cluster
$ kubectl get svc
NAME                          TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                 AGE
beta-redis-cluster            ClusterIP   192.168.171.213   <none>        6379/TCP                                68s
beta-redis-cluster-headless   ClusterIP   None             <none>        6379/TCP,16379/TCP                      68s
```

As you can see, you can choose any of them to establish the connection.`beta-redis-cluster` will load-balance the requests amongst the endpoints while `beta-redis-cluster-headless` let you access specific ones.

I am not very familiar with the Go package you mentioned, but I guess providing the IP for `beta-redis-cluster` will be enough to get it up and running.

Hope it helps, thanks!

**Comment by guiajlopes** [comment]
Alright, thanks!

In the end I choose to use the `NewClusterClient` and connected to all the pods (pod1.beta-redis-cluster-headless, pod2.beta-redis-cluster-headless etc)

**Comment by ammirator-administrator** [comment]
@guiajlopes 
I have same problem
And also I come to the answer that i should use redis-headless

But how do I construct the end url <POD_NAME>.redis-headless.<NAMEPSAVE>.svc.cluster.local ?? is that the correct one to access the pod by name not by IP?
