### ISSUE TITLE
[mariadb-galera] documentation wrong for cluster scaling

### ISSUE THREAD

**Issue by tomaaron** [bitnami/charts#3284]
**Which chart**:
bitnami/mariadb-galera all versions

**Describe the bug**
The documentation for scaling a cluster up and down shows the variables `cluster.update.addNodes`, `cluster.nodes` and `cluster.update.currentNumberOfNodes` but they don't exist in the chart.

**To Reproduce**
1. Go to https://docs.bitnami.com/kubernetes/infrastructure/mariadb-galera/administration/add-nodes/ and https://docs.bitnami.com/kubernetes/infrastructure/mariadb-galera/administration/scale-down/
2. Follow the documentation
3. See error

**Expected behavior**
A clear and concise documentation of how to scale a cluster down and up.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Probably copy & pasted from redis-cluster.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for reporting. I just forwarded the information to our documentation team so they can review and update the guide. 

For adding node, you can use 

```
helm upgrade <name_of_the_release> bitnami/mariadb-galera --version <the chart version you are using> --set replicaCount=<new number of nodes>
```

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
