### ISSUE TITLE
[bitnami/mongodb] Expand Persistent Volume Claim (PVC)

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/charts#3291]
**Which chart**:
[bitnami/mongodb]

**Describe the bug**
Expanding PVC value causes upgrade to fail

**To Reproduce**
1. helm install mongo-prod bitnami/mongodb -f values-production.yml
2. update pvc size on line 395 from 8Gi to 50Gi
3. helm upgrade mongo-prod bitnami/mongodb -f values-production.yml

**Expected behavior**
I expect that it should upgrade expand the volume because i set my storage class to allowVolumeExpansion: true

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by miguelaeh** [comment]
Hi @kaykhancheckpoint ,
Could you share with us which type of storage are you using? Also, wich kind of cluster?

**Comment by kaykhancheckpoint** [comment]
@miguelaeh 

Yes the storage  type is gp2 and provisioner is aws-ebs.

Im not sure what you mean by what kind of cluster

**Comment by miguelaeh** [comment]
H @kaykhancheckpoint ,
I reproduced your issue. Sadly, this is not an issue related to this Helm Chart but to Kubernetes. It is not allowed to change fields different from `replicas`, `updateStrategy` and `template` as you can see in the error:
```
Error: UPGRADE FAILED: cannot patch "mongo-prod-mongodb" with kind StatefulSet: StatefulSet.apps "mongo-prod-mongodb" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```
I guess that is the error you are getting. 
That is being discussed in the following thread: https://github.com/kubernetes/kubernetes/issues/68737

**Comment by kaykhancheckpoint** [comment]
@miguelaeh Yes that is the error im getting.

**Comment by miguelaeh** [comment]
Hi @kaykhancheckpoint,
I am afraid we don't have currently a workaround for that. In case you find one we will really appreciate it if you can share it with us.
Regards.

**Comment by kaykhancheckpoint** [comment]
@miguelaeh The only workaround ive found was to tear it down and rebuild it with the new PVC value which is not ideal and it meant i had to take a backup of the database and restore it to be safe. 

The other option is to update the ebs manually in aws with the new storage value and then update the pvc in k8 to reflect the change but im not sure if mongo?  would recognize that is now has extra storage space. So i didint bother with this.

**Comment by miguelaeh** [comment]
I am sorry for the inconvenience @kaykhancheckpoint .
Thank you very much for sharing your thoughts.

**Comment by techsaau** [comment]
@kaykhancheckpoint You do not need to create a new PVC. You can use the existing one by following below steps if you already set allowVolumeExpansion to true in storageClass:

- Edit PVC and PV with new storage value
- Uninstall mongodb
- Update the disk size in Azure\GCP\AWS
- Install mongodb with new storage value

I have followed these steps in Azure Kubernetes and it is working for me

**Comment by MatthiasLohr** [comment]
I would assume that using an external PersistentVolumeClaim definition should work. This way, you don't need to modify the StatefulSet but only the PersistentVolumeClaim. Am I right with that? What about improving the chart this way?

**Comment by marcosbc** [comment]
@MatthiasLohr Currently the chart supports specifying an external PVC via `persistence.existingClaim`, not sure if that is what you were looking for, although it seems only to be supported for the "standalone" mode.

However, specifying the `existingClaim` option in the current chart would cause a similar error since it would alter [`volumeClaimTemplates`](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/standalone/dep-sts.yaml#L399), so I don't think it would work. Meaning you would still be forced to re-deploy anyways.

**Comment by MatthiasLohr** [comment]
@marcosbc my comment is related to a general and future-proof solution for the problem, unfortunately not working for existing deployed instances.

The `replicaset` mode `StatefulSet` definition uses a `volumeClaimTemplate` instead of externally defining and referring to an `PersistentVolumeClaim`. It would be even possible to use the exact same specification code, one just has to give it a name. Then, when changing the storage size, only the `PersistentVolumeClaim` would be touched, leaving the `StatefulSet` untouched - and the error would not be occur anymore for instances deployed with a seperate `PersistentVolumeClaim` (a).

Also b) allowing to re-use an existing `PersistentVolumeClaim` in `replicaset` mode or c) allowing to add an extraVolume (`$.Values.extraVolumes`) with the name `datadir` would help here. But neither a nor b are implemented, and c will give a conflict since there is no way to prevent the helm chart to create a volume with the name `datadir`.

https://github.com/bitnami/charts/blob/95fde31b18b53f7a2459fbf611d8b2b805a9338d/bitnami/mongodb/templates/replicaset/statefulset.yaml#L466-L480

**Comment by miguelaeh** [comment]
Hi @MatthiasLohr ,
It is needed to use to `volumeClaimTemplate` since we want to use a different volume for each node. Using PVCs we would need to create one file per replica, and because of that, the number of replicas would not be configurable.
IMHO we should not change from `volumeClaimTemaplate` to defining PVCs. We could try to support an option to make this work using PVCs maybe using a `range` to create them, but I am not sure about how to specify the correct one for each node.

**Comment by MatthiasLohr** [comment]
Ok, that's right.

Maybe, for some situations, it could help to work with manually created volumes. In this case, `selector` support in the `volumeClaimTemplates` definition would be great. I created a pull request for that: #4715.

**Comment by miguelaeh** [comment]
Thank you for creating the PR!
We have already merged it.
Regards.

**Comment by dannyharding10** [comment]
For anyone who finds this in the future and feels completely lost like I did, here's what we had to do.

_The following steps assume AWS as the cloud provider_
1. Create a snapshot from the volume through AWS. _Be careful, your data will live here until it makes it to the new volume_
2. Still in AWS, create a new volume of the desired size using that snapshot. It will not be attached to anything
   2.1. The volume has to have a specific tag to be managed by Kubernetes. See [this SO question](https://stackoverflow.com/questions/48132000/kubernetes-kops-error-attaching-ebs-volume-to-instance-you-are-not-authorized). The tag looks like this: `KubernetesCluster: <clustername-here>`
3. In Kubernetes, create a PersistentVolume _that uses this existing volume_, and a PersistentVolumeClaim that goes with that PersistentVolume. (See spec files that I used below)
4. uninstall your mongo release `helm uninstall mongodb` ***This can potentially delete your data, make sure you made a snapshot!!***
5. Reinstall mongo, providing the value `persistence.existingClaim` to your mongo helm chart using the name of the PersistentVolumeClaim you just created, e.g. `helm install mongodb bitnami/mongodb --set persistence.existingClaim=mongodb`
6. Everything should be connected now! But in our case we still got some errors of mongo running out of space.. We had to ssh into the EC2 instance and tell it that the disk size had increased by following the instructions here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html. I had to use sudo for some of these commands to work.

I really hope this helps someone out there!

**Comment by igorrudyk** [comment]
Hello guys,
Could you please recommend the best way to extend Persistent Volume on AWS?

Thank you

**Comment by wittymindstech** [comment]
helm install mongo-prod bitnami/mongodb -f values-production.yml

Will the above command override the value of values.yaml [file ](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml) ? Where do i need to set the storageclass?
