### ISSUE TITLE
postgres-ha replication starts from zero if metric container fail

### ISSUE THREAD

**Issue by cybercoder** [bitnami/charts#3309]
**Which chart**:
postgres-ha

**Describe the bug**
When replication starts it's trying to replicate from master node. In this period if metric container fail, whole of the pod will restart again and replication starts from beginning and this is infinity loop.
I produced database with a table with 30 millions records using ```pg_restore``` and problem exposed.

**Comment by dani8art** [comment]
Hi @cybercoder I think it is not the metrics itself, it could be caused by the readiness probe or the liveness probe. Could you try disabling them? Please add these two parameters to your install command. 

```
--set postgresql.livenessProbe.enabled=fales --set postgresql.readinessProbe.enabled=false
```

It seems your restore script is taking many time so the readiness or liveness probe is killing the container.
