### ISSUE TITLE
[bitnami/mongodb] published chart 8.2.4 doesn't include recent changes 

### ISSUE THREAD

**Issue by vorotech** [bitnami/charts#3364]
**Which chart**:
bitnami/mongodb 8.2.4

**Describe the bug**
I was watching this issue https://github.com/bitnami/charts/issues/3151 and the related PR https://github.com/bitnami/charts/pull/3346. Once merged I was expecting that chart version 8.2.4 should contain the fix introduced to `metrics-svc.yaml`, but the chart contains the previous unfixed version.

**To Reproduce**
```shell
$ helm repo update
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm fetch bitnami/mongodb --untar --version 8.2.4 --destination /tmp/mongodb-8.2.4
$ cat /tmp/mongodb-8.2.4/mongodb/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-metrics
  namespace: {{ include "mongodb.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- if .Values.metrics.service.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector: {{- include "common.labels.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: mongodb
```

**Expected behavior**

The `metrics-svc.yaml` should contain latest changes introduced in https://github.com/bitnami/charts/pull/3346
Notice **if statement**:

```shell
$ cat /tmp/mongodb-8.2.4/mongodb/templates/metrics-svc.yaml
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}-metrics
  namespace: {{ include "mongodb.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- if .Values.metrics.service.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.metrics.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
  selector: {{- include "common.labels.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

cc: @marcosbc

**Comment by carrodher** [comment]
Hi, thanks for reporting this issue. As documented in the [CONTRIBUTING](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#pr-approval-and-release-process) guide once merged the chart code in GitHub, we have an internal CI/CD pipeline to test and push the chart package to the registry. In this case, a weird race condition has done that this test & release process was not triggered.

In the PR, the chart version was bumped ([#3346/files](https://github.com/bitnami/charts/pull/3346/files#diff-8a475b1f61b1fd7fcb06b0359c405eca)), but in the meantime, a new release appeared (https://github.com/bitnami/charts/commit/dbfdbb277b0c9171ca29b52d990d5ef720c3cc06). As those changes were not rebased in the PR when the PR was merged, GitHub didn't include the version bump as it was already bumped in the other commit; that produces the following commit when merged the PR https://github.com/bitnami/charts/commit/39fc0e2e29d2bf81892374d754d8c3dfba924fb6. As the version was not bumped, our internal system didn't detect a new change so the release was not triggered.

In order to solve this issue, I just created a new commit bumping the chart version https://github.com/bitnami/charts/commit/b4550164c8572682f36ea6dfe493999840ca0a94, this new commit should trigger the release process and the changes should be pushed to the registry in the 8.2.5 version.

**Comment by vorotech** [comment]
Thank you for the response @carrodher 
Just as I thought, wanted to draw your team's attention either it is a one-time or potentially repeating issue.

Closing the ticket
