### ISSUE TITLE
default [user] has no permissions

### ISSUE THREAD

**Issue by peppe77** [bitnami/charts#3379]
V.7.5.8

**Describe the bug**
is auth.username is not passed, default [user] is used. turns out that such user has no permissions. would not be better to have guest as default (for the chart) or else have further info/doc on how to make default user to have required permissions?

bash-5.0$ rabbitmqctl list_permissions --vhost /
Listing permissions for vhost "/" ...
user    configure       write   read
guest   .*      .*      .*
bash-5.0$

user user doesn't have any permissions

only guest has

**Comment by peppe77** [comment]
rabbitmq that is

**Comment by carrodher** [comment]
According to the [official documentation](https://www.rabbitmq.com/access-control.html), when the server first starts running and detects that its database is uninitialized or has been deleted, it initializes a fresh database with the following resources:

- a virtual host named `/`
- a user named `guest` with a default password of guest, granted full access to the `/` virtual host

It is advisable to pre-configure a new user with a generated username and password or delete the guest user or at least change its password to a reasonably secure generated value that won't be known to the public.

So I think from a security point of view, doing `guest` as the default user is not recommended by the RabbitMQ developers, what they recommend is create a new user with a password (`user` by default in this case), and then the person managing the Rabbitmq server should create the desired vhost, add the `user` user to the default existing one or whatever, but IMHO the chart by default is following the recommended approach

**Comment by peppe77** [comment]
agreed! though the same problem happened when user==user is used instead [auth.username is not passed OR can set that to user]. only way to get user to work is by deleting the PVC - this is the problem. should be able to set/change the user without having to delete the pvc.

**Comment by carrodher** [comment]
Installing the chart with default parameters the username is set by default to `user` and this user is configured with all the permissions:
```console
$ helm linstall rabbitmq bitnami/rabbitmq
$ kubectl exec -it rabbitmq-0 -- bash
I have no name!@rabbitmq-0:/$ rabbitmqctl list_permissions
Listing permissions for vhost "/" ...
user	configure	write	read
user	.*	.*	.*
```
on the other hand, when installed with `auth.username` everything is configured in the same way but with the new user:
```console
$ helm install rabbitmq1 --set auth.username=newuser bitnami/rabbitmq
$ kubectl exec -it rabbitmq1-0 -- bash
I have no name!@rabbitmq1-0:/$ rabbitmqctl list_permissions
Listing permissions for vhost "/" ...
user	configure	write	read
newuser	.*	.*	.*
```

This is something configured in the configuration file, see [values.yaml#L188](https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml#L188), this configuration file is mounted as a ConfigMap in the StatefulSet.

In the same way, please take into account that the data is stored into a PVC (including the username) so if you are installing or upgrading the chart using the same name for the deployment, you need to pass the username or password if they are different than the default one if not there is going to be a mismatch between what is in the PVC from the first deployment and what is trying to use in the second one.

This is more or less how the chart is configured, that said, what is the current issue to solve and your proposal?

**Comment by peppe77** [comment]
Hi Carlos, 

The problem described is that after initial deployment (let's say we set username==guest) though later we decided to change that to username==user (via helm update). Printout below shows that guest lingers in there meanwhile user does not have any permissions. Interesting that was not able to logon to UI with neither user nor guest after the helm update.

bash-5.0$ rabbitmqctl list_permissions --vhost /
Listing permissions for vhost "/" ...
user configure write read
guest .* .* .*
bash-5.0$

user user doesn't have any permissions
only guest has 

how to change username to something else other than what was configured on the original deployment - without having to delete PVC (which is not ideal)? [worth to note that raised a feature request to have user saved in the same secret as password is - one does not exist without the other and makes life lot easier to have both under the same secret as opposed current approach].

similar question goes to password - we can start cluster relying on the secret.yaml logic that in the absence of password set via auth.password, will randomly generate/encode password and save into secret along cookie. let's say there is a leak and we need to set password to different value (and we decided to start setting auth.password). How to quickly change the password without having to delete the PVC?

Fact is that between what helm does/allows vs setup - users have to be aware on how critical/sensitive key pairs can be replaced/rotated (security reasons, leak and so on) without impacts. 

thanks

Thanks

/Pedro
same question for

**Comment by carrodher** [comment]
Hi,

The chart at this moment (well the container image) is storing the data in the PVC, in order to check if there are previous data already set when upgrading the chart, the initialization logic is checking if there is already a PVC mounted in the expected directory. If there is no any data in that path (first initialization), the user is created using the value provided by the user or `user` by default; on the other hand, if some data is detected in the path, the chart assumes that the required data is already set, and rabbitmq is going to be initialized with the existing data.
In fact, you can execute `rabbitmqctl list_users` and you are going to see the user from the first initialization, not the one passed during the upgrade, this user is only set in some env. variables as result of templating the yamls.
I don't think the chart should handle this kind of thing by itself, if you want to create a new user, assign it to a vhost, configure the permission, etc you should do it manually by yourself with `rabbitmqctl` (https://www.rabbitmq.com/rabbitmqctl.8.html#User_Management).

This is the result of executing the list commands before and after an upgrade setting a new password
```console
$ rabbitmqctl list_users
Listing users ...
user	tags
user	[administrator]

$ rabbitmqctl list_permissions
Listing permissions for vhost "/" ...
user	configure	write	read
user	.*	.*	.*
```
as expected, setting `auth.username` is not creating a new user during an upgrade. Instead of that, I am able to create the user and it to the vhost:
```console
$ rabbitmqctl add_user newuser newpassword
Adding user "newuser" ...

$ rabbitmqctl list_users
Listing users ...
user	tags
newuser	[]
user	[administrator]

$ rabbitmqctl set_permissions -p / newuser ".*" ".*" ".*"
Setting permissions for user "newuser" in vhost "/" ...

$ rabbitmqctl list_permissions
Listing permissions for vhost "/" ...
user	configure	write	read
user	.*	.*	.*
newuser	.*	.*	.*
```
You should be able to manually change the default user, create vhost, assign it to a vhost, provide permission, etc without an upgrade since IMHO it's not the purpose of the chart handle this kind of actions, but there are some parameters used during the first initialization but not in 2nd-day operations.

The same happens with the password, if not `auth.password` is provided during the first installation a random one is going to be generated. If you want to upgrade properly the chart, you also need to pass the random value in your upgrade command `helm upgrade ... --set auth.password=whatever`, if not, the upgrade logic is going to generate a new random password that is not going to match with the existing one in the secret/pvc (for this, we are working on adding validation to check if the random password is provided, if needed, during the upgrade). In the same way, if you deployed the chart with an existing secret, it should be also provided during the upgrade, in the end, the chart logic needs to know what is the password used in the previous initialization, if not it is going to generate a new random one that doesn't match with the previous.

**Comment by peppe77** [comment]
Hi,

Thanks for your time and detailed explanation. Appreciated.
We use TF/helm provider and therefore we will to create helm resources to generate(random alphanumeric string) password/cookie and pass them via auth.password and auth.eralngCookie as a way to ensure it is future/upgrade proof. 
Overlooked the fact that comes an upgrade, we will need to pass same password originally provisioned (though originally we relies on secret.yaml logic). 
btw: I agree it may not be the purpose of the chart - however still think it is a problem that if I set new user/password that I get locked out - that is - unable to use neither original user/password not new one. (can try to reproduce it, if needed)

thanks

**Comment by carrodher** [comment]
Hi, we are working to improve the upgrade workflow in relation to that password stuff. There are different possibilities but each one has different pros and cos.
For now, yesterday we implemented some validations in different charts to ensure that the password parameters are set during upgrades if they are required https://github.com/bitnami/charts/pull/3335. In that case, users should see in the notes if there is something missing. As I mention, it is something we are aware of and we are trying to improve little by little.
