### ISSUE TITLE
username to be stored in same secret as pwd/cookie

### ISSUE THREAD

**Issue by peppe77** [bitnami/charts#3380]
current: v.7.5.8

would it be possible to allow username to be stored same secret where cookie/password are? other option could be to use extraSecrets (creates a new secret only for username - not that convenient) though then how to pass that to auth.username? 

best solution would be to have username stored in the same secret , pls

**Comment by peppe77** [comment]
rabbitmq that is

**Comment by rafariossaa** [comment]
Hi,
  Could you provide more background for your request ? I would like to understand the scenario and the use case.
 In most cases, we want to keep these configurations parameters separated as they can be handled by different teams in large organizations, and because also they are different things.

**Comment by peppe77** [comment]
Hi,

personally feel that user/password can be stored/kept same secret as usually they are not managed separately (i.e. one is useless without the other). Moreover, easier to handle on our charts as we can just point to the same secret as opposed to hardcode 'user' and pass the password via the secret created by the .tpl

**Comment by rafariossaa** [comment]
Hi, 
 Thanks for the clarification, I can see your point.
 We currently only set the password via secret in all our charts.
  I have created and internal task to study this change because, for coherence, we should apply the same to all the charts.
  We will come back to you as soon as we have news, currently this is going to take a while.
  Meanwhile any PR are welcome and we will be glad to review and merge it.

**Comment by peppe77** [comment]
Hi,

Here comes my 1st contribution to helm/chart :) 
Had 2 misses though tests caught them (bump up chart version and there was white space I had introduced in yaml file)
Here it is -> https://github.com/bitnami/charts/pull/3404
Thanks for your prompt help and response. Please let me know. Cheers /Pedro

**Comment by peppe77** [comment]
btw can you elaborate on the coherence part? Did not follow you there. (meanwhile, hope my PR gets reviewed/merged)

**Comment by rafariossaa** [comment]
Thank you very much for the PR, we will review it.
About the "coherence": We currently have all the other charts working this way, with only password stored in the secret, and we like all our charts to work in a similar way so this kind of changes should affect all our charts.

**Comment by carrodher** [comment]
Unfortunately, due to the capacity and priorities the team has, there are no plans to work on this refactor of the secrets in the short term.
I'm closing this issue and it can be reopened in the future if we find bandwidth for this change.
