### ISSUE TITLE
[bitnami/wordpress] Allow to set volumeMode for PVC

### ISSUE THREAD

**Issue by T-Grave** [bitnami/charts#3430]
I'm trying to deploy this chart to a Kubernetes cluster backed by a Ceph RBD cluster. Automatic PVC provisioning is taken care of by the official [ceph-csi](https://github.com/ceph/ceph-csi).

This works fine when I have the chart's PVC accessMode set to `ReadWriteOnce`.

But once I want to enable multiple replica's, or use the RollingUpdate deployment strategy, I start running into issues:

1. To use these features, we need to provision a `ReadWriteMany` PVC instead of `ReadWriteOnce`.
ceph-csi supports this for RBD images, but only when the PVC's `volumeMode` is set to `Block`.
 **This property isn't supported by the values.yml.**

2. As a work-around, I manually created a PVC with this volumeMode and used the `existingClaim` setting to use it.
Problem is, **the pod definition wants to mount it under `volumeMounts`, which doesn't work with Block volumes**. When using a Block volume, it needs to be mounted under `volumeDevices` instead.

An example of what the PVC & Pod definition look like when using RWX on ceph-csi can be found here.
https://github.com/ceph/ceph-csi/tree/master/examples#how-to-test-rbd-multi_node_multi_writer-block-feature

Is it possible to support Block device mounts?

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay.
  I am creating an internal task to add and check this feature. This can take a while. We will come back to you as soon as we have news.
  Meanwhile, feel free to send any PRs you consider. We will be glad to review and merge it.

**Comment by root-ali** [comment]
Hi,
Any News for this issue?

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, this task stills in our backlog. I have no ETA for this.
  We accept contributions,  feel free to send any PRs you consider. We will be glad to review and merge it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
