### ISSUE TITLE
Is it possible to include a directory containing SQL files and resources so that they can be copied into docker-entrypoint-initdb?

### ISSUE THREAD

**Issue by oconnelc** [bitnami/charts#3444]
**Which chart**:
postgresql 9.21

**Is your feature request related to a problem? Please describe.**
I have a project that has a very detailed SQL init file as well as supporting binary files that need to get loaded into the database. If all of these files are in the `docker-entrypoint-initdb` directory, the database will correctly initialize (when the database is first created)

**Describe the solution you'd like**
It would be nice to specify a directory to be copied into the `docker-entrypoint-initdb` directory. 

**Describe alternatives you've considered**
I can wait until after the database has been deployed and run the scripts manually. I have no problem doing this, I was just looking to see if it would be possible to automate this process.

**Comment by javsalgar** [comment]
Hi,

Wouldn't the `initdbScriptsConfigMap` value work for this case? If it is because it has a specific directory structure, I think that the best option could be to use the extraVolumes and extraVolumeMounts section where you could specify a volume with the files you require. After that, you could simply have a initdbscript that executes the commands in the folder that you have.

```
initScripts: 
  myScript.sh:  |
      #!/bin/bash
      bash /path/to/your/mounted/folder/script.sh
```

Please let me know if that works for you

**Comment by oconnelc** [comment]
That's a really good idea. Let me give that a shot and see what haappens
