### ISSUE TITLE
postgresql-ha 300G data using much time to rejoin standby node to cluster 

### ISSUE THREAD

**Issue by Roarain** [bitnami/charts#3450]
# postgresql-ha
our business data is 300G even more, situations will using much time
1. primary(old) restart --> Automatic failover a standby to primary(new)
2. standby restart

# according 

[repmgr_clone_primary](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/10/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L462)

[repmgr_rewind](https://github.com/bitnami/bitnami-docker-postgresql-repmgr/blob/master/10/debian-10/rootfs/opt/bitnami/scripts/librepmgr.sh#L478)

```bash
repmgr_clone_primary() {
    info "Cloning data from primary node..."
    local -r flags=("-f" "$REPMGR_CONF_FILE" "-h" "$REPMGR_CURRENT_PRIMARY_HOST" "-p" "$REPMGR_CURRENT_PRIMARY_PORT" "-U" "$REPMGR_USERNAME" "-d" "$REPMGR_DATABASE" "-D" "$POSTGRESQL_DATA_DIR" "standby" "clone" "--fast-checkpoint" "--force")

    PGPASSWORD="$REPMGR_PASSWORD" debug_execute "${REPMGR_BIN_DIR}/repmgr" "${flags[@]}"
}

repmgr_rewind() {
    info "Rejoining node..."

    debug "Deleting old data..."
    rm -rf "$POSTGRESQL_DATA_DIR" && ensure_dir_exists "$POSTGRESQL_DATA_DIR"

    debug "Cloning data from primary node..."
    repmgr_clone_primary
}
```

# How
1. every pod in statefulset mount all pv to using pg_wind
2. using [barman](http://docs.pgbarman.org/release/2.11/) to avoid [repmgr standby clone](https://repmgr.org/docs/current/repmgr-standby-clone.html)

# Is there any other way ?

**Comment by rafariossaa** [comment]
Hi,
  This is a complex problem that would require deeper analysis and testing. 
  Some comments on the proposed solutions:
1- This is not possible because you will need to mount the volume in several pods and most probably those pods will be in different nodes and depending on how the underlying servers are configured you won't be able to mount the volume in different nodes/pods.
2- could you elaborate a bit more on how this scenario would work ?

  The main issue I see here is that you have >300GB of data and this is going to take long to transfer across nodes no matter how you set them. Then only way I can see right now is not transferring all the info, but to use `pg_wind` you will need to mount other PV and that is not possible (or quite improbable you can do it).

  In any case, we are open to receive PRs and we will be glad to review and merge them.

**Comment by Roarain** [comment]
> can
Thanks for replay.
Yes, This is a complex and still working on 2. 
Keep in touch.

**Comment by rafariossaa** [comment]
Hi,
  Please, don't hesitate to share your findings.
