### ISSUE TITLE
[bitnami/airflow] How to trigger chart release after PR merge

### ISSUE THREAD

**Issue by pankajkoti** [bitnami/charts#3523]
Hi Team, I had created a PR earlier yesterday. It's approved and merged. However, the release of the chart has not taken place yet. Is there a way to expedite the release other than bitnami/bot for which I don't know the schedule? Would really appreciate if it can happen manually as it can unblock me. Thank you

**Comment by juan131** [comment]
Hi @pankajkoti 

I guess you're referring to this one: https://github.com/bitnami/charts/pull/3514

As it's explained in the [Contributing guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md):

> ...
> 4. When the PR passes all tests, the PR is merged by the reviewer(s) in the GitHub master branch.
> 5. Then our CI/CD system is going to push the chart to the Helm registry including the recently merged changes and also the latest images and dependencies used by the chart. The changes in the images will be also committed by the CI/CD to the GitHub repository, bumping the chart version again.
> NOTE: Please note that, in terms of time, may be a slight difference between the appearance of the code in GitHub and the chart in the registry.

It can take a while since the PR is merged, until the chart is actually published. Depending on the load we have in the pipeline at a certain moment, it can take just a few hours or a bit longer. 

By the way, your changes are already published:

```console
$ helm repo update
Hang tight while we grab the latest from your chart repositories...
helm rep...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈ Happy Helming!⎈
$ helm search repo bitnami/airflow
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/airflow	6.4.0        	1.10.12    	Apache Airflow is a platform to programmaticall...
```

**Comment by pankajkoti** [comment]
Thank you for the explanation
