### ISSUE TITLE
[redis] Expose master and replicas to external clients when using redis-sentinel

### ISSUE THREAD

**Issue by wKavey** [bitnami/charts#3524]
**Which chart**:
`bitnami/redis`, all future versions

**Is your feature request related to a problem? Please describe.**
When using the `redis` chart using the sentinel feature, the sentinel only responds with cluster-local IPs to the master and replica instances. This makes it impossible to take advantage of HA from clients connecting from outside the cluster.

```
{external_sentinel_ip}:26379> sentinel get-master-addr-by-name mymaster
1) "{cluster_local_ip}"  #    <-- Here
2) "6379"
```
The docs explicitly call this out...
```
This command will return the address of the current master, which can be accessed from inside the cluster
```

From what research I have done it looks like there is no current workaround for this using the bitnami chart.

**Describe the solution you'd like**
It would be awesome if there was such a way to configure this chart to expose all master and replica instances to external IPs, and then have `redis-sentinel` respond with cluster-external addresses.

**Describe alternatives you've considered**
Currently the only alternative if we want to use redis sentinel is to deploy our own sentinel topology outside of kubernetes. `redis-cluster` does not provide the same HA ability that sentinel does, so it is not an equivalent switch to use that.

**Comment by marcosbc** [comment]
Hi @wKavey, unfortunately this is not supported yet. In order to do that, we would need to implement something similar like we added in [Redis Cluster](https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/values.yaml#L580) or [Kafka](https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml#L508).

Unfortunately we don't have the bandwidth for performing such change right now. However, a similar change was recently added to the Redis Cluster chart which may be helpful for you.

Would you be willing to take a look into it? We appreciate PRs and any kind of external contribution, and will always be happy to review them.

**Comment by jhoomsharabi** [comment]
This looks to be in similar line of https://github.com/bitnami/charts/issues/3745 issue

**Comment by miguelaeh** [comment]
Hi @jhoomsharabi ,
Let's continue talking about this in the referenced thread.
