### ISSUE TITLE
postgresql:  when replication.enabled = true, and service.type = NodePort. The service nodePort conflicts with each other.

### ISSUE THREAD

**Issue by skyrain** [bitnami/charts#3525]
**Which chart**:
bitnami/postgresql

**Describe the bug**
when replication.enabled = true, and service.type = NodePort. The service nodePort conflicts with each other due to we will have multiple service created with same nodePort.

**To Reproduce**
1. In `values.yaml` file set field value as below:

replication.enabled = true
service.type = NodePort

Choose a random nodePort:
service.nodePort = 30001

**Expected behavior**
postgresql installed with replication enabled.

**Version of Helm and Kubernetes**:
helm 3
k8s 1.18
- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Helm cannot install with error message as below:

```
Error: Service "testdb-postgresql" is invalid: spec.ports[0].nodePort: Invalid value: 30001: provided port is already allocated
```

Proposal Solution:
1. Fix helm template or values.yaml, when service type is `NodePort`, we should ask user for two different nodePorts and assign to master/replica service correspondingly.

**Comment by carrodher** [comment]
Hi, that is something you can fix by using the `master.service.nodePort` and `slave.service.nodePort` parameters, for example
```
$ helm install postgresql \
--set replication.enabled=true \
--set service.type=NodePort \
--set slave.service.nodePort=30001 \
--set master.service.nodePort=30002 \
bitnami/postgresql

$ kubectl get svc
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
postgresql            NodePort    10.23.255.204   <none>        5432:30002/TCP   11m
postgresql-headless   ClusterIP   None            <none>        5432/TCP         11m
postgresql-read       NodePort    10.23.250.206   <none>        5432:30001/TCP   11m

$ kubectl get pods
NAME                             READY   STATUS    RESTARTS   AGE
postgresql-postgresql-master-0   1/1     Running   0          11m
postgresql-slave-0               1/1     Running   0          11m
```

Please take into account those values overwrite the `service.nodeport` one, so in case you set the three of them with `--set slave.service.nodePort=30001 --set master.service.nodePort=30002 --set service.nodePort=30099`; `service.nodePort` is going to be ignored. If `service.nodePort` is specified and only one of `slave.service.nodePort` or `master.service.nodePort`, the "global" nodePort will be used in the one that is not specifically set.

It's true that we can improve the user experience by adding a validation instead of letting helm return his error, PRs are welcome just in case you want to contribute by adding this validation; we'll be happy to review the code and merge it

**Comment by skyrain** [comment]
thanks it works
