### ISSUE TITLE
Kafka NoAuth for /config/users/user

### ISSUE THREAD

**Issue by cedricve** [bitnami/charts#3560]
**Which chart**:
Kafka

**Describe the bug**
Agent crashes

I'm using the valies.yml file. I enabled external loadbalancer. Once upgrade the agent crashes with following error.

[2020-08-30 23:07:36,370] ERROR error processing change notification {"version":2,"entity_path":"users/user"} from /config/changes/config_change_0000000002 (kafka.common.ZkNodeChangeNotificationListener)
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/users/user
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:557)

**Comment by joancafom** [comment]
Hi @cedricve 

I would like to know a little bit more about your issue. I guess you are trying to access the broker from the outside, in that case, have you tried following the [guidelines](https://github.com/bitnami/charts/tree/master/bitnami/kafka#accessing-kafka-brokers-from-outside-the-cluster) in the README? Could you provide me with some details on the steps you are following in order to be able to replicate the issue?

In my case, I have tried doing the following and it works for me 😄 :

1. Customize the default`value.yml` file in order to enable external access ([Option A ](https://github.com/bitnami/charts/tree/master/bitnami/kafka#using-loadbalancer-services)in the README):
```yaml
externalAccess.enabled=true
externalAccess.autoDiscovery.enabled=true
rbac.create=true
```

2. Create a new release 

```console
helm install iotta bitnami/kafka
NAME: iotta
LAST DEPLOYED: Mon Aug 31 09:53:59 2020
NAMESPACE: default
STATUS: deployed
...
```

3. The release shows up and running and the service has an external ip:

```console
$ kubectl get pods 
NAME                READY   STATUS    RESTARTS   AGE
iotta-kafka-0       1/1     Running   1          10m
iotta-zookeeper-0   1/1     Running   0          10m

$ kubectl get svc | grep external
NAME                       TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                      AGE
iotta-kafka-0-external     LoadBalancer   10.0.71.73    XXX.XXX.XXX.41   9094:31230/TCP               10m
```
Thanks!

**Comment by TesterYu** [comment]
> **Which chart**:
> Kafka
> 
> **Describe the bug**
> Agent crashes
> 
> I'm using the valies.yml file. I enabled external loadbalancer. Once upgrade the agent crashes with following error.
> 
> [2020-08-30 23:07:36,370] ERROR error processing change notification {"version":2,"entity_path":"users/user"} from /config/changes/config_change_0000000002 (kafka.common.ZkNodeChangeNotificationListener)
> org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /config/users/user
> at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
> at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
> at kafka.zookeeper.AsyncResponse.resultException(ZooKeeperClient.scala:557)

hello  I'm new to kafka I meet the same problem,how to solve it? thank you very much ~~~~

**Comment by andresbono** [comment]
Hi @TesterYu can you check the comment from my colleague  https://github.com/bitnami/charts/issues/3560#issuecomment-683632518?
