### ISSUE TITLE
[bitnami/spring-cloud-dataflow] CTR image needed / env var

### ISSUE THREAD

**Issue by chrisjs** [bitnami/charts#3571]
**Which chart**:
spring-cloud-dataflow / 0.6.2

**Describe the bug**
in the scdf server deployment, an environment variable is set to point to an image containing the CTR bits, for example:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/2.6.1/src/kubernetes/server/server-deployment.yaml#L60

```
        - name: SPRING_CLOUD_DATAFLOW_TASK_COMPOSED_TASK_RUNNER_URI
          value: 'docker://springcloud/spring-cloud-dataflow-composed-task-runner:2.6.1'
```

**Expected behavior**

this environment variable should be defined in the server deployment. the version is in-line with the dataflow server version. i believe we would need you to roll a `spring-cloud-dataflow-composed-task-runner` and on each chart update that image gets updated and version bumped

the image is currently being built out of the `spring-cloud-dataflow-composed-task-runner` directory of the `spring-cloud-dataflow` project.

**Comment by dani8art** [comment]
Hi @chrisjs, 
Thank you for providing this feedback. 

We are going to open an internal task to work on a solution for supporting this new feature in our chart. 

We'll keep you updated on the progress.

**Comment by dani8art** [comment]
Hi @chrisjs 

We've just released `bitnami/spring-cloud-dataflow-composed-task-runner`
- You can see its source code [here](https://github.com/bitnami/bitnami-docker-spring-cloud-dataflow-composed-task-runner)
- You can download the image

```
$ docker pull bitnami/spring-cloud-dataflow-composed-task-runner:2.6.1-debian-10-r0
```

We just merged the chart code as well as you can see in the above PR. The chart releasing process is taking place, please note that helm repository could take a bit more time to reflect these changes because of its cache.

Please give a try and don’t hesitate to let us know if you find any issue.
Regards.
