### ISSUE TITLE
[bitnami/Grafana] Grafana Image Renderer is not working

### ISSUE THREAD

**Issue by teichae** [bitnami/charts#3619]
**Which chart**:
Helm bitnami/grafana 3.4.1

**Describe the bug**
Grafana Image Renderer is not working

**To Reproduce**
1. edit to values-production.yaml
2. plugins: grafana-image-renderer
3. imageRenderer:
     enabled: true
4. helm install ....
5. Setting Datasource, Slack notification add
6. Alert Create & start
7. Not Send Graph... 

**Expected behavior**

**Version of Helm and Kubernetes**:
Kubernetes is v1.16.8-eks-e16311
- Output of `helm version`:
Helm is v3.2.4

**Additional context**
![image](https://user-images.githubusercontent.com/23469981/92382760-17f39480-f148-11ea-867a-c9bfb740fafc.png)

**Comment by dani8art** [comment]
Hi @teichae I was able to reproduce the issue, after some investigations, I realized that images should be publicly available in order to see them in some of the alert channels such as slack. Please refer to https://grafana.com/docs/grafana/latest/alerting/notifications/#external-image-store in order to see how to configure it in Grafana. 

Thanks for your feedback!

**Comment by teichae** [comment]
oh @Dani8art Thank to reply 👍 

Thanks to you, I find it what the problem.

I solved the problem thanks to your guide.

I hope you have a nice day. 😄
