### ISSUE TITLE
[bitnami/nginx-ingress-controller] Include namespace to ClusterRole name so multiple ingresses are possible to install

### ISSUE THREAD

**Issue by aeimer** [bitnami/charts#3657]
**Which chart**:
bitnami/nginx-ingress 5.4.5

**Describe the bug**
If I want to install two ingresses per cluster helm errors on the ClusterRole.

**To Reproduce**
1. Install the ingress controller on namespace ingress-one with the name ingress-controller
2. Install he ingress controller on namespace ingress-two with the name ingress-controller

```
Error: Failed to render chart: exit status 1: Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "nginx-ingress-controller" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "ingress-main": current value is "ingress"
  Error: plugin "diff" exited with error
```

**Expected behavior**
Both helm installs should work

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. Note that ClusterRoles and ClusterRoleBindings are non-namespaced resources, which means that if you deploy the chart with the same name in two different namespaces, it will collide because of the non-namespaced ClusterRole already existing. Did you try installing the second release of the chart with `--set rbac.create=false`?

**Comment by aeimer** [comment]
Hey, no I haven't tried it, but as I can see in the `rolebinding.yaml` if I use your option `rbac.create=false` the `ClusterRoleBinding` will also bot be deployed, which _is_ namespace dependent on its target.
So I dont see any solution here, that using the namespace-name in the name of the Clusterwide-Resurces or the ugly workaround I currently use with deploying:
- nginx-ingress-main/nginx-ingress-ctrl-main
- nginx-ingress-second/nginx-ingress-ctrl-second
I would like use it like this:
- nginx-ingress-main/nginx-ingress-ctrl
- nginx-ingress-second/nginx-ingress-ctrl

Do I miss something?

**Comment by javsalgar** [comment]
Hi,

I think the only reasonable solution would be one of the two:

  - Divide the rbac.create option into two:
           - rbac.deployClusterRules: That would deploy the clusterRoles and clusterRoleBindings
           - rbac.deployNamespaceRules: That would deploy the roles and roleBindings

   - Allow setting a custom name for the clusterRole and clusterRoleBindings, which can collide

I'm not super convinced with any of the two, but I think that option 2 would be better. Thoughts?

**Comment by aeimer** [comment]
Yes the second one is probably the better one. For 100% separation I would
suggest to use two different clusterroles too!

Javier J. Salmerón-García <notifications@github.com> schrieb am Di., 15.
Sept. 2020, 09:44:

**Comment by javsalgar** [comment]
Hi,

Thanks, I will open a task for evaluation. As this is not a critical feature, we cannot guarantee an ETA. If you want to speed up the process, feel free to create a PR and we will review it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
