### ISSUE TITLE
Can't authenticate to mongodb after delete release and re-install

### ISSUE THREAD

**Issue by moshe-shaham-intel** [bitnami/charts#3659]
**Which chart**:
mongodb 9.1.1

**Describe the bug**
Authentication doesn't work on second install of mongodb chart, after it was previously deleted.

**To Reproduce**
1. `helm install mongo bitnami/mongodb` - everything works perfectly
2. `helm delete mongo` - no errors, looks like everything is deleted correctly
3. `helm install mongo bitnami/mongodb` - authentication doesn't work, using root password

**Expected behavior**
Authentication should work...

**Version of Helm and Kubernetes**:
helm 3.3.1
kubernetes 1.19

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/
amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/
amd64"}
```

**Additional context**
Tested on a simple ec2 instance in AWS, running ubunu 18.04

**Comment by juan131** [comment]
Hi @moshe-shaham-intel 

You didn't remove the associated PVCs, right? I mean, when you uninstall a release, the associated PVCs are not deleted unless you manually do so (use the `kubectl delete pvc ...` command). Therefore, when you delete them, and you install a chart again using the same release name, it reuses the previous PVC. This is a [known limitation](https://github.com/helm/helm/issues/5156) on Helm.

The problem is that the randomly generated password now it's not in sync with the data you have in the volumes, and the authentication fails. That's why we always recommend to specify a password when upgrading releases, see: 

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#upgrading
