### ISSUE TITLE
Artifactory implementation/Access Denied

### ISSUE THREAD

**Issue by Felix941** [bitnami/charts#3677]
Hello,

I'm trying to add the https://charts.bitnami.com/bitnami repo as a helm chart in Artifactory, but I'm getting an access denied, Just like when I open the link in my browser.

I'm not sure if here is the right place to post but I didnt find a better one. Thanks

**Comment by andresbono** [comment]
Hi @Felix941, the helm repository doesn't have any index.html file so that should be the reason to throw an access denied. in your browser. But the repository follow the standard structure: https://helm.sh/docs/topics/chart_repository/. For instance you can get the `index.yaml`:

```console
$ curl -I https://charts.bitnami.com/bitnami/index.yaml
HTTP/2 200
```

If you want specific versions of the charts, you can parse that index file.

**Comment by Felix941** [comment]
Hello @andresbono, thank you that explains that! Sadly I still cant access it with artifactory, I just get an Error 500. But I assume that is a Problem on my site then. Thank you for the quick help!

**Comment by andresbono** [comment]
Please, just leave a comment or open a new issue if you need further help.
