### ISSUE TITLE
[bitnami/rabbitmq] support  LDAP lookup for AD

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#3691]
**Which chart**:
rabbitmq

**Is your feature request related to a problem? Please describe.**
Currently it doesn't work with AD

**Describe the solution you'd like**
suppport more env variable 

https://www.rabbitmq.com/ldap.html
https://stackoverflow.com/a/56209575/667767

**Comment by FraPazGal** [comment]
Hi @maxisam,

From what I understand, this issue is more related to our [rabbitmq container](https://github.com/bitnami/bitnami-docker-rabbitmq#enabling-ldap-support) than to the rabbitmq chart, as it seems an issue related to the container features. Please open an issue in our container repo, so that it can be properly investigated and resolved as soon as possible.
