### ISSUE TITLE
[mongodb] architecture replicaset is missing service

### ISSUE THREAD

**Issue by monotek** [bitnami/charts#3696]
**Which chart**:
mongodb 9.1.2

**Describe the bug**
The mongodb service is deactivated if architecture replicaset is used.
only the headless service is created.

**To Reproduce**
helm upgrade -i mongodb bitnami/mongodb --set architecture=replicaset

**Expected behavior**
mongodb service is available

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**

**Comment by juan131** [comment]
Hi @monotek 

That's the expected behaviour. When using MongoDB as a replicaset, you need to configure your MongoDB client with the hostnames of each MongoDB replica (instead of pointing them to a unique hostname that acts as loadbalancer). For instance, if you deploy the chart with 2 replicas, use the hostnames:

- **mongodb-0.mongodb-headless.default.svc.cluster.local**
- **mongodb-1.mongodb-headless.default.svc.cluster.local**

It's explained in the NOTES.txt:

```

To connect to your database, create a MongoDB client container:

    kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.4.1-debian-10-r0 --command -- bash

Then, run the following command:
    mongo admin --host "mongodb-0.mongodb-headless.default.svc.cluster.local,mongodb-1.mongodb-headless.default.svc.cluster.local," --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
```

**Comment by monotek** [comment]
Thanks for the info.
Whats the benefit doing it that way?
And if the mongodb client container is needed, why it is not part of the chart?

**Comment by juan131** [comment]
Hi @monotek 

> Whats the benefit doing it that way?

If you use a "normal" service so it acts as a load balance for MongoDB replicas, you don't have control about which requests go to a "primary" pod, and which ones to a "secondary" pod. The client "sees" the replicaset as a single MongoDB server.

However, it's very important to have control about what nodes can receive write requests (primary ones) and what nodes only receive read requests (secondary ones). That's the reason why you need to configure you client with all the hostnames. Then, by consulting the replicaset status, you can choose where to send write requests on the client side.

> And if the mongodb client container is needed, why it is not part of the chart?

The MongoDB client is totally optional. You can use it, or any other app running in the cluster with a MongoDB client library. That's why it's not included in the chart.

**Comment by monotek** [comment]
Thanks for clarification 😊
