### ISSUE TITLE
nats chart doesn't have support for leaf node block

### ISSUE THREAD

**Issue by c4m4** [bitnami/charts#3759]
**Which chart**:
nats

**Describe the bug**
nats chart doesn't have support for leaf node block, if you want to enable leaf node listening with this charts it's almost impossible

**Comment by marcosbc** [comment]
Hi @c4m4, we encourage users to submit PRs to implement new features, for them to be officially included faster than by conventional means. You can find the source code for the container image [here](https://github.com/bitnami/bitnami-docker-nats/tree/master/2/debian-10), while the source for the chart can be found in the current repo.

**Comment by javsalgar** [comment]
Reopening

**Comment by lukaszraczylo** [comment]
Still waiting.

**Comment by javsalgar** [comment]
Hi,

I'm afraid it is still in our backlog. I forwarded this to the team for reprioritization.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
