### ISSUE TITLE
[bitnami/mongodb] Unable to connect mongodb replicaset

### ISSUE THREAD

**Issue by anirvanr** [bitnami/charts#3799]
We are running Kubernetes cluster (v1.16.8) in our AWS using KOPS. We deployed **bitnami/mongodb (version: 9.1.2)** using below option

```
architecture=replicaset
replicaCount=3
externalAccess.enabled=true
externalAccess.service.type=LoadBalancer
externalAccess.service.port=27017
externalAccess.autoDiscovery.enabled=true
serviceAccount.create=true
rbac.create=true
```

We created DNS record for each ELB like this
```
mongodb-0-external.mydomain.com
mongodb-1-external.mydomain.com
mongodb-2-external.mydomain.com
```

Each URL is accessible using mongo client but when we set our application to this endpoint `mongodb-0-external.mydomain.com:27017,mongodb-1-external.mydomain.com:27017,mongodb-2-external.mydomain.com:27017`, it’s using k8s internal dns names that are not routeable since our application is running outside k8s cluster.

Sample log

```
[0m{"level":"fatal","timestamp":"2020-09-28T15:51:02.740Z","caller":"cmd/compile.go:37","message":
"Couldn't connect to the database server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\nAddr: mongodb-0.mongodb-headless.default.svc.cluster.local:27017, 
Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongodb-0.mongodb-headless.default.svc.cluster.local on 20.0.0.2:53: no such host\nAddr: mongodb-1.mongodb-headless.default.svc.cluster.local:27017, 
Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongodb-1.mongodb-headless.default.svc.cluster.local on 20.0.0.2:53: no such host\nAddr: mongodb-2.mongodb-headless.default.svc.cluster.local:27017, 
Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongodb-2.mongodb-headless.default.svc.cluster.local on 20.0.0.2:53: no such host\n"}
```

Does anyone have any suggestions for solution

Thanks.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

This is strange, could you show the output of `rs.status()` inside one of the nodes? Just to know how they registered themselves in the replicaset.

**Comment by hleal18** [comment]
Hi,

I think the option `clusterDomain` might be of help, setting it to the public domain you own. That way, mongodb nodes will be configured internally using that one instead of `cluster.local`, hence, returning those public DNS to the external client.

The catch is that you'll probably need to modify internal k8s dns to recognize and route internally the public domain you just configured. Also, you're going to end up with a public `cname` entry for each host similar to the following:
`mongodb-0.mongodb-headless.default.svc.<public domain>`.

There are also other details to take care of, mostly related to the fact that all mongo-nodes listen on port 27017. So you'll probably need multiple public ips, one for each internal replicaset-node or use tcp proxying mechanisms through SNI.

At least those were the problems I encountered when trying to accomplish the use case you're working on.

Not sure if there's a smoother way of accomplish that, as currently mongodb doesn't have a built-in option for mapping internal hostnames to external ones.

**Comment by kodeine** [comment]
@anirvanr were you able to solve this issue?

**Comment by rafariossaa** [comment]
@kodeine , this issue is quite old. If you are having some issues I would suggest you to create a new one.
