### ISSUE TITLE
[bitnami/wordpress] Increase the MaxRequestWorkers for wordpress helm deployment

### ISSUE THREAD

**Issue by Msarnaot** [bitnami/charts#3820]
**Which chart**:
Wordpress

**Describe the bug**
We are using the wordpress chart. Our wordpress instance keeps restarting with the following error message: 
"AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting". How can we increase this in a running wordpress instance on kube and stop it from restarting. When ever it restarts there seems to be about 1-2 mins of downtime.

**Comment by carrodher** [comment]
Hi, this is an error related to apache; the [`MaxRequestWorkers`](https://httpd.apache.org/docs/2.4/mod/worker.html) setting can be modified in the apache configuration but you will need to access to the WordPress container with `kubectl exec` and change the setting in the Apache configuration files (under _/opt/bitnami/apache/conf_) but this is not a long-term solution as the Apache configuration is not persisted and you will need to repeat the process when the pod is recreated.

Those are the occurrences of `MaxRequestWorkers` in the configuration files:
```console
$ ag 'MaxRequestWorkers' /opt/bitnami/apache/conf/
/opt/bitnami/apache/conf/original/extra/httpd-mpm.conf
25:# MaxRequestWorkers: maximum number of server processes allowed to start
32:    MaxRequestWorkers      250
41:# MaxRequestWorkers: maximum number of worker threads
49:    MaxRequestWorkers      400
58:# MaxRequestWorkers: maximum number of worker threads
66:    MaxRequestWorkers      400

/opt/bitnami/apache/conf/extra/httpd-mpm.conf
25:# MaxRequestWorkers: maximum number of server processes allowed to start
32:    MaxRequestWorkers      250
41:# MaxRequestWorkers: maximum number of worker threads
49:    MaxRequestWorkers      400
58:# MaxRequestWorkers: maximum number of worker threads
66:    MaxRequestWorkers      400
```

There are a couple of alternatives to solve the issue:

- The first one is to create your own custom WordPress image and use it in the chart. In order to create your custom image you can follow [this guide](https://github.com/bitnami/bitnami-docker-wordpress#customize-this-image), basically, you need to create a _Dockerfile_ extending from `bitnami/wordpress`, implement some substitutions via `sed` for example, and build this _Dockerfile_ by running `docker build`.

```Dockerfile
FROM bitnami/wordpress
LABEL maintainer "Bitnami <containers@bitnami.com>"

## Enable mod_ratelimit module
RUN sed -i -r 's/MaxRequestWorkers      250/MaxRequestWorkers      600/g' /opt/bitnami/apache/conf/original/extra/httpd-mpm.conf /opt/bitnami/apache/conf/extra/httpd-mpm.conf
RUN sed -i -r 's/MaxRequestWorkers      400/MaxRequestWorkers      600/g' /opt/bitnami/apache/conf/original/extra/httpd-mpm.conf /opt/bitnami/apache/conf/extra/httpd-mpm.conf
```

Please, take into account the above _Dockerfile_ is just an example, you will need to create your own _Dockerfile_ using the proper values for the `MaxRequestWorkers` substitutions. Once built the image (`docker build -t my-user/customWP:latest .` and pushed to a public repository like `docker.io`, you can use it in the chart by setting the following parameters 
```
helm install wordpress bitnami/wordpress --set image.repository=my-user/customWP --set image.tag=latest
```
In this way, the chart is going to use a Docker image containing your changes with a customs value for the `MaxRequestWorkers` parameter.

- The second option is to use the _values-production.yaml_ when installing the chart and using an NFS provider. You can find more information about this in https://github.com/bitnami/charts/tree/master/bitnami/wordpress#production-configuration

Note that [_values-production.yaml_](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values-production.yaml) includes a `replicaCount` of 3, **so there will be 3 WordPress pods**. As a result, to use the "/admin" portal and to ensure you can scale wordpress you need to provide a ReadWriteMany PVC, if you don't have a provisioner for this type of storage, we recommend that you install the [NFS Server Provisioner chart](https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner) (with the correct parameters, such as `persistence.enabled=true` and `persistence.size=10Gi`) and map it to an RWO volume.

Then, you can deploy WordPress chart using the proper parameters:
```
helm install wordpress bitnami/wordpress --set persistence.storageClass=nfs --set mariadb.master.persistence.storageClass=nfs
```

By increasing the number of pods, you can avoid reaching the `MaxRequestWorkers` limit.

**Comment by Msarnaot** [comment]
Hi @carrodher , thank you for your prompt response, it was very helpful. 
We were able to deploy with replica sets as well as using NFS server for ReadWriteMany which is great. 

However, we ran into a different issue with the latest 9.x.x chart. We are no longer able to install vim to update the wp-config.php file. I noticed in the release notes it was mentioned the file will no longer be editable. Can you recommend a way to go around that. 
We are looking to edit the site_url and home variables to point to /blog. This was a challenge we faced where we wanted to run wordpress on a subroute instead of a subdomain. So our ingress maps all requests to mydomain.com/blog to our wordpress service. The associated deployment has to have site_url and home set to /blog with all files inside the /blog directory for us to load wordpress correctly.

Please let me know if you have any recommendations for this, or if there is a setting we can utilize in our yaml. (I can also open a different ticket for this)

**Comment by carrodher** [comment]
Hi, I am glad you were able to solve the initial issue.

You're right, in the 9.X.X version the WordPress chart was moved to a non-root approach, which means the container and chart were modified to run as a non-root user. [Here](https://docs.bitnami.com/tutorials/work-with-non-root-containers/) you can find more information about non-root containers.

One of the non-root disadvantages is the user running the container, as a non-privileged user, can't install packages on the container so instead of `vim` you can try some of the already installed packages like `cat`, `grep`, `sed`, `echo`, and I/O redirection (especially append with `>>`), obviously it is not the most user-friendly way to edit files, but if you need to change small things it can works, for example:
```console
$ cat /bitnami/wordpress/wp-config.php
...
// disable pingbacks
add_filter( "xmlrpc_methods", function( $methods ) {
             unset( $methods["pingback.ping"] );
             return $methods;
           });
}

$ sed -i 's@add_filter@oetete@g' /bitnami/wordpress/wp-config.php

$ cat /bitnami/wordpress/wp-config.php
...
// disable pingbacks
my_new_string( "xmlrpc_methods", function( $methods ) {
             unset( $methods["pingback.ping"] );
             return $methods;
           });
}
```

Apart from that, you can revert the non-root behavior by setting the parameters `securityContext.runAsUser`, and `securityContext.fsGroup` to `0`, as `0` is the ID of the root user, deploying the chart with the above parameters it is going to be executed as root and you should be able to install `vim` and modify the files with that approach.
