### ISSUE TITLE
Spark 3.0 values.yaml for GPU

### ISSUE THREAD

**Issue by joehoeller** [bitnami/charts#3822]
Add values to set up Spark 3.0 for GPUs

**Comment by miguelaeh** [comment]
Hi @joehoeller ,
Could you provide more information about what are you requesting? Could you also share a link to the docs please?

**Comment by joehoeller** [comment]
_Please see the following_:

1. https://www.nvidia.com/en-us/deep-learning-ai/solutions/data-science/apache-spark-3/
2. https://www.youtube.com/watch?v=tGqEZYUqexY

**Comment by miguelaeh** [comment]
Hi @joehoeller ,
I am afraid we cannot distribute those libs due to licensing issues.
You can install GPU support following the steps at https://docs.bitnami.com/ibm/infrastructure/tensorflow-serving/configuration/enable-gpu-support/
Have in mind those steps are for VMs but they are similar for the container.

**Comment by joehoeller** [comment]
This is not GPU support for spark

**Comment by miguelaeh** [comment]
Could you please explain what do you mean?
