### ISSUE TITLE
[Mongodb] error with MongoError: not master with three replicas and connecting with headless service

### ISSUE THREAD

**Issue by avanichy25** [bitnami/charts#3830]
**Which chart**:
 9.1.0

**Describe the bug**
I am trying to connection nodejs application with mongo with three replicaset and using the headless service endpoint but getting an error added below:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1) UnhandledPromiseRejectionWarning: MongoError: not master
    at Connection.<anonymous> (xxxx/node_modules/mongodb/lib/core/connection/pool.js:450:61)
    at Connection.emit (events.js:315:20)
    at processMessage (xxxx/node_modules/mongodb/lib/core/connection/connection.js:384:10)
    at Socket.<anonymous> (xxxx/node_modules/mongodb/lib/core/connection/connection.js:553:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

**To Reproduce**
1.I have generated  a manifest for mongo helm template ../mongodb/ -f values-production.yaml --name-template mongodb 
2. after this, mongo was up and running and connected my application with headleass service: **mongodb-headless** but it dint work.

Note: with jut one replicacount everything worked well. Problem comes when use more than one.

**Expected behavior**
my application should connect with mongo even with 3 replicas.

**Version of Helm and Kubernetes**: 1.15x

- Output of `helm version`: 3.X

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"ba1ce4122d67b0f7399a41afbbd8a7258d22ecb8", GitTreeState:"clean", BuildDate:"2020-04-21T00:13:25Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by carrodher** [comment]
Hi, I am not sure if we can help you with this issue as it seems the chart is up and running without any issue. When using the replicaset architecture please, take into account the 1st replica is initially assigned the "primary" role, but any of the "secondary" nodes can become the "primary" if it is down, or during upgrades. Do not make any assumption about what replica has the "primary" role, instead configure your Mongo client with the list of MongoDB hostnames so it can dynamically choose the node to send requests.

Apart from that, is trying to connect to a "secondary" pod instead of the "primary", maybe there is an issue with the user/password if you upgraded from a previous deployment. Can you check in your app if it's something related to that?

**Comment by josepmorey** [comment]
How we can connect to the cluster without services? When using the replicaset architecture and don't want an external service the helm chart doesn't create any ClusterIp internal service. I think that is the question because **mongodb-headless** it's not made for connect to database

**Comment by carrodher** [comment]
The instructions should be shown when installing the chart, in the installation notes. You can see them at any time by running `helm get notes RELEASE_NAME`, for example in a installation from scratch (without any extra parameters, just `helm install mongodb bitnami/mongodb`:
```console
$ helm get notes mongodb
NOTES:


** Please be patient while the chart is being deployed **

MongoDB can be accessed via port 27017 on the following DNS name(s) from within your cluster:

    mongodb.default.svc.cluster.local

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database, create a MongoDB client container:

    kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.4.1-debian-10-r13 --command -- bash

Then, run the following command:
    mongo admin --host "mongodb" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/mongodb 27017:27017 &
    mongo --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD
```

You should be able to execute the same command and see the connection instruction depending on the parameters you used for installing the chart.

**Comment by josepmorey** [comment]
oooh!! yes, thanks!!

```
mongodb-0.mongodb-headless.<mynamespace>.svc.cluster.local
mongodb-1.mongodb-headless.<mynamespace>.svc.cluster.local
```

**Comment by avanichy25** [comment]
I am actually trying to connect my application using configmap with mongodb in aks. When i am specifying the service endpoint as mongodb-headless.<mynamespace>.svc.cluster.local then application complains about the ```MongoError: not master```. I have to explicitly define the primary mongodb-0.mongodb-headless.<mynamespace>.svc.cluster.local in the configmap to connect to primary as my mongodb-0 is primary right now but it doesn't solve the purpose of failover.

**Comment by carrodher** [comment]
Initially, the first replica is running the "primary" role, but any of the "secondary" nodes can become the "primary" if the first pod is down, or during upgrades.
We recommend not making any assumption about what replica has the "primary" role, instead configure your Mongo client with the list of MongoDB hostnames so it can dynamically choose the node to send requests.

I don't know the implementation of your application and if this is possible, but anyway, just for testing purpose hardcoding the service of the primary replica should work (although it is not a long-term solution due to the above limitation)
