### ISSUE TITLE
[bitnami/apache] Get the server static content from a private git repository

### ISSUE THREAD

**Issue by cuttingedge1109** [bitnami/charts#3894]
**Which chart**:
bitnami/apache

**Is your feature request related to a problem? Please describe.**
I am expecting to get the server static content from a private git repository.

**Describe the solution you'd like**
I am expecting to get the server static content from a private git repository.
I am using the cloneHtdocsFromGit.enabled=true and it works well but only for public repos now.

Thank you.

**Comment by andresbono** [comment]
Hi @cuttingedge1109, we don't fully support that feature yet. It should be possible to modify the chart so that the `git-clone-repository` can mount a secret containing an ssh private key.

Another option would be that you encode the credentials in the https url like `https://USERNAME:TOKEN@yourgitserver.com` but this method is strongly discouraged for security reasons.

Contributions are more than welcome. Would you like to open a PR to implement the first method if it works for you?
