### ISSUE TITLE
[external-dns] Will the external dns application see the environment variables I pass in with extraEnv?

### ISSUE THREAD

**Issue by red8888** [bitnami/charts#3905]
Im sorry, perhaps this is obvious but I want to confirm

It seems external DNS can be 100% configured by env vars? https://github.com/kubernetes-sigs/external-dns/issues/1798

First I want to confirm that vars I set via extraEnv will be consumed by the application (dont see why they would not, but want to confirm)

And my second question is, does this mean this chart could literally just be a super thin wrapper that allows you to inject arbitrary env vars and create arbitrary secrets? I was just wondering because seems like it would be trivial to maintain a chart like that if that was the case.

If you can configure 100% of the app with env vars then the only thing youd need in a helm chart is the ability to set any env vars you want and the ability to decide which ones should be created and mounted as secrets

If you did that you wouldnt need keep this thing up to date with the app's config. This chart would not even need to be aware of the apps arguments! If the developers have already done the work of factoring the application to be configured by env vars then I feel like passing in args through the helm chart kind of creates more work for you and also means if you forget an arg or a new arg is added you have update this thing, open a PR in this repo, etc- seems like an arbitrary/redundant layer of configuration no?

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback! Indeed, the extraEnvVars would be consumed by the application. It would also make sense to change all the args to env vars in order to make it consistent. About leaving it blank and have the user put all the env vars, that would work for advanced users but I have my concerns about non-expert users. Wouldn't it become a bit complex for users? Plus, that would be a major change that could be problematic for other users that are already using the charts.
