### ISSUE TITLE
[bitnami/logstash] Liveness / readiness probes fail on `containerPorts` override

### ISSUE THREAD

**Issue by sc250024** [bitnami/charts#3915]
**Which chart**:

**bitnami/logstash**

**Describe the bug**

Putting the `monitoring` port definition in the `containerPorts` section of the `values.yaml` file leads to a potential override.

```yaml
containerPorts:
- name: monitoring
  containerPort: 9600
  protocol: TCP
```

The problem with this it can be overridden, causing the deployment to continually fail if the user specifies additional `containerPorts` entries, and doesn't include the `monitoring` port.

**To Reproduce**

Use the following `values.yaml` file:

<details>
<summary>values.yaml</summary>

```yaml
containerPorts:
- name: beats
  containerPort: 5044
  protocol: TCP
- name: http
  containerPort: 8443
  protocol: TCP
input: |
  beats {
    host => "0.0.0.0"
    port => 5044
  }
  http {
    host => "0.0.0.0"
    port => 8443
  }
metrics:
  enabled: true
output: |
  elasticsearch {
    hosts => ["${ELASTICSEARCH_HOST}:443"]
    ilm_enabled => false
    manage_template => true
  }
```

</details>

And see that the deployment will fail because I _have not_ included the monitoring port definition.

**Expected behavior**

The `monitoring` port should be specified in `sts.yaml` separately so that it can't be overridden.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

The monitoring port should go here: https://github.com/bitnami/charts/blob/master/bitnami/logstash/templates/sts.yaml#L62-L64, and the `containerPorts` should specify any _additional_ ports.

**Comment by javsalgar** [comment]
Hi,

I agree that this values should not be overridden and instead `containerPorts` should be interpreted as `extra container ports`. I will open a task for evaluation. As soon as we have more news, we will update the ticket.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
