### ISSUE TITLE
Support for IngressClass Object in newer versions of k8s

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/charts#3919]
**Which charts**:
[bitnami/nginx-ingress-controller]
[bitnami/contour]
[bitnami/kong]

**Is your feature request related to a problem? Please describe.**

Using the chart it is only possible to differentiate between two ingresses via an Annotation.
Newer Kubernetes versions support differentiating ingress definitions by IngressClass.

[https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)

**Describe the solution you'd like**
Implement either a flag in the helm chart which enables new or old behaviour
or make it dependend on the running Kubernetes version which way the ingressClass gets deployed.

As Annotation or as Object.

**Comment by andresbono** [comment]
Thanks for raising this new feature to our attention, it looks very interesting although we haven't explored it in depth yet. Are you already using IngressClass manifests in your clusters?

**Comment by Cellebyte** [comment]
No I'm not I wanted to first support it in the Helm Charts.
But I could test how they behave and start on implementing them in the helm charts.

**Comment by andresbono** [comment]
That would be great, @Cellebyte ❤️ Thanks again for your all your help and contributions to this project!

**Comment by Cellebyte** [comment]
@andresbono I don't think it should be stale :)

**Comment by andresbono** [comment]
Setting <kbd>on-hold</kbd> label to avoid noise from the stale bot.

**Comment by muffl0n** [comment]
Would be great to also have it in chart "nginx".

**Comment by discostur** [comment]
@andresbono IngressClass support is also missing on [bitnami/kibana] ... just wanted to deploy it on a newer k8s cluster but it doesn't work;

**Comment by carrodher** [comment]
Thanks for reporting it. Would you like to create a PR adding it?

**Comment by discostur** [comment]
@carrodher looks like this PR should fix it: https://github.com/bitnami/charts/pull/8536  ;)

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
