### ISSUE TITLE
[bitnami/logstash] Support for persistence

### ISSUE THREAD

**Issue by sc250024** [bitnami/charts#3932]
**Which chart**:

**bitnami/logstash**

**Is your feature request related to a problem? Please describe.**

No, just a feature request.

**Describe the solution you'd like**

The old `stable/logstash` chart (https://hub.kubeapps.com/charts/stable/logstash) has an option for persistence (`persistence.enabled`).

As I understand it, the attached volume is useful in case Logstash needs to be restarted, and there are still queued items that have not yet been written to some `output`. This is referred to as their [Persistent Queues](https://www.elastic.co/guide/en/logstash/current/persistent-queues.html) feature.

With persistence, that data is not lost. This might have been made redundant, so please let me know if this is not needed anymore.

**Comment by marcosbc** [comment]
Related issue: #6150

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
