### ISSUE TITLE
[bitnami/mongodb-sharded] Arbiter always produces log errors

### ISSUE THREAD

**Issue by TheHunter** [bitnami/charts#3977]
**Which chart**:
[bitnami/mongodb-sharded], version 2.1.3

**Describe the bug**
After installation of this chart, I see some errors on the **arbiter** POD log, examples:

level=error msg="Failed to get replSetGetConfig: (Unauthorized) not authorized on admin to execute command { replSetGetConfig: 1, lsid: { id: UUID(\"0fe48dee-9860-44b0-941d-6e952a6da439\") }, $db: \"admin\", $readPreference: { mode: \"primaryPreferred\" } }." source="replset_conf.go:115"

level=error msg="Failed to get oplog timestamps status: (Unauthorized) not authorized on local to execute command { find: \"oplog.rs\", comment: \"/home/nurlan/go/src/github.com/percona/mongodb_exporter/collector/mongod/oplog_status.go:85\", filter: {}, limit: 1, singleBatch: true, sort: { $natural: -1 }, lsid: { id: UUID(\"0fe48dee-9860-44b0-941d-6e952a6da439\") }, $db: \"local\", $readPreference: { mode: \"nearest\" } }" source="oplog_status.go:149"

These errors produces a continuous restart of arbiter PODs, but I don't understand well where's the real problem.

**To Reproduce**
1. use this values file (I must have changed the file extension, otherwise I couldn't be loaded)
[values.txt](https://github.com/bitnami/charts/files/5361296/values.txt)

2. create a namespace:
   mongo

3. execute this command in order to install this chart
  helm install mongo-store -f values.yml bitnami/mongodb-sharded -n mongo

4. go to Arbiter PODs, and see logs (metrics), in order to see authentication errors

**Expected behavior**
authentication must work 

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.14", GitCommit:"d2a081c8e14e21e28fe5bdfa38a817ef9c0bb8e3", GitTreeState:"clean", BuildDate:"2020-08-13T12:33:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platfo
rm:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"37c06f456fdb4d25e402b5fbcb72cd6a77a021a9", GitTreeState:"clean", BuildDate:"2020-09-18T21:59:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platfor
m:"linux/amd64"}
```

**Additional context**
this error occurs with the "root" user, as we know, this is the admin user for the cluster.

I've tried to add more roles (**userAdminAnyDatabase**, **clusterAdmin**) thinking It was the solution but nothing:

![image](https://user-images.githubusercontent.com/992665/95682257-9c708180-0be4-11eb-8a02-d97c897ddbad.png)

**Comment by dani8art** [comment]
Hi @TheHunter thanks for opening the issue, I can confirm the errors appear in the logs, I was doing some test and investigations trying to modify the connection URI in the metrics container without success.

```
          command:
            - sh
            - -ec
            - |-
              #!/bin/sh
              {{- if $.Values.usePasswordFile }}
              export MONGODB_ROOT_PASSWORD="$(cat "${MONGODB_ROOT_PASSWORD_FILE}")"
              {{- end }}
              /bin/mongodb_exporter --mongodb.uri mongodb://root:`echo $MONGODB_ROOT_PASSWORD | sed -r "s/@/%40/g;s/:/%3A/g"`@localhost:{{ $.Values.service.port }}/admin?connect=direct {{ $.Values.metrics.extraArgs }}
```

We just created an internal task to fix the issue and included it in our backlog. Unfortunately, due to we are a small team and regarding priorities and internal milestones, we can’t provide an ETA. Nevertheless, it will be considered for future application versions.

**Comment by TheHunter** [comment]
Hi @dani8art 
thanks so much.

So let's stay tuned for this ifix.

Hunter

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
