### ISSUE TITLE
[bitnami/node] NodeJS chart seems oddly tailored to a specific use case

### ISSUE THREAD

**Issue by kav** [bitnami/charts#4013]
Hey folks, the NodeJS chart seems oddly tailored to a specific use case.
It defaults to fetching a git repository and installing mongo.
These seem like interesting features but maybe not as default?

Love to hear some thoughts or history on that before I step in something filing issues and PRs to simplify the default deployment a bit.

**Comment by FraPazGal** [comment]
Hi @kav,

Thanks for reaching out! We use mongodb as the default database but we allow the use of an external one. It is true that we default to cloning an app from a git repo. We always welcome contributions and additions to our chart, what changes do you have in mind?

**Comment by kav** [comment]
I love the make the mongo db stuff completely optional. Right now even disabling it still leaves some fussing about external dbs and some spurious environment variables. For context my use cases don't have a mongo server and use pre-baked app images. I do like the option to enable those features of course but it just seems a bit strange by default

**Comment by juan131** [comment]
Hi @kav 

We provided the option to install the chart cloning your node application from a GIT repository as a way to automate deploying your code. That said, you have different alternatives to do so.

For instance, you can build your own Docker image based on the [Bitnami Node image](https://github.com/bitnami/bitnami-docker-node) and add your custom code during the building process. Then, you can simply use the `image.registry`, `image.repository` and `image.tag` parameters to replace the default image with your custom one.

Regarding MongoDB, we added it as an **optional** dependency since it's a common database used on Node applications. That said, you should be able to disable it.

> Right now even disabling it still leaves some fussing about external dbs and some spurious environment variables

Could you please specify what parameters or env. vars do you refer to? Could you please also share the values.yaml you're using to install the chart? Thanks in advance

**Comment by kav** [comment]
Yep, I'm updating the image tags and that's all good. Certainly not my first rodeo, even with the bitnami charts, minideb and whatnot. As for values I was testing with
```yaml
getAppFromExternalRepository: false
mongodb:
  install: false
```
This fails to deploy since the `externaldb.secretName` doesn't exist, which for my use case shouldn't exist as there is no mongodb.

**Comment by juan131** [comment]
Hi @kav 

I just created a PR adding a new parameter  `externaldb.enabled` that you can set to `false` to disable using a external database when using MongoDB as subchart is also disabled.
