### ISSUE TITLE
I deploy tensorflow-resnet in my kubernetes, but i dont know how to  deploy machine learning model in my pod of "tensorflow-resnet"  .Could you help me ? please.

### ISSUE THREAD

**Issue by yangjinlogic** [bitnami/charts#4020]
I deploy tensorflow-resnet in my kubernetes, but i dont know how to  deploy machine learning model in my pod of "tensorflow-resnet"  .Could you help me ? please.

**Comment by javsalgar** [comment]
Hi,

Currently, there's an init container that downloads the resnet model

```
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ -f /seed/.initialized ]; then
                echo "Already initialized. Skipping"
              else
                curl -o /seed/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz
                cd /seed/ && tar -xzf resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz --strip-components=2
                rm resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz
                touch /seed/.initialized
              fi
```

Could you explain your use case? We may need to extend the chart with more features.

**Comment by yangjinlogic** [comment]
@javsalgar 
okay,   I deploy tensorflow-resnet successful,the command is：
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-release bitnami/tensorflow-resnet

but  I dont know how to deploy my model,and  the parameters dont provide more information about it

**Comment by javsalgar** [comment]
Hi,

I believe that we need to extend the charts with more options so you can deploy more models. I will open a task for adding more of our standardizations to this chart. This would allow you to add more init containers, sidecars, volumes and other features so you can use your custom models.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
