### ISSUE TITLE
[bitnami/redis] Cross cluster High availability

### ISSUE THREAD

**Issue by skyrain** [bitnami/charts#4081]
**Which chart**:
bitnami/redis

**Is your feature request related to a problem? 
I am working on Harbor HA, which requires to set up a high available Redis. And it is a normal requirement  that we should achieve cross cluster Redis HA. Thus, when on cluster entirely down, the backup Redis can be brought up.

**Describe the solution you'd like*
Provide an optional field in chart to allow cross cluster replication for Redis. By default 
the slave is in same cluster, if we can set slave in another cluster, then we can achieve cross cluster HA.

**Comment by javsalgar** [comment]
Hi,

Just to clarify. When you mean cross-cluster you mean to deploy more than one redis cluster or to have one redis cluster with sentinel enabled? We have support for the latter but not the former. For the latter you could set the value `redis.sentinel.enabled=true`.

**Comment by skyrain** [comment]
> Hi,
> 
> Just to clarify. When you mean cross-cluster you mean to deploy more than one redis cluster or to have one redis cluster with sentinel enabled? We have support for the latter but not the former. For the latter you could set the value `redis.sentinel.enabled=true`.

Hi, "cross-cluster" I mean that to use [bitnami/redis] chart to deploy redis master in one cluster, and to deploy redis slave in another cluster. Thus, I will have the high availability cross cluster. If master cluster is done, I can switch to backup cluster recdis (if redis promote required).

**Comment by miguelaeh** [comment]
Hi @skyrain ,
Thank you very much for the suggestion.
I will create a task to evaluate this request. We will update this thread when we have news.
Regards.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
