### ISSUE TITLE
[bitnami/redis-cluster] Implement redis cluster using Deployment instead of StatefulSet

### ISSUE THREAD

**Issue by ozooxo** [bitnami/charts#4088]
**Which chart**:
https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster/ version 3.2.8

**Is your feature request related to a problem? Please describe.**
The current bitnami/redis-cluster is [using `StatefulSet`](https://github.com/bitnami/charts/blob/aa6bfb8ca9ce86fa6f88531f1f8ccea54c607e71/bitnami/redis-cluster/templates/redis-statefulset.yaml#L1). However, there's a known issue that `StatefulSet` is not getting along with skaffold (https://github.com/GoogleContainerTools/skaffold/issues/3219, https://github.com/kubernetes/kubernetes/issues/68737) so your manifest can only be deployed once using skaffold and will fail the second time.

Also notice that this Helm chart is very complicated, while https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml is a very simple setup with 6 nodes.

In dev environments, we may want a Redis running in cluster mode. On the other hand, we'd prefer easy setup, compatible with skaffold, and with less security/reliability needs. To have a Kubernetes manifest to mirror what the [docker-compose](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) will be very useful for this kind of setup.

**Describe the solution you'd like**
We tried to setup something like this. Basically we create 6 `Service`s, 6 `Deployment`s, 6 `PersistentVolumeClaim`s, and one `Job` with 6 initContainers to make sure it executed when the 6 Redis `Deployment`s are up and running.

But it seems not at all as easy as the docker-compose case:

* We see the error `/opt/bitnami/scripts/librediscluster.sh: line 189: /bitnami/redis/data/nodes.sh: Permission denied` in nodes, which can be fixed by your same `securityContext: fsGroup: 1001` and `securityContext: runAsUser: 1001` (which you don't need to specify by `-u` in docker-compose).
* We then see an error in redis-cluster-creator job `[ERR] Node 172.20.190.14:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0. Could not connect to Redis at 10.14.206.58:6379: No route to host, ...`. Seems resolvable by `flushall` and `cluster reset` but we resolved it to simply drop uses `PersistentVolumeClaim` and transit storage (since it is for dev). 

We are currently facing two problems:

* Job cannot be skaffold deployed the 2nd time unless you `kubectl delete job redis-cluster-creator`.
* Connection errors out with [our client library](https://pypi.org/project/rediscluster/). Some search shows that it may relate to `cluster-require-full-coverage`.

```
  File "/usr/local/lib/python3.7/site-packages/rediscluster/pipeline.py", line 158, in send_cluster_commands
    node = self.connection_pool.get_node_by_slot(slot)
  File "/usr/local/lib/python3.7/site-packages/rediscluster/connection.py", line 338, in get_node_by_slot
    return self.get_master_node_by_slot(slot)
  File "/usr/local/lib/python3.7/site-packages/rediscluster/connection.py", line 333, in get_master_node_by_slot
    return self.nodes.slots[slot][0]
KeyError: 9935
```

We'll definitely work deeper on our side to fix our bugs. But if you (with much more experience working with Redis/cluster mode) can provide a simple example of Kubernetes manifest w/ minimal setup/`Deployment` we can refer to, that will be great. Thanks!

**Describe alternatives you've considered**

**Additional context**

**Comment by miguelaeh** [comment]
Hi @ozooxo ,
If the main reason to use a stateful set is to have a different volume per pod. Using a deployment will not be trivial since you can create a PVC per pod at the first run, but in case you want to add a new node you will need to manually create another one so the number of nodes would not be customizable.

>We see the error /opt/bitnami/scripts/librediscluster.sh: line 189: /bitnami/redis/data/nodes.sh: Permission denied in nodes, which can be fixed by your same securityContext: fsGroup: 1001 and securityContext: runAsUser: 1001 (which you don't need to specify by -u in docker-compose).

This happens because the volumes are not configured by default to own user `1001` that is the one used by the docker image by default. Just setting `fsGroup` should be enough.

> We then see an error in redis-cluster-creator job [ERR] Node 172.20.190.14:6379 is not empty. Either the node already knows other nodes (check with CLUSTER NODES) or contains some key in database 0. Could not connect to Redis at 10.14.206.58:6379: No route to host, .... Seems resolvable by flushall and cluster reset but we resolved it to simply drop uses PersistentVolumeClaim and transit storage (since it is for dev).

And this error happens when you try to initializa the cluster twice, maybe the first time failed and some nodes already know others so it reach this "corrucpt" state. The easier way to solve it is to delete the PVC as you mention in case you don't have any data.

> Job cannot be skaffold deployed the 2nd time unless you kubectl delete job redis-cluster-creator

Could you share the error? Is there an error with the job or is it an error with skaffold itself?

> Connection errors out with our client library. Some search shows that it may relate to cluster-require-full-coverage.

Regarding this issue it is difficult to know what could be happening with that information only. Not sure if realted but in cluster mode, your client must support to be redirected to the master when it executes a write operation.

**Comment by ozooxo** [comment]
@miguelaeh , Thanks for your quick and helpful implementations.

> to have a different volume per pod. ... you will need to manually create another one so the number of nodes would not be customizable.

The main reason I am asking this, is your [docker-compose](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) also cannot easily scale up/down. The same reason as that docker-compose is useful in development, a fixed redis cluster mode may be useful in a dev k8s environment. Since a lot of people are developing k8s w/ skaffold, it will be useful if that k8s manifest can be compatible with that (need to use `Deployment`). Definitely, it depends on whether you agree with me that will be useful.

> Could you share the error? Is there an error with the job or is it an error with skaffold itself?

Right now there are a lot of noises in my setup (within a complicated enterprise pipeline) and I'll need to clean it up. Highly possible it is my own bug. Since using your [bitnami/redis-cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster) everything works perfectly on my side without any error, just I can't use it with skaffold, I would like to ask some general questions:

* In your [docker-compose](https://github.com/bitnami/bitnami-docker-redis-cluster/blob/master/docker-compose.yml) you don't need any special configuration. But in your [bitnami/redis-cluster](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster) you need to override [redis-default.conf](https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/configmap.yaml), and you need [a special command to exec](https://github.com/bitnami/charts/blob/aa6bfb8ca9ce86fa6f88531f1f8ccea54c607e71/bitnami/redis-cluster/templates/redis-statefulset.yaml#L95-L102). What's the reason behind it?

**Comment by miguelaeh** [comment]
>The main reason I am asking this, is your docker-compose also cannot easily scale up/down. The same reason as that docker-compose is useful in development, a fixed redis cluster mode may be useful in a dev k8s environment. Since a lot of people are developing k8s w/ skaffold, it will be useful if that k8s manifest can be compatible with that (need to use Deployment). Definitely, it depends on whether you agree with me that will be useful.

Change to deployment is not a trivial thing, due to the scale-up and down I explained before, anyway, we want at some point to get rid of the statefulset in all the charts due to upgrade issues. I will add a note about this into that task.

> In your docker-compose you don't need any special configuration. But in your bitnami/redis-cluster you need to override redis-default.conf, and you need a special command to exec. What's the reason behind it?

About the configmap it is to provide the users with a way to extend the defult configuration. That configmap will be mounted as the default configuration and users can provde additional configuration that will be append to that file. The file is basically the default file that is created by default by redis.
The special command is just a patch to maintain backwards compatibility from previous changes.

>Looks like in your docker-compose you want the cluster initializer to run after all other nodes are on. But in your bitnami/redis-cluster you seems no longer need that constrain (I see no initContainer to validate that's the case). Why?

In the chart the cluster is created by a job that has the proper code to wait for all the pods to be up.

**Comment by ozooxo** [comment]
Thanks @miguelaeh ! 

Feel free to close this feature request, as you are committing to get rid of the `StatefulSet` for other reason. And if you can put a link here on that task that will be great. Thanks again!

**Comment by miguelaeh** [comment]
Hi @ozooxo ,
We can share a link since it is on a private board. But I will add this issue to the task.
Regards

**Comment by stephaneetje** [comment]
Hello,
Is there any update on this ? Actually, with one master, each deployment makes a downtime with redis as it kills the master before creating the new one. I can't use it in production because of that.

**Comment by miguelaeh** [comment]
Hi guys, there is no progress on this, and actually, it doesn't look possible to use a deployment since the Redis cluster needs different volumes for each replica and needs to connect to the rest of the pods. Using a deployment it won't be possible to perform those actions, so it wouldn't add any advatanges.

**Comment by stephaneetje** [comment]
It is possible to mount the pvc on 2 pods by changing the access mode of the pvc :
```
ReadWriteOnce -- the volume can be mounted as read-write by a single node
ReadOnlyMany -- the volume can be mounted read-only by many nodes
ReadWriteMany -- the volume can be mounted as read-write by many nodes
```
So `ReadWriteMany` should do the trick, then we might be able to use a deployment for the master.

**Comment by miguelaeh** [comment]
I am not familiar with `skaffold`, but I wouldn't say it is unusable. 
If the issues you are facing are for upgrading, you can always mount the old volumes on a new deployed Redis cluster nodes and force the cluster re-creation.

**Comment by stephaneetje** [comment]
So everytime there is a chart upgrade we will have to manually do it ? It is pretty bad, what's the point using k8s/helm if we can't rolling update the master, and have to do all the upgrades manually.

Actually i can only use redis-cluster on non production env as we always loose the master for few second when upgrading...

**Comment by miguelaeh** [comment]
You can try to delete the statefulset without deleting the pods and then execute helm upgrade:

1. 
```console
kubectl delete sts --cascade=false <name>
```

2. Execute helm upgrade

**Comment by stephaneetje** [comment]
That won't work as i'm using argocd to deploy

**Comment by miguelaeh** [comment]
@stephaneetje could you please explain your whole scenario and which are the issues you face?

**Comment by stephaneetje** [comment]
Hello @miguelaeh 
I'm using argocd to deploy helm charts.
Every time i upgrade redis helm chart, the master kills itself before popping the new one, which creates a downtime and drop connections to redis for a few seconds.
This is the only chart with which i'm facing this issue.

**Comment by miguelaeh** [comment]
So, the problem is that when you upgrade the cluster, there is some downtime for the master right? 
I guess that downtime is only for writing right? As all the pods won't be restarted at the same time, there should always be a replica from which you can read.
In redis-cluster your client will be redirected to the node containing the proper slot, so, in case the master is down, read operations will be sent to the replica.
Having no downtime at all is pretty difficult, so if you cannot assume those seconds during the maintenance for the upgrade, I am afraid you will need to find other ways of doing it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
