### ISSUE TITLE
[bitnami/redmine]

### ISSUE THREAD

**Issue by Jacq** [bitnami/charts#4185]
**Which chart**:
[bitnami/redmine]
**Is your feature request related to a problem? Please describe.**
I think is not possible to configure more than one mail receiver inbox. Setting multiple mail receiver configurations for different email inboxes will be great, so different project, task, categories... could be assigned by email inbox.

**Describe the solution you'd like**
Modify the settings related to mailReceiver to accept an array of entries.

**Describe alternatives you've considered**
Configuration using configmap and additional sidecars (one for account) to receive emails using a rake task.

**Additional context**
The official solution proposes the use of rufus-scheduler where you can setup different rake tasks one for each email: https://www.redmine.org/projects/redmine/wiki/redminereceivingemails#

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this feature. I am creating an internal task in our backlog to analyze your request. I can't give you an estimation on when this would be available.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/redmine#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
