### ISSUE TITLE
[bitnami/logstash] Provide a way to install custom plugins

### ISSUE THREAD

**Issue by yangvipguang** [bitnami/charts#4209]
how  to  install plugins in logstash docker

**Comment by juan131** [comment]
Hi @yangvipguang 

This might not be best repository to ask about installing plugins in the Docker image. Could you please open an issue in the repository below instead? Thanks in advance.

- https://github.com/bitnami/bitnami-docker-logstash

**Comment by yangvipguang** [comment]
@juan131   ok thanks rely。I have  fixed that  based on bitnami logstash docker with copy  offline plugins. But I suggest that this option of  add  plugins  should be added to Helm Chart  based on initContainer or other methods.

**Comment by juan131** [comment]
Hi @yangvipguang 

> But I suggest that this option of add plugins should be added to Helm Chart based on initContainer or other methods.

Well.. That's a different request: I'll rephrase the issue to reflect that. I agree that we could implement a way to automatically specify the list of plugins to be installed during the initialization.

I'll create an internal task to work on adding this feature to the [Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/logstash). We'll keep you updated about our progress.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by pierrecabriere** [comment]
You can set the `LOGSTASH_PLUGINS` env var with the `extraEnvVars` option to install plugins at container initialization

**Comment by juan131** [comment]
Hi @zentavr 

This might not be best repository to ask about installing plugins in the container image. Could you please open an issue in the repository below instead? Thanks in advance.

- https://github.com/bitnami/containers/issues
