### ISSUE TITLE
Add master and replica labels

### ISSUE THREAD

**Issue by alanroche** [bitnami/charts#4232]
**Which chart**:
bitnami/redis-cluster

**Is your feature request related to a problem? Please describe.**
We are deploying bitnami/redis-cluster into a GKE kubernetes cluster which is distribute over 3 availability zones.
Replica and Master pods are not differentiated in any way. This makes Zonal affinity or anti affinity very difficult. 
Also, there is no label showing which master a replica is associated with (This might not even be possible I am thinking, but anyway). This means we cannot have an anti affinity to try and place the replica in a zone different to the master

**Describe the solution you'd like**
- Master pods would have something like a "master" label
- Replica pods would have something like a "replica" label
- Replica pods would have something like "replica-of" label referencing the master pod. I suspect this might not be possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by dani8art** [comment]
Hi @alanroche as per the way we are creating the cluster in this chart, I can't see a way to implement the suggested feature, the thing is:

- We are using only one statefulset to deploy the cluster nodes,
- Before nodes (pods) are created, a job is the one in charge of creating the cluster and assigning the roles to each of the pods.

In order to add the labels, we should know previously what are going to be the roles for each of the nodes, in this case, we should refactor the templates and use one statefulset per role but we will still be missing the `replica-of` label. 

I will open an internal task in order to discuss the best approach to implement this feature, due to priorities and internal milestones we can't give you an ETA. However, if it is important for you and have a chance to create a PR we would be happy to handle it.

**Comment by dani8art** [comment]
Hi @alanroche,

After some internal researches and discussion, we finally discovered that this feature can't fit in this chart. This decision is based on the proper concept of Redis cluster architecture which means there is no fixed master role nor slave so they can change during a failover and then labels will be pointing to wrong masters or slaves. 

I can see two approaches in order to fit your requirements: 

1. Add such a number of masters and provide an affinity that can ensure you have at least one master per zone, This would a matter of playing with those values.

2. Why do you need `bitnami/redis-cluster`? I mean, it is a requirement or just an election. You can use `bitnami/redis` which already implements the separation between master and slave and high availability is solved by sentinel as well. I think this could be a good solution for you.

Thank you so much for your feedback!
