### ISSUE TITLE
Include Flower with Airflow deployment

### ISSUE THREAD

**Issue by jibsonline** [bitnami/charts#4244]
**Which chart**:
Airflow

**Is your feature request related to a problem? Please describe.**
Need support for flower https://flower.readthedocs.io/en/latest/ like how the official helm airflow chart has 

**Describe the solution you'd like**
A deployment and ingress for flower

**Describe alternatives you've considered**
https://github.com/helm/charts/tree/master/stable/airflow/templates/flower

**Comment by dani8art** [comment]
Hi @jibsonline, we are improving our chart for airflow https://github.com/bitnami/charts/pull/4069 and we are evaluating to include flowers, but it would be in a second phase.

However, we are open to contributions if you have a chance and would like to contribute to the `bitnami/airflow`, we will be happy to handle the PRs. Thank you so much for your feedback!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
