### ISSUE TITLE
[grafana] Grafana in HA Multi-Attach error

### ISSUE THREAD

**Issue by alesanmed** [bitnami/charts#4257]
**Which chart**:
grafana-3.4.7

**Describe the bug**
When I set the replicas of grafana pod to more than one, the first pod is correctly created but the following ones are stuck in `ContainerCreating` with the error:

```
Multi-Attach error for volume "pvc-5a24cad3-b87c-4e3b-8064-77d11d1c3ccc" Volume is already used by pod(s) grafana-6fd8cf5c66-gj75d
```

That PVC refers to the data volume

**To Reproduce**
1. Enable persistence in the chart
2. Deploy the chart with > 1 replicas

**Expected behavior**
All pods should be correctly created

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I don't know if I should disable persistence when running grafana in HA because the external database is enough or not.

**Comment by FraPazGal** [comment]
Hi @alesanmed!

Like it is said in our README, HA cannot function without an external database and having the second pod stuck on `ContainerCreating` is intentional. That way, users will easily realise that HA will not be working with the default configuration.

I would say that there is no need to have persistence enabled in a HA configuration as the data will not be stored in the default place:

> From [Grafana documentation](https://grafana.com/docs/grafana/latest/administration/set-up-for-high-availability/#configure-multiple-servers-to-use-the-same-database):
> [...] the default embedded SQLite database will not work [...] Grafana will now persist all long term data in the database.

**Comment by alesanmed** [comment]
@FraPazGal Sorry maybe I expressed myself wrong. I do have the external database configured as the documentation says, the only thing I didn't know was if I should also disable persistence or not. Thank you! And one more thing. Since I had both persistence and database enabled, will my data be in the database or the local storage prevales over database? (Just to know if I'm going to lose the data when I disable persistence).

**Comment by FraPazGal** [comment]
Hello @alesanmed,

Ah sorry, I misunderstood. Yes, you would need to disable persistence and since you configured grafana to use an external database it shouldn't have used the default sqlite3 at any point. Nevertheless, I would recommend to make a backup of the internal sqlite3 database present at `/opt/bitnami/grafana/data/grafana.db` (if it exists) to avoid any data loss.

**Comment by alesanmed** [comment]
Thanks so much @FraPazGal !! Closing the issue :)

**Comment by odorT** [comment]
Hi. I encountered the same issue lately. in our case we install multiple plugins and these plugins are not stored in database as it seems from pod logs. What is advised in this case (store data in database and plugins in pvc maybe?) ?
