### ISSUE TITLE
Error: requirements.lock is out of sync with requirements.yaml

### ISSUE THREAD

**Issue by busla** [bitnami/charts#4350]
**Which chart**:
Airflow 6.7.1

**Describe the bug**
Deploying the chart to our onpremise Gitlab instance (v13.5) using Autodevops fails:
```sh
Error: requirements.lock is out of sync with requirements.yaml
```
I understand this is a Helm issue and since Gitlab still uses Helm v2 and v3 is only available in their beta `auto-deploy-image`. It will be added as stable in the upcoming major release v14.

Since we are not comfortable migrating to an unstable beta release it would be very appreciated if Bitnami could continue to maintain support for Helm v2 in the the latest version of the Chart.

Deploying the image directly to the cluster using Helm v3 remotely works perfectly.

**Comment by carrodher** [comment]
As Helm 2 EOL is effective today as well as the `stable` repository deprecation, we are migrating our charts from `apiVersion: v1` (installable by Helm 2 and Helm 3) to `apiVersion: v2` (only installable by Helm 3).
This change is done as part of a major version bump and Airflow is not yet migrated, so **this issue should not be related to that**. You can find more information about this process at https://github.com/bitnami/charts/issues/3867.

The `Error: requirements.lock is out of sync with requirements.yaml` error sounds familiar to me, according to https://github.com/helm/helm/issues/2033 it seems some specific Helm 2 versions doesn't build property the dependencies, or maybe it was because the `helm dep update` where the _requirements.lock_ is generated was executed with Helm 3 and the `helm dep build` with a specific version of Helm 2. It's weird this issue was not faced previously as there are no recent changes related to that.

**Comment by busla** [comment]
Thanks for clarifying!

This makes sense. Gitlab is using `Helm v2.16.9` and according to https://github.com/helm/helm/issues/2033 this regression started at `v2.0.0`.

I will take the liberty to close the issue and resolve this on our side.

**Comment by busla** [comment]
> It's weird this issue was not faced previously as there are no recent changes related to that.

We are deploying Airflow for the first time which explains this.
