### ISSUE TITLE
[bitnami/mongodb] Provide custom self-signed certificate

### ISSUE THREAD

**Issue by MisterRnobe** [bitnami/charts#4387]
**Which chart**:
mongodb:10.0.4

**Is your feature request related to a problem? Please describe.**
I have root ca certificate that is used across many my applications and used to deploy mongo with [stable mongodb chart](https://github.com/helm/charts/tree/master/stable/mongodb) that aceepts custom provided ca certificate. Unfortunatelly the chart is no longer available and bitnami/mongodb seems ok for replacement. Otherwise bitnami/mongodb generates its own ca certificate and does not support user provided one.

**Describe the solution you'd like**
I expect bitnami/mongodb to specify existing ca certificate as it's done in [bitnami/rabbitmq](https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#enabling-tls-support)

**Describe alternatives you've considered**
Mounting custom ca certificate with secret or config map might be ok for me but not the best and easy solution

**Comment by miguelaeh** [comment]
Hi @MisterRnobe ,
Thank you for reporting this.
The stable/mongodb was this same Chart, but it was moved with the stable deprecation. Nevertheless, it seems that at some point we removed that option. Would you like to create a PR adding it back again?
Would like to create a PR

**Comment by MisterRnobe** [comment]
Hi, @miguelaeh.
Thanks for yor response.
Okay, I guess I'll implement this feature. Are there some specific rules/conventios I need to know before opening PR?

**Comment by miguelaeh** [comment]
Hi @MisterRnobe ,
Thank you very much. For the versions we use the semver system. Since you will add a new feature you should be bumping the minor version. I.e: `M.m.p` you should bump the `m`.
Apart from that, you will see some checkboxes in the template when creating the PR that will indicate some changes we expect into all the PR, things like remembering to bump the version, add the new parameters to the README.md, etc.
Thank you very much again for helping us creating the PR!

**Comment by deveshk0** [comment]
@miguelaeh Can you have a look at my PR

**Comment by miguelaeh** [comment]
Hi @deveshk0 ,
There is already a colleague taking care of it.
Thank you very much for your contribution!!
