### ISSUE TITLE
Every kafka operation is superslow only on one specific machine

### ISSUE THREAD

**Issue by hatharom** [bitnami/charts#4401]
This is probably a question...

I have a kafka setup with the chart's default settings on two different computer machine_1 and machine_2 (1-1 one node cluster).

The only **differences** are:
 * machine_1 runs ubuntu with 32gb memory and 4*3Ghz, 
 * machine_2 runs centos with 16gb memory and 4*1.8Ghz

After starting up kafka uses ~1gb memory on both cluster. cpu usage of kafka is ~5%.

**What happens** is that on machine_1 the one node cluster behaves normally. On machine_2 everything is superslow.

A simple topic listing like `/opt/bitnami/kafka/bin/kafka-topics.sh --list --zookeeper  <my-zk>:2181` is slow.
On machine_1 it takes ~1-2sec to give get back the response , on machine_2 it is 7sec all the time.

**Linux's top command** shows the following: At every CLI operation kafka spins up an other java process, this process spikes up to  ~70% on machine_1,  but to 160% on machine_2

I haven't provided all the details here, so I don't expect a clear answer..just a guidance what to look for.

-I have already completed a consumer-perf and porduce-perf test from CLI and machine_2 was 3times slower in both case.
And yes.. machine_1 is stronger, but in my case the Kafka is far from using that much power.

**edit:** I just tested it on minikube with only 2cpu and 4Gb memory and works well also, topic listing is fast enough. This minikube setup is way faster than machine_2.
The only way I can reproduce machine_2's issue on minikube is to use some addition tool to increase the constant load of the CPU to 100%. And only in that case will it behave like machine_2.

Any idea?

**Comment by juan131** [comment]
Hi @hatharom 

I am afraid I'm not an expert on improving cpu usage on Kafka deployments. That said, I can try to do my best:

- How many cores do you have on these machines? According to [Confluent documentation](https://docs.confluent.io/current/kafka/deployment.html#cpus) it is advisable to have several cores to improve usage (if you need to choose between faster CPUs or more cores, choose more cores)
- Do you have many Kafka partitions? The load on the CPU will get higher with more partitions since Kafka needs to keep track of all of them.
