### ISSUE TITLE
rabbit node affinity conflict when have more than one AZ

### ISSUE THREAD

**Issue by WLun001** [bitnami/charts#4442]
**Which chart**:
The name (and version) of the affected chart
```
rabbitmq-7.7.1, 3.8.9
```

**Describe the bug**

- Hitting `node affinity conflict ` when scale up in cluster have more than 1 availability zone, even though i have node taint on other node pool that is on another zone

**Expected behavior**

- Able to scale without hitting  `node affinity conflict ` in cluster has more than one availability zone

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1400", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-10-28T09:22:18Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by juan131** [comment]
Hi @WLun001 

Could you please share the output of running the command below?

```bash
helm get values MY_RELEASE
```

> Where MY_RELEASE is just a placeholder for the actual name of your release

I'd like to understand how you setup affinity in the chart.

**Comment by WLun001** [comment]
@juan131 , i did not setup affinity in charts

```bash
$ helm get values rabbitmq

USER-SUPPLIED VALUES:
auth:
  erlangCookie: <cookie>
  password: <passoword>
service:
  annotations: 'cloud.google.com/load-balancer-type: "Internal"'
  type: LoadBalancer
```

**Comment by juan131** [comment]
Hi @WLun001 

That's weird since we don't implement any "nodeSelector", nor "affinity", nor "tolerations" rules by default in the RabbitMQ statefulset.

You mentioned you have used "taints" (https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to mark one of the nodes. So I guess you need to set the right tolerations in the Statefulset for K8s to be able to schedule pods there.

**Comment by WLun001** [comment]
Hey @juan131 sorry if I didn't make this clear

I have two node pools
-  Pool A: where RabbitMQ running, no taint (zone A)
-  Pool B: other workload, with taint (Zone A and Zone B)

When I scale RabbitMQ StatefulSet, one of the replica hit the error (node affinity conflict), when I described the PVC and it's PV, it was on Zone B, which is the zone of taint Node Pool. 

Any idea how could this happen?

**Comment by juan131** [comment]
Hi @WLun001 

If you added a taint to "Pool B", only pods with matching tolerations can be scheduled on that pool. 

Therefore, if the scheduler is trying to create RabbitMQ pods in the "Pool B" there are two possibilities unless I'm missing anything:

- A) The RabbitMQ pod has certain toleration defined that matches the taint (which I guess it's not the case since you installed the chart with default values).
- B) The taint wasn't properly defined or your K8s version doesn't support them.

In any case, I don't think this is a problem related to the RabbitMQ chart. I highly recommend you to contact someone from the [Scheduling SIG](https://github.com/kubernetes/community/tree/master/sig-scheduling) that might have more information to help you debugging this issue.

**Comment by WLun001** [comment]
@juan131 thanks
