### ISSUE TITLE
Request for Superset Chart

### ISSUE THREAD

**Issue by jerowe** [bitnami/charts#4457]
**Which chart**:
You guys are so awesome that this is a request for a chart to exist for [Apache Superset.](https://superset.apache.org/)

**Is your feature request related to a problem? Please describe.**
Not a real problem. I want something that doesn't exist and I'm pretty sure that's a personal problem. ;-)

**Describe the solution you'd like**
I just really like bitnami charts and would love to see one for Superset! 

**Describe alternatives you've considered**
There's a helm chart that is included in the superset repo. Another option is that the architecture is similar enough to Airflow that I could clobber that chart. 

**Additional context**
I love your charts and I use them everyday! Especially the NGINX and Airflow charts!

**Comment by dani8art** [comment]
Hi @jerowe thank you so much, we agree with you that would be a great addition to our catalog, however, we would need to evaluate and check if it would be possible. In this way, we have created an internal task to analyze Apache Superset, unfortunately, due to the fact that we are a small team and taking into account internal milestone, we can't give you an ETA.  

Nevertheless, we had some examples in the past where user contribution added a new chart, we think this approach would be an excellent opportunity to work on Apache Superset and we would be pleased to handle your PR. 

You can take a look at some PR: [bitnami/discourse](https://github.com/bitnami/charts/pull/2072), [bitnami/metallb](https://github.com/bitnami/charts/pull/2068) or [bitnami/grafana-operator](https://github.com/bitnami/charts/pull/3287).

In addition, we have a scaffolding that would help you to implement all the bitnami standards see https://github.com/bitnami/charts/tree/master/template, and also we will be helping you with the process.

Hopefully, you finally can work on this, we will be happy to have this chart as part of bitnami as part of your contribution.

**Comment by jerowe** [comment]
Sorry I didn't see this. I get way too many github notifications and can't find a good way to deal with them all. ;-) 

I'll take a look at it then. It's uses a lot of the same tools as Airflow, so maybe I can just hammer on that a bit. Thanks again and I'll definitely take a look in the next few weeks.

**Comment by jerowe** [comment]
Didn't mean to close this.

All the bitnami charts use bitnami docker images. How does that work? Is there a separate repo I would have to create a superset image for?

```
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 5.5.3-debian-10-r24
```

**Comment by dani8art** [comment]
Hi @jerowe, thanks! we really appreciate your interest and your effort here. 

Regrading the image, if we finally got a chart PR we will be in charge of adding the image to our catalog. 

Thanks again!
