### ISSUE TITLE
[Minio] no externalIP options

### ISSUE THREAD

**Issue by maxisam** [bitnami/charts#4462]
For Minio chart
https://github.com/bitnami/charts/blob/fd3584252af47a3e66e6dcca8cfc0826ffe06a5b/bitnami/minio/templates/service.yaml#L10

Could we have externalIP option?

https://kubernetes.io/docs/concepts/services-networking/service/#external-ips

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the feedback! I will open a task for evaluation. I cannot guarantee an ETA, but as soon as we have more news, I will update the ticket. If you want to speed up the process, feel free to create a PR with the feature and we will review it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
