### ISSUE TITLE
charts/airflow upstream needs update to latest from 6.7.2 =>  7.0.1

### ISSUE THREAD

**Issue by thapakazi** [bitnami/charts#4482]
**Which chart**:
airflow

**Describe the bug**
Unable to pull Airflow charts version **[7.0.1](https://github.com/bitnami/charts/tree/master/bitnami/airflow#what-changes-were-introduced-in-this-major-version)**, its still pointing to old revision: **6.7.2**

**To Reproduce**

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm search repo|grep airflow
```
[![asciicast](https://asciinema.org/a/UdTmnq8XZbOxZmVi9e2esWpIU.svg)](https://asciinema.org/a/UdTmnq8XZbOxZmVi9e2esWpIU)
 

**Expected behavior**
Be able to pull version: `7.0.1`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by carrodher** [comment]
Thanks for creating this issue. Although it is not the normal workflow, it's something expected from time to time.

We can differentiate two different processes, on one hand, we have the Helm Charts source code hosted in GitHub where user's contributions are allowed, on the other hand, there is an internal process to test and release the Helm Charts to the Bitnami Helm Charts repository. Sometimes, due to different reasons, is possible to have newer versions in GitHub because a PR was merged but the Helm Chart is not released into the repository.

In this case, since there is a major change related to the `apiVersion: v2` changes, we are tracking the status of the releases in this issue (https://github.com/bitnami/charts/issues/3867). In the comment, although the Airflow PR is merged, it is not marked as done because we are aware that the release is not fully done and we are working to complete the release process. The whole catalog should be fully released with the new `apiVersion` before the 1st of December, according to the mentioned issue, there are only two pending Helm Charts.

**Comment by carrodher** [comment]
The latest version was released, you should be able to find it in the repo:
```console
$ helm repo update && helm search repo bitnami/airflow
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME           	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/airflow	7.0.2        	1.10.13    	Apache Airflow is a platform to programmaticall...
```

Please, feel free to reopen the issue if something is not working as expected and you are not able to see the new version in the repo

**Comment by thapakazi** [comment]
Thanks :clap: :clap: :clap:  and cheers :coffee:
