### ISSUE TITLE
RabbitMQ password not changed on generation

### ISSUE THREAD

**Issue by c0rvax** [bitnami/charts#4486]
**Which chart**:
RabbitMQ

**Describe the bug**
We seem to be having an issues with this, which basically keeps password set to `CHANGEME`. The Kube's secret has a randomly generated password, which however is not accepted to login into the rabbit instance. So the password is generated, but not changed from `CHANGEME`.

**To Reproduce**

```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install my-release bitnami/rabbitmq
```

Use the password generated to log in to the rabbit

**Expected behavior**
Expected for the password to change

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
I'm sorry but I am not able to reproduce your issue. The `CHANGEME` password is not something taken into account by default but just when definitions are loaded, see https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#load-definitions

Installing the Helm Chart without any extra parameter results in a random password stored in the secret, this is the password used to login into the RabbitMQ UI, see the following example:

- Install the chart with default options:
```console
$ helm install rabbitmq bitnami/rabbitmq
NAME: rabbitmq
LAST DEPLOYED: Thu Nov 26 14:59:27 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Credentials:

    echo "Username      : user"
    echo "Password      : $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
    echo "ErLang Cookie : $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"

RabbitMQ can be accessed within the cluster on port  at rabbitmq.default.svc.

To access for outside the cluster, perform the following steps:

To Access the RabbitMQ AMQP port:

    echo "URL : amqp://127.0.0.1:5672/"
    kubectl port-forward --namespace default svc/rabbitmq 5672:5672

To Access the RabbitMQ Management interface:

    echo "URL : http://127.0.0.1:15672/"
    kubectl port-forward --namespace default svc/rabbitmq 15672:15672
```

- Follow the above instructions to obtain username and password, as well as the instruction to access the RabbitMQ UI:
```console
$ echo "Username      : user"
Username      : user

$ echo "Password      : $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-password}" | base64 --decode)"
Password      : FkviAzfnR4

$echo "ErLang Cookie : $(kubectl get secret --namespace default rabbitmq -o jsonpath="{.data.rabbitmq-erlang-cookie}" | base64 --decode)"
ErLang Cookie : i7vN4FoQ48hgxecA1tXEoFtuIh6LinxL

$ echo "URL : http://127.0.0.1:15672/"
URL : http://127.0.0.1:15672/

$ kubectl port-forward --namespace default svc/rabbitmq 15672:15672
Forwarding from 127.0.0.1:15672 -> 15672
Forwarding from [::1]:15672 -> 15672
Handling connection for 15672
Handling connection for 15672
```

- Then, go to http://127.0.0.1:15672 (in my case I'm using minikube) and log in with the above user/password:
![Screenshot 2020-11-26 at 15 16 19](https://user-images.githubusercontent.com/13216600/100361364-5fc4e200-2ffa-11eb-8f24-bebe4b36dc97.png)
![Screenshot 2020-11-26 at 15 10 46](https://user-images.githubusercontent.com/13216600/100361376-63586900-2ffa-11eb-9d17-45e7e5fdda10.png)
---------------

If it is not the first deployment, take into account the volumes are not deleted when `helm delete` is executed, so in the next deployment the PVC from previous deployments is going to be mount. That produces that the new random password generated and stored in the secret doesn't match with the one from the previous deployment that is still stored in the volume.

In order to solve the issue, you need to delete the PVC after `helm delete`, then in the next installations or upgrades you can specify the password with `--set`, see https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#upgrading

**Comment by glothriel** [comment]
I also have problems with RabbitMQ passwords. We are launching test environments on nightly, around 5-10% of total builds ends with RabbitMQ not accepting the password it received through values. I was not able to debug this deeper though.

**Comment by carrodher** [comment]
Hi, @glothriel as it seems a different issue and in order to improve the support avoiding mixing topics, can you create a different ticket for your use case? Thanks!
