### ISSUE TITLE
[prestashop] Backoffice redirected to the wrong port (8080)

### ISSUE THREAD

**Issue by rcaillon-Iliad** [bitnami/charts#4514]
**Which chart**:
prestashop 12.0.2

**Describe the bug**
I've deployed the Helm chart to my K8S cluster (hosted by Scaleway) mostly with default values.
I've enabled the ingress and I use a ClusterIP service in front of the pod. Prestashop container listens on port 8080 and my service accepts connexions on port 80.

I can access the website with the URL that I've specified to the ingress, but when I try to access the backoffice (<URL>/administration), I'm redirected to the port 8080 (<URL>:8080/administration) which can't be accessed.

Any idea how to fix it?

Thank you!

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by javsalgar** [comment]
Hi,

I was able to reproduce the issue. I will open a task to fix it. I cannot guarantee an ETA, but we will update this ticket as soon as we have more news. Thank you very much for reporting

**Comment by Balde-ak47** [comment]
Hi,

So still now this issue is not solve ? Because I have the same problem.

**Comment by javsalgar** [comment]
Hi, 

I am afraid it is still in our backlog. I will forward it to the engineering team to evaluate a re-prioritization.

**Comment by FJEANNOT** [comment]
A quick workaround is to go to `/administration/` instead of `/administration` to dodge the redirection

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/prestashop#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
