### ISSUE TITLE
[mariadb] svc name inconsistency

### ISSUE THREAD

**Issue by Hokwang** [bitnami/charts#4538]
**Which chart**:
mariadb

**Describe the bug**
recently mariadb chart changed same as postgresql.
master/slave -> primary/secondary

in postgresql case,
pod name are changed. that's ok.
```
harbor-stage-postgresql-postgresql-primary-0             2/2     Running       0          7h45m
harbor-stage-postgresql-read-0                           1/1     Running       0          7h45m
harbor-stage-postgresql-read-1                           1/1     Running       0          7h44m
```
but svc name for read/write does not changed. So user does not need to update application's chart! this is great!
```
harbor-stage-postgresql                  ClusterIP   10.96.84.249    <none>        5432/TCP            73d
harbor-stage-postgresql-headless         ClusterIP   None            <none>        5432/TCP            73d
harbor-stage-postgresql-metrics          ClusterIP   10.96.255.45    <none>        9187/TCP            73d
harbor-stage-postgresql-read             ClusterIP   10.96.226.15    <none>        5432/TCP            73d
```

btw mariadb, svc name is changed. so user should change their application's values.yaml.
```
keycloak-stage-mariadb-primary     ClusterIP   10.96.225.230   <none>        3306/TCP,9104/TCP          94m
keycloak-stage-mariadb-secondary   ClusterIP   10.96.222.57    <none>        3306/TCP,9104/TCP          94m
```

Can you provide mariadb-primary svc name same as old version and also postgresql do ?

<and more (little thing)>
postgresql-primary pod name has different convention with read pod, <ns>-postgresql-primary-0.
I think you can remove `postgresql`.

**Comment by rafariossaa** [comment]
Hi,
  This change was indicated in the notes for the version 8. As it is a new major version, some breaking changes can happen.

**Comment by Hokwang** [comment]
@rafariossaa yes, mentioned, but I think commiter does not consider inconsistency with other DB.

**Comment by rafariossaa** [comment]
Hi,
  I have created an internal task to add a parameter to allow service name overriding, that should work for you.
  We will come back as soon as we have news.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
