### ISSUE TITLE
[bitnami/mssql] Request for a mssql chart

### ISSUE THREAD

**Issue by yardenshoham** [bitnami/charts#4576]
**Which chart**:
mssql

**Is your feature request related to a problem? Please describe.**
I want to deploy a highly-available mssql instance. For every other 3rd component in my cluster, a bitnami helm chart exists.

**Describe the solution you'd like**
I would like a mssql bitnami helm chart.

**Describe alternatives you've considered**
I thought about using [this image](https://hub.docker.com/_/microsoft-mssql-server) from Docker hub and create my own chart but fear I'm not familiar enough with [mssql HA](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/overview-of-always-on-availability-groups-sql-server?view=sql-server-linux-ver15) to produce a best-practice chart.

**Additional context**
A deprecated helm chart for mssql exists [here](https://github.com/helm/charts/tree/master/stable/mssql-linux).

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback! Our policy is to own all the containers of the charts we offer, and right now it is not possible for us to package mssql because of license and distribution restrictions. Because of that, I'm afraid there are no plans to package a mssql chart. If the license and distribution conditions change, we'd be happy to work on that.
