### ISSUE TITLE
[bitnami/redis] use term replica instead of slave

### ISSUE THREAD

**Issue by riptl** [bitnami/charts#4617]
**Which chart**:
bitnami/redis

**Is your feature request related to a problem? Please describe.**
Low prio / vanity change.
As of Redis v5, Redis uses the terms "replica" instead of "slave". ([source](https://redis.io/commands/slaveof))
This Helm chart would ideally use the same terminology as Redis.

**Describe the solution you'd like**
Usages of the terms `slave` should be modified to `replica`.
Compatibility with existing bitnami/redis Helm installations must be preserved. Those use terms `redis-slave` in the StatefulSet and PersistentVolumeClaims, which are hard to rename.
Perhaps introducing a `redisV5Naming` flag or similar works.

**Describe alternatives you've considered**
Do not change any identifiers and point out the difference in docs / code comments.

**Comment by marcosbc** [comment]
Hi @terorie, thanks for the suggestion! It's something that we plan to do, but unfortunately I cannot give an ETA for when it would be completed. I'm also going to link to this related issue: https://github.com/bitnami/bitnami-docker-redis/issues/187.

**Comment by marcosbc** [comment]
If you want, feel free to contribute a PR with these changes, we'd be happy to review it. Even if the container uses the old terminology, it can be changed separately. Note that it would be a major change, meaning you would have to increase the major version of the chart (i.e. 12.x.x -> 13.0.0).

You can see how we did it with MariaDB here: https://github.com/bitnami/charts/pull/3849

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
