### ISSUE TITLE
Improve randomly generated password strength

### ISSUE THREAD

**Issue by deed02392** [bitnami/charts#4649]
**Which chart**:
postgresql

**Is your feature request related to a problem? Please describe.**
10 chars alphanum is the *minimum* recommended password length for a randomly generated password.

**Describe the solution you'd like**
Increase the random password length to at least 16 chars, to increase strength for users utilising the auto password generation

**Describe alternatives you've considered**
Disabling auto password generation to force users to select their own. But the random password generation is convenient AND secure - it could just be better than 10 chars.

**Additional context**
https://blog.1password.com/how-long-should-my-passwords-be/

**Comment by marcosbc** [comment]
Hi @deed02392, great suggestion! I agree that 10 characters may be too short for someone expecting a secure password. We could also add a parameter that determines the length of the random password.

I'm creating an internal task for evaluating this, but unfortunately I cannot give an ETA for when we'd start looking into this. In the meantime, feel free to send a PR making the required changes, we'd be happy to review and help with the release.

**Comment by deed02392** [comment]
Cool @marcosbc :-) I had a quick look and the only change needed is the argument to randalpha in the templates, unless you really wanted to add a parameter for specifying the length - not sure how to implement that off-hand.

**Comment by marcosbc** [comment]
Sure @deed02392, feel free to send a PR with the change to increase the random password length. I'm a bit worried in case it could have implications for other apps, but I can't think of any specific issue that may happen right now.

That said, in a production environment we would recommend to always set the passwords. Since you need to specify them for upgrades anyways, it is better this way.

In other charts (i.e. [MariaDB](https://github.com/bitnami/charts/tree/master/bitnami/mariadb#production-configuration)), when using `values-production.yaml`, we force users to set the password. This change has not yet made it into PostgreSQL though.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
