### ISSUE TITLE
[bitnami/postgresql] Cannot authenticate to postgresql when using non-default port and LoadBalancer service

### ISSUE THREAD

**Issue by deed02392** [bitnami/charts#4652]
**Which chart**:
bitnami/postgresql

**Describe the bug**
If you choose a non-default port with LoadBalancer service, you won't be able to authenticate to the server.

**To Reproduce**

1. Deploy a default build of the latest Chart version, only with LoadBalancer and port changed (I tried 65432)

**Expected behavior**
I expected to be able to use either the auto generated passwords by the chart, or the manually specified passwords. I tried a deployment with only a `postgres` user and also a custom user and all combinations of passwords resulted in authentication failed errors.

**Version of Helm and Kubernetes**:
k8s 1.18
chart: bitnami/postgresql 10.1.3

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.14"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:43:56Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I looked at the hba conf file and couldn't see any issues there, although I believe it's port agnostic anyway.

**Comment by alemorcuq** [comment]
Hi, @deed02392.

Thanks for reporting this. I have reproduced the issue and created an internal task to investigate and fix it.

**Comment by rafariossaa** [comment]
Hi,
  We have made a new release of the container image that will fix this issue.

  This chart should be updated automatically, but in the mean time , could you use  `--set image.tag=11.10.0-debian-10-r61` and give it a try ?

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
