### ISSUE TITLE
[bitnami/moodle] external database connection not secure.

### ISSUE THREAD

**Issue by tbertenshaw** [bitnami/charts#4675]
I'm trying to use Azure Database for MySQL as the external database for the moodle helm chart.

When i look at the pod logs to diagnose the problem connecting to the database i can see.

![image](https://user-images.githubusercontent.com/2010002/101764339-df14e400-3ad7-11eb-99c2-7ffba4a30bb1.png)

Is it possible to configure secure transport in the chart as I cannot disable require_secure_transport for the database server in azure.

![image](https://user-images.githubusercontent.com/2010002/101763895-5007cc00-3ad7-11eb-9dc4-04781ab032c3.png)

**Comment by dani8art** [comment]
Hi, @tahsinrahman 

I can confirm that currently, our moodle image doesn't support SSL connections by default, we would need to evaluate and check if it would be possible. In this way, we have created an internal task to analyze it, unfortunately, due to the fact that we are a small team and taking into account internal milestone, we can't give you an ETA.

Meanwhile, I think you can try three things:

- Modify the container logic so that you can add the required flags and files when creating and updating the database through MySQL client, and if you find the solution you can contribute it as well.
  - You can find MySQL docs [here](https://mariadb.com/docs/reference/mdb/system-variables/require_secure_transport/) 
  - And how to use SSL files from different [clients](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl#:~:text=Using%20the%20Azure%20portal%2C%20visit,connection%20setting%20for%20enhanced%20security)
  - We can point you to the function that could be affected, [mysql-client](https://github.com/bitnami/bitnami-docker-moodle/blob/78f3ce780f72c6095edb5fc57a0ba4bd0410a6df/3/debian-10/rootfs/opt/bitnami/scripts/libmoodle.sh#L138)

- Skipping the bootstrap of the moodle application and try to do it manually through the initialization wizard

```
--set moodleSkipInstall=true
```

- [NOT RECOMMENDED] If it is possible, try to disable secure connection using [this](https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl#:~:text=Using%20the%20Azure%20portal%2C%20visit,connection%20setting%20for%20enhanced%20security)

Thanks!

**Comment by dani8art** [comment]
Hi,

After a few more researches, we found that there is an upstream issue in moodle, https://tracker.moodle.org/browse/MDL-54704, they do not support SSL database connection directly so it needs a patch in the application itself to do so. Unfortunately, we are not going to be able to solve this problem since it is an upstream issue but not a configuration issue. Hopefully, you can find a way to add SSL to your database connection.

Thanks!

**Comment by ano010** [comment]
Hi,

Is there any update on this? I have been trying to connect the MySQL client with Azure MySQL via SSL. Though it is enabled from the server-side, it seems the client doesn't support it. 

I get this error "PHP Warning:  mysqli::__construct(): (HY000/3159): Connections using insecure transport are prohibited while --require_secure_transport=ON. in /opt/bitnami/moodle/lib/dml/mysqli_native_moodle_database.php on line 83
moodle_1  | We could not connect to the database you specified. Please check your database settings."

I have enabled these environment variables as well
MYSQL_CLIENT_ENABLE_SSL_WRAPPER: "yes"
MYSQL_CLIENT_ENABLE_SSL: "yes"
But it is still showing the same error.

Anyhow, I am not sure about the following variables? do I need to set these? What should be the values?
MYSQL_CLIENT_SSL_CA_FILE
MYSQL_CLIENT_SSL_CERT_FILE
MYSQL_CLIENT_SSL_KEY_FILE

Thanks

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-moodle#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
