### ISSUE TITLE
[bitnami/kafka] support for wildcard subdomain cert

### ISSUE THREAD

**Issue by tbnguyen1407** [bitnami/charts#4795]
**Which chart**:

bitnami/kafka

**Is your feature request related to a problem? Please describe.**

Current keystore config requires 1 keystore per broker as follow
* kafka.truststore.jks
* kafka-0.keystore.jks
* kafka-1.keystore.jks
* ...

This is not optimal for scalability as the number of brokers needs to be determined beforehand.

**Describe the solution you'd like**

Support for single default keystore file which can contain a cert with wildcard SAN (e.g. DNS.0=*.kafka-headless.default.svc.cluster.local)
* kafka.truststore.jks
* kafka.keystore.jks

The setup.sh script would use the default keystore file if exists instead of looking for individual kafka-[index].keystore.jks

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by marcosbc** [comment]
Hi @tbnguyen1407, thanks for the suggestion! Unfortunately we have a very limited bandwidth at this moment to make this change, but the [bitnami/charts](https://github.com/bitnami/charts/issues/4795) repo is open for contributions.

If you have some bandwidth and wish to contribute, feel free send a PR with this feature! We'd be glad to review and help with the release.

**Comment by clauney** [comment]
@tbnguyen1407 it isn't graceful, but we've worked around this with a hacky thing that creates secrets for each broker from the same keystore file. You can just use whatever number you want as the top end so that you can expand # of brokers. This comes out of some scripts so there are env vars, but they should all be pretty obvious (DIST_KEYSTORE is the relative path to the common keystore file). There are other secrets we create too for keystore pass, truststore, etc. that the other env vars refer to.

```
export ARG_HACK=`for node in $(seq 0 $(($KAFKA_POOL_NODE_COUNT-1)));do echo "--from-file=kafka-$node.keystore.jks=$DIST_KEYSTORE "; done`
kubectl create secret generic $KUBE_JKS_SECRET_NAME -n kafka $ARG_HACK --from-file=$DIST_TRUSTSTORE \
    --from-literal=keystore-password=$SERVER_KEYSTORE_PASS --from-literal=truststore-password=$SERVER_TRUSTSTORE_PASS --dry-run -o yaml | kubectl apply -f -
```

That said, I will see about contributing to the charts repo. @marcosbc this seems like a pretty small scope change, but I'll read through the contributing readme and try to get to this.
