### ISSUE TITLE
New chart request: MockServer

### ISSUE THREAD

**Issue by OmriHarary** [bitnami/charts#4818]
[mock-server/mockserver](https://github.com/mock-server/mockserver) is an HTTP/S mock backend and proxy, and is one of the most starred mock-servers on Github.
While the MockServer project does provide a simple Helm chart, it does not entirely follow best practices and it is not available from a proper chart repo, both of which make it difficult to include in umbrella charts especially.

It would be beneficial to have a Bitnami chart for MockServer, but would also require a Bitnami container image for it which there isn't at this time.

**Comment by rafariossaa** [comment]
Hi,
  Thank you very much for suggesting this. 
  I will add it to the list, however I can not guarantee that it will be done nor when it could be made.

**Comment by rafariossaa** [comment]
I am closing this issue.

**Comment by OmriHarary** [comment]
Hi @rafariossaa, I'm just curious if there's anything that could be done to increase the chances of this happening. I would be able to assist with the chart itself if needed, but I'm not familiar with the process for onboarding new container images.

**Comment by rafariossaa** [comment]
Hi @OmriHarary ,
  We are a small team, this would depend on many factors that affects our workload.
  Thank you very much for offering of contributing to the chart. Maybe you want to take a look to https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository and this [template directory](https://github.com/bitnami/charts/tree/master/template).
  About the container image, it is more difficult because there are many steps that involves our internal CI/CD. But as starting point you can take a look to other of our containers images and create something similar.
