### ISSUE TITLE
Rocket.Chat chart?

### ISSUE THREAD

**Issue by bl-ue** [bitnami/charts#4846]
How about adding a chart for [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat)?  It's a minimal chat server, and it should be simple to add a chart for.

**Comment by javsalgar** [comment]
Hi,

Thank you very much for the suggestion. I will forward the team for evaluation. In order to package such chart, we would need first to create the container and then the chart. Other users have contributed with a PR (examples: MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter...)following our chart guidelines, and while we reviewed it, we packaged the container. If you want to contribute with the chart do not hesitate to open a PR and we will review it.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
