### ISSUE TITLE
[bitnami/minio] support default bucket in distributed mode;

### ISSUE THREAD

**Issue by ethernoy** [bitnami/charts#4847]
**Which chart**:
Minio (latest)

**Is your feature request related to a problem? Please describe.**
Minio in distributed chart cannot create default bucket.

**Describe the solution you'd like**
Apply default bucket config even when in distributed mode.

**Describe alternatives you've considered**
A documentation about creating default bucket in other mean in distributed mode.

**Comment by marcosbc** [comment]
Hi @ethernoy, it seems like the only reason it's missing is because we're defining `MINIO_DEFAULT_BUCKETS` in `templates/deployment-standalone.yaml` but not `templates/statefulset.yaml`. It was added in 0208d979bdd6cd43be946c0f4e7c03b05fa1e508.

If this is a feature you'd like to see, feel free to send a PR implementing the required changes, we'd be happy to help with the review and release of the new chart.

**Comment by vyom-soft** [comment]
I think this support of default bucket in distributed mode is still not in place. It fails.

**Comment by javsalgar** [comment]
Hi @vyom-soft, could you add more details to reproduce the issue?
