### ISSUE TITLE
[bitnami/ghost] unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]

### ISSUE THREAD

**Issue by acim** [bitnami/charts#4899]
**Which chart**:
bitnami/ghost

**Describe the bug**
This chart now has the same problem as described here for wordpress: https://github.com/bitnami/charts/issues/4791

**Comment by marcosbc** [comment]
Hi @acim, we have an internal task where we are tracking the progress of this work. Unfortunately, due to winter holidays this has been delayed and could not be completed immediately.

Note: The first batch was done in #4870, and we are pending for newer batches to be completed ATM. We expect to continue early next week. If you need a fix sooner feel free to send a PR, we'd be happy to help with the review and release of the new chart(s).

**Comment by acim** [comment]
This is already fixed.
