### ISSUE TITLE
[bitnami/wordpress] Error while changing password via wp cli

### ISSUE THREAD

**Issue by huang-jy** [bitnami/charts#4900]
**Which chart**:
bitnami/wordpress, V10.3.0

**Describe the bug**
While using wp cli to change the password of the root user, I get a sendmail error (the password change actually takes though)

**To Reproduce**

```
$ kubectl exec -itn {namespace} {wordpress-pod} -- wp user update 1 --display_name="Joe Bloggs" --user_pass=supersupersecurepassword
sh: 1: /usr/sbin/sendmail: not found
Success: Updated user 1.

```

**Expected behavior**
Password change without error, or at least a warning that does not appear to be fatal

**Version of Helm and Kubernetes**:
```
$ helm3 version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by carrodher** [comment]
Hi, I was taking a look at this issue. This error appears because there are some WP CLI commands (like the one used to change the password) that send an email notification to the user. In this case, the WordPress container image doesn't contain `sendmail` that is the binary used for WP CLI to send this notification. As you rightly said, the command works fine and the password is changed but the reported error appears because the email is not sent.

In order to avoid this error, you can use the `--skip-email` flag as described [here](https://developer.wordpress.org/cli/commands/user/update/). See the result:
```
I have no name!@wordpress-1610038328-d8ccc956f-g56vf:/$ wp user update 1 --user_pass=supersupersecurepassword --skip-email
Success: Updated user 1.
```

`sendmail` is not included by default in the image because it is an insecure scenario if there is not appropriately configured using SMTP.

**Comment by huang-jy** [comment]
Ah, that makes sense. Thanks, I'll use the skip-email switch, thanks!
