### ISSUE TITLE
[oauth2-proxy] Introduction

### ISSUE THREAD

**Issue by jjangga0214** [bitnami/charts#4948]
[oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) is, as its name implies, a standalone proxy for oauth2. 

In fact, Bitnami already provides an [image](https://bitnami.com/stack/oauth2-proxy/containers) of it.

As we know, stable charts are deprecated and [oauth2-proxy chart](https://github.com/helm/charts/blob/master/stable/oauth2-proxy/README.md) is one of them. 

So, what if we maintain it here?

Thanks.

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines.

In this case, as you rightly say, the container image is already part of the Bitnami catalog, which is a good starting point

If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by carrodher** [comment]
I'm closing this issue since we already added ouath2-proxy to the Bitnami Helm Charts, catalog. See https://github.com/bitnami/charts/tree/master/bitnami/oauth2-proxy
