### ISSUE TITLE
[bitnami/mongodb] Add support for startup probe

### ISSUE THREAD

**Issue by krtk6160** [bitnami/charts#4979]
**Which chart**:
Mongodb

**Is your feature request related to a problem? Please describe.**
I had a mongodb replicaset running on GKE without an explicit cache size or ram limit set. After the replicaset started taking too much ram, I set the limit explicitly. After this, mongodb would not start due to a long running oplog truncation process that would prevent mongodb from getting ready, and thus being killed by the liveness and readiness probes.

**Describe the solution you'd like**
Kubernetes official docs suggest using startup probes to protect pods that might have long running initialization processes. Adding startup probe support to the chart will be useful imo.

**Comment by marcosbc** [comment]
Hi @krtk6160, we are usually adding new features to Bitnami charts like these, however due to the amount of charts we're unable to make all those changes at once, meaning they usually take some time before they are available.

Note that we're open for contributions, so feel free to send a PR implementing the required changes! We'd be glad to help with the review and the release of the chart with those changes.

**Comment by marcosbc** [comment]
FYI a recent PR was added to make the changes for MariaDB here, in case you want to contribute these changes to MongoDB, as they would be very similar: https://github.com/bitnami/charts/pull/4966

**Comment by bvobart** [comment]
Hi, I had a similar problem today having a MongoDB replicaset running on GKE, but with a WT cache size of 2GB and a 2.5 GB RAM request (but no configured limit). After an import of a large collection, MongoDB's RAM usage peaked slightly above its request, which caused the pods to get killed by Kubernetes. While the replicaset primary started up normally after that, the secondaries were not able to become ready, as they would start up trying to recover several indexes on this collection, which takes longer than it takes for Kubernetes to start killing the pod. This cycle would repeat ad infinitum, consuming valuable CPU and RAM resources while futilely trying to recover.

The only way I was able to fix this, was to disable the readiness probes on both the MongoDB containers, as well as on the metrics containers. Applying this configuration change could only be done by first `kubectl delete`'ing the secondaries' pods, so they would get recreated with the new configuration.

So, Bitnami, would you please give this a higher priority to implement this for your otherwise great MongoDB chart?

**Comment by marcosbc** [comment]
Hi @bvobart, your use case seems very specific, and it may be required if you first deploy the chart with disabled probes until everything is ready, and then perform an upgrade where the probes are active.

As for the addition of startupProbes, I'm marking this as on-hold to work on it as soon as we get a chance.

Note that we are open for external requests. If you wish to contribute this change, we'd be glad to help with the review and release. Check an example of the few required changes [here](https://github.com/bitnami/charts/pull/5805/files).

**Comment by krtk6160** [comment]
@marcosbc I have created a new PR #5998 that implements a startup probe
