### ISSUE TITLE
Spring Data Flow Charts - External Kafka

### ISSUE THREAD

**Issue by michaelpearce-gain** [bitnami/charts#5050]
**Which chart**:
Spring Data Flow

**Is your feature request related to a problem? Please describe.**
I want to launch Spring Data Flow with an external kafka cluster, like it is possible with rabbitmq as the stream backend binder.

**Describe the solution you'd like**
Able to provide kafka full kafka config options, not just bootstrap, but all of them, e.g. credentials, security settings etc. Ideally not having to use ZK, as all admin functions now should be in admin client, and for uses like confluent cloud its not possible to connect to zk anyhow.

**Describe alternatives you've considered**
make a complete custom chart from scratch :(

**Comment by javsalgar** [comment]
Hi,

Thanks for the request. We have the bitnami/kafka cluster right now. In order to integrate it, do you know which parameters or environment variables we would need to set to SCDF in order to make it work. Do you have experience configuring this integration?

**Comment by michaelpearce-gain** [comment]
Hi, i thought this chart was done in collaboration with the spring team, and your team had/is working with them to make an official helm charts (it reads that way on their microsite), we are simply looking at solution options atm, this tool for us also is new, and just following details found here:

https://dataflow.spring.io/getting-started/

**Comment by javsalgar** [comment]
Hi,

Sorry, I am not an expert on SCDF hence the question. I double checked and saw that we already provide Kafka support as a subchart, so then it should be relatively simple to add support for externalKafka just like we do with other charts like WordPress, where we have an externalDatabase set of values. I will open a task for implementation. I will update this ticket as soon as we have more news.

**Comment by jxy859** [comment]
A simple follow-up -- Any update related to the open issue?
Our team was trying to use build-in Kafka cluster and we really want the external Kafka enabling feature for the spring cloud dataflow chart.
Thank you

**Comment by javsalgar** [comment]
Hi,

I am afraid that it is still in our backlog. As soon as we have more news, we will update the ticket. If you want to speed up the process, feel free to submit a PR and we will review it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
