### ISSUE TITLE
[memcached] values-production.yaml non-functional

### ISSUE THREAD

**Issue by red-trela** [bitnami/charts#5065]
**Which chart**:
memcached

**Describe the bug**
The values-production.yaml is non-functional

**To Reproduce**

1. Attempt to install the helm chart with the values-production.yaml
2. Get an error about replicaCount > 1 being incompatible with architecture == standalone
3. Fix the above and install the helm chart again
4. Notice that the memcached containers crash, because the root file system is read-only which is not supported by the used docker image

**Expected behavior**
Example *values.yaml should be working as-is

**Additional context**
I first tried reporting the second issue (not working with read-only filesystem) against the docker image:
https://github.com/bitnami/bitnami-docker-memcached/issues/68

**Comment by andresbono** [comment]
Hi @red-trela, thanks for reporting this issue. We plan to remove all the `values-production.yaml` from the different charts as they are not that useful. Could you please stick to the `values.yaml` file?

The removal of the files will start during the following days.

**Comment by red-trela** [comment]
Oh, that's a pity, I actually think they're very useful - maybe less so for memcached but certainly for more complex charts. But in that case, figure this issue is obsolete.

**Comment by andresbono** [comment]
Thank you, @red-trela. The problem is that "production" could mean very different things for each user, so we think it doesn't make sense to impose some production values. Instead of that, we want to focus on providing flexibility so each user can customize the default `values.yaml` to particular needs depending on the case.

This will be explained in detail as soon as the plan for removing these files start.
