### ISSUE TITLE
Can’t connect remotely to Mongodb Replicaset with TLS using node.js

### ISSUE THREAD

**Issue by soft-sysops** [bitnami/charts#5085]
Chart used:
  Chart Mongodb 
  appVersion: 4.4.3
  version: 10.4.0

Bug:

I deployed a Mongodb RS on Kubernetes (On Kapsule of Scaleway) using Bitnami chart with 

tls:
  enabled: true
......
externalAccess:
  enabled: true

I added a costum DNS.6 = *.mycostumdomain.fr on StatefulSet.yaml file

The Mongodb cluster is running correctly and I can reach it from outside using mongo shell ( mongo --host "mongo-0.mycotumdomain.fr:27017" --tls --tlsCertificateKeyFile=certs/mongo-client.pem --tlsCAFile=certs/mongodb-ca-cert )

But the problem is that I can't reach it neither with node.js code nor mongo compass 
I have an error which is: 
"getaddrinfo ENOTFOUND mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local"

Someone have a solution for this please ?

**Comment by FraPazGal** [comment]
Hello @soft-sysops,

It seems your mongodb chart is working correctly and its configuration is fine, as you are able to connect to it from outside using TLS. It seems the issue is your application (or the infrastructure) is not able to resolve the service name so it does not look an error in the Chart.

Our charts are tested with a standard Helm installation, so there may be instances where they require some user customisation to be run in a non-typical infrastructure like the one used by Kapsule. As explained, we are not able to reproduce this test scenario and I would recommend you to reach out to Kapsule's support so they can share their insights on this.

**Comment by soft-sysops** [comment]
Hello,

Thank you for your answer,

I found that the problem was when connecting with the node.js mongoose package but no problem with Mongodb package

I am trying to find a solution to be able to connect using mongoose

Best regards

**Comment by ChuckNoxis** [comment]
Hello @soft-sysops, did you find any solution to this problem ?
We are currently using mongoose and I have the same problem !
Thanks
