### ISSUE TITLE
[bitnami/keycloak] Configuration as a service CaaS

### ISSUE THREAD

**Issue by iamaverrick** [bitnami/charts#5146]
**Which chart**:
The name (and version) of the affected chart.

bitnami keycloak version 1.2.0

**Is your feature request related to a problem? Please describe.**

Keycloak is very difficult and time consuming service to implement and once implemented maintaining is a hassle. By configuring this service just once will allow for fast setup and more reliability. Currently the configuration of bitnami keycloak sets up the server which will have to be configured by hand. 

**Describe the solution you'd like**

My solution suggest to use Configuration as as service CaaS which allow the user to provide a file either json or yaml file with all keycloak configuration as they want it. This means the code will execute exactly each and every time. The way we propose to do this is actually very simple. By enabling this project [Here](https://github.com/adorsys/keycloak-config-cli) as the bitnami keycloak helm chart dependency and passing the configs either as environment variables, providing key/value, or directly passing json or yml file.

**Describe alternatives you've considered**

**Additional context**

Please Note:

[Example configuration file in json](https://github.com/adorsys/keycloak-config-cli/blob/master/contrib/example-config/moped.json) 

[Extensive list of examples ](https://github.com/adorsys/keycloak-config-cli/tree/master/src/test/resources/import-files) 

[Project dependency](https://github.com/adorsys/keycloak-config-cli/tree/master/contrib/charts/keycloak-config-cli)

**Comment by carrodher** [comment]
It seems a good feature to automate the configuration but having said that, there are some items that need to be covered in order to add this subchart as a Keycloak dependency.

The `keycloak-config-cli` chart should be part of the Bitnami Helm Chart catalog and then create a PR with the required changes in the bitnami/keycloak Helm chart. The process would be something like this:

1. Create a PR adding the `bitnami/keycloak-config-cli` Helm Chart
2. Create a new PR implementing the required changes to use this new chart as a subchart in `bitnami/keycloak`

For the first step, there are some considerations that must be taken into account since there are three major requirements to add a new chart to our catalog:
- The chart should use Bitnami based container images. If they don't exist like in this case, the Bitnami team will need to create them. As it is an internal process, we will need to be evaluated and prioritized in conjunction with the rest of the team's tasks. 
- Follow the same structure/patterns that the rest of the Bitnami charts (you can find a basic scaffolding in the [`template` directory](https://github.com/bitnami/charts/tree/master/template)) and the [Best Practices for Creating Production-Ready Helm charts](https://docs.bitnami.com/tutorials/production-ready-charts/) guide.
- Use an [OSI-approved license](https://opensource.org/licenses) for all the software.

You can find more information about the process in the [CONTRIBUTING guildelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository).

**Comment by andresbono** [comment]
Hi @iamaverrick, we have just released the new container image for keycloak-config-cli. I added some comments in the PR so that you can make the changes to be able to test the new image.
