### ISSUE TITLE
[bitnami/nginx] Cannot set servicePort of Ingress rule

### ISSUE THREAD

**Issue by soonoo** [bitnami/charts#5147]
**Which chart**:
latest nginx chart

**Is your feature request related to a problem? Please describe.**
Both `http` and `https` ports are exposed in deployment.
https://github.com/bitnami/charts/blob/152afd99edf61b03f7ed6ab4ab1e79207c34ceb3/bitnami/nginx/templates/deployment.yaml#L116-L121
It seems `servicePort` in Ingress rule is fixed to `http` however.
https://github.com/bitnami/charts/blob/152afd99edf61b03f7ed6ab4ab1e79207c34ceb3/bitnami/nginx/templates/ingress.yaml#L43

**Describe the solution you'd like**
Please provide a way to choose servicePort.

**Comment by andresbono** [comment]
Hi @soonoo, in general, when you want to use ingress and https, the SSL/TLS connections end in the ingress and it proxies the requests to the backend through http. Note that the cert management is handled by the ingress if it is enabled.

**Comment by soonoo** [comment]
Hi @andresbono, thank you for your comment.
I'm using [nginx-ingress-controller](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#ssl-passthrough)'s ssl-passthrough feature and it works without ingress side certificates.  

By the way, problem is solved with `ingress.extraPaths`. Another question is whether `http` service or ingress could be disabled. 

Do you have any hints about this?

**Comment by andresbono** [comment]
I don't think that is possible right now, @soonoo.


Maybe you can use the [force-ssl-redirect](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-side-https-enforcement-through-redirect) annotation to help with what you want.

You can tweak a little bit the helm chart parameters and at least you can restrict the ports in the service and the container to 443 only. But it could be missleading because the port name will be `http` and it is actually `https` traffic. This is a sample `values.yaml` that you could use:

```
ingress:
  enabled: true
  hostname: nginx.fuf.me
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

service:
  type: ClusterIP
  port: 443
  targetPorts:
    http: 443

containerPorts:
  http: 8443

serverBlock: |-
  server {
    listen       8443 ssl;

    ssl_certificate      bitnami/certs/server.crt;
    ssl_certificate_key  bitnami/certs/server.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
      root   html;
      index  index.html index.htm;
    }
  }
```

**Comment by soonoo** [comment]
Thank you @andresbono. I'll try it!
