### ISSUE TITLE
[bitnami/spring-cloud-dataflow] Fully support use of external Kafka

### ISSUE THREAD

**Issue by OmriHarary** [bitnami/charts#5169]
**Which chart**:
spring-cloud-dataflow

**Is your feature request related to a problem? Please describe.**
The spring-cloud-dataflow chart currently supports both internal and external databases, and both internal and external RabbitMQ, but only includes parameters in `values.yaml` for internal Kafka.

**Describe the solution you'd like**
The chart should support external Kafka in the same way that it supports external RabbitMQ.

**Describe alternatives you've considered**
An alternative option would be to configure an external Kafka fully manually using the `extraEnvVars`, but this is more cumbersome and doesn't appear like it would even work based on the templates. Currently in the process of testing this, will update this afterwards.

**Comment by juan131** [comment]
Hi @OmriHarary 

Thanks so much for this suggestion!! I totally agree with you and we should also support a way to use an external Kafka server when Kafka is chosen as messaging solution.

Would you like to contribute a PR adding this possibility (see [Contributing](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md))? Otherwise, some maintainer will do it for you.

**Comment by OmriHarary** [comment]
Hi @juan131

Schedule permitting, I will work on contributing this.

**Comment by juan131** [comment]
Sure @OmriHarary ! Take all the time you need.
We really appreciate when users take a step forward and contribute with great ideas to improve our charts. Thanks so much!!!

**Comment by OmriHarary** [comment]
@juan131 I've opened a draft PR with an initial approach for now. Please take a look when you are able.

**Comment by juan131** [comment]
Thanks so much @OmriHarary ! I just added a comment on it
