### ISSUE TITLE
[bitnami/redis-cluster] High Availability with Redis cross replication

### ISSUE THREAD

**Issue by marcom71** [bitnami/charts#5176]
**Which chart**:
bitnami/redis-cluster

**Is your feature request related to a problem? Please describe.**
We are deploying bitnami/redis-cluster with one replica for each master into a Kubernetes cluster with the same number of nodes as Redis masters. It would be useful to have each Redis master and its slave deployed on different nodes to provide high availability if one node fails. We need bitnami/redis-cluster instead of bitnami/redis to support high rate of write operations. There is no label useful for an anti affinity rule to place each master and its slave in different nodes.

**Describe the solution you'd like**
Each pods would have a "replica-set" label with same value for a master pod and its replica pods but the value should be different from the one associated to another master+slave set.

**Comment by juan131** [comment]
Hi @marcom71 

I'm afraid that, since the same statefulset is used to create both slave and master replicas, it's not possible to configure the affinity to guarantee that. 

That's also the reason why each pod has its own loadbalancer IP when you expose it outside the cluster. There's no way to use a single service to load balancer between master or slave replicas since you cannot distinguish them based on the labels.
