### ISSUE TITLE
[bitnami/nifi] Request for an apache nifi chart

### ISSUE THREAD

**Issue by yardenshoham** [bitnami/charts#5208]
**Which chart**:
nifi

**Is your feature request related to a problem? Please describe.**
I want to deploy a highly-available nifi instance. For every other 3rd component in my cluster, a bitnami helm chart exists.

**Describe the solution you'd like**
I would like a nifi bitnami helm chart.

**Describe alternatives you've considered**
I thought about using [this](https://github.com/cetic/helm-nifi) chart but it doesn't have the bitnami parameters I need such as `global.imageRegistry`.

**Additional context**
I would suppose it'll be similar to the already existing bitnami helm chart for apache spark.

**Comment by andresbono** [comment]
Hi @yardenshoham, thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.
 
If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. The container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
