### ISSUE TITLE
Varnish and SFTP for Prestashop chart

### ISSUE THREAD

**Issue by lucmichalski** [bitnami/charts#5214]
Hi guys,

Hope you are all well !

Which charts: **prestashop**

I saw that in the past you were integrated **varnish with prestashop**. 
Why did you drop the varnish support as it is quiet performant/interesting for large scale prestashop deploys ?
Is it possible to put it back (optionally) for the k8s deploy ?

Also, is it possible to access Prestashop volume through an sftp account ? 
How would you do that ? Is it possible to provide an example ?

Thanks for any insights or inputs on these questions.

Cheers,
Luc Michalski

**Comment by javsalgar** [comment]
Hi,

> I saw that in the past you were integrated varnish with prestashop.

The integration with Varnish was for our Single-Vms and installers. We did not add support in our containers because that would imply having more than one process in the container, and it's something that we want to avoid. If we were to add it, maybe it should be sidecar container instead, but we don't have a Varnish sidecar at the moment. I will open a task for evaluating it. 

Regarding SFTP support, my advice would be using the `sidecars` section of the Prestashop chart, there you can add a SFTP server. You would need to mount the Prestashop persistence as well. Would that work for your use case?

**Comment by lucmichalski** [comment]
@javsalgar 

Thanks for the quick reply :-)

For varnish, it would be really nice to have a varnish sidecar. or maybe even a redis sidecar as I have a redis cache module.

Regarding the SFTP service, I ll try this afternoon to add it.

But my use case is quiet complicated and maybe you can help me with some precious insights. :-)

In my workflow, when I develop a website, I have 3 version of it, a dev/preprod/prod version, and I would like to group these 3 deploy as a project and give the sftp access only for the dev one. But it requires only 2 mariadb database one for dev/preprod and the other for the production. Also, I wanna restrict access to them due to the RGDPD laws.

How would you advise me to manage this kind of workflow ?

What do you think of this project for managing k8s deploys ? Would it be helpful for my use case ?
https://github.com/loft-sh/loft

Many thanks for any insights or inputs.

Cheers,
Luc Michalski

**Comment by javsalgar** [comment]
Hi,

From what you say, it looks to me that the way to work would be creating container images that you deploy in the different installations (something closer to immutable infrastructure). I do not know about loft, but I would advise you to take a look to Okteto, which may be closer to what you are looking for. https://okteto.com/

About a Varnish container, I will open a task for investigating it.

**Comment by lucmichalski** [comment]
Hi,

Many thanks for your reply :-)

Will wach the varnish container task too.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/prestashop#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
