### ISSUE TITLE
cassandra: jmx port exposed in Service

### ISSUE THREAD

**Issue by howardjohn** [bitnami/charts#5294]
https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/headless-svc.yaml#L29-L31

The JMX port is exposed in the Service, but its actually listening on localhost in the pod. Therefor, it will not be reachable, so I am not sure it makes sense to expose it in the service

**Comment by juan131** [comment]
Hi @howardjohn 

I agree with you, I don't see any advantage on exposing the port at service level.

That said, Cassandra chart supports using a custom configuration for Cassandra using the "existingConfiguration" parameter (see https://github.com/bitnami/charts/tree/master/bitnami/cassandra#using-custom-configuration), so I guess that somebody could configure Cassandra to listen on every interface (instead of localhost).

**Comment by howardjohn** [comment]
That's fair, feel free to close this if this is intended then

**Comment by juan131** [comment]
I don't think it's intended @howardjohn . I'm just saying that the port can be listening in every interface when using a custom configuration.

What do you think about removing it by default from the headless service, and adding a `service.extraPorts` parameter so users can open any extra port they want when using a custom configuration?

**Comment by AkashRajvanshi** [comment]
hey, can you please explain how I expose the JMX port? so I can access it from outside!

**Comment by juan131** [comment]
Hi @AkashRajvanshi 

You can create a tunnel using `kubectl port-forward ...`  (see https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/). Otherwise, it's not possible to do access this port using the current chart since that port is not exposed in the Cassandra svc.

I'm just curious: why do you want to access that port externally?

**Comment by AkashRajvanshi** [comment]
I'm just curious: why do you want to access that port externally?
@juan131 - to use nodetool in another pod ( backup pod )

**Comment by juan131** [comment]
@AkashRajvanshi to access it from another pod, you can access using the FQDN that the headless service creates for each Cassandra replica. You don't need to expose it outside the cluster to access that port.

That said, you'll have to ensure Cassandra listen on `0.0.0.0` instead of `127.0.0.1` for this port.

**Comment by aeg12345** [comment]
Greetings, I have the same need of exposing the JMX service for monitoring purposes.
The monitoring tool is on a jumpbox which is outside kubernetes network therefore I want to expose it via nodeport.
This can be done easiliy for cqlsh port 9042 but jmx server refuses remote connections.

I tried solution mentioned in this [issue](https://github.com/bitnami/charts/issues/5574) by setting remote hostname parameters but I was not able to achieve success. 

My values yaml is:
image:
  debug: true
dbUser:
  user: cassandra
  forcePassword: false
  password: "cassandra"
cluster.seedCount: 2
replicaCount: 2
extraEnvVars:
  - name: JVM_OPTS
    value: "-Dcom.sun.management.jmxremote.authenticate=true -Dcassandra.jmx.remote.login.config=CassandraLogin -Djava.security.auth.login.config=/opt/bitnami/cassandra/conf/cassandra-jaas.config -Dcassandra.jmx.authorizer=org.apache.cassandra.auth.jmx.AuthorizationProxy -Djava.rmi.server.hostname=cassandra-test-0.cassandra-test-headless.ksps248.svc.cluster.local -Dcassandra.jmx.remote.port=7199"
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: true
  runAsUser: 1000640001

I tried setting both JVM_OPTS and CASSANDRA_CFG_ENV_JVM_OPTS both was not able to succeed.
I also tried server.hostname as 0.0.0.0 or set the cluster ip address of the nodeport service that did not work either. 

I tried setting custom configuration mentioned [here](https://docs.bitnami.com/kubernetes/infrastructure/cassandra/configuration/customize-new-instance/) but the configmap values are not mentioned I tried setting configmap value as: 

cassandra-env.sh: "JMX values"

but it failed so I guess it only customizes the cassandra.yaml.
There was no documentation about what config files can be set and which one are configurable I would be grateful if you can provide me with some if I missed it.


The cassandra yaml parameters about authorizer and authenticator were already set correctly for JMX with cassandra authentication so I did not meddle with it.

I would be grateful if you can guide me through a way to enable remote JMX

Thanks,
Regards,
