### ISSUE TITLE
airflow logs no host supplied

### ISSUE THREAD

**Issue by apalmercari** [bitnami/charts#5377]
Hi Team,

We are getting below error frequently and tasks are getting failed? Any solution for this ?

*** Log file does not exist: /opt/bitnami/airflow/logs/dag_name/last_update_job/2021-02-02T13:57:39.393002+00:00/1.log
*** Fetching from: http://:8793/log/dag_name/last_update_job/2021-02-02T13:57:39.393002+00:00/1.log
*** Failed to fetch log file from worker. Invalid URL 'http://:8793/log/dag_name/last_update_job/2021-02-02T13:57:39.393002+00:00/1.log': No host supplied

Sometimes it works 
*** Log file does not exist: /opt/bitnami/airflow/logs/dag_name/last_update_job/2021-02-02T14:01:44.901046+00:00/1.log
*** Fetching from: http://airflow-worker-0.airflow-worker-headless.default.svc.cluster.local:8793/log/dag_name/last_update_job/2021-02-02T14:01:44.901046+00:00/1.log

**Comment by migruiz4** [comment]
Hi @apalmercari ,

It is possible the issue is caused by this airflow bug: https://issues.apache.org/jira/browse/AIRFLOW-4922

People having the same issue recommend:
- Rerunning the task
- Increasing your pod resources
- Checking manually if the logs are inside the pod using `kubectl exec -it <pod_name> -- bash`
- Increasing the airflow setting `log_fetch_timeout_sec`

I'm sorry but I may not be able more helpful as this seems to be an airflow issue and not an issue of the chart itself.

I hope you find the above information helpful.

**Comment by apalmercari** [comment]
In my case, it was due to pod resources.

**Comment by ecda909** [comment]
What did you update your resource limits and requests to?
