### ISSUE TITLE
Support for Netbox / new Chart proposal

### ISSUE THREAD

**Issue by MaxRink** [bitnami/charts#5397]
**Which chart**:
New chart, Netbox

**Is your feature request related to a problem? Please describe.**
We are using netbox as an DCIm tool and are running it on K8s. For that, ive built an helm chart based upon your template. Its functional, but not fully documented yet. 
Im wondering if there would be any interes from your side to include that chart ( https://github.com/MaxRink/charts/tree/netbox/bitnami/netbox ) in your chart repository.
If so i would spend the time to polish it up and create the necassesary repo for an bitnami image of netbox.
Netbox itself uses an Apache2 Lincence so from that side it should work.

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines (it seems you already used it).

If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

 The container part could take some time since it is something we need to do on our side and due to limited resources and other priorities, I can't provide you an ETA for that.

**Comment by MaxRink** [comment]
> If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines (it seems you already used it).
> 
Great, i will add the documentation it still lacks before tho. :D
> If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.
> 
Yeah, two of those actually came from my collegue 😅
Ive already employed his mind for a few things .
The image isnt part yet, but ive written the chart in a way that the original container works too

**Comment by carrodher** [comment]
That's fine, so if you create the PR we will work on adding the image into our internal release pipeline (although I can't provide an ETA, it will depend on other priorities that the team has).

This step is needed to have full control over the images bundled in the Bitnami Helm Charts so we can handle when and how they are built to, for example, release them on a daily basis updating the system packages in order to avoid fixable CVEs in the images.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
