### ISSUE TITLE
[bitnami/nginx-ingress-controller] It is not clear how to enable tcpConfigMap / udpConfigMap except by extraargs

### ISSUE THREAD

**Issue by Andrei-Paul** [bitnami/charts#5421]
**Which chart**:
Nginx Ingress Controller (7.4.2)

**Describe the bug**
I want to enable --tcpConfigMap and --udpConfigMap support
I can only seem to get them enabled by extraargs

**To Reproduce**
I created tcp-services-configmap and udp-services-configmap ConfigMaps based on comments for tcpConfigMapNamespace(1) and udpConfigMapNamespace(2) in the chart.
I tried:
- leaving them(1,2) blank ( ConfigMaps and nginx-ingress-controller were in the same namespace )
- giving them(1,2) the value "$(POD_NAMESPACE)"
- giving them(1,2) the namespace explicitly ( used by nginx-ingress-controller and ConfigMaps )

**Expected behavior**
Enable --tcpConfigMap and --udpConfigMap support with tcpConfigMapNamespace(1) / udpConfigMapNamespace(2) and helm magic.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by marcosbc** [comment]
Hi @Andrei-Paul, note that what you're instructed to specify is the namespace where the configmaps are located. And they need to follow a very specific name:

* TCP config map: `RELEASE-nginx-ingress-controller-tcp`
* UDP config map: `RELEASE-nginx-ingress-controller-udp`

Where `RELEASE` is your release name. I.e. if you installed with `helm install my-release` then it is `my-release`.

(And they need to be located in the namespace specified by the specific parameter.)

Could you check if this solves your issues? If not, I would recommend you to run `helm template` instead of `helm install` and check if the `--tcp-services-configmap=` flag is added (a simple search is enough).

**Comment by Andrei-Paul** [comment]
Thank you for the suggestions. I used Lens -> Charts -> Install, so I have no idea what 'my-release' is in my case, but I'll do this again in the following days and come back with results.

```
    TCP config map: RELEASE-nginx-ingress-controller-tcp
    UDP config map: RELEASE-nginx-ingress-controller-udp
```
^^ It would be nice to have this piece of info in the chart or in the docs.

**Comment by marcosbc** [comment]
Hi @Andrei-Paul, I agree it's confusing.

After some investigating, I found that this particular parameter is based on the official NGINX Ingress Controller Helm chart as you can see [here](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-daemonset.yaml#L85), with the only difference that it's not parametrized.

It seems like it did once support the parameter, but it was removed in the following commit: https://github.com/kubernetes/ingress-nginx/commit/9f3fbc30145e78bfded4a2fdbdb44ca02dfee122

In fact, the official chart apparently seems to create the configmap [by itself](https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-configmap-tcp.yaml) if `tcp` is enabled (and similar for `udp`).

Therefore it seems like this is a bug that we should fix. It does not look like the official chart allows specifying `--tcp-services-configmap` though.

I've created an internal task for fixing this issue, but unfortunately I cannot give an ETA for when this will be fixed. If you want to speed up the process, feel free to send a PR, we'd be happy to review and help with the release.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
