### ISSUE TITLE
[bitnami/drupal] Upgrading drupal with drush step crash when drupalSkipInstall=true

### ISSUE THREAD

**Issue by xmsanchez** [bitnami/charts#5434]
**Which chart**:
bitnami/chart

**Describe the bug**
When "drupalSkipInstall=true" is set, I get this crash:

```
drupal 14:53:15.83 DEBUG ==> Upgrading Drupal database with drush...

In BootstrapHook.php line 32:                                                                      
  Bootstrap failed. Run your command with -vvv for more information.  
                                                                      
updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]] [--no-cache-clear] [--no-post-updates] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command>
```

If the parameter is disabled, the database gets created and populated and the example site shows up. If afterwards I try to add the parameter skip, I get the above crash. I'm testing with an **external database**, didn't try with a MariaDB.

**To Reproduce**

Deploy the chart with drupalSkipInstall=true. I've tested different combinations of versions. For example, any of these:

```
- Image tag -> 8.9.13-debian-10-r16
- Chart version -> 9.1.5
```

```
- Image tag -> latest
- Chart version -> latest
```

**Expected behavior**
Should detect the database, do any required upgrades and start serving through apache.

**Version of Helm and Kubernetes**:

Tested both with helm2 (older chart versions) and helm3.

- Output of `helm3 version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

- Output of `helm2 version`:

```
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

Full helm command used:

```
export IMAGE_TAG=8.9.13-debian-10-r16
export CHART_VERSION=9.1.5
helm3 upgrade -i test-drupal --force bitnami/drupal \
     --namespace test-drupal \
     --set replicaCount=1 \
     --set drupalUsername=admin \
     --set drupalPassword=randomPass \
     --set service.type=ClusterIP \
     --set image.registry=bitnami \
     --set image.repository=drupal \
     --set image.tag=$IMAGE_TAG \
     --set image.debug=true \
     --set ingress.enabled=true \
     --set ingress.hostname="test-drupal" \
     --set ingress.ingress.hosts[0].name="test-drupal.mydomain" \
     --set ingress.tls[0].hosts[0]="test-drupal.mydomain" \
     --set ingress.certManager=true \
     --set mariadb.enabled=false \
     --set drupalSkipInstall=true \
     --set externalDatabase.user=$(kubectl get secret -n test-drupal drupal-secret -o jsonpath="{.data.DATABASE_USER}" | base64 -d) \
     --set externalDatabase.password=$(kubectl get secret -n test-drupal drupal-secret -o jsonpath="{.data.DATABASE_PASS}" | base64 -d) \
     --set externalDatabase.host=$(kubectl get secret -n test-drupal drupal-secret -o jsonpath="{.data.DB_HOSTNAME}" | base64 -d) \
     --set externalDatabase.database="drupal-test" \
     --set externalDatabase.port="3306" \
     --set allowEmptyPassword=false \
     --wait
```

**Comment by carrodher** [comment]
According to the logs, we can add `-vvv` to the `drush` command in order to improve the verbosity and maybe see what is happening, for that we can build a custom image.

But first, let's take a look at the code:

- [Here](https://github.com/bitnami/bitnami-docker-drupal/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L292) there is a function `drush_execute` that run `drush` with the `--root` flag:
```bash
drush_execute() {
    if am_i_root; then
        debug_execute gosu "$WEB_SERVER_DAEMON_USER" drush "--root=${DRUPAL_BASE_DIR}" "$@"
    else
        debug_execute drush "--root=${DRUPAL_BASE_DIR}" "$@"
    fi
}
```
in this place, we can add `-vvv` to increase the verbosity.
- There is another function (``) [here](https://github.com/bitnami/bitnami-docker-drupal/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L412) that calls the above one using `updatedb` as parameter, resulting in `drush --root=/opt/bitnami/drupal updatedb`
```bash
drupal_update_database() {
    debug 'Upgrading Drupal database with drush...'
    drush_execute "updatedb"
}
```

- This function is executed in the`else` statement at [this point](https://github.com/bitnami/bitnami-docker-drupal/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh#L150):
```bash
        if ! is_boolean_yes "$DRUPAL_SKIP_BOOTSTRAP"; then
            # Perform initial bootstrapping for Drupal
            info "Installing Drupal site"
            drupal_site_install
            if ! is_empty_value "$DRUPAL_ENABLE_MODULES"; then
                info "Enabling Drupal modules"
                drupal_enable_modules
            fi
            if ! is_empty_value "$DRUPAL_SMTP_HOST"; then
                info "Configuring SMTP"
                drupal_configure_smtp
            fi
            info "Flushing Drupal cache"
            drupal_flush_cache
        else
            info "An already initialized Drupal database was provided, configuration will be skipped"
            drupal_update_database
        fi
```

At the end of the cascade, the execution should be:
```console
INFO  ==> An already initialized Drupal database was provided, configuration will be skipped
DEBUG ==> Upgrading Drupal database with drush...
$ drush --root=/opt/bitnami/drupal updatedb
```
You're facing the issue once executed the above command.

-------------------------------------------------------------------

In order to build the custom image (same image used by default but increasing the verbosity):
```console
$ git clone https://github.com/bitnami/bitnami-docker-drupal.git
$ cd bitnami-docker-drupal/9/debian-10
# Implement below changes
$ docker build -t your_repo/drupal:latest
$ docker push your_repo/drupal:latest
```
Changes:
```diff
diff --git 9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh 9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh
index d50ae4d..3330feb 100644
--- 9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh
+++ 9/debian-10/rootfs/opt/bitnami/scripts/libdrupal.sh
@@ -293,7 +293,7 @@ drush_execute() {
     if am_i_root; then
         debug_execute gosu "$WEB_SERVER_DAEMON_USER" drush "--root=${DRUPAL_BASE_DIR}" "$@"
     else
-        debug_execute drush "--root=${DRUPAL_BASE_DIR}" "$@"
+        debug_execute drush -vvv "--root=${DRUPAL_BASE_DIR}" "$@"
     fi
 }

@@ -410,6 +410,8 @@ drupal_flush_cache() {
 #   None
 #########################
 drupal_update_database() {
+    debug 'Checking status...'
+    drush_execute "status"
     debug 'Upgrading Drupal database with drush...'
     drush_execute "updatedb"
 }
```

Install/Upgrade the chart adding/modifying the following parameters:
```
--set image.repository=my_repo/drupal \
--set image.tag=latest \
--set image.pullPolicy=Always
```
in this way, the chart is going to be deployed using your custom image where the verbosity was increased. With that, we will try to figure out what is the issue.

**Comment by xmsanchez** [comment]
Thanks for the quick reply. Before I saw your answer I already added verbosity. The error it returns is:

```
 [debug] Add service modifier [0.14 sec, 9.26 MB]
 [bootstrap] Try to validate bootstrap phase 5 [0.14 sec, 9.26 MB]
 [bootstrap] Unable to connect to database. More information may be available by running `drush status`. This may occur when Drush is trying to bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details. [0.14 sec, 9.28 MB]
 [bootstrap] Could not bootstrap at phase 5 [0.14 sec, 9.27 MB]
```

What is weird, is that it states that cannot connect to the database, although when "drupalSkipInstall" is set to true it successfully connects and populates the DB. With the exact same parmeters (only that flag on/off).

I don't really know how to debug it further.

**Comment by carrodher** [comment]
I was able to reproduce the issue by installing it from scratch (only with `--set drupalSkipInstall=true`), it seems the `SKIP_BOOTSTRAP` logic is not properly implemented. When the application is initialized following the regular/default path, the configuration files are created setting the required parameters but following the `SKIP_BOOTSTRAP` path, the configuration is not properly set, so it is not possible to connect with the database (it doesn't matter if it is an external database or the MariaDB chart bundled as part of the Drupal Helm Chart).

As it seems there is not a valid/quick workaround, I just created an internal task in order to investigate and fix the issue. We will need to modify the logic in the container (see functions in the previous comment). I will add the `on-hold` label to this issue to avoid "stale bot" closing it. We will update this thread with some news when we make any significant progress

**Comment by mralexho** [comment]
Our team is also experiencing the same issue. Thanks for your prompt response.

**Comment by carrodher** [comment]
Thanks for letting us know, unfortunately, due to other priorities in the team the task is still on our backlog and I can't provide a specific ETA. On the other hand, the configuration logic is based on Bash scripts placed in the _rootfs/_ folder that appears in the container repository (https://github.com/bitnami/bitnami-docker-drupal), just in case you want to contribute by sending a PR. Our team will be happy to review it. Thanks again

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/drupal#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.

**Comment by colans** [comment]
Because we came across this, and couldn't get past it, we wrote a Terraform module instead.  See details at [Want to Run Drupal in Kubernetes? Try Our New Terraform Module](https://backupscale.com/posts/drubernetes-terraform-module-for-kubernetes-clusters/).
