### ISSUE TITLE
[Bitnami/Airflow] Dags Fail when running using Kubernetes Executor

### ISSUE THREAD

**Issue by raefezzeldin** [bitnami/charts#5491]
I have Enabled the Kubernetes Executor using the following configuration.

![image](https://user-images.githubusercontent.com/1645929/107884296-df2cc800-6efc-11eb-831d-324843f88b83.png)

and I am getting the following error.

![image](https://user-images.githubusercontent.com/1645929/107884307-f66bb580-6efc-11eb-8108-efaaf6832d4b.png)

**Comment by marcosbc** [comment]
This is a duplicate issue of #5413:

>It seems like this issue could be related to https://github.com/apache/airflow/issues/11696, for which a PR was sent: https://github.com/apache/airflow/pull/12598. I've created an internal task to fix this issue, but unfortunately I cannot give an ETA for when this would be fixed.
>
>However, if you want to speed up the process, you could always contribute by sending a PR, we'd be happy to review it and help release the chart with the fix.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
