### ISSUE TITLE
[bitnami/thanos] Option to run Thanos Compactor as CronJob

### ISSUE THREAD

**Issue by lorenzo-biava** [bitnami/charts#5509]
**Which chart**:
Thanos (latest) v3.9.0 +

**Is your feature request related to a problem? Please describe.**
The Compactor is run as a deployment. While this is a convenient way to run it, it's not necessarily efficient from a resource usage point of view. For instance, with our dataset, compactions for longer intervals (e.g. 7/14 days) require a significant amount of memory (20-40GB) and only happen once a week or so.

Having the Compactor running constantly, using minimal resources most of the time, tends to be kind of wasteful in this situation. On the other hand, granting it a smaller amount of memory requires us to react to incidents when big compactions happen and it gets stuck due to OOM.

**Describe the solution you'd like**
The ability to choose how to run the Compactor: Deployment or CronJob.

**Describe alternatives you've considered**
N/A

**Additional context**
The Compactor command does indeed run to completion by default, so the CronJob support has been envisioned (https://github.com/thanos-io/thanos/blob/master/docs/components/compact.md#compactor).

I might be able to work on a PR if you believe this feature is viable.

**Comment by andresbono** [comment]
Hi @lorenzo-biava, thank you very much for suggesting this feature! I think having the option to run Compactor as Deployment or Cronjob makes sense, and as you point, Compactor supports both modes.

> I might be able to work on a PR if you believe this feature is viable.

That would be great! Contributions are more than welcome. Please link this issue into the PR for reference. We will be happy to review it :+1:

**Comment by djsly** [comment]
reopen

**Comment by migruiz4** [comment]
Reopening because it shouldn't have been closed by the stale-bot

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
