### ISSUE TITLE
Integrate with Auzre AD for identity management

### ISSUE THREAD

**Issue by robinsomarajv** [bitnami/charts#5533]
How to configure the helm charts to pass the Azure AD identity management properties for Spring cloud dataflow

Chart: spring-cloud-dataflow-2.4.2

Unable to pass the identity management values and no description available

**Comment by alemorcuq** [comment]
Hi, @robinsomarajv.

I'm afraid that is not possible at the moment. I'm going to create an internal task to add this feature, but unfortunately I can't give you an ETA. In the meantime, feel free to create a new PR and we will gladly review it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
