### ISSUE TITLE
[bitnami/airflow] Chart Ignores Web Container Image Repository

### ISSUE THREAD

**Issue by don4of4** [bitnami/charts#5587]
While trying to update the web container for Airflow, I noticed that the `web.image.repository` param is currently ignored in the chart.

### Issue
See [values.yaml](https://github.com/bitnami/charts/blob/71fb99f541e971b1daafaa20ffb7d18b153b8d60/bitnami/airflow/values.yaml#L547) where the repo flag is specified, but [the template for web](https://github.com/bitnami/charts/blob/71fb99f541e971b1daafaa20ffb7d18b153b8d60/bitnami/airflow/templates/web/deployment.yaml#L67) does not respect this value.

This is important since the Azure Container repo lags the docker.io repo, which is an irritation if we need the latest tag.

### Desired Result
If the `image.respository` is defined for the web container, it should be respected.

### The Fix
I believe this can be fixed by updating the line above with something similar to the other images in this chart:
- [The template for metrics](https://github.com/bitnami/charts/blob/71fb99f541e971b1daafaa20ffb7d18b153b8d60/bitnami/airflow/templates/metrics/deployment.yaml#L43) uses `{{ include "airflow.metrics.image" . | quote }}`.
- [The template for git](https://github.com/bitnami/charts/blob/71fb99f541e971b1daafaa20ffb7d18b153b8d60/bitnami/airflow/templates/_git_helpers.tpl#L77) uses `image: {{ include "git.image" . | quote }}`.
- [The template for the scheduler](https://github.com/bitnami/charts/blob/71fb99f541e971b1daafaa20ffb7d18b153b8d60/bitnami/airflow/templates/scheduler/deployment.yaml#L68) references `image: {{ include "airflow.schedulerImage" . | quote }}`  which is defined in [the helper](https://github.com/bitnami/charts/blob/ecd6662b0e448f391444541392108d34b048b1f2/bitnami/airflow/templates/_helpers.tpl#L72).  [The template for worker](https://github.com/bitnami/charts/blob/ecd6662b0e448f391444541392108d34b048b1f2/bitnami/airflow/templates/_helpers.tpl#L79) does the same.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for noticing this and providing the fix. 
  Would you like to send a PR ? We will be glad to review and merge it.

**Comment by don4of4** [comment]
This is still an open issue -- I have not had a chance to create a PR.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
