### ISSUE TITLE
RabbitMQ Chart service to be used by other services

### ISSUE THREAD

**Issue by GerryWilko** [bitnami/charts#5595]
Hello,

Apologies for the basic question but I am struggling to understand how to get the RabbitMQ Helm chart services to work.

A simple deploy of the helm chart into my cluster creates 2 services -rabbitmq and -rabbitmq-headless.

If I try to use the -rabbitmq service internally I cannot connect with the C# RabbitMQ.Client Nuget package over AMQP.

Using port forwarding I can access the management interface and I can telnet from the container which cannot talk to the AMQP service and it appears to open the telnet fine.

I am running this within AKS but I can replicate the issue with a local kubernetes cluster too so it appears to be unrelated to AKS. If I set the service type to nodeport and use that then everything works fine but ClusterIP and LoadBalander I cannot get the service to work.

I appear to be having a similar issue to this: https://stackoverflow.com/questions/65506595/how-to-access-rabbitmq-cluster-configured-on-azure-aks-to-send-message-on-queue

This SO suggests using the -headless service instead. Is this correct? If it is would someone be able to take a moment to explain the difference between the -headless and normal services here? My understanding is that the kubernetes service discovery is bypassed with -headless in which case how the cluster work with many replicas.

Thanks in advance,
Gerard

**Comment by carrodher** [comment]
k8s (at the end Helm is using k8s), allows clients to discover pod IPs through DNS lookups. Usually, when you perform a DNS lookup for a service, the DNS server returns a single IP (the service’s cluster IP). But if you tell k8s you don’t need a cluster IP for your service (you do this by setting the clusterIP field to None in the service specification ), the DNS server will return the pod IPs instead of the single service IP. Instead of returning a single DNS A record, the DNS server will return multiple A records for the service, each pointing to the IP of an individual pod backing the service at that moment. Clients can therefore do a simple DNS A record lookup and get the IPs of all the pods that are part of the service. The client can then use that information to connect to one, many, or all of them.

Official info at https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

In this case, when deploying the chart from scratch (or once deployed executing `helm get notes RELEASE_NAME`) you can see the different ways to connect to rabbitmq according to the parameters (such as service type) used during your deployment

**Comment by GerryWilko** [comment]
Ahh I see perfect. That makes sense. Thank you for taking the time to explain that. I shall use the headless service then.

Also I estabilished the cause of my original issue. It was actually just that my cluster resources were restricting the rabbitMQ pod as it defaults to `BestEffort`. In my case I settled on the following `Burstable` resource requests:

``` yaml
resources:
  requests:
    memory: "400Mi"
    cpu: "150m"
  limits:
    memory: "1Gi"
    cpu: "500m"
```
