### ISSUE TITLE
[bitnami/kafka] Question about revision difference in bitnami images

### ISSUE THREAD

**Issue by nc-ruth** [bitnami/charts#5663]
Hi Bitnami,

I was wondering why there is a revision difference between the image being used for running kafka, and the image being used for provisioning kafka topics?

The exact lines are: 
https://github.com/bitnami/charts/blob/3bbab7d4876edd35da13a3ae4df85ebc6c6edec0/bitnami/kafka/values.yaml#L17
https://github.com/bitnami/charts/blob/3bbab7d4876edd35da13a3ae4df85ebc6c6edec0/bitnami/kafka/values.yaml#L799 

Line 17 specifies the kafka image for running kafka.
Line 799 specifies the kafka image used for provisioning kafka topics.

There must be some logical reason to why this is implemented using two different revisions of the same image, but I can't figure it out. 

Best regards,
Ruba

**Comment by Mauraza** [comment]
Hi @nc-ruth,

we are going to investigate why this is happened, as far as I know, should be the same tag. We will update this thread when we have more information.
Thanks for reporting!

**Comment by nc-ruth** [comment]
Hi @Mauraza, do you have any updates in this matter?

**Comment by Mauraza** [comment]
Hi @nc-ruth,

Now, we have an internal task to solve that in the values.yaml, both tags should be the same.

**Comment by nc-ruth** [comment]
Cool, thank you for the update @Mauraza

**Comment by carrodher** [comment]
Hi @nc-ruth, are you having any issues because of that? I'm asking just in case you have some specific use case where the difference in the revision can cause any issue.

We are releasing container images on a daily basis, basically to maintain the system packages up-to-date in order to prevent security issues affecting the bundled Debian system packages. Usually, the difference between an image with `-rX` and `-rX+1` is just the second one that was released one day later so the packages were updated by running `apt-get update && apt-get install ...`

I agree that in order to maintain some consistency in the _values.yaml_ is better to have the same revision in both images and that is why we created an internal task to work on that. Currently, our release pipeline is using a new image for what we consider the main image in the Helm Chart and the previous one in those images used as secondary containers. Although, I can't think of any issue produced by this inconsistency apart from the aesthetic part and having to pull two different images in the cluster (images that share more of the layers). That is why I want to know if there is something else that is causing any issue in your deployment.

**Comment by nc-ruth** [comment]
Hi @carrodher, 

So sorry for the late reply! I think I missed the notification of your message.
We haven't had any issues with it (yet), and it was only out of curiosity I have raised the question. 

But I believe by using the same revision wouldn't make any problems for us, and we believe that using the same revision is more efficient. 

Thank you for your answer, and thanks for setting up an internal task that will fix this :)

**Comment by carrodher** [comment]
Hi, a couple of days ago we released a new Kafka major version introducing those changes. Now there is only one Kafka image that is used in both places, see the Upgrading section at https://github.com/bitnami/charts/blob/master/bitnami/kafka/README.md.
In the same way this issue was fixed for other charts, see

**Comment by nc-ruth** [comment]
Hi @carrodher, thank you for the update. 
Should we close this issue? I assume the issue is not relevant any longer?

**Comment by carrodher** [comment]
Yep, I'm closing it. Thanks
