### ISSUE TITLE
Add checksum

### ISSUE THREAD

**Issue by lassanouer** [bitnami/charts#5723]
**Which chart**:
airflow chart

**Is your feature request related to a problem? Please describe.**
if we re-deploy after changes on requirements.txt or just any config-map, or password passed in a file..., the pod should restart, and to force it, checksum is the best solution

**Comment by carrodher** [comment]
This approach is used for the default ConfigMap, see
```console
$ ag 'checksum/' -B 1
templates/worker/statefulset.yaml
33-      annotations:
34:        checksum/configmap: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}

templates/web/deployment.yaml
25-      annotations:
26:        checksum/configmap: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}

templates/scheduler/deployment.yaml
26-      annotations:
27:        checksum/configmap: {{ include (print $.Template.BasePath "/config/configmap.yaml") . | sha256sum }}
```

And it is being taken into account when the template is rendered:
```console
$ helm template airflow bitnami/airflow -s templates/worker/statefulset.yaml
# Source: airflow/templates/worker/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
...
  template:
    metadata:
      annotations:
        checksum/configmap: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
```

but probably it needs some modification to support configmap provider by the user instead of the default one (same for secrets). Would you like to send a PR implementing these changes? We'll be happy to review it
