### ISSUE TITLE
[RabbitMQ] Credential issues after reinstall

### ISSUE THREAD

**Issue by mladedav** [bitnami/charts#5734]
**Which chart**:
RabbitMQ 8.11.2
(possibly other charts have similar issues if I understand correctly)

**Is your feature request related to a problem? Please describe.**
Credentials persist between reinstallation of charts (as described in the troubleshooting guide.

When trying to upgrade the chart it notifies developers that they need to supply credentials. I though I was too smart for that and simply reinstalling it would do since I didn't mind losing any data. It took me a few hours to figure out that the original credentials I luckily still had in one of my terminals still worked.

**Describe the solution you'd like**
Adding more explanation to the upgrade error that uninstall/install doesn't work either. I think a bit of credentials explanation (one sentence with a link to the troubleshooting page]) could be also part of NOTES.txt, but I would understand if you wouldn't agree with that.

**Describe alternatives you've considered**
Everyone properly reads documentation and the troubleshooting page.

**Comment by carrodher** [comment]
Thanks for creating this issue, you are referring to [this troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases), right? In fact, the specific version is pointed in the link.

We created the guide because it is a known issue, in the same way, the guide appears in the bug report template, see
![Screenshot 2021-03-10 at 11 07 08](https://user-images.githubusercontent.com/13216600/110612735-c4164680-8190-11eb-953c-686561efbbbd.png)

Being said that, it is true that the deployment notes are also a valid place to show this kind of information since it is the first place where the user is going to see after the installation (opening an issue or looking for a guide in Google is a 2nd step). Would you like to create a Pull Request with a POC of what do you expect to see in the notes? We will be happy to review it and provide feedback, as well as adding it to other charts if needed.

Apart from that, we are investigating different alternatives to handle passwords during upgrades, such as using the `lookup` function, to get rid of this kind of issues, see https://github.com/bitnami/charts/pull/4831
