### ISSUE TITLE
Chart proposal for Grafana Loki

### ISSUE THREAD

**Issue by petersin0422** [bitnami/charts#5738]
**Which chart**:
Does not exist today.

**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
I am trying to deploy Grafana Loki for log management. The official Loki Helm chart comes with a very limited set of options and the maintainer is not interested in adding additional features. 

> However, the chart does not support setting up Consul or Etcd for discovery, and it is not intended to support these going forward
>
> [source](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#configuration)

**Describe alternatives you've considered**
Writing my own Helm chart.

**Additional context**
I needed this chart so I will be working on it for my own purposes and would like to contribute it back to this repository. Is this something the maintainers would be interested in, and if so, can I start a draft pull request to get feedback as I make progress? Thank you very much!

**Comment by alemorcuq** [comment]
Thanks for your suggestion, @petersin0422 ! We will check it internally and evaluate its feasibility, but due to our limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by alemorcuq** [comment]
You can use the official image for now and we will take care of creating a new image. Thanks!

**Comment by yardenshoham** [comment]
@petersin0422 did you have progress with the chart?

**Comment by petersin0422** [comment]
Good Morning,

Sorry for the delay reply. I have read more documentation on the Loki's end and understand why they are only supporting `MemberList` by default (and agree on it), since you don't have to have extra infrastructure set up. That being said, I am going to close this one since my original motive for doing this is gone. My sincere apology for the trouble to everyone.
