### ISSUE TITLE
[bitnami/redis-cluster] How to expose redis cluster service to be accessed from outside/externally?

### ISSUE THREAD

**Issue by bharat15-ml** [bitnami/charts#5776]
**Which chart**:
redis-cluster-4.4.0.

**Is your feature request related to a problem? Please describe.**
I had tried to expose the redis-cluster service to outside in following ways:

Method-1: Have made the changes only in service section of values.yaml file and deployed as service type: LoadBalancer.

![image](https://user-images.githubusercontent.com/76279928/111057341-cdfbba80-84ac-11eb-9fa4-95c2770404c8.png)
![IMG_20210314_103754](https://user-images.githubusercontent.com/76279928/111058049-d4406580-84b1-11eb-8650-d3e3c1c9a57c.jpg)

service got deployed and top of that have applied the ingress (LB-IP+PORT) to make it accessible from outside cluster. Have checked the client connection and it is working fine from inside the cluster but I am unable to access it from outside cluster.
Need some clarity on whether, this approach is correct to expose the service outside cluster or not with suitable explanation?

Method-2: Have made the changes only in cluster section of values.yaml file and deployed as externalAccess: true

![image](https://user-images.githubusercontent.com/76279928/111058782-b9242480-84b6-11eb-998b-e40242fc1951.png)

followed this article for approach-2 -  [https://docs.bitnami.com/tutorials/deploy-redis-cluster-tmc-helm-chart/](url)

After the deployment all pod got deployed as LoadBalancer and then have upgraded the chart by mentioning all LoadBalancerIP in the cluster section. by providing LoadBalancerIP, Now Is it required to put ingress for all pod here?  Is this Approach is correct to expose the service outside cluster?? 

![image](https://user-images.githubusercontent.com/76279928/111058652-ee7c4280-84b5-11eb-9c6d-45a7d1df2997.png)

Please help on this how I can redis cluster to outside accessibility?

**Comment by migruiz4** [comment]
Hi @bharat15-ml ,

Both scenarios would be valid, and choosing between them would vary depending on your use case.

I will try to sum up the differences between case 1 and 2:

- Case 1: Only the Redis service is visible from outside the cluster and it should be accessed by providing the flag `-c` when using the `redis-cli` to follow the redirection in case your request connects you with a Slave node.

- Case 2: Using `cluster.externalAccess.enabled=true` each pod will have a public IP and Redis will be configured using those IPs, in this case you can connect to any of the pods from outside the cluster. 

You can find more information about both cases in the `Cluster topology` section of the redis-cluster README: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-topology

Regarding the Ingress Controller, I'd like to clarify it is not mandatory to configure it in order to access your service externally unless you want to define rules to control the ingress traffic: https://kubernetes.io/docs/concepts/services-networking/ingress/

Also, in case you are using `networkPolicy.enabled=true`, it would be necessary to configure `networkPolicy.allowExternal=true`. Otherwise, pods will only accept incoming traffic from other pods in the cluster.

**Comment by bharat15-ml** [comment]
Thanks @migrui4, got your point. Will check both the option and check the client connectivity working.
