### ISSUE TITLE
[bitnami/mongodb] Usage of `existingConfigmap` with subchart/dependency

### ISSUE THREAD

**Issue by jord1e** [bitnami/charts#5857]
**Which chart**:
[`bitnami/mongodb`](https://github.com/bitnami/charts/tree/master/bitnami/mongodb)  version `10.11.0`

**Describe the bug**
I am trying to use a ConfigMap to customize the MongoDB chart using the `existingConfigmap` property in my `values.yaml` file.

**To Reproduce**
*`chart/Chart.yaml`*:
```yaml
apiVersion: v2
name: my-chart
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: mongodb
    version: "^10.11.0"
    repository: https://charts.bitnami.com/bitnami
```
*Update dependencies*
```
helm dependency update
```
*`chart/values.yaml`*
```yaml
# other config ...
existingConfigmap: mongodb-configmap
# other config...
```
*`chart/templates/mongodb-configmap.yaml`*
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongodb.auth.enabled: false
```
*Helm command*
```
helm upgrade --install my-chart --values chart/values.yaml chart
```

**Expected behavior**
The `mongodb.auth.enabled` property is set to `false`.

**Actual behavior**
```
Error: UPGRADE FAILED: template: <project>/charts/mongodb/templates/NOTES.txt:174:4: executing "<project>/charts/mongodb/templates/NOT
ES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $passwordValidationErrors) "context" $)>: error
 calling include: template: <project>/charts/mongodb/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwor
ds.empty" at <fail>: error calling fail:
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command. To get the current
value:

        export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" my-chart-mongodb -o jsonpath="{.data.mongodb-root-passw
ord}" | base64 --decode)
```

**This does work (but i want to use a ConfigMap**
*`chart/values.yaml`*
```yaml
mongodb:
  auth:
    enabled: false
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeSta
te:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeSta
te:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
Docker desktop version `3.2.2` build `61853`

Thank you in advance.

**Comment by migruiz4** [comment]
Hi @jord1e ,

Looks like you are mixing concepts by trying to use `existingConfigmap` to load a Helm chart value.

`existingConfigmap` is used to load a custom MongoDB configuration file (mongodb.conf) using a configMap:
https://github.com/bitnami/charts/blob/7dc3f29d7abfeabcb614af63e03e923a6dfa5bc4/bitnami/mongodb/templates/replicaset/statefulset.yaml#L347-L351

And the configMap should have the following format:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  mongodb.conf:
    #your_custom_config
```

Although, even if you configure `mongodb.conf` to set `security.authorization: disabled`, the chart needs the value `mongodb.auth.enabled` to build the templates accordingly, as it is used to set the pod environment variables. For example:

https://github.com/bitnami/charts/blob/7dc3f29d7abfeabcb614af63e03e923a6dfa5bc4/bitnami/mongodb/templates/replicaset/statefulset.yaml#L236-L254

And it is also used to determine if the chart needs to include a secret or not:
https://github.com/bitnami/charts/blob/7dc3f29d7abfeabcb614af63e03e923a6dfa5bc4/bitnami/mongodb/templates/_helpers.tpl#L164-L172

If you have further questions about how to override values for a subchart, I'd recommend having a look at the following link:
https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

The reason why you see this message:
```
Error: UPGRADE FAILED: template: <project>/charts/mongodb/templates/NOTES.txt:174:4: executing "<project>/charts/mongodb/templates/NOT
ES.txt" at <include "common.errors.upgrade.passwords.empty" (dict "validationErrors" (list $passwordValidationErrors) "context" $)>: error
 calling include: template: <project>/charts/mongodb/charts/common/templates/_errors.tpl:18:48: executing "common.errors.upgrade.passwor
ds.empty" at <fail>: error calling fail:
PASSWORDS ERROR: you must provide your current passwords when upgrade the release
    'auth.rootPassword' must not be empty, please add '--set auth.rootPassword=$MONGODB_ROOT_PASSWORD' to the command. To get the current
value:

        export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace "default" my-chart-mongodb -o jsonpath="{.data.mongodb-root-passw
ord}" | base64 --decode)
```

Is because the chart validates MongoDB password is provided if `mongodb.auth.enabled=true`
https://github.com/bitnami/charts/blob/master/bitnami/common/templates/validations/_mongodb.tpl#L11-L46

**Comment by jord1e** [comment]
Sorry for the late reply.

Thank you for the response @migruiz4, everything is clear now and it's really appreciated 😄.
