### ISSUE TITLE
Addition of SonarQube Helm Chart

### ISSUE THREAD

**Issue by iamsudip** [bitnami/charts#5858]

**Comment by javsalgar** [comment]
Thank you for the suggestion! I will forward this to the team for evaluation.

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by carrodher** [comment]
Thanks for your patience, the _bitnami/sonarqube_ Helm chart was published some minutes ago.
The code was already merged in this GH repo (see https://github.com/bitnami/charts/pull/7819). In some hours, the chart package should be available in the Bitnami Helm repository.
