### ISSUE TITLE
[bitnami/influxdb] Not Actually Support Infuxdb-v2.0 with HA Implementation

### ISSUE THREAD

**Issue by wemod123** [bitnami/charts#5866]
**bitnami/influxdb**
v2.1.0

**Describe the bug**
With HA Implementation, In the influxdb-v2.0 UI, after login, the session will expire after a short time, or just expire immediately.

But If just setup a standalone instance, error will not happen, everything works good.

**To Reproduce**
- Setup HA instances, for example with repilicasCount of 3
- Go to web browser and try to login from UI
- Will succeed when first try, but session will expire after several interaction in UI
- And after try several interaction in UI, the session just expire immediately after login ( In the UI, Press F12, go to network tab, you will find your login is succeed with good session returned, but next call with /me, will got 401 error, means session is not authorized )

**Expected behavior**
The HA implementation should just perform same as the standalone implementation

**Version of Helm and Kubernetes**:
Helm: v3.0
Kubernetes: 1.19

**Additional context**
I just guess with HA setup, the session is not perfectly shared across instance, but also I have further concern data consistence etc. 

Has any other got this experience, and how to solve?  Or had I miss some important config?

**Comment by migruiz4** [comment]
Hi @wemod123 ,

I followed your steps to reproduce the issue but the behavior you described didn't happen in my case using a fresh install.

As you can see below in the screenshot, I tried interacting with the UI and with an idle session for several minutes and the `/me` request was successful every attempt:

![image](https://user-images.githubusercontent.com/37381070/112112158-7698d100-8bb5-11eb-9848-333221d68896.png)

For this test, I used default values and installed with the following command:
```
helm install influx bitnami/influxdb --set influxdb.replicaCount=3,architecture="high-availability"
```

Does your environment have any additional configuration? Do your pods' logs show errors or warnings?

**Comment by wemod123** [comment]
Hi @migruiz4 , thanks for reply,

I test again, with the default values set exactly same as you mentioned in your reply:

```
helm install influx bitnami/influxdb --set influxdb.replicaCount=3,architecture="high-availability"
```

And I still got error like below, which shows with same session-id, some of the request succeed, but not all session works:
![image](https://user-images.githubusercontent.com/26819270/112159815-826fac00-8c24-11eb-8a77-89e150f44587.png)

While as previously described the session expired immediately case is I set relay.replicaCount=2

I check the logs from pods, said 

` ... msg=Unauthorized log_id=... error="session not found"`

-----------------------------------------------------------

And further more about just the relay, I had check the [relay repo](https://github.com/influxdata/influxdb-relay), 

@migruiz4 Do you have any idea about the relay is functionally working with Influxdb-v2.0?

**Comment by migruiz4** [comment]
Hi @wemod123 ,

The high-availability architecture we use for InfluxDB is similar to the described in the Relay repo:

```
        ┌─────────────────┐                 
        │writes & queries │                 
        └─────────────────┘                 
                 │                          
                 ▼                          
         ┌───────────────┐                  
         │               │                  
┌────────│ Load Balancer │─────────┐        
│        │               │         │        
│        └──────┬─┬──────┘         │        
│               │ │                │        
│               │ │                │        
│        ┌──────┘ └────────┐       │        
│        │ ┌─────────────┐ │       │┌──────┐
│        │ │/write or UDP│ │       ││/query│
│        ▼ └─────────────┘ ▼       │└──────┘
│  ┌──────────┐      ┌──────────┐  │        
│  │ InfluxDB │      │ InfluxDB │  │        
│  │ Relay    │      │ Relay    │  │        
│  └──┬────┬──┘      └────┬──┬──┘  │        
│     │    |              |  │     │        
│     |  ┌─┼──────────────┘  |     │        
│     │  │ └──────────────┐  │     │        
│     ▼  ▼                ▼  ▼     │        
│  ┌──────────┐      ┌──────────┐  │        
│  │          │      │          │  │        
└─▶│ InfluxDB │      │ InfluxDB │◀─┘        
   │          │      │          │           
   └──────────┘      └──────────┘           
 ```

InfluxDB OSS does not have support for clustering, but Relay allows basic HA and disaster recovery by replicating all `/write` requests to each node.

The problem you are facing is caused by the service switching nodes mid-session, as influxDB nodes do not share session information.
I couldn't reproduce it because I'm testing it in my lab where Kubernetes does not really need to balance the traffic between pods, but forwarding directly to one pod and switching mid-session did cause the same behavior you describe.

To prevent Kubernetes from switching traffic between pods it would be recommended to use `sticky sessions`. 
When using the Kubernetes service, sticky sessions can be configured by adding `sessionAffinity: ClientIP` to your service.

From [Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/service/):
> If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client's IP addresses by setting service.spec.sessionAffinity to "ClientIP" (the default is "None"). You can also set the maximum session sticky time by setting service.spec.sessionAffinityConfig.clientIP.timeoutSeconds appropriately. (the default value is 10800, which works out to be 3 hours).

Instead, if you are planning to use an Ingress controller, the configuration for sticky sessions may vary depending on the IngressClass you use.

Note: The main inconvenience of using Stickysessions is that it may cause the workload to be unbalanced between your replicas.

**Comment by migruiz4** [comment]
I have submitted this PR that adds the sessionAffinity: #5900

Could you please try using `--set influxdb.service.sessionAffinity:ClientIP` and see if the issue is resolved?

**Comment by wemod123** [comment]
@migruiz4 Thank you for reply and great work,

I tried with this new settings with updated repo, errors still happen.

But actually with a database for me, I normally call API with token authorization, instead of session, and I had not got any error if I call API with token authorization.

With regards to Token authorization, the critical thing is data consistency, I checked the relay repo, I found there is [pending feature request](https://github.com/influxdata/influxdb-relay/issues/81) of supporting Influxdb 2.0 API, means the relay is not support v2.0 API yet, so to speak seams we need further some steps, to finally using influxdb2.0-HA, while this is good discussion and stepping forward :)

**Comment by migruiz4** [comment]
Indeed, looks like InfluxDB relay hasn't received any update to support Influx 2.0.
```bash
$ curl -XPOST "http://localhost:9096/write?org=primary&bucket=primary&precision=s"   --header "Authorization: Token $TOKEN"   --data-raw "$LP_DATA"
{"error":"missing parameter: db"}
```
There is not much we can do regarding that, all I can say is that as soon as InfluxDB-relay receives an update we will release a new image and include it in our chart.

Meanwhile, High-availability will require to continue using the Influx 1.8 images.

> I tried with this new settings with updated repo, errors still happen.

Could you please provide some more details about what method are you using to connect to Influxdb? (port-forward IngressController, change the Service type...) 

I'd say the `Unauthorized issue` is surely caused by the connection bouncing from one pod to another, but with the influxdb service using ClientIP that shouldn't be happening anymore.

**Comment by wemod123** [comment]
Good clarification,

>Meanwhile, High-availability will require to continue using the Influx 1.8 images.

If this is the case, it's good to add this in README.md to let other's know, since the default image now is InfluxDB 2.0.

**Comment by migruiz4** [comment]
Totally agree, I will add a note in the README.md explaining the problem to avoid confusion.

Thank you for your comprehension.
