### ISSUE TITLE
[harbor helm chart] Error can not mount secret uuaSecretName

### ISSUE THREAD

**Issue by scila1996** [bitnami/charts#5894]
Hi bitnami helm team

i waste whole day for that error. I want to config authentication with LDAP, behind my LDAP server is LDAPS with require TLS and CA root. 

First. I created secretName with generic type from cert file

`kubectl create secret generic mcr-cer-mcredit-local --from-file=ca.crt --namespace harbor`

next I set value in helm values.yaml

`core.uaaSecretName: 'mcr-cer-mcredit-local'`

finish, i install helm chart but core-deployment show error

> Error: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/c817b754-862b-4316-a383-799ffef076d7/volume-subpaths/auth-ca-cert/core/4\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v1.linux/k8s.io/core/rootfs\\\" at \\\"/run/containerd/io.containerd.runtime.v1.linux/k8s.io/core/rootfs/etc/core/ca/auth-ca.crt\\\" caused \\\"not a directory\\\"\"": unknown

:(( please help me

**Comment by marcosbc** [comment]
Hi @scila1996, it looks like it is happening because the TLS certificates are mounting the entire `/etc/core/ca/` directory and `core.uaaSecretName` is causing another file to be mounted inside there.

It seems like this was fixed in upstream Harbor chart some time ago, so applying the same fix for the Bitnami helm chart should solve it: https://github.com/goharbor/harbor-helm/commit/685108220c8efab3f2748e16528480282f662e8f

Could you test if that change works beforehand? Feel free to send a PR, we'd be glad to help review it, and would allow to speed up the process.

**Comment by scila1996** [comment]
@marcosbc 

Thank for reply ! I was set `core.uaaSecretName` and helm install normaly, next I have manual edited ConfigMap and Deployment follow that commit and It was successfully

Running Pod success on Harbor Core Deployment !

Please fix helm chart and commit soon ! Thanks (y)

**Comment by marcosbc** [comment]
Thanks for letting us know @scila1996! I just created #5916. Once it is merged, this issue should close automatically.
