### ISSUE TITLE
Un-specified PVC requested in Mariadb-Galera Helm chart

### ISSUE THREAD

**Issue by Choogster1** [bitnami/charts#5913]
I've deployed a 3 node Galera instances to Kubernetes, using an existing PVC/PV which I created for it. After which I installed Moodle which all worked fine for a time.

The problem arises when Galera tries to request a new PVC which isn't specified in the Helm chart anywhere, which then crashes Moodle (unable to connect to database).

light-popcorn-mariadb-galera-0                     1/1     Running            0          18h
light-popcorn-mariadb-galera-1                     1/1     Running            0          18h
light-popcorn-mariadb-galera-2                     1/1     Running            0          18h
maddening-ink-moodle-57b4d8459f-6wbl6   0/1     CrashLoopBackOff   173        18h
maddening-ink-moodle-57b4d8459f-b8r5v    0/1     CrashLoopBackOff   173        18h
maddening-ink-moodle-57b4d8459f-vdws8   0/1     CrashLoopBackOff   172        18h

As you can see, MariaDB-Galera's instances are working fine and the logs don't show anything unusual until the following appears:

1902 [Warning] Aborted connection 1902 to db: 'moodle' user: 'moodle' host: 'moodle' (Got an error reading communication packets)

Does anybody know the issue and why galera is requesting a new PVC claim which isn't listed in the Helm chart anywhere?

data-solid-shop-mariadb-galera-0                              Pending

**Comment by marcosbc** [comment]
Hi @Choogster1, the error you mention may be related to some Galera reconfiguration, it should get stable afterwards though:

> 1902 [Warning] Aborted connection 1902 to db: 'moodle' user: 'moodle' host: 'moodle' (Got an error reading communication packets)

As for the `data-solid-shop-mariadb-galera-0` PVC getting created, I don't think it has any relation with the cluster since it has a different release name (`solid-shop` vs `light-popcorn`). Also I'm not sure as per your post how this even makes the Moodle deployment fine.

Could you verify that there isn't any statefulset/deployment in the same namespace?
