### ISSUE TITLE
[bitnami/wordpress] wordpressExtraConfigContent values are not all applied

### ISSUE THREAD

**Issue by corend** [bitnami/charts#5929]
**Which chart**:
wordpress

**Describe the bug**
wordpress Extra Config content values are not all taken into account.

**To Reproduce**

Apply values.yaml from bitnami wordpress with the following added values:
```YAML
wordpressExtraConfigContent: |
  @ini_set( 'post_max_size', '200M');
  @ini_set( 'upload_max_filesize', '200M');
  @ini_set( 'memory_limit', '640M' );
  @ini_set( 'max_execution_time', '360' );
  @ini_set( 'max_input_time', '360' );
  define( 'WP_MEMORY_LIMIT', '512M' );
```

- [ ] - **post_max_size and upload_max_filesize should be set to 200M but this is still set to the default value which is 40M.**
- [X] - memory_limit is correctly set to 640M in WP for admin screens.
- [X] - max_execution_time and max_input_time are correctly set to 360.
- [ ] - **WP_MEMORY_LIMIT is not applied and 256M is still the limit instead of 512M.**

**Expected behavior**
All the mentioned values in wordpressExtraConfigContent should be applied. Or we should be able to change those values, is there a doc somewhere about the accepted variables?
Including (summary of data not applied that should be applied as weel):
post_max_size and upload_max_filesize should be set to 200M but this is still set to the default value which is 40M.
WP_MEMORY_LIMIT is not applied and 256M is still the limit instead of 512M.

**Version of Helm and Kubernetes**: K8S 1.20.4, helm up-to-date

**Additional context**
Not any errors are returned when we execute the YAML, actually as the config WP php file is updated during or just after the deployment it is not a big issue.
If I do something wrong, please do not hesitate to give advices. ;-)

**Comment by migruiz4** [comment]
Hi @corend,

This is indeed caused by multiple issues.

Thie main one is that `WP_MEMORY_LIMIT`, `post_max_size` and `upload_max_filesize` can not exceed the values defined in `php.ini`.
To fix this, we could modify those values using this https://github.com/bitnami/bitnami-docker-php-fpm#add-additional-ini-files.

This comment has a detailed description of how to do it for Kubernetes: https://github.com/bitnami/bitnami-docker-wordpress/issues/241#issuecomment-624613418

I was able to configure the settings with some slight changes:

1- Create the configmap (configmap.yaml)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini
  namespace: default
  labels:
    app.kubernetes.io/name: wordpress
data:
  php-custom.ini: |
    upload_max_filesize = 256M
    post_max_size = 256M
    max_execution_time = 360
    max_input_time = 360
    memory_limit = 512M
```
2. Modify the values.yaml
```yaml
extraVolumeMounts:
  - name: php-ini
    mountPath: /opt/bitnami/php/etc/conf.d

extraVolumes:
  - name: php-ini
    configMap:
      name: php-ini
```
3. Install the Wordpress chart using the extraVolume
```bash
kubectl apply -f configmap.yaml
helm install wp-test bitnami/wordpress -f values.yaml
```

This should fix the issue except for `WP_MEMORY_LIMIT`, which, additionally, requires a workaround because of this known issue: https://github.com/bitnami/bitnami-docker-wordpress/issues/167 

`wordpressExtraConfigContent` appends the configuration at the end of the file, while `WP_MEMORY_LIMIT` needs to be set above this line: `require_once ABSPATH . 'wp-settings.php';` 

The workaround for that issue would be using a `post-init` script as it follows:

```yaml
customPostInitScripts:
  wp_memory_limit.sh: |
    sed -i "/.*That's all, stop editing! Happy publishing.*/i define('WP_MEMORY_LIMIT', '512M');" /opt/bitnami/wordpress/wp-config.php
```

If you have any further question please let me know.

**Comment by corend** [comment]
I will give it a try. Thank you

**Comment by corend** [comment]
@migruiz4 I confirm, your solution is correctly working, I did a deployment and this is the successful result:
![image](https://user-images.githubusercontent.com/34213983/112868786-bc293280-90bc-11eb-9551-543a5072803b.png)
Thank you

**Comment by fcoulloudon** [comment]
Following @migruiz4 comment, postInit script is good. However, if the pod restarts, you loose this value...

What I suggest doing is to use sed command from the pod shell to modify /bitnami/wordpress/wp-config.php once and keep this value persistently:

In pod shell:

```shell
sed -i "/.*That's all, stop editing! Happy publishing.*/i define( 'WP_MEMORY_LIMIT', '512M' );" /bitnami/wordpress/wp-config.php
```
