### ISSUE TITLE
[kube-prometheus] Queston about replicaCount for prometheus

### ISSUE THREAD

**Issue by pbrissaud** [bitnami/charts#5946]
Hi, 

I downloaded the bitnami/kube-prometheus chart months ago (november 2020). I successfully deployed the chart with `values-production.yaml` values file. 

Actually, I have 3 prometheus instances (because replicaCount = 3) with 3 pvc but I don't know the data is replicated. Is the data is replicated on all volumes ? And is it useful to have multiple Prometheus instance without Thanos ? 

Best regards

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I imagine you deployed three Prometheus objects, right? Then I guess these three instances are independent between them, so there's no replication between them. That's the reason why Thanos provides the replication layer between replicas in a same Prometheus instance. About having three independent Prometheus instance, I don't have much SRE experience but I don't see much value compared to having replication.

**Comment by pbrissaud** [comment]
Hi, 

Thanks for your answer. So, if I understand well having 3 Prometheus without Thanos is completely useless... I will try if only one instance can support the load.

**Comment by mboutet** [comment]
Well, I don't think it's completely useless. For instance, with two  prometheus replicas, if one replica is down (node failure, rolling upgrade, OOM killed, etc.), then the other can still scrape the targets and alertmanager continues to operate. This is especially useful when considering that restarting prometheus can take some time because it needs to reload and replay the current wal segment.

If you don't care about availability, then one replica is fine.

I'm no prometheus expert and that's just my opinion based on what I know.

**Comment by pbrissaud** [comment]
Hi,
Yeah it can be useful to have 2 instance in this case. However, Kubernetes should manage my pod if one node has a problem. And having 2 volumes with the same data is the big trade-off of this solution.

**Comment by mboutet** [comment]
Sure, k8s will eventually detect the node failure and reschedule the Prometheus pod on another node. I say "eventually" because it's not instantaneous. Once the pod is rescheduled and that the volume is re-attached on the Prometheus pod, it can take several minutes to reload the current segment. 

Additionally, if you are running a cluster in multiple availability zones and that the failure is instead affecting all the nodes in a specific AZ, then the Prometheus pod won't be re-scheduled in another AZ because persistent disks are often zonal, i.e. a disk created in one AZ can't be attached to a VM in another AZ. So, it is useful to have at least two replicas running in different availability zones.

In the end it's a trade-off between the additional cost of resources (cpu, ram, storage) for more replicas and the availability you need. You must also take into account the cost of losing all metrics during such an outage or during maintenance operations.
