### ISSUE TITLE
bitnami/influxdb: Influxdb questions

### ISSUE THREAD

**Issue by bhakta0007** [bitnami/charts#5965]
**Which chart**:
influxdb : in high-availability mode

**Describe the bug**
Not a bug but questions:

1. Does high-availability required enterprise license? As per influxdb's own documentation the clustering/HA is an enterprise feature and requires a license Key?
2. Why does the chart not spawn an additional Nginx based load-balancer (it can take bitnami nginx image and inject the necessary configuration (https://docs.openstack.org/developer/performance-docs/methodologies/monitoring/influxha.html#nginx-configuration)
3. How would influxDB relay work when I have collectd/UDP based writes coming in (collectd listener on influx side). The relay service seems to operate only on TCP. I am guessing there needs to be a change to relay service to activate UDP/collectd(25826) listener as well?

Note: I am considering influx 1.x based deployment.

**Comment by alvneiayu** [comment]
Hi @bhakta0007 

1. Influx Enterprise offers Influx Cluster. We use Influx Relay which replicates the `/write`. Our charts don't support Influx cluster and also, Influx HA is broken in 2.0 because Relay has not received yet the update. We need to use 1.8.
2. NGinx is not needed because the service already balances all the requests/petitions. If you want NGinx, it can be implemented as Ingress controller.
3. Relay UDP configuration is not included in our Charts, but this is a feature really easy to include and then you can configure the Relay with relay.configuration (https://github.com/influxdata/influxdb-relay#configuration).

I hope that I solved all you questions. Do not hesitate to contact us, if you have more questions.

Thanks

Álvaro

**Comment by bhakta0007** [comment]
@alvneiayu 

(1) & (2) - thanks - I get it now. makes sense
(3) It appears that relay only works for UDP line protocol (and not for collectd). I have raised an issue [https://github.com/influxdata/influxdb-relay/issues/83]

**Comment by alvneiayu** [comment]
Hi @bhakta0007 

Thanks to you. Let me know if you have more questions.

BR

Álvaro

**Comment by bhakta0007** [comment]
@alvneiayu 

how do we go about including the UDP configuration into the influxdb charts? Can you please assist / or point in the right direction?

**Comment by javsalgar** [comment]
Hi,

There is a value called `relay.configuration` where you can add the configuration settings you require. Find an example here https://github.com/influxdata/influxdb-relay#configuration

**Comment by bhakta0007** [comment]
@javsalgar 

I get that part. What I am not sure is how a real-life scenario will work. My use-case is that I want the UDP port to be exposed along with the HTTP relay port AND assign a load balancer IP to this configuration. This way I can ingest data from outside.

I believe you cannot expose two services (HTTP (aka TCP) and UDP) from the same LB IP. How do we overcome this?

**Comment by javsalgar** [comment]
Hi,

It seems this is an issue that has been brought up in Kubernetes itself. 

https://github.com/kubernetes/kubernetes/issues/2995

It seems that it is not fully working for LoadBalancer services. They mention this tutorial, which seems to require manual actions https://medium.com/asl19-developers/build-your-own-cloud-agnostic-tcp-udp-loadbalancer-for-your-kubernetes-apps-3959335f4ec3

Could you take a look, and let us know what elements you had to add and modify in order to get both TCP and UDP traffic working?

**Comment by bhakta0007** [comment]
@javsalgar that option to create an independent service that would load balance to influx will work. I haven't tried it but I am sure that would work.

**Comment by alvneiayu** [comment]
hi @bhakta0007

Thanks to report the issue. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks

Álvaro

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
