### ISSUE TITLE
[bitnami/rabbitmq] metrics port does not work when TLS enabled

### ISSUE THREAD

**Issue by ReshetS** [bitnami/charts#6004]
**Which chart**:
bitnami/rabbitmq (8.11.4)

**Describe the bug**
Google Cloud Platform has [limit of LoadBalancer ports](https://cloud.google.com/load-balancing/docs/quotas) - 5 and it cannot be changed. When I enable TLS, additional tls-port is added and metrics port does not work.
As a workaround, additional service can be used for metrics and/or `service.extraPorts`

**To Reproduce**

1. Deploy chart to Google Kubernetes Engine with `set auth.tls.enabled=true --set metrics.enabled=true`
2. Try to get metrics from port 9419
3. Get `wget: can't connect to remote host (10.1.7.48): Connection timed out`
4. Check service events to see Error 400 from Google API

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.12-gke.1210", GitCommit:"199a41188dc0ca5d6d95b1cc7e8ba96e05f9dd0a", GitTreeState:"clean", BuildDate:"2021-02-05T18:03:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

`kubectl describe svc rabbitmq`
```
  Warning  SyncLoadBalancerFailed  53m (x489 over 42h)    service-controller  Error syncing load balancer: failed to ensure load balancer: googleapi: Error 400: Invalid value for field 'resource.ports[5]': '9419'. Too many ports specified. Maximum is 5., invalid
```

**Comment by javsalgar** [comment]
Hi,

I see that this is a limitation of GKE LoadBalancer IPs. Just for a small test, could you try deploying it with service.type=ClusterIP ?

**Comment by ReshetS** [comment]
Hi!
We need metrics to be exposed via Internal LoadBalancer.
Currently, as a workaround, we set up with ClusterIP and created separated service for metrics manually.

**Comment by javsalgar** [comment]
I see, I think we should review the amount of services we are creating inside a Service object to ensure that they are compatible with GKE. I will create a task for that. Thanks for reporting!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
