### ISSUE TITLE
grafana  cephfs

### ISSUE THREAD

**Issue by zhaowangda** [bitnami/charts#6059]
**Which chart**:
grafana latest

**Describe the bug**
use cephfs as provisioner, logs as below: 
mkdir: cannot create directory '/opt/bitnami/grafana/data/plugins': Permission denied
mkdir: cannot create directory '/opt/bitnami/grafana/data/plugins': Permission denied

#-----------------------------------------
the pods status is CrashLoopBackOff. I saw readonly in pods config,but i can not change: 
volumeMounts:
        - name: data
          mountPath: /opt/bitnami/grafana/data
        - name: grafana-token-tgm8d
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount

**Comment by carrodher** [comment]
Probably the issue is produced because the container is non-root so the local directories mounted in the container should have the proper permission, can you take a look at the following [troubleshooting guide](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#permission-errors-when-enabling-persistence)?

**Comment by zhaowangda** [comment]
No "--set volumePermissions.enabled=true" does not work。

**Comment by zhaowangda** [comment]
securityContext:
  enabled: true
  #runAsUser: 1001
  #fsGroup: 1001
  runAsUser: 0
  fsGroup: 0
  runAsNonRoot: false

**Comment by carrodher** [comment]
I'm glad you were able to solve the issue by using this approach
