### ISSUE TITLE
Use sh instead of bash for git-clone-repository and git-repo-syncer

### ISSUE THREAD

**Issue by Skallwar** [bitnami/charts#6066]
**Which chart**:
nginx

**Is your feature request related to a problem? Please describe.**
I'm using an arm64 machine so I can't use bitnami/git image and I'm instead using an alpine image which does not have bash.

**Describe the solution you'd like**
The 2 scripts are fairly simple and could be made non bash specific so sh could be used instead

**Describe alternatives you've considered**
Maintaining myself an image just for this. The simplicity of the change makes me thinks it is not the best solution

**Comment by migruiz4** [comment]
Hi @Skallwar,

 I'm sorry but it wouldn't be possible to replace `bash` with `sh` for git-clone-repository and git-repo-syncer containers, as it would have issues with the bitnami/git entrypoint script:

```sh
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-git/master/2/debian-10/rootfs/opt/bitnami/scripts/git/entrypoint.sh
$ [ -f ./entrypoint.sh ] && . ./entrypoint.sh
sh: 6: set: Illegal option -o pipefail
```

As an alternative, I think we could add a value to override the default command, for example: `.Values.cloneStaticSiteFromGit.gitRepoSync.command` and `Values.cloneStaticSiteFromGit.gitClone.command`.
Would that work for you?

Additionally, I'd like to let you know that we are working to release the Bitnami docker images for ARM64, but we don't have yet an ETA for it.

**Comment by Skallwar** [comment]
> As an alternative, I think we could add a value to override the default command, for example: .Values.cloneStaticSiteFromGit.gitRepoSync.command and Values.cloneStaticSiteFromGit.gitClone.command.
Would that work for you?

I'm not sure. I could rewrite ``entrypoint.sh`` by myself and set ``.Values.cloneStaticSiteFromGit.gitRepoSync.command``, but it don't feel like it is a very maintainable solution. As I don't see any pipe at all in ``entrypoint.sh`` why could we not just remove ``set -o pipefail`` ?

> we are working to release the Bitnami docker images for ARM64

That's awesome !

**Comment by migruiz4** [comment]
I think of it the opposite way, adding an extra option so you can overwrite the `command` would be a maintainable solution, as it would allow users who need custom settings, such as your use case, without potentially causing issues to users using the default image.

If we modified the command to use `sh`, then we would have to modify `bitnami/git` entrypoint to use POSIX shell, and because our images don't generally use POSIX shell, it is likely that git-clone-repository and git-repo-syncer could be affected by changes in the image and stop working because of that.

>  I could rewrite entrypoint.sh by myself and set .Values.cloneStaticSiteFromGit.gitRepoSync.command

You wouldn't have to rewrite the entrypoint.sh, because you are using a different image that doesn't include `/opt/bitnami/scripts/git/entrypoint.sh`, you simply would have to overwrite the below command:

https://github.com/bitnami/charts/blob/3ac71514e2ac53eb5b19f6c747595b4716768638/bitnami/nginx/templates/deployment.yaml#L62-L67

With something like:
```sh
             - /bin/sh 
             - -c 
             - | 
               git clone {{ .Values.cloneStaticSiteFromGit.repository }} --branch {{ .Values.cloneStaticSiteFromGit.branch }} /app 
```

**Comment by Skallwar** [comment]
Ok. I understand your point and I agree that your solution is the best. Overriding the command is the solution

**Comment by migruiz4** [comment]
Hi @Skallwar,

I have created this PR (https://github.com/bitnami/charts/pull/6104) that adds the feature we discuss).

That should fix your issue until the image `bitnami/git` supports arm64.
