### ISSUE TITLE
Support subPath for data volume for MySQL

### ISSUE THREAD

**Issue by alex-lx** [bitnami/charts#6196]
**Which chart**:
mysql-8.5.4
**Is your feature request related to a problem? Please describe.**
We've a local pv for both postgresql and mysql, each of them use a subPath to store data.
**Describe the solution you'd like**
Using persistence.subPath to specify the subPath of the mount volumes, 
**Describe alternatives you've considered**
Create two local pv as a workaround
**Additional context**
This feature  is already supported by postgresql's chart.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for suggesting this feature.
  I am creating an internal task in order to add it.
  However, I can not provide an ETA.
  I the meantime, would you like to send a PR? We will be glad to review and merge it.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
