### ISSUE TITLE
[kafka] Exporter missing SASL mechanism

### ISSUE THREAD

**Issue by electrical** [bitnami/charts#6253]
**Which chart**:
kafa chart 12.17.5
Upgraded from 12.7.6

**Describe the bug**
When enabling sasl authentication the exporter needs to know the mechanism.
Currently this is not provided from the chart to the deployment.
It's missing the `sasl.mechanism` option.
This seems to be a new addition in version 1.3.0 of the kafka exporter it self.

**To Reproduce**

sasl enabled cluster.

** Relevant links**

PR adding the mechanism option at the exporter: https://github.com/danielqsj/kafka_exporter/pull/101

**Comment by alvneiayu** [comment]
hi @electrical 

Thanks to report the issue. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news. However, if you want to send us a PR to support this we will be happy to review it.

Thanks a lot

Álvaro

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
