### ISSUE TITLE
[bitnami/mongodb] Require commonAnnotations in values.yaml

### ISSUE THREAD

**Issue by s-sinha9** [bitnami/charts#6264]
**Which chart**: bitnami/mongodb

**Is your feature request related to a problem? Please describe.**
I want to deploy the bitnami/mongodb chart with helm pre-install hook. For this I need to specify the metadata.annotations for each of the resources. In values.yaml there is an option to provide these annotation separately. However there is no option to add annotations for service, secret, pvc, etc from values.yaml directly.

**Describe the solution you'd like**
A commonAnnotations tag in values.yaml which will add required annotations to all the resources required for deployment.

This can be added to values.yaml like

 `commonAnnotations: {}`

and used in the templates files like 
```
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

```
**Describe alternatives you've considered**

I have tried adding these annotations manually to each of the resources but this is not possible when mongodb is a dependency chart for another helm chart.

**Additional context**

This feature is available in bitnami/cassandra chart , bitnami/kakfa chart already.

**Comment by alvneiayu** [comment]
hi @s-sinha9 

I checked the code and it is true that we don't have the "commonAnnotation" key in mongoDB. Instead of "commonAnnotation" key, the mongodb chart has the "annotations" key that is doing the same behavior inside the Replica/Standalone.

```
{{- if .Values.annotations }}                                                                                         
 annotations: {{- include "common.tplvalues.render" (dict "value" .Values.annotations "context" $) | nindent 4 }}      
{{- end }}
```
We don't have this support inside the services, pvcs, secrets, etc. Thanks to report the issue. I created an internal task and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news. However, if you want to send us a PR to support this we will be happy to review it.

Thanks a lot for your time

Álvaro
