### ISSUE TITLE
[bitnami/external-dns] Add support for new BlueCat provider

### ISSUE THREAD

**Issue by ajchiarello** [bitnami/charts#6317]
**Which chart**:
external-dns

A Bluecat provider has recently been added to the external-dns project; it would be great to have the ability to configure this provider added to the chart. They describe how to configure it here: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/bluecat.md.

**Comment by javsalgar** [comment]
not stale

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
