### ISSUE TITLE
[FEATURE] Ability to pass config.php as either a Secret or ConfigMap in Moodle bitnami chart

### ISSUE THREAD

**Issue by ernani** [bitnami/charts#6374]
**Which chart**:
bitnami - onwards

**Is your feature request related to a problem? Please describe.**
Having the ability to pass the config.php as a Secret or ConfigMap can help accommodate the usage of redis/memcached module for Moodle, avoiding sessions to be stored in moodle data. Also it can serve as content caching which can be set as a different running Deployment/Pod in Kubernetes or using a managed service.

**Describe the solution you'd like**
It would require to add php-redis/php-memcached modules in current moodle docker image in bitnami, but after that's done, mounting the config.php as a kubernetes Secret/ConfigMap as a file in the bitnami filesystem inside the image will make it easy to config moodle in a more robust way.

**Describe alternatives you've considered**
I couldn't think of any other ways unless using external storage and modify them by hand.

**Additional context**
There is this issue in bitnami docker team to track on this companion work:
https://github.com/bitnami/bitnami-docker-moodle/issues/178

**Comment by carrodher** [comment]
Thanks, I just added this issue to the internal task we have for this topic. In the same way, I am adding the `on-hold` label to prevent the bot from closing this issue.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/moodle#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
