### ISSUE TITLE
mongodb/templates/replicaset/scripts-configmap.yaml setup.sh primary condition

### ISSUE THREAD

**Issue by asanderson** [bitnami/charts#6378]
**Which chart**:
mongodb 10.15.3

**Describe the bug**
Line 81 of bitnami/mongodb/templates/replicaset/scripts-configmap.yaml has the conditional `if [[ "$MY_POD_NAME" = "{{ $fullname }}-0" ]]; then` that determines the primary vs secondary replica based upon "-0" name suffix which works fine for replica sets created in the same cluster if set up simultaneously, but does not work for adding secondary replicas from other clusters after initial setup, when it's node ends in `-0` as well. 
Instead there should be a way to specify which the primary pod via name prefix or pattern (e.g. `*-primary-*`)

**To Reproduce**

1. `helm install my-mongo bitnami/mongodb --set architecture=replicaset` in 2 separate clusters.
2. Do a `kubectl get pods` in each cluster to confirm pod names end in `'0'.
3. Export each service via Submariner (see submariner.io for details).
4. `kubectl exec -- mongo` into the first cluster and try to `rs.add()` the node from the second cluster but it fails since both pods have the same name.

**Expected behavior**
Should be a way to add secondary replicas from other clusters which have the same pod names.

**Version of Helm and Kubernetes**:

- Output of `helm version`:
All versions

- Output of `kubectl version`:

All versions

**Additional context**
See the following for setting up multicluster services via Submariner:  https://submariner.io/operations/deployment/

**Comment by migruiz4** [comment]
Hi @asanderson ,

The MongoDB chart is designed to deploy a Replicaset where the node `-0` takes the primary role and initializes the cluster and the rest of the nodes are added as secondary replicas.

That is what this section of the `setup.sh` is intended for:
https://github.com/bitnami/charts/blob/2a547f9bdfe9319ea95dcbe553f1b20ebf202605/bitnami/mongodb/templates/replicaset/scripts-configmap.yaml#L81-L91

Although that could cause some issues for your setup, you could replace that logic by mounting a custom script and executing it instead of the `setup.sh` using the `command` value:

https://github.com/bitnami/charts/blob/2a547f9bdfe9319ea95dcbe553f1b20ebf202605/bitnami/mongodb/templates/replicaset/statefulset.yaml#L200-L205


I think the main issue preventing your setup is that MongoDB nodes from both clusters are configured using the same node hostname. MongoDB nodes are configured using:

```
MONGODB_ADVERTISED_HOSTNAME="$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.{{ .Values.clusterDomain }}"
```

If both of your Kubernetes clusters have the same ClusterDomain, namespace, and service name you won't have a unique identifier for each MongoDB pod, which is mandatory to configure MongoDB.

**Comment by asanderson** [comment]
So, the way Submariner **_globally_** resolves services is via `<cluster id>.<service name>.<namespace>.svc.clusterset.local` DNS resolution so that each cluster can contain the same <service name>.<namespace>.svc.clusterset.local` services which the bitnami/mongodb chart does NOT support even with the `MONGO_ADVERSTISED_HOSTNAME` scheme which also needs to be overwritten.  Yes, I guess a custom setup.sh script *could be* used but all we need is really to change that condition in the current bitnami setup.sh.

**Comment by migruiz4** [comment]
I'm sorry but I think your use case is very specific and it would be hard to cover this case without affecting the default deployment in a single Kubernetes cluster.

If you know exactly what would need to be changed in the chart, feel free to send a PR and we will be happy to review your contributions.

Otherwise, I would recommend using a custom `values.yaml` that added a `custom-setup.sh` as I previously mentioned.

For example:
>values.yaml
```yaml
command:
  - /scripts/custom-setup.sh
extraVolumeMounts:
  - name: custom-scripts
    mountPath: /scripts/custom-setup.sh
    subPath: custom-setup.sh
extraVolumes:
  - name: custom-scripts
    configMap:
      name: custom-mongodb-scripts
      defaultMode: 0755
replicaSetHostnames: false
```
> custom-mongodb-scripts.yaml
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mongodb-scripts
  namespace: <<your_namespace>>
  labels:
    app.kubernetes.io/component: mongodb
data:
  custom-setup.sh: |-
    #!/bin/bash

    . /opt/bitnami/scripts/mongodb-env.sh

    export MONGODB_ADVERTISED_HOSTNAME="$(MY_POD_NAME).<<your_cluster_id>>.$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.clusterset.local"

    echo "Advertised Hostname: $MONGODB_ADVERTISED_HOSTNAME"

    # Modify this section at your will
    if [[ "$MY_POD_NAME" = "{{ $fullname }}-0" ]]; then
        echo "Pod name matches initial primary pod name, configuring node as a primary"
        export MONGODB_REPLICA_SET_MODE="primary"
    else
        echo "Pod name doesn't match initial primary pod name, configuring node as a secondary"
        export MONGODB_REPLICA_SET_MODE="secondary"
        export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD="$MONGODB_ROOT_PASSWORD"
        export MONGODB_INITIAL_PRIMARY_PORT_NUMBER="$MONGODB_PORT_NUMBER"
        export MONGODB_ROOT_PASSWORD="" MONGODB_USERNAME="" MONGODB_DATABASE="" MONGODB_PASSWORD=""
        export MONGODB_ROOT_PASSWORD_FILE="" MONGODB_USERNAME_FILE="" MONGODB_DATABASE_FILE="" MONGODB_PASSWORD_FILE=""
    fi

    exec /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh
```

**Comment by biagioT** [comment]
@asanderson did you find a good solution?

**Comment by asanderson** [comment]
@biagioT The only solution is to generate the configmap and then manually modify it, if they won't change the code.
