### ISSUE TITLE
[bitnami/mongodb] No support for external access for standalone deployment

### ISSUE THREAD

**Issue by mix4242** [bitnami/charts#6385]
**Which chart**:
bitnami/mongodb

**Describe the bug**
I'm new to both helm and k8s so please excuse if this is a stupid question or I'm missing something. I am wondering why there appears to be no support for the `externalAccess` option for the `standalone` architecture like there is for the `replicaset`. Setting up a simple PoC deployment I would benefit from as simple a customisation as possible. I have managed to get it working with replicaset and i can access the db externally which is great, but an explanation why this isn't available for standalone would be much appreciated :)

**Comment by miguelaeh** [comment]
Hi @mix4242 ,
For the standalone MongoDB you can access it externally just using a LoadBalancer service. In the case of replica set it is different since to access the nodes externally all of them need to have configured a LoadBalancer IP in order to reach each other to create the cluster.
They are two different topologies, the standalone can be accessed externally by default, while the replicaset needs more configuration to access it externally, and by default, it is only accessible from inside your K8s cluster until all the nodes are configured with an external IP.

**Comment by mix4242** [comment]
Ahh I get it. I managed to create my own LoadBalancer for standalone and all works well. Thanks
