### ISSUE TITLE
[bitnami/wordpress] Health check fails on other languages

### ISSUE THREAD

**Issue by FJEANNOT** [bitnami/charts#6433]
Similar to #6337 but for Wordpress

**Which chart**:
bitnami/wordpress version 11.0.7

**Describe the bug**
When changing to another language, the pods begin to crash because the path /wp-login.php used for the healthcheck is replaced

**To Reproduce**
Change wordpress language after the deployment

**Expected behavior**
 Health check success and pod get to a healthy state

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

- Output of `kubectl version`:

```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
A quickfix is to edit the chart probes in the values file to change the path from /login to /

I can submit a merge request with the changes

**Comment by rafariossaa** [comment]
Hi,
  I think that for this kind of configuration you can use the parameters `customReadinessProbe` and `customLivenessProbe`, so it is not needed to change the chart.
  Also, in general, I think that it is better to test a URL where  the application already does something, like a php script or such. This way you are testing that web server + php + app scripts are working. Well, you can not be 100% sure of the last item, because you usually choose an URL that does not produce to much load on the app, but at least you know that is minimally working. 
  Would those parameters would work for you ?.
