### ISSUE TITLE
Hope bitnami/charts join Nacos and RocketMQ.

### ISSUE THREAD

**Issue by Qoooooooooooo** [bitnami/charts#6441]
Hope bitnami/charts join Nacos and RocketMQ.
:)

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some example, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.
