### ISSUE TITLE
wordpress helm chart pdb in beta

### ISSUE THREAD

**Issue by matti** [bitnami/charts#6459]
https://github.com/bitnami/charts/blob/master/bitnami/wordpress/templates/pdb.yaml#L2

```
W0525 13:19:57.019246   70568 warnings.go:67] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.

**Comment by matti** [comment]
wtf :D
