### ISSUE TITLE
[bitnami/spring-cloud-dataflow] - Add ojdbc driver for external OracleDB

### ISSUE THREAD

**Issue by erlisb** [bitnami/charts#6470]
Motivation: 
Current Helm chart release doesn't provide a clear way how to add an ojdbc driver if you would like to use an external DB i.e Oracle.

From the search that I have done, it is suggested that it is better that you build the Spring Cloud Data Flow (SCDF) image from scratch where you would add the ojdbc driver as a dependency in pom.xml file but in my opinion to implement an image extension is better than to change the project's dependencies. 

What I have tried : 
I thought this could be achieved by using the _initContainers_ field in values.yaml file, which uses an additional container to copy the requested driver inside the main SCDF container, but currently, is not quite clear on which path the driver should be provided.

Please, provide some support, which is the correct path to follow : 
- Build your own image with project dependecies
- Use provided bitnami helm chart attributes _initContainers_

Thank you,
Erlis

**Comment by migruiz4** [comment]
Hi @erlisb,

According to Spring Cloud Data Flow documentation, adding a custom JDBC such as OJDBC would require you to build the JAR file including your dependency: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_adding_a_custom_jdbc_driver

When completed the steps to build your JAR with OJDBC dependency, you would have to replace the container JAR located at `/opt/bitnami/spring-cloud-dataflow/spring-cloud-dataflow-server-{version}.jar` with your custom JAR.

To do so, you could either build a custom image based on `bitnami/spring-cloud-dataflow` or use the values `server.extraVolumeMounts` and `server.extraVolumes` to overwrite the original JAR file.

I'm not sure the `initContainer` would work because the JAR file is not located in a volume, and attempting to replace the file during runtime will fail because of permission issues as the container runs as non-root user but the jar file is owned by the root user.

**Comment by erlisb** [comment]
We agreed to proceed as suggested by Bitnami.
