### ISSUE TITLE
Multi Region Redis Cluster

### ISSUE THREAD

**Issue by sabareeshkkanan** [bitnami/charts#6476]
**Which chart**:
Redis Cluster

**Is your feature request related to a problem? Please describe.**
Resilient cluster that is available across a region . Basically high availability across region

**Describe the solution you'd like**
A cluster that can support disaster recovery and failover across regions. Essentially each cluster will be deployed on its own kube cluster

**Comment by carrodher** [comment]
Hi, thanks for your suggestion.
Are you trying to use the current solution for the described use case? What errors/issues are you facing?
Do you have any idea about how this feature can be implemented in the chart? ([PRs are welcome](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md))

**Comment by sabareeshkkanan** [comment]
Current solution works only within same kubernetes cluster and mostly this cluster sits only on one region. In order for it to work we should be able to deploy across multiple kube cluster. We might also need to use something like external dns to achieve this .

**Comment by carrodher** [comment]
Adding this feature in an automated way it is not something trivial for a Helm Chart, probably this kind of task can fit better in an operator, I'm not sure how this can be done automatically in the Helm Chart, since the chart is installed in a specific cluster.

On the other hand, maybe you can try to do it by yourself with some human intervention. You can deploy the Helm Chart in the "cluster A" with external access, in that case, each node will have its own IP address. Then you can deploy the chart in a "cluster B" setting the `cluster.init` parameter to _false_ (see [1](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-management-parameters), [2](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#external-access), and [3](https://github.com/bitnami/charts/blob/5e89d342534fbf7c5e790fb9da6e1ec1f856902a/bitnami/redis-cluster/values.yaml#L47)). Then, you can execute in "cluster B" the update job using the external IPs from "cluster A" (see [1](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#cluster-update-job-parameters), [2](https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#adding-a-new-node-to-the-cluster), and [3](https://github.com/bitnami/charts/blob/5e89d342534fbf7c5e790fb9da6e1ec1f856902a/bitnami/redis-cluster/values.yaml#L281))

**Comment by busyboy77** [comment]
@carrodher -- Extremely eager to see that in action. We have multiple requirements where we need to have multi-cluster replication between site-a and site-b only for DR+HA.

Can you please consider sparing sometime and share any further guidelines to achieve this cluster-wide sync and fail-over. Any reference or guide or anything that might consider valuable will be much appreciated.

We can also pay for this, if someone wants to help us with a multi-cluster replication of Bitnami/Redis Helm charts with automatic or semi-automatic DR.
