### ISSUE TITLE
[bitnami/mysql] init script is not working

### ISSUE THREAD

**Issue by BedivereZero** [bitnami/charts#6485]
**Which chart**:
bitnami/mysql

**Describe the bug**
Custom init script under files/docker-entrypoint-initdb.d is not working.

**To Reproduce**

init script:

```sql
CREATE TABLE test (id INT);
```

1. Get and extract mysql-8.5.9.tgz
2. Put init script under mysql/files/docker-entrypoint-initdb.d
3. run command `helm install mysql -g`
4. the table `test` does not exist

**Expected behavior**
Init script is working.

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

**Additional context**

I found `bitnami/mysql/templates/primary/initialization-configmap.yaml` was add at  36c62d976c648ce61c280d266f8b5221d23d5007 and no longer use `.Files.Glob`.

**Comment by BedivereZero** [comment]
I just put the scripts under the directory `files/docker-entrypoint-initdb.d`, without configuring `initdbScriptsConfigMap` or `initdbScripts`, as described in the documentation [Customize a new MySQL instance](https://artifacthub.io/packages/helm/bitnami/mysql#customize-a-new-mysql-instance).

**Comment by juan131** [comment]
Hi @BedivereZero 

We deprecated the possibility of adding custom init scripts by placing them in the `files/docker-entrypoint-initdb.d` directory. This possibility was very error-prone since users didn't realize that they need to previously fetch the chart or clone the charts repository.

That said, you can still add your custom scripts using the `initdbScriptsConfigMap` or `initdbScripts` as @Mauraza said. 

For instance:

- Create a **custom-values.yaml** like the one below:

```yaml
initdbScripts:
  01-create-table.sql: |
    CREATE TABLE test (id INT);
```

- Install the chart using: `helm install mariadb bitnami/mariadb -f custom-values.yaml`

As an alternative:

- Create a ConfigMap based on your SQL script:

```console
$ kubectl create configmap mariadb-initialization --from-file=01-create-table.sql
```

- Install the chart using: `helm install mariadb bitnami/mariadb --set initdbScriptsConfigMap=mariadb-initialization`

**Comment by BedivereZero** [comment]
Thank you very much for your clarification, I understand the current measures that should be taken, so does the support documentation need to be updated.

**Comment by juan131** [comment]
You're right! Sending a PR to fix it
