### ISSUE TITLE
Charts can not be statically imported in Go using `go:embed`

### ISSUE THREAD

**Issue by adamantal** [bitnami/charts#6515]
**Which chart**:
Common chart 1.5.2

**Describe the bug**
The common chart can be not imported in Go using the `go:embed` directive.

**To Reproduce**
Steps to reproduce the behaviour:

1. Have the following Go file.
```go
import "embed"

// ...
//go:embed charts/redis/charts/common/*
chartFs embed.FS
```
2. `go build -v` fails with the following error:
```
assets/assets.go:6:13: pattern charts/redis/charts/common/*: cannot embed directory charts/redis/charts/common/templates/validations: contains no embeddable files
```

**Expected behavior**
Go compiles succeeds.

**Version of Helm and Kubernetes**:
The issues is not related to any Helm or Kubernetes version.

**Additional context**
There is two types of syntax for embedding directories using [`go:embed`](https://golang.org/pkg/embed/): `//go:embed directory` and `//go:embed directory/*`. The first one ignores the files that has the `.` or `_` suffix while the latter does not.
Using the latter syntax also imports the subdirectories, but the behaviour for the child folders is the first one (ignoring the prefixed files). Since bitnami/common chart's `template/` directory contains only ignored files, the embedding fails.

A workaround is to enumerate every template file from the common chart which is tedious and error prone (in case, let's say a new template is introduced in a newer common chart version - that will be excluded), and this can be more easily fixed on the chart's side.

Programmatic reconciliation of helm charts are quite common, and are almost exclusively written in Go. `go:embed` is a relatively new feature from Go 1.16, but it is expected to gain popularity due to its advantages compared to other solutions. It would be nice to resolve this problem.

**Comment by Mauraza** [comment]
Hi @adamantal,

I'm going to create an internal task to investigate this, we will update the thread when we have more information.
Thanks for reporting!!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
