### ISSUE TITLE
[bitnami/jasperreports] Prometheus monitoring with metrics endpoint annotations

### ISSUE THREAD

**Issue by dlakatos847** [bitnami/charts#6522]
**Which chart**:
Jasperreports 10.2.7

**Is your feature request related to a problem? Please describe.**
Our org would like to use Prometheus monitoring for JasperReports. Prometheus is mentioned in the chart's readme, but found no implementation or documentation how Prometheus monitoring can be used for JasperReports installed by the chart.

**Describe the solution you'd like**
Prometheus JMX exporter sidecar container with proper pod metadata annotations pointing to the metrics endpoint.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by marcosbc** [comment]
Hi, it seems like it is indeed missing. I'm creating an internal task for investigating this. Unfortunately I cannot give an ETA for when we will start working on this.

If you are able to get it working on your side with some modifications to the chart or [container image](https://github.com/bitnami/bitnami-docker-jasperreports/), feel free to send a PR, we'd be glad to help with the release of those changes.

**Comment by dlakatos847** [comment]
@marcosbc Thanks. My intent with this issue was to probe how Bitnami likes the thought of JasperReports+Prometheus monitoring. We already have a working solution via forking your chart and implementing sidecar+JMX exporter based monitoring. It's going to take us a few days to create the PR.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/jasperreports#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
