### ISSUE TITLE
[bitnami/mongodb] Add support for topology spread constraints

### ISSUE THREAD

**Issue by krtk6160** [bitnami/charts#6668]
**Which chart**:
Mongodb chart (all versions)

**Describe the solution you'd like**
Add support for topology spread constraints so that replicas are able to be spread across nodes to ensure higher availability in case of node upgrade/failure

**Additional context**
Topology spread constraints is a beta feature in k8s 1.18

**Comment by alvneiayu** [comment]
hi @krtk6160 

I opened an internal task to decide internally with the team and to investigate about this feature and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot

Álvaro

**Comment by krtk6160** [comment]
> hi @krtk6160 
> 
> I opened an internal task to decide internally with the team and to investigate about this feature and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.
> 
> Thanks a lot
> 
> Álvaro

Could you also consider adding this feature to the redis chart?

Thanks

**Comment by alvneiayu** [comment]
hi @krtk6160 

We are going to evaluate the feature and also in which charts we can include it. So, we will have in mind also Redis.

Thanks a lot for your time

Álvaro

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
