### ISSUE TITLE
image bitnami/node:7.5.0 not found

### ISSUE THREAD

**Issue by zhanghaichang** [bitnami/charts#670]
image bitnami/node:7.5.0 not found

**Comment by carrodher** [comment]
What command are you running to obtain this error?

**Comment by gaffneyc** [comment]
Running into the same issue trying to work through [the documentation](https://docs.bitnami.com/kubernetes/how-to/deploy-application-kubernetes-helm) for deploying an app with Helm. It looks like the [7.5.0 tag](https://hub.docker.com/r/bitnami/node/tags/) doesn't exist for `bitnami/node`.

**Comment by carrodher** [comment]
Hi, thanks for reporting it. Currently, we are working on improving this chart, here (https://github.com/bitnami/charts/pull/668) you can see the PR. With these changes, we want to update and fix different stuff in the MEAN chart. We will take into account this issue in order to ensure that the example of documentation works
