### ISSUE TITLE
[bitnami/kafka] Is it possible to release a new version of the kafka chart using the latest zookeeper chart ?

### ISSUE THREAD

**Issue by hmerat** [bitnami/charts#6727]
**Which chart**:
kafka chart

**Is your feature request related to a problem? Please describe.**
I'd like to have the latest zookeeper chart deployed when deploying the kafka chart

**Describe the solution you'd like**
A new version of the kafka chart containing the last version of the zookeeper chart

**Comment by carrodher** [comment]
A new Kafka major version is being released because the bundled ZooKeeper subchart was updated in a major version as well, you can take a look at the PR bumping the versions (https://github.com/bitnami/charts/pull/6730) and also the [upgrade notes in the Kafka README](https://github.com/bitnami/charts/tree/master/bitnami/kafka#to-1300)

**Comment by hmerat** [comment]
Thank you
