### ISSUE TITLE
Enable X-Pack setup config to para Elasticsearch 7.13.0 

### ISSUE THREAD

**Issue by lpmatos** [bitnami/charts#6753]
**Which chart**:
Bitnami Elasticsearch - Chart Version 15.6.0

**Is your feature request related to a problem? Please describe.**
I'm currently using this elasticsearch helm chart in my graylog setup in Kubernetes. I would like to enable basic authentication on my elasticsearch, but in the current process this is not explicit how to do it. 

**Describe the solution you'd like**
Enable elasticsearch x-pack security feature and show how this is done in the catalog.

**Comment by alvneiayu** [comment]
hi @lpmatos

My colleague @migruiz4 is working in this feature.  I am not able to give you an ETA but we expect to release a new version of the Elasticsearch chart and Docker image during the next week.

I will update this issue once the new feature is released.

Thanks a lot

Álvaro

**Comment by lpmatos** [comment]
Any updates?

**Comment by migruiz4** [comment]
Hi @lpmatos,

Sorry for the late response.

The bitnami/elasticsearch Helm chart now has support for X-Pack security features. 

To configure basic authentication, set the value `security.enabled=true` and configure your TLS certificates with the values `security.tls` (TLS encryption is required to enable X-Pack Security). 
Additionally, you can configure the password for the `elastic` user with the value `security.elasticPassword`, otherwise a random password will be generated.

TLS certificates can be autogenerated by Helm using `security.tls.autogenerated`, but we recommend to use this feature for dev environments and generate your own certificates for production environments.

**Comment by lpmatos** [comment]
Thanks! Closing this issue.
