### ISSUE TITLE
Configure Thanos Rule GRPC TLS with `grpcTLS` the same as Thanos Query

### ISSUE THREAD

**Issue by jppitout** [bitnami/charts#6797]
**Which chart**:
bitnami/thanos version 3.18.2

**Is your feature request related to a problem? Please describe.**
We are using Thanos in a multi-cluster setup. The central-thanos-query (observer) and federated-thanos-query (observee) have MTLS enabled for secure GRPC comms between clusters. 

Unfortunately Thanos query does not allow for separate MTLS config per store (https://github.com/thanos-io/thanos/issues/977) this means that any store central-thanos-query needs to access must have MTLS configured as well even if in the same cluster. Central-thanos-query needs to be able to query Thanos Rule for recording rule outputs using MTLS.

Although we can configure this using ` extraFlags:` in the values file it would be nice if the same implementation used for Thanos Query could be used for Ruler as well.

**Describe the solution you'd like**
Ability to configure Thanos Rule TLS with the same/similar values as Thanos Query i.e.:
```
  grpcTLS:
    server:
      secure: true
      autoGenerated: false
      existingSecret:
        name: thanos-tls
```

**Describe alternatives you've considered**
Using ` extraFlags` with `extraVolumes` and `extraVolumeMounts`

**Comment by alemorcuq** [comment]
Thanks for the suggestion, @jppitout! Are you interested in contributing with a PR?

**Comment by jppitout** [comment]
@alemorcuq Unfortunately I don't have capacity at this time :(

**Comment by alemorcuq** [comment]
I will create an internal task then. Thanks.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
