### ISSUE TITLE
Error: Deployment.apps "elasticsearch-coordinating-only" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

### ISSUE THREAD

**Issue by patsevanton** [bitnami/charts#6837]
Hello! I try install elasticsearch by helm from bitnami in Microk8s.

```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install elasticsearch bitnami/elasticsearch
```

Get error
```
Error: Deployment.apps "elasticsearch-coordinating-only" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
```

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

- Output of `kubectl version`:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by migruiz4** [comment]
Hi @patsevanton,

Looks like your Kubernetes is preventing the 'sysctl' initContainer from starting because it does not allow privileged containers.

Elasticsearch needs the sysctl initcontainer to configure the limits for VM virtual memory and file descriptor: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html
 
You can disable it using the value `sysctlImage.enabled=false`.
If Elasticsearch fails to start because of your cluster virtual memory limits, Elasticsearch documentation suggests using a different FS store type: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-virtual-memory.html

Using Bitnami Elasticsearch chart, additional configuration can be added using `extraConfig`:
```
extraConfig:
  index.store.type: niofs
```

**Comment by patsevanton** [comment]
@migruiz4 I use microk8s.
Sorry. I add to first post.

**Comment by migruiz4** [comment]
In that case, maybe this issue would help you: https://github.com/ubuntu/microk8s/issues/749

It looks like microk8s requires an additional flag to allow privileged containers.

**Comment by patsevanton** [comment]
I added `--allow-privileged` into `/var/snap/microk8s/current/args/kube-apiserver` and do a restart with `microk8s.stop; microk8s.start`

It work. Thanks!
