### ISSUE TITLE
ClickHouse support

### ISSUE THREAD

**Issue by jingwux** [bitnami/charts#6838]
**Which chart**:
ClickHouse 

**Is your feature request related to a problem? Please describe.**
I cannot find  available chart about clickhouse.

**Describe the solution you'd like**
Can your support it?

thanks

**Comment by alvneiayu** [comment]
hi @yuanqingx 

I created an internal to evaluate ClickHouse project (evaluate the possibility to create a bitnami container and a chart) and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot to share with us your request
Álvaro

**Comment by electrical** [comment]
There is a good clickhouse Operator available from https://github.com/Altinity/clickhouse-operator which pretty much handles everything.

**Comment by alvneiayu** [comment]
hi @electrical 

Thanks a lot for sharing with us a solution to this.

Álvaro

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by jingwux** [comment]
thanks 

> There is a good clickhouse Operator available from https://github.com/Altinity/clickhouse-operator which pretty much handles everything.

thanks very much.   (*￣︶￣)

**Comment by carrodher** [comment]
We just released the bitnami/clickhouse Helm chart, see
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
$ helm search repo bitnami/clickhouse
NAME              	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/clickhouse	0.2.0        	22.8.5     	ClickHouse is an open-source column-oriented OL...
```

You can find it at https://github.com/bitnami/charts/tree/master/bitnami/clickhouse
