### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by pjsofts** [bitnami/charts#6841]
PostgreSQL needs locale to be on the system.
It is usually done by echo "locale" >> /etc/locale.gen && locale-gen
Is there any way to use helm charts with a specific locale?

**Comment by javsalgar** [comment]
Hi,

I'm afraid you may have to add the locale you want by forking the image and adding it. Another option would be to launch the container as root so you can use the package manager, but I wouldn't recommend it in production.

**Comment by pjsofts** [comment]
Instead of a workaround, I'm suggesting this to be added as a feature.

**Comment by javsalgar** [comment]
The issue is that, if we allow any locale in the container, then the size of it would increase substantially. Because of this, we added this script that it is called during `docker build` https://github.com/bitnami/bitnami-docker-postgresql/blob/master/13/debian-10/rootfs/opt/bitnami/scripts/locales/add-extra-locales.sh

I see that it is missing the ARG section for the EXTRA_LOCALES variable, so I will create a task for fixing it.

**Comment by pjsofts** [comment]
So if I intend to use it with PostgreSQL helm charts, I need to build the custom docker image with EXTRA_LOCALES set as environment variables, then point to the image using helm charts parameters?

**Comment by javsalgar** [comment]
Hi,

Yes, that would be the case if you want to use custom locales.
