### ISSUE TITLE
Jenkins Job error - /script.sh: docker: not found

### ISSUE THREAD

**Issue by HareeshNRao** [bitnami/charts#6875]
bitnami/Jenkins

Job - Pipeline Style Item
Job Configuration - Using pipeline script from SCM and referenced with github that has the repository and Jenkins file
When we execute the job getting below error (i.e. docker not found)  . It seems Docker is not available in the Jenkins instance hence it could not connect to docker daemon and pull the docker image ppiper/cf-cli:7 as part of job execution.
We think Docker agent should be install on the Jenkins container and docker agent should access the docker demon on the host.
We need Docker-in-Docker kind of a container in the Pod. Please help how to fix this issue.

Error:
```
+ docker ps -q
/opt/bitnami/jenkins/jenkins_home/workspace/ABAPEnvironmentPipeline@tmp/durable-5de832b6/script.sh: 1: /opt/bitnami/jenkins/jenkins_home/workspace/ABAPEnvironmentPipeline@tmp/durable-5de832b6/script.sh: docker: not found
[Pipeline] echo
[WARNING][dockerExecute] Cannot connect to docker daemon (command 'docker ps' did not return with '0'). Configured docker image 'ppiper/cf-cli:7' will not be used.
```

**Comment by carrodher** [comment]
As you rightly said, `docker` is not installed in the bitnami/jenkins image but you can install it and use your custom image in the chart:

- Create a _Dockerfile_ as described in this section of the README: https://github.com/bitnami/bitnami-docker-jenkins#customize-this-image
- Build an image using the above _Dockerfile_: 
```
$ docker build -t myuser/jenkins:latest .
```
- Push this image to DockerHub (or any other registry): 
```
$ docker push myuser/jenkins:latest
```
- Use the custom image in the Helm Chart:
```
helm install myjenkins --set image.repository=myuser/jenkins --set image.tag=latest bitnami/jenkins
```
please, note if you used a registry different than DockerHub, you'll also need to set `image.registry`. In the same way, you can modify the _values.yaml_ and install the chart with `-f values.yaml` instead of the different `--set`

-------------------------------------------------------------------------------------------------

As the Bitnami images are used by different users in different use cases it's difficult to include all the required packages; we need to find a balance between image size, usability, etc; mainly this is the reason why there are packages no included by default but there are ways for users to customize the image adding more packages or any other customization.

**Comment by HareeshNRao** [comment]
We have created a custom image (based on bitnami/jenkins) but in the System Information page the Environment Variables HOME value is showing as  "/".   Please let us know how to set it to "/bitnami/jenkins/home".

**Comment by carrodher** [comment]
The Jenkins Home path is `/bitnami/jenkins/home` by default when deploying the Helm Chart, see https://github.com/bitnami/charts/tree/master/bitnami/jenkins#jenkins-configuration-parameters and the code in the _values.yaml_ that is used in the deployment:
```yaml
- values.yaml
## @param jenkinsHome Jenkins home directory
##
jenkinsHome: /bitnami/jenkins/home

- deployment.yaml
            - name: JENKINS_HOME
              value: {{ .Values.jenkinsHome | quote }}
```
because of that, I don't think the issue is related to the Jenkins Home but the path where the plugin is configured to look for the kube config files. I am not sure if the plugin can be configured to look for the files in a specific folder or you need to put the files in the place where the plugin is looking for (`/.kube/config`)

**Comment by HareeshNRao** [comment]
Hi Team,
Issue resolved after setting the Environment Variables HOME value to "/bitnami/jenkins/home".

Thanks a lot for your help.

**Comment by HareeshNRao** [comment]
below 2 issues resolved
1.  docker: not found
2.  java.io.FileNotFoundException: /.kube/config (No such file or directory)

**Comment by mreyesjonmarco** [comment]
Hello, I would like to re-open this as I need some guidance, I've tried building my own image using the Dockerfile Below

`FROM bitnami/jenkins
LABEL maintainer "Bitnami <containers@bitnami.com>"

## Change user to perform privileged actions
USER 0
RUN apt-get update && apt-get install -y docker 
## Revert to the original non-root user
USER 1001`

I also tried

`FROM bitnami/jenkins
LABEL maintainer "Bitnami <containers@bitnami.com>"

## Change user to perform privileged actions
USER 0
## Install 'vim'
RUN install_packages vim
## Revert to the original non-root user
USER 1001`

I then built the image using
`docker build -t mreyesjonmarco/jenkins:latest .`

I have this global tool configuration

![image](https://user-images.githubusercontent.com/88312943/142800208-bdd21475-5de9-4459-a3f5-d45e2c9f9700.png)

but when I run it on my local machine I have this issue:

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by carrodher** [comment]
We saw you created a new issue, in order to avoid duplicating the responses and the effort we will check the new one and provide an answer there.

**Comment by abhishekgupta2205** [comment]
@HareeshNRao can you please share your customised jenkins image dockerfile  where docker is running. i am stuck at problem where docker daemon is not connected

**Comment by renzglogc** [comment]
hi can anyone help me about this one ?
![image](https://user-images.githubusercontent.com/101684803/215452474-1a4380f0-8744-4773-8e66-985563667170.png)

**Comment by DilysNgo94** [comment]
I have same error @renzglogc
