### ISSUE TITLE
New OpenSearch helm chart

### ISSUE THREAD

**Issue by viceice** [bitnami/charts#6945]
**Which chart**:

Doesn't yet exists.

**Is your feature request related to a problem? Please describe.**

Currently I'm using the official elasticsearch helm chart from https://helm.elastic.co and are pinned to a version `<7.6` because of licensing issues.

**Describe the solution you'd like**
Now [OpenSearch](https://opensearch.org/) is released as v1 (has a migration path from ElasticSearch v7) i like to have an Bitnami chart of an OpenSearch.  

**Describe alternatives you've considered**
Wait for the official OpenSearch chart https://github.com/opensearch-project/opensearch-devops/pull/4

**Additional context**
No.

**Comment by pablogalegoc** [comment]
Hi @yuanqingx!

I created an internal task to evaluate the possibility of creating an OpenSearch Bitnami container and chart and added it to the backlog. Sadly, I am not able to give you an ETA. Other users have contributed charts with a PR (examples are MetalLB, Grafana Operator, kubernetes-event-exporter…) following our [chart guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository), and while we were reviewing it, we packaged the container. If you want to contribute, do not hesitate to open a PR and we will review it, otherwise we will update this thread once we have news.

Thanks a lot to share with us your request!

**Comment by viceice** [comment]
OK, official chart is now here: https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch

**Comment by rafariossaa** [comment]
Thanks for coming back and providing the link.

**Comment by jingwux** [comment]
> OK, official chart is now here: https://github.com/opensearch-project/helm-charts/blob/main/charts/opensearch

thanks

**Comment by shanginn** [comment]
yeah, but what about bitnami version of the chart?

your charts are so good, I would gladly use your version over the official one

**Comment by carrodher** [comment]
We checked it internally and evaluated the feasibility of adding this new product to the catalog, the result was to go ahead with this addition, although this process could take some time due to limited resources. We'll update this ticket once released the Helm chart.

**Comment by 0xHexE** [comment]
Hi, I released that the open-search is not available in the registry https://hub.docker.com/u/bitnamicharts so it fails.

**Comment by carrodher** [comment]
The Helm chart is now available as OCI package in DockerHub, see https://hub.docker.com/r/bitnamicharts/opensearch

**Comment by mandrean** [comment]
Hi,

I think we want to move away from internally maintained subcharts for supporting infra as they tend to become neglected/unmaintained and or riddled with bugs/inconsistencies VS. hardened production-worthy charts that more closely mimic the infra we want to e2e test 

Similar to how the outdated Disco Kafka chart was deprecated in favor of an up-to-date chart by Bitnami, I would say this is a good case for that as well:

https://github.com/bitnami/charts/blob/main/bitnami/opensearch/README.md

But if you're in a hurry I guess we can merge this and migrate later.
