### ISSUE TITLE
[bitnami/mongodb-sharded] DNS SRV record lookup

### ISSUE THREAD

**Issue by cmario** [bitnami/charts#6946]
Hello,

I have a sharded cluster running and I am testing the "mongodb+srv" connection string. Doing a DNS query I see that the SRV record contains all the nodes in the cluster, including shards, arbiters, config servers and mongos instances. The client driver understands what is a SHARD_ROUTER and excludes all the rest of the servers but it creates a lot of annoying error logs. I was just wondering if it is correct that the SRV record contains all the nodes in the cluster and/or if there is any other server name I can use to get only the list of the mongos instances.

Thank you
Best,
Mario

**Comment by javsalgar** [comment]
Hi,

I'm afraid currently the headless service contains all the nodes in mongodb. Do you think it would make more sense to create multiple headless services? Also, there is a service (non-headless) that only contains the mongos one, would that work for you?

**Comment by cmario** [comment]
yes, I think from a client perspective would make sense to have a dedicated headless service just related to mongos. Regarding the second question the non headless service would work and actually it works for me but I have the feeling that the driver would make a better job to detects failures and switch to alternative mongos instances. That is the reason I was trying to use the DNS approach and let the client discover and get the full list of mongos instances.

**Comment by javsalgar** [comment]
Thanks for the feedback. I will create a task for this improvement. I'm not able to provide an ETA but as soon as it is finished we will update this ticket.

**Comment by cmario** [comment]
Thanks a lot Javier. Looking forward to hearing from you.

Best,
Mario

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
