### ISSUE TITLE
[bitnami/harbor] User self service password reset

### ISSUE THREAD

**Issue by harrishcris** [bitnami/charts#6962]
Hello,

I have setup Harbor (using default database auth mode) and configured a SMTP server which returns "Connection to mail server is verified." when clicking on SMTP test. In the Harbor documentation it says "The email server is only used to send out responses to users who request to reset their password." however there is no "reset password" option on the Harbor login page and no way to send a password reset link via email using the API. Is there anyway for a user to self service password reset? Where are the SMTP server details used?

Thanks

Chris

**Comment by marcosbc** [comment]
Hi @harrishcris, you seem to be right, the password reset link disappeared:

![Screen Shot 2021-07-16 at 14 00 47](https://user-images.githubusercontent.com/5102866/125944366-d91bd24e-8b80-41fc-8523-b5bb4b642127.png)

Checking the code, it seems like it was removed in this commit: https://github.com/goharbor/harbor/commit/8e876cb946581d619edf0befb90b6c73caa3156d - and related to the issue #10712.

I would advise to open a new issue/bug report in the Harbor repo, asking clarification on why the SMTP configuration is still supported if the password reset feature was removed, since they mention [here](https://goharbor.io/docs/2.2.0/administration/general-settings/) that it's the only use for it.

**Comment by harrishcris** [comment]
What a shame, thanks @marcosbc
