### ISSUE TITLE
bitnami wildfly ingress not working after add ssl

### ISSUE THREAD

**Issue by ruwan1235** [bitnami/charts#6979]
I alredy used latest bitnami/wildfly helm chart.

And wildfly is alredy working fine but we are facing some issue in loading admition console.

In is working fine useing ip and port.
![Screenshot from 2021-07-15 11-30-22](https://user-images.githubusercontent.com/86238699/125924759-091497ca-b36a-400e-8e1d-2bd6453f9cdc.png)

do we need to do any changes to add ssl cetification? or do we neeed change standalone.xml ?

**Comment by migruiz4** [comment]
Hi @ruwan1235,

I'm sorry for the late response.

I tried to reproduce your issue but I couldn't. Could you please share some more details about your configuration?

Also, I noticed two errors in your console logs that might help us troubleshoot the issue:
- Requests going to `/console` are failing with error 403 (Forbidden/Unauthorized)
- Requests going to `/keycloak/` are failing because the address is not reachable (Error 404)
