### ISSUE TITLE
[bitnami/airflow] : Infinite redirect loop on opening Airflow Home Page 

### ISSUE THREAD

**Issue by jayaswalayush** [bitnami/charts#7010]
When we open the Login page in the browser we are getting too many redirects error. I have used LDAP for authentication

![image](https://user-images.githubusercontent.com/59866888/126457124-fafa59d0-68b8-495a-9d64-ad4b7de61330.png)

![image](https://user-images.githubusercontent.com/59866888/126457407-23464075-1cf2-4018-855c-349e15876af5.png)

Note : I am using ingress and I have already added proxy fix in extraEnvVars in values.yaml 

![image](https://user-images.githubusercontent.com/59866888/126457462-6592620e-5f32-4748-91b5-f69444582321.png)

**Comment by javsalgar** [comment]
Hi,

Did you set the `web.baseUrl` value? This could be related to the issue

**Comment by bdsoha** [comment]
@javsalgar 
I am having the exact same issue with the image `bitnami/airflow:2.1.1-debian-10-r7`.

And yes, `web.baseUrl` is set.

**Comment by jayaswalayush** [comment]
@javsalgar : Yes i have set web.baseUrl

![image](https://user-images.githubusercontent.com/59866888/126595833-aa079bbd-88d2-4010-8b08-2af08a227c68.png)

**Comment by javsalgar** [comment]
Thanks, and last question, does the same issue happen when not using https? Just to clearly spot the issue

**Comment by jayaswalayush** [comment]
@javsalgar : Yes the same issue in HTTP mode also 

![image](https://user-images.githubusercontent.com/59866888/126612682-10f2e465-9205-4587-8d7c-c5b520de4534.png)

**Comment by javsalgar** [comment]
Thank you for the input. I'll be on PTO until Tuesday. As soon as I'm back I'll work on reproducing the issue.

**Comment by bdsoha** [comment]
@javsalgar Hope you enjoyed the break.
Any updates?

**Comment by javsalgar** [comment]
Hi,

Thank you! I enjoyed the break :D 

I tred reproducing the issue but I couldn't.


![image](https://user-images.githubusercontent.com/1133777/127318618-835aab81-5c3a-49b9-a6ef-c1d9bd45f4c7.png)

I used the latest version of the chart 

These are the values

```
helm install airflow . --set web.baseUrl=http://dbarranco.net --set ingress.enabled=true --set extraEnvVars[0].name=AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX --set-string extraEnvVars[0].value="True" --set ingress.hosts[0].name=dbarranco.net
```

**Comment by jayaswalayush** [comment]
@javsalgar : Please test using TLS enabled for ingress and also if possible with LDAP enabled

**Comment by javsalgar** [comment]
It is also working

![image](https://user-images.githubusercontent.com/1133777/127502814-da64e0ab-6f53-455d-bf52-2495d5f89f00.png)


```
helm install airflow3 . --set web.baseUrl=https://dbarranco.net --set ingress.enabled=true --set extraEnvVars[0].name=AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX --set-string extraEnvVars[0].value="True" --set ingress.hosts[0].name=dbarranco.net
```

Could you try without LDAP? To see if the issue persists

**Comment by jayaswalayush** [comment]
@javsalgar : Yes it works fine without LDAP enabled

![image](https://user-images.githubusercontent.com/59866888/127603990-922d4bdf-f64a-4f8f-aa59-b80a33929ca6.png)

However when we enable LDAP then get this too many redirects error 

![image](https://user-images.githubusercontent.com/59866888/127604536-43d6d272-a9d8-4c8d-9d36-17df10d45492.png)

![image](https://user-images.githubusercontent.com/59866888/127604569-3bd5f215-da02-4fad-9e06-6d480368710a.png)

**Comment by javsalgar** [comment]
Hi,

I tried enabling the LDAP mode and it seems to work

![image](https://user-images.githubusercontent.com/1133777/127660757-f7431d97-6076-4773-ae3d-9ef1df28c235.png)

It is failing the login because it is unable to access the LDAP server, but I'm not getting the redirect loop you are getting.

**Comment by bdsoha** [comment]
@javsalgar 

> It is failing the login because it is unable to access the LDAP server, but I'm not getting the redirect loop you are getting.

You will only get an infinite redirect after a successful login.
In your case, you are not actually logging in.

**Comment by jayaswalayush** [comment]
@javsalgar : Infinte Redirect Loop is in case of successful login. Please check and help in providing a fix for it

**Comment by jayaswalayush** [comment]
@javsalgar : Thanks for the update. I will await for the fix in bitnami chart so that we can specify the correct values in the values.yaml file

**Comment by jayaswalayush** [comment]
@javsalgar : I hope the team enjoyed the vacation. 
Any updates on the release ?

**Comment by javsalgar** [comment]
Hi, I'm afraid it is still in our backlog. I will forward this to the team to see if we can proritize for future iterations (we are still in the middle of our sprint)

**Comment by NateDreier** [comment]
For situational awareness, I'm not sure this is directly related to Bitnami's chart. I came across this thread though don't use the Bitnami chart and still have the issue. 

Just to add some color, LDAP works fine but LDAPS, or enabling TLS or adding a filter other than `memberOf` breaks LDAP(S) for me.

**Comment by javsalgar** [comment]
I reproduced the issue with regular LDAP. @randradas is going to check the issue during the following weeks, he will be able to provide more details once he finds the solution.

**Comment by randradas** [comment]
OK finally I configured the /opt/bitnami/airflow/webserver_config.py with these fixes:

```
AUTH_ROLES_MAPPING = { "cn=users,ou=example,o=org": ["User"], "cn=admins,ou=example,o=org": ["Admin"], }
AUTH_LDAP_GROUP_FIELD = 'memberOf'
AUTH_ROLES_SYNC_AT_LOGIN = True
AUTH_PERM_SESSION_LIFETIME = 1800
```

and reviewed the ldap structure, user and password population. Unfortunately it seems the problem persists, I mean, I still got the ERR_TOO_MANY_REDIRECTS error after what looks like a successful log-in.

The openldap container perform bindings properly when I try to login with 'user01' but it leads me to the too many redirects error:

```
612cfaeb.1fe2fbd4 0x7f585ed8f700 conn=1015 op=2 BIND dn="cn=user01,ou=users,dc=example,dc=org" method=128
612cfaeb.1fe3c7bc 0x7f585ed8f700 conn=1015 op=2 BIND dn="cn=user01,ou=users,dc=example,dc=org" mech=SIMPLE bind_ssf=0 ssf=0
612cfaeb.1fe57ae4 0x7f585ed8f700 conn=1015 op=2 RESULT tag=97 err=0 qtime=0.000076 etime=0.000279 text=

```
My next step is to activate some logging and debugging options in the Flask App Builder component of Airflow (/opt/bitnami/airflow/airflow.cfg) in order to find more information about what is happening under the hood.

**Comment by jayaswalayush** [comment]
@randradas @javsalgar : Please any update on the fix for this issue ?

**Comment by randradas** [comment]
Hello @jayaswalayush finally I got rid of the ERR_TOO_MANY_REDIRECTS. There some things needed in order to integrate Airflow (which depends on Flask App Builder for this) with LDAP properly, please find them below:

1. **Specific webserver_config.py configuration variables**. This is not an airflow configuration file, it is a Flask App Builder which Airflow depends on to be integrated with LDAP. According to Flask App Builder's documentation and users there are needed some variables, it is not only about the ROLE_MAPPING but also about AUTH_LDAP_GROUP_FIELD, AUTH_ROLES_SYNC_AT_LOGIN and others. Also it is needed to comment the "from.... AUTH_DB" line, it is not allowed to keep both "from... AUTH_DB" and "from... AUTH_LDAP" uncommented.
2. **A properly configure LDAP scheme to match the variables configured in 'webserver_config.py',**. Once I got a proper LDAP scheme aligned with webserver_config.py (I wrote an example LDAP ldif file with it) it didn't work because it was needed to activate the 'memberOf' module in the LDAP server.

Because there are several changes, soon I will submit a PR (one for the airflow container and other for the helm chart) that generates a proper 'webserver_config.py file', stay tuned. Other than that it is very important to match the configuration with a proper LDAP scheme and 'memberOf' module activated, please find attached a LDAP ldif file with the example scheme I used that match the default bitnami chart configuration (the generated by the upcoming PR)
[airflow_openldap_scheme.zip](https://github.com/bitnami/charts/files/7104978/airflow_openldap_scheme.zip)

**Comment by jayaswalayush** [comment]
@randradas : Thanks for the update. I will wait for the updated helm chart which contains all the LDAP params which have to be passed from values.yaml

**Comment by randradas** [comment]
Hello @jayaswalayush thank you for your patience, finally I can be back with the fix. It is important to note the following in order to get Airflow + LDAP work.
1.  Airflow + OpenLDAP integration requires certain variables to be configured into webserver_config.py file. Some of them were missing.
2. These variables need to be set with proper values aligned with each use case's OpenLDAP.

We have released a new Airflow container version [bitnami/airflow:2.1.3-debian-10-r10](https://hub.docker.com/layers/bitnami/airflow/2.1.3-debian-10-r10/images/sha256-298020d1c539a9220e37332cfd341c30828858addcb5984630606df1cf540e36?context=explore) and a new [bitnami/airflow](https://github.com/bitnami/charts) Helm chart version that together can be use to deploy Airflow integrated with OpenLDAP.

As you can see in the links above, [some variables](https://github.com/bitnami/charts/pull/7484/files) have been added to the '`values.yaml`' file of the chart. They are the ones you need to get Airglow+OpenLDAP work. It helps to fulfil the requirement mentioned in the point 1 above.

Regarding point 2, it is needed to have a working **OpenLDAP server with 'memberOf' module installed**. This module is used by Airflow to look for the group a user belongs to so an Airflow role can be assigned according to the '`rolesMapping`' variable that is set in '`values.yaml`'. Also the scheme used in the OpenLDAP should fit the values used in 'values.yaml' into the 'ldap' section. E.g. if your OpenLDAP does not contain 'dc=example,dc=org' DN then the defaults values are not going to work (it will lead you to the ERR_TOO_MANY_REDIRECTS error again) and you need to custom them to your OpenLDAP scheme, the same happen with other values like the name of the groups and [roles](https://airflow.apache.org/docs/apache-airflow/stable/security/access-control.html) used in '`rolesMapping`' or the '`uidField`'. So be ready to set a proper OpenLDAP scheme aligned with the values configured in '`values.yaml`'.

In order to help you to set a first 'demo' environment please find below the OpenLDAP ldif file that you can use to init your directory with a scheme aligned with the chart default values (I used it during all my develop and testing):

```
# LDIF Export for dc=shihadeh,dc=intern
# Server: openldap (openldap)
# Search Scope: sub
# Search Filter: (objectClass=*)
# Total Entries: 9
#
# Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on May 5, 2021 2:59 pm
# Version: 1.2.5

version: 1

# Entry 1: dc=example,dc=org
dn: dc=example,dc=org
dc: example
o: example
objectclass: top
objectclass: dcObject
objectclass: organization

# Entry 2: cn=user01,dc=example,dc=org
dn: cn=user01,dc=example,dc=org
cn: user01
displayname: User 01
givenname: user01
mail: user01@user01mail.org
objectclass: inetOrgPerson
objectclass: top
sn: User01
userpassword: password01

# Entry 3: cn=user02,dc=example,dc=org
dn: cn=user02,dc=example,dc=org
cn: user02
displayname: User 02
givenname: user02
mail: user02@user02mail.org
objectclass: inetOrgPerson
objectclass: top
sn: User02
userpassword: password02

# Entry 4: ou=Groups,dc=example,dc=org
dn: ou=Groups,dc=example,dc=org
objectclass: organizationalUnit
objectclass: top
ou: Groups

# Entry 5: cn=Admins,ou=Groups,dc=example,dc=org
dn: cn=Admins,ou=Groups,dc=example,dc=org
cn: Admins
objectclass: groupOfUniqueNames
objectclass: top
uniquemember: cn=user01,dc=example,dc=org

# Entry 6: cn=All,ou=Groups,dc=example,dc=org
dn: cn=All,ou=Groups,dc=example,dc=org
cn: All
objectclass: groupOfUniqueNames
objectclass: top
uniquemember: cn=user02,dc=example,dc=org
```

You can insert this scheme in the OpenLDAP using the following command:

`$ ldapmodify -a -x -D "cn=admin,dc=example,dc=org" -W -H ldap://localhost:1389 -f ./bootstrap.ldif`

Other than that remember that the **'memberOf' module is required** in your OpenLDAP server.

Hope it helps.

**Comment by jayaswalayush** [comment]
@randradas : Thanks for the update. I tested it out and LDAP login works seamlessly

**Comment by randradas** [comment]
thank you!!
