### ISSUE TITLE
[ghost] livenessProbe/readinessProbe failing when ghostEnableHttps=true

### ISSUE THREAD

**Issue by insekticid** [bitnami/charts#7021]
bug no 1 - there is no http port when ghostEnableHttps=true https://github.com/bitnami/charts/blob/master/bitnami/ghost/templates/deployment.yaml#L183

bug no 2 - missing options in readinessProbe/livenessProbe when ghostEnableHttps=true resulting in error - http: server gave HTTP response to HTTPS client
    
```
 httpHeaders:
 - name: X-Forwarded-Proto
   value: https
```

fix described here https://github.com/helm/charts/pull/11898/files

bug no 3 - ingress serviceport is always http instead of https 
https://github.com/bitnami/charts/blob/master/bitnami/ghost/templates/ingress.yaml#L37

**Comment by alemorcuq** [comment]
Thanks for reporting this, @insekticid. I have created an internal task to investigate and fix this issue.

**Comment by acim** [comment]
I get the same error with ghostEnableHttps=false.

**Comment by alemorcuq** [comment]
Thanks, @acim. We have a task to work on this. Unfortunately, I can't give you an ETA.

**Comment by ElanHasson** [comment]
i'm having the same issue as well.

**Comment by ElanHasson** [comment]
I'm not seeing the liveness probe contain these:

https://github.com/javsalgar/charts/blob/master/stable/ghost/templates/deployment.yaml#L139-L145

**Comment by pablogalegoc** [comment]
Hi @ElanHasson!

That repo you reference is a fork of the obsolete [helm/charts](https://github.com/helm/charts).
On the issue itself, as @alemorcuq said, we have it in our backlog but we are a small team and we can't say when it is going to enter a development iteration, sorry.

**Comment by ElanHasson** [comment]
Thanks @pablogalegoc, ports are the same here: https://github.com/bitnami/charts/blob/master/bitnami/ghost/values.yaml#L265-L267

If you can elaborate on the issue a bit I may be to send a PR to fix-- just need a hand on what ya'll see the issue as.

**Comment by pablogalegoc** [comment]
@insekticid I've taken a quick look and hard to tell to me. Chart configuration seems fine, the issue may come from the Ghost server on the Docker image, not taking into account the `GHOST_ENABLE_HTTPS=yes`. Part of the ticket we've created is investigation, sorry 😅

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/ghost#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute by creating a PR; the Bitnami team will be happy to review it and provide feedback.
