### ISSUE TITLE
[meta] PodDisruptionBudget apiVersion `policy/v1`

### ISSUE THREAD

**Issue by z0rc** [bitnami/charts#7039]
**Which chart**:
All charts with PDB.

**Is your feature request related to a problem? Please describe.**
```
policy/v1beta1 is deprecated since 1.21 and will be removed in 1.25
```

**Describe the solution you'd like**
Upgrade all PDBs to support new apiVersion.

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/kubernetes/kubernetes/blob/v1.21.3/CHANGELOG/CHANGELOG-1.21.md?plain=1&rgh-link-date=2021-07-23T09%3A07%3A59Z#L602

**Comment by carrodher** [comment]
Thanks for letting us know, we have a library chart (bitnami/common) that is included in all the charts to provide common functions. There is a capabilities template where the apiVersion is defined based on the k8s version for different objects, it seems we will need to add a new function in that file, see https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl.

Then use the new function in all the charts using PDB. Would you like to contribute by adding this function to the mentioned file and use it in the different charts? Otherwise I will create an internal task to do it

**Comment by z0rc** [comment]
@carrodher about mentioned template. I'm not sure checking Kubernetes version is the right approach here. Helm provides `.Capabilities.APIVersions.Has` function for this kind of checks. Also checking Kuberenes version is error prone with various cloud providers, who happen to use uncommon "pre-release" version, for example https://github.com/aws/containers-roadmap/issues/1404.

Also I'm using just single chart from this repo, so I don't have means to tests this for every chart. I let you handle the required changes.

**Comment by z0rc** [comment]
Actually I missed that this is already resolved at https://github.com/bitnami/charts/pull/6662. Feel free to look into `.Capabilities.APIVersions.Has`, but there is nothing to do about this specific issue.
