### ISSUE TITLE
[bitnami/etcd] preStop fails

### ISSUE THREAD

**Issue by renier** [bitnami/charts#7048]
> Warning   FailedPreStopHook   pod/etcd-2                                   Exec lifecycle hook ([/opt/bitnami/scripts/etcd/prestop.sh]) for Container "etcd" in Pod "etcd-2_ntc-renier(5975b36c-200c-498c-8bcf-1adfc86341ac)" failed - error: command '/opt/bitnami/scripts/etcd/prestop.sh' exited with 128: Error: bad member ID arg (strconv.ParseUint: parsing "": invalid syntax), expecting ID in Hex

With a cluster of 3 replicas, if I scale down to 2 replicas I get this ` FailedPreStopHook` event. If I exec into one of the existing replicas and list members, all three members appear.

This situation makes it so that if I scale back to 3 replicas, the new one cannot join due to the cluster being unhealthy (due to strict-reconfig-check which I don't want to disable) since it is still missing the lost member.

Looking at the preStop.sh more closely, I noticed that it relies on `${ETCD_DATA_DIR}/member_id` existing. However, this file is not created in this script.

It can be created by calling one of the functions defined in [libetcd.sh](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh) called `etcd_store_member_id`, but this function is not called explicitly from the preStop script.

Digging a bit more, it does seem that during initialization this function is called under "some" circumstances. None of which seem to fit my particular use case, since the `member_id` file does not end up in any of my healthy functioning members. You see, I'm not using [snapshotting](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L380) nor [PVs](https://github.com/bitnami/bitnami-docker-etcd/blob/master/3/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L414). I'm simply using etcd as a distributed cache.

Regardless, if the `member_id` file is a dependency of the preStop script, it would be better if it checked for it and created if it didn't exist **from** the preStop script.

**Comment by alemorcuq** [comment]
Thanks for reporting this, @renier. I think this is the same as issue #6251.

We hope to start working on it soon.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
