### ISSUE TITLE
[bitnami/mongodb] Unable to connect to MongoDB replicaset using Nodejs MongoDB 4.0 Driver

### ISSUE THREAD

**Issue by kaykhancheckpoint** [bitnami/charts#7050]
Hi friends,

I have a mongodb replicaset setup using this helm chart. I use a mongodb nodejs driver https://github.com/mongodb/node-mongodb-native to connect to mongodb, there has been a recent update to this driver that stops me from connecting to my mongodb.

I am attempting to connect to mongodb using the following code:

**mongodb.ts**

```
import { MongoClient } from "mongodb";
import { Config } from "@config";

let MongoConnection;

console.log(Config);
export const MongoDBService = async (): Promise<MongoClient> => {
    if (MongoConnection) {
        return MongoConnection;
    }

    try {
        const client = new MongoClient(Config.mongo, {
            replicaSet: "rs0",
            // directConnection: true
        });

        MongoConnection = await client.connect();
    } catch (error) {
        console.log(error);
    }

    return MongoConnection;
};
```
When i do i get the following error:

> MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local
>     at Timeout._onTimeout (/home/kay/checkpoint/mongodb-consumer/node_modules/mongodb/src/sdam/topology.ts:583:30)
>     at listOnTimeout (internal/timers.js:557:17)
>     at processTimers (internal/timers.js:500:7) {
>   reason: TopologyDescription {
>     type: 'ReplicaSetNoPrimary',
>     servers: Map(2) {
>       'mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local:27017' => [ServerDescription],
>       'mongodb-prod-arbiter-0.mongodb-prod-arbiter-headless.mongodb.svc.cluster.local:27017' => [ServerDescription]
>     },
>     stale: false,
>     compatible: true,
>     heartbeatFrequencyMS: 10000,
>     localThresholdMS: 15,
>     setName: 'rs0',
>     maxSetVersion: 2,
>     maxElectionId: new ObjectId("7fffffff0000000000000003"),
>     commonWireVersion: 9,
>     logicalSessionTimeoutMinutes: undefined
>   }
> }
> 

if i enable the option `directConnection` it connects successfully, The [documentation](https://github.com/mongodb/node-mongodb-native/blob/4.0/docs/CHANGES_4.0.0.md#mongoclientoptions-interface) says 

> NOTE: With the unified topology, in order to connect to replicaSet nodes that have not been initialized you must use the new directConnection option.

**Im abit confused what it means when it says "replicaSet node that have not been initialized". I'm  not sure if i have misconfigured my mongodb or not. Hoping someone can shed some light on this for me.**

```
rs0:PRIMARY> rs.status();
{
	"set" : "rs0",
	"date" : ISODate("2021-07-24T15:14:58.357Z"),
	"myState" : 1,
	"term" : NumberLong(3),
	"syncSourceHost" : "",
	"syncSourceId" : -1,
	"heartbeatIntervalMillis" : NumberLong(2000),
	"majorityVoteCount" : 2,
	"writeMajorityCount" : 1,
	"votingMembersCount" : 2,
	"writableVotingMembersCount" : 1,
	"optimes" : {
		"lastCommittedOpTime" : {
			"ts" : Timestamp(1627139688, 1),
			"t" : NumberLong(3)
		},
		"lastCommittedWallTime" : ISODate("2021-07-24T15:14:48.623Z"),
		"readConcernMajorityOpTime" : {
			"ts" : Timestamp(1627139688, 1),
			"t" : NumberLong(3)
		},
		"readConcernMajorityWallTime" : ISODate("2021-07-24T15:14:48.623Z"),
		"appliedOpTime" : {
			"ts" : Timestamp(1627139688, 1),
			"t" : NumberLong(3)
		},
		"durableOpTime" : {
			"ts" : Timestamp(1627139688, 1),
			"t" : NumberLong(3)
		},
		"lastAppliedWallTime" : ISODate("2021-07-24T15:14:48.623Z"),
		"lastDurableWallTime" : ISODate("2021-07-24T15:14:48.623Z")
	},
	"lastStableRecoveryTimestamp" : Timestamp(1627139688, 1),
	"electionCandidateMetrics" : {
		"lastElectionReason" : "electionTimeout",
		"lastElectionDate" : ISODate("2021-06-07T09:28:28.932Z"),
		"electionTerm" : NumberLong(3),
		"lastCommittedOpTimeAtElection" : {
			"ts" : Timestamp(1623057684, 1),
			"t" : NumberLong(2)
		},
		"lastSeenOpTimeAtElection" : {
			"ts" : Timestamp(1623057684, 1),
			"t" : NumberLong(2)
		},
		"numVotesNeeded" : 2,
		"priorityAtElection" : 5,
		"electionTimeoutMillis" : NumberLong(10000),
		"numCatchUpOps" : NumberLong(0),
		"newTermStartDate" : ISODate("2021-06-07T09:28:28.937Z"),
		"wMajorityWriteAvailabilityDate" : ISODate("2021-06-07T09:28:29.037Z")
	},
	"members" : [
		{
			"_id" : 0,
			"name" : "mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local:27017",
			"health" : 1,
			"state" : 1,
			"stateStr" : "PRIMARY",
			"uptime" : 4081602,
			"optime" : {
				"ts" : Timestamp(1627139688, 1),
				"t" : NumberLong(3)
			},
			"optimeDate" : ISODate("2021-07-24T15:14:48Z"),
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"electionTime" : Timestamp(1623058108, 1),
			"electionDate" : ISODate("2021-06-07T09:28:28Z"),
			"configVersion" : 2,
			"configTerm" : 3,
			"self" : true,
			"lastHeartbeatMessage" : ""
		},
		{
			"_id" : 1,
			"name" : "mongodb-prod-arbiter-0.mongodb-prod-arbiter-headless.mongodb.svc.cluster.local:27017",
			"health" : 1,
			"state" : 7,
			"stateStr" : "ARBITER",
			"uptime" : 4081600,
			"lastHeartbeat" : ISODate("2021-07-24T15:14:56.990Z"),
			"lastHeartbeatRecv" : ISODate("2021-07-24T15:14:57.480Z"),
			"pingMs" : NumberLong(0),
			"lastHeartbeatMessage" : "",
			"syncSourceHost" : "",
			"syncSourceId" : -1,
			"infoMessage" : "",
			"configVersion" : 2,
			"configTerm" : 3
		}
	],
	"ok" : 1,
	"$clusterTime" : {
		"clusterTime" : Timestamp(1627139688, 1),
		"signature" : {
			"hash" : BinData(0,"dIuAMKqhd4r5pTZtTU6zrH+SFgU="),
			"keyId" : NumberLong("6970978542725103620")
		}
	},
	"operationTime" : Timestamp(1627139688, 1)
}
```

**Comment by Mauraza** [comment]
Hi @kaykhancheckpoint,

It seems that not found `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local`
When you deploy MongoDB something like this appears: 

```bash
NAME: mongodb
LAST DEPLOYED: Mon Jul 26 09:32:20 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

MongoDB(R) can be accessed on the following DNS name(s) and ports from within your cluster:

    mongodb.default.svc.cluster.local

To get the root password run:

    export MONGODB_ROOT_PASSWORD=$(kubectl get secret --namespace default mongodb -o jsonpath="{.data.mongodb-root-password}" | base64 --decode)

To connect to your database, create a MongoDB(R) client container:

    kubectl run --namespace default mongodb-client --rm --tty -i --restart='Never' --env="MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" --image docker.io/bitnami/mongodb:4.4.7-debian-10-r5 --command -- bash

Then, run the following command:
    mongo admin --host "mongodb" --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

To connect to your database from outside the cluster execute the following commands:

    kubectl port-forward --namespace default svc/mongodb 27017:27017 &
    mongo --host 127.0.0.1 --authenticationDatabase admin -p $MONGODB_ROOT_PASSWORD
```

Is the access inside or outside the cluster?

**Comment by kaykhancheckpoint** [comment]
@Mauraza 

> Is the access inside or outside the cluster?

I'm accessing mongodb from outside of my kubernetes cluster.

**Comment by Mauraza** [comment]
Hi @kaykhancheckpoint,

In that case you can't use `'mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local:27017' ,
'mongodb-prod-arbiter-0.mongodb-prod-arbiter-headless.mongodb.svc.cluster.local:27017'` that in for inside the cluster. 
if you check this type of deploy appears this for connection outside:
```
To connect to your database nodes from outside, you need to add both primary and secondary nodes hostnames/IPs to your Mongo client. To obtain them, follow the instructions below:

  NOTE: It may take a few minutes for the LoadBalancer IPs to be available.
        Watch the status with: 'kubectl get svc --namespace default -l "app.kubernetes.io/name=mongodb,app.kubernetes.io/instance=mongodb,app.kubernetes.io/component=mongodb,pod" -w'

    MongoDB(R) nodes domain: You will have a different external IP for each MongoDB(R) node. You can get the list of external IPs using the command below:

        echo "$(kubectl get svc --namespace default -l "app.kubernetes.io/name=mongodb,app.kubernetes.io/instance=mongodb,app.kubernetes.io/component=mongodb,pod" -o jsonpath='{.items[*].status.loadBalancer.ingress[0].ip}' | tr ' ' '\n')"

    MongoDB(R) nodes port: 27017
```

You can get the information about the IP and the services running `kubectl get svc --namespace default` you need to change 'default' for the namespace you deployed mongodb

**Comment by kaykhancheckpoint** [comment]
@Mauraza 

I don't quite understand what you mean.

Just to confirm i did not set those values for members[].name, this chart automatically sets `mongodb-prod-0.mongodb-prod-headless.mongodb.svc.cluster.local:27017'` and `mongodb-prod-arbiter-0.mongodb-prod-arbiter-headless.mongodb.svc.cluster.local:27017`.

What i have done is enabled externalAccess with type loadblanacer. Which automatically creates an external endpoint such as `http://<redacted>-<redacted>.us-east-2.elb.amazonaws.com:27017/` this endpoint is what i use to connect to mongodb. 

![image](https://user-images.githubusercontent.com/65535942/127287807-67564ce9-9fb8-44c7-a481-82bd33ad6eef.png)

**Comment by Mauraza** [comment]
Hi @kaykhancheckpoint,

Did you try to access mongo using the command line? if not, could you try it and tell us what happened? 
```
mongosh "mongodb://<redacted>-<redacted>.us-east-2.elb.amazonaws.com:27017" --username USER --authenticationDatabase DATABASE
```
You can check the documentation of MongoDB for more information about this https://docs.mongodb.com/mongodb-shell/connect/#connect-to-a-deployment.

**Comment by kaykhancheckpoint** [comment]
@Mauraza 

yes i can connect using 

```
mongo mongodb://<redacted>-<redacted>.us-east-2.elb.amazonaws.com:27017 --authenticationDatabase admin -u root -p <redacted>```

This was never a problem

**Comment by Mauraza** [comment]
Hi @kaykhancheckpoint,

The `directConnection=true` indicates you want to connect to that host, you can get more information in MongoDB documentation https://docs.mongodb.com/drivers/node/current/fundamentals/connection/#direct-connection. 
"`replicaSet node that have not been initialized`" could happen when the connection is not with the primary.

**Comment by kaykhancheckpoint** [comment]
@Mauraza

1.  If you have a mongodb replicaset should you be using `directConnection` ?

2. if i'm not able to connect to my mongodb replicaset without using `directConnection` have i misconfigured my mongodb setup?

**Comment by Mauraza** [comment]
Hi @kaykhancheckpoint,

It seems that `directConnection` needs it, but in this case that the question is relates to the application I suggest posting your question in the official forum https://www.mongodb.com/community/forums/

**Comment by simplenotezy** [comment]
@kaykhancheckpoint Kay, did you ever solve this issue? We are facing the same issue now. We can login fine inside the Cluster, but when we try to use the connection string locally it won't work. Compass works fine though, which is very strange.

This is the error message I get locally when trying to connect to a replicaset:
```
MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb-0.mongodb-headless.mongodb.svc.cluster.local
    at Timeout._onTimeout (/Users/mf/Projects/X/backend/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(5) {
      'mongodb-0.mongodb-headless.mongodb.svc.cluster.local:27017' => [ServerDescription],
      'mongodb-1.mongodb-headless.mongodb.svc.cluster.local:27017' => [ServerDescription],
      'mongodb-2.mongodb-headless.mongodb.svc.cluster.local:27017' => [ServerDescription],
      'mongodb-3.mongodb-headless.mongodb.svc.cluster.local:27017' => [ServerDescription],
      'mongodb-arbiter-0.mongodb-arbiter-headless.mongodb.svc.cluster.local:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'rs0',
    maxSetVersion: 11,
    maxElectionId: ObjectId { [Symbol(id)]: [Buffer [Uint8Array]] },
    commonWireVersion: 9,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined
}
```

As you can see, it tries to access `mongodb-3.mongodb-headless.mongodb.svc.cluster.local:27017` which naturally won't work locally, since that's a SVC inside the cluster.

**Comment by edemen** [comment]
Spent hours on this problem. It is crazy that many people all around have this problem yet on the official community forums it is not properly addressed.
Kudos!

**Comment by andrejvanderzee** [comment]
Facing exactly the same issue.

@edemen @simplenotezy  Any solutions to this problem?

**Comment by edemen** [comment]
@andrejvanderzee for me `directConnection=true` is the acceptable solution

**Comment by ZachThill** [comment]
To whom it may concern, 

Just recently I was running into similar issues while deploying a MongoDB replicaset to EKS with the Bitnami chart. Through all adversity and issues I ran into, I have found all the workarounds needed to get the replicaset deployed, enable external access, and be able to connect to the replicaset without needing `directConnection=true`. To all the future suffering engineers, below I define the method for working around all issues with this chart if you need external access and TLS enabled.

When installing this helm chart to your kubernetes cluster and deploying a `statefulSet` you first have to install it with `exteralAccess` disabled. The reason for this is the fact that the javascript templates that Bitnami uses to initialize the replicaset don't work with the external `LoadBalancer` service type. 

After you have installed the chart with `externalAccess` disabled, you want to enable `externalAccess` and upgrade the chart (i.e. applying the chart again). This will create your external services for your replicaset and retain it's functionality. 

However, doing just this will only allow you to connect to the replicaset via `directConnection=true` which will bottleneck your application and destroy it's possible performance. Luckily, I have found a way to workaround this as well, but frankly I would recommend to a seasoned engineer: just build your own custom helm chart and learn/research about creating a MongoDB replicaset because it might be much easier to just do that than deal with this. For those that wish to continue down the Bitnami chart path, following the steps below will allow your developers to connect their app to the entire replicaset instead of having to define `directConnection=true` with mTLS enabled.

## Supporting `directConnection=false` (AWS Workaround)

**NOTE:** This is what worked for me on AWS EKS, but there's a good chance that this method may work for all other cloud providers as well. 

Prerequisites:
 - EKS cluster exists
 - kubectl and helm are installed on local machine
 - K8s context is checked-out
 - `aws-load-balancer-controller` pods are deployed and ready on cluster

1. Install chart on K8s cluster with `externalAccess` disabled - Initializes replicaset
           - `tls.enabled:` and `tls.mTLS.enabled:` are both set to `true`
           - Add custom FQDNs to the `tls.extraDnsNames:` list so that the CA init container will add them to the SAN of the certificates.
           - `externalAccess.enabled:` is set to `false` 
2. Upgrade chart on K8s cluster with `externalAccess` enabled w LoadBalancer - Creates external services for replicaset
           - `externalAccess.enabled:` is set to `true` 
3. Use `kubectl` to exec into the `PRIMARY` pod and then use `mongosh` to connect to the local database. 
           - Follow the [official MongoDB documentation](https://www.mongodb.com/docs/manual/tutorial/change-hostnames-in-a-replica-set/) and change the hostname values in `rs.conf()` to match your custom FQDNs defined in the SAN.
4. Go into `route53` and create CNAME records pointing your custom FQDNs to the FQDN of the network load balancers
5. Use `kubectl` to copy the `mongodb.pem` and `mongodb-ca-cert` from the `PRIMARY` pod to your local machine. 

From here, you should be able to port-forward your local machine into a jump-box or any node within your VPC and access the entire mongodb replicaset (so long as your SG rules are allowing it). I use MongoDB Compass and that works just fine when configuring `General`, `Authentication`, `TLS/SSL`, and `Proxy/SSH` respectively.
