### ISSUE TITLE
[bitnami/contour] Deploy using a DeamonSet

### ISSUE THREAD

**Issue by MatthieuCoder** [bitnami/charts#7077]
**Which chart**:
bitnami/contour

**Is your feature request related to a problem? Please describe.**
For environments without access to a loadbalancer, we should be able to deploy contour using a DeamonSet instead of a standard deployment

**Describe the solution you'd like**
A deploymentType field where we can either specfy DeamonSet or Deployment

**Describe alternatives you've considered**
A alternative chart where a DeamonSet is used

**Comment by juan131** [comment]
Hi @MatthieuCoder 

Thanks so much for the feedback!!

In other similar charts, such as NGINX Ingress Controller, we offer a "kind" parameter that allows user to decide whether to deploy the solution using a deployment or a daemonset, see:

- https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller#nginx-ingress-deployment--daemonset-parameters

Would sth like that work for you?

**Comment by MatthieuCoder** [comment]
That would totally work!

**Comment by juan131** [comment]
Thanks @MatthieuCoder !! I'll try to send a PR adding this feature in the next days.

Before starting, one last question: we're already deploying Envoy as a Daemonset. Why do you need Contour to be on every node of the k8s cluster too?

Check [Contour Architecture](https://projectcontour.io/docs/v1.16.0/architecture/), Envoy is the one acting as a proxy and receiving the HTTP/HTTPS requests. Therefore, I understand that it's necessary to have an Envoy pod on every node of the cluster when there's no support for LoadBalancer services. However, I don't see why you need Contour on every node since it's just responsible of monitoring the defined Ingress rules and updating the Envoy configuration.

**Comment by MatthieuCoder** [comment]
Excuse me, I thought envoy was only deployed as a Deployment
