### ISSUE TITLE
I need a new helmchart on citusdata

### ISSUE THREAD

**Issue by prakash7396** [bitnami/charts#7165]
**Which chart**:
The name (and version) of the affected chart

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
(paste your output here)
```

- Output of `kubectl version`:

```
(paste your output here)
```

**Additional context**

**Comment by migruiz4** [comment]
Hi @prakash7396,

Thank you for your suggestion! I have created an internal task to evaluate adding Citus Data to our catalog.

**Comment by prakash7396** [comment]
hi Team,


When can I guess that the citus data helm chart will be there in github . .
Thanks in advance .

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR. If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by prakash7396** [comment]
Hi Team,

Any update?

**Comment by carrodher** [comment]
I'm sorry but still no news, due to the small size of the team we didn't find the required bandwidth to work on this, we will update this GH issue with more news.

**Comment by prakash7396** [comment]
Hi Team, any update

**Comment by carrodher** [comment]
Hi, unfortunately, there is no news regarding the addition of this Helm chart to the catalog. Taking a look at our roadmap, it is not something we will work on in the short term.

Being said that, contributions via PRs are welcome, [here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the contributing guidelines in case you want to work on this chart addition; we will be happy to review any PR.

**Comment by prakash7396** [comment]
Hi Team,

Any update?

**Comment by carrodher** [comment]
No, sorry, there is no news regarding this topic. Due to other priorities and team capacity, it's not something we will work on it in the short term.

**Comment by prakash7396** [comment]
can u please tell me estimation time.

**Comment by carrodher** [comment]
There is no ETA for new chart additions, it should be evaluated, and if decided to include it as part of the catalog, the engineering team will work on that.
But it is possible after the evaluation it is not considered to be developed in the short term, which is this case. The request was internally created and it can be considered in the future depending on the priorities and bandwidth.

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
