### ISSUE TITLE
Mangeto redirect fail

### ISSUE THREAD

**Issue by schroedt** [bitnami/charts#7296]
Hi There,

I used helm for deploying `Magento`. I am using istio traffic routing for entering Magento successfully.
Only admin behaves very strange:
- `/admin` shifted from `https` (istio) to `http`, `--set magentoUseSecureAdmin=true \` resolved that
- `/`(shop) mixed up ports, `--set service.port=443 \` fixed for staying on https (istio)

I noticed everything in URL is doubled and `HTTP 302` redirected:
- /admin/admin/
- /index/index/

```
https://magento.my-example.de/admin/admin/index/index/key/f5eb0021f885927eafb87d3ec95857a8b55eda1c934821ad4617071a8765179b/
```

**Helm Install**
```
              helm install magento bitnami/magento --namespace magento \
                --set magentoUsername=*** \
                --set magentoPassword=*** \
	        --set magentoHost=magento.mx-example.de \
	        --set service.port=443 \
	        --set magentoUseSecureAdmin=true \
	        --set ingress.tls=true \
                --set mariadb.enabled=false \
                --set externalDatabase.host=release-10-4-mariadb.mariadb.svc.cluster.local \
                --set externalDatabase.port=3306 \
                --set externalDatabase.user=app_magento \
                --set externalDatabase.password=*** \
                --set externalDatabase.database=app_magento \
                --set image.debug=true
```

**Comment by marcosbc** [comment]
Hi @schroedt, the two main things you pointed out are expected (`/admin` on `https` and `/` mixed ports), due to how the app works.

As for the URL parameters being doubled, this is apparently the [default setting](https://magento.stackexchange.com/questions/195445/magento-2-the-words-admin-and-index-appear-twice-in-the-admin-url), so I don't think there's anything to worry.

**Comment by schroedt** [comment]
Hi @marcosbc,

thanks for the update related to /admin/admin/index/index.

is there any configuration option accepting / keeping the protocol without `Magento` updating/changing it? Traffic is Istio encrypted, Magento should stay without TLS, but accept browsers HTTPS protocol?

**Comment by marcosbc** [comment]
Hi @schroedt, thanks for the details. I'd say that you would need to set Magento to be configured for HTTPS, but the proxy must be prepared to serve an appropriate header so that Magento recognizes it as such.

In your case it would be necessary to set [`X-Forwarded-Proto`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), and it seems like [Magento supports this](https://docs.magento.com/user-guide/stores/store-urls.html#configure-the-secure-base-url).

>Most Magento installations use the default `X-Forward-Proto` Offloader Header to identify the protocol as either `HTTP` or `HTTPS`. If your server configuration uses a different `offloader_header`, enter it here.

It could be possible that your Istio deployment uses a different header, in which case you would need to modify the `offloader_header` parameter in Magento configuration as mentioned in their [documentation](https://docs.magento.com/user-guide/stores/store-urls.html#configure-the-secure-base-url).

**Comment by schroedt** [comment]
Hi @marcosbc,

As stated above, I do have `X-Forward-Proto` set to `$scheme`.
As I changed config for visibiity; please find attached current config:
```
# reverse proxy
    location / {
	# Security Limits
	limit_req		zone=limit burst=1000 nodelay;
	limit_conn		addr 100;
	
        # Buffer Limits
        proxy_buffer_size       16k;	# Default: 4k
	proxy_buffers           64 16k;	# Default 8 4k
	proxy_busy_buffers_size 32k;
	#proxy_read_timeout	30;

        # DNS refresh
	set $backend ****;
	
	proxy_pass		https://$backend:30000;
	proxy_http_version	1.1;
	
        proxy_set_header Upgrade           $http_upgrade;
	proxy_set_header Connection        "upgrade";
	proxy_set_header Host              $host;
	proxy_set_header X-Real-IP         $remote_addr;
	proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-Host  $host;
	proxy_set_header X-Forwarded-Port  443;
	add_header X-Frame-Options	   "allow-from https://portal.my-example.de/";
	
	proxy_set_header Referer	   $http_referer;
```

`Magento` still throws the error.

**Comment by marcosbc** [comment]
Unfortunately I'm unsure on what is the issue with your proxy, but for sure this is a scenario supported by the Magento application.

That said, note that you can update the `base_url`/`secure_base_url` options via CLI in the same way the admin panel would:

```
$ magento config:set web/secure/base_url https://yournewdomain.com/
$ magento config:set web/secure/base_url https://yournewdomain.com/
$ magento config:set web/secure/use_in_frontend 1
$ magento config:set web/secure/use_in_adminhtml 1
```

You may also need to clear the cache afterwards:

```
$ magento cache:clean
```

Also, in order to reload the PHP code for the Magento application, you may need to recompile the Magento code and reload the web server:

```
$ magento setup:di:compile
$ apachectl -k graceful
```

Afterwards, you can reload your web server and those configurations would have been applied.

Feel free to try and play with those options, and let us know if you are able to get it work.

**Comment by schroedt** [comment]
Hi @marcosbc,

I updated the values via DB and deleted all related `PV` and `PVC`. After re-installing `Magento`-Admin was reachable.

Thanks for your support!
