### ISSUE TITLE
Add appsmith and airbyte Charts

### ISSUE THREAD

**Issue by liguilini** [bitnami/charts#7297]
It is possible add [appsmith ](https://github.com/appsmithorg/appsmith)and [airbyte ](https://github.com/airbytehq/airbyte)helm charts?
Thanks!

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container image is not part of the Bitnami catalog at this moment (it would be this case), we can work on that part while we review the Chart PR. If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by carrodher** [comment]
Hi @liguilini, we have evaluated adding Airbyte to the catalog, however, we have found some blockers for packaging it with our requirements and packaging structure. We might reconsider it in the future but for now, we will not add Airbyte to the Bitnami Application Catalog.

Regarding Appsmith, we are currently working on the container images, hopefully, they will be added to the catalog sooner rather than later. Once released the container images, we will start working on the Helm chart so a PR should appear in this repository during the next weeks.

**Comment by carrodher** [comment]
We're glad to announce that the [bitnami/appsmith](https://github.com/bitnami/charts/tree/main/bitnami/appsmith) is published:
```console
$ helm search repo bitnami/appsmith
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/appsmith	0.1.0        	1.8.8      	Appsmith is an open source platform for buildin...
```
