### ISSUE TITLE
[bitnami/mongodb] Allow metrics user to be configurable

### ISSUE THREAD

**Issue by tielou** [bitnami/charts#7310]
**Which chart**:
mongodb:10.23.13

**Is your feature request related to a problem? Please describe.**
As of now the user which the metrics exporter uses is hardcoded as `root` if the authentication is enabled. We don't have a `root` user enabled in our setup and therefore can't use the chart out of the box. It would be great if one could manually configure credentials for the metrics exporter to use.

**Describe the solution you'd like**
Values to configure a username and password for the metrics exporter to use.

**Describe alternatives you've considered**
Workaround: Create a user called `root` in the MongoDB.

**Additional context**
I implemented a solution and will open a PR for it.

**Comment by yilmi** [comment]
Hi @tielou,

Sorry for the delay here, I needed to check a few things before getting back to you.

You're right, we don't need these environment variables for the bitnami/mongodb-exporter container because they are created at runtime by k8s (referencing a secret) and are used when the exporter command is executed (to provide authentication credentials). 

Nevertheless the metrics user needs to exist in the MongoDB container if we want the exporter to authenticate successfully, this is why we asked this user (exporter/metrics) to be created.

To give you some background on the MongoDB container users creation, we do create the root user by default. Also a user could specify a `MONGODB_USERNAME`, `MONGODB_PASSWORD` and `MONGODB_DATABASE` if they want a user other than root. There may be an issue by using this `MONGODB_USERNAME` user, as they most likely will not have the necessary permissions for metrics collection (see https://stuff.21zoo.com/posts/prometheus-mongodb-exporter-user-permissions/ as a starting point). I also understand that you don't want to use the root user for metrics collection, which is great as it follows the principle of least privilege by only giving it the necessary permissions.

So the recommendation for the creation of a specific metrics user in the MongoDB container was more to allow for this user to be created when the container starts. You can see how the other environment variables defining users are used, see [Users creation](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/libmongodb.sh#L501) which is where we create the root and regular user.

I'll be providing some feedback on your chart PR (unrelated to this specific discussion) and I will also give you some additional pointers in the PR you have opened against https://github.com/bitnami/bitnami-docker-mongodb.

I'll do my best to get back to you quickly in order to move forward on this!

Thanks,
Yass
