### ISSUE TITLE
[bitnami/common] common.validations.values.postgresql.passwords macro doesn't work

### ISSUE THREAD

**Issue by juan131** [bitnami/charts#7323]
**Which chart**:

Every chart using PostgreSQL as dependency and including this validation macro:

- bitnami/airflow
- bitnami/concourse
- bitnami/discourse
- bitnami/harbor
- bitnami/jupyterhub
- bitnami/keycloak
- bitnami/kong
- bitnami/kubeapps
- bitnami/odoo
- bitnami/redmine**

**Describe the bug**

The validations should complain when the PostgreSQL passwords aren't set during an upgrade but they're not complaining.

**To Reproduce**

1. Install any of the charts mentioned above (e.g. Odoo) with default values, wait for the pods to be ready and obtain the secret data:

```console
$ helm install odoo bitnami/odoo
$ kg pods
NAME                    READY   STATUS    RESTARTS   AGE
odoo-66785679f6-4r589   1/1     Running   0          3m59s
odoo-postgresql-0       1/1     Running   0          3m58s
$ kubectl get secret -o json odoo-postgresql | jq .data
{
  "postgresql-password": "TkRhWENEclBjcw==",
  "postgresql-postgres-password": "cTZ6WDRTUE96Yw=="
}
```

2. Perform an upgrade with default values:

```console
$ helm upgrade odoo bitnami/odoo
...
    'odooPassword' must not be empty, please add '--set odooPassword=$ODOO_PASSWORD' to the command. To get the current value:

        export ODOO_PASSWORD=$(kubectl get secret --namespace "default" odoo -o jsonpath="{.data.odoo-password}" | base64 --decode)
```

3. As we can see, it complains about the Odoo password being missing. Follow the instructions and retry the upgrade:

```console
$ export ODOO_PASSWORD=$(kubectl get secret --namespace "default" odoo -o jsonpath="{.data.odoo-password}" | base64 --decode)
$ helm upgrade odoo bitnami/odoo --set odooPassword=$ODOO_PASSWORD
```

4. This time it doesn't complain (AND IT SHOULD) about PostgreSQL passwords being missing!! As we can see the passwords were changed in the secret:

```console
$ kubectl get secret -o json odoo-postgresql | jq .data
{
  "postgresql-password": "WUZqWXQ2NDIzSQ==",
  "postgresql-postgres-password": "dG1ZdTVuOWxkdA=="
}
```

**Expected behavior**

Validation should block the upgrade process when postgresql passwords aren't provided.

**Comment by dscham** [comment]
Hello, I have an error while upgrading from 6.0.1 to 7.1.5 which seems to me like it correlates to this issue.
![image](https://user-images.githubusercontent.com/17717545/158793478-8d2f54be-91ac-4574-87a3-62120a23f4a8.png)
The secret it complains about does exist. And the postgres password is configured in the values.yaml as well.
Otherwise, the app runs and redeploys fine.

**Comment by javsalgar** [comment]
In the latest major of PostgreSQL we removed the Password validation and relied on the `fetch` function. When all the charts are upgraded to the latest major of the PostgreSQL subchart, this issue should not appear.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
