### ISSUE TITLE
bitnami/mysql sometimes restarts on probe failure, nothing is logged, reason unknown

### ISSUE THREAD

**Issue by zerthimon** [bitnami/charts#7326]
**Which chart**:
bitnami/mysql 8.8.1

**Describe the bug**
mysql pod works most of the time but restarts occasionally on probe failure for unknown reason, so I have no idea how to troubleshoot
```
Events:
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  19m (x1671 over 5d15h)  kubelet  Liveness probe failed:
  Warning  Unhealthy  14m (x1237 over 5d15h)  kubelet  Readiness probe failed:
```

**To Reproduce**
Not sure
```yaml
auth:
  rootPassword: "mysql"
  database: backend
primary:
  extraFlags: --sql_mode=NO_ENGINE_SUBSTITUTION
```

**Expected behavior**
If probe fails I'd like to know the reason to this, log something.

**Version of Helm and Kubernetes**:
```console
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
```console
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"9ec80e7041cfd2c6258649830e5edc2ac6cd1881", GitTreeState:"clean", BuildDate:"2021-03-17T15:48:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

**Additional context**

**Comment by zerthimon** [comment]
The default probe settings are really evil on a resource-limited installations such as minikubes.
Try running the chart in minikube with 2 CPU and 6GB of ram, then do some import of a large SQL dump like this:
`zcat sql.gz | kubectl -n mysql exec -i mysql-mysql-0 -- mysql -uroot -pmysql db` and watch how the pod gets killed during import.
I had to disable the probes entirely on my laptop.

**Comment by carrodher** [comment]
Probes are customizable parameters because it is difficult to set some default values that work fine in all the scenarios and use cases, as described at https://github.com/bitnami/charts/tree/master/bitnami/mysql#mysql-primary-parameters and https://github.com/bitnami/charts/tree/master/bitnami/mysql#mysql-secondary-parameters there are several parameters that allow you to customize the defaults values to make them compatible with your scenario

Name | Description | Value
-- | -- | --
| `primary.livenessProbe.enabled`              | Enable livenessProbe                                                                                            | `true`          |
| `primary.livenessProbe.initialDelaySeconds`  | Initial delay seconds for livenessProbe                                                                         | `5`             |
| `primary.livenessProbe.periodSeconds`        | Period seconds for livenessProbe                                                                                | `10`            |
| `primary.livenessProbe.timeoutSeconds`       | Timeout seconds for livenessProbe                                                                               | `1`             |
| `primary.livenessProbe.failureThreshold`     | Failure threshold for livenessProbe                                                                             | `3`             |
| `primary.livenessProbe.successThreshold`     | Success threshold for livenessProbe                                                                             | `1`             |
| `primary.readinessProbe.enabled`             | Enable readinessProbe                                                                                           | `true`          |
| `primary.readinessProbe.initialDelaySeconds` | Initial delay seconds for readinessProbe                                                                        | `5`             |
| `primary.readinessProbe.periodSeconds`       | Period seconds for readinessProbe                                                                               | `10`            |
| `primary.readinessProbe.timeoutSeconds`      | Timeout seconds for readinessProbe                                                                              | `1`             |
| `primary.readinessProbe.failureThreshold`    | Failure threshold for readinessProbe                                                                            | `3`             |
| `primary.readinessProbe.successThreshold`    | Success threshold for readinessProbe                                                                            | `1`             |
| `primary.startupProbe.enabled`               | Enable startupProbe                                                                                             | `true`          |
| `primary.startupProbe.initialDelaySeconds`   | Initial delay seconds for startupProbe                                                                          | `15`            |
| `primary.startupProbe.periodSeconds`         | Period seconds for startupProbe                                                                                 | `10`            |
| `primary.startupProbe.timeoutSeconds`        | Timeout seconds for startupProbe                                                                                | `1`             |
| `primary.startupProbe.failureThreshold`      | Failure threshold for startupProbe                                                                              | `10`            |
| `primary.startupProbe.successThreshold`      | Success threshold for startupProbe                                                                              | `1`             |
| `primary.customLivenessProbe`                | Override default liveness probe for MySQL primary containers                                                    | `{}`            |
| `primary.customReadinessProbe`               | Override default readiness probe for MySQL primary containers                                                   | `{}`            |
| `primary.customStartupProbe`                 | Override default startup probe for MySQL primary containers                                                     | `{}`            |

Something similar can be applied to the secondary and metrics containers
