### ISSUE TITLE
Support topologySpreadConstraints for MongoDb (and others)

### ISSUE THREAD

**Issue by deveth0** [bitnami/charts#7391]
**Which chart**:
MongoDb (latest)

**Is your feature request related to a problem? Please describe.**

When deploying the MongoDb Chart, it's not guaranteed, that the Pods are spread across multiple Nodes. 

**Describe the solution you'd like**

I'd suggest to add a `topologySpreadConstraints` configuration (see https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) to allow spreading the pods evenly. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by juan131** [comment]
Hi @deveth0 

Thanks for the suggestion! This is sth. we already support in other charts but it's missing in some other such as MongoDB. We have an ongoing task to standardize several features in the catalog that are only present in specific charts, so I'm going to add this topic to the list to ensure my colleagues also tackle this.



---

> When deploying the MongoDb Chart, it's not guaranteed, that the Pods are spread across multiple Nodes.


You can also achieve that using Pod Affinity policies, see:

- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#mongodb-statefulset-parameters
- https://github.com/bitnami/charts/tree/master/bitnami/mongodb#set-pod-affinity

For instance, set `podAntiAffinityPreset` to `hard` to enforce the scheduler to have a single MongoDB pod per node you have in the k8s cluster.

**Comment by deveth0** [comment]
Ahh indeed, thanks for the hint and your great work!

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
