### ISSUE TITLE
[bitnami/kafka] Changing metrics.kafka.service.port parameter does not change the port actually. 

### ISSUE THREAD

**Issue by romankspb** [bitnami/charts#7408]
**Which chart**:
kafka-14.0.5

**Describe the bug**
Changing metrics.kafka.service.port parameter does not change the port actually. Kafka-exporter is still listening on the default port  - 9308.

**To Reproduce**
1. Edit values.yaml to set metrics.kafka.service.port to 8080
2. Run ```helm upgrade -f values.yaml kafka bitnami/kafka```

**Expected behavior**
kafka-exorter must listen 8080 port

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

$ oc version
Client Version: 4.7.0-0.okd-2021-05-22-050008
Server Version: 4.7.0-0.okd-2021-05-22-050008
Kubernetes Version: v1.20.0-1073+df9c8387b2dc23-dirty

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"archive", BuildDate:"2021-03-30T00:00:00Z", GoVersion:"go1.16", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-1073+df9c8387b2dc23-dirty", GitCommit:"df9c8387b2dc2308da01706ff89982c6b7ad9c48", GitTreeState:"dirty", BuildDate:"2021-05-15T22:42:25Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pablogalegoc** [comment]
@romankspb thanks for reporting! I've opened a PR to fix it

**Comment by pablogalegoc** [comment]
Hi again @romankspb, I've closed the PR because there was a misunderstanding on my part on how this is configured. `metrics.kafka.service.port` parameter applies to `kafka-metrics-svc` and configures the port of this service:
https://github.com/bitnami/charts/blob/4986338b63815cdd926a27589204c50aa5e039e1/bitnami/kafka/templates/kafka-metrics-svc.yaml#L34-L37
and then it binds to the metrics port of the kafka-exporter container, which is fixed
https://github.com/bitnami/charts/blob/4986338b63815cdd926a27589204c50aa5e039e1/bitnami/kafka/templates/kafka-metrics-deployment.yaml#L88-L89
If you run `kubectl describe service/kafka-metrics` you should see:
```
Port:              http-metrics  8080/TCP
TargetPort:        metrics/TCP
```

**Comment by romankspb** [comment]
@pablogalegoc Yes, I have not fully understood the configure of this parameter. Thanks for the explanation.

**Comment by romankspb** [comment]
@pablogalegoc Yes, I have not fully understood the configure of this parameter. Thanks for the explanation.
