### ISSUE TITLE
[bitnami/kafka] Confluent platform?

### ISSUE THREAD

**Issue by turowicz** [bitnami/charts#7467]
Some of the new software libraries depend on the [Confluent Platform](https://www.confluent.io/download/), for example: https://github.com/jonathansant/Orleans.Streams.Kafka

Can we perhaps get an image of Kafka with the required SDK installed?

**Comment by carrodher** [comment]
Unfortunately, we are not used to adding any third-party library that is not present in the source code of the application itself (Kafka in this case), being said that all the code (based on bash) is publicly available in the Kafka container repository, see https://github.com/bitnami/bitnami-docker-kafka.

You can customize this code in order to add any feature/library that can be interesting for your use case, in the same way, you can submit a PR and the team will review it, just in case it makes sense to be added to the image by default

**Comment by turowicz** [comment]
Thanks!
