### ISSUE TITLE
[bitnami/wordpress] Specifying updateStrategy 'Recreate' generates invalid manifest

### ISSUE THREAD

**Issue by timbrd** [bitnami/charts#7532]
When specifying updateStrategy `Recreate` in the values.yaml of wordpress chart, I get the following error:

```
[...] Helm upgrade failed: failed to create resource: Deployment.apps "wordpress" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'...
```

It seems to me that the values.yaml is being merged with the default values.yaml, where an empty `rollingUpdate` value is specified:

```
updateStrategy:
  type: RollingUpdate
  rollingUpdate: {}
```

This is an excerpt of my values.yaml:

```
updateStrategy:
  type: Recreate
```

**Comment by alemorcuq** [comment]
Can you try this?

```
updateStrategy:
  type: Recreate
  rollingUpdate: null
```

**Comment by timbrd** [comment]
> Can you try this?
> 
> ```
> updateStrategy:
>   type: Recreate
>   rollingUpdate: null
> ```

Doesn't work either. I think it is checked if the key 'rollingUpdate' exists, no matter what the exact value is.

**Comment by alemorcuq** [comment]
It works for me. The problem here is that, when you upgrade your chart setting the `type` to Recreate, the `rollingUpdate` field it's still present, so you need to delete the `rollingUpdate` key. This is done in Helm by setting the value to `null`: https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

**Comment by timbrd** [comment]
Sorry for the late reply. You are correct, adding `rollingUpdate: null` fixed the issue.
