### ISSUE TITLE
MongoDB 5.x support

### ISSUE THREAD

**Issue by mprahlkamps** [bitnami/charts#7694]
**Which chart**:
mongodb

Are there any plans to support mongodb 5.x?

**Comment by carrodher** [comment]
The [bitnami/mongodb 5.X container](https://github.com/bitnami/bitnami-docker-mongodb/commits/master/5.0/debian-10) was released one month ago; for the Helm chart, we are used to waiting sometime before moving it to the latest version due to several reasons, such as this Helm chart is used as subchart in others Helm charts where it is needed to check the compatibility, a new major version bump is required, we need to check the upgrade path, etc.

Although the chart is not using MongoDB 5.X out of the box, we provide an easy way for modifying the bundled containers in order to use a different tag; in this case, installing the chart with
```console
$ helm install mymongo --set image.tag=TAG bitnami/mongodb
```
where _TAG_ can be any of the ones [listed in DockerHub](https://hub.docker.com/r/bitnami/mongodb/tags?page=1&ordering=last_updated&name=5.), for example
```console
$ helm install mymongo --set image.tag=5.0.3 bitnami/mongodb

$ kubectl get pods
NAME                              READY   STATUS    RESTARTS   AGE
mymongo-mongodb-79794c555-745q5   1/1     Running   0          110s

$ kubectl describe pod mymongo-mongodb-79794c555-745q5
...
Containers:
  mongodb:
    Image:          docker.io/bitnami/mongodb:5.0.3
...
Events:
  Type     Reason                  Age                    From                                         Message
  ----     ------                  ----                   ----                                         -------
  Normal   Pulling                 2m16s                  kubelet, gke-dev-default-pool-ab651c88-hzxw  Pulling image "docker.io/bitnami/mongodb:5.0.3"
  Normal   Pulled                  2m7s                   kubelet, gke-dev-default-pool-ab651c88-hzxw  Successfully pulled image "docker.io/bitnami/mongodb:5.0.3" in 8.948363701s

$ kubectl exec mymongo-mongodb-79794c555-745q5 -- mongo version
MongoDB shell version v5.0.3
connecting to: mongodb://127.0.0.1:27017/version?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("4b3dec4f-a9bc-4453-b8d2-eb6c8351a267") }
MongoDB server version: 5.0.3
```

**Comment by mprahlkamps** [comment]
Thank you very much
