### ISSUE TITLE
[nginx-ingress-controller] - Versions past 7.6.21 not being published to bitnami helm repo

### ISSUE THREAD

**Issue by oasisvali** [bitnami/charts#7751]
**Which chart**:
nginx-ingress-controller

**Describe the bug**
Github Repository lists Chart v8.0.4 as latest release, but bitnami helm repository only provides v7.6.21. ArtifactHub also reflects the older release: https://artifacthub.io/packages/helm/bitnami/nginx-ingress-controller

**To Reproduce**

1. `helm repo add bitnami https://charts.bitnami.com/bitnami`
2. `helm repo update`
3. `helm search repo bitnami/nginx-ingress-controller`

Output:
```
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/nginx-ingress-controller	7.6.21       	0.48.1     	Chart for the nginx Ingress controller
```

**Expected behavior**
Latest release (v8.0.4) of the chart should be listed

**Version of Helm and Kubernetes**: 

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Hi, we are facing some issues while releasing the new version. Apart from the changes in the code itself and the PRs merged in this GH repo, there are performed some internal tests before fully releasing the Helm chart; in this case, there are some issues with the new version and we are trying to fix them.
Although the chart code is merged in the GH repo the release in the Helm repo can be blocked because of the mentioned issues, once solved the new version should appear in the Helm repo.
 
You can find more info about this process in the following links:
- https://docs.bitnami.com/kubernetes/faq/get-started/understand-charts-release-process/
- https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#pr-approval-and-release-process

I am adding the `on-hold` label to prevent the stale bot from closing the issue while we work on a solution.
