### ISSUE TITLE
[redis-cluster]Service ports are not container ports

### ISSUE THREAD

**Issue by antoineozenne** [bitnami/charts#7765]
**Which chart**:
redis-cluster 7.0.0

**Describe the bug**
I think the port in [l.18](https://github.com/bitnami/charts/blob/28d43a871cbae2e1aa2cdcbc35124a2fd06526d6/bitnami/redis-cluster/templates/headless-svc.yaml#L18) should be `.Values.service.ports.redis` instead of `.Values.redis.containerPorts.redis` and the port in [l.21](https://github.com/bitnami/charts/blob/28d43a871cbae2e1aa2cdcbc35124a2fd06526d6/bitnami/redis-cluster/templates/headless-svc.yaml#L21) should be `.Values.service.ports.bus` instead of `.Values.redis.containerPorts.bus`.

**Comment by juan131** [comment]
Hi @antoineozenne 

Apparently yes! The `containerPorts` should only be used to set the port to expose at container level (in the statefulset). Although the "bus" port isn't intended to be exposed outside the k8s cluster and that might have prevented @miguelaeh to use `service.ports` (since it could be interpreted as a port to be open).

I'd like to hear from @miguelaeh about this since he included these latest changes.

**Comment by antoineozenne** [comment]
I understand the situation, so I think the image logic isn't really good: we should use a custom port (variable in the chart template) in the image logic to search the rest of Redis nodes (custom port that is finally `.Values.service.ports.redis`). What do you think about that?

**Comment by miguelaeh** [comment]
Hi @antoineozenne ,
It should be possible to change the image logic to pass `FQDN:port` as the hosts, but, could you explain why do you need to change that? After all, that's an internal port that you won't need to contact.

**Comment by antoineozenne** [comment]
Hi all, no particular use case. It's just a matter of convention, and a little mania. :)
When I see `containerPorts`, I'm only thinking to container ports, not service ports. It's a bit confusing to me.
I think it makes sense to say : The first redis node searches the rest of Redis nodes by connecting to the `Service` object in front of redis nodes, so by connecting to the port of the service (which is equal to the container port in this case, but it is not the same port object).
What worries me here is that `containerPorts` refers to two different objects: the port of the `Service` and the port of the container.

If you fell that this is not a problem, feel free to close this.

**Comment by miguelaeh** [comment]
Hi @antoineozenne ,
Since the headless service is intended to be used by the Redis pods themselves, I consider it is done in the simplest possible functional way.
I will close this ticket since it seems to be correct and it should not produce any issues. Feel free to reopen it in case you find any issue related.
You can also open a PR for that, but have into account that you need to change the redis-cluster containers too.
