### ISSUE TITLE
Revert PR #7720, this broke metrics export with ServiceMonitor

### ISSUE THREAD

**Issue by sgolod** [bitnami/charts#7778]
Please revert this PR. It broke metrics export because you place ServiceMonitor labels (Prometheus instance selector labels) to Service selector section. And now Prometheus server can't discover a ServiceMonitor without this labels.

_Originally posted by @sgolod in https://github.com/bitnami/charts/issues/7720#issuecomment-940923470_

**Comment by sgolod** [comment]
According to the description from the README.md (for example in grafana/ chart):
`metrics.serviceMonitor.selector`      | Prometheus instance selector labels

before this PR, we put this value in the section ServiceMonitor.metadata.labels and Prometheus instance use this label to select the ServiceMonitor. After this patch - value moved to ServiceMonitor.spec.selector.matchlabels, but this serves to select the service from which we are going to collect metrics.

**Comment by mehta-ankit** [comment]
Is there a timeline for this to be done ?
I ask because after upgrade things broke for us (which as mentioned above, we can fix) but there have been more PR's in some charts like this one: https://github.com/bitnami/charts/pull/8448 which have made specific charts use a different value vs what was suggested in this ticket.
For example `metrics.serviceMonitor.additionalLabels` vs `metrics.serviceMonitor. labels`. I feel all charts should be standardized as that was the aim of the original PR.

**Comment by javsalgar** [comment]
Hi,

We are doing efforts in standardizing all the objects is the chart. Could you let us know in which chart you are having the issue?

**Comment by mehta-ankit** [comment]
Hi @javsalgar thanks for asking.
I currently use Kafka and Zookeeper charts and as I mentioned above they both have different ways of adding the labels to the serviceMonitor: 

1. https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/servicemonitor-metrics.yaml#L13
2. https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/servicemonitor.yaml#L13

Problem is worse if I use version 14.x.x for Kafka (which uses 7.x.x for Zookeeper). In that case I have to use `.Values.commonLabels` for Kafka service-monitors which would ad the label to all the other components also.
So all in all in kinda not fun and yes there are ways around it, and in my case I am creating my own service monitors or kafka  and disable the ones coming from the helm chart
```
metrics:
    serviceMonitor:
      enabled: false
    kafka:
       enabled: true
    jmx:
      enabled: true
```

**Comment by javsalgar** [comment]
Hi,

You should expect these charts to become standardized with all these values. It is something that we're working on at the moment.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
