### ISSUE TITLE
[Cassandra] Partial reconfiguration

### ISSUE THREAD

**Issue by zmeggyesi** [bitnami/charts#7801]
This is less of an _issue_ and more of a _question_, but I couldn't find an appropriate community channel.

I'm trying to tweak my Cassandra installation's write performance, first by increasing the MemTable space and possibly some GC-related tweaks. I understand that the Helm chart contains a field to override the default configs (`existingConfiguration`), but this appears to supplant the configuration _entirely_, which unsurprisingly breaks the entire system.

Is there a way where I can specify just a few keys from the default `cassandra.yaml` to override their values, keeping everything else intact?

**Comment by miguelaeh** [comment]
Hi @zmeggyesi ,
In other charts we have a config map that can be extended with custom config, it seems it is not the case for Cassandra, since there is not a default config map.
Something that you could do is to copy the default file from a default deployment and then mount that into the `existingConfiguration` in order to override the full file.

**Comment by zmeggyesi** [comment]
Hi @miguelaeh,

Let me see what I can do, not being _that_ familiar with the systems...  
I'll reference this issue if I do end up making one.
