### ISSUE TITLE
[bitnami/airflow] No dags showing up in airflow UI using dag.configMap and Kubernetes executor 

### ISSUE THREAD

**Issue by junaidnasir-ps** [bitnami/charts#7806]
**Which chart**:
Bitnami/airflow 11.1.1 (Kubernetes executor)

**Describe the bug**
Airflow UI is not showing the dags available through dag.configMap

**To Reproduce**

1. Create a config map with dag
2. deploy chart with dag.configMap and Kubernetes executor
3. open airflow web ui

**Expected behavior**
Dags added via configMap should be available via airflow UI

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

```

**Additional context**
I can see my dag being loaded under the path `/opt/bitnami/airflow/dags/external/` on airflow web pod, but it's not showing up in the UI.
Also updating the configMap doesn't update the dags on the above path.  Could it be because of the changes in https://github.com/bitnami/charts/pull/7716 ?
airflow web logs 
```
airflow 20:14:22.12 INFO  ==> ** Airflow setup finished! **

airflow 20:14:22.15 INFO  ==> ** Starting Airflow **
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-10-13 20:14:26,767] {dagbag.py:496} INFO - Filling up the DagBag from /dev/null
```

**Comment by randradas** [comment]
hello @junaidnasir-ps thank you for the issue. could you run the following command in the scheduler, worker and web pods? dags should be visible in all those pods.

`kubectl exec -it airflow-<scheduler/worker/web> -- ls -l /opt/bitnami/airflow/dags/external/`

**Comment by junaidnasir-ps** [comment]
@randradas 
```bash
# web
I have no name!@trf-airflow-web-64dc686d64-nvf9q:/$ ls -l /opt/bitnami/airflow/dags/external/
total 12
-rw-r--r-- 1 1001 1001  332 Oct 14 10:00 dag.py
# scheduler
I have no name!@trf-airflow-scheduler-84d84cf6c8-d6mvn:/$ ls -l /opt/bitnami/airflow/dags/external/
total 8
-rw-r--r-- 1 1001 1001  471 Oct 14 10:48 dag.py
```
I found a typo in the dag.py imports, probably that's why it wasn't showing in UI without any errors.
However when I updated the configMap, it's not being picked up by airflow. have the behaviour changed? (before I could update the dags by updating the config map after helm deployments)

**Comment by randradas** [comment]
hello @junaidnasir-ps you are right, one problem with the current approach is that dags are not updated if you add new dags to the configmap. The problem mounting the configmap into the "...airflow/dags/external" is that Airflow uses the real path ("..2021_09..25686..") as dag location and then worker and scheduler does not find it since they are different containers and their real path is different because mounting the configmap on them happens at different point in time.

The cron based solution does not look bad and it is simple, just keep copying the dags from the configmap to the airflow directory and that's all.

At this point we strongly encourage to the community to push a PR if you have the time for this, otherwise I will create an internal task for it but unfortunately I cannot provide an ETA, what do you think about it?
