### ISSUE TITLE
[bitnami/redis] Password leaked through logs

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [bitnami/charts#7869]
**Which chart**:
bitnami/redis `15.4.1`

**Describe the bug**
The chart includes a pre-start script on sentinel which prints the password to the logs:

```
my-release-redis-node-2 sentinel  13:19:55.72 INFO  ==> about to run the command: redis-cli -a hunter5 -h my-release-redis.default.svc.cluster.local -p 26379 sentinel get-master-addr-by-name mymaster
my-release-redis-node-2 sentinel Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.
```

**To Reproduce**

1. Install the chart

**Expected behavior**
The logs do not contain the password.

**Additional context**
Other scripts have already been rewritten to use the `REDISCLI_AUTH` environment variable instead of `redis-cli -a`, applying this to the remaining invocations should fix the issue.

**Comment by WarheadsSE** [comment]
:wave: Based on what I am seeing here, and familiarity with the chart, I think this is actually within the underlying `bitnami/redis-sentinel` container.

Looking at `15.4.1` of the chart, [Sentinel was using `6.2.6-debian-10-r0`](https://github.com/bitnami/charts/commit/f8ec0a881fda830279eff5c1f320e69a18ac165d#diff-5063c6dcbc478573073c2f1b280610c29b86379ce92e6dc3ce04b51eeb0c8fd6R779-R782). There have been no changes to any of the scripts [within Sentinel container](https://github.com/bitnami/bitnami-docker-redis-sentinel/commits/master/6.2/debian-10/rootfs/opt) since ~6.2.1. :thinking: It's not in this container. So, it may be in `bitnami/redis`.

:dart: [/opt/bitnami/scripts/libredis.sh#L262, function `redis_configure_replication`](https://github.com/bitnami/bitnami-docker-redis/blob/fb8535d8a27e390b08c3aae76947e891aa895295/6.2/debian-10/rootfs/opt/bitnami/scripts/libredis.sh#L262) ... but I see no `-a` involved :thinking: 

Okay, so. `15.4.1` of the chart, `redis` also was `6.2.6-debian-10-r0`. Looking at the history, [there's no evidence of recent changes](https://github.com/bitnami/bitnami-docker-redis/commits/master/6.2/debian-10/rootfs/opt) to the scripts directory.

**Comment by alemorcuq** [comment]
Thanks for investigating this, @WarheadsSE. I actually think the issue comes from this script in the `bitnami/redis` chart: https://github.com/bitnami/charts/blob/master/bitnami/redis/templates/scripts-configmap.yaml

If you are interested in contributing with a PR, please feel free to do so and we will gladly review it.
