### ISSUE TITLE
[bitnami/rabbitmq-cluster-operator] rabbitmq-cluster-operator-metrics service is unreachable

### ISSUE THREAD

**Issue by yogesh-reddy** [bitnami/charts#7879]
**Which chart**:
bitnami/rabbitmq-cluster-operator

**Describe the bug**
When we enable the rabbitmq cluster operator metrics the service which gets created to expose metrics is unreachable.
This might be due to the --metrics-bind-address in the operator pod being at 9782 port and the service created is bound to port 80

**To Reproduce**
enable the  rabbitmq cluster metrics 
set `rabbitmq-cluster-operator.metrics.enabled` to true.

**Comment by batazor** [comment]
Is there any progress on this task?

I tried adding the templates from the documentation of the rabbitmq documentation page to the chart and everything worked fine.

Maybe we should just move the templates from the official doc?

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
