### ISSUE TITLE
[bitnami/harbor] Separation of user API from administrative API

### ISSUE THREAD

**Issue by jowko** [bitnami/charts#7976]
**Which chart**:
bitnami/harbor

**Is your feature request related to a problem? Please describe.**
My company is planning to use Harbor as it's registry for docker images and Helm Charts.
We have our own internal network and we wanted to put Harbor there to forbid access to it through public network for better security. But we need to expose stored docker images and Helm Charts to our customers from publicly available network.

**Describe the solution you'd like**
Some applications allow to separate public (user) API from private (admin) API. This can be done easily by configuring two ingress resources. Then the user API can be used by public ingress controller and admin API can be used by private ingress controller.
This would require more detailed rules in ingress resources and more configuration options to specify separate hostname, certificates and ingress controller for each ingress resource.

**Describe alternatives you've considered**
Replacing current ingress resources with our custom ones - can be hard to maintain.

**Additional context**
It looks that it may not be an easy task, since harbor docker images follow such pattern: hostname/project/repository/...
So we would need to create more detailed rules in Harbor (for harbor-portal deployment and for core API endpoints).

**Comment by juan131** [comment]
Hi @jowko 

Thanks so much for your detailed feature request!!

To be honest, I find this request quite particular. I mean, your use case is specific to your environment and it can be tackled at different levels: using ingress, using network policies, using authentication/authorization mechanisms in the app, etc.

We try to provide the basic required features in our charts catalog but also providing space for customizations to users so they can adapt our "generic" charts to their use cases. That's why we expose parameters such as `*.sidecars`, `*.initContainers` or `extraDeploy` that allow you to customize the solutions. For instance, using `extraDeploy` you can add any custom k8s object when installing the chart such as a second ingress, see: 

- https://github.com/bitnami/charts/blob/master/bitnami/harbor/values.yaml#L38
