### ISSUE TITLE
joomla chart - apache exporter command should not be hardcoded

### ISSUE THREAD

**Issue by timox** [bitnami/charts#8004]
**Which chart**:
joomla 
version: 10.1.27 and olders

**Describe the bug**

in templates/deployment.yaml
the command for metrics image is hardcoded with :
`command: [ '/bin/apache_exporter', '--scrape_uri', 'http://status.localhost:80/server-status/?auto']`

the port should be the same than `.Values.containerPorts.http` but joomla have to run on a dedicated port, so impossible to use 80.

for example,  change the deployment chart with
`command: [ '/bin/apache_exporter', '--scrape_uri', 'http://status.localhost:{{ .Values.containerPorts.http }}/server-status/?auto'] `

allows the apache-exporter to work.

**To Reproduce**

try to change the metrics port in the values file ? I don't know how to override hardcoded values ?

**Expected behavior**
the metrics image command should be a values parameter or use the  `.Values.containerPorts.http`

**Version of Helm and Kubernetes**:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pablogalegoc** [comment]
Hi @timox!

After a quick look I see that the change you are proposing is already used in other charts, Drupal for example:
https://github.com/bitnami/charts/blob/b9f93282750b45c1a774b1105f65cf68d0a4a106/bitnami/drupal/templates/deployment.yaml#L260
Would you like to open a PR to fix it? If so, here's a quick read on [How to contribute](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#how-to-contribute). Otherwise we'll take care of it, thanks for reporting it!

**Comment by timox** [comment]
ok done here :
https://github.com/bitnami/charts/pull/8013

**Comment by pablogalegoc** [comment]
Thanks!
