### ISSUE TITLE
Kafka externalAccess should create 1 service for multiple kafka pods

### ISSUE THREAD

**Issue by brsolomon-deloitte** [bitnami/charts#8014]
**Which chart**:

kafka

**Describe the bug**

From https://github.com/bitnami/charts/blob/master/bitnami/kafka/README.md#accessing-kafka-brokers-from-outside-the-cluster:

> In order to access Kafka Brokers from outside the cluster, an additional listener and advertised listener must be configured. **Additionally, a specific service per kafka pod will be created.**

"A specific service per kafka pod will be created." This seems to fly in the face of what a Service is supposed to do, which is load balancing to multiple pod replicas, among other things. That's the [purpose of `spec.selector` for `kind: Service`](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service). The service is supposed to _abstract access to multiple pods_, not require me to keep tracking of multiple host:port pairs for multiple services.

Is there a way to effect this with the Kafka Helm chart rather than a 1:1 service-to-pod relationship for `externalAccess`?

It looks like the short is no, since the [service definition](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/svc-external-access.yaml) creates one service for each `i` in replicaCount. So what's the rationale behind this behavior? Is there something stateful about Kafka that requires the 1:1 relationship?

**Comment by javsalgar** [comment]
Hi,

The reason for this is how kafka works. We initially had a service that would load the balance between the instances when accessing from the outside, but the problem was that it would try to get the addresses from all the kafka instances when performing the access. So, the result was that from the outside it was trying to access the private IPs from each of the kafka instances. Therefore, the access from the outside would not work (again, this has to do with how Kafka is implemented). As an alternative, we needed to create an external service per pod so, when building the connection string internally, all of the pods were accessible. 

This behaviour can be seen in other applications, such as Redis Cluster if I'm not mistaken.

**Comment by brsolomon-deloitte** [comment]
@javsalgar thanks for the reply, I figured there was reasoning behind it.

We are also looking at [Strimzi](https://strimzi.io/docs/operators/latest/overview.html#con-overview-components-kafka-bridge-clients_str) which allows use of a single Kafka Bridge, but that is thousands of lines of Java code and a CRD, so I understand it is a totally different thing than in this case :)
