### ISSUE TITLE
[bitnami/mongodb] unable to do mongodump due to access denied

### ISSUE THREAD

**Issue by jamsman94** [bitnami/charts#8127]
Hi, I wonder if there is a way for the user to backup the data from the mongodb. I tried to do a `mongodump` but I got a permission denied error when creating the directory.

**Comment by pablogalegoc** [comment]
Hi @jamsman94!

Could you share the full `mongodump` command you are using to backup the data?

**Comment by jamsman94** [comment]
> Hi @jamsman94!
> 
> Could you share the full `mongodump` command you are using to backup the data?

Hey, I tried mongodump --db=xxxxx --out=yyyy. I tried to dump the data to anywhere but failed. It seems like the default 1001 user does not have create permission anywhere. When I tried to switch to root user, I cannot find the root password in the document

**Comment by pablogalegoc** [comment]
> It seems like the default 1001 user does not have create permission anywhere

Yes, we try to give 1001 only the strictly needed permissions for the app to run. You can try this: https://github.com/bitnami/charts/issues/3026#issuecomment-655393520
Take into account:
- **MONGODB_ROOT_PASSWORD** `kubectl get secret --namespace [namespace-of-the-release] [name-of-the-release] -o jsonpath="{.data.mongodb-root-password}" | base64 --decode`
- You will be dumping to your local machine, that's why "In my case I used kubectl port-forward and a local mongodb client"
