### ISSUE TITLE
How to create a redis cluster using an existing K8s secret?

### ISSUE THREAD

**Issue by MayukhSobo** [bitnami/charts#8131]
**Which chart**:
redis-cluster

**Is your feature request related to a problem? Please describe.**
More documentation on the `values.yaml` file

**Describe the solution you'd like**
A more detailed docs file

**Describe alternatives you've considered**
There shouldn't be any other alternative than better documentation. The following link should have worked but not working as well.
https://github.com/bitnami/charts-docs/blob/d02d04b816b628e9690ed8bb7422029e3419a98e/docs.bitnami.com

**Additional context**
I am having problems while creating a redis cluster with an existing K8s secret that stores redis password

**Comment by marcosbc** [comment]
> I am having problems while creating a redis cluster with an existing K8s secret that stores redis password

Could you describe your issues further?

Note that a very common issue when using an existing secret, is that values in the secret contains an ending newline, due to not generating it properly. For instance, instead of adding values to a secret via `echo`, `echo -n` should be used to avoid the ending newline being added.

**Comment by MayukhSobo** [comment]
Hey...I got it figured but the general issue is that I am not able to get enough docs on different things that I want to do. My objective is to create a Redis cluster with 2 master and 4 slaves and connect with with a LoadBalancer inside the Minikube called metallb. I need the right `values.yaml` file for this. If I give nodes to be 6, it create 3 master and 3 slaves. Also I don't see any way to connect to the metallb LoadBalancer in the docs. It would be great if you can let me know and also add this in your docs.

**Comment by marcosbc** [comment]
Our recommendation is to create the configuration step-by-step, in order to detect possible misconfigurations early.

If you find any specific page in our documentation that you believe is inaccurate or lacks information, feel free to send any contribution to improve it, we'd be glad to help with the review and merge.
