### ISSUE TITLE
Error: template: elasticsearch/templates/ingest-statefulset.yaml:118

### ISSUE THREAD

**Issue by mprusinski** [bitnami/charts#8132]
When I try to run Bitnami ElasticStack with ingest enabled:
```yaml
ingest:
  enabled: true
  replicas: 1
```
I receive the following parse error from Helm:
```
Error: template: elasticsearch/templates/ingest-statefulset.yaml:118:101: executing "elasticsearch/templates/ingest-statefulset.yaml" at <eq .Values.master.autoscaling.enabled>: error calling eq: missing argument for comparison
```

It seems there are some errors at lines 115, 118 and 121 of the following file:
`bitnami/elasticsearch/templates/ingest-statefulset.yaml`

The problem is the part:
```
(eq .Values.master.autoscaling.enabled)
```
The eq operator requires 2 arguments but only have 1. Those errors were introduced in the commit with id: 55a4fcddfaef07d44d04b42942127be585acb540

**Comment by carrodher** [comment]
Thanks for letting us know, I just notified the author and reviewer of the PR (https://github.com/bitnami/charts/pull/7847) where the bug was introduced so they can take a look and provide a solution. In the same way, if you have a solution in mind don't hesitate to create a PR fixing the issue.
Thanks again!

**Comment by pierophp** [comment]
Hi @mprusinski I will try to reproduce the bug and send a PR with a fix

**Comment by pierophp** [comment]
I just saw @Mauraza fixed the issue, thank you. I just saw the problem today
