### ISSUE TITLE
MariaDB container creation failed due to quota limits

### ISSUE THREAD

**Issue by jahanzeb-arshad** [bitnami/charts#8227]
I am trying to deploy the wordpress chart on kubernetes name space which has quota limits defined. I can provide cpu and ram quota limits for the wordpress container and it gets started but the mariadb container fails with following error. Need guidance on how to specify cpu/ram limits for the mariadb container. 

_2m38s       Warning   FailedCreate       statefulset/kbase-mypress-mariadb              create Pod kbase-mypress-mariadb-0 in StatefulSet kbase-mypress-mariadb failed error: pods "kbase-mypress-mariadb-0" is forbidden: failed quota: basic-quota-limits: must specify limits.cpu,limits.memory_

**Comment by marcosbc** [comment]
@jahanzeb-arshad You can find MariaDB parameters here: https://github.com/bitnami/charts/blob/master/bitnami/mariadb/README.md#mariadb-primary-parameters

Since MariaDB is a subchart of WordPress, you must specify them like `--set mariadb.primary.resources.limits`, `--set mariadb.secondary.resources.limits`, etc.

**Comment by jahanzeb-arshad** [comment]
Thanks. That worked.
