### ISSUE TITLE
Witness Server for postgres-ha

### ISSUE THREAD

**Issue by vishrantgupta** [bitnami/charts#8237]
**Which chart**:
postgres-ha

**Is your feature request related to a problem? Please describe.**
https://github.com/bitnami/charts/issues/8062
https://github.com/bitnami/charts/issues/2610

**Describe the solution you'd like**
Right now the postgres-ha charts are not production ready.
The split-brain issue can not be avoided unless there are an odd number of replicas, having a witness service will make the postgres-ha more stable and production ready.

**Describe alternatives you've considered**
- Increasing the replicas to 3, this did not work and the cluster continue to had more than 1 primaries in case of failures.

**Comment by rafariossaa** [comment]
Hi, 
  We already have an internal task to study those cases an find a fix for them.
  We will come back as soon as we have news.

**Comment by vishrantgupta** [comment]
Thanks, @rafariossaa, is fixing the postgres-ha multiple masters issue being actively worked upon given the number of issues multiple people have reported?

**Comment by rafariossaa** [comment]
We are trying to fix the issues you indicated, it seems that them all are related.

**Comment by vishrantgupta** [comment]
Thanks, @rafariossaa if you could share the timeline when we can expect a fix, it will help us estimate and decide upon the backup plan internally.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, not ETA yet, but it should happen soon. I guess this should be checked/fixed during this month.

**Comment by ppilawa** [comment]
Hi, any news ?
i think this is not usable at all at this point.
There should be some info "DO NOT USE IT IN PRODUCTION"

**Comment by rafariossaa** [comment]
Hi, 
Sorry, no news yet.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
