### ISSUE TITLE
How to upgrade bitnami/harbor helm chart 

### ISSUE THREAD

**Issue by mikulass** [bitnami/charts#8252]
Hello, I apologize, if this is wrong place to ask for a help. I’m trying to upgrade Harbor register from 2.3.3 to 2.4.0 via bitnami/harbor helm chart. The helm upgrade process for pods chartmuseum, jobservice, registry hang in the state: Unable to attach or mount volumes: hangs on already allocated pvc.. like on attached image. 
![image](https://user-images.githubusercontent.com/25911396/143626561-8bd8a8ea-f845-43c0-877c-a1d4c97261cc.JPG)
Please can you share, any idea or hint or some link to the resource, where I can learn, how to do right upgrade for harbor (bitnami/harbor) helm chart? What do I need to set in values.yaml that newly created pods during upgrade process will use existing pvc.What is the trick? Thanks in advance.

**Comment by javsalgar** [comment]
Hi,

This is due to an affinity issue. It seems that you are using a multi-node Kubernetes cluster and the pods are being scheduled in a different node than the original one. That causes issues with ReadWriteOnce PVCs. In order to fix this, you will need to tweak the affinity of the pods so they get scheduled in the same node. As an alternative, you could change the update strategy to Recreate, so the original pods get killed. That would cause a bit of downtime but the affinity issue would not occur.

Example affinity value: https://github.com/bitnami/charts/blob/master/bitnami/harbor/values.yaml#L579

Example update strategy: https://github.com/bitnami/charts/blob/master/bitnami/harbor/values.yaml#L720

**Comment by mikulass** [comment]
Hi, great, thanks a lot it works (I've changed update strategy to Recreate). Best regards.
