### ISSUE TITLE
How do I get my existing database and file data into an app created by a bitnami helm chart? Wordpress, Drupal, Mariadb

### ISSUE THREAD

**Issue by blue928** [bitnami/charts#8378]
If I follow the instructions in the readme for each of the charts bitnami/wordpress, bitnami/drupal, or bitnami/mariadb (which the other two depend on) all I have to do is run:

```
helm install my-release bitnami/drupal (for example)
```

And the application is up and running, ready for me to start adding data without me having to think about secrets, PV, PVC, etc, since the chart abstracts all of that away for me.

But how do I seed the database with data from my sql dump file?

Scenario: I have an existing WordPress site (not kubernetes). I want to use the official bitnami/wordpress chart to install my existing WordPress application into my cluster. Specifically, how do I get my existing sql data installed during the deployment process (using Helm install my-release bitnami/wordpress?)

If I were using a pure docker solution, I’d map my local directory with backupdb.sql file into the mariadb docker-entrypoint-initdb.d directory. If I were using Kustomize, I’d do the same with hostPath.

What is the Helm command and how do I configure values.yaml (or use --set) to point to the db file I want to use to initialize the application? I want to see MY website with MY data after I run the command, not the default vanilla one from the README.md instructions.

I have read through all of the parameter documentation for each chart, and it is certainly not clear on how this works. I read bitnami/mariadb specifically, there is a tiny section about initialization using .sh, .sql, or .sql.tar.gz, but there is zero information on how to use or an example. (I don't want to use a bash script, I want my data to seed the db as if I had placed it in the docker-entrypoint-initdb.d folder.)

Can someone please provide a very clear explanation on how this works? Thank you!

**Comment by blue928** [comment]
Reference:
https://stackoverflow.com/questions/66344724/deploying-bitnami-mysql-helm-chart-with-an-existing-persistence-volume-claim

In this SO thread, the user has almost the exact same problem. In the comments Ibana mentioned "Don't use docker-entrypoint-initdb.d, instead use initDbScripts. But she never actually answers the question.

Ibana mentions that she's a chart engineer at Bitnami, but I didn't see her in the contributers list. Ibana if you're watching, can you complete your answer on that SO question? Or if anyone knows how to ping her, please make her aware of the issue / thread. I feel like these are related and an answer to that would be a step closer here.

**Comment by blue928** [comment]
@OmriHarary I came across your issue post #1928 (https://github.com/bitnami/charts/issues/1928). That was posted in Feb 2020. In the above SO reference, the OP's question was posted much later - 9 months ago. Her comment seems to imply that getting data into the docker-entrypoint-initdb.d directory is no longer an option and one should only use initdbScript parameter. 

But no matter what I set, I cannot get it to work. I wonder if I'm having so much trouble because of lingering or similar issues to the problems you were experiencing?

Since you are familiar with the parameters, can you please provide examples for correctly using initdbScripts and initdbScriptsConfigMap when referencing an existing backup.sql file? Either I'm not using it correctly, or there is still something wonky going on.

**Comment by OmriHarary** [comment]
Hi @blue928. Sure, happy to help out. It's been a while since I worked with these charts but I just refreshed myself on them, so this should be correct but excuse me if I'm slightly off. Here are your options, I will give as many as I can think of, which one is right for you will depend on your preference and deployment process.

## `initdbScripts` options

As stated in the readme, `initdbScripts` is a yaml dictionary of scripts. Specifically this means that the dictionary keys are the script file names, and the values are the file contents. These are the ways you can set it:

1. Edit `values.yaml`. Add the `initdbScripts` map to the values file of the wordpress chart. Again the key is the file name (arbitrary, but I'll use backup.sql as an example) and the value is your file contents as a multiline yaml string). With the edit, it will look something like this

    ```yaml
    # other values
    mariadb:
      # other values
      initdbScripts:
        backup.sql: |
          <your sql here>
          <make sure it's all indented right>
    # other values
    ```
    I'll say that this is probably the option I recommend the least. It's my philosophy to never edit values.yaml, and if you have a lot of data this is going to create a very messy file.

2. Supply an override values file with `-f` or `--values`. In this case, you would create a new yaml file containing the same as the example above. This works, but seems a bit unnecessary, as you might agree.
3. Supply a value using `--set`. I'm not even going to go into too much detail with this one, it would require you to pass the contents of the file as a string on the command line.
4. Using `--set-file`. **This is the option I think might suit you the best.** This is the same as using `--set` but instead of passing the value on the command line, you give the name of a file containing the value. ie `--set-file mariadb.initdbScripts."backup\.sql"=backup.sql`. This assumes that `backup.sql` is in the directory where you are running the command, adjust path if necessary. (Also I'm not sure if the double quotes are required there, I seem to recall them being important when I did something similar before, but it was a long time ago at this point.)

## `initdbScriptsConfigMap` options

`initdbScriptsConfigMap` is for passing the name of an *existing* configmap that contains your script file(s). In this case how to set the value itself is less interesting (essentially the same options as above, which are the standard helm ways of doing it anyways, just change the parameter key to `initdbScriptsConfigMap` and the value to the name of your configmap.)

Going with this option, you just need to create your configmap first. Easiest way to do that is `kubectl create configmap init-script --from-file=backup.sql`. With that example, you're going to want to set the value of `initdbScriptsConfigMap` to `'init-script'` in whichever manner you prefer.

## Wrap up

Might be a bit more than you asked for, but I figured I'd be exhaustive just in case you need it, or someone else who does comes across this. Again bear in mind that I did this all off the top of my head after a brief refresh on the charts and I haven't tested it, so while I'm pretty sure it's all right I might have gotten something wrong. `--debug --dry-run` is your friend if anything doesn't seem to be setting right.

**Comment by juan131** [comment]
Thanks so much for providing such detailed instructions @OmriHarary, we really appreciate it!!

@blue928 as @OmriHarary mentioned you have some alternatives:

- Use custom init scripts (mounted with one of the available options).
- Use the own's app backup/restore mechanisms (e.g. in WordPress, use JetPack plugin based on VaultPress, seehttps://docs.bitnami.com/installer/apps/wordpress/administration/backup-restore-jetpack).
- Install the chart enabling the "diagnostic" mode (see https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L45) and manually perform the backup restore.

**Comment by blue928** [comment]
Thank you so much for the detailed answers! I feel like I'm getting a lot closer. Here are some issues I'm experiencing, which look like they are related to the same root cause. Since I'm trying to import a database, well, that's going to be a lot larger than 3 MB

kubectl create configmap init-script --from-file=db.sql
error: failed to create configmap: Request entity too large: limit is 3145728

Using the helm command, here is the error

helm install -f values.yaml stihl7 bitnami/drupal --set-file mariadb.initdbScripts."backup\.sql"=backup.sql  
Error: INSTALLATION FAILED: create: failed to create: Request entity too large: limit is 3145728

I think I'm still confused about what's happening. If you look around line 255 in the mariadb chart you'll see the following
https://github.com/bitnami/charts/blob/5452f42a5b231026fc6f1f4693325e2efa05eb05/bitnami/mariadb/templates/primary/statefulset.yaml#L254

 - name: custom-init-scripts
    mountPath: /docker-entrypoint-initdb.d
    
Because I've been so accustomed to mounting a directory directly into that, or COPY a file into that from local, my error is that I was trying to use initdbScripts as some type of local mount reference to get the SQL file in there so mariadb can do its thing, which is automatically import anything into the active database that ends in .sql

I'm learning, I think, that what kubectl / helm is trying to do is take that raw data and import it into the chart as a permanent data value, which is millions of additional lines of code, in my case.

Maybe I'm learning that this isn't possible through the helm / kubectl command? What about an initContainer? I was [reading this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container) and it seemed promising, maybe I can go that route, but I'm worried that will fire every single time a pod / node / cluster comes back up and repopulates the database with the initial date. Not sure if that fear is founded.

This is so easy with a Dockerfile and building the images by copying that sql file into that initdb directory. I'm wondering why this is so hard with Helm / bitnami / charts? If the above is true, I'm more lost than ever on how to get my existing data into my mariadb database, even after it comes up.

**Comment by OmriHarary** [comment]
Right so in this case the problem that you're hitting is that there is a maximum size for Kubernetes objects of 3MB. All the options I gave you are essentially doing the same thing: Creating a configmap with the file and mounting it to the container so that the startup can run the script.

What this means is that neither `initdbScripts` nor `initdbScriptsConfigMap` are usable options for you. It's great for, say, creating some empty databases and tables, for example. But not for a large-scale data import.

Your next steps should be following the suggestions from @juan131 above.

**Comment by johnmba** [comment]
Thank you so much for the detailed instructions, and explanation, this is the solution I have been searching for
