### ISSUE TITLE
[mongodb] Add skipInitialization flag to ease in migrating to K8s

### ISSUE THREAD

**Issue by mckennajones** [bitnami/charts#8483]
**Which chart**:
mongodb `10.30.8`

**Is your feature request related to a problem? Please describe.**
If migrating from a Non-Kubernetes based ReplicaSet to K8s, a valid approach is to create a new ReplicaSet in K8s, and then add the K8s members to the existing non-K8s ReplicaSet (for example VM based). However, it is essential that the K8s ReplicaSet has not been initialized, otherwise Mongo will prevent you from adding the K8s members because of a replica set ID mismatch. 

**Describe the solution you'd like**
The now deprecated helm chart in the https://github.com/helm repo, has the flag mentioned in the title: `skipInitialization`.  

Here is the documentation of the use of the flag: https://github.com/helm/charts/tree/7e45e678e39b88590fe877f159516f85f3fd3f38/stable/mongodb-replicaset#migrate-existing-replicasets-into-kubernetes

**Describe alternatives you've considered**
I briefly tried to determine if there was a way to modify the Bitnami chart to not initialize the ReplicaSet, but did not have any success. 

If there are any suggestions on how to successfully use the Bitnami chart to migrate from a ReplicaSet outside of Kubernetes please let me know!

**Comment by juan131** [comment]
Hi @mckennajones 

Have you tried to deploy the chart enabling the "diagnostic" mode? This mode simply deploy the MongoDB pods but overriding the default command so it doesn't initialize MongoDB, see:

- https://github.com/bitnami/charts/blob/master/bitnami/mongodb/values.yaml#L72

**Comment by mckennajones** [comment]
@juan131 I did not notice that option in the Values file, thanks for mentioning it. 

It looks closer to what I am hoping to accomplish. However, I'm not sure what command I would specify.  The default command is `/scripts/setup.sh`. There appears to be quite a bit of setup logic that I would miss out on by skipping over this code path. 

Enabling diagnostic mode would also disable the liveness probes which is not intended for my use case. 

I see now that there are also `command` and `args` options (outside of the diagnostic mode). Any ideas on a command I could specify to the bitnami/mongo image to accomplish this?

**Comment by juan131** [comment]
Hi @mckennajones 

Please note my suggestion is just a workaround since the use case you mentioned isn't supported by the chart.

My suggestion would be doing sth like this:

- Install the chart with diagnostic mode (the containers will do nothing) and setting `replicaSetConfigurationSettings.configuration` and `configuration` parameters adding your custom configuration.
- Manually exec into each containers and initialize them as you want to join your existing replicaset.
- Once your new MongoDB nodes are running, you can perform a `helm upgrade` disabling diagnostic mode. The containers should detect there's persistent data and skip the initialization. 

Pleas note this isn't a simple process and it'll require you to get familiar with the Bitnami MongoDB container and MongoDB.
