### ISSUE TITLE
Adding Honeycomb Refinery Chart

### ISSUE THREAD

**Issue by bdarfler** [bitnami/charts#8490]
Per the [CONTRIBUTING.md documentation](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository), Honeycomb would like to request evaluating the feasibility of adding [Honeycomb’s Refinery](https://github.com/honeycombio/refinery) to the Bitnami catalog.

Refinery is Honeycomb’s trace-aware sampling proxy. Honeycomb customers direct their distributed trace data to a Refinery host or cluster. Refinery co-locates all data from a single trace and allows for intelligent sampling decisions to be made based on the entire trace. Further documentation can be found [here](https://docs.honeycomb.io/manage-data-volume/refinery/).

Refinery is provided under an Apache 2 license and is distributed via a [docker container](https://hub.docker.com/r/honeycombio/refinery) and a [helm chart](https://github.com/honeycombio/helm-charts/tree/main/charts/refinery).

Related: #8491

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container images are not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR (**once analyzed the request and agreed to be included**). If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by bdarfler** [comment]
👋🏻  I recognize that "Due to limited resources this step could take some time" but I wanted to see if there is any update as the ticket has been open for a month now.

We are talking with VMware about inclusion in the Tanzu Application Catalog and getting these charts included in Bitnami is a required step on that path.

**Comment by carrodher** [comment]
Unfortunately, there are no updates at this moment, this and other requests are being analyzed

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your suggestion!
