### ISSUE TITLE
Adding Honeycomb Kubernetes Agent Chart

### ISSUE THREAD

**Issue by bdarfler** [bitnami/charts#8491]
Per the [CONTRIBUTING.md documentation](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository), Honeycomb would like to request evaluating the feasibility of adding [Honeycomb’s Kubernetes Agent](https://github.com/honeycombio/honeycomb-kubernetes-agent) to the Bitnami catalog.

Honeycomb’s Kubernetes Agent collects resource metrics and application and cluster logs and forwards them onto Honeycomb. Honeycomb customers can run the Honeycomb Kubernetes Agent to get improved observability into their Kubernetes infrastructure. Further documentation can be found [here](https://docs.honeycomb.io/getting-data-in/integrations/kubernetes/).

Honeycomb’s Kubernetes Agent is provided under an Apache 2 license and is distributed via a [docker container](https://hub.docker.com/r/honeycombio/honeycomb-kubernetes-agent) and a [helm chart](https://github.com/honeycombio/helm-charts/tree/main/charts/honeycomb).

Related: #8490

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container images are not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR (**once analyzed the request and agreed to be included**). If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by bdarfler** [comment]
👋🏻  I recognize that "Due to limited resources this step could take some time" but I wanted to see if there is any update as the ticket has been open for a month now.

We are talking with VMware about inclusion in the Tanzu Application Catalog and getting these charts included in Bitnami is a required step on that path.

**Comment by carrodher** [comment]
Unfortunately, there are no updates at this moment, this and other requests are being analyzed

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your contribution and suggestion!

**Comment by carrodher** [comment]
Hi, unfortunately after an internal review, and due to other priorities we have, this solution was not considered to be added to the catalog in the short/mid term.

We apologize for the inconvenience. We will reconsider it in the future.

Thanks for your contribution and suggestion!
