### ISSUE TITLE
[bitbnami/mysql] questions regarding secondary -> primary upgrade

### ISSUE THREAD

**Issue by wgerlach** [bitnami/charts#8503]
Hi,

sorry if this is the wrong place to ask... I installed the bitnami mysql helm chart and have one primary and two secondary mysql instances. If the node on which the primary goes down, how can I upgrade one of the secondaries to become the new primary ? Is there existing documentation or examples ?

thanks

**Comment by javsalgar** [comment]
Hi,

Right now, the bitnami/mysql and bitnami/mariadb charts don't have any configuration set for master re-election when one node goes down. In order to achieve this, we have the mariadb-galera chart which does have master re-election features. 

If you use the bitnami/mysql chart, you may have to perform manual operations to change the master, though I don't know the consequences that it would have https://dev.mysql.com/doc/refman/5.7/en/replication-solutions-switch.html

I would first try to fix the master node instead of trying the master switch. If that's something you require, then I would try mariadb-galera.

**Comment by pankaj-83incs** [comment]
How can we do the multi-master architecture with this chart ??

**Comment by wgerlach** [comment]
@javsalgar Thanks, I probably will try out mariadb-galera !
