### ISSUE TITLE
https://charts.bitnami.com/bitnami access denied

### ISSUE THREAD

**Issue by Filter94** [bitnami/charts#8519]
**Which chart**:
Any

**Describe the bug**
Bitnami charts repo is unavailable for more than 12 hours now

**To Reproduce**
1. `helm repo add bitnami https://charts.bitnami.com/bitnami`
Result: `Error: context deadline exceeded`
OR 
In the browser go to https://charts.bitnami.com/bitnami
Result:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>4E9G5SK2AK7GRM0B</RequestId>
<HostId>0lZJRoF4P+W2lP9fUPjtieQS6PFgGeeLw2eSCTRI1KE8y9HF6CQ+X9M4MhzJxld2Q6RSGwiK+MY=</HostId>
</Error>
```

**Expected behavior**
I expect repo to be added to helm or a different response from the server which indicates successful connection to Bitnami repo

**Version of Helm and Kubernetes**:
Helm version: 3.7.1
Kubernetes client version: 1.22
- Output of `helm version`:
```
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by carrodher** [comment]
Thanks for letting us know, we are facing some transient issues with the Helm registry, it should work if you retry it:
```console
$ helm repo add bitnami2 https://charts.bitnami.com/bitnami
"bitnami2" has been added to your repositories
```

About the browser, please note this URL is designed for the Helm CLI, the only path accessible via browser is https://charts.bitnami.com/bitnami/index.yaml where you can download the _index.yaml_

Please note this issue was already reported at #8433, I am closing this one in order to keep all the conversations in a single place. Thanks!
