### ISSUE TITLE
The administrator password cannot be logged in during use

### ISSUE THREAD

**Issue by zhaobei** [bitnami/charts#8648]
![image](https://user-images.githubusercontent.com/55879962/149259708-b00b3412-9779-4a11-925a-676742a82db4.png)

**Comment by zhaobei** [comment]
I do this according to the standard course, and I look forward to someone to answer my questions

**Comment by carrodher** [comment]
Hi, when creating a new issue a template is shown asking for some information that helps us to understand the issue and reproduce it. Can you please edit the first comment by filling the template?



**Which chart**:



**Describe the bug**



**To Reproduce**

Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**



**Additional context**
