### ISSUE TITLE
Failed to install postgres

### ISSUE THREAD

**Issue by amjedsaleel** [bitnami/charts#8753]
**Which chart**:
postgresql
**Describe the bug**

I am deploying Postgres on the Linode Kubernetes cluster. But failed to run postgres.
![image](https://user-images.githubusercontent.com/56245938/150733970-afe70b4e-dcfc-420e-a2e5-d00fac1dcd16.png)

**Comment by juan131** [comment]
Hi @amjedsaleel 

Could you please share the following information?

- The `values.yaml` or equivalent parameters that you set to install the chart.
- The Bitnami PostgreSQL chart version you're using.

I'd also recommend you to take `volumePermissions` parameters (see [values.yaml#L101](https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml#L101)) that can help you to solve permissions issues on certain K8s environments.

**Comment by amjedsaleel** [comment]
values.yaml
![image](https://user-images.githubusercontent.com/56245938/150742116-bfb0304e-3610-4658-bcde-607f3f80f959.png)
Bitnami PostgreSQL chart version: 10.16.1

**Comment by migruiz4** [comment]
Hi @amjedsaleel,

The Postgresql helm chart is failing to create the data folder inside the volume mounted at `/bitnami/postgresql`.

I would recommend you to have a look at the configuration of your Kubernetes storage class, as this issue is frequent especially when using storage systems like NFS where the container may not have writing permission.

**Comment by carolili** [comment]
Hi, had the same problem and managed to solve it by changing the mountpoint to `/bitnami` following this comment: https://github.com/bitnami/charts/issues/1210#issuecomment-678759936

However, when changing anything in the chart that causes the Postgresql pod to restart, all data on the mountpoint is lost. I'm not sure why the data is deleted or by what, e.g. the chart or an initcontainer or something else. The DB starts up empty.

I'm using the Postgresql chart together with the [Bitnami Keycloak chart](https://github.com/bitnami/charts/tree/master/bitnami/keycloak) in case it matters. Thanks in advance for any hints.

**Comment by migruiz4** [comment]
Hi @carolili,

Could you please share more details about your issue? Pod logs, configuration being used (values.yaml) or any significant detail about your environment would be helpful.

We test the PostgreSQL chart, but we haven't seen this issue so anything that may help us reproduce or troubleshoot the problem is appreciated.

**Comment by carolili** [comment]
Thanks for the quick response. There doesn't seem to be anything specific in the Postgresql logs. Perhaps I should open a separate issue as this one is more related to not being able to install Postgresql?

Here are the logs after the Postgresql restart when Keycloak tries to access tables that don't exist anymore -- I don't see any errors in the omitted lines and no mentions of something that could empty the `data` directory:
```
...
fixing permissions on existing directory /bitnami/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
...
2022-02-01 13:32:49.573 GMT [1] LOG:  database system is ready to accept connections
2022-02-01 13:34:38.756 GMT [175] ERROR:  relation "public.client_scope" does not exist at character 205
```
Below is the Postgresql configuration in the Keycloak `values.yaml`. I don't use `volumePermissions` since I don't seem to need to change permissions if I use the mountpoint `/bitnami` as by the comment https://github.com/bitnami/charts/issues/1210#issuecomment-678759936 that I mentioned previously:
```
...
    postgresql:
      image:
        debug: true
        repository: bitnami/postgresql
        #tag: 11.14.0-debian-10-r28
      volumePermissions:
        enabled: false
      postgresqlUsername: my-username
      postgresqlDatabase: my-keycloak-db
      existingSecret: my-postgresql-secret
      networkPolicy:
        enabled: true
      extraEnvVars:
        - name: BITNAMI_DEBUG
          value: true
      persistence:
        mountPath: /bitnami
        enabled: true
        size: 8Gi
        accessModes:
          - ReadWriteOnce
      resources:
        requests:
          memory: 512Mi
          cpu: 500m
        limits:
          memory: 512Mi
          cpu: 500m
```

The attached storage is an NFS mount (NetApp `csi.trident.netapp.io`) in case that helps.

You could try to reproduce it by:
1. Deploying Keycloak with the default configuration and the above Postgresql configuration.
2. Adding some configuration to Keycloak (e.g. a new realm or configure the admin user)
3. Upgrading or downgrading the Keycloak helm chart version or change the ingress annotations in the Keycloak Helm chart (both of that caused Postgresql to restart)
4. Check the database (e.g. open Keycloak and see if the admin user is still intact or log in to the Postgresql instance if there is any data)

I know it's a bit unclear whether it's something in the Keycloak chart, Postgresql chart, or something else that causes this. If you spot anything obvious that could be wrong, please let me know & thanks in advance :)

**Comment by migruiz4** [comment]
Hi @carolili,

I would appreciate it if you could create a separate issue since the behavior you describe is different from the original topic discussed here.

In addition, I would like to suggest you not overwrite the mountPath and let it with its default value. Instead, I think the issue may be caused by the NFS storage.

Keep in mind that, depending on the NFS version and its configuration, it may vary how the permissions are handled, and it is possible that the Pod created after the upgrade does not have permission over the files and folders created by the original pod because of how NFS user mapping works.

That is why I previously mentioned it is a frequent issue when using NFS storage systems.

If your Kubernetes cluster allows running root containers, I would recommend trying to the use `volumePermissions` container in case it fixes your issue. Otherwise, I would recommend checking your NFS configuration.

**Comment by carolili** [comment]
Thank you very much for the advice @migruiz4. I will try your recommendations and checking the NFS configuration and then create a separate issue if there is no solution in the NFS configuration.
