### ISSUE TITLE
Exposing MongoDB Via NodePort Not Working when replicaSet is added to connection URL

### ISSUE THREAD

**Issue by krebznet** [bitnami/charts#8868]
Hello, 
I know this is not a bug but something I've been breaking my brain on for 2 days, I have a 6 node mongo db cluster setup in Kubernetes using this helm chart configured with replica sets, followed the docs to expose my cluster through node ports, when I connect with just a single server in the URL and not replicaSet param it works but the minute I addd /?replicaSet=rs0 I get a connection timeout as my java client is trying to connect to another node via its internal hostname 

**{java.net.UnknownHostException: mongodb-4.mongodb-headless.mongo.svc.cluster.local}},**

Without adding the replicaSet param I am still able to insert documents using a connection string with just the first db server:nodeport but it takes about 6 seconds to bulkWrite 1,000 documents with write concern on 0 and its super frustrating that I can't figure this out. I wrapped MongoDB in a helm chart a wrote to also install mongo db express these are the config params I have when it comes to this area of concern. 

`mongodb:
  architecture: "replicaset"
  auth:
    enabled: true
    rootPassword: "password"
  replicaCount: 6
  persistence: 
    enabled: true
    storageClass: "local-storage"
  fullnameOverride: "mongodb"
  externalAccess:
    enabled: true
    service:
      type: NodePort
      nodePorts: [32700,32701,32702,32703,32704,32705]
      domain: testrock1.xxx.net'
  `

I've followed tutorials and I seem to have everything added that is mentioned but clearly missing something here. Can anyone help me out? Can anyone out there offer some hourly consulting to help me get this correct? I've looked on upwork.com and can't find anyone that knows this chart better than I do.  Based on the config above does anyone see anything wrong?

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. We are aware of issues with external access and nodePort. We have a task for this but we cannot guarantee an ETA. As soon as there are more news, we'll let you know.

**Comment by carrodher** [comment]
Unfortunately, this issue was created a long time ago and although there is an internal task to fix it, it was not prioritized as something to address in the short/mid term. It's not a technical reason but something related to the capacity since we're a small team.

Being said that, contributions via PRs are more than welcome in both repositories (containers and charts). Just in case you would like to contribute.

During this time, there are several releases of this asset and it's possible the issue has gone as part of other changes. If that's not the case and you are still experiencing this issue, please feel free to reopen it and we will re-evaluate it.
