### ISSUE TITLE
nats to support JetStream

### ISSUE THREAD

**Issue by skyrain** [bitnami/charts#9080]
### Name and Version

charts/bitnami/nats/

### What is the problem this feature will solve?

Nats currently supports streaming server: Jetstream. We are looking forward to use streaming capability to help persist message.

### What is the feature you are proposing to solve the problem?

Support configure Jetstream which nats supports now.
https://docs.nats.io/using-nats/developer/develop_jetstream

**Comment by juan131** [comment]
Hi @skyrain 

Thanks so much for this feature request!

At this point, we don't have much bandwidth to work on adding support for more complex setups for NATS. That's why we'd really appreciate some help here: it'd be a pleasure for us helping in the review process if someone drops a PR adding support for this.
