### ISSUE TITLE
How to set WP_MEMORY_LIMIT for wordpress

### ISSUE THREAD

**Issue by thanhtoan1196** [bitnami/charts#9082]
### Name and Version

bitnami/wordpress 13.0.11

### What steps will reproduce the bug?

1. In values.yaml, set `wordpressExtraConfigContent` = `define('WP_MEMORY_LIMIT', '512M')`
2. Run helm upgrade.
3. I see memory limit is not set, it's still 40MB (default)

### What do you see instead?

Memory limit (wordpress, not php) is not changed, how to change it?

**Comment by miguelaeh** [comment]
Hi @thanhtoan1196 ,
the configuration file is created the first time you run helm install. After that, since the existing configuration is loaded so just changing that parameter in the values and performing an upgrade is taking the old configuration. Check the code [here](https://github.com/bitnami/bitnami-docker-wordpress/blob/0518030e9946997a59d301bfa12f47513f8a91a2/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L202).
In order to change that parameter once Wordpress is already running you need to edit the persisted file manually.

**Comment by thanhtoan1196** [comment]
@miguelaeh thank you.
