### ISSUE TITLE
[bitnami/kong] Kong 5.0.7 not available in Bitnami Helm Repo

### ISSUE THREAD

**Issue by mschmidt291** [bitnami/charts#9174]
### Name and Version

bitnami/kong

### What steps will reproduce the bug?

So yesterday the bitnami/kong 5.0.7 helm chart was released and merged into master. This version fixes the CRD depreciation in 1.22 kubernetes and above - but although it is merged into master, and has a bumped chart version, only 5.0.6 is available in the repository.
I already looked at the index.yaml of the repository myself and 5.0.7 is missing.
Does it take some more time for the repository to index the new chart version?

### What do you see instead?

5.0.6 is the latest one although 5.0.7 is already released

**Comment by carrodher** [comment]
Thanks for letting us know, as pointed out in the [CONTRIBUTING guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#pr-approval-and-release-process):
> NOTE: Please note that, in terms of time, maybe a slight difference between the appearance of the code in GitHub and the chart in the registry.

We are testing internally all the charts in different k8s clusters (IKS, GKE, TKG, AKS, etc) before pushing them to the Helm registry. Currently, we are having some issues with our infrastructure and one of those clusters is not stable so releases are blocked because of this issue. Once solved the issue, the new version of the Helm chart should be released automatically.

In the meantime as a workaround, you could try to install it from this GH repo by cloning it and deploying the Helm chart by using the local path to the chart instead of fetching it from the registry.

**Comment by mschmidt291** [comment]
> Thanks for letting us know, as pointed out in the [CONTRIBUTING guidelines](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#pr-approval-and-release-process):
> 
> > NOTE: Please note that, in terms of time, maybe a slight difference between the appearance of the code in GitHub and the chart in the registry.
> 
> We are testing internally all the charts in different k8s clusters (IKS, GKE, TKG, AKS, etc) before pushing them to the Helm registry. Currently, we are having some issues with our infrastructure and one of those clusters is not stable so releases are blocked because of this issue. Once solved the issue, the new version of the Helm chart should be released automatically.
> 
> In the meantime as a workaround, you could try to install it from this GH repo by cloning it and deploying the Helm chart by using the local path to the chart instead of fetching it from the registry.

Thanks for the quick response! I already did what you recommended as a workaround, so we can use the filepath instead of a repo. I just opened this issue because I thought there is maybe something wrong with a release pipeline or something like this. Did not know that the charts are tested "manually". 
Then we have to wait a little bit longer :+1:

**Comment by carrodher** [comment]
No no, they are not tested manually, this test & release pipeline is fully automated, the topic is that there are some issues in the underlying infrastructure. If you're curious, [here](https://docs.bitnami.com/kubernetes/faq/get-started/understand-charts-release-process/) you can find more info about this process.
