### ISSUE TITLE
Elasticsearch exporter does not connect to master node

### ISSUE THREAD

**Issue by jaudiger** [bitnami/charts#9182]
### Name and Version

bitnami/elasticsearch 17.9.3

### What steps will reproduce the bug?

1. Add a master node
2. Add a data node
3. Enable exporter

No coordinating node has to be added to reproduce this issue. If a coordinating node is added, there is not problem with the exporter. See, below why.

### What is the expected behavior?

The exporter should connect to the elasticsearch cluster in regardless of the nodes configuration.

### What do you see instead?

When no coordinating node is present (only master and data nodes), the exporter is not able to get the cluster health.

```log
level=warn ts=2022-02-23T15:34:09.05606013Z caller=nodes.go:1871 msg="failed to fetch and decode node stats" err="failed to get cluster health from http://alaska-elasticsearch-master:9300/_nodes/stats: Get \"http://alaska-elasticsearch-master:9300/_nodes/stats\": net/http: HTTP/1.x transport connection broken: malformed HTTP status code \"is\"" 
```

### Additional information

The problem comes from using the default port 9300 to try to get the cluster health. But this port should only be used internally by elasticsearch between its nodes. And should not be used to target the cluster from outside. For this purpose, the port 9200 has to be used.

Here we can see in the chart the usage of `.Values.master.service.port` at the line 49: https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/metrics-deploy.yaml#L49

The default value of `master.service.port` is 9300.

When at least one coordinating node is added, the line evaluated is: https://github.com/bitnami/charts/blob/master/bitnami/elasticsearch/templates/metrics-deploy.yaml#L46. Here, the default value for `.Values.coordinating.service.port` is 9200 which is correct.

**Comment by jaudiger** [comment]
If you want any help, I'm here. I just want to be sure first of the approach to take to solve this issue.

**Comment by migruiz4** [comment]
Hi @jaudiger!

Thank you for reporting this issue! 

Indeed, this is a bug with the metrics deployment here:
https://github.com/bitnami/charts/blob/6c698dfcf39233b54139661458f0813a8df60e6a/bitnami/elasticsearch/templates/metrics-deploy.yaml#L44-L50

It should be using 9200 instead of `{{ .Values.master.service.port }} `, since the `master.service.port` references the transport port (9300) and not the rest API port (9200) which is hardcoded:
https://github.com/bitnami/charts/blob/6c698dfcf39233b54139661458f0813a8df60e6a/bitnami/elasticsearch/templates/master-svc.yaml#L15-L17

Since it was your catch, would you like to contribute by sending a PR? Otherwise, let me know and I will create the PR.

**Comment by jaudiger** [comment]
Thanks @migruiz4 , I just opened this PR (https://github.com/bitnami/charts/pull/9199) to fix this issue.
