### ISSUE TITLE
Does rabbitmq or rabbitmq-cluster-operator support rabbitmq stream

### ISSUE THREAD

**Issue by skyrain** [bitnami/charts#9219]
### Name and Version

bitnami/rabbitmq

### What is the problem this feature will solve?

Currently, rabbitmq support rabbitmq streams as https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview. I would love to know does either `bitnami/rabbitmq` or `bitnami/rabbitmq-cluster-operator` support rabbitmq streams? I do see the appversion in `bitnami/rabbitmq` is `3.9.13` which should support rabbitmq streams, but cannot find where to enable to rabbitmq stream option.

### What is the feature you are proposing to solve the problem?

support rabbitmq streams https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview

### What alternatives have you considered?

kafka, nats

**Comment by javsalgar** [comment]
Hi,

If the application includes it, then you should be able to use it in the Bitnami containers. About `bitnami/rabbitmq`, it is not clear to me looking at the documentation if there's any setting to enable or if it is something to be created using the CLI.

About `rabbitmq-cluster-operator`, I advise you to ask to the `rabbitmq-cluster-operator` devs to see if the operator supports it. https://github.com/rabbitmq/cluster-operator

**Comment by javsalgar** [comment]
Hi,

Sorry for not explaining myself correctly. What Bitnami essentially does is packaging open source apps and automating certain parts of the configuration. In this case, in order to enable streaming in RabbitMQ, we first need to know how to enable in RabbitMQ itself. Do you know the exact steps to enable streaming in RabbitMQ? If we know them, then we can check how to add more automations to the container in order to allow this configuration in an easy manner.

**Comment by soelgary** [comment]
@skyrain 

I came here with the same question, but was able to figure it out. There are two streams plugins you can enable: `rabbitmq_stream` and `rabbitmq_stream_management`. You will also need to open the streams port in the service. I did this using `service.extraPorts`:

```
extraPorts:
    - name: streams
      port: 5552
      targetPort: 5552
```

Hopefully others find this useful.

**Comment by javsalgar** [comment]
Thank you for sharing!
