### ISSUE TITLE
StatefulSet with architecture: high-availability should not set volume tmp emptyDir: {}

### ISSUE THREAD

**Issue by chelope** [bitnami/charts#9339]
### Name and Version

bitnami/memcached 6.0.5

### What steps will reproduce the bug?

I've installed in a kubernetes cluster the memcached helm using a values.yml with the values architecture = high-availability and persistence storage enabled. With this configuration the statefulset pod is created with volumeClaimTemplates "data" that would be enough, but the statefulset pod is created with a local storage "tmp" too.

[memcached.yml](https://github.com/bitnami/charts/files/8211497/memcached.txt)

### Are you using any custom parameters or values?

This is the values.yml

[values.yml](https://github.com/bitnami/charts/files/8211509/values.yml.txt)

### What is the expected behavior?

The local storage tmp shouldn't be created.

### What do you see instead?

In the kubernetes cluster I see this warning

Pod is blocking scale down because it has local storage

**Comment by juan131** [comment]
Hi @chelope 

> Pod is blocking scale down because it has local storage

The "tmp" storage is an "emptyDir" volume as you can check in the link below:

- https://github.com/bitnami/charts/blob/master/bitnami/memcached/templates/statefulset.yaml#L237

As you can see in the [Kubernetes documentation](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) these volumes exist as long as the Pod exists and they're delete once the Pod is removed for whatever reason. Therefore, this kind of volumes should not affect scaling the solution.

> The local storage tmp shouldn't be created.

Could you please elaborate the reasons why it shouldn't be included?

**Comment by chelope** [comment]
Hi @juan131 

I think this empy dir is affecting the scale down in kubernetes cluster since the GKE is showing the following message

![image](https://user-images.githubusercontent.com/2678164/157455031-c6b4127c-2eb0-4163-8ea7-29f14b502db9.png)

![image](https://user-images.githubusercontent.com/2678164/157455211-1cdfbfda-0c09-4e82-918b-bb3929a45b77.png)

This is the log

![image](https://user-images.githubusercontent.com/2678164/157455430-638eb7aa-12d0-419b-a59b-d23aa8e491ab.png)

**Comment by juan131** [comment]
Hi @chelope 

The problem isn't related with the "emptyDir" volume but the PVC that's created using the volumeClaimTemplates below:

- https://github.com/bitnami/charts/blob/master/bitnami/memcached/templates/statefulset.yaml#L242

Depending on the StorageClass you're using (customizable via [this parameter](https://github.com/bitnami/charts/blob/master/bitnami/memcached/values.yaml#L457)), your cluster could use one kind of volumes or another. It's very likely that you're using a local volume provisioner available in your cluster to create the required volumes instead of a [gcePersistentDisk](https://kubernetes.io/docs/concepts/storage/volumes/#gcepersistentdisk).

**Comment by juan131** [comment]
Thanks for sharing this workaround! Can you confirm that the annotations works to solve the issue?

**Comment by chelope** [comment]
Hi @juan131 

Just to confirm that the issue is solved adding the annotation "cluster-autoscaler.kubernetes.io/safe-to-evict."

**Comment by javsalgar** [comment]
Thanks for confirming!
