### ISSUE TITLE
Add a new shadowsocks chart

### ISSUE THREAD

**Issue by longkai** [bitnami/charts#9581]
### Name and Version

bitnami/shadowsocks

### What is the problem this feature will solve?

[Shadowsocks](https://github.com/shadowsocks) is a fast tunnel proxy that helps you bypass firewalls.

It's nice if bitnami have one and I'm delight to do the contribution!

### What is the feature you are proposing to solve the problem?

Add the new chart to the bitnami.

**Comment by rafariossaa** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container images are not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR (once analyzed the request and agreed to be included). If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.

**Comment by longkai** [comment]
OK, I find the common library is really useful and have used in my company projects.

I will have a try for the open source chart.
