### ISSUE TITLE
autoscaling HPA doesn't work after enabling it in MongoDB yaml files

### ISSUE THREAD

**Issue by DevBey** [bitnami/charts#9585]
### Name and Version

bitnami/mongodb

### What steps will reproduce the bug?

1. in eks 1.21.2 tried deploying mongodb using bitnami/mongodb latest version chart
2.  tried using `kubectl get hpa` doesn't show anything.
3.  tried kubectl autoscale sts mongodb --min=1 --max=5 --cpu-percent=20 which start a HPA for the particular statefulsets.

### Are you using any custom parameters or values?

autoscaling:
  enabled: true    
  replicas:
      min: 1
      max: 3
    
  targets:
    cpu: 40
    memory: 40

### What is the expected behavior?

1. would have expected this to be automatically started it HPA autosclar.
2.  `kubectl get hpa` should show the HPA for the statefulset

### What do you see instead?

nothing

### Additional information

cluster autoscalr is already deployed which is scaling the nodes automatically, but HPA is not working even if I set the cpu percetage at 10 percentage on a 2 core node and bombard it with tremendous amount of query during stress testing.

**Comment by migruiz4** [comment]
Hi @DevBey,

I'm sorry but the `bitnami/mongodb` chart does not have support for `autoscaling.*` values, as you can see in the [README.md](https://github.com/bitnami/charts/blob/master/bitnami/mongodb/README.md).

If you would like to contribute to our charts, feel free to send a PR adding the HorizontalPodAutoscaler template and values. We will be happy to review it and help with anything needed.

**Comment by migruiz4** [comment]
> when deploying MongoDB on a replica set using this chart, the main point is this to scale dynamically, but as you said it can't scale with externalaccess=true, but we have to use Loadbalancer right, for external access, is there any way around this ??

Not an issue with the service type, but with MongoDB design.

When the MongoDB client connects to a node, it may happen that the MongoDB server redirects to another node where the data is located, and the client will establish a new connection with that node.

If that address is internal, the client won't be able to connect to that second node. That is why with `externalAccess.enabled=true` an individual service for each MongoDB pod is created, so each node has an externally resolvable IP/DNS.

In addition, if your goal is to handle more connections in higher stress times, it might be better to configure vertical autoscaling instead of autoscaling horizontally. If you see any bottlenecks in CPU or memory during high-stress moments, then do some horizontal scaling up manually.

I haven't tried it personally, but that would be my recommendation if you are looking for autoscaling to save resources.

> Currently while even doing manually scaling the pods fail to initialize, I think this might also be because of external access issue.

To scale up manually with `externalAccess.enabled=true`, you have to do it using `helm upgrade` setting a new value for `replicaCount`. Scaling the Statefulset does not create the service for the new pods, so you have to update the chart to increase the number of nodes.

> what happens to the PVC when pods scale in, from what I understand they are not deleted, but whenever scale-out 
happens on HPA, would it again use the save PVC or create new ??

PVCs are persisted and reused by the same node after a node is scaled up/down.

**Comment by DevBey** [comment]
Hi @migruiz4,

yep, thanks, scaling up is definitely working after using the helm upgrade command, which definitely means that's automatic HPA is impossible as of now. 

my observation are->
1. HPA currently can't work with helm MongoDB because of an external load balancer issue, which is quite sad.
2. the workaround to automatic upscaling is either using carpenter or cluster autoscale which can autoscale the nodes while calling a helm upgrade with a revised set of replicas.
3. while scaling down there are tonnes of issues if helm upgrade is done to scale in the replica set, the process which were already accessing the load balancer URL connection started failing intermittently, which I suppose is because of removal of load balancer URL from the corresponding replica set while scaling down.
4.  the most important observation is this workaround for autoscaling is a very astute use of limits and requests for the replica set containers, as that would help the cluster autoscaler in intelligent autoscaling of nodes.
5. there is also this final problem of crashbackloop while autoscaling sometimes, which I have not quiet gotten to the bottom of.

**Comment by DevBey** [comment]
Hi @migruiz4,

I think we can close this issue down, thanks for all the help.
