### ISSUE TITLE
Add a new helm-exporter chart

### ISSUE THREAD

**Issue by rubyalwaystaken** [bitnami/charts#9677]
### Name and Version

bitnami/helm-exporter

### What is the problem this feature will solve?

[This project](https://github.com/sstarcher/helm-exporter) exports helm release, chart, and version statistics in the prometheus format

### What is the feature you are proposing to solve the problem?

Add a new bitnami chart using sstarcher/helm-exporter

### What alternatives have you considered?

There does not seem to exist any known organisation maintaining this project as a helm chart

**Comment by carrodher** [comment]
Thanks for your suggestion! We will check it internally and evaluate the feasibility but due to limited resources that could take some time.

If you want to contribute with the chart do not hesitate to open a PR and we will review it. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#adding-a-new-chart-to-the-repository) you can find the requirements and scaffolding to create a Helm Chart following the Bitnami guidelines. If the container images are not part of the Bitnami catalog at this moment, we can work on that part while we review the Chart PR (**once analyzed the request and agreed to be included**). If you want some examples, there are recent additions like MetalLB, ASP.net, Grafana Operator, kubernetes-event-exporter, etc that were based on PRs from users.
