### ISSUE TITLE
[bitnami/thanos] Deploy receive with replication factor higher than 1

### ISSUE THREAD

**Issue by saisree-philips** [bitnami/charts#9707]
### Name and Version

bitnami/thanos

### What is the problem this feature will solve?

To be able to run receive with replication factor of 3 (anything higher than 1), hashring config has to be provided so that receiver knows where to forward the request to. With the current version of helm it is not possible to have this in combination with autoscaling of pods. When the receive pods are scaled automatically, the hashring config has to be updated as well.  Using a receive controller like [this](https://github.com/observatorium/thanos-receive-controller) will solve the hashring update problem with autoscaling.

### What is the feature you are proposing to solve the problem?

Deploy receiver with higher replication factor and autoscaling thus improving system resilience and reliability.

**Comment by joancafom** [comment]
Hi @saisree-philips 

Thanks for opening up this issue. I will take a look into it with the team and provide you with updates soon 😁

**Comment by joancafom** [comment]
Hi @saisree-philips 

As far as I understand, in order to solve this, we would need to add a new `bitnami/thanos-receive-controller` container to our catalog. Then, this could be used together with the chart to properly update the hashring config accordingly in this specific scenario. However, we are not currently considering adding new containers to our catalog and, unfortunately, this would not be an option.

If there is any other alternative that can be applied to the chart/current application, please feel free to send a PR. The team will be more than happy to review it.
