### ISSUE TITLE
[bitnami/etcd] Recreated pod doesn't attach to recent cluster

### ISSUE THREAD

**Issue by q-markwilliams** [bitnami/charts#9950]
### Name and Version

bitnami/etcd 3.5.4-debian-10-r0

### What steps will reproduce the bug?

Using Helm chart & Kubernetes v1.21.10 (GKE)
Will attach install values for the helm chart in comment below

### Process:

Perform a fresh install of the etcd chart, wait until the cluster is healthy and then run the following commands:
`kubectl delete pvc data-etcd-2` 
`kubectl delete pod etcd-2`

### What is the expected behavior?

Pod to rejoin the cluster successfully and go healthy

### What do you see instead?

etcd pod hangs with
```
etcd 14:05:27.22 
etcd 14:05:27.22 Welcome to the Bitnami etcd container
etcd 14:05:27.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
etcd 14:05:27.23 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
etcd 14:05:27.23 
etcd 14:05:27.23 INFO  ==> ** Starting etcd setup **
etcd 14:05:27.27 INFO  ==> Validating settings in ETCD_* env vars..
etcd 14:05:27.27 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
etcd 14:05:27.27 INFO  ==> Initializing etcd
etcd 14:05:27.27 INFO  ==> Generating etcd config file using env variables
etcd 14:05:27.29 INFO  ==> There is no data from previous deployments
etcd 14:05:27.29 INFO  ==> Bootstrapping a new cluster
etcd 14:05:27.31 INFO  ==> Obtaining cluster member ID
etcd 14:05:27.32 INFO  ==> Starting etcd in background
```

### Additional information

Raising here as I believe it can be resolved within the boot scripts.
It seems like the scripts assume they're booting to a new cluster, maybe ETCD_INITIAL_CLUSTER_STATE can be driven from cluster state (e.g. are the other nodes healthy?) instead of relying of the Helm provided value.
Let us know thoughts

**Comment by joancafom** [comment]
Hi @q-markwilliams 

> It seems like the scripts assume they're booting to a new cluster, maybe ETCD_INITIAL_CLUSTER_STATE 

Taking a look at the scripts, the `ETCD_INITIAL_CLUSTER_STATE` variable is only taken into account on there is no previous data from previous deployments:

https://github.com/bitnami/bitnami-docker-etcd/blob/8e1c46d68bc8c3b0bf69408f4df14ec99fe41dad/3.5/debian-10/rootfs/opt/bitnami/scripts/libetcd.sh#L551-L555

This makes sense to me, and I think the issue here could be related to the scenario you are trying to reproduce. Not only are you simulating a failover in the pod, but also data loss (by deleting the PVC). Instead, could you please try to only delete the pod and see if it re-joins the cluster successfully?
