### ISSUE TITLE
Please upgrade nginx-ingress to fix invalid protocol error

### ISSUE THREAD

**Issue by floek** [bitnami/charts#9991]
### Name and Version

bitnami/nginx-ingress-controller:9.1.26

### What steps will reproduce the bug?

Add nginx.ingress.kubernetes.io/from-to-www-redirect:true

--> Redirect has an invalid location

It is already fixed in upstream.

### What is the expected behavior?

```
HTTP/2 308
date: Sat, 30 Apr 2022 06:39:56 GMT
content-type: text/html
content-length: 164
location: https://www.domain.de
```

### What do you see instead?

```
HTTP/2 308
date: Sat, 30 Apr 2022 06:39:56 GMT
content-type: text/html
content-length: 164
location: nil://www.domain.de
```

### Additional information

https://github.com/kubernetes/ingress-nginx/pull/8468
https://github.com/kubernetes/ingress-nginx/issues/8462

**Comment by fmulero** [comment]
Thanks for letting us know. The fix is available in version 1.2.0, that version was already detected by our automated test & release pipeline but there are some changes in the upstream code that requires some manual changes on our side in order to adapt the mentioned pipeline.

We will update this thread once released the new version.

**Comment by Mauraza** [comment]
Hi @floek,

Version 1.2.0 was released. Could you confirm that the upstream issue was fixed?

**Comment by floek** [comment]
Hi @Mauraza,

its fixed. Thank you.
