### ISSUE TITLE
Please release a version with 1.2.0 nginx ingress controller to fix CVE-2021-25745

### ISSUE THREAD

**Issue by dmitry-bakaleinik-sap** [bitnami/charts#9993]
### Name and Version

bitnami/nginx-ingress-controller

### What is the problem this feature will solve?

It will fix CVE-2021-25745 described at https://github.com/kubernetes/ingress-nginx/issues/8502

The version 1.2.0 fixes this vulnerability

### What is the feature you are proposing to solve the problem?

Release a new version of nginx-ingress-controller pointing to the 1.2.0 release.

**Comment by carrodher** [comment]
Thanks for letting us know, the new version was already detected by our automated test & release pipeline but there are some changes in the upstream code that requires some manual changes on our side in order to adapt the mentioned pipeline.

We will update this thread once released the new version.

**Comment by Mauraza** [comment]
Hi @dmitry-bakaleinik-sap,

The new version of bitnami/nginx-ingress-controller was released and the chart was updated 
https://github.com/bitnami/charts/blob/f4bec9a7ea5fa40eb085eb92c7194b9e88175b9e/bitnami/nginx-ingress-controller/values.yaml#L45-L48
